### ISSUE TITLE
Warnings in --prod mode

### ISSUE THREAD

**Issue by teland94** [stephanrauh/ngx-extended-pdf-viewer#100]
When I built the app in prod mode, I see many warnings in console:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/fFPvVBH/Capture.png" alt="Capture" border="0"></a>

**Comment by stephanrauh** [comment]
You're i18n translation files are missing. Check the `[useBrowserLocale]` flag, the `[language]` setting and if you've copied the language files either to the assets folder or into the `index.html` file.

**Comment by stephanrauh** [comment]
Please report back when you've managed to solve the issue, so I can close the ticket.

**Comment by teland94** [comment]
I set [useBrowserLocale]="true", this is not issue of missing translation files

**Comment by stephanrauh** [comment]
I'm cueless. Would you mind to send me a reproducer? There are so many ways to configure the PDF viewer, it's hard to provide a correct diagnosis remotely, without seeing your source code.

**Comment by teland94** [comment]
Here is a code that I used in prod build:
`<ng-container *ngIf="pdfDocData">
  <ngx-extended-pdf-viewer [base64Src]="pdfDocData"
                           [useBrowserLocale]="true"
                           [filenameForDownload]="filenameForDownload"
                           (pagesLoaded)="pagesLoaded()"
                           [showSidebarButton]="showSidebarButton"
                           [showOpenFileButton]="false"
                           [showPrintButton]="false"
                           [showBookmarkButton]="false"
                           [showPresentationModeButton]="false"></ngx-extended-pdf-viewer>
</ng-container>`

**Comment by stephanrauh** [comment]
That doesn't look much different from the showcase. I'd suggest you clone the showcase, compile it and check if the warnings are still there. I suppose that takes less than ten minutes.

If the warnings are gone, you can compare the showcase to your project. My guess: the language files aren't copied to the assets folder. You can see that in the network tab of your browser's debugging tools. Are there any 404 errors?

Here's the URL of the showcase: https://github.com/stephanrauh/extended-pdf-viewer-showcase 
(that's the same code also running on https://pdfviewer.net)

**Comment by stephanrauh** [comment]
I'll close the ticket because it doesn't occur on my projects. I didn't hear from you, so maybe you've managed to solve the bug yourself? If so, I'd like to hear from you. Maybe the documentation needs to be improved, or something like that.
