### ISSUE TITLE
PDF does not render in chromium browser

### ISSUE THREAD

**Issue by WilsonGodoi** [stephanrauh/ngx-extended-pdf-viewer#1000]
PDF does not render in chromium browser, there is a error in console.
The error below appears on the console.
Uncaught SyntaxError: Unexpected token .

ngx-extended-pdf-viewer version 10.5.0

Chromium version 75.0.3770.100

![pdf-error](https://user-images.githubusercontent.com/35606937/139240279-846ea4d5-1fd9-4941-b37a-2b0e1827c461.png)

**Comment by stephanrauh** [comment]
Your bugfix has shipped with version 11.0.0-alpha.1.
