### ISSUE TITLE
FR: new feature toggle: [wheel-action] to zoom without holding down the ctrl/meta key

### ISSUE THREAD

**Issue by barnewsapp** [stephanrauh/ngx-extended-pdf-viewer#1007]
**Is your feature request related to a problem? Please describe.**
We want to be able to use the mouse wheel to zoom without holding down the ctrl/meta key. 
This is useful in single page mode, and maybe other cases. 

**Describe the solution you'd like**
Add a feature toggle to control the mouse-wheel action. 
E.g.  [wheel-action]="'pagination' | 'zoom'"?

If wheel-action is not specified, use 'zoom' on single page mode and pagination/scroll in other modes.

Thanks

**Comment by stephanrauh** [comment]
I think it's better to use the word "scroll" instead of "pagination". Scrolling also works in single-page mode.

**Comment by stephanrauh** [comment]
The feature is going to land with version 11.1.0 soon.

**Comment by stephanrauh** [comment]
The bugfix has landed with version 11.1.0.

**Comment by barnewsapp** [comment]
Thanks @stephanrauh 
This works perfectly. 

After being busy with other projects I have now restarted my work on the relative coords feature. 
I'll keep you updated.

**Comment by stephanrauh** [comment]
@barnewsapp The Mozilla team have implemented a decent pinch algorithm now. As a side effect, it seems I have to remove the `[wheelAction]` attribute because it doesn't work properly with pdf.js 3.3.

**Comment by gelsas** [comment]
How can I now change the behavoir so I can set my mousewheel to zoom in and out as default without clicking the control key?
