### ISSUE TITLE
Programmatically access the layers? 

### ISSUE THREAD

**Issue by ShotiQ** [stephanrauh/ngx-extended-pdf-viewer#1012]
**Is your feature request related to a problem? Please describe.**
Had a hard time to show or hide layers programmatically. What i currently did is to access the html elements directly.

**Describe the solution you'd like**
I hope to the list of pdf layers, and enable disable some of them by its layer name.

Thank you so much for this wonderful library

**Comment by stephanrauh** [comment]
Sounds like a good idea!

**Comment by stephanrauh** [comment]
@ShotiQ I'm confused by your remark you were able to access the layers vial HTML. I've just checked my layer demo. There's the canvas layer (i.e. the PDF file itself) and an annotation layer. When I toggle one of the layers in the sidebar, the canvas is redrawn. Are we talking about the same thing?

**Comment by stephanrauh** [comment]
I've implemented the programmatic access and documented is here: https://pdfviewer.net/extended-pdf-viewer/layers.

Enjoy!
Stephan
