### ISSUE TITLE
single page mode

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1015]
though i am using single page mode but still all pages rendering in dom which making webpage laggy. no use of single page mode for performance large pages like 33000 pages. zoom in, out performing super slow. i am at page 1.
![Screenshot (90)](https://user-images.githubusercontent.com/82865585/141507461-4df5099e-ff0b-4cc6-a22b-8188883e1cd7.png)

**Comment by stephanrauh** [comment]
Yes, that's true. That's something I can't solve easily. But maybe the pdf.js team has already solved the problem. Please update to version 11.0.0-alpha.x, use the "bleeding edge" branch of pdf.js, and use the brand-new `[scrollMode]="3"`.

I haven't tested it yet, but I suspect they don't add 33.000 empty pages to the DOM. Can you confirm that?

**Comment by aysha-statvalu** [comment]
fixed in v11 bleeding edge now rendering only one page thank you.
![Screenshot (91)](https://user-images.githubusercontent.com/82865585/141608073-ba47a4ac-c4b1-411a-9198-db10de00718a.png)

**Comment by stephanrauh** [comment]
Starting with version 11.0.0-alpha.3, the single-page mode uses the new `[pageMode]="3"`, provided you're running pdf.js 2.12 or higher.
