### ISSUE TITLE
sidebar ngx-perfect-scrollbar issue

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1017]
sidebar showing default scrollbar not  ngx-perfect-scrollbar.
![Screenshot (92)](https://user-images.githubusercontent.com/82865585/141778491-1aba7ea5-7f58-40f0-97b1-c580c99ff661.png)

**Comment by stephanrauh** [comment]
The demo https://pdfviewer.net/extended-pdf-viewer/perfect-scrollbar shows how to activate the perfect scrollbar. See the TypeScript tab. I suppose the same recipe also works for the sidebar.

**Comment by stephanrauh** [comment]
I've just tested the idea. It works:

```typescript
    const sidebar = document.querySelector('#thumbnailView') as HTMLElement;
    if (sidebar) {
      this.scrollbar = new PerfectScrollbar(sidebar, this.config);
    }
```
