### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by Luisfermp18** [stephanrauh/ngx-extended-pdf-viewer#102]
Hi there,

At first, thank for the component, it's very useful, but I have a little problem with the preventDefault when pinch over pdf viewer container. Always when I'm pinching, the console show me the following error:

![Captura de pantalla 2019-07-05 a las 12 20 43](https://user-images.githubusercontent.com/5788484/60716313-5592d700-9f1f-11e9-9e4e-05a642e0cdfc.png)

And when I press over viewer.js:2286 the sources show me this:

![Captura de pantalla 2019-07-05 a las 12 15 12](https://user-images.githubusercontent.com/5788484/60716376-8410b200-9f1f-11e9-80cc-78a55a155280.png)

Obviously, I'm doing something wrong, could you help me to solve this. 

Thank you very much.

**Comment by stephanrauh** [comment]
How can I reproduce the bug? Does it occur on https://pdfviewer.net, too? That's make things easier.

I can only guess: you're using Google Chrome?

**Comment by stephanrauh** [comment]
I'll close the ticket because I don't know how to reproduce the bug.
