### ISSUE TITLE
add support for counting pdf pages

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1020]
please add support to count pdf pages. Our requirement is to count pdf pages for 10000 pdf documents before uploading to the cloud please add support for that.

**Comment by stephanrauh** [comment]
You can use the `(pdfLoaded)` event to learn about the number of pages. See the live demo at https://pdfviewer.net/extended-pdf-viewer/pages-loaded.

**Comment by aysha-statvalu** [comment]
for 10000 records not possible at all. Please add a separate method for this which takes an array of files and returns page count. Maximum doc processing company charges money based on how many pdf pages are processed.

**Comment by stephanrauh** [comment]
No, I won't do that. That's obviously the job of a different library. As it happens, there are several npm libraries counting the pages of a PDF file. Just google it!
