### ISSUE TITLE
single page mode giving black screen

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1028]
I again tried to load the pdf document having 13000 pages its loaded fine but I got a black screen some pages were not loaded properly. you can produce this if you follow below

first, try to load that 13000-page pdf I sent you before and on page load as quickly as you can click on the next page button you will see this black screen.

![Screenshot (95)](https://user-images.githubusercontent.com/82865585/141941582-0ac85447-3018-4bc7-b57b-59c1eb2c1e3f.png)

**Comment by stephanrauh** [comment]
Disable the buttons by default. Granted, that's only a work-around, but it should solve the problem for your users.

**Comment by aysha-statvalu** [comment]
<ngx-extended-pdf-viewer [src]="src" [showToolbar]="false" [useBrowserLocale]="true" [textLayer]="false"
        [handTool]="false" [contextMenuAllowed]="false" [showZoomButtons]="true" [showPresentationModeButton]="true"
        backgroundColor="#fff" [scrollMode]="scrollMode" [zoom]="'page-fit'" [showBorders]="false" [(page)]="currPage"
        [(sidebarVisible)]="sidebarOpen" [(rotation)]="rotation" (pagesLoaded)="onPagesLoaded($event)"
        (progress)="onProgress($event)" [class.hide]="isLoading">
    </ngx-extended-pdf-viewer>

i removed [customFreeFloatingBar] still same blackscreen what to do?

**Comment by stephanrauh** [comment]
I'm afraid I can't reproduce the bug. Quite the contrary, I'm surprised how fast the document shows. Plus, the pagination buttons are inactive until the document has been loaded. That's several seconds before the page is rendered. When I hit one of the pagination buttons, the requested page shows a lot later, but it does show reliably.

I've tested this with the current Firefox 91.3.0 ESR on MacOS.

**Comment by aysha-statvalu** [comment]
did you check with that 33200-page pdf I sent you before? continuously 2 3 times you can check after that you will notice if not maybe it's my system issue. I tested on chrome. [scrollMode]="0" should be zero.

**Comment by stephanrauh** [comment]
I believe the improvement https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1055 fixes this issue, too.
