### ISSUE TITLE
progress not coming properly

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1029]
when I fetch a pdf file from HTTP post request the is progress always coming 100% while without HTTP request if I open pdf file locally then it shows progress from 0 to 100 not only one result several results like 1%,11%,55%, so like this, it should come while fetching pdf from an HTTP request, I am using base64 string.

**Comment by stephanrauh** [comment]
Are you using this algorithm?

```typescript
    this.httpClient.post(
      '/document_upload/download_output_files/',
      formdata)
      .subscribe((res: any) => {
        const byteCharacters = atob(res['res_data']['encoded_string']);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }

        const byteArray = new Uint8Array(byteNumbers);
        this.src = new Blob([byteArray], { type: "application/pdf" });
      });
  
```

If so, that's not surprising. The PDF viewer doesn't have an opportunity to track the progress because it's not involved in loading the PDF file. The PDF viewer can only track the progress if you pass it an URL.

**Comment by aysha-statvalu** [comment]
I pass it as an URL not working

let objectUrl = URL.createObjectURL(new Blob([byteArray], { type: "application/pdf" }));
this.src = this.sanitizer.bypassSecurityTrustResourceUrl(objectUrl);

what to do?

**Comment by stephanrauh** [comment]
Oh, it is working. The progress bar indicates the load progress. If you load the BLOB beforehand and pass it as a data URL, the PDF viewer doesn't spend much time loading the file. It's already in memory, so the progress bar jumps to 100% after roughly zero milliseconds.
