### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1030]
initially i set `currentZoomFactor: any = 'page-fit';` then i want to get current zoom value

`(currentZoomFactor)="updateZoomFactor($event)"`

my method to set initial zoom value
```typescrpt
updateZoomFactor(zoom: number) {
    if (this.currentZoomFactor === 'page-fit') {
      setTimeout(() => {
        this.currentZoomFactor = Math.floor(zoom * 100);
      }, 100);
      console.log("zoom",this.currentZoomFactor);
    }
  }
```
but error is coming ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '110'. Current value: '110.00000000000001'

also i did an alternativeway 

i set zoom value  `currentZoomFactor: any = 'page-fit'; `
```typescrpt
zoomin() {
    this.currentZoomFactor += 5;
  }

  zoomout() {
    this.currentZoomFactor -= 5;
  }
```
while firing zoomin,zoomout error is coming when zoom value is 110
but error is coming ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '110'. Current value: '110.00000000000001'

**Comment by aysha-statvalu** [comment]
fixed this issue with change detection strategy onpush just add this line

@Component({
  selector: 'app-preview-pdf',
  templateUrl: './preview-pdf.component.html',
  styleUrls: ['./preview-pdf.component.scss'],
  providers: [],
  changeDetection: ChangeDetectionStrategy.OnPush, //this line
  animations: [
    trigger('fade', [
      state('void', style({ opacity: 0, visibility: 'hidden' })),

      transition('void <=> *', animate(400))
    ])
  ]
})

**Comment by stephanrauh** [comment]
No, that's not a bug fix. It's just hiding the bug by a piece of band-aid.

**Comment by stephanrauh** [comment]
Please update to version 10.0.0-alpha.5. If everything works as I intend it to be, it fixes the rounding difference bug.
