### ISSUE TITLE
Highlight Text and scroll to that text in PDF programmatically

### ISSUE THREAD

**Issue by chetan592** [stephanrauh/ngx-extended-pdf-viewer#1034]
Its not bug but request to help me figure out how I can build the following functionality with ngx-extended-pdf-viewer

In current use case we show PDF to user. User can select the text from PDF. Once he selects any text (word/line) from PDF we store it. For getting text we are using window.getSelected(). 
Now when user wants to check from where is that text copied from PDF, we have component where user can see all previously copied texts , user can click on any of the text and then what we want to build is to show user where is copied it( scroll PDF to that text and highlight its exact position)
For that I think may be we will need coordinates of selected/copied text so next time we can scroll to it and highlight that text.

Please help me with this. How I can do this with this library. How I can scroll to specific text in the pdf and highlight that one.

**Comment by stephanrauh** [comment]
Have a look at the pdf_find_controller.js:

![image](https://user-images.githubusercontent.com/3045767/142477315-99caf34a-e4c1-4b8a-8169-9ffce94f155b.png)

At the moment, I don't have a clue what "element" is, but I'm pretty sure it's the key to success. The class pdf_find_controller isn't that convoluted, I guess you can find out with some persistence and the help of the debugger. I suppose you "just" have to adapt the code.
