### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1035]
pdf file is not opening throwing the error Window is not defined. Loading screen only showing. Major Issue please fix, help.
[Cyber_Security_C.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7563280/Cyber_Security_C.pdf)
![Screenshot (97)](https://user-images.githubusercontent.com/82865585/142427775-029ca093-020d-405c-8b74-9ef5e510c6ee.png)
 please use this code, convert it to base 64 encoded string

```
const byteCharacters = atob(res);
    
    const byteNumbers = new Array(byteCharacters.length);
    for (let i = 0; i < byteCharacters.length; i++) {
      byteNumbers[i] = byteCharacters.charCodeAt(i);
    }
    
    const byteArray = new Uint8Array(byteNumbers);
    this.src = new Blob([byteArray], { type: "application/pdf" });
```

**Comment by stephanrauh** [comment]
Please update to version 10.0.0-alpha.5. I believe it fixes the bug.

**Comment by aysha-statvalu** [comment]
thank you solved, but got another issue can you update pdf.js bleeding version to 10.0.0-alpha.5. [scrollMode]="3" not working.

**Comment by stephanrauh** [comment]
The bug-fix was incomplete. It has improved with version 10.0.0-alpha.6.

**Comment by aysha-statvalu** [comment]
can you fix this bug in version 11 i want to use updated bleeding edge, the scrollmode=3

**Comment by aysha-statvalu** [comment]
i updated to version 11.0.0-alpha.8, i think this issue is fixed in this version

**Comment by stephanrauh** [comment]
Hooray!
