### ISSUE TITLE
single-page mode is broken on first load

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1040]
Ayesha (@aysha-statvalu) reports in #1035 that version 10.0.0-alpha.5 doesn't support the new `[scollMode]="3"`.

**Comment by stephanrauh** [comment]
The bug-fix has shipped with version 10.0.0-alpha.6.

**Comment by aysha-statvalu** [comment]
Thank you will update on Monday and will check working or not.
