### ISSUE TITLE
Option to search/find in a particular page

### ISSUE THREAD

**Issue by chetan592** [stephanrauh/ngx-extended-pdf-viewer#1041]
**Is your feature request related to a problem? Please describe.**
I want to highlight the words from specific page. In find we highlight results from all PDF pages but can we limit that to particular page.

**Describe the solution you'd like**
User can enter text and target page number to search for. So when user hit button I want to find that text in provided page only.

**Comment by stephanrauh** [comment]
I've started to work on this yesterday. See #832. If you're using the "bleeding edge" branch of version 10.0.0-alpha.7, the feature is already available to you (apart from some rough edges that need to be smoothed). 

You've also suggested to use an arbitrary range of pages. Do you have a usecase for that, or is it enough to limit the search range to the current page?

**Comment by chetan592** [comment]
Yes, I have use case to find text in any page provided by user and not just current page.

**Comment by stephanrauh** [comment]
Yes, it's possible. It's just a bit cumbersome because I've implemented the programmatic search API in such a way it forces me to add input fields for the search range. On the other hand, this may be useful for some developers, so I guess it's OK to go the extra mile.

**Comment by stephanrauh** [comment]
I've published an early prototype of the "find on current page only" feature on https://pdfviewer.net. Just make sure you select pdf.js 2.12, because I haven't ported the feature to the default branch yet. It's not perfect yet, but I think it's already useful.

**Comment by stephanrauh** [comment]
Quick update: I've implemented a "range" input field:

- You can enter a single page number,
- you can enter an arbitrary number of comma separated page numbers,
- and you can enter page ranges.

For example, "1,2,4, 10-20, 25" is a valid input.

The feature is going to be part of the next version I'll publish.

**Comment by stephanrauh** [comment]
The new feature is going to ship with version 11.0.0-alpha.13 today.

**Comment by stephanrauh** [comment]
Note that I've implemented the feature in the "bleeding edge" branch only. Recently, the pdf.js team has started to publish a new version every three or four months, so it's probably just a matter of two months until the feature migrates to the default branch.
