### ISSUE TITLE
update bleedng edge for 10.0.0-alpha.6

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1042]
in 10.0.0-alpha.6 version bleeding-edge scrollmode="3" not working. I started using the old input property pageViewMode="single" but the problem is though it's showing one page at a time but its rending all pages means if a pdf have 33000 pages rather rendering single page on dom its rendering all pages.

**Comment by aysha-statvalu** [comment]
please help I want that feature in my project for opening large pdf which have 33000 pages.

**Comment by aysha-statvalu** [comment]
bleeding-edge scrollmode="3" not working please update help

**Comment by stephanrauh** [comment]
It works on the showcase (https://pdfviewer.net/extended-pdf-viewer/page-view-mode). What's the problem?

![image](https://user-images.githubusercontent.com/3045767/143679734-219f2348-c012-4c6b-928d-3efb97cc7e98.png)

**Comment by aysha-statvalu** [comment]
there is a difference between pageviewmode=''single'' , scrollmode-'3'. while using bleeding edge scrollmode 3 its only rendering single div element per page but in pageviewmode  though we are setting single view but its rendering all pages as div in dom. in version 11 scrollmode 3 working but in version 10 scrollmode 3 is not working.

**Comment by aysha-statvalu** [comment]
all pages rendering as div in DOM in pageviewmode=''single''.
![pageviewmode](https://user-images.githubusercontent.com/82865585/143732241-e3b87238-de6e-4346-bafa-979f3e62795d.png)

**Comment by aysha-statvalu** [comment]
in scrollviewmode=3 only one div rendering per page which is great for performance.
![scrollmode-3](https://user-images.githubusercontent.com/82865585/143732284-9ef5461d-5873-4c15-a32c-5ec012eebd35.png)

**Comment by aysha-statvalu** [comment]
scrollviewmode=3 is working perfectly in version 11 alpha x but not working in version 10 alpha 6. Before I used version 11 but I got an error Window is not defined then you suggested & I degrade the version to 10 alpha 6 now scrollmode 3 is not working.

**Comment by aysha-statvalu** [comment]
i used this code

<ngx-extended-pdf-viewer *ngIf="!browserViewer" [src]="src" [showToolbar]="false" [useBrowserLocale]="true" [textLayer]="textRender" [handTool]="false" [contextMenuAllowed]="false" [showZoomButtons]="true" [showPresentationModeButton]="true" backgroundColor="#fff" [scrollMode]="scrollMode" [(zoom)]="currentZoomFactor" [showBorders]="false" [(page)]="currPage" pageViewMode="single" [spread]="'off'" (currentZoomFactor)="updateZoomFactor($event)" [(sidebarVisible)]="sidebarOpen" [(rotation)]="rotation" (pagesLoaded)="onPagesLoaded($event)" (progress)="onProgress($event)" (pageRendered)="onPageRendered($event)" [class.hide]="isLoading">
    </ngx-extended-pdf-viewer>
![Screenshot (5)](https://user-images.githubusercontent.com/82865585/143811469-48db8a63-f506-4ca0-aaeb-1b12a8f744cc.png)
![Screenshot (6)](https://user-images.githubusercontent.com/82865585/143811471-b1143cc6-5d6b-46d6-b451-f6f3708f065f.png)

**Comment by stephanrauh** [comment]
It's hard to see what's going wrong. `[class.hide]="loading"` might be a problem. The PDF viewer often crashes if it's invisible when it's initializing. Another idea: does the problem vanish if you don't display a BLOB, but use a simple URL?

**Comment by aysha-statvalu** [comment]
but scrollmode=3 working fine in version 11 but not working version 10

**Comment by aysha-statvalu** [comment]
i degraded my version to 10 that why this issue is coming.

**Comment by stephanrauh** [comment]
I see. I thought the version number was a typo. No, I won't update version 10. I don't have enough time to maintain two version simultaneously. I think it's better to focus on version 11, so I can publish the final release earlier.

**Comment by aysha-statvalu** [comment]
yes, my issue is solved thank you updated to version 11.
