### ISSUE TITLE
 height of the PDF viewer widget is zero pixels. 

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1043]
ngx-extended-pdf-viewer.js:1487 The height of the PDF viewer widget is zero pixels. Please check the height attribute. Is there a syntax error? Or are you using a percentage with a CSS framework that doesn't support this? The height is adjusted automatedly.

```
<ngx-extended-pdf-viewer *ngIf="!browserViewer" [src]="src" [showToolbar]="false" [useBrowserLocale]="true" [textLayer]="textRender" [handTool]="false" [contextMenuAllowed]="false" [showZoomButtons]="true" [showPresentationModeButton]="true" backgroundColor="#fff" [scrollMode]="scrollMode" [(zoom)]="currentZoomFactor" [showBorders]="false" [(page)]="currPage" (currentZoomFactor)="updateZoomFactor($event)" [(sidebarVisible)]="sidebarOpen" [(rotation)]="rotation" (pagesLoaded)="onPagesLoaded($event)" (progress)="onProgress($event)" (pageRendered)="onPageRendered($event)" [class.hide]="isLoading">
    </ngx-extended-pdf-viewer>


updateZoomFactor(zoom: number) {
    if (this.currentZoomFactor === 'page-fit') {
      Math.floor(zoom * 100) < 35 ? this.currentZoomFactor = 36 : this.currentZoomFactor = Math.floor(zoom * 100);
      console.log("zoom",this.currentZoomFactor);
    }
  }
```

**Comment by stephanrauh** [comment]
By default, the PDF tries to acquire as much screen estate as possible. Expressing this more technical, it uses 100% of the height of the surrounding `<div>`. For some reason, many CSS frameworks have weird rules with respect to the height. A height of 100% amounts to zero pixels. It seems you've run into such a situation.

There's nothing I can do about this. It's just the way it is. But I can print a warning, and I can force the PDF viewer to have a height of 100 pixels. That's what you're observing.

So fix the issue, find out why the surrounding HTML element has a height of zero pixels. If you can't fix that, use the `[height]` attribute to force the PDF viewer to have a certain height.

**Comment by aysha-statvalu** [comment]
Thanks for your help
