### ISSUE TITLE
PDF-VIEWER cant open pdfs from any url 

### ISSUE THREAD

**Issue by soulmate1337** [stephanrauh/ngx-extended-pdf-viewer#1047]
**Describe the bug**
Pdf-extended-viewer cant show pdf from url like (https://mywebser.com/api/File/any-guid) which comes as blob

**Version info**
- Version: "ngx-extended-pdf-viewer": "^10.5.0",

**Desktop (please complete the following information):**
 - Browser [Tested on Chrome]

**To Reproduce**
Get a file from ur api as blob, give this blob into the src attribute or move this blob into base6e and give this in ur src attribute
I get always this error => **ngx-extended-pdf-viewer.js:1339 GET http://localhost:4200/assets/pdf-2.10.562.min.js net::ERR_ABORTED 404 (Not Found)** or is this error about localization?
We save pdfs on a different storage and the api get the file as blob so i dont have it on assets folder i mean maybe im missunderstand smth but u cant tell me this is a solution to store all pdfs in assets folder. We have thousands of customer and i cant store all of their files in assets folder!

**Demo PDF file**
CAnt provide pdf file but its a blob coming from server

**Comment by soulmate1337** [comment]
fixed

**Comment by stephanrauh** [comment]
Hey, you're my favorite user. You've fixed the issue before I even had an opportunity to read it! :)

Jokes aside: is there anything I can do to keep developers from running into this trap? Do you want me to improve the documentation, the error messages, whatever?

**Comment by soulmate1337** [comment]
> Hey, you're my favorite user. You've fixed the issue before I even had an opportunity to read it! :)
> 
> Jokes aside: is there anything I can do to keep developers from running into this trap? Do you want me to improve the documentation, the error messages, whatever?

Sorry for my late response but ive fixed it on angular.json like in ur documentation mentioned but ive only pasted this into my angular.json

assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }
            ],

**Comment by stephanrauh** [comment]
I see. Sounds like you've given me another good reason to put https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1065 on the priority list.

**Comment by ChristopherBanas** [comment]
this issue was my issue as well. hours debugging led to this! @stephanrauh after going through a lot of the issues i love the support you provide for the users of this library. never seen an open source dev this supportive

**Comment by stephanrauh** [comment]
Thanks a lot! This kind of feedback keeps me going!
