### ISSUE TITLE
Firing events on pdf download

### ISSUE THREAD

**Issue by AleksanderBodurri** [stephanrauh/ngx-extended-pdf-viewer#105]
Hey there. I was wondering if it's possible to trigger an event when a user downloads a pdf. Would be a super useful feature I think. Loving the library btw :)

**Comment by stephanrauh** [comment]
Seems to be possible, at least to a point. I can fire an event when the user clicks the "download" button, or type CTRL+S to start the download. What I can't do is recognize if they did download the file. All I can detect is the intention to download the file. If the user hit the "cancel" button, my event fires nonetheless.

Adding insult to injury, chances are that the event is fired before downloading the file. That's a first assessment, maybe I'm wrong. I didn't implement the feature yet.

Given all these doubts, is the feature still valuable?

**Comment by AleksanderBodurri** [comment]
Had a feeling that would be the case. I think I'm instead going to just hide the download button and create my own outside the component to hit an endpoint that both audits the download and serves the file.

I'm not entirely sure of the technical side of it but I could forsee implementing this feature into the library being useful. For example, on click of the download button a user could prevent the download from happening and then serve the file to the user through whatever method they wish (possibly auditing the process in the act).

Thank you for the speedy reply. :}

**Comment by stephanrauh** [comment]
The file `viewer.js` contains a class `DownloadManager` that's a good starting points for experiments. Copy it to you local assets folder, so you edit isn't overwritten after the next `npm install`. As things go, that's one of the files I frequently update when publishing a new version, but still, it's a good starting point to figure out how to do things correctly.

Just tell me when you've found a good way to intercept the download process, so I can add the event. For the moment, I'll keep the ticket open, waiting for the result of your research. Deal?

Best regards,
Stephan

**Comment by AleksanderBodurri** [comment]
It seems like the following lines of code are responsible for downloading (line 14169 - 14186).

```
function _download(blobUrl, filename) {
  var a = document.createElement('a');

  if (!a.click) {
    throw new Error('DownloadManager: "a.click()" is not supported.');
  }

  a.href = blobUrl;
  a.target = '_parent';

  if ('download' in a) {
    a.download = filename;
  }

  (document.body || document.documentElement).appendChild(a);
  a.click();
  a.remove();
}
```
It makes the most sense to me to intercept the download like this,

```
function _download(blobUrl, filename) {
  var a = document.createElement('a');

  if (!a.click) {
    throw new Error('DownloadManager: "a.click()" is not supported.');
  }

  function handleDownloadClick(e) {
    e.preventDefault();
    // Handle click event

  }
  a.addEventListener('click', handleDownloadClick)

  a.href = blobUrl;
  a.target = '_parent';

  if ('download' in a) {
    a.download = filename;
  }

  (document.body || document.documentElement).appendChild(a);
  a.click();
  a.removeEventListener('click', handleDownloadClick)
  a.remove();
}
```
I'm not sure how to actually handle the event from there however. Any ideas?

**Comment by stephanrauh** [comment]
Looks promising. Awesome!

As for firing the event: pdf.js uses the standard window events, so I suggest to follow their lead. We can convert this to Angular event listeners later. So basically, that's the code required to fire the event:

```javascript

    var evtObject = document.createEvent('Event');
    evtObject.initEvent('downloaded', true, false);
    document.dispatchEvent(evtObject);
```
If it's available in the download manager, we can also use the internal event bus of pdf.js: `(<any>window).PDFViewerApplication.eventBus`.

Here's an example how to convert such an event to an Angular event:

```typescript
    (<any>window).PDFViewerApplication.eventBus.on('pagerendered', (x: PageRenderedEvent) => {
      this.pageRendered.emit(x);
    });
```

Finally, instead of modifying the `viewer.js` directly, I prefer to write a program to modify the code. That, in turn, enables me to update the underlying version of pdf.js quickly. You don't have to do this, but if you're interested, have a look at the file `modifyPdfJs/modifyPdf.js` and send me the necessary changes. That'd earn you a ton of extra kudos! :)

**Comment by AleksanderBodurri** [comment]
I'll give it a shot when I get the chance. Will keep you posted.

**Comment by stephanrauh** [comment]
Awesome. Implementing and testing #103 requires more time than I expected, so I appreciate your help. Feel free to send me a pull request. There's not much I can do to thank you except mentioning you in the "kudos" section of the 1.0 announcement of the library. But unless you contradict, that's something I'd love to do, hopefully giving your career a tiny boost!

**Comment by AleksanderBodurri** [comment]
Sounds good to me! Sorry for the late reply, I'm very busy with work these days. I'll take a look at implementing the feature over the weekend.

**Comment by stephanrauh** [comment]
This feature is going to be part of version 1.0.0-rc.2.
