### ISSUE TITLE
Range Request on https://pdfviewer.net

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1051]
The showcase doesn't use range request. As a consequence, many demos are a lot slower than they need to be. However, the server supports range requests.  Let's examine what's going on.

**Comment by muuvmuuv** [comment]
Yes, noticed that too. I have also noticed that in Ionic (native WebView) it's also no longer working. It always fetches the full PDF. But there it might be some not supported capability.

**Comment by stephanrauh** [comment]
Strange. The only good thing about it is I'm looking forward to an exciting debugging session.

BTW, my leisure time is a limited resource at the moment. If you've got a hint or if you want to dig into the bug yourself, I'd appreciate it!

**Comment by stephanrauh** [comment]
It seems range requests are only activated if the server also sends the `content-length` header. For some reason, my server did so only for small files, probably a side-effect of gzipping. Since deactivating gzip, the server uses Brotli compression (awesome!) and sends the `content-header` reliably.

**Comment by muuvmuuv** [comment]
Thanks for the hint; now for Ionic I need to investigate this. I hope its not something WebView is limited in...

**Comment by stephanrauh** [comment]
BTW, if you want to debug this, here's the culprit: https://github.com/stephanrauh/pdf.js/blob/c864e8a5c5561c26c72b572eb01b656460efb333/src/display/network_utils.js#L36

I had some difficulties to debug this line. It seems to be added multiple times to the binaries, and my debugger ran havoc. But if you're persistent, you can debug it!
