### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1055]
having performance issues while trying to open pdf having 33000 pages. zoom in,out. 

https://www.pdftron.com/webviewer/demo/gallery/us-public-health-and-welfare-code.pdf

**Comment by aysha-statvalu** [comment]
low performance please help

**Comment by stephanrauh** [comment]
Good news! I've been able to loosen another brake. As long as you don't show the thumbnails, the PDF file shows twice as fast now in single-page mode, and zooming doesn't reduce the performance.

However, if you (or your user) shows the thumbnails, the performance goes south immediately. Using your 13000 page test document, even scrolling becomes slow and laggy.

Note that the other two page-view modes - the regular mode and the infinite scroll mode - are still slow with such a huge document. There's no easy way to get rid of this limitation. It'd require me to rewrite large parts of the PDF viewer core, and while that's probably an interesting challenge, it's out-of-scope of this project.

At the moment the improvement is only active in the "bleeding edge" branch.

**Comment by stephanrauh** [comment]
The improvement has shipped with version 11.0.0-beta.1.

**Comment by aysha-statvalu** [comment]
Thanks Bro... Thanks for your help!!!

**Comment by stephanrauh** [comment]
The feature is now part of version 11.0.0 and both the stable and the bleeding edge branch.
