### ISSUE TITLE
get selected text coordinates

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#1056]
get selected text coordinates.

**Comment by aysha-statvalu** [comment]
please help

**Comment by aysha-statvalu** [comment]
if user selects text in pdf then i should able to get the x,y coordinates of that selected text please help.

**Comment by aysha-statvalu** [comment]
please help please reply

**Comment by stephanrauh** [comment]
You could add this event listener to the text layer of every page: https://developer.mozilla.org/en-US/docs/web/api/document/selectionchange_event.

However, this only tells you only which HTML element has been selected. You can calculate the position of the selected HTML element on the page. That, in turn, enables you to calculate something like "selection is in the lower third of the page".
