### ISSUE TITLE
ngx-extended-pdf-viewer.js:1117 Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by glasje** [stephanrauh/ngx-extended-pdf-viewer#106]
hi, install the package and follow the indications of the documentation but I get the following error
![image](https://user-images.githubusercontent.com/34929785/60988210-201c2e00-a311-11e9-9dca-d0b3f2f167a6.png)

**Comment by stephanrauh** [comment]
That's no much detail to work with. Which version of Angular are you using? Which version of ngx-extended-pdf-viewer are you using? Which documentation are you referring to? The instructions I posted on npm, or the instructions of https://pdfviewer.net?

My guess is that your copy of Angular is incompatible with ngx-extended-pdf-viewer. It requires at least Angular 6. Another idea: delete your node_modules folder and run npm install again.

**Comment by glasje** [comment]
Project dependency:
"devDependencies": {
    "@angular/cli": "^1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }

install npm i ngx-extended-pdf-viewer, I assume that the latest version of this was installed. Follow the instructions of both pages 

- https://www.npmjs.com/package/ngx-extended-pdf-viewer

- https://pdfviewer.net

**Comment by stephanrauh** [comment]
Awesome. That solves the puzzle. You're using Angular 5. I didn't expect that, but from the library maker's point of view, both Angular 6 and Angular 8 introduce nasty breaking changes. After pondering about it for a while, I decided to support Angular 6+ only. 

However, if you're using Angular 5, that's still possible. It's just a little extra work. The ngx-extended-pdf-viewer is just a few files. You can copy them to your own project. Have look at the recipe and GitHub repository provided by @tanzl, who kindly showed us the way to get ngx-extended-pdf-viewer up and running with Angular 5: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/86#issuecomment-506914609

**Comment by stephanrauh** [comment]
I'll close the ticket now. If you're still experiencing problems, don't hesitate to tell me. This ticket may be closed, but that doesn't stop the e-mail notifications.
