### ISSUE TITLE
Syntax errors caused by the logical assignment operator ||=

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1063]
Some browsers crash when trying to execute the logical assignment operator `||=`. So let's add a check if the browser support this operator. If it doesn't, fall back to the ES5 version of pdf.js.

**Comment by stephanrauh** [comment]
Originally reported by @bmadhan90 in https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/657#issuecomment-985570727

**Comment by stephanrauh** [comment]
Version 11.0.0-alpha.11 fixes the bug.

Enjoy!
Stephan

**Comment by bmadhan90** [comment]
Thank you @stephanrauh for quick fix.

Will check and update.

**Comment by stephanrauh** [comment]
The bugfix has an annoying side-effect: it slows down the pdf viewer. It uses the ES5 code that's probably still compatible to good old Internet Explorer 11. The modern code is much more efficient and more compact. Luckily this affects only a small number of users because every modern browser already support the logical assignment operator.

https://caniuse.com/?search=logical%20assignment
