### ISSUE TITLE
The pdfLoaded event always returns pagesCount is 0 on 11.0.0-alpha-*

### ISSUE THREAD

**Issue by nhvu1988** [stephanrauh/ngx-extended-pdf-viewer#1064]
**Describe the bug**
The pdfLoaded event always returns pagesCount is 0.

**Version info**
- Version 11.0.0-alpha-*

**Desktop (please complete the following information):**
 - All browsers (tested on chrome, MS edge & firefox)

**To Reproduce**
Go to this showcase and see it exists https://pdfviewer.net/extended-pdf-viewer/pages-loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/13212737/144737569-433a0b64-a188-4140-940d-fb7fd4f90d1d.png)

**Comment by stephanrauh** [comment]
That's surprising. The `PDFLoaded` event is fired before the PDF viewer starts loading the document. Did the API change, or did I miss the bug from day 1? Be that as it may, I'll fix this. 

That's a breaking change because the event is going to fire later after the bugfix.

**Comment by stephanrauh** [comment]
The bugfix is going to ship with version 11.0.0-alpha.13 today.
