### ISSUE TITLE
PDF data not loaded, until I'm performing any action in the pdf viewer

### ISSUE THREAD

**Issue by wajedali** [stephanrauh/ngx-extended-pdf-viewer#107]
Hello,

recently i upgraded PDF viewer version from 0.9.24 to 0.9.54 (with no code changes except lib version ), what can i observe in 0.9.24 pdf data rendered perfectly but when tried with 0.9.54, i have to perform some action either change page number or click spread menu in pdf viewer to load the data. 

Can you please take a look and let me know if i have to set any param on initialization for release version 0.9.54 compare to 0.9.24.

------------------------Template Code ---------------------------
```xml
  <ngx-extended-pdf-viewer *ngIf="currentPdf"
                           [src]="currentPdf"
                           useBrowserLocale="false"
                           style="height: 100%; width: 100%"
                           [delayFirstView]="1000"
                           [showHandToolButton]="true"
                           [handTool] = false>
  </ngx-extended-pdf-viewer>
```
--------------------------component code -------------------------
```typescript
  ngOnInit() {
    this.displayPdf();
  }

  displayPdf() {

    // setTimeout(() => {
      this.service.getPdfExtractedContentById(this.contentId)
        .pipe(first())
        .subscribe(
          data => {
            this.currentPdf = URL.createObjectURL(this.b64toBlob(data.ExtractedByte,'data:application/pdf;base64', 1024));
            
          },
          error => {
            console.log(error);
          }
        );
    // }, 500);

  }

  b64toBlob(b64Data, contentType, sliceSize) {
    const byteCharacters = atob(b64Data);
    const byteArrays = [];
    for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
      const slice = byteCharacters.slice(offset, offset + sliceSize);

      const byteNumbers = new Array(slice.length);
      for (let i = 0; i < slice.length; i++) {
        byteNumbers[i] = slice.charCodeAt(i);
      }

      const byteArray = new Uint8Array(byteNumbers);
      byteArrays.push(byteArray);
    }

    const blob = new Blob(byteArrays, {type: contentType});
    return blob;
  }
```

Thank you
Wajed

**Comment by stephanrauh** [comment]
I don't understand the question, so I'll rephrase it: Are the two features "change page number` and `change spread mode` broken in the new version?

**Comment by wajedali** [comment]
I am sorry, but i will try to explain again.

After initialisation PDF file/data has to be render, i mean PDF data has to be displayed, which is displayed if i use version 0.9.24. But when we upgrade to 0.9.54 , i can see only top bar of PDF viewer after initialization , and once i perform any manual action such as change page number or click on spread from menu, then PDF file/data get loaded.

Thank you
Wajed

**Comment by stephanrauh** [comment]
OK, got it. That's really weird. Let's hunt it down step-by-step:

- Are there any error message in the JavaScript console?
- Does the error also occur when you're using the 2.2 preview files? I.e. pdf-2.2.js, pdf.worker-2.2.js, and viewer-2.2.js?
- If the bug still persists, can you find out which version introduced the bug?

Alternatively - and much preferred - you can send me a reproducer (a minimal, viable program showing the bug with little to none configuration overhead).

Thanks in advance,
Stephan

**Comment by wajedali** [comment]
Thank you for reply Stephan.

the issue started post 0.9.24, but i will randomly pick versions between 0.9.25 and 0.9.54 and provide update.

Thank you
Wajed

**Comment by wajedali** [comment]
Hi Stephan,

I have verified and i can observe this issue started from version 0.9.51. for version 0.9.50 my application working fine.

Thank you
wajed

**Comment by stephanrauh** [comment]
Thanks! I looked up the changes between 0.9.50 and 0.9.51. The only thing I can spot is the change detection. For a short time, it was "onPush" until I reverted that again.

Which set of the *.js files are you using? Are the any messages in the JavaScript console?

**Comment by wajedali** [comment]
i have added following js file -
       "/node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
              "/node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js",
              "/node_modules/ngx-extended-pdf-viewer/assets/viewer.js",

also tried with pdf-2.2.js, pdf.worker-2.2.js, and viewer-2.2.js but having same result.

I dont see any error/message in console.

Thank you
Wajed

**Comment by stephanrauh** [comment]
@wajedali Thanks. I still don't have any clue what's going on. What about version 1.0.0-rc.1? Does it solve the bug?

**Comment by wajedali** [comment]
I will give a try with version 1.0.0-rc.1 and let you know.

**Comment by stephanrauh** [comment]
The alternative is to try to debug the code. Maybe the code opening the PDF file is never called. That'd be this code:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/3045767/61410862-6e1ecc00-a8e5-11e9-8ada-46d8b8ff2c1e.png">

Maybe - just maybe - this has something to do with your PDF file. I don't think so, but as I said, I've run out of ideas.

**Comment by wajedali** [comment]
Hello Stephan,

I have tried with version 1.0.0-rc.1, but no luck.

i am sorry, I didnt understand your above code , where should i use this?

**Comment by stephanrauh** [comment]
The code snippet is part of ngx-extended-pdf-viewer. More precisely, it's a snippet from the class `NgxExtendedPdfViewerComponent`. My hope is you can set a breakpoint there, so we learn what's going on here.

Maybe there's an alternative approach. Can you send me a reproducer? That's a small program showing the problem. I know that's demanding a lot - it's almost always a lot of work to prepare such a reproducer. However, currently the bug doesn't happen on my machine, so I need your help. I'm afraid either you or me has to debug the source code of ngx-extended-pdf-viewer in order to solve the puzzle.

**Comment by wajedali** [comment]
Thank you for reply. I will try to debug, if i am not able to, then will create reproducer.

**Comment by stephanrauh** [comment]
@wajedali Any progress?

**Comment by wajedali** [comment]
Hello Stephan,

i tried to debug , i can see openPDF() getting called but unable to still pdf file is not rendered.

I will create reproducer and let you know.

Thank you
Wajed

**Comment by stephanrauh** [comment]
@wajedali Any progress on your side?

**Comment by wajedali** [comment]
Hello Stephan,

I have created new project only for pdf viewer and everything working fine, i am wondering whats going wrong.

Not sure , we can close the ticket for now i think :(.

Thank you
Wajed

**Comment by stephanrauh** [comment]
Strange. Really strange. But I'm glad it works now, at least in your new project!
