### ISSUE TITLE
No matching version found for ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by vels-sonata** [stephanrauh/ngx-extended-pdf-viewer#1081]
Hi, 
I'm trying to install ngx-extended-pdf-viewer@10.5.0 and got the following error, Let me know what I'm missing.
_"No_ matching version found for ngx-extended-pdf-viewer@10.5.0"_

Even tried other versions, getting same error message.

**Comment by stephanrauh** [comment]
Sounds like a proxy problem. Are you using something like Nexus, Artifactory, Archiva or a corporate npm? Does it block certain libraries?

The version is there: https://unpkg.com/browse/ngx-extended-pdf-viewer@10.5.0/

**Comment by vels-sonata** [comment]
> Sounds like a proxy problem. Are you using something like Nexus, Artifactory, Archiva or a corporate npm? Does it block certain libraries?
> 
> The version is there: https://unpkg.com/browse/ngx-extended-pdf-viewer@10.5.0/

Thanks for the quick support stephanrauh, It is corporate npm, fixed the npm config set registry .
Thanks again.
