### ISSUE TITLE
Want to understand how I can use range request for base64 pdf string that I am getting from django backend server

### ISSUE THREAD

**Issue by chetan592** [stephanrauh/ngx-extended-pdf-viewer#1082]
I am getting PDF from Django to angular using API call which I have subscribed to. 
It waits for whole PDF to fetch and once PDF is there it loads the PDF .
Because of this user has to wait for sometime before they can interact with PDF and in the cases where PDF size is large they have to wait longer as we get whole PDF from Django (rest api).

`this.apiService(url,file_id).subscribe((pdf)=>{
this.pdfBase64 = pdf
})
`

I am using this `this.pdfBase641 for showing pdf using ngx-extended-pdf-viewer.

How can I use byte ranges here so it does not wait for complete pdf to fetch and start loading as soon as there is some data?

**Comment by stephanrauh** [comment]
This sounds difficult. Your Django backend has to implement the range request protocol. Are we talking about files that are created dynamically during the REST call?

**Comment by stephanrauh** [comment]
Maybe this code snippet helps: https://gist.github.com/dcwatson/cb5d8157a8fa5a4a046e

**Comment by chetan592** [comment]
Yes.... files are in media folder of django. 
I am reading files media folder and converting them to base64 string.

`with open(path, "rb") as pdf_file:
        encoded_string = base64.b64encode(pdf_file.read()).decode('utf-8')
    response = {
        "pdfString": encoded_string
    }
    return JsonResponse(response,status=status.HTTP_200_OK)`

What is end to end thing I need to do.?
What changes do I need to make in frontend to implement this?
Do I need to make multiple request to backend for ranges or just single call is sufficient and pdf-viewer will handle things?
I am not getting clear picture on both frontend (changes need to do for it to work with ngx-extended-pdf-viewer) and backend?

**Comment by stephanrauh** [comment]
You don't need to do anything on the frontend. It's only the backend that has to support range requests.

**Comment by stephanrauh** [comment]
I think the file https://gist.github.com/dcwatson/cb5d8157a8fa5a4a046e#file-range_streaming-py is what you need. Instead of returning `JsonResponse(...)` you call the method `stream()`.

**Comment by chetan592** [comment]
I tried it .. adding code for reference . But it still loads pdf once complete pdf fetched

`getNativePDF() {
    let subscription = this.webService.getNativePDFResponse(WebUrl.getNativePDF, this.selectedFileId).subscribe((response) => {
      console.log('native pdf response ', response)
      this.nativePDFSrc = response
    })
    this.subscriptions.push(subscription)
  }`

`getNativePDFResponse(endPoint: string, file_id): Observable<any> {
    return this.http.get(environment.baseurl + endPoint + '/' + file_id, {
      headers: this.addHeader(),
      responseType: 'blob'
    })
  }`

`<ngx-extended-pdf-viewer #pdfViewer [src]="nativePDFSrc" useBrowserLocale="true" [zoom]="'page-width'"
            [showPrintButton]="false" [showOpenFileButton]="false" [showPresentationModeButton]="false"
            [showDownloadButton]="false" [showBookmarkButton]="false" [showRotateButton]="false"
            [showScrollingButton]="false" [showSecondaryToolbarButton]="false" [showHandToolButton]="false"
            [textLayer]="true" [showBorders]="false" [handTool]="false" (textLayerRendered)='textLayerRendered($event)'
            [showSidebarButton]="false" (pageRendered)='pageRendered($event)' >
          </ngx-extended-pdf-viewer>`

django - 
`return stream(request,path)`

**Comment by stephanrauh** [comment]
Oh, yeah, sorry. You've already mentioned you're prefetching the PDF file. Don't do that. Instead, point the URL parameter directly to `environment.baseurl + endPoint + '/' + file_id`, like so:

```html
<ngx-extended-pdf-viewer [url]="environment.baseurl + endPoint + '/' + file_id" ... ></ngx-extended-pdf-viewer>
```

I don't know if that's possible because I don't know what your `addHeader()` method does. If it does something crucial, try to deactivate the feature on the back-end to learn if the approach works. If so, we can figure out how to add the header your need later.

**Comment by chetan592** [comment]
I made changes I tried it... But it is same. Only change I can see is pdf progress bar is now moving according to api response.

version - ^11.0.0-alpha.10

`<ngx-extended-pdf-viewer #pdfViewer [src]="baseUrl + nativePDFUrlEndPoint + '/' + selectedFileId" 
            useBrowserLocale="true" [zoom]="'page-width'"
            [showPrintButton]="false" [showOpenFileButton]="false" [showPresentationModeButton]="false"
            [showDownloadButton]="false" [showBookmarkButton]="false" [showRotateButton]="false"
            [showScrollingButton]="false" [showSecondaryToolbarButton]="false" [showHandToolButton]="false"
            [textLayer]="true" [showBorders]="false" [handTool]="false" (textLayerRendered)='textLayerRendered($event)'
            [showSidebarButton]="false" (pageRendered)='pageRendered($event)' >
          </ngx-extended-pdf-viewer>`

url - doesn't work so used src. It url says its not known property of ngx

backend is same..

**Comment by stephanrauh** [comment]
You're right, of course that parameter's called `[src]`.

**Comment by stephanrauh** [comment]
I wonder if you can send me a reproducer. There's a catch: I have very little experience with Ruby, and none at all with Django. I suppose I need to install Ruby. In other words: brace yourself for guiding me through stupid rookie questions. If that's fine by you, feel free to send me a reproducer so I can debug the problem myself!

**Comment by chetan592** [comment]
Thanks Stephan for helping me out with this and for such a beautiful library that saves us lot of time on functionality and implementations.

I am still looking into it. If possible I will reproduce issue soon.
I used to chrome to hit the API as chrome is having built in PDF display engine. Same is happening there. So think problem might be in Django as it does not support range requests out of the box.

Thanks again for all.

**Comment by stephanrauh** [comment]
You're welcome! You know, you can always make me happy with a challenging puzzle. :)

**Comment by chetan592** [comment]
I checked your comment on previous issue where you have said that it only works on static files..
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/470

Is it still the case that it works with static file and not with files served dynamically with rest?

**Comment by chetan592** [comment]
Hello @stephanrauh 

Here I have pushed code to github to reproduce the issue.

My use case is with Django but here I tried node to check if it works there but it does not.
So I have added node server code to reproduce issue as it is much simple than django to reproduce

Link to github - 

https://github.com/chetan592/reproduce_issue_range_request

**Comment by stephanrauh** [comment]
Awesome, thanks! Today I've got a bad headache, so apologize me for not looking into your issue immediately. I've cloned the repository, added it to my workspace, and quickly scanned if everything's there. I guess it looks good.

Stay tuned! :)
Stephan

**Comment by stephanrauh** [comment]
I'm beginning to investigate your topic. As a first step, I copied on of my PDF files as `demo.pdf` into your project, as you've asked for in the instructions. When trying to open this document via `http://localhost:3000/demo.pdf`, I ran into an error message ("Error loading the PDF document").
![image](https://user-images.githubusercontent.com/3045767/147005312-29afe14e-3815-4ed8-8d0b-d02b2c2185c6.png)

I'm not sure if it's related to your issue at all, but I'd check this first. At the moment, I'm at a loss. I don't see any error messages, but Chrome (more precisely: https://github.com/Eloston/ungoogled-chromium) refused to display the file.

**Comment by stephanrauh** [comment]
Be that as it may, let me express my gratitude for submitting a reproducer. Few developers go into such great lengths, and, being a developer myself, and knowing the pain brought by deadlines, I just have to say "thank you"!

**Comment by chetan592** [comment]
Hello @stephanrauh 
Thanks for support you are providing without anything in return.... that's very few people do. 

One thing I changed was I commented this part
 `let readable = createReadStream(samplePDF);
       pipeline(readable, res, err => {
         console.log(err);
       });`

and added `res.end()` because of it may be its throwing error so you can uncomment that part and comment this 'res.end()` part. 

So it would be like this - 
`res.writeHead(200, {
        "Content-Length": size,
        "Content-Type": "application/pdf",
        "accept-ranges": "bytes",
        "Access-Control-Allow-Origin": "http://localhost:4200"

      });

      //res.end()

       let readable = createReadStream(samplePDF);
       pipeline(readable, res, err => {
         console.log(err);
       });	
`
then it should work.

I think if you haven't changes anything in node/index.js file then you can also try to use `http://localhost:3000`

**Comment by chetan592** [comment]
I got the same error when I tried, so I changed it to original (Steps I mentioned above). 
I have also pushed the same on github so you can also pull that if you want.

This node server code is from article written by Vishal Patel that you have suggested in range request info page 
https://pdfviewer.net/extended-pdf-viewer/range-requests

Thanks again

**Comment by stephanrauh** [comment]
Found it! It's a CORS limitation: https://stackoverflow.com/questions/43344819/reading-response-headers-with-fetch-api/44816592#44816592

Adding the headers `Access-Control-Expose-Headers` and `Access-Control-Allow-Headers` solves the issue:

```javascript
    res.writeHead(200, {
        "Access-Control-Expose-Headers": "Accept-Ranges",
        "Access-Control-Allow-Headers": "Accept-Ranges,range",
        "Accept-Ranges": "bytes",
        "Content-Length": size,
        "Content-Type": "application/pddf",
        "Access-Control-Allow-Origin": "http://localhost:4200"
      });
```

**Comment by stephanrauh** [comment]
@chetan592 I've added the source code to the showcase. I'd also like to add a little kudos section mentioning your name. I hope that's fine by you. If it isn't, just tell me.

**Comment by chetan592** [comment]
Finally..........

Thank you so much for it..

I will make necessary changes for django also once done I am planning to write blog on Angular to Django with ngx-extended-pdf-viewer.

Yeah , I would love to be mentioned on page. My name is Chetan Patil.

**Comment by stephanrauh** [comment]
If you're writing a high-quality blog post without advertising, I can offer you to publish your post on my website, too. Here are the rules to follow: https://www.beyondjava.net/page/guest-posts 

I'm going to mention you here: https://pdfviewer.net/extended-pdf-viewer/range-requests. I haven't published the new version of the showcase yet, but you can already check the text here: https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/main/src/app/extended-pdf-viewer/range-requests/range-requests.component.html

**Comment by chetan592** [comment]
Sure.... I will share blog with you once it is complete so you can decide if we can go ahead with it or not... It will take some time  as I am working on project.

What would be good way to communicate with you for it and in general ?
