### ISSUE TITLE
Addition of new pages and rendering them only instead of rerendering the entire document

### ISSUE THREAD

**Issue by SamratSK** [stephanrauh/ngx-extended-pdf-viewer#1094]
Hey Stephan!
An awesome library. Thanks for it.

I am trying to display a pdf of about 300-400 pages without the user being able to download it. To handle the large size, the php laravel backend sends pdf split at 10 pages encoded in a base64 string which is encrypted (decrypted in the client side). Now using jsPDF I stitch it back to a single pdf and convert this to a base64 string and rerender. This happens many times over. For a 300 page pdf this happens for 300/10 = 30 times. Pretty straightforward.

However I think that the conversion, addition, combined with rerendering the entire pdf on the component takes up a lot of memory and is time consuming. Please correct me here if I am wrong, So are you planning to develop a feature where someone could directly add new pdfs and the component could now just render only the newly added pages instead of all the pages?

If you think there is a better way to handle large pdfs, please suggest it to me.

Thank You.

**Comment by stephanrauh** [comment]
Whow. That's a clever solution! But maybe there's a simpler approach. I don't know what "the user isn't able to download it" means precisely. If you're referring to file size, you might want to have a look at the range requests feature.

Open the default showcase page (https://pdfviewer.net) and watch the network traffic:
![image](https://user-images.githubusercontent.com/3045767/146437092-02453523-103e-4cf9-9f98-50889e276174.png)

I assume the first request doesn't really download 1.9 megabytes. Instead, the PDF viewer downloads chunks of 64 kilobyte. This allows it to display pages very quickly. In fact, the PDF viewer never downloads pages unless you read them.

That doesn't work with Base64 encoding. You have to send the binary file. Plus, you server has to support range requests. But most servers do, so I'm positive that no show-stopper, either.

**Comment by SamratSK** [comment]
Hi Stephan,
Thanks for answering.

By "the user isn't able to download it", I mean that there shouldn't be an for the user to download the file. He/She should just be able to view it. I know that 100% prevention of download is not possible, yet trying my best to prevent common ways. So I used encrypted base64 here. 

Thanks for informing me about range requests. Definitely will check and implement it in my backend if there is a way.

Thank You.

**Comment by stephanrauh** [comment]
I see. Yeah, taking this into mind, your approach is even more clever than I thought. It goes without saying that this doesn't protect you against professional actors - but you've mentioned that yourself.

Come to think of it, range requests make it difficult to download the entire PDF file, too. At least if you block downloading the entire file. This, in turn, mean you have to implement the server-side API yourself. But that's not difficult, either. Here's a Ruby code snippet that does the trick (according to the author - I didn't test it): https://gist.github.com/dcwatson/cb5d8157a8fa5a4a046e#file-range_streaming-py

What can I do to prevent downloading the entire file? I'm afraid there's little I can do. You can hide the download button, but that only protects you from the most simple attempts to download the file. So I guess range requests are a good way to go, especially if you implement a backend that never sends entire files.

Best regards,
Stephan

**Comment by SamratSK** [comment]
Hi Stephan,
Thanks a lot for your insights. I was sure benefitted by the.

Once again thank you for this awesome library.

Thank You.

**Comment by stephanrauh** [comment]
Is there anything I have to do? I'm closing the issue because it doesn't seem so.
