### ISSUE TITLE
Chinese font broken after update to version 10.5.0(before is 1.8.0 and work normal)

### ISSUE THREAD

**Issue by bonbonmark** [stephanrauh/ngx-extended-pdf-viewer#1104]
**Describe the bug**
Use online demo also appears this problem, 

**Version info**
- Version of ngx-extended-pdf-viewer(10.5.0, 11.0.0 also has same problem)

**Desktop (please complete the following information):**
 - Chrome(96.0.4664.110 )
 
**Smartphone (please complete the following information):**
 - Not tested in smart phone

**To Reproduce**
Use online demo upload pdf file attachment can reproduce this problem

**Demo PDF file**
[1205_富邦投信_富邦AI智能新趨勢多重資產型基金_中信版A4DM-compressed.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7777750/1205_._.AI._.A4DM-compressed.pdf)

**Screenshots**
in console can see some warning
<img width="776" alt="mapurl" src="https://user-images.githubusercontent.com/12341661/147423351-4864d2af-dacc-4cc5-9d72-82992bca0a31.png">

Not showing font demo
<img width="776" alt="font not show" src="https://user-images.githubusercontent.com/12341661/147423360-2090988c-8be6-4792-84b5-16b9cd8759f2.png">

pdf open in adbobe reader
![font normal](https://user-images.githubusercontent.com/12341661/147423372-920cabf2-1da2-4cf3-b057-0c060968161b.jpg)

**Comment by stephanrauh** [comment]
The bugfix has landed with version 11.0.1.
