### ISSUE TITLE
Provide Option to Align Document Left in the Viewer

### ISSUE THREAD

**Issue by cvjanick** [stephanrauh/ngx-extended-pdf-viewer#1108]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I'm always frustrated when [...]"
Some use cases prefer the ability to align the PDF document left and top in the viewer similar to ng2-pdf-viewer. 

**Describe the solution you'd like**
An option to align-pdf-document = left, center, right with center being the default

**Describe alternatives you've considered**
Tried but didnt work:
*::ng-deep .pdf-viewer .page {
    margin-left: 2px !important;
}
or stay will ng2-pdf-viewer without the benefits of ngx-extended-pdf-viewer for now, building own angular module (ugh).
    

**Additional context**
Helps on small form factors to align the pdf document to the left in the viewer.

**Comment by stephanrauh** [comment]
This CSS rule does the trick:

```css
::ng-deep ngx-extended-pdf-viewer #viewerContainer .pdfViewer .page {
  margin: unset;
}
```

**Comment by cvjanick** [comment]
Thank you for the CSS solution - working fine for our needs.
