### ISSUE TITLE
Warning: getPdfFilenameFromUrl: ignore "data:"-URL for performance reasons.

### ISSUE THREAD

**Issue by JoanJosep33** [stephanrauh/ngx-extended-pdf-viewer#1112]
Hello, I am trying to simply display two pdfs but the second it is never displayed. 
On the `console.log()` appears the following message: 

```
Warning: getPdfFilenameFromUrl: ignore "data:"-URL for performance reasons.
app.js:1573 PDF viewer: ngx-extended-pdf-viewer running on pdf.js 2.10.562
app.js:1579 PDF c8d76c535d566b88ab968b0a066c07be [1.4 Skia/PDF m97 Google Docs Renderer / -] (PDF.js: 2.10.562) modified by ngx-extended-pdf-viewer)
```

![image](https://user-images.githubusercontent.com/15216494/148133674-687e46d7-38e6-4e40-b5de-c36f7ea7da36.png)

What could it be? 

The html file looks like this: 

`<ngx-extended-pdf-viewer 
				[src]="pageInfo.currentItemSelected.origin.info" 
				useBrowserLocale="true" 
				height="50vh"
				[textLayer]="true"
     			(textLayerRendered)=highlightWords($event);></ngx-extended-pdf-viewer>`

Thanks in advise

**Comment by stephanrauh** [comment]
These PDF files are displayed side-by-side? I'm afraid that's not possible because pdf.js pollutes the global namespace. However, I believe you can wrap ngx-extended-pdf-viewer in an iFrame or - even better - in a WebComponent.

**Comment by stephanrauh** [comment]
BTW, the error message is really weird. At the moment, I don't have a clue what it's about: https://github.com/stephanrauh/pdf.js/blob/04d315b9ec2f1d04b544bbf92d6d788eafdc2cd8/src/display/display_utils.js#L429

**Comment by JoanJosep33** [comment]
Yes, they are side by side. I thought it could be since I can do it easily with the `ng2-pdf-viewer` library. 
And yes, it's a strange message. Thanks for all!
