### ISSUE TITLE
Export pdf with highlights

### ISSUE THREAD

**Issue by JoanJosep33** [stephanrauh/ngx-extended-pdf-viewer#1113]
Hello, I would like to know if it is possible to export/download the pdf after highlighted the desired words. When I download it, the highlighteds parts are gone. 

Thanks in advise.

**Comment by stephanrauh** [comment]
I'm afraid that's not possible. In theory, you could use PDF annotations to implement highlighting. But that's not the way the base library, pdf.js, works. It doesn't modify the PDF file. Highlighting has been implemented with HTML.

![image](https://user-images.githubusercontent.com/3045767/148223263-ed0bfec0-5a97-4607-985c-8e9ff437221f.png)
