### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by tanishkab** [stephanrauh/ngx-extended-pdf-viewer#1116]
On installing this new update I am facing npm errors. 
Like

![image](https://user-images.githubusercontent.com/64952583/148517735-965aeb15-9439-4984-8cc9-c63c0a0444eb.png)

**Comment by stephanrauh** [comment]
Looks like an Ivy problem. Version 11 requires the new Ivy engine. If you're still using the old ViewEngine, you'll see these errors.

Background information about Ivy: https://chriskohler.dev/angular-view-engine-was-removed-what-you-need-to-know

Does that help you?

**Comment by tanishkab** [comment]
Okay, will update it then. Thanks!

**Comment by tanishkab** [comment]
Also, I was facing another issue with Angular, if you could help me. It says:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'bg-dark parentNode'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook.

**Comment by stephanrauh** [comment]
Yeah, sure. I've poured all my knowledge about `ExpressionChangedAfterItHasBeenCheckedError` into this article: https://www.beyondjava.net/zonejs

**Comment by stephanrauh** [comment]
BTW, when you've managed to solve the issue, please tell me so I know I can safely close this ticket.

**Comment by tanishkab** [comment]
Yes, I did thanks Stephan! Thanks for sharing that article also!
