### ISSUE TITLE
Unexpected private name #i. Cannot parse class method with private name.

### ISSUE THREAD

**Issue by danchaseCTS** [stephanrauh/ngx-extended-pdf-viewer#1118]
Works on Android, but when running in an iOS 14.5 emulator, I get:

------ STARTUP JS ERROR ------

⚡️ SyntaxError: Unexpected private name #i. Cannot parse class method with private name.
⚡️ URL: capacitor://localhost/assets/pdf-2.12.544.min.js
⚡️ pdf-2.12.544.min.js:23:0

⚡️ See above for help with debugging blank-screen issues
⚡️ [log] - Done Loading Report

Version of ngx-extended-pdf-viewer: 11.0.1

Works on Deskop, Android, does not work on the IOS Emulator I'm using.

Steps to reproduce the problem:

1. Ionic Angular App with Capactitor, using package ngx-extended-pdf-viewer.
2. ionic cap build iOS
3. Run the application in Xcode, and attempt to access the pdf.

When I put a bug request in to the pdfjs project, they say that it's not a supported version, here was their response:
------
_PDF.js version: 2.12.544

Sorry, but that version number does not correspond to an official release; please find the latest supported releases at https://mozilla.github.io/pdf.js/getting_started/#download

SyntaxError: Unexpected private name #i. Cannot parse class method with private name.

If you environment/browser doesn't support modern JavaScript, please use a legacy build of the PDF.js library. Note that this is mentioned e.g. in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and https://github.com/mozilla/pdfjs-dist/#pdfjs_
------

Unsure what to do, is there a way to load the official supported version in to assets? I was reading that IOS needs es5, but could be wrong, when I build with "es5" as target is tsconfig, it still gives the same error. Ideas?

**Comment by danchaseCTS** [comment]
I checked further, and it looks like the iPhone has to be completely new and up to date to support private name methods. I don't think I want to target only the newest device, hoping I'm wrong about the error?

**Comment by stephanrauh** [comment]
As for the pdf.js issue: I feel you. They get so many issues they started to triage them. The last part of the version number is the number of commits. And I've added a couple of modification, so the version number is different from the "official" build number.

Be that as it may, using a unmodified distribution of pdf.js doesn't work. But then, I never tried, maybe it's not entirely incompatible. :) You'd loose the modifications and bugfixes I've added. pdf.js is intended to be used as the full-page PDF viewer of Firefox. I've embedded it in a wildly different environment, so some things need to be tweaked and patched to make it work reliably.

**Comment by stephanrauh** [comment]
As for the private namespaces: that's bad news. I didn't expect that. It means your iPhone has to use the slow legacy build. I'm going to publish a bugfix version that switches to the legacy build automatically. If you need an older version for some reason, you have to replace the file `/assets/viewer-2.12.xxx.min.js` by `/assets/viewer-2.12.xxx-es5.min.js`. At the time of writing, the other two files - `pdf-2.12.xxx.js` and `worker-2.12.xxx.js` - do not seem to use private variables yet, but it's only a question of time until the teams starts using them.

**Comment by stephanrauh** [comment]
The minimum requirement for iOS is Safari 15: https://caniuse.com/?search=private

**Comment by stephanrauh** [comment]
The bugfix has landed with version 11.1.1.

**Comment by kemsky** [comment]
@stephanrauh, I think we could use post-processing https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/570#issuecomment-936603324 to make sure that it never happens again.

I have sample gulp task:

```js
const path = require('path');
const sourcemaps = require('gulp-sourcemaps');
const gulp = require('gulp');
const terser = require('gulp-terser');
const rename = require('gulp-rename');

gulp.task('pdf-viewer-minify', function () {
    return gulp
        .src(path.join(angularSourcePath, 'assets', '*.js'))
        .pipe(sourcemaps.init())
        .pipe(rename({suffix: '.min'}))
        .pipe(
            terser({
                keep_fnames: true,
                mangle: false,
                ie8: true,
                safari10: true,
                compress: true
            })
        )
        .pipe(
            sourcemaps.write(path.join(angularSourcePath, 'assets'), {
                sourceMappingURL: function (file) {
                    return file.relative + '.map';
                }
            })
        )
        .pipe(gulp.dest(path.join(angularSourcePath, 'assets')));
});
```

**Comment by stephanrauh** [comment]
Yes, I thought about this, too. However, I don't think that's necessary. Currently, the pdf.js team is only using ES2020 features supported by a wide range of browsers. For the other browsers there's already the ES5 build.

BTW, instead of adding a post-build script, I'd add some limited Babel processing to this script: https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/gulpfile.js
