### ISSUE TITLE
Download and Print buttons are not accessible in small devices

### ISSUE THREAD

**Issue by ravikumarbggit** [stephanrauh/ngx-extended-pdf-viewer#112]
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
Not Sure
- Does the bug also happen on https://pdfviewer.net/simple?
Not Sure

Description:
I only need print and download buttons in the toolbar. but download/print from mobile device is not possible as they are not visible even in landscape mode.

I can however enable show more button (showSecondaryToolbarButton) in the toolbar (visible in small screen) which allows to access print/download options

**Version info**
- Version of ngx-extended-pdf-viewer: 0.9.49
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser  Chrome
 - Version 75

**Smartphone (please complete the following information):**
 - Device: Galaxy S6
 - OS: Android
 - Browser Chrome
 - Version latest

**To Reproduce**
Any project which uses this library

**Comment by stephanrauh** [comment]
I see. You're right - the default layout doesn't make any sense for a smartphone. I believe it's a good idea to make the layout more flexible in future - say: in version 1.1.

Until then, I've prepared a bugfix for you. You can override the standard CSS rules. The showcase shows you how to do that: https://pdfviewer.net/smartphone.

Putting it in a nutshell, the idea is to use the deprecated `/deep/` selector. If you don't want to do that, put the same CSS rule into the global `style.css` file:

```CSS
/deep/ button#print {
  display: block !important;
}

/deep/ button#download {
  display: block !important;
}
```

**Comment by prasanthnsn11** [comment]
Hi @stephanrauh I cant able to reproduce the download icon even after i override the css !  Is there any other way to bring the download icon in mobile devices ?

**Comment by stephanrauh** [comment]
Maybe you've discovered a bug. Have a look at https://pdfviewer.net/smartphone. The simulated smartphone has a print button and a download button. For some reason, the image has gone lost, so you don't see the buttons although they are there. They even work.
