### ISSUE TITLE
window.print() is blank

### ISSUE THREAD

**Issue by AlbertoMontalesi** [stephanrauh/ngx-extended-pdf-viewer#1131]
**Describe the bug**
It's very simple, go here https://pdfviewer.net/extended-pdf-viewer/simple and call `window.print()` in the console. the page is blank. 

**Version info**
- 2.12.548

Happens on both latest Safari and Chrome

**Comment by stephanrauh** [comment]
This bug is caused by a CSS rule that's important for printing the PDF file:

```css
@media print {
  body {
    & > * {
      display: none !important;
    }
}
```

How much does it hurt? I could try to add dynamic CSS, but I'm afraid of the side effects. I suppose it's better if you overwrite the rule in your application.

**Comment by stephanrauh** [comment]
As it turns out, implementing your feature is easier than thought. You bugfix is going to land soon with version 13.0.0-alpha.6.
