### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by yaseen-nadaf** [stephanrauh/ngx-extended-pdf-viewer#114]
![image](https://user-images.githubusercontent.com/30219634/61949331-2f190680-afc8-11e9-9b3b-b236a7298ebd.png)

Check the First Heading in side menu "About false". Well, I didn't understand if that means something, hence filing this issue, but if it has any meaning then discard this issue.

**Comment by stephanrauh** [comment]
Indeed. When I'm grown-up, I should stop publishing debug code. :)

FWIW, the "false" showed the "isHandset" flag of Angular Material. I was pretty surprised by the results. Large screens are "false", tiny screens are "true". So far, so good. To my surprise, reducing the screen width suddenly jumped back to "false" before finally settling on "true". In other words: `isHandset()` is a bad choice to detect cellphone. Or I haven't got the idea behind it.

**Comment by stephanrauh** [comment]
Just updated the documentation. Thanks for reporting the bug!
