### ISSUE TITLE
PDF text missing in page(s) when using Android version 12

### ISSUE THREAD

**Issue by ajlsemana** [stephanrauh/ngx-extended-pdf-viewer#1140]
Anyone can help or encounter the same issue of missing text using Android 12? We are still currently using this NPM version "ngx-extended-pdf-viewer": "^3.7.2", since our app is running in Angular 6.

**Comment by stephanrauh** [comment]
I'm afraid I can't support such an old version of ngx-extended-pdf-viewer. I simple don't have enough time. As you may or may not know, this is a leisure-time project. But maybe I can give you some pointers how to solve the problem yourself.

Printing issues are almost always CSS problems. Are you using a CSS framework? If so, it may overwrite the CSS rules for printing. I've collected some hints here: https://pdfviewer.net/extended-pdf-viewer/troubleshooting (scroll down to "Trouble with printing").

**Comment by ajlsemana** [comment]
Actually, it is not a printing issue. Text missing is happening when the viewer is open the first time or being zoomed in or out. Appreciate your hint. Will dig deeper on this issue of Android 12. Thank you

**Comment by ajlsemana** [comment]
Just an FYI:

I tried also upgrading to latest "ngx-extended-pdf-viewer": "^11.2.0-alpha.1", but still issue remains with the missing text while viewing the PDF.

I think best solution for this now is to use window.open() if the user is using Android v12. :)

![image](https://user-images.githubusercontent.com/7235178/150510606-b11337cd-efd2-4377-a7e4-245b2bb73e02.png)

**Comment by stephanrauh** [comment]
All right, if the bug still lurks in the dark corners of version 11, I'm ready to look for it. :) 

Well, at least, if I can. I don't own an Android device. But maybe my limited Browserstack account helps.

But first I'd like to understand the issue. You've sent me a screenshot. Unfortunately, I don't know you document, so I don't know what is should look like. What's missing, precisely? And how can I reproduce your bug?

**Comment by ajlsemana** [comment]
Yes. This issue can be also replicated using a Browserstack account, which I shared you the snapshot above.

The issue is happening when you open the viewer at first load or doing zoom in/out. You will noticed that your PDF text content are missing somehow on any pages in random.

On my own experience we have a PDF that contains 3 pages and some of the text are missing during first load of the viewer or when you do zoom actions. Please do note that we tried also other PDF's that we have and same issue is happening there as well.

I decided for now to add a **temporary workaround** of adding a reload button that will empty the [src] and refill it back after 1sec timeout until the user saw the complete text per page. It's up to the user to click reload button several times until he got what he wants to see.

**Code Snippet:**
HTML:
<button title="Reload PDF Viewer" (click)="reloadPdfViewer(idx)">
    Reload PDF Viewer
</button>

TS:
reloadPdfViewer(paramIndex: number): void {
        try {
            this.tempPdfViewerSrc = "";

            setTimeout(() => {
                this.tempPdfViewerSrc = this.dialog[paramIndex].fileSourcePlain;
            }, 1000);
        } catch (ex) {
            this._globalService.exceptionError("reloadPdfViewer", ex);
        }
    }

Here is the snapshot. The one with red are the text missing on first page or can happen also on other subsequent pages.
![Screenshot 2022-01-22 115245](https://user-images.githubusercontent.com/7235178/150630447-db2891f6-9bad-4ec2-b1c2-c24ecc2ec789.jpg)

**Comment by stephanrauh** [comment]
How can I reproduce the bug? When I test my showcase in Browserstack, everything looks fine:

![image](https://user-images.githubusercontent.com/3045767/150636629-4241f4f3-199a-401f-b1de-aecf96f3a416.png)

**Comment by ajlsemana** [comment]
Try to create a new angular project, just a plain one.

You can install your npm then just call any pdf that has multi pages from your assets folder even during the init load of the page.

**Comment by stephanrauh** [comment]
Which device and which browser did you choose?

**Comment by ajlsemana** [comment]
Browserstack:
Pixel device v12
Chrome/Edge browser

Using Real Mobile:
Samsung S20+ v12

**Comment by stephanrauh** [comment]
Here's a reproducer project. Every once in a while, the black background of the PDF file isn't rendered. I guess that's pretty much the bug you're describing:
https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue1140

![image](https://user-images.githubusercontent.com/3045767/150638532-90cbb3a8-2747-4996-9904-578a85483759.png)

**Comment by ajlsemana** [comment]
Exactly. You can also use plain text only to easily see the missing text on a white pdf background.

Keep us posted and let us know how we can help you bro 😊

**Comment by stephanrauh** [comment]
@timvandermeij It's time to ask the expert. Tim, there seems to be a problem with pdf.js on Android 12. But of course, it only happens with the Chrome browser. Firefox renders the file nicely. I've opened your showcase (https://mozilla.github.io/pdf.js/web/viewer.html) in Browserstack on a real device. Every once in a while, part of the pages are dropped. You can see this in the screenshots below. The upper screenshot shows the Chrome browser, and the tracemonkey PDF file has a lot a white space. Below that is the Firefox screenshot, displaying the file correctly.

Have you ever heard about this problem? What might go wrong? How to debug it? Every http request is successful (status 200), and the console window only show the version info, as you can see in the third screenshot.

![image](https://user-images.githubusercontent.com/3045767/150639124-11e513ff-1335-40a0-84dd-69d60bd2e688.png)

![image](https://user-images.githubusercontent.com/3045767/150639246-7764cbee-945b-4821-989f-5bc069ba3fb7.png)

![image](https://user-images.githubusercontent.com/3045767/150639514-7a81a655-8274-423d-a94e-90487e99819d.png)

**Comment by timvandermeij** [comment]
I have seen this before, mostly indeed in combination with Chrome. In those cases it was always due to either a platform bug in Chrome or due to hardware acceleration/bad graphics drivers when rendering the canvases. The fact that Firefox works fine seems to point to there former more than the latter. Sometimes entire pages were missing, but mostly indeed only sections of a page like here. The following PDF.js issues seem very similar to this:

- https://github.com/mozilla/pdf.js/issues/5016
- https://github.com/mozilla/pdf.js/issues/12501
- https://github.com/mozilla/pdf.js/issues/4083

For debugging, perhaps there is console output where the browser logs warnings/errors, but the cases I have seen didn't really have useful console output since it's the browser's rendering engine or the graphics driver messing up. I think the best course of action would be to try to make a minimal reproducer and report it to the Chrome team via their bugtracker; perhaps it's a known upstream bug or otherwise they can debug further.

**Comment by stephanrauh** [comment]
@timvandermeij Thanks you very much!

@ajlsemana Even before Tim replied, my gut feeling said it has to do something with the browser. So I'm officially giving up. However, if you want to report the bug to the Chrome team, I'm going support you.

**Comment by stephanrauh** [comment]
I'm keeping this ticket open until we've decided whether to open the bug at the Chrome bug tracker or not.

**Comment by ajlsemana** [comment]
Thank you for explaining this issue further @timvandermeij @stephanrauh 

I suggest to keep this ticket open, and maybe we can raise a ticket to Chrome and Edge bug tracker for them to take action.

Anyways, thanks again for your time guys. Really appreciated.

**Comment by stephanrauh** [comment]
Two months have passed. What's the current state of affairs?
