### ISSUE TITLE
minHeight cannot be set through HTML

### ISSUE THREAD

**Issue by OldShaterhan** [stephanrauh/ngx-extended-pdf-viewer#1143]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). No.
- Does the bug also happen on https://pdfviewer.net/simple? No.
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template I'll try to provide it later.

**Describe the bug**
I noticed that `minHeight` cannot be set through HTML, however it is available through TS. I wonder if this is planned or not (minHeight is not mentioned on: https://pdfviewer.net/extended-pdf-viewer/attributes ), but it might be helpful, especially basing on description for `height`:
Define the height of the PDF window. By default, it's 100%. Unfortunately, on most web pages, 100% translates to a height of 0 pixels. In this case, the height is set to fill all the available space. More precisely, the all the space to the bottom of the window. If that's less then 100 pixel, the height is set to 100 pixel. Note that this is just an initial setting. It doesn't change when the window is resized.

**Version info**
- 11.1.0

**Desktop (please complete the following information):**
 - Chrome
 

**Screenshots**
![image](https://user-images.githubusercontent.com/1622866/150950529-110660ce-5c76-443d-bd1e-91d11e6e00a8.png)

**Comment by stephanrauh** [comment]
That's just a use-case I didn't think of. I just wanted to make sure the PDF viewer is visible. If the minimum height is 0 pixels, most developers believe the PDF viewer isn't that at all.

I suppose I can safely expose `[minHeight]` as an attribute.

**Comment by stephanrauh** [comment]
The feature is going to land with version 12.1.0 in a few minutes.
