### ISSUE TITLE
Drawing on top of PDF file

### ISSUE THREAD

**Issue by OldShaterhan** [stephanrauh/ngx-extended-pdf-viewer#1144]
**Is your feature request related to a problem? Please describe.**
I need functionality of drawing on top of PDF - especially rectangles, with ability to read it's location on PDF level.

**Describe the solution you'd like**
Clear API that would allow drawing on top of PDF files, with ability to access drawn items data (position, size)

**Describe alternatives you've considered**
I found solutions as below, but I'm not sure how can I get to the PDF canvas in "elegant way" through PDF viewer.
https://github.com/mozilla/pdf.js/issues/11285
https://github.com/mozilla/pdf.js/issues/8191

**Additional context**
-

**Comment by stephanrauh** [comment]
Well - it's a PDF viewer, not a PDF drawing library. I suspect you're looking for something like annotation support. That's probably a cool feature and an interesting project in itself, but I'm afraid modifying PDF file is out of scope. It's a leisure-time project, and I simply don't have enough leisure-time to do that.

However, if you're happy with drawing something on the canvas, that's easy. `(pageRendered)` is a good starting point. At the moment, the canvas is not an attribute of. the `PageRenderedEvent`, but that's no problem: you get is using a selector like `document.querySelector("[data-page-number='1'] canvas")`.

**Comment by OldShaterhan** [comment]
Just to clarify - I don't need creating annotations with constant changing of PDF file content, I hope canvas drawing will be good enoguh. I'll try your suggestion. Thanks!

**Comment by digaus** [comment]
> Just to clarify - I don't need creating annotations with constant changing of PDF file content, I hope canvas drawing will be good enoguh. I'll try your suggestion. Thanks!

I got this working with `signature_pad` and `pdf-lib` but only in singlepage mode.

For every PDF canvas rendered I create my own canvas and signature pad with the exact same dimensions and then insert it on top of the PDF canvas.

When zooming you you to rescale the signature and set the canvas again:


```
        const page: number = this.myNgxExtendedPdfViewerService.getCurrentlyVisiblePageNumbers()[0] - 1;
        const signatureCanvas: HTMLCanvasElement = this.signatureCanvasElements[page];
        const canvas: HTMLCanvasElement = document.getElementById('viewer').querySelector('canvas');
        const ratio: number = Math.max(window.devicePixelRatio || 1, 1);
        if (signatureCanvas) {
            const factor: number = (canvas.offsetWidth * ratio) / signatureCanvas.width;
            const data: PointGroup[] = this.signaturePads[page].toData();
            const scaleData: PointGroup[] = data.map((pointGroup: PointGroup) => {
                const points: BasicPoint[] = pointGroup.points.map((point: BasicPoint) => {
                    return {
                        x: point.x * factor,
                        y: point.y * factor,
                        time: point.time * (factor * factor),
                    };
                });
                return {
                    color: pointGroup.color,
                    points,
                };
            });
            signatureCanvas.width = canvas.offsetWidth * ratio;
            signatureCanvas.height = canvas.offsetHeight * ratio;
            signatureCanvas.getContext('2d').scale(ratio, ratio);
            signatureCanvas.style.position = 'absolute';
            signatureCanvas.style.top = '0';
            signatureCanvas.style.display = 'initial';
            signatureCanvas.style.zIndex = '1000';
            signatureCanvas.style.height = canvas.offsetHeight.toString() + 'px';
            signatureCanvas.style.width = canvas.offsetWidth.toString() + 'px';
            canvas.parentElement.appendChild(signatureCanvas);
            this.signaturePads[page].fromData(scaleData);
        } 
```

Here is how I merge the signatures: 
```

    private async getModifiedPdf(): Promise<PDFData> {
        this.loading$.next(true);
        const pdfBlob: Blob = await this.myNgxExtendedPdfViewerService.getCurrentDocumentAsBlob();
        const existingPdfBytes: ArrayBuffer = await pdfBlob.arrayBuffer();
        const pdfDoc: PDFDocument = await PDFDocument.load(existingPdfBytes);
        let page: number = 0;
        for (const signaturePad of this.signaturePads) {
            const svgSignature: string = signaturePad.toDataURL('image/png');
            const jpgImageBytes = await fetch(svgSignature).then((res) => res.arrayBuffer());
            const jpgImage = await pdfDoc.embedPng(jpgImageBytes);
            pdfDoc.getPage(page).drawImage(jpgImage, { x: 0, y: 0, width: pdfDoc.getPage(page).getWidth(), height: pdfDoc.getPage(page).getHeight() });
            page++;
        }
        const file_content: string = await pdfDoc.saveAsBase64();
        const name: string = this.enableSignature || this.hasSignature?.value ? `${this.pdf.name.split('.pdf')[0]}.signed.pdf` : this.pdf.name;
        const result: PDFData= { ...this.pdf, file_content, name };
        this.loading$.next(false);
        return result;
    }

```

**Comment by stephanrauh** [comment]
@digaus Awesome!

**Comment by OldShaterhan** [comment]
@digaus thanks! Actually I'm looking for drawing rectangles instead, but maybe it will help me somehow! 😊
