### ISSUE TITLE
plugin blocked after loading pdf (page not responding)

### ISSUE THREAD

**Issue by matiasAS** [stephanrauh/ngx-extended-pdf-viewer#1160]
When I open a pdf obtained from my server in base64, I can see it but the scroll and the entire page is blocked and it appears "the page does not respond"

The pdf I want to view is an invoice.

I can send the pdf file by mail if you need it

**Version info**
- ^10.5.0

**Desktop (please complete the following information):**
 - Desktop, Chrome
 
**Smartphone (please complete the following information):**
 - Notebook asus TUF gaming

**Comment by stephanrauh** [comment]
What happens when you open your file on https://pdfviewer.net/simple? Does the application freeze, too?

**Comment by matiasAS** [comment]
all good, in the console I can see the following:

PDF viewer: ngx-extended-pdf-viewer running on pdf.js 2.10.562
app.js:1579 PDF 3b1aefd2295dadaf502a480288d4d601 [1.4 Qt 5.5.1 / -] (PDF.js: 2.10.562) modified by ngx-extended-pdf-viewer)

has something to do with that?

**Comment by stephanrauh** [comment]
"All good" means the PDF viewer showcase does not freeze?

The message simply means the PDF viewer has been loaded correctly, and at least some of the initialization was successful. If that's the only message, I'd say everything's fine. Did you check the console messages of the frozen application, too?

**Comment by matiasAS** [comment]
"all good" means that in https://pdfviewer.net/simple the pdf is displayed perfectly.

In my application it keeps freezing and the console log is the same as before:

PDF viewer: ngx-extended-pdf-viewer running on pdf.js 2.10.562
app.js:1579 PDF e02447847bdd4d4ec074aaaead8f0bd7 [1.4 Qt 5.5.1 / -] (PDF.js: 2.10.562) modified by ngx-extended-pdf-viewer)


My question is, does the version of pdf.js or angular 12 have anything to do with it?

**Comment by stephanrauh** [comment]
> does the version of pdf.js or angular 12 have anything to do with it?

No, I don't think so. To analyze the problem, please create a new project:

- `ng new my-favorite-project`
- `cd my-favorite-project`
- `ng add ngx-extended-pdf-viewer`
- replace the content of `app.component.html` by `<app-example-pdf-viewer></app-example-pdf-viewer>`
- check if the application works
- put your invoice PDF into the project and try again
- if that's still OK, load your invoice PDF as a BASE64 string

**Comment by matiasAS** [comment]
In a clean project with angular 13 and the latest version of the module, my pdf opens perfectly. I have updated the module in my project and now it gets stuck with any pdf

**Comment by stephanrauh** [comment]
Weird. But it's exactly what I expected. There must be something special about your project. You can try to remove features from your project until it stops freezing. Maybe there's a third-party library using some JavaScript interfering with the PDF viewer?

**Comment by stephanrauh** [comment]
BTW, you're probably the first developers ever who's used the brand-new `ng add ngx-extended-pdf-viewer` schematic. Did it work well?

**Comment by matiasAS** [comment]
As I said before, in a clean project yes, no problem, but not in my project.

I have returned to the previously installed version of the 10.5.0 module and now if they open the pdfs except the one I have had a problem from the beginning

I have done one more test of manually opening the pdf with problems and it has not been stuck. It's strange

**Comment by matiasAS** [comment]
@stephanrauh hello

I have updated to angular 13, ionic6 and the module to version 11.1.0 and the page is blocked

i cant go back to 10.5.0 because it is not compatible with angular 13 please i need urgent help to solve this problem

**Comment by matiasAS** [comment]
@stephanrauh  I share the code fragment that I am using in case something is my mistake.

I make a request to the backend and get the base64 of the pdf

  getDispatchGuidePdfFromOpenfactura() {
    this.presentLoading('Obteniendo PDF desde openfactura, por favor espere...')
    let data = {
      dispatch_guide: this.dispatchGuide.identity
    }
    this.dispatchGuideService.getDispatchGuidePdfFromOpenfactura(data).subscribe(res => {
      if (res.error == null) {
        this.ionicToastService.showToast('PDF obtenido correctamente ', 2000, 'success')
        this.base64Src = res['PDF_BASE_64']
      } else {
        this.ionicToastService.showToast('Error al obtener PDF', 10000, 'danger')
        this.dismissLoading()
        this.modalCtrl.dismiss()
      }
    }, (err: HttpErrorResponse) => {
      this.ionicToastService.showToast('Error al obtener PDF: ' + err.message, 10000, 'danger')
      this.dismissLoading()
      this.modalCtrl.dismiss()
    })`

and html:

`<ion-content>
  <div id="outerContainer">
    <div class="pdf-container">
      <ngx-extended-pdf-viewer [base64Src]="base64Src" useBrowserLocale="true"
                               (pageRendered)="pdfLoaded()"></ngx-extended-pdf-viewer>
    </div>
  </div>
</ion-content>
`
`

**Comment by matiasAS** [comment]
<ion-content>
  <div id="outerContainer">
    <div class="pdf-container">
      <ngx-extended-pdf-viewer [base64Src]="base64Src" useBrowserLocale="true"
                               (pageRendered)="pdfLoaded()"></ngx-extended-pdf-viewer>
    </div>
  </div>
</ion-content>

**Comment by matiasAS** [comment]
![Captura de pantalla de 2022-02-01 00-48-19](https://user-images.githubusercontent.com/7276332/151910153-b971a6a1-49e0-40da-a691-126f3717a0a6.png)

**Comment by stephanrauh** [comment]
At first glance, I can't spot any mistake in your sourcecode. Maybe your BASE64 code isn't correct. What happens if you use this BASE64 file? https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/main/src/app/extended-pdf-viewer/base64/secondPdfBase64.ts

**Comment by stephanrauh** [comment]
If you're still stuck, please send me a reproducer. That's a minimal project that allows me to reproduce the bug in five minutes. In particular, I don't want to install any backend (because that tends to be a matter of hours, not minutes).

BTW, don't waste time translating the reproducer to English. I'm fairly proficient at reading and writing Spanish.

¡Muchas gracias!
Stephan

**Comment by matiasAS** [comment]
@stephanrauh speak spanish?, i am from Chile!!!

**Comment by stephanrauh** [comment]
Pues, me cuesta mucho hablarlo, por falta de practica... ¡pero leer español es ningún problema!

**Comment by matiasAS** [comment]
@stephanrauh Puede que tenga que responder en ingles, pero me complica algunas cosas ya que debo usar el translate de google, jajaja. Te explico en español entonces.

Mi código hace lo siguiente:
En una page tengo una MatTable de angular material y en una columna un boton para ver una factura. Hago click, abro un modal con ModalController y en el ngOnInit de ese modal hago un request a mi backend para que me entregue la base64 del pdf. Cuando llega, actualizo una variable del component, la que se llama base64Src y se carga el PDF.

Todo funcionaba bién con la versión del módulo 10.5.0, menos una factura con 20 items (abría hasta con 16 items). Luego este problema intenté actualizar a la última versión del modulo y ningún PDF habría. 

Despues de este error fue cuando me recomendaste un proyecto en blanco, que lo hice y funcionaba sin problemas abriendolo dirécto de una url sin hacer el request.

Como funcionaba con Angular13/Ionic6, dije, ok, actualizo todo mi proyecto y pruebo, y me encuentro con la sorpresa que también se bloquea la página, como que todo queda en cache, y cuesta para que el se vea la interfaz (cualquier ruta) del proyecto en el navegador.

Haciéndo más pruebas, si hago el request antes de abrir el modal, ahí si funciona. Hasta ese momento estaba almacenando en mi base de datos del backend la base64 del PDF y XML (en Chile es obligatorio que para los documentos tributarios haya por cada PDF un XML),entonces ejecuté mi plan B que consiste en guardar los archivos en el servidor y desde angular abrir el pdf por la url y no base64. 

Todo funcionaba perfecto hasta que llegué a un PDF que al abrirlo con el módulo me aparece un error que dice algo como que el archivo tiene 0 bytes, pero si lo abro directo en el navegador, puedo ver ese pdf sin problemas.

Dado esto, y para no arriesgarme algún bloqueo de la página es que le pregunté a mi cliente si le parece bién que los pdfs se vean en una nueva pestaña, me dijo que si y ahora cuando lo que hago es en angular formar una url con una cierta lógica del archivo y hacer un window.open(this.url)

Saludos



@stephanrauh I may have to answer in English, but it complicates some things since I have to use google translate, hahaha. I'll explain in Spanish then.

My code does the following:
On one page I have an angular material MatTable and on one column a button to view an invoice. I click, I open a modal with ModalController and in the ngOnInit of that modal I make a request to my backend to deliver the base64 of the pdf. When it arrives, it updates a component variable, the one called base64Src, and the PDF is loaded.

Everything worked fine with module version 10.5.0, except for an invoice with 20 items (it opened with up to 16 items). Then this problem I tried to update to the latest version of the module and no PDF would have.

After this error it was when you recommended me a blank project, which I did and it worked without problems opening the direct url without making the request.

Since it worked with Angular13/Ionic6, I said, ok, I update my whole project and try, and I found the surprise that the page also crashed, like everything is cached, and it costs for the interface to be seen (any route ) of the project in the browser.

Doing more tests, if I make the request before opening the modal, then it works. Until that moment I was storing in my backend database the base64 of the PDF and XML (in Chile it is mandatory for tax documents to have an XML for each PDF), so I executed my plan B which consists of saving the files on the server and from angular open the pdf by the url and not base64.

Everything worked perfectly until I got to a PDF that when I open it with the module I get an error that says something like the file has 0 bytes, but if I open it directly in the browser, I can see that pdf without problems.

Given this, and in order not to risk any blocking of the page, he asked my client if it is okay for the pdfs to be seen in a new tab, he told me yes and now when what I do is in angular to form a url with some file logic and do a window.open(this.url)

Greetings

**Comment by stephanrauh** [comment]
¿Es posible combinar Angular Material con Ionic? ¿Como [este](https://www.freakyjolly.com/ionic-angular-material-how-to-install-material-and-use-its-components-in-ionic-app/)? ¡No sabía antes!

Creo que podemos encontrar y solvers esta bug. Parece que es bastante simple crear un _reproducer_:

- No necesitamos un backend. Supongo que puedes copiar los archivos PDF en la carpeta `assets` y todavía puedes mostrar el problema.
- Ademas, elimina todas las paginas de tu aplicación, con la excepción de la pagina que contiene la `MatTable` y, claro, el modal mostrando el PDF.
- El contenido del `MatTable` puede ser un array constante. Come dice antes, no necesitamos algún backend. Al menos, creo que no es el backend que cause la falla.

Supongo que puedes recopilar este reproductor en menos de una hora. Después, envíame tu proyecto _reproducer_. Mi dirección del correo electrónico es webmaster1 arroba beyondjava punto de. Has dicho de datos tributarios. Por eso, envíame archivos seudónimazados y - sí es posible - sin datos reales, por favor.

> le pregunté a mi cliente si le parece bién que los pdfs se vean en una nueva pestaña

100% de acuerdo. Es un rompecabezas para mí :) - pero tu cliente necesita una solución. No obstante, ¡vamos a resolverlo!

**Comment by matiasAS** [comment]
Hola muchas gracias, pero no te preocupes, dejaré de usar el plugin para
este proyecto, al menos por ahora

Te puedo asegurar que si tengo otro proyecto me pondré en contacto contigo
para ver el problema

Yo creo que sí es necesario el backend porque el problema es cuando llega
la base64 en el response

Saludos

**Comment by stephanrauh** [comment]
¿Tiene el formato base64 algo que ver con este falla de verdad? Y sí es así, ¿podríamos crear un archivo de format base64 in la carpeta assets?

Stephan

**Comment by stephanrauh** [comment]
Let's close the ticket for the moment, because it seems to be hard to reproduce the bug and @matiasAS has found a workaround.

Talking of which: there are two great alternative to my library out there. Check out https://www.npmjs.com/package/ng2-pdf-viewer, which seems to be the market leader. It's a no-nonsense but useful library displaying PDF files without all the bells and whistles I've implemented. In special cases, I also recommend using https://www.npmjs.com/package/ng2-pdfjs-viewer. The only drawback is it's used only once in a while. The big advantage of ng2-pdfjs-viewer is it hides the PDF viewer in an iFrame. That sounds bad, but actually, it's good: it means you can put multiple PDF viewers on the same page.
