### ISSUE TITLE
Expose PDFViewer.imageResourcesPath to options

### ISSUE THREAD

**Issue by MKITConsulting** [stephanrauh/ngx-extended-pdf-viewer#117]
Hi,

if a PDF document contains PDF annotations like a "comment", there will be a missing image link error as pdfjs image assets are missing. This can be "fixed" with proper angular.json settings and it would make sense to adjust the README.MD for this case. 

But my main concern is this one: The default imageResourcesPath for PDFjs is "/images/". As I don't want to mess up my /images/ folder with all the PDFjs SVGs it'd be nice to have an option that handles this and initializes the PDFViewer.imageResourcesPath property right. I do not see any point to do this outside of your component.

Best regards, keep it up on this great lib!

**Comment by stephanrauh** [comment]
Which images are you referring to? I've found only this image, but that doesn't look like the images you're talking about. https://github.com/mozilla/pdf.js/tree/master/src/images

**Comment by MKITConsulting** [comment]
Take this test document: [Testdocument.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/3452042/Testdocument.pdf)

If you use ngx-extended-pdf-viewer as documented you'll end up with a broken image as you'll have to copy the "pdfjs-dist/web/images/*" to your "/images/" folder in order to fix that. If you copy them to "assets/images" PDFjs won't find them. (see images below) So it would be nice to expose the "imageResourcesPath" property of PDFjs that enables the definition of another image repository to your component options.

This is how it looks like with no further asset operations:
![image](https://user-images.githubusercontent.com/29451012/62215999-3e24fd80-b3a8-11e9-9420-ad797b8c341c.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/29451012/62215883-0c139b80-b3a8-11e9-90f3-a513a2ad0fdd.png)

**Comment by stephanrauh** [comment]
I see. I've inlined every image into the CSS file, so there's no need for the `images` folder. Too bad there are a few exception, such as the `*.svg` images. I'll care about that. It's good you've noticed that during the release-candidate phase!

**Comment by stephanrauh** [comment]
Most likely, I'm going to put the SVG images in a folder like `node_modules/ngx-extended-pdf-viewer/assets/images`. You can use the `angular.json` to copy these files into the `assets/images` folder of your application. That's still messing up the folder, but "only" in production. 

Given all this information, do you still need the image path to be configurable?

**Comment by stephanrauh** [comment]
Shipped with version 1.0.0.
