### ISSUE TITLE
Width of secondaryToolbar too wide

### ISSUE THREAD

**Issue by MKITConsulting** [stephanrauh/ngx-extended-pdf-viewer#118]
The "width:100%" property leads to a toolbar that is too wide (tested in current Chrome and Firefox on Windows 10) for "ngx-extended-pdf-viewer" version "1.0.0-rc.6". (see image)

![image](https://user-images.githubusercontent.com/29451012/62202672-00b17780-b38a-11e9-8dcd-1c2725709cc0.png)

**Comment by stephanrauh** [comment]
Oops. That's an unexpected side effect. The 100% was meant to affect the regular toolbar only.

**Comment by stephanrauh** [comment]
Status update: I'm working on it. I'm not yet 100% satisfied, so I'm still fine-tuning a few bits and pieces. But the next release is definitely in sight!

**Comment by stephanrauh** [comment]
I've just published version 1.0.0-rc.7. The secondary toolbar, the find bar, and the thumbnail bar look fine on Chrome, Firefox, and Safari - all tested on OSX.

TODO left: repeat the same tests on Windows, including Edge and IE11.

**Comment by MKITConsulting** [comment]
Thank you, looks good now. I can confirm that it's working on current Edge.

**Comment by stephanrauh** [comment]
I've published 1.0.0-rc.8, which fixes IE11 compatibility.
