### ISSUE TITLE
Prints empty console message

### ISSUE THREAD

**Issue by muuvmuuv** [stephanrauh/ngx-extended-pdf-viewer#1182]
I am a little confused where this message is coming from ^^.

![Bildschirmfoto 2022-02-08 um 08 34 20](https://user-images.githubusercontent.com/11534760/152939630-f00447ba-90b8-48c8-a8bd-5846e39b0ae0.png)

![Bildschirmfoto 2022-02-08 um 08 36 26](https://user-images.githubusercontent.com/11534760/152939781-8c5d529c-b8a8-433a-932e-9ccdeb8dbc2d.png)

**Version info**

"ngx-extended-pdf-viewer": "^11.2.0-alpha.1"

**Desktop (please complete the following information):**
 - Browser Brave
 
**Smartphone (please complete the following information):**

**Comment by stephanrauh** [comment]
The message was my attempt to prevent tree-shaking from shaking the `NgxConsole` class away. I've just published version 11.2.0, using a slightly different approach. The message is gone now.
