### ISSUE TITLE
Checkboxes variation on form initialisation and form update

### ISSUE THREAD

**Issue by namblard-sword** [stephanrauh/ngx-extended-pdf-viewer#1183]
Hi, it's me again to bother you.

**Describe the bug**
I've come across a weird use case of pdf checkboxes, used as radio buttons (same name for a given set of checkbox, different exported values) thus messing with formData on your pdfviewer.
The thing is that upon initialization, for checkboxes you're receiving from pdfjs ${checkboxName}/${exportValue}: true or false.

Then when clicking on the described checkboxes, you receive only the ${checkboxName}: true or false.

I'd need to know both on initialisation and on update which checkbox has been checked (or unchecked), meaning it would be perfect to get every time ${checkboxName}/${exportValue}.

Does this ring a bell to you ? 

**Version info**
Version used : 11.0.0-alpha.13

**Desktop (please complete the following information):**
 Tested on Chromium and safari
 
**To Reproduce**
[checkboxes.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/8023713/checkboxes.pdf)

If you need anymore info or help don't hesitate to ping me ! 

Thank you for your time and help

**Comment by stephanrauh** [comment]
I suspect ngx-extended-pdf-viewer does the wrong thing. :) After debugging, I found out that loops over all three checkboxes and reports their state to Angular (https://github.com/stephanrauh/pdf.js/blob/8ff3f24b1f5cfba05ffd1f7fce477e90cae73b5f/src/display/annotation_layer.js#L1186-L1194). The problem is that all three checkboxes are called "Checkbox 1", so basically Angular receives random nonsense.

Instead, I should report the export value:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/3045767/153500036-19cf55af-d46e-4155-9b5b-e5d90d27f127.png">

I've prepared a change fixing the problem. But before pushing it, I wonder if it's a breaking change that annoys other developers. What's your opinion? Is it a feature that's already broken, so it can't get worse, or did some developers find a clever way to cope with the bug?

**Comment by stephanrauh** [comment]
If you want to review my changes - here you are:

From 596a3cd5074832f5af2d81c9666641174750e3e9 Mon Sep 17 00:00:00 2001
From: Stephan Rauh <3045767+stephanrauh@users.noreply.github.com>
Date: Thu, 10 Feb 2022 22:56:13 +0100
Subject: [PATCH] stephanrauh/ngx-extended-pdf-viewer#1183 deal correctly with
 checkboxes behaving as radio buttons

---
 src/display/annotation_layer.js   | 15 ++++++++++++++-
 src/display/annotation_storage.js |  5 +++++
 2 files changed, 19 insertions(+), 1 deletion(-)

diff --git a/src/display/annotation_layer.js b/src/display/annotation_layer.js
index f45e16860..ee1d2850a 100644
--- a/src/display/annotation_layer.js
+++ b/src/display/annotation_layer.js
@@ -1208,7 +1208,20 @@ class CheckboxWidgetAnnotationElement extends WidgetAnnotationElement {
         }
         storage.setValue(checkbox.id,
           this.data.fieldName, // #718 modified by ngx-extended-pdf-viewer
-          { value: curChecked });
+          {
+            value: curChecked,
+            exportValue: checkbox.exportValue // #1183 modified by ngx-extended-pdf-viewer
+          });
+      }
+      if (!value) {
+        if (data.exportValue) {
+          storage.setValue(id,
+            this.data.fieldName, // #1183 modified by ngx-extended-pdf-viewer
+            {
+              value: true,
+              exportValue: null
+            });
+        }
       }
       storage.setValue(id, this.data.fieldName, { // #718 modified by ngx-extended-pdf-viewer
         value: checked
diff --git a/src/display/annotation_storage.js b/src/display/annotation_storage.js
index c08d1a2a3..5b6f2f954 100644
--- a/src/display/annotation_storage.js
+++ b/src/display/annotation_storage.js
@@ -125,6 +125,11 @@ class AnnotationStorage {
             // ignore this field
           } else if (value.radioValue) {
             window.setFormValue(fieldname, value.radioValue);
+          } else if (value.exportValue) { // #1183 modified by ngx-extended-pdf-viewer
+            if (value.value) {
+              window.setFormValue(fieldname, value.exportValue);
+            }
+          }
           } else {
             for (const val of Object.values(value)) {
               window.setFormValue(fieldname, val);
-- 
2.35.1

**Comment by namblard-sword** [comment]
Hello,

Honestly I don't know but it's indeed a breaking change.
But even though they found a way to fix, this should ease their pain I think.

If anyone is annoyed by that they can either stay to a former version or communicate how they fixed it ?

It's up to you to decide if it's worth or not to merge that.

Sorry for the inconvenience and thank you for your time

**Comment by stephanrauh** [comment]
I thinks it's a breaking change that can't be avoided. So I've updated the version number to 12.0.0.

Please update to version 12.0.0-alpha.0 and test the new behavior. Is it an improvement?

**Comment by stephanrauh** [comment]
I think we can close the ticket now. If you think differently, just add a comment to this ticket.
