### ISSUE TITLE
Build Warning

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#1194]
When building my application I get the following warning:

- ngx-extended-pdf-viewer [es2015/esm2015] (https://github.com/stephanrauh/ngx-extended-pdf-viewer)
Encourage the library authors to publish an Ivy distribution.

Is this something that will be addressed in a future release?  Thanks!

**Comment by stephanrauh** [comment]
Actually, I've already dropped pre-Ivy support a couple of weeks ago. If you're using version 11 of the library, the message should be gone. Can you confirm that?

(More precisely, I've dropped pre-Ivy support with version 11.0.0-alpha.8).

**Comment by stephanrauh** [comment]
I've closed this ticket, but I'm still listening to this channel. If the issue is still an issue to your for some reason, just tell me!

**Comment by stephanrauh** [comment]
Hooray!
