### ISSUE TITLE
Allow programmers to clear the PDF programmatically even if the user has opened it

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1197]
The discussion of #71 (near https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/71#issuecomment-1034283526) revealed that programmers can't un-display the PDF file if the user has opened it using the menu. More precisely, sometimes it works, but only once.

That's a sort of a contradiction to what I've documented here: http://localhost:4200/extended-pdf-viewer/multiple-documents. 

Let's examine if it's possible to reset the PDF viewer by setting `[src]="undefined"` reliably and multiple times.

Kudos to @luis-cosillo who made me aware of this nuisance!

**Comment by luis-cosillo** [comment]
disculpa la molestia pudiste ver este problema de poder limpiarle el src o que tenga una opcion como de reinicio para limpiar el archivo que allan subido, disculpa las molestias??

**Comment by stephanrauh** [comment]
No te preocupes por molestarme. Estas molestias son importante para mí: ¡indican cual parte de mi proyecto de afición esta en alta demanda!

**Comment by stephanrauh** [comment]
(English translation below)

Actualiza a versión 12.0.0-alpha.2. Acabe encontrar una solución. Al menos, lo espero: durante mi prueba, vi errores extraños, pero no creo que son relacionados a tu problema. Ví algunas `MissingPdfExceptions` después seleccionar un archivo de mi disco duro. No obstante, limpiar el visor PDF parece que funcionar sin problemas.

Puedes probarlos y decirme si funciona o no? ¡Gracias!

Please update to version 12.0.0-alpha.2. I've managed to implement a solution. At least, I hope so: during my test, I ran into weird errors. After selecting a file from my local hard disk, I saw some `MissingPdfExceptions`. But I don't think this weid behavior is related to this issue. Quite the contrary, clearing the PDF viewer seems to work like charm.

Can you run a test and check whether the feature works or not, please?

Thanks in advance,
Stephan

**Comment by luis-cosillo** [comment]
ya baje a esa versión y al cargar por segunda vez otro pdf ya no limpia el control. Solo lo hace la primera vez.

**Comment by stephanrauh** [comment]
Allow me to answer in English - it's late in the evening over here, and I'm tired. :)

I wonder if you've run into a caching problem. If everything works as intended, when the user opens a PDF, this line should be reached:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/e9aa61dab0f2498b6009c978e41ef9dfd992dac6/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L811-L813

That, in turn, should allow the viewer to detect the change here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/e9aa61dab0f2498b6009c978e41ef9dfd992dac6/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1690

Please add breakpoints at these lines and tell me what happens. Is it really a caching problem, or did I miss something?

**Comment by stephanrauh** [comment]
¿Algun progreso?

**Comment by luis-cosillo** [comment]
aun tengo pendiente hacer lo de los puntos de interupcion y ver que esta llegando, que me han tenido algo ocupado, pero si lo voy a realizar para poder ver cual es el problema

**Comment by stephanrauh** [comment]
¡Vale! Abriendo el ticket de nuevo :)

**Comment by luis-cosillo** [comment]
perdon no te habia contestado, baje la ultima version que hiciste y alli ya funciona bien la parte de cargar diferentes documentos, solo la de eliminación o sea limpiar el control, esa si no funciona, si el control contiene alguna funciona para hacer eso me cuentas.

**Comment by stephanrauh** [comment]
Parece que fuí demasiado rapido :)

**Comment by luis-cosillo** [comment]
solo un poco, jajaja pero solo ese punto que cuando quieres limpiar el control, o resetearlo, no lo hace, se queda el mismo documento en pantalla.

**Comment by stephanrauh** [comment]
¡Gracias! Pensé que funciona... pero si dices que no funciona, tengo que ver al problema de la limpieza de nuevo.

**Comment by stephanrauh** [comment]
Encontré y depuró una otra falla. Ahora, puedes

- abrir un archivo PDF usando el botón del visor PDF
- limpiar `[src]`
- abrir el mismo archivo de nuevo.

Antes de mi depuración no paso nada. Ahora, el archivo se abre.

**Comment by stephanrauh** [comment]
Ahora es tu turno. Durante mis pruebas, pudo limpiar e abrir todas los archivos sin problemas con la version 13.0.0-alpha.11.

**Comment by luis-cosillo** [comment]
Listo ya actualicé e hice esto que te mando y allí ya me funciono bien.

Pasos que realice, cargue un archivo, volví a cargar otro, limpie y funciono, cargue otro, volví a limpiar y lo hizo, cargue otro PDF y volví a limpiar y si limpia el control.

```
limpiarPDF() {
        setTimeout(() => {
            this.valorURLPDF = undefined;
            this.valorURLPDF = '';
            this.valorBase64PDF = '';
        }, 100);
        this.valorURLPDF = undefined;
        this.valorBase64PDF = '';
}
```
