### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#1199]
This is just a wish item.

Is there away to add annotations? Maybe something out there that can do this with pdfjs?  For example, we would like to add a toolbar where the user can:

1. Add Stamps, ie. Denied, Approved, rejected, etc.
2. Add notes
3. Redact
4. Circle areas
5. Add highlights
6. etc. 

I have searched around and find some hints that it is possible but nothing concrete that would help. So I am just curious if more experienced people with pdfjs have any clue or if there is some documentation out there. 

Thanks!

**Comment by pedrojrivera** [comment]
I should have gone to the next page as I found someone else asking the same question. My bad. 

https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/647

**Comment by stephanrauh** [comment]
Yeah, this is a PDF viewer, not a PDF editor. I'm not familiar with the PDF format, and I'm afraid annotation support would take a lot of time to develop and even more time to maintain.

On the other hand, if someone's contributing a pull request, I'm ready to merge it. Maybe it's possible to create an optional plugin allowing users to add annotations both programmatically and manually.

Any volunteers?
