### ISSUE TITLE
Not able to navigate to a Page just after load 

### ISSUE THREAD

**Issue by kakroo** [stephanrauh/ngx-extended-pdf-viewer#120]
**Describe the bug**
I am creating an angular app having a feature which can navigate directly to a specific page no. after pdf is loaded.

```typescript
 public onPageLoaded()
{
      this.page=this.globalPage;
 }
 public onPageRendered()
{
      this.page=this.globalPage;
}
```
```html
  <ngx-extended-pdf-viewer
    [src]="filePathAndName"
    backgroundColor="#ffffff"
    [height]="'90vh'"
    [useBrowserLocale]="true"
    [zoom]="90"
    [page]="page"
    (pagesLoaded)="onPageLoaded()"
    (pageRendered)="onPageRendered()"
    > 
```
i'm getting the url of the PDF and the page number to be navigated to from an API. The PDF loads fine, but i'm not navigated to the page number. Tried doing it on both pagesLoaded & pageRendered but that did not work.

Version - 0.9.49

**Version info**
- Version of ngx-extended-pdf-viewer - Version - 0.9.49
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)
Happening for all PDF's that i tested

**Comment by stephanrauh** [comment]
When I tried your code snippets, it worked, just a bit slowly. I suspect the problem is you're setting the page in one of the callback functions. It's easier and more reliable to do it immediately:

```html
<ngx-extended-pdf-viewer
    [src]="filePathAndName"
    backgroundColor="#ffffff"
    [height]="'90vh'"
    [useBrowserLocale]="true"
    [zoom]="90"
    [page]="globalPage"
    > 
```

**Comment by stephanrauh** [comment]
Please report back even if this solves your bug, so I can close the bug.

**Comment by stephanrauh** [comment]
@kakroo Any progress on your side?

**Comment by kakroo** [comment]
@stephanrauh , sorry for the late reply.
No, it did not work for me. When i try to switch the page it does not work.
You can find the code here. https://github.com/kakroo/PDF-Zoning

**Comment by stephanrauh** [comment]
Thanks for the reproducer! I've managed to reproduce and solve the bug.

Upgrading to version 1.0.2 should solve the problem.

**Comment by stephanrauh** [comment]
BTW, after updating to 1.0.2 you probably only need one of the two variables `page` and `globalPage`. Basically, me bugfix simply followed your idea: I set the application page in the eventlistener `pagesloaded`. That wasn't reliable enough (still too early?), so I wrapped it in another timeout.

**Comment by kakroo** [comment]
Thanks
