### ISSUE TITLE
Scroll bar when using pageViewMode "Single", zoom: "page-fit" and showborders false

### ISSUE THREAD

**Issue by jpb-keystone-solutions** [stephanrauh/ngx-extended-pdf-viewer#1201]
**Describe the bug**
When displaying a PDF with 

- pageViewMode="single"
- [zoom]="'page-fit'"
- [showBorders]="false"

A margin of 10px remains at the bottom of the page and a scroll bar appears

**Version info**
- [11.2.0](https://www.npmjs.com/package/ngx-extended-pdf-viewer/v/11.2.0)

**Desktop (please complete the following information):**
 - Chrome Version 98.0.4758.82 (64 bits)
 - Edge Version 98.0.1108.50 (64 bits)

**To Reproduce**
```
<ngx-extended-pdf-viewer	
	[src]="src"
	[height]="'100vh'"
	pageViewMode="single"
	[page]="1"
	[showToolbar]="false"
	[zoom]="'page-fit'"
	[showBorders]="false"
></ngx-extended-pdf-viewer>
```

**Demo PDF file**

https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

**Screenshots**

View of the problem 
![image](https://user-images.githubusercontent.com/97437030/153853981-66978430-bc42-4c07-ae48-7eaedfefe9c1.png)

Css issue
![image](https://user-images.githubusercontent.com/97437030/153854975-62e53cec-6731-43cf-ba87-b9601ba2b415.png)

**Additional context**
Applying custom css on the page element with something like

```
#extendedPdf .page {
	margin-bottom: 0;
}
```
remove the scrollbar

**Comment by stephanrauh** [comment]
I think you're right. When I dropped my own implementation of the single-page mode in favor of the pdf.js implementation, this particular CSS rule got lost. Please update to version 12.0.0-alpha.1, run a test and tell me whether it fixes your issue.
