### ISSUE TITLE
Linking to a section in pdf, incorrectly scrolls to that section

### ISSUE THREAD

**Issue by CeeCon** [stephanrauh/ngx-extended-pdf-viewer#1204]
**Check this first**

- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? 
No

- Does the bug also happen on https://pdfviewer.net/simple?
Yes

- Can you write a reproducer based on this template project? 
Yes

**Describe the bug**
When having internal links in a pdf that refers to other sections in the pdf, it will scroll to that section incorrectly when pressing the link - i.e. scroll too far or not far enough.

**Version info**
Bug verified in both version 11.0.0 and in most current at the time of writing 12.0.0-alpha.0

**Desktop (please complete the following information):**
Bug verified to exist in both safari and chrome on Mac OS
 
**To Reproduce**
https://github.com/CeeCon/ngx-extended-pdf-viewer-issues/tree/main/template

In my sample code provided, you can scroll to page two and click the links in the top and see the behavior. It scrolls close to the target but it varies how close it comes to having the element in the top. When using same PDF in mozilla it works as expected.

**Demo PDF file**
The PDF in the repository angular "assets" folder will reproduce the problem.

**Comment by stephanrauh** [comment]
Well, these links are simple, old-fashioned HTML links. I suppose the Angular engine confuses the algorithm calculating the target position of the link. Actually, I'm surprised it works at all because it works by modifying the URL, and I'd expect the router to react to that change.

**Comment by stephanrauh** [comment]
It's nothing to do with PDFs. The PDF file is rendered as HTML, and it contains a simple HTML `<a href="#target">` link. I'm a bit puzzled that that standard link doesn't work out-of-the-box.

**Comment by CeeCon** [comment]
ah i see, if there is anything i can do - please reach out and i'll see what i can do :)

**Comment by stephanrauh** [comment]
As it turns out, I was wrong. It's not just a simple link. Instead, it's implemented here: https://github.com/stephanrauh/pdf.js/blob/cc58c3e9ab808fb5a49f39323b7a2ab54c05a6b7/src/display/annotation_layer.js#L545

**Comment by CeeCon** [comment]
So what does that mean exactly? :)

**Comment by CeeCon** [comment]
It appears to work beautifully! thank you very much for your quick assistance - it's highly appriciated :)
