### ISSUE TITLE
PDF-Page is shown in black sometimes (even in the showcase) in chrome

### ISSUE THREAD

**Issue by TLucasIND** [stephanrauh/ngx-extended-pdf-viewer#1208]
It's a Mozilla-Bug. But I already wrote the report, so maybe it helps for awareness. If not, you can do with this report, what you want of course. (Btw.: its my first bug report)

**Check the following**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
**- - happens there too**
- Does the bug also happen on https://pdfviewer.net/simple?
**- - yes**

**Describe the bug**
when working with the pdf-viewer, sometimes after loading (maybe some amount of time) the part, where the pdf should be shown, only black screen is appearing. All other features are still working as far as I can assess it (searching, marking the text, zooming, etc.).

**Version info**
- Version of ngx-extended-pdf-viewer
- current version (it happens in the showcase too)

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]
 - Chrome Version 98.0.4758.102
 
**Smartphone (please complete the following information):**
 - not tested

Step to reproduce: just open the web-page and wait some amount of time (not sure but less than 2 minutes)
**Demo PDF file**
Happens in the showcase with example pdf

**Screenshots**
![Screenshot 2022-02-21 084425](https://user-images.githubusercontent.com/49560161/154911699-e334a4da-1e57-4b55-8b1e-c374acd8e1b0.png)

Greets!

**Comment by stephanrauh** [comment]
Just to make sure I get it right: the PDF file is displayed, but blacks out after one or two minutes?

**Comment by stephanrauh** [comment]
Is this bug specific to Chrome? Some time ago, I've seen a similar problem with certain version of Chrome on some Android devices. That was a Chrome bug that may be fixed in the next version. As far as I understand, the bug was a regression, so downgrading probably helps, too. Maybe your bug falls into the same category.

**Comment by TLucasIND** [comment]
> Just to make sure I get it right: the PDF file is displayed, but blacks out after one or two minutes?

That's right. Even on the official Mozilla Page. 
I reported the bug but was in a hurry, so it probably wasn't precise enough (I sent them the wrong screenshot). So they closed the report.

> Is this bug specific to Chrome? Some time ago, I've seen a similar problem with certain version of Chrome on some Android devices. That was a Chrome bug that may be fixed in the next version. As far as I understand, the bug was a regression, so downgrading probably helps, too. Maybe your bug falls into the same category.

Yes, the bug wasn't reproducable on firefox.
At first I thought, it had something to do with my code. But the thing is, that I simultaneously opened the official Mozilla page in another instance of chrome and the same problem appeared.

For what it's worth, now you know about it too, at least.

**Comment by TLucasIND** [comment]
The error appears when switching to another tab and then back to the pdf viewer tab.
I really think, it has nothing to do with your wrapper. Here is the link to my issue on mozillas repo:
https://github.com/mozilla/pdf.js/issues/14592

**Comment by stephanrauh** [comment]
Running into Jonas is always an interesting experience. He's a mighty doorkeeper, it's not easy to get your ticket accepted!

BTW, you could try what Jonas did, too: check if the bug is gone with Chrome Beta 99.

**Comment by TLucasIND** [comment]
> BTW, you could try what Jonas did, too: check if the bug is gone with Chrome Beta 99.

Yeah, would try it, but can't install it in my environment. It's not an option to use the beta version in our use case anyway.
I'm not sure, if Jonas tested it with switching the tabs tho...

Did you possibly try to reproduce it in chrome?
