### ISSUE TITLE
version 1.0.0 didn't display pdf on edge and IE11

### ISSUE THREAD

**Issue by RojasAB** [stephanrauh/ngx-extended-pdf-viewer#121]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple?

This issue not reproduced on the above links

**Describe the bug**
simply, all components are hidden or in other position diffrent than the point of view

**Version info**
ngx-extended-pdf-viewer v1.0.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge 38 and IE  11

**To Reproduce**
Just open the latest verdion on IE11 and Edge

Maybe because of the use of 2.2 versions of the js
I did some tests with the latest pdfJS and pdf worker seem
s they work fine with the old version of viewerJs not with 2.2 version

**Comment by stephanrauh** [comment]
That's a bit surprising. Just to be sure: "all components" refers to the components outside the PDF viewer?

**Comment by stephanrauh** [comment]
As for your tests: did you replace the JavaScript files viewer.js, pdf.js, and pdf-worker.js, but nothing else? Or did you go back to an older version of ngx-extended-pdf-viewer?

**Comment by RojasAB** [comment]
with:

1-pdf.js viewer.js pdf-worker.js fail

2-all or any of them with 2.2 fail

3- v2.2.2 pdf.js only and others no version success but the error with
sidebar still there

**Comment by stephanrauh** [comment]
Thanks. I'm still confused.

1) Can you send me a screenshot, please? I don't know what's wrong.
2) Where did you get the other versions of pdf.js, pdf-worker.js, and viewer.js from?

Maybe it's simply an IE11 problem. Did you try the ES5 set of the JavaScript files? I.E. pdf-es5.js, pdf-worker-es5.js, and viewer-es5.js?

**Comment by RojasAB** [comment]
i get the version 2.2.2 directly from mozilla pdf js on gitlab

**Comment by stephanrauh** [comment]
GitLab? I thought pdf.js is hosted on GitHub? Over there, I can only see a version 2.2.228 - not 2.2.2. The developer version is already a 2.3.x version.

**Comment by stephanrauh** [comment]
In any case - I still believe the problem is that you're using the EcmaScript 6 files. Did you try the files with the *-es5.js suffix?

**Comment by stephanrauh** [comment]
BTW, I wonder if there's a language barrier. If you're a native speaker of Spanish, French, Portuguese, Italian, German or Dutch, feel free to answer me in your language. Thanks!

**Comment by RojasAB** [comment]
sorry for the late, no i didnt try those files.  i just change the files
located on the assets folder.

ok, la verdad no me queda claro que debo hacer, ¿copiar el contenido de
esm5/lib hacia la carpeta lib o recompilar el proyecto?. Por lo que me
dices entiendo que la librería utiliza es6 pero hay algo compilado para
es5, ¿es cierto mi análisis?

de todas maneras, deberías poder reproducir el error, ese error creo que lo
habías arreglado pero en la versión 1.0.0 no se refleja el cambio.

**Comment by stephanrauh** [comment]
Mira a la carpeta `node_module\ngx-extended-pdf-viewer\assets\`. Ahi hay seis archivos JavaScript:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/3045767/63150683-c55cad00-c007-11e9-90a5-66cda742912e.png">

Si usas un navegador moderno, puedes incluir los archivos `pdf.js`, `pdf-worker.js` y `viewer.js` en la sección `scripts` de tu `angular.json`. Estos archivos are mas pequeños que los archivos originales. Mas importante, es mas facil depurar errores.

En otro lado, si tu (o tu cliente) usas un Internet Explorer, tenemos que usar archivos compilado con el viejo dialecto de JavaScript (ES5). Estos archivos son mas largo. Ademas, es casi imposible leerlos. Es codigo producido por el transcompilador Babel. Sea como sea, para suportar el Internet Explorer tienes que includir los archivos `*-es5.js`:

```json
// angular.json -> tu proyecto -> architect -> build -> options
"scripts": [
              "node_modules/ngx-extended-pdf-viewer/assets/pdf-es5.js",
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker-es5.js",
              "node_modules/ngx-extended-pdf-viewer/assets/viewer-es5.js",
              "node_modules/marked/lib/marked.js",
             ... ]
```

**Comment by tomek2k1** [comment]
Maybe related:

I also couldn't get the PDFViewer running in IE11.
After a couple of hours of investigation I realized that the IE11 was running in IE10 mode.
Is it possible to get the viewer running in IE10 mode?

**Comment by stephanrauh** [comment]
Maybe adding the Babel polyfill help, as described here: https://stackoverflow.com/questions/33828840/symbol-is-undefined-in-ie-after-using-babel

**Comment by tomek2k1** [comment]
I will give it a try.
Just for completeness. IE11 in IE10 mode throws the following error: 
Object doesn't support property or method 'webViewerLoad'

**Comment by RojasAB** [comment]
ok perfect, bien claro.

We need to support several browsers. If i just do that i will support only
IE11. Anyway i'm not sure, i will test it to see what happens

**Comment by stephanrauh** [comment]
I didn't hear anything from you guys, so I'll close the ticket now. 

@tomek2k1 I've opened a follow-up ticket for IE10 compatibility. Most likely it's simply a matter of documentation, but even so, let's track it in a dedicated ticket (#127).
