### ISSUE TITLE
No provider for NgxExtendetPdfViewerService

### ISSUE THREAD

**Issue by Dennis-Do** [stephanrauh/ngx-extended-pdf-viewer#1231]
Hi,

I used this plugin for a while now, for just showing a PDF file. As of yet I used version 9 with angular 11, allways with the same PDF as a placerholder. After upgrading to Angular 13 I decided to upgrade to Version 11 of ngx-extendet-pdf-viewer too.

Unfortunatelly I never get it to work.

![grafik](https://user-images.githubusercontent.com/26918219/156736050-6c0f9f71-e558-491d-bbd4-dc180c910bd0.png)

Therefore I have to downgrade to Version 9 again.

**Comment by stephanrauh** [comment]
I can only guess. Either you've run into a bad version (unlikely, but not impossible), or you're suffering from a weird caching problem.

I'd like you to run a quick check. It takes about three minutes, depending on your internet connection. Please create a fresh project like so:

- `ng new test`
- `cd test`
- `ng add ngx-extended-pdf-viewer` (and accept all the defaults)
- replace the content of `app.component.html` with `<app-example-pdf-viewer></app-example-pdf-viewer>`
- start the application with `ng s -o`.

I've run this a few minutes ago, and it worked like charm. Does it work on your machine, too?

BTW: this installs an alpha version of version 12. However, you can safely update to version 12 of the PDF viewer. I've finished all tests I want to run. It's just I haven't updated the documentation yet, so I didn't call it a final version yet.

**Comment by stephanrauh** [comment]
I haven't heard from you for a long time, so I assume you've managed to solve the issue. I'm closing the ticket now.

**Comment by nestdimon** [comment]
In case someone hit same error: you need to add import of `NgxExtendedPdfViewerModule` in your application main module at `app.module.ts` and not just in your some custom inner module.

**Comment by stephanrauh** [comment]
Really? I'll double-check this, because forcing developers to add the `NgxExtendedPdfViewerModule` to the root module isn't my intention. Thanks for pointing this out!
