### ISSUE TITLE
how to create annotations dynamically with predetermined json data

### ISSUE THREAD

**Issue by VISHNUMURTHY** [stephanrauh/ngx-extended-pdf-viewer#1240]
if I have the information in json format like below the annotation can be created automatically instead of providing form data:
**{ "alternativeText": "First name", "fieldName": "firstName", "fieldType": "Tx", "fieldValue": "", "pageNumber": 1, "id": "4R", "maxLen": 40, "rect": [ 165.7, 673.9, 315.7, 688.1 ] }**

**Comment by stephanrauh** [comment]
That's beyond the scope of my project. But it's a clever idea.

I believe you have to tweak this method to add your custom annotation: https://github.com/stephanrauh/pdf.js/blob/ba670cab33bf303e4a6d750df35d3eaf927545d2/src/display/api.js#L1333

I suggest you add a breakpoint and debug this method to verify if I'm right. 

I'm not sure what to do after that. I don't want to add this feature to the project, but I think it's possible to create a working demo which can be published on https://pdfviewer.net. This way, you get your feature, too. It's just I expect you to contribute some effort to make it work!

Does that sound like a fair deal?
Stephan

**Comment by VISHNUMURTHY** [comment]
I successfully added the annotations dynamically using javascript under individual pages. But while saving/downloading the pdf file annotations are missing. File render without annotations is only downloading again

**Comment by stephanrauh** [comment]
I'd say that's already a great success. Awesome!

Just to be sure: when you say you've managed to add the annotation, you're saying you see the additional input fields in the PDF file?

As for the download: well, you need to modify the PDF file itself to make the change permanent. No idea if that's easy or not. But it may give you a hint what's going wrong. I suspect the PDF viewer takes the original PDF file, fills in the form data from the input fields, and that's what you get by downloading the file.

Maybe this method is called during the download: https://github.com/stephanrauh/pdf.js/blob/ba670cab33bf303e4a6d750df35d3eaf927545d2/src/display/api.js#L1333. If so, maybe you "only" have to modify it to add the new input field and its data to the PDF file. Just a wild shot, but may it helps.

**Comment by stephanrauh** [comment]
I'm closing this ticket because it's beyond the scope of this project and because it doesn't seem to be easy to implement the feature.

**Comment by scry-UrjitDesai** [comment]
@VISHNUMURTHY  I want to achieve similar functionality where in I want to draw a bounding box on the pdf given some coordinates. Can you guide me on how did you achieve your requirement ?
