### ISSUE TITLE
Date fields with custom formats are filled with a value but the input display something else

### ISSUE THREAD

**Issue by namblard-sword** [stephanrauh/ngx-extended-pdf-viewer#1242]
Hi @stephanrauh 

**This issue is for your information only.**

This issue also happens on pdfjs viewer.
It is just to let you know the issue I face, and that eventually in the future when this will be solved, I'll let you know so you can include the fix in your project.

**Describe the bug**
I have a pdf which contains 3 dates fields with custom formats:

    1. dd
    2. mm
    3. yyyy

when I input values such as:

    1. 05
    2. 06
    3. 2020

then the viewer displays:

    1. 01
    2. 01
    3. 2020

the date and month in my case are wrongly rendered.

However if I focus one input I see the value I wrote is displayed.

if I get value form data then I get:

    1. 01
    2. 01
    3. 2020

Furthermore, I have strange behavior with these two inputs when I fill them and click outside from times to times but I still need to investigate that.

**Version info**
- Version of ngx-extended-pdf-viewer 12.0.0-alpha.0

Here is a really simple pdf file with to types of Dates, the first in one input with a default format and the second in three inputs with custom date formats : 
[Date.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/8242282/Date.pdf)

You can test that if want to, by inputing values and then TAB on date and month inputs.

Thank you for your attention,

Kind regards

**Comment by namblard-sword** [comment]
For information: https://github.com/mozilla/pdf.js/issues/14672#issuecomment-1066741106

**Comment by stephanrauh** [comment]
Thanks for keeping me in the loop. Calixteman started to investigate the topic, which is always a good sign. I hope the bugfix trickles down to ngx-extended-pdf-viewer soon.

**Comment by namblard-sword** [comment]
The fix have been merged on their side.

**Comment by stephanrauh** [comment]
The bug fix is already included in the "bleeding edge" branch of version 12.0.1.

I've also added it to the stable branch, but I haven't published the corresponding bugfix version yet. It's going to land soon.

**Comment by namblard-sword** [comment]
Hi @stephanrauh , 

I've pull that version in my project but this issue is still there. 

I've also tried on pdfjs viewer, it is properly fixed on their's.

Could you look into the version used and make sure it's the right one ? 

thank you for your time

**Comment by stephanrauh** [comment]
Did you activate the "bleeding edge" branch? The stable branch doesn't contain the bugfix yet.

**Comment by namblard-sword** [comment]
Indeed you're right I forgot that, I'm sorry for the inconvenience. Thank you once again

**Comment by stephanrauh** [comment]
Oops - I've been too slow describing how you can debug this stuff yourself. :) Just for future reference, I'll add it anyways:

As for looking into the code: you can do that, too. First, add the attribute `[minifiedJSLibraries]="false"`. Open a form in the PDF viewer. Open the source tab of the developer tools, and open the "pdf.sandbox-2.13.478.js". Search for a text that's been added by the PR. For example, `date = this._util.scand(cFormat, cDate);`.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/3045767/159670022-8c6f590e-a291-4b94-ba23-87f5cab6c99f.png">

**Comment by stephanrauh** [comment]
The next few days I'm busy. If everything works out as planned, I'm going to publish the bugfix of the stable version this weekend or early next week.

**Comment by stephanrauh** [comment]
I've just published version 12.0.2, which fixes the error in the default branch of pdf.js.

(Ignore my commit message - it's 12.0.2, not 12.0.3).

Enjoy!
Stephan
