### ISSUE TITLE
zoom event not fired when automatic zoom selected

### ISSUE THREAD

**Issue by mcornillon87** [stephanrauh/ngx-extended-pdf-viewer#125]
**Check this first**
- Does the bug also happen on https://pdfviewer.net/simple? 
 YES on https://pdfviewer.net/zoom -> Current zoom level: doesn't change when zoom is modified 

**Describe the bug**
(zoomChange)="zommChanged($event)" 
zommChanged  fired when zoom is changed manually in the pdf viewer except when user select "Automatic zoom"

<img width="980" alt="Capture d'écran 2019-08-18 11 39 21" src="https://user-images.githubusercontent.com/22214655/63222824-e4487400-c1ac-11e9-9534-2d6f4081c20a.png">

**Comment by stephanrauh** [comment]
Interesting. And easy to fix. Oh, the pitfalls of the JavaScript language! :)

 Remains the question what's a useful message. Truth to tell, `page-fit`, `page-actual`, and `page-width` set an example: just report that the zoom factor is `auto`.

I'd prefer to report the actual zoom factor in percent. However, I suspect that'd break backward compatibility. To avoid that, I could add a new event, something like `(effectiveZoomFactor)`or `(currentZoomFactor)`. 

Quelle est votre opinion, @mcornillon87 ?

**Comment by stephanrauh** [comment]
Of course I'm also interested in the opinion of everybody reading this. :)

**Comment by stephanrauh** [comment]
As it turns out, there's already a event of pdf.js notifying us about the real zoom factor: `scalechanging`.

So `(effectiveZoomFactor)` could be a simple mapper of `scaleChanging`.

**Comment by mcornillon87** [comment]
Easy to fix is always good :) Yes a mapper of scaleChanging would be perfect then. As a french with an average english 🤔  (currentZoomFactor) sound more clear but (effectiveZoomFactor) is good too.
A big thanks you for your job by the way, It is a revolution coming from ng2-pdf-viewer 👏

**Comment by stephanrauh** [comment]
@mcornillon87 Vous écrivez bien l'Anglaise. Au-dessus de la moyenne, j'imagine. :)

**Comment by stephanrauh** [comment]
Ah, you're referring to the component of Vadym Yatsyuk. He's written a nice component, but you're right, it's just the core PDF viewer. Adding the toolbar makes it so much more useful!

**Comment by stephanrauh** [comment]
It's a small change - but I guess the rules of semantic versioning make it a new minor version. So here it is: ngx-extended-pdf-viewer 1.1.0!
