### ISSUE TITLE
Error: PDFViewerApplication.pdfLinkService.navigateTo is not a function

### ISSUE THREAD

**Issue by dvag-vibula-kanakalingam** [stephanrauh/ngx-extended-pdf-viewer#1257]
I am using the  `[nameddest]` attribute and  I am getting this error. 
PDFViewerApplication.pdfLinkService.navigateTo is not a function. 
![image](https://user-images.githubusercontent.com/85543601/159238192-5cf04f69-0dbf-4bd0-8580-3db6d44e06d2.png)

The deprecated `pdfLinkService.navigateTo` method [https://github.com/mozilla/pdf.js/commit/92ec10bfcad11fea430c5bda6e4b104b1653d57f](https://github.com/mozilla/pdf.js/commit/92ec10bfcad11fea430c5bda6e4b104b1653d57f) has been removed. 

Can you fix the problem please? 

Version: 
  "ngx-extended-pdf-viewer": "^12.0.0-alpha.4",

**Comment by stephanrauh** [comment]
The bug fix has landed with version 12.0.1.

Enjoy!
Stephan
