### ISSUE TITLE
pdf.sandbox.js does not load inside iframe

### ISSUE THREAD

**Issue by agrube** [stephanrauh/ngx-extended-pdf-viewer#1264]
**Describe the bug**
We are working on a project that has an embedded pdf viewer using an iframe. We have a demo page that lets a user use the "embedded" application inside our other application. This works fine on dev since our apps exist on different ports (i.e. http://localhost:4200 and http://localhost:4201), but once we deploy to prod, the apps exist on the same port and domain (i.e. http://my.app.com/app1 and http://my.app.com/app2). Once this happens, the app embedded in the iframe is no longer able to load pdf.worker.js and pdf.sandbox.js correctly. When running this app outside of an iframe in it's own browser tab, it is able to successfully locate pdf.sandbox.js. It seems to only be an issue when the app is in an iframe and has the same domain/port as the hosting app.

We have circumvented the issue with pdf.worker.js by adding the exact script to our angular.json scripts list, but this is not working for pdf.sandbox.js. It appears to be searching for pdf.sandbox.js in the wrong directory. On the working builds, it loads it from the /app2/assets directory, but in the iframe it is searching in the /build directory.

I've noticed this only happens on certain files since it doesn't seem like other files are triggering this loading of pdf.sandbox.js. Unfortunately, all the pdf files we are trying to serve trigger the loading of pdf.sandbox.js.

**Version info**
- 10.5.0

**Desktop (please complete the following information):**
 - Chrome and Firefox

**To Reproduce**
https://github.com/agrube/ngx-extended-pdf-issue

**Demo PDF file**
[file.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/8352105/file.pdf)

**Screenshots**
In an iframe:
![embedded-sandbox](https://user-images.githubusercontent.com/1392839/160157981-283e90f4-27ed-4dbd-b8e1-8ce7a06b7f85.png)

Not in the iframe:
![not-embedded-sandbox](https://user-images.githubusercontent.com/1392839/160157992-7f8be41e-4921-40fd-a8df-12d4d7a0f506.png)

**Comment by stephanrauh** [comment]
You've even added a reproducer. Awesome, thanks!

**Comment by stephanrauh** [comment]
You can configure the URL of the worker using `pdfDefaultOptions.workerSrc()`. However, I'm puzzled the pdf viewer doesn't manage to guess the path correctly without help. 

Be that as it may, I didn't care about the sandbox URL yet, so it's obvious there a to do open.

**Comment by agrube** [comment]
I did try to edit the workerSrc() directly, but it seems to have trouble getting the iframe's version. I don't think the worker.js issue exists anymore in 12.0.1, though. I bumped the version to 12 and didn't encounter it even without explicitly defining it in the angular.json scripts array.

I wasn't able to test the sandbox issue in v12 since I discovered that I needed to use a special pdf file to cause sandbox to be loaded. I'll try bumping the version and report back.

**Comment by agrube** [comment]
Just confirmed. After bumping the version to 12, this error doesn't pop up anymore. Perhaps something was done in pdf.js that addressed this issue?

**Comment by stephanrauh** [comment]
Interesting. I'm not aware of any improvements concerning the `workerSrc` since version 10.5.0. But if it works, it works, and I'm not going to complain! :)

As I've mentioned above, I consider it likely that the sandbox still causes troubles. It's a new file - introduced last year, if I'm not mistaken - so bugs are not surprising.

I'm looking forward to your improved sandbox reproducer!

**Comment by agrube** [comment]
For the worker issue, I think it may be because the scripts don't have the versioning as part of their name anymore? It seems to have no trouble finding assets/pdf.worker.js. 

I only tested on 12 using ng serve, so I'm not sure what will happen on a prod build. Also, suspiciously, the devtools network tab doesn't indicate that pdf.sandbox.js was accessed with version 12 on that same busted pdf.

**Comment by stephanrauh** [comment]
> because the scripts don't have the versioning as part of their name anymore?

I hope you're wrong. The version number is annoying, no doubt about that, but it solved a lot of nasty caching problem. So I prefer to stick with the version numbers of the JavaScript files. Did you remove the `pdf-worker.js` from the `scripts` section of the `angular.json`?

The sandbox is used to execute JavaScript embedded in PDF files. I admit I'm not familiar with the details, so I can't tell you what triggers loading the sandbox and which PDF documents don't need it. What I can tell you is that the demo https://pdfviewer.net/extended-pdf-viewer/scripting forces loading the sandbox.

**Comment by stephanrauh** [comment]
As it turns out, I did solve the bug some time ago. Please update to version 12 of the PDF viewer. This solves both the issue of the worker file and the sandbox file.

Note this means you also have to enable Ivy. I've dropped support for the old View Engine with version 11.

**Comment by stephanrauh** [comment]
Side remark: removing the worker file from the `angular.json` improves rendering performance a lot. Probably that's not a issue to you, but if you've got a really large file like https://www.obwb.ca/newsite/wp-content/uploads/mr_93_e.pdf it makes a big difference.
