### ISSUE TITLE
IE10 compatibility

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#127]
@tomek2k1 reports this bug:

I couldn't get the PDFViewer running in IE11.
After a couple of hours of investigation I realized that the IE11 was running in IE10 mode.
Is it possible to get the viewer running in IE10 mode?

_Originally posted by @tomek2k1 in https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/121#issuecomment-521923830_

**Comment by stephanrauh** [comment]
Supporting IE11 is painful enough. So supporting IE10 seems to be pointless to me. 

Even most conservative German companies (and that's a really conservative group!) have almost always updated to IE11.

Let's close this ticket.

**Comment by tomek2k1** [comment]
You are right. In my special case the IE10 compatibility mode in IE11 is just used as workaround for a couple of issues with SharePoint 2013.

**Comment by stephanrauh** [comment]
@tomek2k1 Thanks! Both for watching this follow-up ticket and for your kind words!

I'm afraid IE11 compatibility is the main reason to adopt ngx-extended-pdf-viewer, so I take this stuff very seriously. On the other hand, I suspect I've added enough additional value to ngx-extended-pdf-viewer to justify using it instead of an `<embed>` or `<object>` solution.
