### ISSUE TITLE
[printResolution] is not working

### ISSUE THREAD

**Issue by joelvargheseg** [stephanrauh/ngx-extended-pdf-viewer#1290]
hello,
I'm trying to implement the ngx view in my JS web application. And the user complained that when they directly print the pdf from the view the clarity is really bad and I tested it myself. then I tried to put the value of [printResolution] to 300,600,900,1150 as given in the documentation but nothing is working. The viewer only opens the dialog box if I put [printResolution] = 300 if I put any other value then the print dialog box doesn't even open up. and still the clarity is poor for [printResolution] = 300.
I'm using the latest version of the viewer. 12.0.3 and in Bleeding-edge.

**Comment by stephanrauh** [comment]
It's difficult to say without knowing your PDF file. But in most cases, the PDF file is huge, so it eats up more memory than the browser needs to render it clearly. So let's check this first. How does the print look like if you print the same file at https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by stephanrauh** [comment]
Any news?
