### ISSUE TITLE
viewer is throwing unwanted noise in the logs. 404

### ISSUE THREAD

**Issue by joelvargheseg** [stephanrauh/ngx-extended-pdf-viewer#1292]
this is a 404 error I'm getting from pdf.worker from Bleeding edge. 
request_line="GET /myProject/web/standard_fonts/FoxitDingbats.pfb HTTP/1.1" code=404 bytes =8966 user_agent = "Mozilla/5.0 (Windows NT 6.2: Win64; x
64) AppleWebKit/XX7.36 (KHTML, like Gecko) Chrome/XX.0.XXX0.198 Safari/5X7.36" referer="https://myURL.com/myProject/bleeding-edge/pdf.worker-
2.13.288.min.js" 

please advice a solution for suppressing this unwanted noice. or please add all the required fonts in the library.
thanks

**Comment by stephanrauh** [comment]
I think the PDF file is missing the font, so there's nothing I can do about it. To doublecheck: what happens if you open the document at https://mozilla.github.io/pdf.js/web/viewer.html? Do you observe the same error?

**Comment by stephanrauh** [comment]
The bug also happens on https://pdfviewer.net/extended-pdf-viewer/blob and slows down the PDF viewer tremendously.

**Comment by stephanrauh** [comment]
Oh, that's what you're talking about: https://unpkg.com/browse/pdfjs-dist@2.13.216/standard_fonts/

Those fonts have been added with pdf.js. Things to check:
- Where do these font come from?
- Are they published under a license compatible to Apache V2?

**Comment by stephanrauh** [comment]
The bugfix has landed with version 13.0.0-alpha.5.

Enjoy!
Stephan

**Comment by stephanrauh** [comment]
Yes, that's possible. This is the commit you need: https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/962968c870b4d0757c69787e85b9fa3541a0131d

BTW, you don't even have to cherry-pick the commit. As far as I remember, it's enough to copy the 14 standard fonts to the `/assets/standard_fonts` folder. That's something you can do in your `angular.json`.

**Comment by hari-narendran** [comment]
Thanks Stephan, i will report back once i give that a shot.
