### ISSUE TITLE
no resource to load, early way out

### ISSUE THREAD

**Issue by javid-abd** [stephanrauh/ngx-extended-pdf-viewer#13]
We're using Angular material's tabs with ngx-extented-pdf-viewer [version 0.9.8]. In the first tab it works perfectly, but in the second or third tab, it's broken and throws an error on console: `no resource to load, early way out`

![pdf2](https://user-images.githubusercontent.com/32272345/48935488-53947e80-ef21-11e8-9cb9-94953b95a464.png)

. 

## Code sample
  `ngOnInit() {

    this.route.params.subscribe(id => {
      this.documentId = id['id'];
      this.documentApi
        .getSingleDocument(this.documentId)
        .subscribe((data: OneDocument) => {
          this.document = data;
          this.pdf = true;
        });
    });
  }`

**Comment by stephanrauh** [comment]
The error description is a bit different, but even so I wonder if it's related to #12.

**Comment by javid-abd** [comment]
In my case, I solved my problem by adding  selectedTabChange output event that is emitted when the active tab changes. It seems it should be called when the active tab changes or any component gets bootstrapped.
So I close this issue.

**Comment by stephanrauh** [comment]
That's an unexpected solution!
