### ISSUE TITLE
React to CMD + mouse wheel scroll or wheelAction="scroll" only if cursor or focus is inside viewer area

### ISSUE THREAD

**Issue by newq** [stephanrauh/ngx-extended-pdf-viewer#1302]
**Describe the bug**
I was not sure if this is a feature request or a bug (and i am not sure if this is a pdf.js problem, but i think it might not), but here it goes: 

Having the pdf viewer basically take over the mouse wheel on a page, even if the cursor is not inside the viewer area, is not ideal. In my case having part of the application always display the viewer and part of the application being scrollable forms / tables etc. 

If the wheelAction="zoom" and the user uses the scroll wheel, it will always zoom the pdf, even if the cursor is outside the viewer area. The user is now not able to scroll the page the viewer is included on. 

If the wheelAction="scroll" and the user does CMD + scroll, it will always zoom the pdf, even if the cursor is outside the viewer areas. The user is now not able to zoom the page as he might expects. 

I looked through the documentation and could not find an attribute to change this behaviour.

**Version info**
- i think all, but tested on 12.1.0 and the current simple demo page.

**Desktop (please complete the following information):**
 - tested in Chrome 97 and Firefox 99
 
**Smartphone (please complete the following information):**
 - did not test

**To Reproduce**
1. go to https://pdfviewer.net/simple
2. scroll anywhere outside the viewer area
3. set [wheelAction]="scroll" and CMD+scroll anywhere outside the viewer area

**Thank you!**
Thank _you_ for working on this great wrapper it really is a big help!

**Comment by stephanrauh** [comment]
Why did I never think about it? The capricious zoom annoyed me, too, but I just took it for granted!

Plus, it's surprisingly easy to solve. Thanks for pointing this out!
