### ISSUE TITLE
PDF files often are displayed after a long delay

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1316]
Not sure how to reproduce this, but frequently the PDF files are displayed after a long wait. However, they are rendered immediately if you're scrolling.

**Comment by stephanrauh** [comment]
Version 13.0.0-alpha.5 powered by pdf.js 2.14.424 is still fast. Version 13.0.0-alpha.6 running on pdf.js 2.14.433 seems to be the first slow version.

**Comment by stephanrauh** [comment]
Version 13.0.0-alpha.3 running on pdf.js 2.13.482 seems to be the first "stable branch" version that's slow. Version 13.0.0-alpha.2 running on pdf.js 2.13.482 is still fast. Might that be two independent bugs?

**Comment by stephanrauh** [comment]
Here's the reason why the PDF is displayed at all: https://github.com/stephanrauh/pdf.js/blob/53ae60684b9a7fedcfd710ef7a985ad88ffa2fdc/web/app.js#L1350

It seems the `pagesPromise` never finishes. Maybe a swallowed exception?

**Comment by stephanrauh** [comment]
I still don't understand what's going wrong, but I've managed to publish a workaround. It's not as fast as it used to be, but the difference should hardly be perceptible. Update to ngx-extended-pdf-viewer 13.0.0-alpha.14 to benefit from the workaround.

**Comment by KillerCodeMonkey** [comment]
i do not use version 13, but your behaviour sounds like something related to the Angular ChangeDetection Strategy "OnPush".

Maybe only some data is changing but the change detection does not recognize them. After some time change detection runs again or if you scroll (change detection is triggered by some native events like scrolling) the changes are coming to the templates and the pdf renders.

I would try to set ChangeDetection Strategy to the default one (only for testing purposes).
If so you just need to find out where you forgot to change the reference to an object to trigger change detection or to manually call "changeDetectorRef.detectChanges()".

**Comment by stephanrauh** [comment]
Thank you very much for your insight! My analysis show the bug is buried deep inside pdf.js, but you never know... I'll try to modify the change detection strategy. Maybe that solves the problem!

What I found out during my last debugging session, is that [here](https://github.com/stephanrauh/pdf.js/blob/53ae60684b9a7fedcfd710ef7a985ad88ffa2fdc/web/app.js#L1350) are two promises. The first one finishes when the first page is rendered, the second fires after a timeout. Until a few weeks ago, the page was rendered quickly. For some reason unknown, now it isn't rendered at all. I've compared the implementations of pdf.js and my fork line by line, but the offending change slipped my attention. What's even more weird is that the bug occurs both in the stable branch and the bleeding edge branch - but in different versions. That should make it easy to spot the error - what has changed in both of my forks of pdf.js 2.13/2.14 - but that's the theory.

**Comment by KillerCodeMonkey** [comment]
but maybe this is a combination of timing issues like angular component init speed and the promise timeout. i would guess, that the second promise wrapped in the timeout leads to the case, that the change detection does not automatically get the changes.

**Comment by stephanrauh** [comment]
Well, the problem is not related to change detection. It's not unlikely that triggering change detection releases the brake. But the problem happens in pdf.js, which is not an Angular framework.

While we're speaking about it, an idea crosses my mind. I tried to solve the bug debugging the Angular application. But that's difficult because zone.js messes up every promise. The added value of zone.js has a downside: debugging becomes really hard.

Maybe it's better to do it the other way round. I could copy my modified source files to the original pdf.js until it breaks. If it doesn't, I know that your theory is right: Angular interferes in an unexpected way with pdf.js.

**Comment by KillerCodeMonkey** [comment]
no probs. but maybe for debugging purpose just wrap your functions in "runOutsideAngular"?

**Comment by stephanrauh** [comment]
I tried. In particular, loading the libary and opening a PDF file  But I've missed quite a piece lines that have to be wrapped, and I don't know which ones. When I started to use `runOutsideAngular`, I was rewarded with a major performance boost, so I'd like to continue. Maybe you can help me. Do you spot a forgotten line?

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/e0ba574720c94807bdf904675016712d2f10a6a2/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1510

**Comment by stephanrauh** [comment]
ToDos:

- [ ] add `runOutsideAngular` to https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/e0ba574720c94807bdf904675016712d2f10a6a2/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1587

**Comment by crlsmsq** [comment]
Hi, Im not sure if its related to this

`Duplicate definition of module 'pdfjs-dist/build/pdf'` 

i sometimes encounter this when trying to use the popup. the pdf doesn't load

**Comment by stephanrauh** [comment]
ngx-extended-pdf-viewer doesn't use `pdfjs-dist/build/pdf`. It sounds like you've added the standard distribution of pdf.js to your project. That's not a good idea because ngx-extended-pdf-viewer ships with its own copy of pdf.js, and I've modified that copy. If you're using the standard build, ngx-extended-pdf-viewer may try and fail to access some features I've added during the last years.

**Comment by CPatel1712** [comment]
Frequently the PDF files are displayed after a long wait. However, they are rendered immediately if you're scrolling or click. What to do in order to fix this ?

**Comment by stephanrauh** [comment]
@CPatel1712 Are you using a current version? The bug is still there, but I've reduce the timeout so the workaround kicks in almost immediately. To be honest, it works so well I'd already forgotten about the bug. Do you still observe the 10 seconds delay?

**Comment by CPatel1712** [comment]
Thanks for amazing pdf viewer option. But Yes, I just make re-install the package. Currently, in my package.json  has  "ngx-extended-pdf-viewer": "^13.5.3", .
I am able to load the pdf right after I do right click onto the gray area where pdf going to load, otherwise I have to wait for so long.

**Comment by CPatel1712** [comment]
> @CPatel1712 Are you using a current version? The bug is still there, but I've reduce the timeout so the workaround kicks in almost immediately. To be honest, it works so well I'd already forgotten about the bug. Do you still observe the 10 seconds delay?
.

**Comment by madhubasana** [comment]
@CPatel1712 can you please provide where we need to provide the timeout. I am also having same issue page is not getting rendered. And loads immediately on click

**Comment by stephanrauh** [comment]
@madhubasana You don't have to do anything except using a version that's new enough. In version 13.0.0-alpha.14, I've reduce the timeout to 10 milliseconds:
https://github.com/stephanrauh/pdf.js/blob/1666cbe68210b43bfb3dcb5a4a2b3e1f757b9c2c/web/app.js#L83

The constant is used here:
https://github.com/stephanrauh/pdf.js/blob/1666cbe68210b43bfb3dcb5a4a2b3e1f757b9c2c/web/app.js#L1418

**Comment by stephanrauh** [comment]
FWIW, I've tried to hunt down the bug yesterday. When using the original timeout, the first page loads slow in one of five to ten attempts. I've managed to find a few promises that don't fire, but I don't see how they are related to page loading:

```ts
PDFViewer._resetView: _onePageRenderedCapability
PDFAttachmentViewer.reset: _renderedCapability
PDFFindController._reset: _firstPageCapability
```

**Comment by madhubasana** [comment]
I am still having this issue with the issue pdf loads start only after I click on any of the buttons below is my code 

html:
                  <ngx-extended-pdf-viewer *ngIf="pdfSrc" [src]="pdfSrc" [useBrowserLocale]="true" [theme]="'dark'"
               [showOpenFileButton]="false" [backgroundColor]="backGroundColor" [delayFirstView]="5000"
                [customFindbarInputArea]="customFindbarInputArea" [customFindbarButtons]="customFindbarButtons" [textLayer]="true"
                [showHandToolButton]="false" [showPrintButton]="false" [showDownloadButton]="false" [handTool]="false"
                [showSecondaryToolbarButton]="true" [backgroundColor]="backGroundColor" (pdfLoadingStarts)="onPageLoadingStart($event)"
                (progress)="onProgress($event)" (pdfLoaded)="onPDFLoaded($event)" >
              </ngx-extended-pdf-viewer>
    

typescript: 
 ngOnInit(): void {

    this.route.params.subscribe((param) => {

      const faxId = param['faxId'];

      if (faxId == null) {
        this.router.navigateByUrl('error');
      } else {
        this.docId =  faxId;
        this.showProgress=true;
        this.getPdfDocument(this.docId);

      }
    });
  }

**Comment by madhubasana** [comment]
I am using 15.0.0 version

**Comment by michaelmarcuccio** [comment]
v15.0.4
I still have problems with this too, but unsure if it is the same issue we are talking about here. PDF file like 100MB very high resolution has trouble rendering (very slow). If I open pdf.js in firefox and view it directly using pdf.js pages load much faster.

On top of this, the virtual scrolling in this package doesn't seem to be able to cancel the previous page render request so if you scroll quickly, too many pages are queued to render and it basically slows to a crawl. Especially on high resolution pdf files. I am unsure if pdf.js has this same issue, but maybe better page rendering speed causes it to be hard to notice.

**Comment by stephanrauh** [comment]
@michaelmarcuccio That's almost certainly a different issue. I wonder if you've accidentally deactivated the worker thread. Please create a new test project with
```
ng new some-project
cd some-project
ng add ngx-extended-pdf-viewer (and accept all the defaults)
```
Put the example PDF component into the `app.component.html` and load your large file. Is it still slow? If not, you're probably loading the file `pdf.worker.js` manually instead of leaving this to ngx-extended-pdf-viewer.

As for scrolling: Good point. You're right, I never noticed. The only huge and slow PDF file I have has only a single page. But you can activate the single-page mode.

**Comment by stephanrauh** [comment]
@madhubasana You don't need `[delayFirstView]="5000"`. This option delays rendering by five seconds.

**Comment by stephanrauh** [comment]
While I didn't manage to find the root cause, the problem seems to be gone. Let's close the ticket.
