### ISSUE TITLE
Print view adds an additional blank page

### ISSUE THREAD

**Issue by i7i5** [stephanrauh/ngx-extended-pdf-viewer#1318]
**Describe the bug**
The print view adds an additional blank page.

**Version info**
- We had this with ^9.0.5 since I guess around January and I also tried the latest 12.1.2

**Desktop (please complete the following information):**
 - Every browser, latest version

**To Reproduce**
I created a demo project with Angular 12 and latest version 12 of the viewer: [Demo repo](https://github.com/i7i5/test/blob/master/src/app/app.component.ts)

Just click the Button to activate the viewer and the printing screen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9058776/164019225-fb03dd2c-75ea-450d-b6ef-0243f66f89be.png)

Thanks a lot for having a look :)

BR
i7i5

**Comment by stephanrauh** [comment]
Thanks for providing a reproducer!

**Comment by stephanrauh** [comment]
When you open your file on https://pdfviewer.net/extended-pdf-viewer/simple, there's no extra page in the print preview. I haven't seen the offending CSS rule yet, but judging from previous error reports, I'm 95% sure it's a CSS problem hidden somewhere in your project.

**Comment by stephanrauh** [comment]
I'm confused. I've counted the CSS rules of your project. I ended up with zero. Adding insult to injury, I can reproduce the extra page with a fresh project (`ng new` + `ng add ngx-extended-pdf-viewer`).

**Comment by stephanrauh** [comment]
As it turns out, the additional page seems to be caused of the width of your demo document. It seems to be a tiny fraction too wide. I've added this rule to the global `styles.css`, and it solves the problem:

```css
body[data-pdfjsprinting] #printContainer>.printedPage {
  width: 99.99% !important;
}
```

**Comment by i7i5** [comment]
Hello, I tested this solution in our production code and it works flawless. Thanks a lot for investigation! :)

**Comment by Mcondino** [comment]
So, from what I could find via Chrome:

This CSS style is what seems to be giving me issues.  The Width specifically.
![image](https://user-images.githubusercontent.com/107938323/174890639-8c8501c7-c651-4226-ac17-9e6cc5554d30.png)

If I set that to 99%, close the print preview and re-open it, then it shows correctly.

I have not had any luck trying to set that manually on my side.
