### ISSUE TITLE
get changed values from a form

### ISSUE THREAD

**Issue by fgerges** [stephanrauh/ngx-extended-pdf-viewer#1319]
When you use NgxExtendedPdfViewerService.getFormData() you have access to the field before modification, 
The information entered in these fields are not returned, it would be necessary either to update the fields before calling this function or to have another function to obtain the modified fields with their new values

**Comment by stephanrauh** [comment]
Vous avez raison!

**Comment by stephanrauh** [comment]
I've published version 13.0.0-alpha.15, which addresses your issue. `NgxExtendedPdfViewerService.getFormData()` adds a new attribute, `annotation.fieldAnnotation.value` containing the current value to the array. For the sake of compatibility, there's also `NgxExtendedPdfViewerService.getFormData(false)` which is the old logik.

Hope that helps!

@+
Stephan

**Comment by fgerges** [comment]
You are the best !!!
thank you so much
