### ISSUE TITLE
Pdf not updating when changing base64src

### ISSUE THREAD

**Issue by Stromwerk** [stephanrauh/ngx-extended-pdf-viewer#135]
**Description**
When using `base64src` attribute to display the pdf initially there is no problem and the pdf is displayed, however when the value bound to `base64src` changes the pdf doesn't update. When using `src` attribute it's working correctly.

**Version info**
- Version of ngx-extended-pdf-viewer: `1.2.0`
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js : not entirely sure, I think they are the default files

 - OS: Windows
 - Browser: Tested on both `Chrome (76.0.3809.100)` and `Firefox (68.0.2)`

**Steps to reproduce**

I am unable to provide a reproducer at the moment, however if the steps below aren't sufficient I'll try to create a reproducer.

1. Set up library and add the `ngx-extended-pdf-viewer` tag with `base64src` attribute
2. Set up some way of changing the `base64src` attribute (I have two buttons, which when clicked set a different value)
3. The first `base64src` value to be loaded is shown, however when changing to a different one the pdf doesn't update

**Demo PDF file**
I've used some default base64 encoded pdfs. I could upload them if needed

**Comment by stephanrauh** [comment]
You're right. I've simply forgotton to implement the `ngOnChanges` method.

**Comment by stephanrauh** [comment]
I've published ngx-extended-pdf-viewer 1.3.1 containing the bugfix. I've also added a second document and a switch-documents button to https://pdfviewer.net/base64.

Thanks for reporting the bug!
Stephan

**Comment by Stromwerk** [comment]
Thank you for the quick response. I've updated and it's working great now.
