### ISSUE TITLE
Problem with Angular 11.2 and Version 10.5

### ISSUE THREAD

**Issue by NoSoup4you2** [stephanrauh/ngx-extended-pdf-viewer#1354]
Due to the problems in running current version of component with Angular@cli 11.2 i imported 10.5 which is supposed to be latest working version, I am able to import without any errors but for some reason it does not work like it works in a Angular@13 App which i created initially for testing. Originally i thought that MAT-Dialog might cause my issues but after some more testing and removing that from the equation it seems to be not the source.
As i log the pdfData to console, i can see when it changes. But it never fires the pageLoad(event). I also tried to load the data as a 
path to a pdf in my asset folder and that didnt work either.( i changed it to [src] ) But i can go and use the upload option of the Viewer and select a file which will be correctly displayed.

So i cant figure out what causes this that same very simple code does not work on 11.2 which works on 13 with version 13 of component

I have a basic ts file for now which should load a base64 file into viewer

```
import {Component, Inject, OnInit} from '@angular/core';
import { base64data }  from '../../../assets/pdf/demopdf'
import { pdfDoc2 } from '../../../assets/pdf/demo2pdf';

@Component({
    selector: 'app-pdf-viewer',
    templateUrl: './pdf-viewer.component.html',
    styleUrls: ['./pdf-viewer.component.scss']
})
export class AppPdfViewerComponent implements OnInit {
    pdfData: any 
    constructor() {
    }
  changeDoc1() {
        console.log('Changing Doc')
        this.pdfData = base64data
        console.log(this.pdfData)
    }
    changeDoc2() {
        console.log('Changing Doc')
        this.pdfData = pdfDoc2
        console.log(this.pdfData)
    }
    pageLoad(e : any){
        console.log(e)
      }
    ngOnInit(): void {
        this.pdfData = base64data
    }
    } 

```

Here is my Template file

```
<button (click)="changeDoc1()">Change to Doc 1</button><button (click)="changeDoc2()">Change to Doc 2</button>

<ngx-extended-pdf-viewer>
[base64Src]="pdfData"
backgroundColor="#ffffff"
[height]="'90vh'"
[useBrowserLocale]="true"
[handTool]="false"
(pagesLoaded)="pageLoad($event)"
[showHandToolButton]="true"
></ngx-extended-pdf-viewer>
```

**Comment by stephanrauh** [comment]
At first glance, it look fine to me. So it's time to start debugging. Can you send me the reproducer project?

BTW, the only change I'm aware of in this area is related to this issue: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1197. The issue contains a lot of Spanish text, and at some point in time I forgot to translate it to English, but basically it's about resetting the attributes `[src]` and `[base64Src]`. Before the change, setting these attributes to `undefined` didn't hide the PDF file reliably. However, I don't think that's related to your issue.

**Comment by NoSoup4you2** [comment]
i will try to build a sample in 11.2 and get you the code. As the code i have is in a large project where i try to implement the viewer to display reports. Like i mentioned this simple code works fine with both on 13 so the basic logic should be correct.  Fyi i learned hard way that i cant use stackblitz to to proof concepts. The behavior on stackblitz was similar to this one where files would not load by changing src or base64src

**Comment by stephanrauh** [comment]
Thanks in advance! Please take in mind that this is a leisure-time project, so I'd appreciate the reproducer to be a complete project running out-of-the-box. I don't want to install stuff like databases. And, of course, I'm not interested in corporate secrets. I'm always curious what people are doing with my pet library, but to solve this ticket, a bare-bone reproducer does the trick just as well!

As for Stackblitz: yeah, there's that. I love Stackblitz. But it doesn't support using the assets folder. I guess you could work around that limitation by copying all the JavaScript files to the `src` folder. But StackBlitz doesn't run `ngx-extended-pdf-viewer` without further ado. That's a pity!

**Comment by NoSoup4you2** [comment]
That's why I have to make a new sample that replicates the issue. My issue is creating a clean Angular 11.x project as all new projects i create are 13. It will be simple, 2 var that hold base64 pdf files and the code i send you originally

**Comment by NoSoup4you2** [comment]
Here is the sample project that demonstrates the behavior [Sample Project](https://github.com/NoSoup4you2/PDFViewer11)

**Comment by NoSoup4you2** [comment]
Sorry , yes it was private, i just made it public

**Comment by stephanrauh** [comment]
It turns out to be a cute little typo in your `app.component.html`. I've opened a bug ticket in your repo.

Enjoy!
Stephan
