### ISSUE TITLE
iOS extra dialog-content (Enter the password to open this PDF file.)

### ISSUE THREAD

**Issue by winnievips** [stephanrauh/ngx-extended-pdf-viewer#1355]
<img width="1439" alt="Screenshot 2022-05-06 at 5 26 57 PM" src="https://user-images.githubusercontent.com/27732258/167109862-0fac6032-1ad1-49d0-b22c-2ac871aa18f3.png">

version 13.0.0 got this issues in **safari/ios** but no issue in **chrome/android**

Tested in 12.0.0-alpha.3 dont have this extra "Enter the password ..." but the version 12 i can't use because having issue on scrolling for real device ipad landscape mode

git to reproduce issue: https://github.com/winnievips/test-pdf.git

**Comment by stephanrauh** [comment]
It's even worse: iOS doesn't show the password dialog if you're opening a protected PDF.

**Comment by stephanrauh** [comment]
@winnievips The bug is gone, at least on my devices. I suspect it was a bug of the Safari browser. Can you check this? If the bug still happens on your device, does an update make it go away?

**Comment by winnievips** [comment]
<img width="377" alt="Screenshot 2022-06-07 at 11 21 07 AM" src="https://user-images.githubusercontent.com/27732258/172288765-cf2b279d-515f-4430-9dc3-2ded0b98dc8b.png">

I upgrade the package to version 3.5.2, the issue still persist

**Comment by stephanrauh** [comment]
What about an update of iOS?

**Comment by winnievips** [comment]
Sorry but the iPad not belongs to me..Cant simply update for testing.
Maybe next time if the iPad Software Version updated I can test to verify again.

FYI: I am testing with
Model Name: iPad Air (4th Generation)
Software Version: 15.1

Since version 12.1.2 works fine for my app, I will proceed with the version for now.
Thank You!

**Comment by stephanrauh** [comment]
My iPad runs on iPadOS 15.5. Maybe that's really the difference. I remember to have seen the bug when you reported it. But it's difficult to fix a bug that's so shy it goes away when I open my debugger!
