### ISSUE TITLE
Warning: Setting up fake worker

### ISSUE THREAD

**Issue by philippendrulat** [stephanrauh/ngx-extended-pdf-viewer#136]
**Describe the bug**
See title. We are using Spring boot for the server and copy our files in the "public" folder. This means we changed angular.json/projects/PROJECT/architect/build/options/outputPath to ../resources/public and serve the "public" folder to the client.
We saw that the default lookup path for the worker is "../build/pdf.worker.js", which seems to not exist.
Do we need to copy the worker.js file to the correct location or do we set the worker.js location in pdfjs directly?

**Version info**
- Version of ngx-extended-pdf-viewer: 1.0.2

**Comment by stephanrauh** [comment]
You don't need to do anything. If you PDF file is displayed, everything's fine.

I'm still trying to find out what these weird messages mean. I'm pretty sure it's a false positive. The default lookup path is also a puzzle. It shouldn't matter because the worker is imported by the `angular.json` (if you've followed my instructions, that is).

I'm keeping the ticket open. It's a good reminder to investigate the topic.

**Comment by Catscratch** [comment]
Hi guys.

I have the same problem. I thought pdfjs is doing the heavy load in a webworker for performance increasements. Currently when loading large PDFs the whole web application is blocked by this process which means I cannot interact with any of the other components outside pdfjs.

Also the browser brings up the message that a script is taking long time and ask me if I want to kill this script.

Shouldn't the webworker solve this problem? And at least the application should stay responsive?

**Comment by stephanrauh** [comment]
Sounds like your PDFs are really large. How many megabyte, how many pages are we talking about?

**Comment by stephanrauh** [comment]
BTW, it's an interesting theory that the "fake worker" stuff means pdf.js can't setup a worker thread. Maybe it's a hot trace. Thanks for the hint!

**Comment by Catscratch** [comment]
> 
> 
> Sounds like your PDFs are really large. How many megabytes, how many pages are we talking about?

That is one of our test PDFs. Very heavy.
https://www.obwb.ca/library/okanagan-basin-waterscape-poster/

**Comment by stephanrauh** [comment]
If I get https://github.com/mozilla/pdf.js/issues/7612 right, the `pdf.worker.js` must be in a file of its own (as opposed to being bundled with pdf.js). Otherwise it can't be run in a service worker thread.

**Comment by stephanrauh** [comment]
You sample file is heavy indeed. My Firefox needed several minutes to open the file (using the native viewer). Adding Angular and a falsy webworker configuration probably doesn't make things better.

However, the PDF itself looks really nice. I guess someone (you?) has spent a lot of energy and enthusiasm on it. Awesome!

**Comment by stephanrauh** [comment]
Finally, I've found an explanation what the fake worker is: https://www.codeproject.com/articles/568136/porting-and-extending-pdfjs-to-nodejs (scroll down to "Fake worker for web worker").

**Comment by stephanrauh** [comment]
Good news: I've figured out how to use the service worker, and it improves the performance of the PDF viewer a lot.  I'm publishing the new version this evening after adding the documentation. 

Thanks for nudging into the right direction!

**Comment by stephanrauh** [comment]
@Catscratch Completely off-topic - but when I opened your test document, this sentence caught my eye: "many say we should pay for the water based on how much we use". I can't believe it: you don't have water meters? They are so common in Europe I thought they're used everywhere. :)

**Comment by stephanrauh** [comment]
Since version 1.5.0 you can use the service worker. Currently it's not configurable; it's always `/assets/pdf-worker.js`. So you have to rename the file `pdf.worker-es5.js` to support IE11.

Basically, that's the only thing blocking the issue from closing.

**Comment by philippendrulat** [comment]
I don't know how to make it run.
I copied pdf.worker.js into /assets/ folder and tried both pdf-worker.js and pdf.worker.js, but I still get the warning: Setting up fake worker.

I also cloned https://github.com/stephanrauh/extended-pdf-viewer-showcase ran `npm i` and `npm start` and I still get the warning.

Is there another demo project I can use?

**Comment by philippendrulat** [comment]
PS: with the new Version 1.5.0 I get the error "ERROR Error: "Uncaught (in promise): Error: Invalid pages rotation angle.". 
I did a little research and it seems the error happened since 1.4.0.
In 1.3.1 there was no error

**Comment by Catscratch** [comment]
> 
> 
> @Catscratch Completely off-topic - but when I opened your test document, this sentence caught my eye: "many say we should pay for the water based on how much we use". I can't believe it: you don't have water meters? They are so common in Europe I thought they're used everywhere. :)

Sorry to disappoint you, but it's not my document. It's just a random one from the internet that I use for testing. ;-)

**Comment by stephanrauh** [comment]
@philippendrulat I'm still fighting with ES5 support for the PDF worker, so I didn't wan't to commit my code yesterday. Sorry for the inconvenience! 

BTW: the pdf.worker.js file should be available as localhost:4200/assets/pdf.worker.js.

**Comment by stephanrauh** [comment]
@philippendrulat Now it's landed. Please update to version 1.5.1. It fixes the rotation bug and allows you to define a custom path for the pdf worker. I needed that for IE11 support.

Updating  https://github.com/stephanrauh/extended-pdf-viewer-showcase should give you a working example. It's the same as https://pdfviewer.net.

**Comment by Catscratch** [comment]
Thanks Stephan.

I tried it. Seems to work. At least the fake worker message disappeared. But nevertheless the performance seems not to be changed. The whole ui is still blocking for the heavy pdf file. Also its still taking loooong time to render it. Did I missed something here?

**Comment by Catscratch** [comment]
Thanks Stephan.

I don't get things running here.
I updated to 1.5.1 and added ```defaultOptions.workerSrc = './assets/pdf.worker-es5.js';```to app.component.ts.

Furthermore I checked that the asset is accessible through the browser. It is!

But I still get the "setting up fake worker" message. Any chance to debug into here?

**Comment by stephanrauh** [comment]
@Catscratch Correct! I tried to document these steps, but I'm not sure I've managed to finish that. If there's something missing in the doc, just tell me.

BTW, I'm glad it finally works on your PC!

**Comment by Catscratch** [comment]
Only difference is, I switched to the newer versions without "-es5" suffix.
