### ISSUE TITLE
ctrl + and ctrl - to zoom in and out break emitZoomChange() 

### ISSUE THREAD

**Issue by CMadden8** [stephanrauh/ngx-extended-pdf-viewer#137]
@stephanrauh - I have three items I'd like to raise. 

1) We found another hotkey-related issue, as they're popular with the users of the app. This time it's the ctrl + and ctrl - hotkeys that allow you to zoom in and out. If used, the new zoom figure never gets emitted by emitZoomChange(), since it appears to only be monitoring the clicks on the UI's zoom toggle. It creates a few change detection problems when dynamically setting the zoom level, since updates to the zoom level can be ignored even when they shouldn't be.

In the pdf-viewer.js, you'll see the below that's causing the issue:

```javascript 
        case 61:
        case 107:
        case 187:
        case 171:
          if (!isViewerInPresentationMode) {
            PDFViewerApplication.zoomIn();
          }
  
          handled = true;
          break;
  
        case 173:
        case 109:
        case 189:
          if (!isViewerInPresentationMode) {
            PDFViewerApplication.zoomOut();
          }
```

2) I see you have `@Output pageChange` - it's not mentioned in the configuration options on the homepage, but it works. We were going to ask for this, as it's a lot more flexible than `[(page)]`. Just in case someone else goes looking for it!

3) This is more a feature request than a bug. Currently, the viewer generates thumbnail images of the available pages. These are dynamically printed into `<a href=""></a>` elements. Unfortunately you can't focus or click anchor links with JavaScript (at least not with any methods I tried). If it were possible, would they be better as radio buttons, styled to look as they do now?

Benefits would be: a) radios can be easily focused with JavaScript; b) up/down/left/right arrows are easier to select elements with than tab and tab+shift; c) radios automatically get selected with keyboard keys (currently you have to select the new page with spacebar). Just a thought! I'm sure there are many ways to make it easier, but the anchor links are difficult to work with at the moment.

**Comment by stephanrauh** [comment]
Let's start with number 2. I've started to document the event of the `[(banana-in-a-box)]` attributes. Please have a look at https://pdfviewer.net/attributes. Is it already good, or do I have to mention the `(banana-in-a-boxChange)` event explicitely in the first column?

**Comment by stephanrauh** [comment]
Number 1 works fine on my MacBook using Firefox. When I zoom in or out using the keyboard, the `(zoomChange)` event fires reliably. It is an OS or browser-specific problem?

**Comment by stephanrauh** [comment]
Number 3 is weird. In theory, it should be enough to set the `tabIndex`. However, when I tried, I learned that almost no element of the toolbar can be selected with the keyboard. That's strange because they already have `tabIndexes`, ranging from 1 to 68. I've already added `tabIndexes` to the thumbnails, but to no avail. You can't tab through them. Is it the same on your machine?

**Comment by CMadden8** [comment]
@stephanrauh - sorry, I'm swamped at the moment :) I don't have enough brain cells left to answer your questions, or test the problems again. I'll double check with the ctrl + and -, but it was definitely not triggering the CD for me. Only triggered CD if I clicked the + and - buttons. I'll get back to you!

Regarding the thumbnails - it is a problem with focus, more than tab. The thumbnails are anchor links. I assume it's deliberate that you can't focus on anchor links or click them with JavaScript. You can tab to them, but not click them. Imagine if you loaded a malicious site and it clicked a malicious link with JS?

What we are trying to do with your library is this - once the doc has loaded (it takes 10secs from server), we want it to automatically focus on the pager thumbnails. Because our users do everything with the keyboard - and it makes sense, it's quicker :) But we can't do it with anchor links. I tried the hacks -they don't work, If they were radios, you could easily style them and make them focus-able with JS. Hide the radio inputs, use the labels as triggers is the standard.

Sorry if it's too vague - give me a week and I think I'll be free to try and contribute a fix for this, but I can't at the moment ;)

**Comment by stephanrauh** [comment]
Sounds good. Take your time. I'm going to have little to none time during the next three weeks, so I'm afraid I can't do much to help.

I like the idea of using the PDF viewer with tabs. I'm afraid it's going to be difficult to implement the feature: the thumbnails are generated by Mozilla's pdf.js project, not by me. I've modified the core libraries frequently - I've even written scripts to modify the core lib automagically - but that seems to be a major change, not just a few lines. I hope it's possible nonetheless!

**Comment by stephanrauh** [comment]
I've investigated the first issue:

- `(currentZoomFactor)` emits the zoom factor, even with the keyboard
- `(zoomChange)` didn't react to the keyboard. Sorry for the wrong initial analysis.

I've modified `(zoomChange)`. Now it also reacts to the keyboard events. Sometimes it fires twice. I'm not sure if I should prevent this. I've decided to publish version 1.6.0 with the double-fire-behaviour. IMHO that's better then firing to seldom.

**Comment by stephanrauh** [comment]
Shipped the feature with version 1.6.0. Enjoy!

**Comment by stephanrauh** [comment]
After extracting request #3 to a dedicated issue, I'm closing this ticket now.

**Comment by CMadden8** [comment]
Much appreciated!
