### ISSUE TITLE
Small issue after upgrading to v13: scaleSelect is created as a span-element, not select

### ISSUE THREAD

**Issue by barnewsapp** [stephanrauh/ngx-extended-pdf-viewer#1376]
Hi @stephanrauh 

I just upgraded to v13 and found a small issue. 

The bug is related to a change is this file: 
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pdf-dummy-components/pdf-dummy-components.component.ts#L10

You added scaleSelect as a requiredId. 
But in the code bellow the same ID is hard coded to check for scaleSelect to create a select-element. 
But now this code is dead because it is always created as a span-element first. 

This in turn causes issues here because a select-element with options is expected: 
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1967

Have a nice day!

/Bjørn

**Comment by stephanrauh** [comment]
Interesting. The bug you've found is similar to the bug I've fixed. Thanks for reporting it!

**Comment by stephanrauh** [comment]
Version 13.5.0-alpha.0 fixes this. Hope this time for real - there's a reason why I call it an alpha version. However, I intend to publish the final version 13.5.0 featuring the new version of pdf.js (published last weekend) soon.

**Comment by stephanrauh** [comment]
I've just shipped version 13.5.1. I'm closing this ticket now.
