### ISSUE TITLE
File name problem

### ISSUE THREAD

**Issue by krishnamoorthy51** [stephanrauh/ngx-extended-pdf-viewer#1388]
hii 
i have # on my file name its brakes the local pdf link and i am getting error with invalidate pdf constructed

**Comment by krishnamoorthy51** [comment]
<ngx-extended-pdf-viewer src="https://example.com/demo#file.pdf" >>> exactly i am trying to say this issue only. i am having hash in file name and the file size around 66mb if i am using Blob how long it take to load the pdf ???

**Comment by stephanrauh** [comment]
I've debugged the source code. The url is passed correctly to the `fetch()` function (see https://javascript.info/fetch-api). It seems that JavaScript simply doesn't allow for hashes in URLs.
