### ISSUE TITLE
Images paths issues on application name hosting

### ISSUE THREAD

**Issue by bdi-gud** [stephanrauh/ngx-extended-pdf-viewer#1399]
Hello,

When deploying our application on a server that contains an application name as a subfolder, the paths to retrieve some images (svg) are wrongly pickup. Below the struture concerning our frontend applications:

- http://host:10004/application1
- http://host:10004/application2
- http://host:10004/application3
 
The error message below when opening a file:
treeitem-expanded.svg:1          GET http://host:10004/assets/images/treeitem-expanded.svg 404

As you can see, the application name has been removed during the call to retrieve the image. The expected call would be on http://host:10004/application_name/assets/images/treeitem-expanded.svg

After some investigations, we found that the call on the images(svg) contains a relative path that would automatically remove the application name. Below the css that call the images:

content:url(../assets/images/treeitem-collapsed.svg)
content:url(../assets/images/treeitem-expanded.svg)

The expected content:url to make it works on our side would be ./assets/images/filename.svg with only a point.

Could you please let us know whether this issue should be fixed on your side or is there a way to rebuild the content:url so that we structure properly the paths on the images?

See the attached screenshots for an overview of the impact of the issue.
![with_bug](https://user-images.githubusercontent.com/83651463/171358765-f30c926c-a163-4219-a2d6-7b4287dc5405.jpg)

**Expected with correct paths:**
![without_bug](https://user-images.githubusercontent.com/83651463/171358798-e197c3b0-3789-413e-bb92-a2d4ffe1a4ac.jpg)

**Comment by stephanrauh** [comment]
The bugfix has shipped with version 13.5.2.

Enjoy!
Stephan
