### ISSUE TITLE
using blob url in ionic, pdf viewer is not working

### ISSUE THREAD

**Issue by boboplush** [stephanrauh/ngx-extended-pdf-viewer#1400]
using blob url in ionic, pdf viewer is not working in ionic android, working fine in browser!

```typescript
  ngAfterViewInit(): void {

    setTimeout(() => {
      this.loadPdf();
    });
  }


loadPdf() {
    this.http
      .get(this.pdfSrc, {
        responseType: 'blob',
      })
      .subscribe((response) => {
        this.src = response;
        this.loaded = true;
      });
  }
```

```html
<ion-content fullscreen>
  <ngx-extended-pdf-viewer
    *ngIf="loaded"
    [showSecondaryToolbarButton]="false"
    [backgroundColor]="'#ffffff'"
    [showToolbar]="false"
    [src]="src"
    [showFindButton]="false"
    [showBorders]="false"
    (pdfLoaded)="loadCompleted()"
    (pdfLoadingFailed)="loadError($event)"
    [height]="'100%'"
    [zoom]="'page-fit'"
  ></ngx-extended-pdf-viewer>
</ion-content>
```

<img width="262" alt="Screen Shot 2022-06-01 at 8 51 03 PM" src="https://user-images.githubusercontent.com/106516045/171408561-d85dd32c-4a0d-47ad-8bb4-ce48aca82faf.png">

**Comment by stephanrauh** [comment]
I don't know how to reproduce the bug. I'm not familiar with Android. I'm afraid you have to walk me through installing Android Studio and everything I need to debug the bug.

Maybe it's easier if you do the debugging. Please set `[minifiedJSLibraries]="false"` and check the console. Is there any error message?

**Comment by FrancescoCapelli-dev** [comment]
I use this:
```
fileReader.onloadend = (e: any) => {
      this.pdfSrc= e.target.result;
      console.log(this.pdfSrc)
    };
fileReader.readAsArrayBuffer(this.uploadingfile)
```

**Comment by stephanrauh** [comment]
@FrancescoCapelli-dev Give me some context, please. Is your code snippet a solution or is it part of a reproducer?

**Comment by stephanrauh** [comment]
I haven't heard from your for several weeks, and I still don't know how to reproduce the issue. I'm closing the ticket now.
