### ISSUE TITLE
Using inside a form causes all the buttons to submit

### ISSUE THREAD

**Issue by fannin127** [stephanrauh/ngx-extended-pdf-viewer#142]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
n/a
- Does the bug also happen on https://pdfviewer.net/simple?
n/a

**Describe the bug**
Quite an odd use-case I'm aware. We're using the pdf-viewer inside of a form (for various reasons we can't get around). Clicking on any of the buttons inside the pdf viewer are triggering our onSubmit event. It would be nice if the buttons inside the toolbar had `type='button'` on them to prevent them triggering submits.

**Version info**
- Version of ngx-extended-pdf-viewer 1.5.1
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js 2.2.228

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 76

**To Reproduce**
Drop the `ngx-extended-pdf-viewer` inside a form 
Click a button inside the toolbar 
and it will trigger on submit.

**Demo PDF file**
n/a

**Additional context**
Couldn't decide whether to raise this as a bug or feature request. Feel free to shoot it down because it's a bit too edge case, but any help would be greatly appreciated!

**Comment by fannin127** [comment]
Classic agile, we've changed our minds about it being in the form ;)
Still might be worth considering though if anyone else has the same issue though?

**Comment by stephanrauh** [comment]
Sure, you're agile :) But I think your request is sensible nonetheless. Plus, it seems to be an easy change.

**Comment by stephanrauh** [comment]
I've published the feature with version 1.5.2. Thanks for opening the issue!

**Comment by fannin127** [comment]
Sounds good! Just didn't wanna request something that wouldn't be needed by a lot of people. :)
