### ISSUE TITLE
Print Preview displaying extra blank pages in Chrome and Edge but not Firefox.

### ISSUE THREAD

**Issue by Mcondino** [stephanrauh/ngx-extended-pdf-viewer#1431]
Hello There!

We've been having an issue with the PDF Viewer displaying extra blank pages in Chrome and Edge during the print preview. But it seems to work fine using Firefox. 
They don't seem to be counted as part of the total pages as well.

**Version info**
    "ngx-extended-pdf-viewer": "^14.0.4",

**Desktop **
 - Browser: Chrome Version 102.0.5005.115 (Official Build) (64-bit)
 - Edge: Version 102.0.1245.44 (Official build) (64-bit)
 - Print Preview displays correctly in Firefox 101.0.1 (64-bit)
 

**To Reproduce**
I've attached a copy of a 2 page PDF that I've been using to test.
In Chrome/Edge, print preview is displaying extra blank pages not being counted after each page, for a total of 4 pages in the preview.
![image](https://user-images.githubusercontent.com/107938323/174833437-b66301a3-dbcd-439f-84bb-9ee5981fc223.png)

In Firefox, it shows correctly, no blank pages for a total of 2 pages.
![image](https://user-images.githubusercontent.com/107938323/174833106-b3d8d29e-1391-4047-b62a-1684f00db2b1.png)

Thanks for taking a look at this for us!
[document.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/8950063/document.pdf)

**Comment by stephanrauh** [comment]
BTW: welcome to GitHub! Did you really join GitHub just to file this bug? I feel honored!

**Comment by Mcondino** [comment]
So, from what I could find via Chrome:

This CSS style is what seems to be giving me issues. The Width specifically.
image

If I set that to 99%, close the print preview and re-open it, then it shows correctly.

I have not had any luck trying to set that manually on my side.

**Comment by stephanrauh** [comment]
You're welcome! I'm glad you've managed to sort it out so quickly!

BTW, if you (or any other reader of these lines) are new to CSS and don't want to add the `!important` bit, I've written a [CSS survival guide](https://www.beyondjava.net/gentle-introduction-css) some time ago.

Cheers,
Stephan

**Comment by stephanrauh** [comment]
I've documented the debugging strategies now. The new text will show after the next deployment on https://pdfviewer.net/extended-pdf-viewer/troubleshooting.

**Comment by avdoseferovic** [comment]
> Oh no, not again! :)
> 
> This kind of bug is almost always a CSS issue. Printing is implemented like this: the PDF viewer generates an image for each page. A media query hides everything except these images. And some CSS magic makes sure that the images fit exactly into a page. If the image is half a pixel to large, you end up with additional pages. I suppose that's what happened.
> 
> When you create a blank project (`npm new demo && cd demo && npx add ngx-extended-pdf-viewer`), do you still see additional pages? If not, one of the CSS rules of your application cause trouble.
