### ISSUE TITLE
Print button - Inner container issue(Dialog)

### ISSUE THREAD

**Issue by bdi-gud** [stephanrauh/ngx-extended-pdf-viewer#1434]
Hello,

When using the component inside an inner container(Dialog), it looks like the print button is not aware of the current container.

![bug_print](https://user-images.githubusercontent.com/83651463/176437141-e2f64308-4767-496e-a38d-6e6a03af5ba2.jpg)

1) First time you click on the button print for only a preview, everything looks good. Then you close the dialog(container).
2) Second time you open a document and then you click on the button print, the below error is propagated in the console. This error will be shown everytime in the console when you use the print button again.

Uncaught (in promise) DOMException: Failed to execute 'showModal' on 'HTMLDialogElement': The element is not in a Document.
    at OverlayManager.open (http://localhost:4200/assets/viewer-2.14.308.min.js:22:70320)
    at http://localhost:4200/assets/viewer-2.14.308.min.js:22:304554

Note that there are no impact on the print. Everything looks ok, but this error looks like the print button is not aware of the current container.

Below the use of the component in our page:

<p-dialog [(visible)]="display" [breakpoints]="{'960px': '75vw', '640px': '100vw'}" [style]="{width: '70vw', height:'100%'}" (onHide)="onHide()">
        <div class="col-12 test" *ngIf="pdfSrc">
            <p-messages [(value)]="errorMessage" [closable]="false"></p-messages>
            <ngx-extended-pdf-viewer #pdfViewer [(src)]="pdfSrc" [showBorders]="true" [delayFirstView]="250"  [showHandToolButton]="true"
                [enablePrint]="true" [logLevel]="0" [showToolbar]="true" [showSidebarButton]="true" [showFindButton]="true"
                [showPagingButtons]="true" [showZoomButtons]="true" [showPresentationModeButton]="true"
                [showOpenFileButton]="false" [showPrintButton]="true" [showDownloadButton]="true" [showBookmarkButton]="false"
                [showSecondaryToolbarButton]="true" [showRotateButton]="true" [showHandToolButton]="true"
                [showScrollingButton]="true" [showSpreadButton]="true" [showPropertiesButton]="true" [useBrowserLocale]="true"
                [showUnverifiedSignatures]="true" height="80vh" [filenameForDownload]="filename">
            </ngx-extended-pdf-viewer>
        </div>
    </p-dialog>

We are not using any bootstrap css and have also read your section of 'Troubleshoot' without any success. We have used primeNg for our container - http://primefaces.org/primeng/dialog

Any help would be welcome.

**Comment by stephanrauh** [comment]
Would you mind to add the attribute `[minifiedJSLibraries]="false"` and to send me the line number where the exception is raised? Or, even better, a screenshot of the source code view of your developer tool?

I've tried to locate your error message in my source code, but to no avail. Maybe it's a PrimeNG message. I guess it's 60% my fault, 40% PrimeNG's fault. :)

**Comment by bdi-gud** [comment]
Hello,

I have included your attribute, but no more information is provided since the error comes from the **viewer-2.14.308.min.js**. I have located some open methods in the source codes of this script:

```
ensureOverlay().then(function () {
    if (activeService) {
      overlayManager.open(dialog);
    }
  });

async open() {
    await this.overlayManager.open(this.dialog);
    this.input.type = "password";
    this.input.focus();
    const passwordIncorrect = this.#reason === _pdfjsLib.PasswordResponses.INCORRECT_PASSWORD;

    if (!this._isViewerEmbedded || passwordIncorrect) {
      this.input.focus();
    }

    this.label.textContent = await this.l10n.get(`password_${passwordIncorrect ? "invalid" : "label"}`);
  }

async open() {
    await Promise.all([this.overlayManager.open(this.dialog), this._dataAvailableCapability.promise]);
    const currentPageNumber = this._currentPageNumber;
    const pagesRotation = this._pagesRotation;

    if (this.#fieldData && currentPageNumber === this.#fieldData._currentPageNumber && pagesRotation === this.#fieldData._pagesRotation) {
      this.#updateUI();
      return;
    }
```

In addition, what I have noticed when using the library in my inner container(p-dialog), some html codes, styles are generated on the entire html page without sticking to the current container. Example below:

**Before generating the component:**
`<html lang="en">`

**After generating the component**
```
<html lang="en" dir="ltr" style="--viewer-container-height:743px; --progressBar-percent:100%; --progressBar-end-offset:17px; --zoom-factor:1.19853;">
<style>
ngx-extended-pdf-viewer .textLayer{position:absolute;text-align:initial;left:0;top:0;right:0;bottom:0;overflow:hidden;opacity:.2;line-height:1}ngx-extended-pdf-viewer .textLayer span,ngx-extended-pdf-viewer .textLayer br{color:transparent;position:absolute;white-space:pre;cursor:text;transform-origin:0% 0%} etc...
</style>
```

Since those codes are added once the component loaded, even if I destroy my p-dialog component (visible), the entire html still contains all generated codes from the ngx-extended-pdf-viewer. 
I would expect that all generated codes stick to the div where it has been assigned (inner container) and I will easily be able to destroy once not needed. Or probably provide a method that would remove the entire generated codes from the html page.

**The full stack error if it can be helpful:**

```
viewer-2.14.308.js:4863 Uncaught (in promise) DOMException: Failed to execute 'showModal' on 'HTMLDialogElement': The element is not in a Document.
    at OverlayManager.open (http://localhost:4200/assets/viewer-2.14.308.js:4863:12)
    at http://localhost:4200/assets/viewer-2.14.308.js:20537:22
    at push.23484._ZoneDelegate.invoke (http://localhost:4200/polyfills.js:3538:30)
    at push.23484.Zone.run (http://localhost:4200/polyfills.js:3298:47)
    at http://localhost:4200/polyfills.js:4455:38
    at push.23484._ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3572:35)
    at push.23484.Zone.runTask (http://localhost:4200/polyfills.js:3343:51)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:3761:39)
```

**Comment by stephanrauh** [comment]
The stack trace is what I was looking for, and why I asked you to use the non-minified code. Now we know that the error message is an error message of the PDF viewer,  and not raised by PrimeNG:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/3045767/176664077-b6e31376-af84-4792-9de2-1b1485a5911e.png">

You can add a breakpoint to line 4863 and examine what `dialog` is, and what `dialog.showModal()` is supposed to do. I'll have a look this evening, too.

**Comment by bdi-gud** [comment]
Hello,

Thanks for your quick reply. Below some debugging on my side:

![debug_1](https://user-images.githubusercontent.com/83651463/176674401-2b7fa449-7847-467d-8c2a-0b0101fa1018.jpg)

Both #d and e represents a dialog#printServiceDialog

Some information about the object innerHtml and outerHtml

```
innerHTML: "<div class=\"row\"><span data-l10n-id=\"print_progress_message\">Préparation du document pour l’impression…</span></div><div class=\"row\"><progress value=\"0\" max=\"100\"></progress><span data-l10n-id=\"print_progress_percent\" data-l10n-args=\"{ &quot;progress&quot;: 0 }\" class=\"relative-progress\">100&nbsp;%</span></div><div class=\"buttonRow\"><button id=\"printCancel\" class=\"dialogButton\"><span data-l10n-id=\"print_progress_close\">Annuler</span></button></div>"


outerHTML: "<dialog id=\"printServiceDialog\" style=\"min-width: 200px;\"><div class=\"row\"><span data-l10n-id=\"print_progress_message\">Préparation du document pour l’impression…</span></div><div class=\"row\"><progress value=\"0\" max=\"100\"></progress><span data-l10n-id=\"print_progress_percent\" data-l10n-args=\"{ &quot;progress&quot;: 0 }\" class=\"relative-progress\">100&nbsp;%</span></div><div class=\"buttonRow\"><button id=\"printCancel\" class=\"dialogButton\"><span data-l10n-id=\"print_progress_close\">Annuler</span></button></div></dialog>"
```

If you need additionnal information, let me know.

**Comment by stephanrauh** [comment]
It seems the code appending the dialog to the DOM tree has gone lost, if I'm to believe StackOverflow: https://stackoverflow.com/questions/48444594/is-it-possible-to-create-modal-popup-only-from-javascript

**Comment by stephanrauh** [comment]
At the moment I don't have a PrimeNG project at hand, and I remember it's not simple to set up a PrimeNG project. Can you send me a reproducer project, please?

**Comment by stephanrauh** [comment]
I think I've found it. pdf.js tries to re-use a global variable, but that doesn't work after closing and re-opening the modal. Consider it fixed.

**Comment by stephanrauh** [comment]
BTW, I've decided not to change the `--viewer-container-height` bit. I could modify it, but I'm afraid if I do, I'm going to run into countless hard-to-detect merge conflicts with pdf.js in future.

**Comment by stephanrauh** [comment]
The bugfix has shipped with version 14.0.6.

**Comment by bdi-gud** [comment]
Hello,

I was working on a stackblitz last week https://stackblitz.com/edit/primeng-dialog-demo but when I start to include your lib, I was not able to properly see the errors.

I can confirm that your fix works.

Many thanks.

**Comment by stephanrauh** [comment]
Thanks! I'm afraid the PDF viewer isn't compatible to Stackblitz - but I don't know why, it's something to do with their project setup.
