### ISSUE TITLE
The ability to change the externalLinkTarget

### ISSUE THREAD

**Issue by SeppeDev** [stephanrauh/ngx-extended-pdf-viewer#144]
I'd like to be able to change the externalLinkTarget from 0 to 2, so links in the pdf open in a new tab.
Maybe this can be done using an attribute?

Currently I'm writing something to go through the DOM, find the `<a>`'s and change the target, which is not a very nice way.

Thanks in advance for considering this!

**Comment by stephanrauh** [comment]
Since version 1.5.1, you can use the `defaultOptions` object to set the default external link target:

```typescript
import { defaultOptions } from './default-options';

defaultOptions.externalLinkTarget = 2;
```

You need to run this code snippet before opening the PDF file. So probably the `AppModule` (or another module) is a good starting point.

Does this solve your problem? Please report back, so I can close the ticket or continue investigating it.

**Comment by SeppeDev** [comment]
Thank you for the fast reply, it works like a charm!

**Comment by rineez-livares** [comment]
> Since version 1.5.1, you can use the `defaultOptions` object to set the default external link target:
> 
> ```ts
> import { defaultOptions } from './default-options';
> 
> defaultOptions.externalLinkTarget = 2;
> ```
> 
> You need to run this code snippet before opening the PDF file. So probably the `AppModule` (or another module) is a good starting point.
> 
> Does this solve your problem? Please report back, so I can close the ticket or continue investigating it.

For those coming here via Google search, and wondering why you can't access this `defaultOptions` mentioned in stephanrauh's post above: In a later version of ngx-extended-pdf-viewer this `defaultOptions` property was renamed as `pdfDefaultOptions` .
```
import { pdfDefaultOptions } from 'ngx-extended-pdf-viewer';
pdfDefaultOptions.externalLinkTarget = 2;
```
Of course this options variable is mentioned in official documentation, but it took some time for me to connect the dots between this sample code and that documentation. So I hope this comment will help some others like me.

**Comment by stephanrauh** [comment]
Thanks for the hint, @rineez-livares! I've updated the text above. ngx-extended-pdf-viewer is intended to be fun and not to be a riddle! :)
