### ISSUE TITLE
PDF to thumbnails

### ISSUE THREAD

**Issue by bdi-gud** [stephanrauh/ngx-extended-pdf-viewer#1445]
The pdf sidebar comes with a nice display of thumbnails on the left when clicking on an icon button.

![pdf-sidebar](https://user-images.githubusercontent.com/83651463/177725268-1e243135-5e9d-4b79-9b2b-ca522b26a614.jpg)

When investigating on your code, the class being managed is the PDFThumbnailView and it comes also with a selector namely 'pdf-sidebar-content'.

Is there a way to allow this section to be autonomous by adding the PDF source as an 'Input'? Then we can:
- Display the pdf pages as thumbnails
- Provide a variable to retrieve the list of thumbnails as it is (base64)
- Allow  some configuration to the width and height of the thumbnails

Buy doing so, we will be able to display the thumbnails in another container for future management.

An example can be found at https://lexnim.github.io/pdf-thumbnails-generator/

**Comment by stephanrauh** [comment]
Interesting idea. Let me ponder about it for a while. In the meantime, I've got a partial solution for you: https://pdfviewer.net/extended-pdf-viewer/custom-thumbnails

**Comment by bdi-gud** [comment]
Thanks for the quick reply.

I do have read this section but unfortunately I was only able to change the sidebar layout overview and also I am forced to open the pdf pages via ngx-extended-pdf-viewer tag and both containers are opened (sidebar viewer and pdf viewer).

The idea would be to collect the generated thumbnails and then display those thumbnails in a custom container to allow users to change the order of the pages by using the thumbnail. 

Is there a way to retrieve the list of generated thumbnails via a specific method?

**Comment by stephanrauh** [comment]
If you're ready to put enough effort into this task, it is possible. It's just that at the moment, I'm not convinced I want to to it myself. If you want to have a look yourself, have a look at these three classes or files:

- https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/pdf_sidebar.js
- https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/pdf_thumbnail_view.js
- https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/pdf_thumbnail_viewer.js

I believe you'll find it easy to modify the viewer according to your needs. The reason why I'm more careful is I'm maintaining a fork of Mozilla's pdf.js, and I want to benefit from their updates. So I chose carefully which files I modify and which not. I don't want to end up in a "merge hell". Truth to tell, I'm already in that hell every couple of months.

**Comment by stephanrauh** [comment]
I'm afraid I'm still short of time, so I reluctantly close this ticket.
