### ISSUE TITLE
Search does not work as expected while searching phrase in multiple lines

### ISSUE THREAD

**Issue by akhilnimmala** [stephanrauh/ngx-extended-pdf-viewer#1449]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). **_No, it works as expected on pdfjs viewer_**
- Does the bug also happen on https://pdfviewer.net/simple? **_Yes, able to replicate issue on your website_**
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template **_No, will explain how to reproduce below and attached screenshot to help visualize the issue_**

**Describe the bug**
_While searching a phrase which lies in multiple lines next to each other the expected behavior is to highlight the text over in multiple lines, but it returns phrase not found._ 

**Version info**
- Version of ngx-extended-pdf-viewer _**14.0.6**_

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser] **_Chrome_**
 
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] **N/A**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug. It's always a good idea to start from a fresh, new project. There's a template project at https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template. A side effect is that writing a reproducer often helps you to find bugs of your code. This spares me the embarrassement of pointing our you bugs. More important, it saves me a lot of time. ngx-extended-pdf-viewer has become so popular that answering issues costs a lot of my spare time, so I appreciate your help.

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to **_your website "https://pdfviewer.net/extended-pdf-viewer/simple" with the example pdf on the viewer_**
2. Click on **_find/search button and try to look for this phrase which is on the page 2 "useful little doodads, like mousetraps" and it returns phrase not found. But if I search for "useful little doodads, **_likemousetraps_**" where I removed the whitespace where a newline happens, it works well but it is not expected behavior right?_**

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**
**_phrase not found -_** 
![image](https://user-images.githubusercontent.com/42742848/178729205-d93d677e-0c72-4a5d-85f9-5fc425284847.png)
**_phrase found when removed whitespace_** - 
![image](https://user-images.githubusercontent.com/42742848/178729315-3bbbb557-bb64-41b3-ad17-02a70f77ce08.png)
**_phrase search over multiple lines on pdf.js viewer_** - 
![image](https://user-images.githubusercontent.com/42742848/178729490-3e9b506e-d153-401a-9c01-8e52789aaa1d.png)

**Additional context**

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**_Thanks for the wonderful and very powerful pdf tool, looking forward to hear your thoughts. Let me know if you need any additional info. Hope we can find a way to resolve this_**

**Comment by stephanrauh** [comment]
I feel your pain. You say it works as expected on Mozilla's showcase? That probably means I have to raise the priority of #1181. I can only guess, but you make it sound like I've missed some useful updates.

Truth to tell, merging the all-new find engine with my shiny search engine is going to be a lot of work. But so be it. I'll have to do it one day or another. If the Mozilla team found a way to deal with line breaks, it's worth the effort.

In the meantime, you can activate the fuzzy search as a workaround. It's slow like hell, but it's fast enough in most documents, and it finds your useful little doodads.

Nice search term, by the way. I wasn't aware my demo PDF contains such a funny or colloquial sentence, so you caught my by surprise and caused a hearty laugh! :)

**Comment by akhilnimmala** [comment]
Thanks for prioritizing this Stephan, this will add a huge value.

Yeah agree with you on the fuzzy search, it is super slow and almost crashes while searching multiple lines. Looking forward for the latest search update.

Hahah that was a funny mistake, I did not while filling out the form

**Comment by stephanrauh** [comment]
I believe I'm managed to fix this. However, there might be side-effects. If you're trying to find special characters like 1/2, the highlighted text might be a couple of characters off.

Please update to version 14.5.3 and tell me if it fixes your problem!

Thanks in advance,
Stephan

**Comment by Bezno** [comment]
Hi, sorry for bring this again. I'm having the same issue but with getPageAsText, even in your demo when I hit the "Export as text" button happens.
![imagen](https://user-images.githubusercontent.com/13257348/202252448-9cf0c351-b910-48cb-9cbe-279e6450f1e2.png)

Any idea what can I do?

**Comment by stephanrauh** [comment]
Don't worry - if there's a bug, there's a bug, and I won't argue. :) Just one thing: would you mind to open a new ticket, please? Just copy your bug description and add a link to the this ticket. New tickets help me keeping track of my tasks.

As for what you can do: well, I'd appreciate a pull request fixing the bug, but I assume that's asking too much. If you want to give it a try, you're lucky. I believe this is one of the few tickets newbies can solve. Before you ask: there are no obligations, it's just my vain hope of talking you into doing my work.

I suspect the bug is a merge conflict resolved wrong. I'm pretty sure you have to modify the code of the base library (pdf.js), so there's nothing you can do as an application developer. It's a bug requiring a new version of the library. Or an old version - I believe the bug wasn't always there.
