### ISSUE TITLE
Rendering already loaded pages of a large PDF file

### ISSUE THREAD

**Issue by chriswin23** [stephanrauh/ngx-extended-pdf-viewer#145]
Hey, 

I have been trying to render large pdf files (over 100mb) and show pages that have been already downloaded using the accept-ranges attribute in the response header. I am using [this useful class](https://gist.github.com/chikien276/66229316147ba1180df2f84caff8730d) so that the server supports multipart file sender. The network tab in the developer tool is showing that the request using the header with the attribute accept-ranges are being made (packages of 64KB are being received). The issue I am having is that it does not show the pages that are already loaded. The first page is obviously being shown after the delay given in the parameters of ngx-extended-pdf-viewer, but the other pages are blank with a loading wheel. Though, once the entire file is loaded, then the file renders in its entirety without any issues.  It seems like it is just ignoring the packages received and waits for the entire file to be downloaded. 

#### Version info
- ngx-extended-pdf-viewer: "^1.5.2",
- Browsers: Chrome, Edge, Firefox
- Server side: Spring Boot

**Comment by stephanrauh** [comment]
Oops. That doesn't sound good. Thanks for pointing this out!

Are you using the service worker? Or do you still use the "old" approach I recommended before version 1.5.0?

Currently, I've got very little spare time, but I'll try to reproduce and fix your issue ASAP. Probably in a week or two.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
BTW, you can speed up things by sending me a reproducer. I suppose it's not easy to reproduce the bug because it requires both the client and a server. So chances are I implement things slightly different than you, which might result in, well, different results.

**Comment by chriswin23** [comment]
Thanks for your help.
I am using the service worker, so the issue should not come from there. I will try to do a reproducer, but as you said it, won't be easy. I will get back to you if I can manage to do one.

**Comment by stephanrauh** [comment]
Thanks for the reminder. During the last couple of week, I concentrated on the IE11 bugs, so there's no progress yet. However, I'm positive I can try to reproduce your bug soon.

**Comment by stephanrauh** [comment]
@chriswin23 You can speed up things by helping me:

- I'm familiar with Java, but even so, I shy away from creating a server. Obviously, you've already done that. Can you send me a down-stripped version of your server (or servlet, or Spring Boot application)?

- The biggest PDF file I've found so far is this one: https://www.obwb.ca/library/okanagan-basin-waterscape-poster/ Is it big enough to reproduce the bug?

**Comment by joywinmissier** [comment]
Hello,

Bigger PDF takes too much time to load in EDGE browser, is there any solution for this?
PDF viewer doesn't even load single thumbnail nor the main view in Edge instead it looks like hang !

How to handle larger pdf files in Edge using ngx-extended

**Comment by stephanrauh** [comment]
@joywinmissier Did you activate the service worker?

If the message "using fake worker" is shown, the performance is worse than it should be.

Best regards,
Stephan
