### ISSUE TITLE
Debugger in package version 14.5.0

### ISSUE THREAD

**Issue by blzpedro** [stephanrauh/ngx-extended-pdf-viewer#1452]
I have installed the ngx-entededed-pdf-viewer v^14.50.

When the ngx-extended-pdf-viewer package renders on my component, it stops on a "debugger".

The "debugger" it's in injectStyle() of the ngx-entended-pdf-viewer.mjs file.

To fix that I had to downgrade to v14.0.1. When I did that, got fixed.

**Comment by stephanrauh** [comment]
Oops. Yeah, that sounds like me. Sorry about that! Consider it fixed. I'll publish the bugfix soon (this week-end, probably).

**Comment by Dimanoid** [comment]
Any updates on this?

**Comment by stephanrauh** [comment]
It seems I've forgotten to publish the update. Sorry. I even remember publishing the update - but two or three days ago I stumbled upon the forgotten `debugger` statement.

**Comment by stephanrauh** [comment]
I've just published version 14.5.1. This time for real. Sorry for the inconveniences!

Best regards,
Stephan
