### ISSUE TITLE
Hyperlinks inside the pdf is not working

### ISSUE THREAD

**Issue by shravanipraharaj** [stephanrauh/ngx-extended-pdf-viewer#1457]
I have a pdf being rendered in ngx-extended-pdf-viewer, the pdf contains links to an external website. If I open the pdf in browser i am able to navigate to the external link , However if the same pdf is rendered in the pdf viewer the links an unclickable.
 <ngx-extended-pdf-viewer *ngIf="loadPdf"  [useBrowserLocale]="true"
                [showPresentationModeButton]="true"
                                         [src]="'../../assets/sample.pdf'" [textLayer]="true" [showHandToolButton]="true">
 </ngx-extended-pdf-viewer>

below code is also added to the component file 
pdfDefaultOptions.externalLinkTarget = LinkTarget.BLANK;

Attaching the pdf here for reference.
[sample.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9151641/sample.pdf)
[sample.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9151643/sample.pdf)

**Comment by stephanrauh** [comment]
The bug also happens with the the base library. Please open a ticket at https://github.com/mozilla/pdf.js/issues (and don't mention ngx-extended-pdf-viewer, because the bug isn't caused by my library).

BTW, I suspect there's something wrong or special with your document. In general, the viewer is able to create links with other PDF files.

**Comment by shravanipraharaj** [comment]
Hi can you share a stackblitz example where i can test if the links within a pdf is working or not. Also what do you mean by something wrong with the pdf shared by me. If I open this pdf in browser the links are working fine

**Comment by shravanipraharaj** [comment]
Also take a look at the attached pdf, this seems to be working fine in the browser and adobe pdf viewer where as when opend in ngx-pdf viewer it behaves weird.
[somepath.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9191650/somepath.pdf)

**Comment by stephanrauh** [comment]
ngx-extended-pdf-viewer is a nice façade of Mozilla's pdf.js. So it inherits bugs of Mozilla's PDF viewer. I didn't test it, but pdf.js is the PDF viewer of Firefox, so you should see the error if you open your file in Firefox.

I've tested your file with the default viewer of MacOS, so I can confirm you're right: there are PDF viewers out there that are able to render the hyperlink as a hyperlink. No idea why pdf.js doesn't  recognize the link.

As for the weirdness of your file: I didn't want to offend you. Sorry about that. I just observed that ngx-extended-pdf-viewer renders the hyperlinks of my own test file, but fails to do so using your file. Plus, I also observed that the showcase of Mozilla suffers from the same problem.

So I'd like to send you to the real experts. Remember, I'm just the guy adding a fancy Angular UI to Mozilla's pdf.js project. I can support you, if you wish so. It's just I've learned the hard way it's a bad idea to mention my project when opening a bug at https://github.com/mozilla/pdf.js/issues. One of the team members insists that pdf.js is the PDF viewer of Firefox, and almost always closes tickets that are not related to Firefox.

Best regards,
Stephan
