### ISSUE TITLE
PDF not opening correctly in ngx-pdf-viewer

### ISSUE THREAD

**Issue by shravanipraharaj** [stephanrauh/ngx-extended-pdf-viewer#1463]
@stephanrauh : I have a pdf, which we are trying to open in ngx-pdf-viewer. 
[somepath.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9191752/somepath.pdf)

This seems to be working fine in chrome, firefox and also adobe , but when I open the same file in ngx-pdf-viewer, it shows blank lines

**Comment by stephanrauh** [comment]
`PartialEvaluator.options.cMapUrl` seems to be null. But I haven't found out yet what's going wrong.

```
util.js:430 Warning: loadFont - translateFont failed: "UnknownErrorException: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.".
11:30:56.440 ngx-extended-pdf-viewer.mjs:5158 Warning: Error during font loading: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.
11:30:56.441 util.js:430 Warning: loadFont - translateFont failed: "UnknownErrorException: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.".
11:30:56.441 ngx-extended-pdf-viewer.mjs:5158 Warning: Error during font loading: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.
11:30:56.456 
```

**Comment by stephanrauh** [comment]
Found it! Please update to version 14.5.2. When you run a test, I'd appreciate your confirmation everything works as expected.

**Comment by stephanrauh** [comment]
By the way: Japanese fonts were broken since Mid March. That's a bit embarrassing. Can you provide me a Japanese demo PDF? Ideally, it's something cute and funny, something annoying nobody, and it has to be either public domain or it has to be under a Creative Commons license.

Thanks in advance!
Stephan

**Comment by shravanipraharaj** [comment]
@stephanrauh : I tested with the same pdf which I had attached in the ticket it still doesnt work, even after updating to 14.5.2. The document seems to be loading in the browser but not in pdf viewer

**Comment by stephanrauh** [comment]
Strange. Could that be a caching issue? Can you send me your console output?

**Comment by shravanipraharaj** [comment]
Hi @stephanrauh : Dont think its a caching issue . PFB the console output
![image](https://user-images.githubusercontent.com/109145536/182822139-c35edda9-34f2-498e-84d0-abdbf8527d39.png)

**Comment by stephanrauh** [comment]
You have to copy the CMAPs folder from `node_modules/ngx-extended-pdf-viewer/assets` to your assets folder. The console window shows the precise folder names. The CMAPs are your font - so it's not surprising the PDF document looks a bit odd when these files are missing.

**Comment by stephanrauh** [comment]
This is the folder I was referring to: https://unpkg.com/browse/ngx-extended-pdf-viewer@15.0.0-alpha.0/assets/cmaps/

<img width="930" alt="image" src="https://user-images.githubusercontent.com/3045767/182937362-230f10c9-3d9c-4b0e-900f-3abdadf4bf81.png">
...
<img width="908" alt="image" src="https://user-images.githubusercontent.com/3045767/182937588-34906aea-9742-48bc-95b1-5d6f6690af1f.png">

**Comment by shravanipraharaj** [comment]
Hi @stephanrauh : I added below lines of code to my angular.json file and also to the typescript file still no luck. Still getting cmaps not found, can you help?
 "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/cmaps",
                "output": "/assets/cmaps/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }
 pdfDefaultOptions.cMapUrl = () => './' + pdfDefaultOptions.assetsFolder + '/cmaps/';

**Comment by stephanrauh** [comment]
In general, I recommend adding the entire assets folder recursively because it's a complex folder structure:

```json
{
  "glob": "**/*",
  "input": "node_modules/ngx-extended-pdf-viewer/assets",
  "output": "/assets/"
},
```

Did you check the network tab of the developer tools? It shows which files the pdf viewer tries to load and which files are missing.

**Comment by stephanrauh** [comment]
BTW, your `cMapUrl` is precisely the default value:
```typescript
cMapUrl: () => `./${pdfDefaultOptions.assetsFolder}/cmaps/`,
```

**Comment by shravanipraharaj** [comment]
@stephanrauh : If you see the below code , entire assets folder is added in the script file .
"src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/cmaps",
                "output": "/assets/cmaps/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }

            ],
Take a look at the console, still the cmaps files are missing. Not sure if I am missing something
![image](https://user-images.githubusercontent.com/109145536/183297301-443b78cf-abcf-4538-9e39-46866025257e.png)

**Comment by stephanrauh** [comment]
If you want to include the entire assets folder, you need to specify two asterisks: `**/*`.

Build your application with `ng build` and check the `dist` folder. Is the entire assets folder there?

If it is, check the network folder. The error messages on the console window say that `./assets/cmaps/*.bcmap` isn't there. How is the relative URL `./` resolved? Maybe it's something unexpected.

**Comment by shravanipraharaj** [comment]
Hi @stephanrauh : Found the issue, issue was with  the cmaps url, the default url is ./assets/cmaps/,
when we use "glob": "/*",
"input": "node_modules/ngx-extended-pdf-viewer/assets/",
"output": "/assets/"
}  it by defaults copy all the assets stuff from pdfviewer into the assets folder of the project, due to the cmaps default url , it tries to find the items in assets/assets/cmaps .
changing the default url to below code made it work
pdfDefaultOptions.cMapUrl = () => './'  + '/cmaps/';

Thanks a lot for the support

**Comment by stephanrauh** [comment]
I'm glad it works now! The duplicate `assets` worries me a bit - I'll keep that in mind and check if it happens with my test projects, too.
