### ISSUE TITLE
Disable key bindings for n, p, j, k

### ISSUE THREAD

**Issue by limcheepei** [stephanrauh/ngx-extended-pdf-viewer#149]
Hi,

In the same page, I have both ngx-extended-pdf-viewer and ckeditor (for rich text editor) components. In the ckedictor, when I press n or p, the characters are not captured into ckeditor; instead the key event is detected by ngx-extended-pdf-viewer, and the PDF document was moved to next or previous page. For this scenario, I want to enter the characters into the ckeditor, and not trigger any event in gx-extended-pdf-viewer. 

Anyone has experienced this issue before?

Thanks in advance.

**Comment by stephanrauh** [comment]
Sounds like a sensible request. It's surprising nobody else reported this before.

**Comment by stephanrauh** [comment]
Ideas:
- [ignoreKeyboard] ignores the keyboard entirely. (I've already implemented this on my PC).
- [ignoreKeys] Array of keys to ignore. TODO: defined the format of the key (such as "CTRL+P" and "CMD+P")
- [accepsKeys] Array of keys to accept. Similar to [ignoreKeys], but just the other way round. Plus, if this attribute is set, every other key is ignored by default.. TODO: defined the format of the key (such as "CTRL+P" and "CMD+P")

**Comment by stephanrauh** [comment]
@limcheepei  I've just published version 1.7.3. It covers your use case. Please update to the latest version and add the attribute `[ignoreKeys]="['n', 'p', 'j','k']"`. Does that work for you?

BTW: I'll continue working on this feature. Currently, keys like "home" can't be configured. However, every simple key binding should already work.

**Comment by stephanrauh** [comment]
I guess I can close this ticket now. https://pfdviewer.net/keyboard give a pretty complete list of the keybindings, plus a live demo showing how to enable or disable most of them.

**Comment by limcheepei** [comment]
Thanks @stephanrauh 
It is working well.
