### ISSUE TITLE
Is there a way to check if the pdf has been scrolled?

### ISSUE THREAD

**Issue by rwitmans** [stephanrauh/ngx-extended-pdf-viewer#1493]
Hello!

Is there a way of checking whether the pdf has been scrolled? I have been trying to use a scroll event on the pdf viewer with no real results, and I was wondering whether there was already something in place for this.

With kind regards,
rwitmans

**Comment by stephanrauh** [comment]
There's. a low-level function you can use. It's low-level, so it might change without notice, but it's not likely to change any time soon: https://github.com/stephanrauh/pdf.js/blob/3bb60346573d760aa7f34875e51d31afa133dd90/web/ui_utils.js#L179

The PDF viewer uses this function to observe page scrolling:
https://github.com/stephanrauh/pdf.js/blob/3bb60346573d760aa7f34875e51d31afa133dd90/web/base_viewer.js#L314

At the end of the day, it's just a scroll event listener with a debouncer. So I'm puzzled you couldn't implement the scroll event yourself. You need to identify the `<div>` that's scrolling, so you can't use the Angular tooling. You'll want to implement a pure JavaScript scroll event listener plus some magic to trigger Angular's change detection after scrolling (see https://www.beyondjava.net/zonejs).

In multi-page mode (i.e. in default mode) the scroll container is `#viewerContainer`.
