### ISSUE TITLE
SSR  ERROR

### ISSUE THREAD

**Issue by e404r** [stephanrauh/ngx-extended-pdf-viewer#1495]
ncaught SyntaxError: Unexpected token '<'

**Comment by e404r** [comment]
Sorry, it was my mistake

**Comment by stephanrauh** [comment]
Let me guess: it was a missing JS file? :) I'm glad you've managed to figure it out!

**Comment by e404r** [comment]
> Let me guess: it was a missing JS file? :) I'm glad you've managed to figure it out!

Yes, I did not notice at first :)
