### ISSUE TITLE
possible to remove empty space where toolbar used to be?

### ISSUE THREAD

**Issue by skyleguy** [stephanrauh/ngx-extended-pdf-viewer#1498]
Hello, I am converting from ng2-pdf-viewer to this library but am running into an issue where i am left with blank grey space where the top toolbar used to be (I have set showToolbar and showBorders to false).

Is there a library-supported way of removing this blank space so my pdf is touching the edge of the container and not having this 'padding'? (view picture below)

I have been able to get rid of it myself by adding this styling at my root styles.scss file:

#mainContainer {
  margin-top: -30px !important;
}

but would rather not have to do this in case something changes with the library later on.

Thanks for the great pdf viewer!

Default:
![Screen Shot 2022-08-17 at 2 45 19 PM](https://user-images.githubusercontent.com/14967057/185219408-5d9232a3-e2bb-4245-8d00-c3a1e324e9d9.png)

Desired:
![Screen Shot 2022-08-17 at 2 52 06 PM](https://user-images.githubusercontent.com/14967057/185219672-e168cbfa-bcb6-4751-95ad-125330fcf871.png)

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 15.0.0-alpha.3. I've found an astonishing amount of broken code, so thanks a lot for point this out!

If you don't want to update to an alpha version, your workaround does the trick just as well. Basically, my bugfix does the same thing. It's more flexible, that's all. Just keep in mind you have to remove your workaround after upgrading to version 15.0.0.

Enjoy!
Stephan

**Comment by skyleguy** [comment]
now it seems the opposite problem is happening for me where the top ~30px of the pdf viewer seem to be getting swallowed up

![Screen Shot 2022-08-19 at 5 40 54 PM](https://user-images.githubusercontent.com/14967057/185710988-5fcf5ca4-fd99-404d-bde0-ddada9dbc61d.png)

note that you cant see the top of the scroll bar anymore

**Comment by stephanrauh** [comment]
I've prepared a bug fix, but I don't understand what's going wrong yet - so I prefer not to publish the bugfix yet. Publishing work-around that merely fix the symptom have a nasty tendency to come back to you. :(

**Comment by skyleguy** [comment]
definitely do not want to introduce any other problems with this. especially when there seems to be such an easy workaround

**Comment by stephanrauh** [comment]
The tentative bugfix has landed with version 15.0.0-alpha.5. I may modify it when once I understand what's going on, but I guess the current version is an improvement worth shipping.

Enjoy!
Stephan

**Comment by stephanrauh** [comment]
To dos left:
- [ ] understand why the viewer is shifted 33 pixels upwards when there's no toolbar

**Comment by skyleguy** [comment]
definitely seems like this issue has been fixed and i no longer need to mess with the mainContainer's margins

**Comment by stephanrauh** [comment]
You're welcome!
