### ISSUE TITLE
many warn messages every time the viewer is opened

### ISSUE THREAD

**Issue by skyleguy** [stephanrauh/ngx-extended-pdf-viewer#1500]
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).

No

- Does the bug also happen on https://pdfviewer.net/simple?

Yes

**Describe the bug**
Many warn logs in the console every time the pdf viewer is opened (Note also that the enhanceTextSelection is deprecated)

![Screen Shot 2022-08-19 at 11 45 29 AM](https://user-images.githubusercontent.com/14967057/185657031-979e1388-0487-4051-a4b6-23777105f08c.png)

**Version info**
- Version of ngx-extended-pdf-viewer: 15.0.0-alpha.4

 - Browser Chrome

**To Reproduce**
go to https://pdfviewer.net/extended-pdf-viewer/simple and see the console

Other Notes

Seems wrong to use the console filter to not log warning messages just to get rid of these

**Comment by stephanrauh** [comment]
Fair enough. Nobody wants to see warning for features I haven't made public yet. A short investigation revealed that the i18n support of the editor is surprisingly good. So maybe I "only" need to update the HTML code. Thanks for pointing this out!

<img width="655" alt="image" src="https://user-images.githubusercontent.com/3045767/185698875-2d57f1c5-5055-41b2-9600-95e47979d840.png">

**Comment by stephanrauh** [comment]
I've updated pdf.js in version 15.0.0-alpha.6. Chances are the warnings are gone now. Can you have a look, please?

**Comment by stephanrauh** [comment]
Thanks!

**Comment by stephanrauh** [comment]
I've removed the enhance text selection. Plus, I'm positive the warning are a thing of the past with version 15.0.0-beta.0.
