### ISSUE TITLE
find API seems to return true even when the search term was not found

### ISSUE THREAD

**Issue by skyleguy** [stephanrauh/ngx-extended-pdf-viewer#1502]
**Describe the bug**
The return value from `NgxExtendedPdfViewerService.find` always seems to be true even when the text does not exist

**Version info**
15.0.0-alpha.4

**Desktop (please complete the following information):**
Chrome

**To Reproduce**
1. Open PDF
2. try to use the find api with text you know does not exist
```ts
const example = this.ngxExtendedPdfViewerService.find(stringToSearch, {
      highlightAll: false,
      matchCase: false,
      wholeWords: undefined,
      ignoreAccents: undefined,
      findMultipleSearchTexts: false
    });
```
4. console.log the output of the find method
5. it seems to always be true

**Demo PDF file**
I used the user-experience.pdf example file present in the repo but it happens on all

**Screenshots**
![Screen Shot 2022-08-22 at 9 25 56 AM](https://user-images.githubusercontent.com/14967057/185932783-3164d584-f74b-4612-8a80-49dc5a6a71f9.png)

What actually brought us to this library (other than our previous pdf viewer being outdated) was the strong find features. when the text does appear in the doc the viewer works great but we would like to be able to provide the user with some reason why they were not taken to text if it doesnt exist and cant seem to do that if the output is always false.

Also is there a way to trigger a find without actually being taken to the place the text was found? we are currently showing a list of snippets that should be in the doc but would like to trigger a find on all snippets to disable any that are not found before the user has a chance to click on them and not be taken anywhere. 

Thanks for the great library!

**Comment by stephanrauh** [comment]
The find API is asynchronous, so the return value doesn't mean much. It just tells you it was able to fire the find request. If you call the API before the PDF viewer finished initializing, it returns false.

Come to think of it, the find API is very old. I guess I can improve it now. Maybe it's possible to add a callback function and an option to skip scrolling the match into view. 

An even better option might by to implement an `Observable` because find results are a stream of events - but that's more difficult, so I won't promise anything yet.

**Comment by skyleguy** [comment]
Definitely seems like a cool feature to have as currently the only way a user knows what they searched is not available in the PDF is the lack of anything happening

**Comment by skyleguy** [comment]
hey i know you're still considering this but is there any way you can think of that would let me know now that the word was not found? I attempted to bind to the pdf viewer's scroll bar to see if it moved or not after a find but that proved to be rather unreliable.

**Comment by stephanrauh** [comment]
It's easier than I expected. There are three low-level events you can use:
- updatetextlayermatches
- updatefindmatchescount
- updatefindcontrolstate

The latter seems to be the most useful event.

You can use them like so:
```ts
const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
PDFViewerApplication.eventBus.on('updatefindcontrolstate', (x: any) => {
        console.log("Hurray, new information about the find result!");
        console.log(x);
});
```

You should also add a call to `eventBus.off()` in your `ngDestroy()` method.

When I convert this into an official API, I'll try to convert `event.on()` into an `Observable`.

**Comment by stephanrauh** [comment]
Oops. Your feature is already there, just a little different than ordered. Check out the events `(updateFindMatchesCount)` and `(updateFindState)`.

Enjoy!
Stephan
