### ISSUE TITLE
page label showing incorrect

### ISSUE THREAD

**Issue by aishwaryalima** [stephanrauh/ngx-extended-pdf-viewer#1505]
Hi,
The page label in input field is showing incorrectly only for this document. I am using angular11 pdfviewer10.5

<img width="954" alt="pagination" src="https://user-images.githubusercontent.com/46273974/186109161-7683d0f2-e9b7-423e-a138-2a760055086e.PNG">

**Comment by stephanrauh** [comment]
I don't think so. Your document is an excerpt from a huge journal. The page labels refer to the page number of the original publication. I didn't find your demo document, but I've found another version of the same document. Look:

![image](https://user-images.githubusercontent.com/3045767/189497512-bbe38522-35bc-4041-9879-224b3ad47092.png)
