### ISSUE TITLE
PDF viewer not loading in single-spa application

### ISSUE THREAD

**Issue by akhilaet-92** [stephanrauh/ngx-extended-pdf-viewer#1508]
I am using ngx-extended pdf viewer for rendering PDF in my angular 13 application. The pdf viewer is not loading inside single spa micro frontend application. I have added the below asset mapping inside angular.json file 

```json
"assets": [
  "src/assets",
  {
    "glob": "**/*",
    "input": "node_modules/ngx-extended-pdf-viewer/assets/",
    "output": "/assets/"
  }
],
```

and also set the pdfDefaultOptions.assetsFolder path to point to the MFE path,
`pdfDefaultOptions.assetsFolder = mfe-base-url + 'assets';`

But the pdf viewer appears with a blank screen.

How do we resolve this issue in single spa? Thanks in advance.

**Comment by stephanrauh** [comment]
At first glance, your setup look OK to me. Maybe the assets aren't where the PDF viewer expects them to be. You've already investigated this, but still, based on my limited information, it's my best guess.

Please add the attribute `[minifiedJSLibraries]="false"`. That slows down your application, but makes debugging a lot easier.

After that, run your application and check both the console window of your browser's developer tools and the network tab. Plus, check the `build` folder of your application. Are there any files requested by the PDF viewer but missing in the `build` folder?

Generally speaking, it's also a good idea to create a green-field application using the approach described here: https://pdfviewer.net/extended-pdf-viewer/getting-started. I know it's not related to your problem, but it's an approach delivering a working application, so you can examine how things are supposed to work. Comparing this to your application helps most people to find the issue.

Good luck, and keep me in the loop, please!
Stephan

**Comment by stephanrauh** [comment]
Your stack traces are much more useful if you add `[minifiedJSLibraries]="false"`. BTW, what stops you from using version 15.0.0? I'm going to release it soon. I've learned the hard way not to make promises, but my goal is to publish it this week-end.

**Comment by akhilaet-92** [comment]
@stephanrauh Yes, I can use 15.0.0. But I was unable to use customToolbar with 15.0.0 as I was getting the above mentioned js errors while adding customToolbar attribute. Is there anything else I need to do for fixing the customToolbar issue?

**Comment by stephanrauh** [comment]
Yes. I've just published version 15.0.0-alpha.6. Please run a test and tell me if there's a difference. Actually, it may be worse or better: I've been surprised by a pdf.js update last week-end, so it may be both. I've run a quick test, unless you're using forms everything should be OK.

As for the custom toolbar: can you send me a code snippet? Or even better, can you me a reproducer?

**Comment by akhilaet-92** [comment]
@stephanrauh  Yes, 15.0.0-alpha.6 version is working fine in single-spa application and customToolbar also works fine. Thanks for providing the latest version and timely response. Hope we will get the stable version 15.0.0 published soon. Thank you.

**Comment by stephanrauh** [comment]
Awesome! I didn't expect it to be so easy... but I'm glad it is!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
You've mentioned this in another ticket, so bear with me when I quote myself... :)

Well, my library does not work with AMD modules. I'm not sure I could make it work, even if I wanted to. But Angular is an opinionated framework, and it doesn't use AMD modules, so I suspect Angular doesn't play well with this module system. It's one of those thing I don't even try because it looks like an uphill race.

Be that as it may, I wonder why you've set `define.amd={}`. Is this only the default value? Maybe it's a left-over from earlier times? Or do you populate the object over time?

**Comment by ietabhi** [comment]
Sorry about confusion, my application is inside SPA container and we have system.js and amd.js as prerequisite.
So define and amd is added into window object and causing issue for me.

I am not able to bypass this condition which is checking with "define.amd" and iffe stop working as it come out of this method and pdf.js i not loading.

If i reset define.amd = null, pdf will work fine but in SPA we cannot make this changes if we have multiple apps running.

**Comment by stephanrauh** [comment]
Are you talking about this framework? https://single-spa.js.org/

I'm afraid I can't solve the issue. However, there's a workaround. You can put the PDF into an iFrame.

I know iFrames are frowned upon for a good reason, but this reason usually does not apply to embedded PDF files. It's still an ugly workaround, but hey, it works! You can see a live demo (including source code) here: https://pdfviewer.net/extended-pdf-viewer/side-by-side
