### ISSUE TITLE
Feature Request: Disable/hide pdfjs print progress in order to display a custom one. 

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#151]
Would it be possible to disable the built-in pdfjs print dialog so that I can display my own?

Based on the beforePrint and afterPrint I can show and hide a custom progress. 

Also, if I can show my own, is there a way to get the pages processed?

Thanks!

**Comment by stephanrauh** [comment]
I'm not sure if it's possible, but I'll examine it. However, I don't understand the last question. What does "getting the pages processed" mean?

**Comment by pedrojrivera** [comment]
For example, pdfjs renders each page as an image to send to the printer. Whenever a page has been rendered it increments the progress bar. If there was a way to know its progress we could have an emitter to inform the user of progress while printing.

**Comment by pedrojrivera** [comment]
@stephanrauh I was able to disable the pdfjs print dialog and implement our own. I was also able to get the current page processed. I don't know if this could be ported over to your library. I did test this in several browser with success.

Here is how I was able to do it:

1. Disable the the print dialog via css
```typescript
    #printServiceOverlay {
      .dialog {
        display: none !important;
      }
    }
```

2. Show and close our own modal with progress bar and cancel button using before and after print

3. Calculate current page being rendered by using a **MutationObserver** over **#printContainer**. Here is a snippet of the relevant code:

```typescript
  ngOnInit() {
    const node = document.querySelector('#printContainer');

    if (node) {
      this._observer = new MutationObserver(mutations => {
        mutations.forEach(mutation => {
          try {
            const count = mutation.target.childNodes.length;
            this.printPercentage = Math.round((count / this.data) * 100);
          } catch (error) {
            this.printPercentage = 0;
          }
        });
      });

      this._observer.observe(node, {
        childList: true
      });
    }
  }

  ngOnDestroy() {
    if (this._observer) {
      this._observer.disconnect();
    }
  }
```

**Comment by stephanrauh** [comment]
Awesome! Truth to tell, I don't believe I can do much to make it simpler. So chances are your solution becomes the reference implementation. Fancy to provide a demo to https://pdfviewer.net ? The repository is https://github.com/stephanrauh/extended-pdf-viewer-showcase.

**Comment by pedrojrivera** [comment]
I will gladly provide a demo.

**Comment by pedrojrivera** [comment]
I prepared a demo ... I forked your project and changes are in branch  feature/customPrintDialog.

**Comment by stephanrauh** [comment]
The demo is online!

https://pdfviewer.net/custom-print-dialog
