### ISSUE TITLE
Saved passwords prompt from browser opening when clicking inside pdf-page-number

### ISSUE THREAD

**Issue by ppkh** [stephanrauh/ngx-extended-pdf-viewer#1511]
We have an issue when clicking inside the pdf-page-number input which results in saved password dialog from browser opening. I have no clue why that happens. Any ideas?

![image](https://user-images.githubusercontent.com/95472151/186688200-45e299a2-a2f3-4bea-994c-359ea845a655.png)

**Version info**
- 14.5.0

**Desktop (please complete the following information):**
 - Browser Edge

**Comment by stephanrauh** [comment]
Oh not, not again! I've solved this bug at least twice already. The PDF viewer contains an input field allowing you to open files protected by a password. This field is hidden almost all the time, but even so, it tricks browsers into thinking the page number is your user id. :)

**Comment by stephanrauh** [comment]
See #8 and #277.

Judging from the old commits, all I need to do is adding `autocomplete="off"` to the page number input field.

**Comment by ppkh** [comment]
While searching through the issue tickets I saw that there was indeed an issue in the passed. Hopefully it can be fixed this time forever 😃. Thanks for checking 👍

**Comment by stephanrauh** [comment]
The bugfix has landed with version 15.0.0-alpha.5.

Enjoy!
Stephan
