### ISSUE TITLE
Support Content-Security-Policy directive 'require-trusted-types-for'

### ISSUE THREAD

**Issue by hofsa** [stephanrauh/ngx-extended-pdf-viewer#1512]
When the CSP directive 'require-trusted-types-for' is active, the 'ngx-extended-pdf-viewer' component is not shown correctly in the browser and the following errors are shown in the browser-console:

`Uncaught TypeError: Failed to execute 'setAttribute' on 'Element': This document requires 'TrustedScript' assignment. 
 Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
`

Addition info for the 'require-trusted-types-for' - directive: [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for)

Example CSP-Header:
`
Content-Security-Policy: media-src 'self'; require-trusted-types-for 'script'; script-src 'self'; connect-src 'self'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; form-action 'self'; font-src 'self'; default-src 'none'; frame-ancestors 'self' ; frame-src 'self'; child-src 'self'; worker-src 'self'
`

Consider using 'TrustedTypes' ('TrustedScript' and 'TrustedHTML') when setting values for innerHTML and attributes in the DOM.

**Comment by stephanrauh** [comment]
That's probably the dynamic CSS. I'm not sure I can do something about it, but I can have a look. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
Support for `require-trusted-types-for` has landed with version 15.2.1.

Enjoy!
Stephan
