### ISSUE TITLE
Unhandled Promise Rejection: cannot read properties of null( reading 'classList')

### ISSUE THREAD

**Issue by skyleguy** [stephanrauh/ngx-extended-pdf-viewer#1513]
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template:

I have attempted to write a reproducer on my personal machine but the issue does not appear to happen with the few example pdfs from your repo that I pulled in.

https://github.com/skyleguy/extended-viewer-list-test

**Describe the bug**
My application shows a list on the left side of the screen and the viewer is present on the right. when clicking an item in the list that item's pdf will show. When rapidly clicking on items on the left (so essentially clicking a new element before the original item's pdf has had time to render/destroy) i sometimes get the error listed in the title of the document:

```Unhandled Promise rejection: Cannot read properties of null (reading 'classList')```

After setting minifiedJsLibraries to false i was able to see that this is the line it was mad about:

    document.querySelector(".body").classList.remove("loadingInProgress");

it does not seem to actually break anything or stop the user from interacting with anything at all. It is not showing up in the log filter either so I can not get rid of it.

- Version of ngx-extended-pdf-viewer: 14.5.3

 - Browser [basically Internet Explorer, Edge, or any other browser]: Chrome

**To Reproduce**
The only way to attempt reproduce was to create a repo that puts a few pdfs in a list with the choice of clicking on them to change the PDF rapidly, however none of the PDFs in this example caused my issue to show itself:

**Demo PDF file**
Unfortunately only happening in my companies internal PDF files so I cannot share any of them

**Additional context**
Seems to me that the PDF is already destroyed by the time the document is queried for .body so there is no classList to access

**Thank you!**
Sorry for bombarding with so many issues that _seem_ to be related to my companies documents, but seems like this could be possible for any application that lets you switch between PDFs quickly?

**Comment by stephanrauh** [comment]
Don't be sorry! :) You're right, switch documents rapidly is a challenge to the PDF viewer. You can try to set `[src]="undefined"` and setting the new URL after a short timeout. Maybe that helps.

I guess I can easily fix this particular bug - bug I'm afraid the next bug is lurking around the next corner, due to the highly asynchronous nature of pdf.js.

**Comment by stephanrauh** [comment]
In the meantime, the PDF.js team removed the offending line. So version 15.0.0 solves the problem.

**Comment by stephanrauh** [comment]
Version 15.0.0-beta.0 adds some additional resilience against this error message.
