### ISSUE TITLE
Wrong visualization of apostrophe char

### ISSUE THREAD

**Issue by fousto** [stephanrauh/ngx-extended-pdf-viewer#1519]
When I load a pdf with a 

> '

(apostrophe char) it's not shown correctly.
Below a preview:

![preview](https://user-images.githubusercontent.com/83006270/188173430-897d589d-f1c2-47a8-894b-258725ebb932.png)

**Comment by stephanrauh** [comment]
Please check your console window. Does the PDF viewer show errors there?

If not, please check if the bug also happens in my showcase (https://pdfviewer.net) or even on Mozilla's showcase (https://mozilla.github.io/pdf.js/web/viewer.html). If it happens in my showcase, but not in Mozilla's showcase, please send me a PDF file that's rendered incorrectly.

**Comment by fousto** [comment]
No errors on console window.
The bug occurs in your showcase and also on Mozilla's
[document_2013009988776.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9567370/document_2013009988776.pdf)

**Comment by stephanrauh** [comment]
Please open a bug ticket at Mozilla's showcase. Take your time and fill out their issue form meticulously: they receive an incredible number of tickets and tend to close issue quickly for formal reasons. In particular, don't tell them you're using my libraries. Luckily, you can reproduce the bug in Firefox, and that's usually your ticket to get your issue accepted. As you may or may not know, pdf.js is the PDF viewer of Firefox. I'm just using it to do things it was never intended to do. :)

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/3045767/190223781-13d29b6d-1e3d-41cf-aedd-ac0eb868e968.png">

Best regards,
Stephan

**Comment by stephanrauh** [comment]
For the sake of convenience, here's the URL of Mozilla's bugtracker: https://github.com/mozilla/pdf.js/issues

**Comment by fousto** [comment]
Thank you, it has already been fixed on Mozilla's showcase

**Comment by stephanrauh** [comment]
So fast? Awesome! I'll merge their latest changes, so you can test the bugfix in the "bleeding edge" branch. If I can wrap my head around their bug fix, I can even port it back to the stable branch. But probably not today - I'm busy this evening.

**Comment by stephanrauh** [comment]
This is the commit fixing the issue:

https://github.com/mozilla/pdf.js/pull/15442/files#diff-214dc188b83c6d2803399d8e0bbaf8691b2a4fffc1ef5fd2b9d3f4bb04890227

That looks simple enough to cherry-pick it to the default branch.

**Comment by fousto** [comment]
Alright, thanks. Please check also this https://github.com/mozilla/pdf.js/pull/15445.
Since I'm using version 10.5.0, the latest which still supports IE11 (if I'm not wrong), could you patch that version too?

**Comment by stephanrauh** [comment]
I'm not sure. I can try, but I'm not sure. Supporting an old version of pdf.js is always a challenge to me because my workflow isn't optimized for that. That, in turn, is caused by the sad fact that I'm developing the library alone. Dear open-source developers, please join this team so we can create an even greater library, including support for old versions and IE11!

**Comment by stephanrauh** [comment]
The bugfix ships with version 15.0.3. However, I didn't manage to back-port the bugfix to version 10.5.
