### ISSUE TITLE
Search result doesn't highlight the word

### ISSUE THREAD

**Issue by limcheepei** [stephanrauh/ngx-extended-pdf-viewer#153]
After the search result returns some matches, the viewer is not able to highlight the word.
 - Windows 7, Chrome 77.0.3865.120

Here is the re-production of the issue.
1. Go to https://pdfviewer.net/simple
2. Search for 'PDF'
3. Search for next 'PDF', and viewer unable to highlight the word.

![image](https://user-images.githubusercontent.com/914464/66733276-9476e800-ee91-11e9-9957-9849105b6cf5.png)

**Comment by stephanrauh** [comment]
I suppose this is basically the same as #116. Set `[handTool]="false"` or `[showHandToolButton]="true"` to solve the problem.

Please report back if this solves it, so I know I can close the ticket.

**Comment by stephanrauh** [comment]
The documentation on pdfviewer.net seems to be incomplete:

- [handTool] is missing
- Is the default value of `[showHandTool]` correct?
- Is source code shown at https://pdfviewer.net/find still up-to-date?

**Comment by limcheepei** [comment]
Adding [showHandTool] solves the problem. Thanks for the help.

![image](https://user-images.githubusercontent.com/914464/66737693-3a7d1f00-ee9f-11e9-9432-8f48ee07daef.png)

**Comment by stephanrauh** [comment]
I've also improved the documentation.
