### ISSUE TITLE
Spread operator used in es5 version of viewer prevents very old browsers to show pdf files

### ISSUE THREAD

**Issue by MasterATM** [stephanrauh/ngx-extended-pdf-viewer#1530]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
In Firefox 52.9.0 ESR, the error in the console is "SyntaxError: invalid property id".
- Does the bug also happen on https://pdfviewer.net/simple?
A blank page is shown and the error in the console is "SyntaxError: missing ( before catch".
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template
A reproducer is available here: https://github.com/MasterATM/ngx-extended-pdf-viewer-issues/tree/main/template

**Describe the bug**
In Firefox 52.9.0 ESR and ngx-pdf-extended-viewer>9.0.0-alpha.3, the pdf viewer fails to display the pdf. The error is shown in the console: "SyntaxError: invalid property id  viewer-2.14.311-es5.js:3434:13"
When opening the file, it highlights this line:
`return { ...this.documentInfo,`
The spread operator for objects is not understood by the old Firefox. The es5 version of the viewer includes the spread operator.

**Version info**
- Version of ngx-extended-pdf-viewer: 14.5.3

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]: Firefox 52.9.0 ESR
 
**To Reproduce**
1. git clone https://github.com/MasterATM/ngx-extended-pdf-viewer-issues/tree/main/template
2. npm install
3. npm run start

When opening http://localhost:4200 in Firefox 52.9.0 ESR, the pdf viewer is well shown but the pdf file is not loaded. Instead an error is displayed in the console:
console: "SyntaxError: invalid property id  viewer-2.14.311-es5.js:3434:13"

**Comment by stephanrauh** [comment]
Firefox ESR 52.9.0 ESR is more than four years old. I imagine you're slowed down by a very conservative operations department, or you can't update for some other reason. I feel you. Even so, I don't think I want to support this browser. 

In the realm of Internet Security, four years is an eternity. Even before the Russian assault using a four years old browser - even if it's a Firefox ESR browser - was a security risk. Nowadays, it's become even worse. Maybe you've managed to protect your IT infrastructure so you can afford to take the risk, but if I were to support such an old browser, I'd lead other developers into accepting security risks. Don't get me wrong: I know my influence is limited, but even so, it's a signal. I won't do that.

There's that. From a technical point of view, I'm afraid it's difficult for me to compile a version that's compatible to ECMAScript 5. If you want to do that, feel free. It's a lot easier for you. My problem is I want to be able to update to the latest version of pdf.js at any point of time, and the gulpfile is a rich source of nasty merge conflicts. Clone both ngx-extended-pdf-viewer and my fork of pdf.js, adapt [these lines](https://github.com/stephanrauh/pdf.js/blob/0ec25318aee06e99a664ddf216032d907384cc9c/gulpfile.js#L81) according to your needs, and you're good to go. At least I think so: I've lost track which lines need to be modified precisely to support older browsers. The command `./updateMozillasPdfViewer.sh` compiles the base library, and `npm run unix-package` or `npm run windows-package` bundles the PDF viewer in the `dist` folder.

I'm awfully sorry for not being able to be more helpful!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I forgot to mention I appreciate the effort you've put into writing the reproducer and the ticket. I've been able to spot the offending line of code within seconds. Few people go to such lengths, so I'd like to shout out a heart-felt "Thank you!" to you. From my point of view, your effort makes it even more difficult to say no!

**Comment by MasterATM** [comment]
Hello,
Thanks a lot for your response. Indeed, I am working for a company which blocks us with this old browser despite our numerous attemps to convince them to upgrade. And it is a real burden to carry: css incompatibilities, performance issues, new API not available, ... This FF 52 is even abandoned by Windows XP...

I totally understand your refusal to fix the issue: actually, your answer is very valuable as it is an additional argument which will put the company in a position where it is forced to upgrade the browser.

Thanks for your great library !

**Comment by stephanrauh** [comment]
If I can help you by just saying "no", I'll happily do it. :) If you company insists on using FF 52, I suppose compiling the library yourself does the trick, too. Of course, this adds to the cost of your project - and money is another good argument for your discussions. 

Good luck!
Stephan
