### ISSUE TITLE
Non Functional Floating Dialog Boxes upon render

### ISSUE THREAD

**Issue by tjanga** [stephanrauh/ngx-extended-pdf-viewer#1533]
**Describe the bug**
Adding <ngx-extended-pdf-viewer> to any component, and I get:

![image](https://user-images.githubusercontent.com/54868496/190578224-d1d150ce-6d14-4625-8cc9-5bb6fa4cb99c.png)

There seem to be dialogs that are covering content. The floating dialogs are non functional, and I can't close them.

**Version info**
Happens on: 15.0.2, 13.53
Does not happen on: 9.05, 10.5.0, 11.2.0, 12.1.2

**Desktop (please complete the following information):**
 - Chrome (latest), Firefox (latest)
 

**To Reproduce**
I cannot reproduce this in a simple project. When I create a project from scratch, I do not see this behavior. It seems there's something with my existing angular 13 project (that I updated from angular 11). 

**Demo PDF file**
This happens on all pdf files (and even no pdf file as in the screenshot)

**Additional context**
The strange thing is I put the pdf viewer in a form once, and clicking the 'close' button on the dialogs calls the formSubmit function of the form. It seems that something in my project is affecting the internal operations of the ngx-extended-pdf-viewer component.

**Comment by stephanrauh** [comment]
Yes, this bug is almost certainly caused by your Angular project. More precisely, there seems to be a CSS rule confusing the HTML+CSS code of the PDF viewer.

As for the `formSubmit`: no idea. That's probably a side-effect of displaying dialogs before the PDF viewer needs them.

However, that brings me to the final point: how come your screenshot doesn't display any PDF file? Did you leave `|src|` empty, or is the rendering engine broken? If so, please paste the error messages in the console window here. Before you do, set `[minifiedJSLibraries]="false"` because otherwise the stacktrace is useless to me.

**Comment by stephanrauh** [comment]
I'm not sure how familiar you are with CSS. Just in case you aren't: some time ago, I've written a quick CSS survival guide that seems to help quite a few developers: https://www.beyondjava.net/gentle-introduction-css

**Comment by tjanga** [comment]
@stephanrauh Than you so much for your response! It put me on the right track.

`_reboot.scss` was overriding the `dialog` style to specify `{display: block}`

I added: 
```
dialog:not([open]){
  display: none;
}
```
to `style.css` and it has resolved.

**Comment by stephanrauh** [comment]
I take it the `formSubmit` bit is also solved? That'd be great news!

**Comment by tjanga** [comment]
The formSubmit bit is not resolved. The dialogs are no longer showing up, but if i open a dialog (let's say hamburger menu > Document Properties ...), the dialog will show. Clicking 'Close' Will submit the form the viewer is inside.

**Comment by tjanga** [comment]
Update. The form submit problem is reproducible on the simple example.
app.component.html
```
<form (submit)="formSubmit()" >
  <ngx-extended-pdf-viewer
  [src]="'assets/foo.pdf'"
  [delayFirstView]="50"
  [useBrowserLocale]="true"
  [height]="'50vh'"
  [showHandToolButton]="false">
  </ngx-extended-pdf-viewer>
</form>
```

app.component.ts
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'test';

  formSubmit(){
    console.log('Form submitted');
    return false;
  }
}
```

Then if you open the document properties dialog, and click close, the form will be submitted.
