### ISSUE TITLE
Show Images from url

### ISSUE THREAD

**Issue by nazmuddin** [stephanrauh/ngx-extended-pdf-viewer#1535]
Is it possible to show images using this library ?

I tried showing the images using base64 feature. But I face this errror
```
PDF.js v2.16.445 (build: 357ab615d)
Message: Invalid PDF structure.
```
I first converted the image to a base64 string. If i simply paste this string to some web based base64 viewers it shows the image correctly.

**Comment by stephanrauh** [comment]
Well, this is a PDF viewer, not an image viewer. I don't see any point in adding this feature because it's so simple to display an image:
```html
<img src="https://example.com/my.jpg">
```
