### ISSUE TITLE
Add new event listeners (annotationLayerRendered, annotationeditorlayerrendered, xfalayerrendered, etc.)

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1536]
There are a couple of event developers might be interested in:

- [x] annotationLayerRendered
- [x] annotationEditorLayerRendered
- [x] xfaLayerRendered
- [x] outlineLoaded
- [x] attachmentsloaded
- [x] layersloaded

**Comment by korydondzila** [comment]
Definitely would be interested in the `annotationLayerRendered` it's something I was just looking for the other day as I needed to modify form inputs. Can still do it using `pageRendered` however.

**Comment by stephanrauh** [comment]
The new events are going to ship with version 15.2.1 soon.

**Comment by korydondzila** [comment]
Hi @stephanrauh thanks for adding this. I just tried using the `annotationLayerRendered` event, but it appears that it never gets called. I have it and `pageRendered` set up in the same way with a console log, `pageRendered` fires, but `annotationLayerRendered` does not.

**Comment by stephanrauh** [comment]
Incredible. Some time ago I've fixed a similar bug at the same spot. I've fixed the  bug in version 16.0.0-alpha.4, which will land soon. I hope this time the bug remains fixed!
