### ISSUE TITLE
Search functionality does not highlight/work for all occurrences when using custom findbar 

### ISSUE THREAD

**Issue by akhilaet-92** [stephanrauh/ngx-extended-pdf-viewer#1540]
Hi,

I am using ngx-extended-pdf-viewer version 15.0.0 in my angular 13 application. I have added the custom findbar option for customizing the search window. The search functionality does not work for all occurrences of the searching term when I search using custom findbar. I am adding more details below.

Scenario: I tried searching a term within a PDF document and which does not show all the occurrences of the term. This happens only if I use custom find bar. Search is working fine with the default find bar. I am attaching the screenshots of one sample pdf with and without custom find bar below. 

With Custom Find bar (shows only 13 matches):
![image](https://user-images.githubusercontent.com/62993854/192253375-c8d22897-51c2-4ae8-9278-3ef8bb83869b.png)

With default find bar (shows 32 matches):
![image](https://user-images.githubusercontent.com/62993854/192253683-acf41b58-f477-4f12-8a2f-d192e5abd47d.png)

Adding below the pdf viewer code I have tried:
![image](https://user-images.githubusercontent.com/62993854/192254216-99c5b529-a8c2-4853-8833-aa99b9bb43e9.png)

How do we resolve this issue? Appreciate any help here.

**Comment by stephanrauh** [comment]
That's very surprising. I'm short of time these weeks, so would you mind to debug the code yourself if I tell you how to do it?

First of all, use the non-minified version of the JavaScript code (`[minifiedJSLibraries]="false"`). This allows you to debug the code.

Now set a breakpoint here: https://github.com/stephanrauh/pdf.js/blob/2.16/web/pdf_find_controller.js#L491. You'll find this line in the file viewer-2.16.xxx.js by searching for the method name (`_calculatePhraseMatch` or `_calculateMatch `). Your bug description makes me suspect these methods receive different parameters, depending on whether you're using the standard findbar or your custom findbar.

Just a wide shot: maybe your custom toolbar activates the "entire word search".

**Comment by stephanrauh** [comment]
If I can't talk you into debugging, please send me a reproducer based on a new project (`ng new issue1540 && cd issue1540 && ng add ngx-extended-pdf-viewer`). I'm curious what the bug is. It's a pity I haven't got enough time for interesting issues now!

**Comment by akhilaet-92** [comment]
@stephanrauh sorry I couldn't spend time on debugging, I will give a try.. Meantime, I am adding my code details below, kindly have a look.

- component.html file

```
<ngx-extended-pdf-viewer
    [src]="pdfSrc"
    [useBrowserLocale]="true"
    [showFindButton]="true" [textLayer]="true"
    [customFindbarInputArea]="customFindbarInputArea" [minifiedJSLibraries]="false"
  [customFindbarButtons]="customFindbarButtons"
>
</ngx-extended-pdf-viewer>


<ng-template #customFindbarInputArea>
  <div id="findbarInputContainer">
    <pdf-search-input-field></pdf-search-input-field>
    <br />
    <pdf-find-previous></pdf-find-previous>
    <pdf-find-next></pdf-find-next>
  </div>
</ng-template>

<ng-template #customFindbarButtons>
  <pdf-find-input-area [customFindbarInputArea]="customFindbarInputArea"></pdf-find-input-area>
  <div id="findbarOptionsOneContainer">
    <pdf-find-highlight-all></pdf-find-highlight-all>
    <pdf-find-match-case></pdf-find-match-case>
  </div>
  <br />
  <div id="findbarOptionsTwoContainer">
    <pdf-find-entire-word></pdf-find-entire-word>
    <pdf-find-entire-phrase></pdf-find-entire-phrase>
  </div>
  <br />
  <div id="findbarOptionsThreeContainer">
    <pdf-find-ignore-accents></pdf-find-ignore-accents>
    <pdf-find-results-count></pdf-find-results-count>
  </div>
  <br />
  <pdf-findbar-message-container></pdf-findbar-message-container>
</ng-template>
```
And using the latest version 15.0.4. I am using this simple component to load pdf viewer and there is no other files involved. Please let me know whether this would be suffice for reproducing the issue from your end?

**Comment by stephanrauh** [comment]
Here's your reproducer: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue1540-custom-find

**Comment by stephanrauh** [comment]
As expected, it was an interesting bug. I'd implement a method with a default parameter. The default was basically meant to document how to use the method. However, in your scenario, the paramter `pageRange` is undefined, so my default kicked in. Hence, the find algorithm only searched pages 1, 3, 6, and 7:

```js
 // #832 modification by ngx-extended-pdf-viewer
  _isInPageRanges(page = 1, commaSeparatedRanges = "1,3,6-7") {
    try {
      if (!commaSeparatedRanges) {
        return true;
      }
      const parts = commaSeparatedRanges.split(",");
      return parts.some(range => this._isInPageRange(page, range));
    } catch (e) {
      return true;
    }
  }
```

**Comment by stephanrauh** [comment]
Updating to version 15.0.5 fixes the problem.

Enjoy!
Stephan
