### ISSUE TITLE
Buttons submit surrounding forms

### ISSUE THREAD

**Issue by yutamago** [stephanrauh/ngx-extended-pdf-viewer#1546]
At least one button has no defined type, which results in the surrounding form being submitted when you click the button.
A button should always include `type="button"` unless its supposed to submit a form.

I encountered this problem in the **document properties** and fixed it in the PR below.

However, while scrolling through more of your html files, I encountered **many more instances of this bug**.
I trust you're able to fix those as well.

**Comment by stephanrauh** [comment]
Sorry for responding so sluggishly. This evening, I had a look at the issue. I'm not sure about the "many" bit. I've found five buttons matching your issue. I guess that qualifies as "many" - but I wonder if I missed a button or two?

**Comment by stephanrauh** [comment]
The bugfix is going to ship with version 15.1.2 soon.
