### ISSUE TITLE
Allow users to browser through the page thumbnails with the keyboard cursor keys

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#155]
Originally taken from #137, submitted by @CMadden8:

 This is more a feature request than a bug. Currently, the viewer generates thumbnail images of the available pages. These are dynamically printed into <a href=""></a> elements. Unfortunately you can't focus or click anchor links with JavaScript (at least not with any methods I tried). If it were possible, would they be better as radio buttons, styled to look as they do now?

Benefits would be: a) radios can be easily focused with JavaScript; b) up/down/left/right arrows are easier to select elements with than tab and tab+shift; c) radios automatically get selected with keyboard keys (currently you have to select the new page with spacebar). Just a thought! I'm sure there are many ways to make it easier, but the anchor links are difficult to work with at the moment.

**Comment by stephanrauh** [comment]
@CMadden8: It took a while, but I've finally managed to address your issue. The thumbnails now react to the keyboard cursor keys. You can also add a radio button or a checkbox to the thumbnails. 

The implementation does not integrate perfectly into Angular, so more likely than not I'm going to re-work it again, but the current state of the art is already useful, as you can see at https://pdfviewer.net/custom-thumbnails.

**Comment by CMadden8** [comment]
@stephanrauh - awesome work! Honestly we haven't needed to look into any issues related to this for months, so all of the latest additions are enhancements to what's already working great. It's in very good shape right now, really appreciate all the work that went into this.
