### ISSUE TITLE
Print does not rotate landscape pages

### ISSUE THREAD

**Issue by adalbero** [stephanrauh/ngx-extended-pdf-viewer#1551]
**Check this first**

Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
NO
Does the bug also happen on https://pdfviewer.net/simple?
YES

**Describe the bug**
When printing PDF with Portrait and Landscape pages, the Landscape pages do not rotate, but shrink to fit the Portrait page size.
On Mozila showcase, Landscape pages are correctly rotated 90 degrees.

**Version info**
- Version of ngx-extended-pdf-viewer: 15.0.0

**Desktop (please complete the following information):**
 - Browser Edge and Chrome
 
**Smartphone (please complete the following information):**
 - Device: not tested

**To Reproduce**
1. Go to PDF Viewer Showcase
2. Upload a PDF with Portrait and Landscape pages.
3. Click on "Print"
4. See that the Landscape page does not rotate, but shrinks.
5. On Mozila showcase it rotates Landscape pages

**Demo PDF file**
[A4 Landscape.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9715662/A4.Landscape.pdf)

**Screenshots**
PDF Viewer Showcase:
![image](https://user-images.githubusercontent.com/9035622/194063436-f37da3ea-5d39-45d9-8846-63b5159b4c12.png)

Mozila Showcase:
![image](https://user-images.githubusercontent.com/9035622/194063532-bec377c5-5584-4b67-baa9-562f219e5f27.png)

**Comment by stephanrauh** [comment]
Sorry for the sluggish answer. I was a couple of week abroad. I'm still short on time, so I can't guarantee you a quick bug fix, but if Mozilla's showcase rotates the pages before printing, this is probably a bug. 

However, this also may be a recent improvement of Mozilla's viewer that didn't make it into ngx-extended-pdf-viewer yet. In particular, pdf.js 3.0 introduced serveral changes causing horrible merge conflicts in my fork of the project. Nonetheless, you can give the "bleeding edge" branch a try and check if it prints correctly.

As for the state of the bleeding edge branch: I'm tracking it in #1538.

**Comment by stephanrauh** [comment]
After a long search, it turns out that you can simply activate print rotation in the `pdfDefaultOptions`. By default, it was set to `false`. In version 16, I'm going to set the default to `true`.

```ts
pdfDefaultOptions.enablePrintAutoRotate=true;
```
