### ISSUE TITLE
Custom Thumbnails not showing. What I'm doing wrong?

### ISSUE THREAD

**Issue by mariusbolik** [stephanrauh/ngx-extended-pdf-viewer#1559]
**Describe the bug**
Hello Stephan! First of all, thank you for this awesome project! I really appreciate the hard work!
I am trying to implement the library into an Ionic App. It works well so far, but the custom thumbnails aren't showing up.

Here is my HTML:
```html
  <ngx-extended-pdf-viewer
    [src]="'/assets/bitcoin.pdf'"
    height="60vh"
    width="100vw"
    [showBorders]="false"
    [useBrowserLocale]="true"
    [showToolbar]="false"
    [contextMenuAllowed]="false"
    [textLayer]="false"
    [handTool]="false"
    [enablePinchOnMobile]="false"  
    [scrollMode]="1"
    zoom="page-width"
    spread="off"
    backgroundColor="var(--ion-color-step-100, #fff);"
    [customThumbnail]="thumbnails">
</ngx-extended-pdf-viewer>

<p>Thumbnails:</p>
<ng-template #thumbnails>
  <a class="pdf-viewer-template">
    <div class="thumbnail" data-page-number="PAGE_NUMBER">
        <input id="thumbnail-cbx-$page"
        class="thumbnail-radiobutton"
        type="radiobutton"
        style="top: 80px;right: 25px;position: relative;transform:scale(1.5)"
        onClick="window.PDFViewerApplication.page=PAGE_NUMBER;window.updateThumbnailSelection(PAGE_NUMBER)">
        <div class="thumbnailSelectionRing" style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING; display: contents">
          <div class="thumbnail-text" style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING;margin-bottom: -HEIGHT_OF_RING">
          </div>
          <div class="image-container">
            <!-- image is automatically inserted here -->
        </div>
      </div>
    </div>
  </a>
</ng-template>
```
**Version info**
- 15.0.5

**Desktop (please complete the following information):**
 - Opera 91.0.4516.77 macOS Version 12.6 (Build 21G115) 12.6.0 x86_64
 
**To Reproduce**
I created a small demo project: https://github.com/learn-ionic/ionic-pdf-viewer/
1. Clone repo
2. run `npm i` or `yarn`
3. run `ng serve`

**Demo PDF file**
https://bitcoin.org/bitcoin.pdf

**Screenshots**

<img width="80%" alt="Bildschirmfoto 2022-10-18 um 12 11 23" src="https://user-images.githubusercontent.com/39862171/196402432-429e06ec-40c4-4a8b-a0e5-c59d31936881.png">

Best regards,
Marius

**Comment by stephanrauh** [comment]
I'll have a look, but I'm afraid I'm short of time until Monday. At first glance, your code doesn't look wrong, but I'm afraid that info doesn't help you. In the meantime, you can checkout my showcase project and play with the custom thumbnails demo. It's possible you've hit a cornercase I didn't think about. In particular, I never tried to move the thumbnails below the PDF file. All I did was modifying the original thumbnails.

**Comment by stephanrauh** [comment]
Holy moly - I promised feedback not before Monday, but this particular Monday is more than a month ago. @mariusbolik Did you manage to solve the problem in the meantime? Do you still want me to look at it? Do you have any additional insight?

**Comment by stephanrauh** [comment]
Looking at your code snippet: the stuff written in capitals looks fishy. Did you copy it verbatim into your sourcecode? That won't work. `WIDTH_OF_RING`, `HEIGHT_OF_RING`, and the other capitalized texts are meant to be valid CSS size units. So the browser will assume a with and height of zero pixels when it hits this line:

```html
style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING; display: contents"
```

What does work is something like this:

```html
style="width: 100px; height: 150px; display: contents"
```
