### ISSUE TITLE
can we view write button in presentation mode ?

### ISSUE THREAD

**Issue by Mithlesh29** [stephanrauh/ngx-extended-pdf-viewer#1567]
@stephanrauh Hi , will we be able to view the write, pen, erase buttons in presentation mode in our ngx-extended-pdf viewer . 
Similar to the feature available in Microsoft powerpoint . I have attached a ss for ur reference

I am using nix-extended-pdf version - 9.01 

<img width="1728" alt="Screenshot 2022-10-25 at 3 06 32 PM" src="https://user-images.githubusercontent.com/97294709/197739835-1991cc09-daea-4270-951f-dbfbc2ac672a.png">

**Comment by stephanrauh** [comment]
@timvandermej @calixteman Do you have any plans to enable editing in full-screen mode?

**Comment by timvandermeij** [comment]
I'm not aware of plans for that. The currently planned work can be found in https://github.com/mozilla/pdf.js/projects/9.

**Comment by Mithlesh29** [comment]
That's okay . Thankyou so much for the clarification. 
You Guys are Amazing. @stephanrauh @timvandermeij

**Comment by stephanrauh** [comment]
I'm closing the ticket now because on the short term, I don't have enough time to spare to implement the feature. It's a pity, because it sounds fun and it might be a useful feature.
