### ISSUE TITLE
how about custom action on the pdf?

### ISSUE THREAD

**Issue by koo9** [stephanrauh/ngx-extended-pdf-viewer#157]
would be nice to be able to add custom action/button to the pdf view.

**Comment by stephanrauh** [comment]
I already thought about this, too. However, I don't know how people want to use the feature. Is it enough to add buttons to the toolbar and menu items to the secondary menu?

**Comment by koo9** [comment]
that will do!

**Comment by stephanrauh** [comment]
The feature has landed with version 2.0.0-alpha.18. Have a look at https://pdfviewer.net/custom-toolbar and chose the "additional buttons" demo. It shows how to implement a "open in new window"-button.
