### ISSUE TITLE
Accept Blob File

### ISSUE THREAD

**Issue by blindsz** [stephanrauh/ngx-extended-pdf-viewer#158]
Hi just wanted to ask if this is possible to accept blob file as an input?

**Comment by stephanrauh** [comment]
Yes, of course. Just pass the BLOB to the `[src]` attribute. `[(src)]` also accepts `Uint8Array` or an `ArrayBuffer`. The only exception are base64 encoded files. There's no reliable way to detect them, so I had to add the attribute `[base64Src]`.

**Comment by stephanrauh** [comment]
I've updated the docuementation on  https://www.pdfviewer.net. For some reason, the documentation `[(src)]` attribute had gone away. Thanks for pointing this out!

**Comment by blindsz** [comment]
Cool! Thanks for updating the docs :)
