### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' 

### ISSUE THREAD

**Issue by oz-shamay** [stephanrauh/ngx-extended-pdf-viewer#1581]
Hi Stephan,
I am trying to use ngx-extended-pdf-viewer V15.0.9 in my web angular 12 app but every time I open the viewer in the
chrome browser, when I am trying to show a PDF or an image, both base64 format file with the attribute [base64Src]

this error shows up:  Uncaught SyntaxError: Unexpected token '<' (at pdf-2.16.449-es5.js:1:1) 

wich pointing on this code:

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sheba</title>
  <base href="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="styles.css"></head>
<body dir="rtl">
  <app-root></app-root>
<script src="runtime-es2017.js" type="module"></script><script src="polyfills-es2017.js" type="module"></script><script src="vendor-es2017.js" type="module"></script><script src="main-es2017.js" type="module"></script></body>
</html>

Please help,
and thank you for your time,
Oz.

here is a screenshot:

![Error](https://user-images.githubusercontent.com/82337232/201061947-32df0187-6237-4285-8b52-4273fae14fd1.png)

**Comment by stephanrauh** [comment]
The error message means that the file `pdf-2.16.449-es5.js` doesn't exist. Usually, there's a 404 error message, but unfortunately, Angular routing kicks in and assumes you want to navigate to a page with a weird name.

Please check if your assets folder contains the JavaScript files needed by the PDF viewer.

It's also a bit odd that your Chrome browser tries to use legacy EcmaScript 5 code. That's for old browsers (and - to my dismay - iOS devices, because Safari adopts new features slowlier than the other browsers). So I suspect you need to add the code copying the assets folder from `node_modules/ngx-extended-pdf-viewer/assets` to your application's `asset` folder.

**Comment by stephanrauh** [comment]
I didn't hear from you for more than two weeks, so I assume you've managed to solve the issue. I'm closing the ticket now.

**Comment by MatDepInfo** [comment]
Hello, I got the same error... Files are located in asssets folder. Moreover how to tell to angular to find files into specific folder ? Like /assets/ngx-extended/ ?

**Comment by stephanrauh** [comment]
If you get the same error message, the JavaScript files are probably not there. Or maybe they are there, but ngx-extended-pdf-viewer tries to load them from a different URL. You can hunt down this kind of bugs by inspecting the network tab of your browser's developer tools and by running `ng build` to double-check where the files are.

As for your second question, you're looking for `pdfDefaultOptions.assetsFolder`, as described here: https://pdfviewer.net/extended-pdf-viewer/options

```ts
@Component({ ... })
export class DefaultOptionsComponent {
  constructor() {
    pdfDefaultOptions.assetsFolder = 'bleeding-edge';
  }
}
```

**Comment by MatDepInfo** [comment]
OK I try this: 

```
export class DetailValueFileComponent implements OnInit, OnChanges, OnDestroy {
  constructor(
      public appS: AppService,
  ) {
    pdfDefaultOptions.assetsFolder = 'front/assets/ngx-extended-pdf-viewer';
  }
```

but in network tab it tries to find op-chaining-support only in assets (see image below)
![Capture d’écran 2024-04-25 à 12 44 15](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/13313050/35d85d93-5f6e-41b2-8b32-4a6714128e73)

**Comment by MatDepInfo** [comment]
OK my bad it was the wrong component. Now it's ok for the path. But I got a new error: 
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by MatDepInfo** [comment]
OK I follow this: https://pdfviewer.net/extended-pdf-viewer/troubleshooting and it's working well. Thanks.

**Comment by stephanrauh** [comment]
I'm glad you've figured it out! This kind of bugs is always difficult for me: it's easy to hunt down if I can see the source code, but of course, the source code is on your machine, so I'm left in the dark. :)
