### ISSUE TITLE
[useBrowserLocale]="false" still adds a <link type="application/l10n" ...> element to the DOM

### ISSUE THREAD

**Issue by nicholas-ochoa** [stephanrauh/ngx-extended-pdf-viewer#1583]
**Describe the bug**
`<ngx-extended-pdf-viewer>` with `[useBrowserLocale]="false"` is still adding a `<link type="application/l10n" ...>` element to the DOM.

I'm using the inline HTML l10n objects to provide translations. With this bug, the `locale.properties` file is always referenced / used because the element is present in the DOM. Right now as a workaround I'm just removing the `<link>` element from the DOM. This allows the underlying `pdf.js` library to pick up the inline translations.

**Version info**
- 15.0.9

**Desktop (please complete the following information):**
 - Chrome 107
 
**To Reproduce**
I can provide a reproduction if necessary, but this one seems pretty simple.

**Demo PDF file**
N/A

**Screenshots**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/126299/202306868-0663168e-f6da-402f-b8a4-e5a499623085.png">

**Comment by stephanrauh** [comment]
You're right, the feature was broken. Your bugfix has landed with version 15.0.11.

Enjoy!
Stephan
