### ISSUE TITLE
Issue with Xfa layer rendering using ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by namblard-sword** [stephanrauh/ngx-extended-pdf-viewer#1585]
Hi

**Describe the bug**
A Xfa pdf file is not properly displayed, as the call to renderXfaLayer ends up in error

**Version info**
Either version 13.0.0 or 15.0.9 have the same issue

**Desktop (please complete the following information):**
Chrome - 107.0.5304.110

**To Reproduce**
Here is a pdf that fails to be displayed : 
[tva-declaration-pers-physiques-EN.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/10030147/tva-declaration-pers-physiques-EN.pdf)

If you open it using the demo example of pdfjs there is no issue at all : https://mozilla.github.io/pdf.js/web/viewer.html

When opening it in the ngx extended pdf viewer I see these errors in my browser console : 
![image](https://user-images.githubusercontent.com/78027512/202416112-15734b04-4cee-4621-9baa-1c312ab178bf.png)

It seems to me that the overriding of the getFormValue you are doing in : https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/3c4dd3e24aa608035acc134825c9907b117fc457/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L872 messes up with the function renderXfaLayer() of pdfjs.

After a bit of debbuging I see two issues : 
  1. The call is made not with the key but with field name whereas you expect the key ? 
  2. The formData in ngx-extended-pdf-viewer is not yet populated so either way the key or fieldname being the right choice, the value is undefined.
  
Please feel free to request anything you need to debug and fix that issue.

Thank you for your consideration,

Best regards

**Comment by stephanrauh** [comment]
At the moment, I'm short of time, but this sounds like a bug I ought to solve soon, so I'll put it high on my priority list.

**Comment by stephanrauh** [comment]
I've just shipped version 15.0.10 fixing your bug. I didn't check two-way binding for radiobuttons and checkboxes yet, so chances are I'm going to ship a second bugfix. In any case, your application should work with version 15.0.10.

Your PDF file is very useful because it covers a lot of use-cases. Is it protected by copyright? More to the point: Am I allowed to use it in the showcase?

**Comment by namblard-sword** [comment]
Hi,

Thanks a lot for your commitment ! 

As for your request, it seems that there is no copyright on the pdf files. As for the showcase, I'm unable to answer you, though it is a "public" document from the luxembourgish government (you still need an identification from that government to access it).

**Comment by stephanrauh** [comment]
I've created a follow-up ticket to track the remaining tasks: #1621
