### ISSUE TITLE
Using the ES5 version of the PDF viewer. error

### ISSUE THREAD

**Issue by rlucky469** [stephanrauh/ngx-extended-pdf-viewer#1588]
![b1](https://user-images.githubusercontent.com/77981064/203108324-f00f5cef-2141-4d95-a547-5b8789895b4a.png)

**Comment by stephanrauh** [comment]
Usually, this error message means you didn't copy the JavaScript files to the assets folder. In your case, it's a bit more complecated, because you're using the bleeding-edge branch. But the idea remains the same. Add these lines to your `angular.json` file:

```json
{
  "projects": {
      "<your-project>": {
        "architect": {
            ...
            "assets": [
              ...,
              // add these lines:
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets",
                "output": "/assets/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/bleeding-edge",
                "output": "/bleeding-edge/"
              },

```

**Comment by stephanrauh** [comment]
I assume this answers your question, so I'm closing this ticket now. If you're still stuck, just tell me.

**Comment by rlucky469** [comment]
Thank you @stephanrauh
