### ISSUE TITLE
PDF is not downloading on Edge/IE 11

### ISSUE THREAD

**Issue by samit2015** [stephanrauh/ngx-extended-pdf-viewer#159]
We are unable to download pdf on IE while we are able to see it on IE 11/Edge. On Download, it says Cant download and then if we retry, It hangs at Resuming status.

**Comment by stephanrauh** [comment]
Please try again with version 1.7.0. I've tried to reproduce your issue on my local test project, and it worked like charm. However, the official demo https://pdfviewer.net is broken on IE11 for some reason, so I can't be sure.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Now https://pdfviewer.net works again with Internet Explorer 11. So I've tried to reproduce your bug. The download works like charm.

I suppose there's an important info missing. So I'll close the ticket, but I'll keep listening. If you send me a reproducer, I'll happily re-open the ticket.

Best regards,
Stephan

**Comment by samit2015** [comment]
Thanks Stephan for ur quick help and reply,.

**Comment by samit2015** [comment]
Thanks for looking into this Stephan, issue is with ngx-extended-pdf-viewer.js where we define this.filenameForDownload = 'document.pdf';, if we remove the name and keep this.filenameForDownload = '';  we get file name and download correctly on Chrome BUT on IE 11, download doesnt happen...any idea ...how can we pass our custom name to download file.
