### ISSUE TITLE
Pdf viewer didn't work without internet connection

### ISSUE THREAD

**Issue by jackcoral89** [stephanrauh/ngx-extended-pdf-viewer#1596]
When I try to load pdf without internet connection get thid error: 
![image](https://user-images.githubusercontent.com/27479143/204802762-0331e95f-ccb0-41db-ae82-872054920453.png)

I need to use that without connection.

Angular version: 14.2.10
ngx-extended-pdf-viewer: 15.0.12

Thanks for support

**Comment by stephanrauh** [comment]
That's strange. I just tried it with the showcase, and it works flawlessly without WIFI. Can you check your network tab and your console, please? There should be an error message.

![grafik](https://user-images.githubusercontent.com/3045767/204888031-eec3fd79-8663-4f55-8705-91fc60c9bb08.png)

**Comment by jackcoral89** [comment]
I had tried removing connection on the chrome network tab. In that mode didn't work. Instead, removing internet by wifi, seem to work.

**Comment by stephanrauh** [comment]
Ah, that makes sense. Cutting the connection in Chrome itself means Chrome can't even access the local server. But that's probably not your scenario, because Angular needs a web server. But it doesn't need internet.

I suppose I can close the ticket now?

**Comment by jackcoral89** [comment]
Thanks anyway, cheers
