### ISSUE TITLE
on page load statile file path not loading..

### ISSUE THREAD

**Issue by sagarkakadiya735** [stephanrauh/ngx-extended-pdf-viewer#1600]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template

**Describe the bug**

**Version info**
- Version of ngx-extended-pdf-viewer

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]
 
**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug. It's always a good idea to start from a fresh, new project. There's a template project at https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template. A side effect is that writing a reproducer often helps you to find bugs of your code. This spares me the embarrassement of pointing our you bugs. More important, it saves me a lot of time. ngx-extended-pdf-viewer has become so popular that answering issues costs a lot of my spare time, so I appreciate your help.

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**

**Additional context**

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by sagarkakadiya735** [comment]
<ngx-extended-pdf-viewer *ngIf="!isCropActive" 
      [src]="path"
      [height]="'85vh'"
      [minifiedJSLibraries]="false"
      [useBrowserLocale]="false"
      [showHandToolButton]="true"
      > 
    </ngx-extended-pdf-viewer>
    
    
    
    
    in ts file 
    
     value = '../../../assets/GS.pdf';
     
     when file load show the message like this
     
     
![image](https://user-images.githubusercontent.com/78949681/204978025-cc4506d9-0d0d-4e1f-9e22-7d148f9d3191.png)
![Screenshot_4](https://user-images.githubusercontent.com/78949681/204978139-9c7006fe-73e1-4c1c-8019-0ee5c1409030.png)
![Screenshot_4](https://user-images.githubusercontent.com/78949681/204978188-416c2496-1b41-4dc2-8ef7-c81102a8ed9b.png)

**Comment by stephanrauh** [comment]
The error message (according to the email) says "failed to fetch". Usually, this means the file isn't there. Please have a look at your console and your network tab. Are there any error messages? You can also deactivate the Internet Download Manager. Maybe it interferes with the PDF viewer.

**Comment by sagarkakadiya735** [comment]
<ngx-extended-pdf-viewer 
      [src]="value"
      [useBrowserLocale]="true"
      [height]="'85vh'"
      [minifiedJSLibraries]="false"
      [useBrowserLocale]="false"
      [(page)]="page"
      [showHandToolButton]="true"
      > 
    </ngx-extended-pdf-viewer>
    
    
    
    In ts file
    
    value = 'C:\\fakepath\\GS.pdf';

    I have set the my window url Path how can i get it.

    
    second error how can i get the page no. i am on which page.

**Comment by stephanrauh** [comment]
1. `C:\\fakepath\\` is a placeholder added by the PDF viewer if you open a file via drag and drop. It's not a path you can use. In fact, you can't access files on your file system at all. That's a limitation of the browser, and it's there for a good reason. Otherwise hackers could prepare a website reading your entire hard disk. However, any URL provided by a web server (or `ng serve`) should do the trick, such as `value = `http://localhost/realpath/GS.pdf`. 
2. You're already on the right track. `(page)` always tells you which page is currently visible.

**Comment by stephanrauh** [comment]
I'm closing the ticket now. If you're still stuck, feel free to add comments to this tickets. I'm still listening.

Best regards,
Stephan
