### ISSUE TITLE
NgxExtendedPdfViewerService.findMultiple() and the corresponding UI feature are broken

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1607]
Currently, it's you can't search for multiple multi-word phrases. It seems the feature is a victim of a difficult merge conflict.

The bug has been reported by @victorDECLAU with much more detail in #1602.

**Comment by stephanrauh** [comment]
The bugfix has landed with version 15.1.1.

**Comment by victorDECLAU** [comment]
Thank you very much for your commitment to solve this bug quickly @stephanrauh ! I'm thrilled my feature now behave as wished on the latest version your library :)
Best regards.
