### ISSUE TITLE
Issue with zoom dropdown values for French language

### ISSUE THREAD

**Issue by smp65akh** [stephanrauh/ngx-extended-pdf-viewer#1608]
Hi,

I have an angular 13 application which is using ngx-extended-pdf-viewer version 15.0.7. Upon using French language in the application, the zoom dropdown values are displaying with a white space. This happens only with French language and it displays properly for other languages. Attaching screenshots below. Kindly have a look at this issue.

Dropdown with French language:
![image](https://user-images.githubusercontent.com/119669845/205341247-1c6be49b-d1c2-4a9e-8c40-5604fdff443a.png)

Dropdown with English language:
![image](https://user-images.githubusercontent.com/119669845/205341594-b5c516b5-fc58-4dbc-96ad-9ec7c9cb5a1f.png)

**Comment by smp65akh** [comment]
Hi @stephanrauh,

Thanks for the reply. I tried updating the page_scale_percent={{scale}} % in the viewer.properties file inside the assets/i18n/locale/fr folder in my application. But still facing the same issue. Could you please suggest whether anything else needs to be done from my application to resolve this?

**Comment by stephanrauh** [comment]
I've added the documentation of your nice workaround in the showcase. I think many developers want to modify the translation files, so thanks a lot for providing the idea!

Best regards,
Stephan
