### ISSUE TITLE
Ctrl+P doesn't prepare document for printing before sending it to Print Preview

### ISSUE THREAD

**Issue by adalbero** [stephanrauh/ngx-extended-pdf-viewer#1609]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html?
NO
- Does the bug also happen on https://pdfviewer.net/simple
YES

**Describe the bug**
PDF Viewer doesn't prepare document for printing when we press Ctrl+P.

**Version info**
- ngx-extended-pdf-viewer: 15.2.0
- pdf.js: 2.16.451

**Desktop (please complete the following information):**
 - tested on Edge & Chrome
 
**Smartphone (please complete the following information):**
 - not tested

**To Reproduce**
1. Open any document on PDF Viewer
2. Press Ctrl+P
3. Verify that the document is not prepared for printing and a blank document comes on Print Preview

**Demo PDF file**
- any PDF document

**Screenshots**
PDF Viewer Showcase
![image](https://user-images.githubusercontent.com/9035622/205622098-c8f55668-839d-4ca5-a85e-1cbbe93f2e87.png)

Mozilla Showcase
![image](https://user-images.githubusercontent.com/9035622/205622251-6386c854-7f2a-4548-9948-38b453d668bf.png)

**Additional context**
Disabling Ctrl+P would be a solution, but I tried to add a listener to Ctrl+P and abort it, but it never gets to my handler. It is captured by viewer which calls window.print (without preparing the document for printing) and stop event propagation.

**Comment by stephanrauh** [comment]
While I'm not sure it's OK to highjack the functionality of `window.print()`, I have to admit the current behavior is wrong, too. I suppose I can replace `window.print()` by the custom print funtion when the PDF viewer is visible and restore the original behavior in an `ngOnDestroy()` method.

Maybe it's also a good idea to add an option allowing users to keep the original `window.print()`. If so, I ought to add some CSS rules because printing an empty window is wrong, too.

**Comment by stephanrauh** [comment]
I've implemented a prototype. It seems to work. If the feature survives my tests, I'm going to add the attribute `[replaceBrowserPrint]`. As long as I'm maintaing version 15.x.x, the default value is false. Version 16.0.0 allows me to introduce a breaking change, so I'm going to activate the feature by default.

**Comment by stephanrauh** [comment]
The new attribute is going to ship with version 15.2.1 soon.
