### ISSUE TITLE
Page turn effect

### ISSUE THREAD

**Issue by jmpeltier** [stephanrauh/ngx-extended-pdf-viewer#161]
It would be nice to add a page turn effect as you page through a document.  In order to do this, it might make sense to also limit the number of pages to be shown to 2.  It would create more of a book or magazine experience.

Example:  https://flowpaper.com/flipbook-software/

**Comment by stephanrauh** [comment]
I'd love to do so! However, I don't have a clue how to do it. I'm pretty sure the idea is well beyond the scope of the original pdf.js project, so I hardly dare to ask @Snuffleupagus, @timvandermeij, and the rest of the team to chime in. However, since I've just done that: guys, what' your opinion?

**Comment by stephanrauh** [comment]
Basically, that's two questions:

- Is it possible to modify pdf.js in such a way it supports page-turn effect?
  (I'm almost sure the answer is a clear "yes", and I'm 90% sure I'm up to the task).
- Can we add the feature to pdf.js without destroying the core features?

Bonus question: just imagining I'd manage to implement that feauture, would you, @timvandermeij and @Snuffleupagus, accept my pull request?

**Comment by timvandermeij** [comment]
This is not something we would consider for the general PDF.js viewer since it only applies to a very specific use case. However, at https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications there are some project that forked PDF.js and implemented this feature; see https://github.com/RaffaeleMorganti/pdf-viewer for example.

**Comment by stephanrauh** [comment]
@timvandermeij Thanks! I'm surprise someone has managed to do this, while keeping the rest of the functionality. Awesome!

BTW, may I kindly ask you to include ngx-extended-pdf-viewer to your gallery? It's a Angular integration that's recently becoming surprisingly popular.

**Comment by timvandermeij** [comment]
Done! It's always nice for us to see PDF.js being used in all kinds of cool projects.

**Comment by stephanrauh** [comment]
I'm putting this aside for a while. I've managed to implement a book mode, but currently, it's bug-ridden and slow. I plan to start fresh later.

**Comment by stephanrauh** [comment]
I'm closing the ticket for the moment. Nonetheless, I'll keep it in mind. I like the idea.
