### ISSUE TITLE
Unable to open pdf file Error:TypeError: key.split(...).at is not a function at new KeyboardManager

### ISSUE THREAD

**Issue by sattasundar** [stephanrauh/ngx-extended-pdf-viewer#1610]
I am using ngx-extended-pdf-viewer in my Ionic-Angular project. And It's working fine in Android 10 emulator, but unable to load in Android 12 emulator because coming below error in console Here is the code below;

`     <ngx-extended-pdf-viewer
          [src]="'assets/OPDNewPatientReport.pdf'"
          [useBrowserLocale]="true"
         ></ngx-extended-pdf-viewer>
`

**Version info**
- Version of ngx-extended-pdf-viewer : 15.2.0
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
 
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Android 12 Emulator

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/62828724/205940331-b687ce29-a409-4079-89b8-2e05f14ba588.png)

**Comment by stephanrauh** [comment]
@Calixteman This might be a topic for you. Are you aware of any Android-specific errors when pdf.js calls `key.split()`? I'm not 100% sure, but this seems to be the offending line:

https://github.com/mozilla/pdf.js/blob/ba2fec98913589b7a6ae16ea62b213e9a432e456/src/display/editor/tools.js#L224

**Comment by calixteman** [comment]
It's weird: it's for internal stuff only.
It's used here:
https://github.com/mozilla/pdf.js/blob/ba2fec98913589b7a6ae16ea62b213e9a432e456/src/display/editor/tools.js#L399-L422
and
https://github.com/mozilla/pdf.js/blob/ba2fec98913589b7a6ae16ea62b213e9a432e456/src/display/editor/freetext.js#L61-L66

So I'd say that there is likely something wrong on how the bundler handles the static initialization.

**Comment by stephanrauh** [comment]
Thanks a lot for your fast response! "Internal stuff" means that it shouldn't be in the generic build?

**Comment by calixteman** [comment]
No, no it should be.
By "internal stuff", I meant not accessible in any way by the user.
Above you've the two call sites so you can see that split should always exist except maybe in a context I don't know.

**Comment by stephanrauh** [comment]
OK. At the moment, I'm clueless, but then, that's the beauty of software development: you're always confronted with challenges.

@sattasundar I don't have an Android emulator, so I need your help. At the moment, I've got two ideas:

- Please examine what's the difference between Android 10 and 12. My theory: ngx-extended-pdf-viewer on Android 10 loads the ES5 build of pdf.js. Can you confirm that? You can see this in the network tab of your browser's developer tools.
- Set a breakpoint at the line raising the exception. What's the datatype of the variable `key`? Reading the source code and the insight of Calixteman, I assume it should be a string. Can you confirm or falsify that?

**Comment by digaus** [comment]
@stephanrauh 

For me both load same `pdf-2.16.443.min.js` file but on android it fails.

The issue is not the `.split` it is the `.at` after the split

**Comment by stephanrauh** [comment]
@digaus All right, that's a new and valuable insight!

CanIUse.com claims that 90% of all users are using a browser supporting the `at()` function, so maybe I should simply add `at()` to the compatibility checks. Using the ES5 fallback solution may seem painful, but if it works well, too.

**Comment by digaus** [comment]
Or include an at polyfill 🙃

**Comment by stephanrauh** [comment]
Yeah, that was my first idea. But then I saw how many polyfills core.js contains, and my optimism was gone. I can add a polyfill with the next alpha version, so you can run a test. I'm afraid we're opening Pandora's box: there's always a missing polyfill when the Mozilla team adds new code.

Another option is to tweak the build script. However, I always have a hard time wrapping my head around it. As far as I can see, the toggle `SKIP_BABEL` switches off Babel and its polyfill completely, but I'm not sure. There's an array called `ENV_TARGETS`, so I could reduce the minimum Chrome version to 71, but I'm not sure it's used at all. Are you more familiar with Gulp than I am?

https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/gulpfile.js

**Comment by lixaotec** [comment]
+1

same error on Angular 15
just made a simple test app with it and got straight to this error.. 

how to workaround?

**Comment by lixaotec** [comment]
In fact I dist found out that the cause was the outdated Chrome.  v88
in newer it works..

Is there any way to tell pdfjs check compatibility?

**Comment by stephanrauh** [comment]
Starting with verion 16.0.0-alpha.4, the browser switch also checks for `string.at()`. If it's not available, the old ES5 code is used.

**Comment by digaus** [comment]
> Starting with verion 16.0.0-alpha.4, the browser switch also checks for `string.at()`. If it's not available, the old ES5 code is used.
Now I am getting this error :)
![popup error](https://user-images.githubusercontent.com/15358538/221895879-d2aace55-0003-4588-a7ce-dafe84bf9088.PNG)

**Comment by stephanrauh** [comment]
Like so? 
<img width="1989" alt="grafik" src="https://user-images.githubusercontent.com/3045767/221970413-d946dca2-c285-47e3-9b16-387dcc38f247.png">

If your application shows but your annoyed about the error message, I'm afraid I can do little about it. I don't know how to suppress the message.

**Comment by stephanrauh** [comment]
If your application doesn't show at all, I invite you to investigate the topic yourself. I don't have an old browser on my computer. All I can do is using Browserstack. That's a tremendous tool, but it's also cumbersome when it comes to debugging. You're probably better off.

All you need to do is to modify the file `node_modules/ngx-extended-pdf-viewer/assets/op-chaining-support.js`. Next time you build the application, your modified copy of `op-chaining-support.js` is used. `npm install` or `npm ci` should revert your changes.

If you find a way to test browser support without the ugly messages, I'll happily accept your improvement!
