### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by kemsky** [stephanrauh/ngx-extended-pdf-viewer#1611]
Hi @stephanrauh

Occasionally we receive crash reports that look like this:

```js
TypeError: Cannot read properties of null (reading 'parentNode')
  at webViewerWheel(/assets/pdf-viewer/viewer-2.16.451.min.js:44:61771)
```

We use `ngx-extended-pdf-viewer` in a popup and this error appears right after popup is closed. 

Most probably it happens because some listeners are not yet removed while html node is already destroyed.

We tried the following hack in close event handler:

```ts
    protected close(result?: void) {
        // wait for scripts to load
        if (!this.componentInitialized && this.pdfSrc != null) {
            this.warn('PDF engine is not initialized yet');
            return;
        }

        // unbind offending event listeners
        const application = (window as any).PDFViewerApplication;
        const unbindWindowEvents = application?.unbindWindowEvents?.bind(application);
        if (typeof unbindWindowEvents === 'function') {
            unbindWindowEvents();
        } else {
            this.warn('unbindWindowEvents failed');
        }

        super.close(result);
    }
```
but crash report contains log entry `unbindWindowEvents failed`, it means that viewer is in some intermediate state when `PDFViewerApplication` is null but it is running. 

It is minor issue but we would like to know what are possible options to avoid this error?

**Version info**
- Version of ngx-extended-pdf-viewer 15.2.0

**Desktop (please complete the following information):**
 - Browser Chrome 108.0.0

**Comment by stephanrauh** [comment]
Sorry for responding late. I was convinced I already asked your question, but somehow it slipped my attention.

IMHO, your "hack" is clever. It's pretty much what I'd do. As you report, it's still not enough, so it seem to be my job to investigate the topic more closely. Your hint that the listeners are removed too late sounds like a hot trace.

**Comment by kemsky** [comment]
@stephanrauh, meanwhile I've added more logging to see what happens and modified the code to capture `PDFViewerApplication` instance early when `pdfLoadingStarts` event fires.

**Comment by stephanrauh** [comment]
What does your modification do? Does it solve the problem?

**Comment by kemsky** [comment]
@stephanrauh, the idea is to capture application instance in `pdfLoadingStarts` callback:

```html
    <ngx-extended-pdf-viewer
            [src]="pdfSrc"
            [showBorders]="true"
            [useBrowserLocale]="true"
            [showOpenFileButton]="false"
            [showBookmarkButton]="false"
            [zoom]="100"
            (pdfLoadingFailed)="onError($event)"
            (pdfLoadingStarts)="onReady()"
            class="flex-block"
    >
    </ngx-extended-pdf-viewer>
```

```ts
    public onReady(): void {
        this.componentInitialized = true;
        this.application = (window as any).PDFViewerApplication;
        this.info('PDF loading starts', this.application != null);
    }

    protected close(result?: void) {
        // wait for scripts to load
        if (!this.componentInitialized && this.pdfSrc != null) {
            this.warn('PDF engine is not initialized yet');
            return;
        }

        // unbind offending event listeners
        const unbindWindowEvents = this.application?.unbindWindowEvents?.bind(this.application);
        if (unbindWindowEvents === 'function') {
            unbindWindowEvents();
        } else {
            this.warn('unbindWindowEvents failed');
        }

        super.close(result);
    }
```

I have to wait a week or so, this error is not very frequent.

**Comment by stephanrauh** [comment]
Ah, that makes sense. I went to great lengths to unsubscribe the event listeners, but I can only do it in the `ngOnDestroy()` method, and who knows when this is called. Countless error reports indicate it's called too late. Your workaround is clever! I'm looking forward to your next report.

You don't need to capture the instance of PdfViewerApplication. It's a singleton. That's very annoying because it's difficult to display two PDF viewers simultaneously, but the ugly truth is that the PDF viewer pollutes the global namespace, so there's nothing I can do about it.

On the plus side, it's completely OK to simply use `(window as any).PDFViewerApplication`. I'm afraid it's never removed from memory, not even after removing `<ngx-extended-pdf-viewer>` from the DOM tree.

**Comment by stephanrauh** [comment]
I'm assigning the "partially solved" label to this ticket, because I hope your idea works. If so, I'm going to make the unbinding an official API of the viewer.

**Comment by kemsky** [comment]
@stephanrauh it does work, I made obvious mistake in condition (`typeof` was missing), but now when error is corrected, everything works as expected. Since PDFViewerApplication is singleton, the correct fix in the library itself may be too convoluted so I'm not sure if it is worth it.

**Comment by stephanrauh** [comment]
Exposing a method allowing you to unbind the event listeners isn't that much work, so it might be worth it. To be honest, documenting the feature is more work than implementing it. I wonder if I should add a page dedicated to popups to the showcase.

**Comment by stephanrauh** [comment]
Well... I've exposed an unbinding method a long time ago. You can simply use `NgxExtendedPdfViewerComponent.ngOnDestroy()`. I've added a demo showing the idea to the showcase.
