### ISSUE TITLE
Add latest features to the SSR components

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1622]
A couple of features of the library didn't make it into the server side rendering component yet:
- window.print() (as reported by @exavior75)
- the new listener attributes
- to be continued

**Comment by exavior75** [comment]
Thanks! Deployed updates to our site (www.ournevadajudges.com) in the meantime using the prior version. Here's an example of your awesome library in action: https://www.ournevadajudges.com/judges/linda-marie-bell/cases?state=%7B%22show%22:%2250529-84697.pdf%22%7D Thanks Stephen!

**Comment by stephanrauh** [comment]
Awesome! I believe your site is a nice addition to the gallery I'm planning (see https://github.com/stephanrauh/ngx-extended-pdf-viewer/discussions/780). I just wonder why someone would want to rate a judge, and whether it's a good or even legal thing to do so. But I guess things are a bit different in the USA. Are you electing your judges in a public voting?

**Comment by stephanrauh** [comment]
Another question: I faintly remember you talked about a pull request (or was it someone else? I'm not sure). I just don't see any pull request, apart from the usual dependabot PRs. Did you forget to push it?

**Comment by AlexanderFalconi** [comment]
I would answer your rate-a-judge question but I don't need to, because our website doesn't track this information. If you're seeing judicial review and that is confusing you, it is occurring by our Supreme Court and disciplinary bodies. These are official government actions. If a judge makes a mistake, the Supreme Court corrects it by admonishing the judge and sending them instructions to correct the error. Yes, in Nevada, our judges are elected publicly.

**Comment by AlexanderFalconi** [comment]
I didn't create a pull request, but next time I will.

**Comment by stephanrauh** [comment]
That's interesting! It's always interesting to learn the ways of a foreign culture, and it's a surprising privilege that maintaining an open-source project turns out to provide plenty of opportunities for that. Come to think of it, our judical reviews probably work in a similar way, it's just something most of us never hear or think about.

**Comment by AlexanderFalconi** [comment]
Indeed, I've been sharing this with a lot of organizations to show appreciation for how your work impacts public service. You can also check out some videos of the judges actually coming to our private studio! https://youtu.be/gpPVgggGOCg And here's an example of our Supreme Court acknowledging our work: https://www.ournevadajudges.com/assets/docs/documents/35-order-granting-media-request.pdf I'm a software engineer and I think its important for us to find ways to serve the public with our talents, and I like to share this with other engineers.

**Comment by stephanrauh** [comment]
You've sort of summarized what's driving open-source developers like me. Your website probably isn't open-source, but you make it sound like a similar motivation. One day or another, I'm writing an article about that. That's a project I promised to a magazine editor years ago. In the meantime, he's left the company, but the idea is still there. :)

**Comment by AlexanderFalconi** [comment]
I have to keep this project private because of efforts by undermining factions who do not benefit from the public learning of how the judiciary operates. We have 3 lawyers, including 2 of which are with the American Civil Liberties Union. You can learn more about the ACLU's backing here: https://www.youtube.com/watch?v=6MAgYSVF1Ww It's disappointing to have to deal with this political aspect of our work but it is to be expected. You can also learn about our media support here: https://www.reviewjournal.com/opinion/editorials/editorial-new-family-court-rule-is-an-affront-to-justice-2606110/ and finally, you can learn about the Legal Aid Coalition's backing of us here: https://www.ournevadajudges.com/assets/docs/documents/359-brief-of-amici-curiae.pdf For these several reasons, I have to keep the project private, at least for now.

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 15.2.2. At the moment, I don't have a SSR project at hand. Would you mind to run a quick check and tell me whether the bug is gone?

Thanks in advance,
Stephan

**Comment by AlexanderFalconi** [comment]
I ran a quick check and, oddly enough, it compiles successfully but is
still finding a window reference at run time. I first thought maybe it's
something on my end, but when I revert to 15.1.~ it works fine, so it has
to be something within the library. I don't even have a hunch with this
one, since the stack trace purports the issue to be a reference to a css
file (totally mystified on that).

ReferenceError: window is not defined
    at Module.5531 (../src/oxxj/css/index.css:3:1)
    at null.__webpack_require__ (../src/oxxj/css/index.css:3:1)

**Comment by stephanrauh** [comment]
Yeah, this rings a bell. It's been a while since I solved the last SSR bug, but I remember it was something to do with the non-existing window reference. The general wisdom is to use `globalThis` instead of `window`, but I'm not sure that's the correct solution in this particular case.

**Comment by stephanrauh** [comment]
My article on the topic: https://www.beyondjava.net/detecting-service-worker

**Comment by stephanrauh** [comment]
Testing `!!globalThis['print']` probably does the trick. It should be false in SSR environment and true in a browser, unless someone assigns `undefined` to `window.print` - but that sounds like a pathological case, anyways.

**Comment by AlexanderFalconi** [comment]
I'll review your article. SSR can be so pesky.

**Comment by stephanrauh** [comment]
@AlexanderFalconi Is your topic still open?

**Comment by AlexanderFalconi** [comment]
I'll try your latest version again this evening. By the way, a few days ago
the Supreme Court is hearing arguments on the website (specifically First
Amendment access). It's going to be streamed live. It's rare to get a
Supreme Court to order oral arguments in a case. All 7 Justices will be
fielding questions to government and ACLU lawyers.
https://www.ournevadajudges.com/assets/docs/documents/407-order-scheduling-oral-argument.pdf

**Comment by stephanrauh** [comment]
I have a hard time to understand because I'm missing some context (not to mention the judical language - I'm not a native speaker of English). I doesn't read like somebody has sued you. Have you started a petition, and now they want to talk about it with you in person?

**Comment by stephanrauh** [comment]
BTW, I've released version 16.0.0 a few minutes ago. I believe it's a major improvement over version 15.

**Comment by AlexanderFalconi** [comment]
Yes, I used the website to teach the public about the courts, one of the
Districts tried to put a stop to it, I brought it to the Supreme Court's
attention with the help of American Civil Liberties Union lawyers, and they
want to discuss it in person, before the public in their courtroom, which
will be broadcast live. The lawyers of the ACLU will be speaking with them
on my behalf. The government is sending 2 lawyers which will be expected to
explain why they have done what they have done. If the Supreme Court
rejects the government's position, it will cause a shockwave of change
throughout the state and encourage other organizations like mine to teach
the public.

I'm excited to try out 16. I'm hoping that one day I won't have to keep
sending up a big chunk of folders from node_modules as well, this library
is the only one where I have to do that.

**Comment by stephanrauh** [comment]
Good luck! You convinced me that your website is for the public benefit, so I don't want it to go away. 

From a German point of view, it sounds a bit odd because we value data protection highly, but then, we don't vote our judges. Our politicians enjoy very little privacy, so I guess that's the better comparison.

**Comment by stephanrauh** [comment]
As for sending a big chunk of folders: what's really important (from the user's point of view) is how much data is transferred to their device. That's a lot, but gzip or Brotli reduce the penalty to roughly half a megabyte. If you want to reduce the size of the installation: you can fine-tune what you copy to your assets folder. For instance, you probably don't need all the i18n files. I just tell people to copy them because that's the easiest way to get started.

**Comment by AlexanderFalconi** [comment]
It looks like 16 still breaks with SSR. It gives some kind of nebulous
error regarding the first css file it tries to load. I reverted to 15.1.1
and everything works.

**Comment by stephanrauh** [comment]
@AlexanderFalconi Finally, I've managed to address your issue. I'm not entirely sure because the error I've fixed has nothing to do with CSS, but I'm positive version 16.2.1 knows how to do server-side rendering again.

I also plan to migrate the showcase (and later, my blog) to SSR. [This blog article](https://levelup.gitconnected.com/prerender-angular-and-deploy-it-as-a-static-website-on-aws-s3-to-make-it-42-times-faster-115fadcf8614) indicates I don't need a real server to do SSR. I always suspected pre-rendering does the trick, but until now, I wasn't able to figure out how to do it. I hope it works because buying an AWS EC2 instance is too expensive for a hobbyist open-source project!

Be that as it may, the point I want to bring home is that if everything works according to the plan, problems with server-side rendering are going to be a thing of the past because SSR is a first-class citizen in ngx-extended-pdf-viewer country.

**Comment by AlexanderFalconi** [comment]
Whatever you did, worked! It took me a while to get back because of this:
https://www.reviewjournal.com/news/politics-and-government/nevada/supreme-court-weighs-arguments-challenging-closure-of-family-court-hearings-2737941/

And this: https://www.youtube.com/watch?v=4AbZmTCmuNI

**Comment by stephanrauh** [comment]
Interesting links. Thanks for sharing!

As for ngx-extended-pdf-viewer: I'm happy to learn my library knows about SSR again. I'm trying to convert the showcase to server-side rendering, but that turned out to be difficult. As a first step, I've tried and manage to convert my blog to SSR. As things go, there are a couple of pages I forgot - especially those pages using the PDF viewer.

Be that as it may, I hope to succeed sooner or later. When I do, SSR problems are a thing of the past. Basically, that's one of the reasons for creating the showcase: it's great for testing.

**Comment by stephanrauh** [comment]
May I close this ticket now?

**Comment by AlexanderFalconi** [comment]
Sure!

**Comment by stephanrauh** [comment]
@AlexanderFalconi Currently, I'm activating SSR on my blog. It shows a couple of presentations displayed by ngx-extended-pdf-viewer. You've got more experience with SSR than I have. I wonder if it's better to simply hide the component or too send the HTML even though the CSS is missing. What's your opinion?

The initial reponse of the server renders like so:
<img width="701" alt="grafik" src="https://user-images.githubusercontent.com/3045767/226137982-5c53a5ce-9757-4517-83bf-2c6b2b15a425.png">

Not exactly easy to the eye, but on the plus side, it gives Google a lot of insight into what the page does.

The client-side rendering looks a bit nicer:
<img width="1353" alt="grafik" src="https://user-images.githubusercontent.com/3045767/226138048-3d30518b-d71e-4bbf-97b4-b247ee0e5d02.png">

**Comment by stephanrauh** [comment]
It doesn't work yet - there's a problem with injecting the CSS theme. Stay tuned!
