### ISSUE TITLE
Issue with "Current page only" filter in Search

### ISSUE THREAD

**Issue by smp65akh** [stephanrauh/ngx-extended-pdf-viewer#1624]
Hi @stephanrauh,

I am using ngx-extended-pdf-viewer in my angular 13 application. I am facing an issue while doing search with "Current page only" filter. "Phrase not found" message is not displaying if we search with any keyword which is not present in document with "Current page only" filter. The message displays when we do search with any other filters or without filters. Attaching screenshots below. Kindly have a look at this issue.

With Current Page filter:
![image](https://user-images.githubusercontent.com/119669845/207305670-425c767b-63fd-41ff-9614-ff6c2cd6da6e.png)

Without current page filter:
![image](https://user-images.githubusercontent.com/119669845/207305820-f8af9de0-8cab-4aac-a7e8-a226f870f343.png)

**Comment by smp65akh** [comment]
Hi @stephanrauh, Is there any update regarding this issue?

**Comment by stephanrauh** [comment]
Not yet. The days before Christmas are always so busy. Plus, I'd like to update to the latest version of pdf.js first, because I'm badly behind schedule, and I hate it when merge conflicts pile up.

**Comment by stephanrauh** [comment]
Oops, I just see that I didn't answer you three days ago. That's strange, because I remember I thought about the answer. It shows I'm busy! :( So here's my belated answer:

I'm slightly confused about your topic because I solved a similar topic recently. But I've managed to reproduce your bug, so I have to have a look at it. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
That was a difficult hunt! Your bugfix is going to land with version 16.0.0-alpha.5 soon.

**Comment by smp65akh** [comment]
Thanks @stephanrauh
