### ISSUE TITLE
outlineLoaded event never fires

### ISSUE THREAD

**Issue by cbrianball** [stephanrauh/ngx-extended-pdf-viewer#1626]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template

**Describe the bug**
When using `ngx-extended-pdf-viewer` and subscribing to the outlineLoaded event, the handler is never invoked.
The issue is that there is a typo in the event name the component listens to on the bus. It's listening to `outlineLoaded` on the event bus instead of `outlineloaded` (note the casing on the last L)
Here's the line in the source code causing the bug:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1538

I apologize for not submitting a PR, but I have not done so to this project and figuring out what all is required for a 1 character change would take too much time. I do really appreciate all the hard work that has gone into this library!

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by stephanrauh** [comment]
Oh no! I remember the capitalization typo. Did I really do it twive, but fix it only once? Sorry about that!

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 15.2.2.

Enjoy,
Stephan

**Comment by cbrianball** [comment]
Thanks for the quick turnaround! Confirmed that the `outlineLoaded` event is now firing.
