### ISSUE TITLE
issue with angular 8

### ISSUE THREAD

**Issue by jm06487** [stephanrauh/ngx-extended-pdf-viewer#163]
Uncaught TypeError: Cannot set property 'pdfjsLib' of undefined
    at webpackUniversalModuleDefinition (pdf.js:31)
    at pdf.js:32
webpackUniversalModuleDefinition @ pdf.js:31
(anonymous) @ pdf.js:32

**Comment by stephanrauh** [comment]
That's not much information to work with. However, the "line 31" message indicates your project setup is wrong. Check your `angular.json` and your `assets` folder. Compare it to https://github.com/stephanrauh/ngx-extended-pdf-viewer and/or the installation description.

Best regards,
Stephan
