### ISSUE TITLE
Print contact sheet, image breaking issue in latest chrome

### ISSUE THREAD

**Issue by psrivash** [stephanrauh/ngx-extended-pdf-viewer#1632]
Hello There!

We've been having an issue with the PDF Viewer displaying extra blank pages in Chromethe print preview. But it seems to work fine using Firefox, safari.
They don't seem to be image break down in single page.

Version info
chrome latest version

**Desktop **
Print Preview displays correctly in safari 
To Reproduce
I've attached a copy of a 2 page PDF that I've been using to test.
In Chrome, print preview is displaying image break down, for a first page in the preview.
<img width="1025" alt="Screenshot 2022-12-19 at 2 48 12 PM" src="https://user-images.githubusercontent.com/75964935/208391324-2d27e203-844c-44c6-9305-08efe68bc597.png">

<img width="1025" alt="Screenshot 2022-12-19 at 2 48 21 PM" src="https://user-images.githubusercontent.com/75964935/208391381-9b387685-9363-48be-8905-47a78d1bd54d.png">

<img width="1025" alt="Screenshot 2022-12-19 at 2 49 15 PM" src="https://user-images.githubusercontent.com/75964935/208391411-07c6f3be-9386-4d25-9397-d4f3ce339285.png">

Thank you and grateful if anyone helps.

**Comment by stephanrauh** [comment]
It seems you've forgotten to attach the PDF file.

**Comment by stephanrauh** [comment]
Does the extra page show on the showcase? If it doesn't, the problem is almost certainly your CSS code. I've collected a couple of hints how to solve the issue here: https://pdfviewer.net/extended-pdf-viewer/troubleshooting (and scroll down to "Trouble with printing" and the three following sections).

**Comment by psrivash** [comment]
Hi, yah issue was in CSS code. So, after giving the 'page-break-inside: avoid;' in the parent div class its working. Thank you.
