### ISSUE TITLE
Issue with hyper links pointing to local path

### ISSUE THREAD

**Issue by smp65akh** [stephanrauh/ngx-extended-pdf-viewer#1633]
Hi @stephanrauh ,

I am using ngx-extended-pdf-viewer in my angular 13 application and facing an issue with the links in PDF file. There are some internal links (local network) available in the PDF documents and which are not supported by the library. I have done some debugging to check this in detail and also tried some work around to read the urls in PDF and update it to absolute path before rendering the document to make it work within the library. I tried using the pageRendered event to manipulate the links as suggested by the showcase documentation, but I was unable to get the urls or anchor tag details in the linkAnnotations there. We have data-annotation-id but there is no associated data-element-id for that annotation. This happens only for the local paths, and we will be able to see anchor tag details for external/https urls. Attaching screenshots of both scenarios below. So could you please confirm whether it is possible to add local paths (like file://xyz/a/b/c) also as an anchor to linkAnnotations? or is there any other work arounds can be done to resolve this issue?

With url pointing to local folder:

![image](https://user-images.githubusercontent.com/119669845/208494725-4551e77b-dc20-4f1e-80a7-0df6286b6a94.png)

With https Url:
![image](https://user-images.githubusercontent.com/119669845/208494839-58a9da56-5bc6-462f-8e49-8ee57af3463a.png)

**Comment by stephanrauh** [comment]
What happens if you open the file in the showcase of Mozilla? https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by smp65akh** [comment]
It is not working there also. Attaching the PDF file for your reference.
[sample (4) (1) (1).pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/10262251/sample.4.1.1.pdf)

**Comment by stephanrauh** [comment]
@timvandermeij Just a short question: are local links supposed to work with pdf.js? It seems the document above is rendered by pdf.js, but without the actual hyperlink. In this particular case, it points to `test/sample/url` (without any protocol). I've edited the PDF, so the link points to `file:://test/sample/url`, but pdf.js still renders an empty `linkAnnotation`.

**Comment by timvandermeij** [comment]
The file protocol is deliberately disabled for rendering due to security concerns. See for example https://github.com/mozilla/pdf.js/blob/1f082d3e1de0beb514087f6d241eda9ca9646e4a/src/shared/util.js#L443-L458 and https://github.com/mozilla/pdf.js/issues/12415#issuecomment-698865176.

**Comment by stephanrauh** [comment]
Thanks, Tim!

Happy New Year
Stephan

**Comment by smp65akh** [comment]
Hi @stephanrauh, 

I am using PDFs with local paths/relative paths in my application and which is now become a blocker for me as pdf.js doesn't support local paths. Could you please suggest any work arounds to resolve this issue if possible? Thanks in advance.

**Comment by w00tazn** [comment]
Was looking into something similar and found this issue... on the core pdf.js github there was a related issue referenced here https://github.com/mozilla/pdf.js/issues/10427 that documents a workaround that allows you to set "docBaseUrl" when calling the getDocument method on the library that will allow relative links to work.  

Could this be a potential fix to this issue?

**Comment by stephanrauh** [comment]
I'm not sure. I don't think so. `docBaseUrl` is great to support relative links, but the question was about accessing local files.

While I'm writing this, I wonder if you can serve the local files using your server. Angular needs a server, so chances are you can add some additional logic to the server allowing it to serve local files. Of course, you need a proper URL instead of `"file://C://some/file.pdf"`. Does this sound like a possible solution?

**Comment by smp65akh** [comment]
Thanks @stephanrauh for the suggestions. I was looking in to the docBaseUrl solution. Is there a way we can set it from ngx-extended-pdf-viewer? The **pdfDefaultOptions** doesn't support docBaseUrl and I am unable to call the getDocument method as well. Do you have any suggestions on this?

**Comment by stephanrauh** [comment]
OK, you're up to something. I've documented pdfDefaultOptions.docBaseUrl (albeit sloppily), but it seems I've forgotten to formally add this option. Try to set it, anyways. A brute force approach like this should do the trick:
```typescript
(pdfDefaultOptions as any).docBaseUrl="http://example.com";
```

I didn't try it, but I believe this approach works because I've found this comment in the api.js file:
```
* @property {string} [docBaseUrl] - The base URL of the document, used when
 *   attempting to recover valid absolute URLs for annotations, and outline
 *   items, that (incorrectly) only specify relative URLs.
```

Please keep me in the loop, so I can update the documentation and the type definition if it works.

**Comment by smp65akh** [comment]
Hi @stephanrauh, yes it worked. I am able to set the docBaseUrl with the suggested approach and relative links are now clickable in PDF viewer. Thank you so much.

**Comment by stephanrauh** [comment]
Awesome! I've opened a new ticket to track the missing bits.
