### ISSUE TITLE
ngx-extended-pdf-viewer cors issue for opening pdf url from server 

### ISSUE THREAD

**Issue by durgamalleswariyeruva** [stephanrauh/ngx-extended-pdf-viewer#1637]
Access to fetch at '1658485795-sample.pdf' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

An error occurred while loading the PDF.

PDF.js v3.1.435 (build: fb06cf4ac)
Message: Failed to fetch
_otherError @ viewer-3.1.435.min.js:44
_documentError @ viewer-3.1.435.min.js:44
(anonymous) @ viewer-3.1.435.min.js:44
push.99140._ZoneDelegate.invoke @ zone.js:409
push.99140.Zone.run @ zone.js:169
(anonymous) @ zone.js:1326
push.99140._ZoneDelegate.invokeTask @ zone.js:443
push.99140.Zone.runTask @ zone.js:214
drainMicroTaskQueue @ zone.js:632
Promise.then (async)
nativeScheduleMicroTask @ zone.js:608
scheduleMicroTask @ zone.js:619
push.99140._ZoneDelegate.scheduleTask @ zone.js:433
push.99140.Zone.scheduleTask @ zone.js:257
push.99140.Zone.scheduleMicroTask @ zone.js:277
scheduleResolveOrReject @ zone.js:1316
resolvePromise @ zone.js:1253
(anonymous) @ zone.js:1169
Promise.then (async)
(anonymous) @ zone.js:1564
ZoneAwarePromise @ zone.js:1349
Ctor.then @ zone.js:1563
(anonymous) @ viewer-3.1.435.min.js:44
push.99140._ZoneDelegate.invoke @ zone.js:409
push.99140.Zone.run @ zone.js:169
(anonymous) @ zone.js:1326
push.99140._ZoneDelegate.invokeTask @ zone.js:443
push.99140.Zone.runTask @ zone.js:214
drainMicroTaskQueue @ zone.js:632
push.99140.ZoneTask.invokeTask @ zone.js:529
invokeTask @ zone.js:1714
globalCallback @ zone.js:1757
globalZoneAwareCallback @ zone.js:1781
zone.js:409 Uncaught (in promise) UnknownErrorException {message: 'Failed to fetch', name: 'UnknownErrorException', details: 'TypeError: Failed to fetch'}

**Comment by stephanrauh** [comment]
You've run into the dreaded CORS error. What's running on port 8100? Is it a local Spring application, it suffices to add an annotation to allow the cross-origin request. If you're using a different framework, I'm sure there's a similar approach available. I've added the Spring annotation in one of my example projects:

https://github.com/stephanrauh/SpringBoot2019/blob/master/expenses/src/main/java/de/beyondjava/travel/expenses/ExpenseController.java#L10-L12

**Comment by durgamalleswariyeruva** [comment]
I am using ionic- angular. I am still facing the cors issue after making changes in server side. So, I tried to download the file using file transfer and want to display using ngx- extended- pdf-viewer. I am successfully able to download the file locally. But not able to display in app. I am getting below error message 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/79316482/210718343-5245999c-8e54-40e6-80ee-9a5e6f22c097.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/79316482/210716448-682e91c4-2205-46ac-9fa5-1a582615eff5.png">

network tab:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/79316482/210717243-b80b8b83-bb2e-4e80-91a7-226d835cef2a.png">

code that i used :

 <ngx-extended-pdf-viewer [src]="pdfSrc " 
    [showToolbar]="false"
    [showSidebarButton]="false"
    [showFindButton]="false"
    [showPagingButtons]="false"
    [showZoomButtons]="false"
    [showPresentationModeButton]="false"
    [showOpenFileButton]="false"
    [showPrintButton]="false"
    [showDownloadButton]="false"
    [showBookmarkButton]="false"
    [showSecondaryToolbarButton]="false"
    [showRotateButton]="false"
    [showHandToolButton]="false"
    [showScrollingButton]="false"
    [showSpreadButton]="false"
    [showPropertiesButton]="false"
    height="100%" zoom="100%"
    localeFolderPath="assets/locale"
    [useBrowserLocale]="true"></ngx-extended-pdf-viewer>

.ts:
constructor(private file: File,
    private transfer: FileTransfer) {}

viewFile(url){ //url we are getting from server which is signed url with aws )
  const transfer = this.transfer.create();
 let path =null;
 
  if(this.platform.is('ios')){
    path =this.file.documentsDirectory;
  }
  else {
    path= this.file.externalDataDirectory; // i tried using data directory also
    console.log("path else..", path)
  }
 
  const name = url.substr(url.lastIndexOf('/') + 1);
  const fileName= name.split('?')[0]
 })
 transfer.download(url, path +name ).then((entry)=>{
  let fileurl =  entry.toURL();(here i tried using fullpath, nativeURL, but no luck)
  console.log('url',fileurl, entry);
  this.pdfSrc= fileurl;
 }).catch((e)=>{
 // console.log('failed error',e)
 })
}

It will be good, if i get help from you.
Thanks for quick response!

**Comment by stephanrauh** [comment]
Browsers are not allowed to access local files unless the user explicitely allows it. So you can drag and drop the file into the viewer, but you can't open a local file. If that were possible, every hacker can write a website reading your entire hard disk.

But you're close. Instead of storing the PDF in a file, put it in a BLOB or a Base64 string. The showcase has two demos showing you how to display BLOBs and Base64 files:
https://pdfviewer.net/extended-pdf-viewer/base64
https://pdfviewer.net/extended-pdf-viewer/blob

**Comment by swami-sanapathi** [comment]
@stephanrauh its not local file, @durgamalleswariyeruva is saying that its AWS signed URL.

**Comment by stephanrauh** [comment]
@swami-sanapathi Thanks for your additional insight. @durgamalleswariyeruva Just in case you feel I dismissed your ticket too quickly - I didn't intend to be disrespectful. To be honest, I'm surprised that `[listenTuURL]="true"` solves the issue. I didn't expect that.

Swami, I don't think that the signature of AWS makes any difference. CORS simply means the browser doesn't accept any URL from a different server. It doesn't matter if the URL is signed. The browser can tell trustworthy URLs from malicious URLs, so it prefers to err on the safe side.

I'm curious. I'd like to know why `[listenTuURL]="true"` works. As far as I know, it shouldn't be possible to download files from third-party URLs. The only exception being the server sends a CORS header, advising the browser to trust certain clients. Can you send me a reproducer?
