### ISSUE TITLE
Printing fails with second instance

### ISSUE THREAD

**Issue by utraum** [stephanrauh/ngx-extended-pdf-viewer#1638]
With the first instance of ngx-extended-pdf-viewer printing works perfect.
After removing (*ngif gets false) and creating again (*ngif gets true) printing only shows a blank page.
I saw in dev-tools that the printContainer-div remains after removig the pdf-viewer. 
If I delete this div manually before creating the next pdf-viewer, printing works again.

**Comment by stephanrauh** [comment]
This rings a bell. I believe to have solved this problem some time ago. Is it back, or are you using an old version of ngx-extended-pdf-viewer?

**Comment by utraum** [comment]
> This rings a bell. I believe to have solved this problem some time ago. Is it back, or are you using an old version of ngx-extended-pdf-viewer?

I'm using 16.0.0alpha2

**Comment by stephanrauh** [comment]
I can confirm that the `printContainer` div isn't removed. That's clearly a bug, and I'm going to fix it. However, I can't reproduce the problem that the second print doesn't work. Can you send me a reproducer, please?

**Comment by stephanrauh** [comment]
Starting with version 16.0.0-alpha.4, the `printContainer` is removed in the `ngOnDestroy` method.
