### ISSUE TITLE
Refused to execute script from 'http://localhost:4200/assets/op-chaining-support.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by Miedziaq** [stephanrauh/ngx-extended-pdf-viewer#1639]
ngx-extended-pdf-viewer.mjs:4710          GET http://localhost:4200/assets/op-chaining-support.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ ngx-extended-pdf-viewer.mjs:4710

439605196838388405:1 Refused to execute script from 'http://localhost:4200/assets/op-chaining-support.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
ngx-extended-pdf-viewer.mjs:4803          GET http://localhost:4200/assets/pdf-3.2.506-es5.min.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ ngx-extended-pdf-viewer.mjs:4803

439605196838388405:1 Refused to execute script from 'http://localhost:4200/assets/pdf-3.2.506-es5.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by stephanrauh** [comment]
Usually, this mean these files aren't there. Angular responds with the `index.html`, so the browser is confused and starts complaining about HTML when it expects JavaScript.

Check the rules in your `angular.json`. Did you add the rules to copy `pdf-*.js`, `viewer*.js`, and `op-chaining-support.js` to the assets folder?

**Comment by Miedziaq** [comment]
still problems :| even if scripts is copied

![image](https://user-images.githubusercontent.com/15612453/211288976-1921742e-9a26-490b-aa00-637f6121002f.png)

**Comment by ziaKhan1995** [comment]
I just re-runned the project and it worked.
