### ISSUE TITLE
404 (pdf-2.16.453-es5.min.js & op-chaining-support.js) Error

### ISSUE THREAD

**Issue by simran9988** [stephanrauh/ngx-extended-pdf-viewer#1650]
Hi, I am creating  angular library using ngx-extended-pdf-viewer .following thoses steps
 i have created angular library https://angular.io/guide/creating-libraries. after creating when i am testing that library into the another app i am getting this error :
Refused to execute script from 'http://localhost:4200/op-chaining-support.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
d to execute script from 'http://localhost:4200/pdf-2.16.453-es5.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by stephanrauh** [comment]
I'm afraid you've run into a shortcoming of Angular libraries. They allow you to share Angular code without problems, but they don't support sharing other resources. At least they didn't when I checked last time (about Angular 8 or so), and your bug report indicates the problem still exists.

The error message means that you didn't copy the JavaScript files of ngx-extended-pdf-viewer to the assets folder. Add these lines to your `angular.json`:

```json
"assets": [
    "src/favicon.ico",  // already there
    "src/assets",         // already there
    {                             // lines to insert start here
      "glob": "**/*",
      "input": "node_modules/ngx-extended-pdf-viewer/assets/",
      "output": "/assets/"
    }
  ],
```

In an ideal world, you'd configure this in the library, but it seems Angular isn't there yet. Or both of us missed it in the documentation. :)

Best regards,
Stephan
