### ISSUE TITLE
NgxExtendedPdfViewerService and getFormData sometime fails (16.0.0-alpha.3)

### ISSUE THREAD

**Issue by Sergiobop** [stephanrauh/ngx-extended-pdf-viewer#1651]
**Describe the bug**
Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'numPages')
TypeError: Cannot read properties of null (reading 'numPages')

**Version info**
^16.0.0-alpha.3

**To Reproduce**
I'm using the package to display some PDF's with forms. I have a select to change the PDF which i want to display.

Sometimes when i change the PDF (i'm just changing the [src] input of the ngx-extended-pdf-viewer component) i see those errors on my console.

**Additional context**
The error is tracked to this line: 
`for (let i = 1; i <= pdf.numPages; i++)`
 (pdf.numPages, in the getFormData method)
 
 
 I'm calling the pdfService.getFormData when the pdfLoaded event is triggered like this:
 ```
 <ngx-extended-pdf-viewer
  [src]="src"
  (pdfLoaded)="pdfDocumentLoaded($event)">
</ngx-extended-pdf-viewer>
```

```
async pdfDocumentLoaded($event: PdfLoadedEvent) {
    const formData = await this.pdfService.getFormData();
    ...
}
```

Sometimes (and i don't know if it's a different issue) this line 
`const formData = await this.pdfService.getFormData();`
    
Explodes and doesn't load the PDF:
    ```
    Uncaught (in promise): TypeError: this.pdfService is null getFormData
    ```

I load the service like this:
` private pdfService = inject(NgxExtendedPdfViewerService); `

**Comment by stephanrauh** [comment]
Both bugs are probably timing errors. I think I ought to solve the NPE at `pdf.numPages` by adding a null-safe chaining operator (aka question mark), but I'm not sure it's really an improvement. If you call the method too early, you're rewarded with an empty array. That's better than a crash, but a perfect solution would wait until pdf.js has created the form data structures, and I don't know how to do that.

The second bug also sounds like a timing problem. Often, simply setting a timeout with 0 seconds delay helps. The idea is to delay the execution of the code slightly, so pdf.js has an opportunity to catch up. pdf.js uses promises a lot - basically, everything is asynchronous - so it's often difficult to wait until the library has finished initializing, and adding a short timeout is an ugly workaround that works. A timeout of 0 seconds puts your request at the end of the request queue, so even a delay of zero seconds may help.

**Comment by stephanrauh** [comment]
Does this help you? I'm keeping this issue open until you tell me you've managed to solve the issue.

**Comment by Sergiobop** [comment]
I tried this:
HTML:
```
<ngx-extended-pdf-viewer
  (pdfLoaded)="pdfDocumentLoaded($event)"
</ngx-extended-pdf-viewer>
```
TS:
```
async pdfDocumentLoaded($event: PdfLoadedEvent) {
    setTimeout( async () => { const formData = await this.pdfService.getFormData() } );
```

The error TypeError: Cannot read properties of null (reading 'numPages') is still there sometimes

**Comment by stephanrauh** [comment]
I'm afraid I need a reproducer to help you. Can you send me a simple, minimal, and complete project showing the bug, please?

BTW, sorry for responding late: COVID-19 kept me busy during the last two weeks.

**Comment by Sergiobop** [comment]
Hi @stephanrauh , sorry for the delay.
You can close the issue for now, since i'm just ignoring the error in my app (Everything works, the error shows in the console but no side effects) Anyway, i think you could add the pdf.numPages null-safe chaining operator (aka question mark)

Thanks

**Comment by stephanrauh** [comment]
Adding Elvis operators is always a good idea. No clue why I missed your suggestion in January - sorry about that. The next version of ngx-extended-pdf-viewer is going to fix this.
