### ISSUE TITLE
Can't load the pdf first time, but can loaded after resize the browser windows

### ISSUE THREAD

**Issue by winsonet** [stephanrauh/ngx-extended-pdf-viewer#1654]
**Describe the bug**

For example, I created a button for loading the pdf from blob data, but it will not load after first time click the button, I need to click the second time and can loaded the pdf. 

and also, I found that the pdf can be loaded after resize the browser window even first time loading

and there is no any pages loaded events if the pdf was not loading

and my codes is same with your sample and very simple
https://pdfviewer.net/extended-pdf-viewer/blob

button click event for load the pdf
```
getReport(){
    this.cityService.cityReport().subscribe(data => {
      this.cityReportData = data;
      console.log('%c [ response ]-28', 'font-size:13px; background:pink; color:#bf2c9f;', data);      
    }, error => console.error(error));
  }
```
get blob data from remote server
```
 cityReport() {
    var url = this.getUrl("/Reports/city-report");
    return this.http.get(url, { responseType: 'blob' });
  }
```

my angular version: v15.0

**Version info**
- Version of ngx-extended-pdf-viewer : ^16.0.0-alpha.3

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser] : Chrome (Version 109.0.5414.75 (Official Build) (64-bit))
 
**Smartphone (please complete the following information):**
 - Device: no

**To Reproduce**
I think that's only happen in my case, but I also found another similar [issue ](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/932)

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Click the load pdf button 
2. Click the button again

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**
![image](https://user-images.githubusercontent.com/1869995/213336278-894a8243-9d07-43f1-9412-762b11b3f712.png)

Many Thaks!

**Comment by stephanrauh** [comment]
I hoped this bug is gone for good. However, it doesn't happen in my projects. Can you send me a reproducer, please? That's a minimal but complete project showing the problem.

BTW, sorry for responding late. COVID-19 kept me busy during the last two weeks.

**Comment by winsonet** [comment]
Many thanks for your reply and hope everything goes well with you!

And for my case, it's very strange, I spend a lot of times and didn't solve it, but after I created another new page and put all same codes, everything is fine, the problem has been solved~~ 

and I also tried to put all codes in the old page again, and still can't reproduce the issue, so maybe just my environment issue not the bug!

By the way, the `ngx-extended-pdf-viewer` is very powerful and great, thank you so much!

**Comment by winsonet** [comment]
But I just found another issue that when I created two pages with same codes for show the pdf below:

1. click page 1 show pdf and is fine
2. turn to page 2, will show below error in console and can't working
![image](https://user-images.githubusercontent.com/1869995/215368565-1b6b4d70-cd5b-4ae3-9aae-ae91ecc1be4c.png)

and if show the page 2 first, will be changed to fail with page 1
1. click page 2 show pdf and is fine
2. turn to page 1, will show the above errors

the error line in the code as below
![image](https://user-images.githubusercontent.com/1869995/215368931-d37fe6e9-e579-46b2-ad62-0c766a104849.png)

![image](https://user-images.githubusercontent.com/1869995/215368865-79e1fef5-c581-41a1-81cd-2cb5ee419fce.png)


do you have any ideas?

**Comment by winsonet** [comment]
I tried to create a new project base on your sample and it can reproduced this issue, I think you can try it.

new project structure just very simple with two pages and use angular material for the UI layout

![image](https://user-images.githubusercontent.com/1869995/215382485-4aec83cd-8161-4b43-9dbd-989023fe9f98.png)

please find the below core codes

get the pdf by http
```
this.http
      .get(
        '/assets/pdfs/Bootstrap-vs-Material-Design-vs-Prime-vs-Tailwind.pdf',
        { responseType: 'blob' }
      )
      .subscribe((res) => this.reportData = res);
```

the view codes
```
<ngx-extended-pdf-viewer
        (pagesLoaded)="onPagesLoaded($event)"
        (pageRendered)="onEvent('pageRendered', $event)"
          [src]="reportData"
          [useBrowserLocale]="true"
          [customToolbar]="additionalButtons"
          [textLayer]="true"
          [height]="'80vh'"
        >
        </ngx-extended-pdf-viewer>
        <ng-template #additionalButtons>
          <div id="toolbarViewer">
            <div id="toolbarViewerLeft">
              <pdf-toggle-sidebar></pdf-toggle-sidebar>
              <div class="toolbarButtonSpacer"></div>
              <pdf-find-button [showFindButton]="true" [textLayer]="true"></pdf-find-button>
              <pdf-paging-area></pdf-paging-area>
            </div>
            <div id="toolbarViewerRight">
              <pdf-open-file></pdf-open-file>
              <pdf-presentation-mode></pdf-presentation-mode>
              <pdf-print></pdf-print>
              <pdf-download></pdf-download>
              <div class="verticalToolbarSeparator hiddenSmallView"></div>
              <pdf-toggle-secondary-toolbar></pdf-toggle-secondary-toolbar>
            </div>
            <pdf-zoom-toolbar></pdf-zoom-toolbar>
          </div>
        </ng-template>
```

**Comment by solita-PerttuLe** [comment]
This is still issue. 
Currently preventing us to use this component. I guess problem started after updating to Angular 14.
Resizesing window can be used as workaround.

**Comment by stephanrauh** [comment]
@solita-PerttuLe Can you send me a reproducer, please? You know, I can't solve a problem I don't have.

Best regards,
Stephan

**Comment by solita-PerttuLe** [comment]
I will try to provide a reproduce.
Problem seems to be that PDFViewerApplication.eventBus is null.
I found related issue.
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/56

**Comment by stephanrauh** [comment]
That sounds encouraging. If there's an error message, there's usually an opportunity to find the bug.

**Comment by solita-PerttuLe** [comment]
I provided a reproduce of eventBus being null.
I was not able to reproduce our case where re-sizing fixes problem.

Here is zip:
It can be tested by running npm install and npm start.

https://drive.google.com/drive/folders/1NW01F-jGptlUGzwKHw8L0dcTYJg12OHS?usp=sharing

**Comment by solita-PerttuLe** [comment]
Error can be also "offsetParent is not set – cannot scroll" not only "Cannot read properties of null"

**Comment by stephanrauh** [comment]
Terve maailma? :) Greetings to Finland (or so I guess)!

I other words: I've downloaded your example, managed to reproduce your issue, and managed to see both PDF files when I started being persistent.

At the moment, that's all I did. I'm stuck with #1718. But I'm very happy that you went the extra mile and sent me a reproducer. Thanks at lot!

**Comment by solita-PerttuLe** [comment]
Nice to hear you was able to reproduce problem.
I was going to hunt it down myself and create pull request but was not able to get project work locally with "how to build" instructions or with node modules file link in package.json. It might be a typescript typing issue.
Maybe I will create another issue about that.

**Comment by stephanrauh** [comment]
Adding a timeout of zero milliseconds solves the problem. The problem is that pdf.js pollutes the global namespace, so you have to give it some time to destroy resources before opening a new instance of the PDF viewer. It's a bit surprising that 0 milliseconds is already enough, so maybe you'll want to experiment with the timeout setting.

I've modified your demo and uploaded it to https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue1654.

Enjoy!
Stephan
