### ISSUE TITLE
How can i show only zoom button(showZoomButtons]) without enabling toolbar([showToolbar]) in ngx-extended-pdf-viewer plugin

### ISSUE THREAD

**Issue by durgamalleswariyeruva** [stephanrauh/ngx-extended-pdf-viewer#1655]
(removed this text because it was the unmodified, unfilled bug form)

**Comment by durgamalleswariyeruva** [comment]
I want to show zoom in and zoom out buttons. when i enabled toolbar defaultly textbox and pencil icon are displaying. how can i hide textbox and pencil icon in toolbar

**Comment by stephanrauh** [comment]
Like so? Use the most current 16 version (yeah, I know, it's currently alpha) and set `[showEditor]="false"`.

<img width="1339" alt="grafik" src="https://user-images.githubusercontent.com/3045767/215284762-5c613188-284d-45f6-b358-6ea1aefa47ee.png">

**Comment by stephanrauh** [comment]
BTW, sorry for responding late. COVID-19 kept me busy for two weeks.
