### ISSUE TITLE
Problem to open attachments

### ISSUE THREAD

**Issue by cvpereira** [stephanrauh/ngx-extended-pdf-viewer#1657]
Hi Stephan

I have a pdf with several attachments and I'm trying open  one of the attachments, but when I click, is opened a new tab with the original file again on the browser, but don't open or download the attachment selected. The bug not happen on https://mozilla.github.io/pdf.js/web/viewer.html. Can you help me with this problem?

I'm using the version 15.2.0 of ngx-extended-pdf-viewer. The browser used to test was Chrome 109.0.5414.75 - 64 bits

To reproduce, 

1 - Go to https://pdfviewer.net/extended-pdf-viewer/simple, open the pdf attached 
2 - Click on any attachment
3 - A new tab is opened with other pdf, but not the attachment selected

[PDFWithAttachmets.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/10462060/PDFWithAttachmets.pdf)

![image](https://user-images.githubusercontent.com/43296859/213588616-1cfb181e-4302-4d79-b3e4-68c5c1a90cc5.png)

![image](https://user-images.githubusercontent.com/43296859/213588754-f2554356-a017-4a48-9595-1a1a16d9c49d.png)

![image](https://user-images.githubusercontent.com/43296859/213588827-061dc871-94b5-4b83-b321-a8902767be22.png)

**Comment by stephanrauh** [comment]
I'll have a look at it.

BTW, sorry for responding late. COVID-19 kept me busy during the last two weeks.

**Comment by stephanrauh** [comment]
That was an interesting bug. Mozilla's PDF viewer tries to open the attachment using Mozilla's viewer. That's clever, but it doesn't work in an Angular application. Now the file is opened using the PDF viewer of the browser.

The bugfix is going to land with version 16.0.0-alpha.4 soon.

**Comment by cvpereira** [comment]
> That was an interesting bug. Mozilla's PDF viewer tries to open the attachment using Mozilla's viewer. That's clever, but it doesn't work in an Angular application. Now the file is opened using the PDF viewer of the browser.
> 
> The bugfix is going to land with version 16.0.0-alpha.4 soon.

Glad you were able to fix this problem, you planned when you will release version 16 officially? I am also happy to hear that you are in good health, I also had covid, but it was very mild.

Best regards.

**Comment by stephanrauh** [comment]
I'm not sure about the release date. Once again, Mozilla surprised me with a new release of pdf.js 3.3. So maybe I'm delaying version 16 another week, so I can update the stable branch to pdf.js 3.3. They've implemented smooth pinch gestures on touch pads (and hopefully on mobile devices, too, but I didn't test that yet), so it may be worth the delay.

In any case, that's early February.
