### ISSUE TITLE
/images/toolbarButton-editorInk.svg is missing

### ISSUE THREAD

**Issue by Sergiobop** [stephanrauh/ngx-extended-pdf-viewer#1658]
**Describe the bug**
I'm getting this error when i click on the editorInk button
GET http://localhost:4200/images/toolbarButton-editorInk.svg 404 (Not Found)

**Version info**
^16.0.0-alpha.3

**Additional context**
I can't find that svg in the https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/assets/images folder

The css files use the svg on something like this:
```--editorInk-editing-cursor: url(images/toolbarButton-editorInk.svg)```

**Comment by stephanrauh** [comment]
The bugfix is going to land with version 16.0.0-alpha.4 soon.

Sorry for replying so late. Covid-19 keep me busy during the last two weeks.
