### ISSUE TITLE
Sorry for re-posting same issue as I was unable to open previous one: PDF is not downloading on Edge/IE 11

### ISSUE THREAD

**Issue by samit2015** [stephanrauh/ngx-extended-pdf-viewer#166]
We are unable to download pdf on IE while we are able to see it on IE 11/Edge. On Download, it says Cant download and then if we retry, It hangs at Resuming status.

Thanks for looking into this Stephan, issue is with ngx-extended-pdf-viewer.js where we define this.filenameForDownload = 'document.pdf';, if we remove the name and keep this.filenameForDownload = ''; we get file name and download correctly on Chrome BUT on IE 11, download doesnt happen...any idea ...how can we pass our custom name to download file.

**Comment by stephanrauh** [comment]
No worries... if there's a bug, I've got a bug to fix! :)

Yesterday, I've tried to reproduce your bug on IE11. It worked like charm, even with your `filename=''" bit.

As for your question: with most browsers, the property `[filenameForDownload]` defines the default file name. Usually, the user is asked if and where they want to store the file, so they can override this filename. Sometimes the browser simply stores the file in a `downloads` folder without asking the user. In this case, the setting `[filenameForDownload]` should define the filename.

One of these days, I'll try to reproduce your bug one more time. However, I still think there's a crucial bit of information missing.

**Comment by samit2015** [comment]
Thanks for ur input and replying Stephan

**Comment by stephanrauh** [comment]
Yeah... but so far I didn't give you that much input. :) I suppose you've still got this bug?

**Comment by stephanrauh** [comment]
I didn't hear from you for a long time. Do you have got a reproducer for me?

Best regards,
Stephan
