### ISSUE TITLE
book view mode

### ISSUE THREAD

**Issue by RaghavRNK007** [stephanrauh/ngx-extended-pdf-viewer#1665]
Hi if i change pdf [src] on button click pageViewMode 'book' is not working properly, most of the time it just reset to default view when src link get changed

**Comment by stephanrauh** [comment]
I never tried that, and implementing book mode was difficult, so I'm not surprised. At the moment, my priority is publishing version 16, so I'll postpone your issue - although it sounds interesting. If you haven't heard from me in, say, four weeks, please nudge me.

In the meantime, you can probably work around the bug by

1. hiding the pdf viewer (`*ngIf="false"`)
2. waiting until the garbage collector has finished (i.e. by setting a timeout of 500 milliseconds)
3. modify the `src` attribute and show the pdf viewer again

**Comment by stephanrauh** [comment]
Version 17.4.2 is a slight improvement. Changing `[src]` now works most of the time. However, book mode remains capricious, and neither drag and drop nor the "file open" menu work.

**Comment by stephanrauh** [comment]
Shortly after publishing I noticed that it's easy to get rid of the last two shortcomings. Version 17.4.3 now also allows users to use drag-and-drop and the "file open" menu.
