### ISSUE TITLE
pageViewMode is changed when loading a PDF with an untrusted signature

### ISSUE THREAD

**Issue by manerow** [stephanrauh/ngx-extended-pdf-viewer#1668]
I'm working on an application for PDF document e-signing. When I load a non signed document, the viewer displays it with the correct pageViewMode that I have configured (pageViewMode="multiple").
The problem comes when I try to display different PDF documents with self-generated signatures embedded on them. They are loading every time with "singlePageView" class pre-defined on the "`viewer`" div, inside the "viewerContainer" div.

![image](https://user-images.githubusercontent.com/33031570/216387001-d9698880-cb8b-473d-919a-85211936426e.png)

I'm working with ngx-pdf-viewer on v14.5.3.
```
// package.json
"dependencies": {
    ...,
    "ngx-extended-pdf-viewer": "14.5.3",
    ....
}
```

 I have the following ngx-extended-pdf-viewer declaration:
 ```
 <ngx-extended-pdf-viewer
    *ngIf="!!documentFile && documentFile | fileToBase64 | async as documentSrc"
    #pdfViewer
    class="pdf-viewer"
    [src]="documentSrc"
    [(zoom)]="zoom"
    [(page)]="page"
    [showToolbar]="true"
    [showSidebarButton]="false"
    [showFindButton]="false"
    [showPagingButtons]="false"
    [showEditor]="false"
    [showZoomButtons]="false"
    [showPresentationModeButton]="false"
    [showOpenFileButton]="false"
    [showPrintButton]="false"
    [showDownloadButton]="false"
    [showSecondaryToolbarButton]="false"
    [showRotateButton]="false"
    [showHandToolButton]="false"
    [showScrollingButton]="false"
    [showSpreadButton]="false"
    [showPropertiesButton]="false"
    [mobileFriendlyZoom]="true"
    pageViewMode="multiple"
    backgroundColor="#666666"
    showUnverifiedSignatures="true"
    (pdfLoaded)="afterLoadComplete($event)"
    (pageRendered)="pageRendered($event)">
</ngx-extended-pdf-viewer>
```
I'd want to be able to open signed documents in the same pageViewMode I've defined on my pdf-viewer.

**Comment by stephanrauh** [comment]
You're right, that's definitely not the way I intended the feature to work.

**Comment by stephanrauh** [comment]
I suspect something different happens. At least I couldn't reproduce your problem in my showcase. I only managed to reproduce it when I selected the single page mode in the menu.

Pdf.js has a small cache allowing it to remember the last user-defined setting. The idea is that the user knows what they're doing, so their choice should be honoured, no matter what the programmer says. In your case, this causes confusion. Possibly it's even detrimental.

Can you verify my theory, please? To do so, open the "web memory" tab of your browser's developer tools, examine the local storage, and delete the entry "pdfjs.history". Below's the screenshot. It's in German language, but I hope it's close enough to your language to help you:

![grafik](https://user-images.githubusercontent.com/3045767/216463666-2a6c0564-5380-4609-9633-e40a10bf8cd4.png)

**Comment by manerow** [comment]
Oh, you're absolutely right! 
I'm glad to say that after deleting the pdfjs.history entry, everything is working as expected. I must have caused the error during my previous tests.

Congratulations on having an amazing library and  thanks for your speedy responses! :)
