### ISSUE TITLE
Open file should able to select PDF files only

### ISSUE THREAD

**Issue by umar-shafiq** [stephanrauh/ngx-extended-pdf-viewer#167]
The "open file" dialog allows you to open any file type. It'd be nice to restrict this to *.pdf files.

Usually browsers offer the option of ignore this default setting, so that's no breaking change. If the file has the wrong suffix and/or the wrong MIME type, the user still can open it. It's just an additional click.

Here's a screen shot of how it should look like:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/3045767/68625074-9952aa00-04d8-11ea-9b3a-9279a8d2238d.png">

Non-PDF files are gray, so it's easy to see the relevant files. The "options" button allows you to choose any file, no matter which suffix.

**Comment by stephanrauh** [comment]
@umar-shafiq Sounds like a sensible request. By the way, I took the liberty to complete your feature request. In this case, it was easy enough to guess what you need, so everything's fine. But sometimes, it's not so easy, so I really appreciate any help you can offer to me!

**Comment by stephanrauh** [comment]
Shipped with version 1.7.6. Thanks for the hint!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
@umar-shafiq I've just opened a ticket on the root project (i.e. Mozilla's pdf.js). Of course, I mentioned your name - or at least your GitHub username. Now I'm curious what's going to happen. Maybe your suggestion makes it into every Firefox and Chrome browser!
