### ISSUE TITLE
Export/import PDF editor annotations?

### ISSUE THREAD

**Issue by Blunderchips** [stephanrauh/ngx-extended-pdf-viewer#1679]
**Is your feature request related to a problem? Please describe.**
With the inclusion of the Editor by default with v16, is it possible to programmable export and load?  We have a DB that stores links to PDFs and little metadata. You can view these PDFs in the app using this viewer. 

It would be nice if the user can annotate the PDF using the viewer, that data gets saved alongside a reference to the PDF and then when we retrieve the URL of the document we also include all annotation data.

**Describe the solution you'd like**
Some way to export the current editor state as JSON (maybe fire an event on edit?) and have an input for setting the editor state when the document is loaded. 

**Describe alternatives you've considered**
In my case, if there is no way to persist Editor annotation then the editor needs to be disabled.

**Additional context**
This may already be possible but I am not seeing how it is done in any of the docs.

**Comment by stephanrauh** [comment]
@Calixteman Do you plan to implement an editor annotations export in pdf.js? If not, is it difficult to implement such an export in my branch of pdf.js?

**Comment by calixteman** [comment]
The data for each new annotations are stored in the `annotationStorage`:
https://github.com/mozilla/pdf.js/blob/fd1c9e34ac63bbe0287c5b218ccaa9cb1f15cf9d/src/display/annotation_storage.js#L160
Each new annotation can be serialized:
https://github.com/mozilla/pdf.js/blob/fd1c9e34ac63bbe0287c5b218ccaa9cb1f15cf9d/src/display/editor/ink.js#L1084
and can be deserialized:
https://github.com/mozilla/pdf.js/blob/fd1c9e34ac63bbe0287c5b218ccaa9cb1f15cf9d/src/display/editor/ink.js#L1032

This serialization/deserialization are used when copying/pasting some annotations from a pdf to an other:
https://github.com/mozilla/pdf.js/blob/fd1c9e34ac63bbe0287c5b218ccaa9cb1f15cf9d/src/display/editor/tools.js#L539-L546

The serialized data are used to print/save the annotations, for example:
https://github.com/mozilla/pdf.js/blob/fd1c9e34ac63bbe0287c5b218ccaa9cb1f15cf9d/src/core/annotation.js#L4088

**Comment by Blunderchips** [comment]
Thank you for looking into this. Please give me a poke if there is anything I can do to assist with the development or if you guys need hand testing.

**Comment by stephanrauh** [comment]
During the next couple of days, I'm busy preparing a conference talk. In the meantime, you can explore the API yourself. You can access it in your TypeScript code. I've cobbled together a few lines in the browsers console to give you a head start:

```js
let annotations = Object.values(PDFViewerApplication.pdfDocument.annotationStorage.getAll());
console.log(annotations[0].serialize());
```

In TypeScript, you'll probably run into missing type definitions. Bear with me. You find the full set of type definitions here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/types. The list of `AnnotationTypes` is here: https://github.com/mozilla/pdf.js/blob/22618213c7f69060d5e7c4823f3f9863588236df/src/shared/util.js#L114 

To get the root object, use this line:
```typescript
const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
```

If you want to go the extra mile and send me a pull request, the class `NgxExtendedPdfViewerService` is a good point to add your feature. In any case, I suggest you experiment with the API and tell me what works and what doesn't.

Enjoy!
Stephan

**Comment by Blunderchips** [comment]
@stephanrauh still considering this/any plans to develop further? (:

**Comment by stephanrauh** [comment]
Yes - but currently, I haven't got enough time to spare to develop new features. Pull requests are welcome!

**Comment by Blunderchips** [comment]
For reference: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1685

**Comment by stephanrauh** [comment]
The pdf.js showcase already saves the editor annotations. So I suspect all I have to do is to update to the latest version of pdf.js. Which is two versions upstream of the current version of ngx-extended-pdf-viewer. My current strategy is to publish version 17.0.0 first, and after that, I'll update the "bleeding edge" branch to pdf.js 3.7. That, in turn, means that this ticket has to wait a bit longer. I hope it's going to be a short wait. If everything goes according to plan, we're talking about days, not weeks. But I've learned the hard way not to make promises!

**Comment by stephanrauh** [comment]
Holy moly... it was a bug, not a missing feature! Please update to version 17.0.0-beta.1. It includes the editor annotations both in print and in the download.

**Comment by Blunderchips** [comment]
> Holy moly... it was a bug, not a missing feature! Please update to version 17.0.0-beta.1. It includes the editor annotations both in print and in the download.

Not sure what you mean here? So the annotations are included when printing and downloading but how do we add them when viewing a PDF? Use-case being viewing a PDF, adding some annotations, closing the tab, and then viewing the same PDF at a later date. Not seeing how they will still be there if we don't stick the state in a database or something :)

**Comment by stephanrauh** [comment]
Sorry for getting you wrong. I'll open a new ticket later because I often get confused by tickets with a long history.

The annotations are part of the PDF file you get by clicking the download button or by calling `NgxExtendedPdfViewerService.getCurrentDocumentAsBlob()`. That's why I got you wrong.

If you need to export the annotations and store them separately from the PDF file, that's a valid use-case, too, but it's not the use-case I had in mind.

In a nutshell, you get the annotation by calling `PDFViewerApplication.pdfDocument.annotationStorage.getAll()` (plus a type cast to make TypeScript happy). Note that this give you every annotation, including the form fields if you PDF file has an AcroForm or an XFA form.

Adding the annotations to the PDF file and making them visible is more difficult. But it shouldn't be impossible. The editor does the same, so the algorithm should be somewhere in this folder: https://github.com/mozilla/pdf.js/tree/master/src/display/editor
