### ISSUE TITLE
is it possible to disable editing of PDF forms.?

### ISSUE THREAD

**Issue by NexPlex** [stephanrauh/ngx-extended-pdf-viewer#1680]
My application generates data that goes on the PDF.  using ngx-extended-pdf-viewer I can populate the data onto a PDF form without a problem.

I want to disable the user's ability to edit the Data directly on the PDF form. I want the fields displayed by ngx-extended-pdf-viewer to be read-only. The users need to close the PDF viewer and then edit the data in the app.

Is it possible to set the PDF viewer to read only?

Warm Regards
Chris

**Comment by stephanrauh** [comment]
This seems to be a popular demand, so I'm going to add an attribute in one of the next versions.

In the meantime, have a look at #1663. I'm describing over there how to implement the feature yourself.

**Comment by NexPlex** [comment]
Great, thank you!! Second Question, How do I programmatic save the PDF with the updated data?

**Comment by stephanrauh** [comment]
I've opened #1685 to address your second question. If I'm not mistaken, you're the third user asking for the feature this week, so I guess it's a popular feature.

**Comment by stephanrauh** [comment]
Your first feature has landed: version 17.0.0-alpha.9 adds the flag `[disableForms]`.
