### ISSUE TITLE
TypeError Object.initializeLoadingBar(assets/viewer-3.3.491) Unhandled Cannot read properties of null (reading 'hide')

### ISSUE THREAD

**Issue by dev080** [stephanrauh/ngx-extended-pdf-viewer#1688]
**Describe the bug**
Issue reported by sentry, in production mode. block users in theirs works

**Version info**
- 16.0.2

**Desktop (please complete the following information):**
 - chrome, angular service worker

angular 13

**Comment by stephanrauh** [comment]
I feel your pain, but I'm afraid your error description is a bit vague. I don't know where to start looking. Do you have a stacktrace for me?

**Comment by stephanrauh** [comment]
Oh, got it. Yeah, that's a stupid bug. Maybe a rogue merge? I'm admittedly sloppy, but I can't imagine being this sloppy... :)

```ts
  /* modified by ngx-extended-pdf-viewer #633. The shadow() function        */
  /* replaces the getter by a property,so when a new instance of            */
  /* ngx-extended-pdf-viewer is opened, it still references the old viewer. */
  /** The bug fix solves this problem.                                      */
  initializeLoadingBar() {
    const barElement = document.getElementById("loadingBar");
    const bar = barElement ? new ProgressBar(barElement) : null;
    bar.hide(); // <<< may be null
    return shadow(this, "loadingBar", bar);
  },
```
