### ISSUE TITLE
Allow developers to define the breakpoint for each toolbar element

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1691]
@durgamalleswariyeruva reports in #1667 that the editor menu icons are not available on mobile devices.

I guess that's a special case of a general problem. I've defined the breakpoints of the toolbar icons as seemed fit, but that doesn't necessarily match the requirements of the customer. Let's find a way to override the default breakpoints.

**Comment by stephanrauh** [comment]
@durgamalleswariyeruva and @ everybody: Currently, there's a set of options `[showXXXButton]`. These properties are booleans. Setting them to false hide the button.

What about allowing new values, such as `boolean | 'always-visible' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl'`?

So 
- false means the button is never shown
- true is the default breakpoint by me
- always-visible means the button is shown on every device, even the smallest ones
- xs means the button is hidden if the toolbar is less than 490 pixels wide
- sm means the button is hidden if the toolbar is less than 560 pixels wide
- md means the button is hidden if the toolbar is less than 610 pixels wide
- lg means the button is hidden if the toolbar is less than 660 pixels wide
- xl means the button is hidden if the toolbar is less than 740 pixels wide
- xxl means the button is hidden if the toolbar is less than 830 pixels wide

How do you like the idea?

**Comment by durgamalleswariyeruva** [comment]
@stephanrauh , your Idea Sounds great. Is it compatible incase to hide any one of toolEditors(If i want to show only one editor i.e either textbox or pencil drawer)?

**Comment by stephanrauh** [comment]
Yes, of course. 

Yesterday, I've split `[showEditor]` into the two properties `[showEditorDraw]` and `[showEditorText]`. Currently, I'm unhappy with the names of the properties because they sound like broken English. On the other hand, names like `[showTextEditor]` and `[showFreehandDrawingEditor]` might be more difficult to find by guessing. I haven't made up my mind yet about the names, so this is subject to change.

The datatype (tentatively baptized `ResponsiveVisibility` applies to each button and menu item. Splitting `[showEditor]` into two properties gives you all the flexibility you need.

I just wonder if someone needs even more flexibility. I can think of two scenarios:

- The breakpoints I've defined work well in my use-cases, but I was always unhappy with the breakpoint Bootstrap defines. I don't believe I'm the only rebel out there. So I'd like to allow developers to override my choice of breakpoints. More likely than not, that's not a big deal. You can do this with some custom CSS magic. I just have to check if this works and to document how to do it.
- I wonder if I should allow users to hide buttons if the screen is wider than a certain breakpoint. This idea is a bit weird, so I'm going to postpone it. I'll implement the feature if at least two or three users demand it. But still, I consider breakpoint definitions like `[showEditorText]="sm-lg"` or `[showEditorDraw]="<lg"` strangely attractive. I can't think of a use-case, but my gut feeling is I should support this.

BTW, what's also a challenge is that every button is meant to move into the secondary menu on small screens. So the secondary menu has to interprete the values of `ResponsiveVisibility` the other way round. I guess that's merely my headache. I don't think that's an issue for developers using my library. Nonetheless, I wonder if there's a valid use-case for omitting some of the buttons in the secondary menu while still showing the secondary menu. The effect would be that users loose access to some features on small displays, but still can access a small selection features in the secondary menu.

While I'm writing this, I feel my scenarios are absurd or at least irrelevant. Nonetheless, they feasible, at least in theory. So I guess I'm going to consider them out-of-scope until someone who's reading this requests such a feature.

**Comment by stephanrauh** [comment]
Our idea works fine. I've pushed my current progress, so you can have a look at the current state of the art. Of course, there's still work to do. In particular, the secondary menu doesn't react to the new attribute values. Consider it a glimpse into the workshop.

**Comment by stephanrauh** [comment]
The feature has landed with version 16.1.0.

**Comment by stephanrauh** [comment]
Version 16.2.0 now also allows you to modify the breakpoints (as opposed to simply assigning different breakpoints to the buttons).

Enjoy!
Stephan

**Comment by durgamalleswariyeruva** [comment]
Thanks @stephanrauh  for your quick action on this issue.
