### ISSUE TITLE
"currentPageNumber is not a valid page number" after opening a new PDF file

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1699]
[Grajon](https://github.com/Grajon) recently pointed out that it's a bit odd that the PDF viewer reports an error if you're switching to a new PDF file, and the PDF file has less pages than the previous one. More to the point, if your previous page number is higher than the number of pages of the new PDF file, the PDF viewer reports an error.

I'm not sure I can do something about it, but I have to admit it's a bit odd to report an error because neither the programmer and the user did anything wrong.

**Comment by Grajon** [comment]
sorry, i have deleted my comment. By setting the currentPageNumber to 1 on loading there is no error

**Comment by stephanrauh** [comment]
Yeah, but I believe you do have a point, so I picked it up anyways. I never consider this a bug - but on the other side, if everybody's doing everything correctly, what's the point in showing an error message?

However, maybe I can't do much about it. But I'd like to try.

**Comment by stephanrauh** [comment]
Solved with version 17.2.1.
