### ISSUE TITLE
Memory leaks in the pdf.vs viewer

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#17]
While investigating #12, I noticed there are memory leaks concerning the PDFViewer object. It's referenced my many widgets even after destroying the PDF viewer and removing it from the DOM.

The memory leak is roughly 30 KB each time a PDF viewer is created (e.g. after hiding and showing the PDF file again).

**Comment by dalepo** [comment]
Is this an issue for the original library as well?

**Comment by stephanrauh** [comment]
@Srimugan reports in #12:

**Print Container and file Input Element** appending at the document body each time when navigate changes from any page to this page.

**Comment by stephanrauh** [comment]
@Srimugan Confirmed and solve the `printContainer` and `fileInput` issue.

**Comment by stephanrauh** [comment]
Also see https://github.com/mozilla/pdf.js/issues/10021. @timvandermeij recommends updating to a current (i.e. developer) builds.

**Comment by timvandermeij** [comment]
Only do that to try if the memory leak situation improves. If it does, wait for mozilla/pdf.js#10819 to be done first so you can use an official release.

**Comment by stephanrauh** [comment]
@timvandermeij I've decided to bundle both pdf.js 2.1 and the developer snapshot 2.2.199 with ngx-extended-pdf-viewer. So developers can choose freely between the stable production or the experimental developer version.

**Comment by stephanrauh** [comment]
Looking at the memory snapshots, I've noticed the memory is full of classes (as opposed to objects). 

Theory to put under test: Maybe calling `webViewerLoad()` creates these classes over and over again, although they are already in memory?

**Comment by stephanrauh** [comment]
Let's close the ticket for the moment. Recently, I haven't heard many complaints, so the library seems to be good enough. Of course, checking the memory footprint is a task that has to be repeated every once in a while.
