### ISSUE TITLE
Print prints an empty page (and sometime even forgets the first page)

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#170]
One of my test documents (https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/src/assets/pdfs/fancy.pdf) is displayed correctly, but looks a bit odd when printed. The first page is empty, because it is shoved below the image representing the second page. Plus, an empty third page is printed.

Maybe that's caused by Material Design, but the print shouldn't depend on which CSS framework is used.

**Comment by stephanrauh** [comment]
shipped with version 1.8.0-rc.0

**Comment by sathiyam-optisol** [comment]
Hi @stephanrauh 

Print click its showing the empty page  my config files are already sent this issue #172

<img width="740" alt="Capture12" src="https://user-images.githubusercontent.com/48469090/69735157-3e66b700-1156-11ea-8ad4-ee8008e8ac5b.PNG">

**Comment by stephanrauh** [comment]
@sathiyam-optisol Well, you've sent me a small part of your configuration. Most likely, your printing problems are related to the CSS code you're using. Currently, all I know is you're using Bootstrap. 

Most likely your CSS code hides the pages at print time. It's always difficult to hunt down this bug. I could help you if you'd send me a reproducer - i.e. a small, minimal, but complete program showing the problem without forcing me to install any third-party code.

**Comment by Sathiyamm** [comment]
I Used iframe so that time print is correclty working.
<img width="756" alt="Capture13" src="https://user-images.githubusercontent.com/30838274/69868127-dd162380-12ce-11ea-886b-40398346bcd3.PNG">


Use ngx-extended-pdf-viewer tag that print is showing empty.
I'm trying to  reproduce on stackblitz, but it throws an error "Error: window.webViewerLoad is not a function"   https://stackblitz.com/edit/angular-jxny3v

**Comment by stephanrauh** [comment]
Using an iframe is a clever way to solve the bug. You just have to be aware of the disadvantages of iframes.

As for Stackblitz: I love this platform and use it often, but it doesn't support editing the `angular.json`. No matter what you do, it won't load the additional scripts. What a pity!

**Comment by stephanrauh** [comment]
@sathiyam-optisol I've reported the bug to the Stackblitz team, using your example as a reproducer. So please don't modify it! :)

https://github.com/stackblitz/core/issues/700

**Comment by stephanrauh** [comment]
Version 9.0.0 is going to ship with a new set of CSS rules. Let's hope that solves all these nasty bugs.
