### ISSUE TITLE
Reduce the size of ngx-extended-pdf-viewer.mjs

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1705]
The file ngx-extended-pdf-viewer.mjs weighs in a 600 KB, at least in the showcase. Let's analyze why it's so big and what to do about it.

Ideas:

- [ ] check if tree-shaking works. For example, is the ngx-extended-pdf-viewer.service included in a bare-bone application that doesn't need it?
- [ ] make theming tree-shakeable (or, preferable, allow lazy loading). The two CSS themes weigh in a roughly 80 KB, each.

**Comment by majora2007** [comment]
Out of pure curiosity, were you able to find anything?

**Comment by stephanrauh** [comment]
Basically, I've decided to tackle this issue later. It doesn't seem to be urgent because the *.mjs file is still tiny compared to the JavaScript file it need to work. If developers have a problem with the initial load time, they can put ngx-extended-pdf-viewer into a module that's loaded lazily.

However, I still think it should be possible to do something about the CSS code. For example, removing them from the ngx-extended-pdf-viewer.module.ts and declaring them in the host module. That's another breaking change, so I'm reluctant to do this, but it's probably an option.

**Comment by majora2007** [comment]
Ahh, okay. I lazy load the module myself and really haven't noticed much issue, although it is a bit heavy, so more speed is always nice, but it is also a lot of complex code, so it's not something that can be that thin.

I haven't looked much at the css, but I also wonder if there are any savings as 80KB each seems like a lot. 

Keep up the good work, appreciate the response.

**Comment by stephanrauh** [comment]
Hm, while we're talking about it - Angular's budget feature might be a good reason to re-open this issue soon. However, in the short term, I'm trying to bring the number of open issues below ten and to keep it there. :)
