### ISSUE TITLE
Setting to load/render all the pages in the PDF on initial load without having to use preRendering() API

### ISSUE THREAD

**Issue by jimbarrett33** [stephanrauh/ngx-extended-pdf-viewer#1706]
**Is your feature request related to a problem? Please describe.**
My requirement is to be be able load the PDF and get at all form fields in the PDF on initial load but with paging I can only get the fields in the first couple of pages. Ultimately, I am trying to identify form fields in the PDF and to jump/scroll to them (or at least the page) by clicking on a field name (outside of the PDF viewer).

**Describe the solution you'd like**
A setting that, when the PDF loads, causes all pages to render and emit pageRendered() event for each page so that all the contents/ fields of the PDF can be read on initial load. I realize there would be performance implications for very large PDF's but this feature probably wouldn't be suitable for that use case.

**Describe alternatives you've considered**
I have used the prerendering API [https://pdfviewer.net/extended-pdf-viewer/prerendering](https://pdfviewer.net/extended-pdf-viewer/prerendering) but I can only get that to work with `pageViewMode="infinite-scroll"` and then I am left/stuck with a full/non-paged PDF view instead of a paged view within the PDF container. I still want the PDF to be within the PDF container so the user can scroll through pages.

I tried switching from `pageViewMode="infinite-scroll"` back to `pageViewMode="multiple"` in TS code via binding after I get all pages/fields from the preRender API but this doesn't work currently #1415.

Another way to describe the problems is that when `pageViewMode="multiple"` and I use the preRendering() API's, the call to `NgxExtendedPdfViewerService.currentlyRenderedPages()` returns ALL the pages in the PDF, for example 50, but I only get the `pageRendered()` and `annotationLayerRendered() events for the first 2 pages.

**Additional context**
Maybe there is another way to achieve what I need.  If so, help would be appreciated.

Great component BTW!

**Comment by stephanrauh** [comment]
In a nutshell, you (or I :) ) have to deactivate the cache. Or rather, cache eviction. At the moment, I don't know how to do this, but it's probably a change of the base library. If you're interested, you could help me by debugging my prerendering API and trying to find out where pdf.js implements cache eviction. But no obligation - it's slightly advanced code.

**Comment by jimbarrett33** [comment]
@stephanrauh Thanks for the quick reply. I can probably take a look next week. I'm currently prototyping a feature and use of this library. Not sure if this will be a show-stopper yet.

**Comment by stephanrauh** [comment]
The missing events are probably a side-effect of my tinkering with a low-level API without really knowing what I'm doing. Even so, it's strange.

A good starting point to investigate might be this line: https://github.com/stephanrauh/pdf.js/blob/1b931096b0c9678cea3cd2afc3d6f1389be6ba55/web/pdf_viewer.js#L506

You should also have a look at the `PdfPageViewBuffer` (https://github.com/stephanrauh/pdf.js/blob/1b931096b0c9678cea3cd2afc3d6f1389be6ba55/web/pdf_viewer.js#L128).

And maybe there's a very simple solution to getting an unlimited cache: try setting `pdfDefaultOptions.defaultCacheSize=1000000`.  I remember I've already increased this setting to 50. Mozilla's viewer ships with a cache size of 10.

**Comment by stephanrauh** [comment]
Another interesting line to investigate is this one:
https://github.com/stephanrauh/pdf.js/blob/1b931096b0c9678cea3cd2afc3d6f1389be6ba55/web/pdf_viewer.js#L1895

If you trick pdf.js into believing every page is visible, it'll render every page.

Maybe these limits may stop you - but you said your document isn't that big, so you're probably lucky:
https://github.com/stephanrauh/pdf.js/blob/1b931096b0c9678cea3cd2afc3d6f1389be6ba55/web/pdf_viewer.js#L70

**Comment by jimbarrett33** [comment]
@stephanrauh Thanks for the above. I will try to check it out your suggestions next week.

**Comment by stephanrauh** [comment]
@jimbarrett33 What's the current state of the art?

**Comment by stephanrauh** [comment]
As far as I remember, I've been working on the prerendering API to make it more reliable after you've opened the ticket. So updating the library might be worth a try.

Another interesting option is setting `pdfDefaultOptions.defaultCacheSize=1000`. That doesn't force preloading, but it prevents cache eviction.

**Comment by stephanrauh** [comment]
I'm afraid I'm still short of time, so I reluctantly close this ticket.
