### ISSUE TITLE
AnnotationLayer does not appear to be in the built PdfPageView type

### ISSUE THREAD

**Issue by korydondzila** [stephanrauh/ngx-extended-pdf-viewer#1711]
**Describe the bug**
Apparently `annotationLayer` exists on `PdfPageView`
![Screen Shot 2023-03-10 at 5 38 58 PM](https://user-images.githubusercontent.com/1796312/224441396-c84d0ac0-7dff-4258-afde-3b863992157c.png)

But it does not appear in the built type definition.
![Screen Shot 2023-03-10 at 6 00 27 PM](https://user-images.githubusercontent.com/1796312/224443927-d4af64b3-4dec-48a7-9759-dbc26631dfb9.png)
![Screen Shot 2023-03-10 at 5 59 51 PM](https://user-images.githubusercontent.com/1796312/224443881-70a62dae-6bf3-4a77-b5b9-29e8948fc842.png)

Though I do see that it exists in the code
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/62ff34ce91eb1302a0f88111b16ab98e0389e3d1/projects/ngx-extended-pdf-viewer/types/web/pdf_page_view.d.ts

**Version info**
- 16.2.5

**Desktop (please complete the following information):**
 - Browser Chrome

**Describe the solution you'd like**
Fix type definition.

**Comment by korydondzila** [comment]
So I realize that this is apparently in the type https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/62ff34ce91eb1302a0f88111b16ab98e0389e3d1/projects/ngx-extended-pdf-viewer/types/web/pdf_page_view.d.ts


But it doesn't appear to exist in the built version?
![Screen Shot 2023-03-10 at 6 00 27 PM](https://user-images.githubusercontent.com/1796312/224443927-d4af64b3-4dec-48a7-9759-dbc26631dfb9.png)
![Screen Shot 2023-03-10 at 5 59 51 PM](https://user-images.githubusercontent.com/1796312/224443881-70a62dae-6bf3-4a77-b5b9-29e8948fc842.png)

**Comment by stephanrauh** [comment]
The updated type definition has landed with version 17.0.0-alpha.3.
