### ISSUE TITLE
Pdf file is not showing in Internet explorer 

### ISSUE THREAD

**Issue by sathiyam-optisol** [stephanrauh/ngx-extended-pdf-viewer#172]
following changes made in my project
**Install the packages**
npm i ngx-extended-pdf-viewer --save
npm install pdfjs-dist

**Package.json**
<img width="247" alt="Capture2" src="https://user-images.githubusercontent.com/48469090/69621672-9376d000-1065-11ea-855e-bce5a5a59164.PNG">

**App.module.ts** 
`import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';`

**Angular.json**
<img width="417" alt="Capture3" src="https://user-images.githubusercontent.com/48469090/69621861-df297980-1065-11ea-8c0d-d8a63c2c1277.PNG">
<img width="330" alt="Capture4" src="https://user-images.githubusercontent.com/48469090/69621923-fe280b80-1065-11ea-983d-b0e868d0bae0.PNG">

pdfshow.html

 ```
<ngx-extended-pdf-viewer [src]="'../Downloads/FORMID-496299-1 (2).pdf'" useBrowserLocale="false" height="80vh">
                    </ngx-extended-pdf-viewer>
```

Pdfshow.ts 

```
import { defaultOptions } from 'ngx-extended-pdf-viewer';
...
.....
constructor(){
defaultOptions.workerSrc = './assets/pdf.worker-es5.js';
}
```

Its working fine chrome and edge. But not working IE11, Ipad
Chrome
<img width="891" alt="Capture7" src="https://user-images.githubusercontent.com/48469090/69627811-64fef200-1071-11ea-9b67-6fa41c287655.PNG">

IE-11 

<img width="882" alt="Capture5" src="https://user-images.githubusercontent.com/48469090/69627845-7516d180-1071-11ea-87aa-4706c43c7311.PNG">

Ipad
this error will be showing
![IMG_1174](https://user-images.githubusercontent.com/48469090/69636636-0dff1a00-107d-11ea-9f78-0f6173dec206.png)

Message:setting up fake worker failed cannot loading script at pdfjs worker-es5.js failed

And I **change the code** 
**Pdfshow.ts** 
```
 const _isIE11 = !!(<any>window).MSInputMethodContext && !!(<any>document).documentMode;
    defaultOptions.workerSrc = _isIE11 ? './assets/pdf.worker-es5.js' : './assets/pdf.worker.js';
```
 
That time not working chrome also 
<img width="883" alt="Capture8" src="https://user-images.githubusercontent.com/48469090/69633795-e907a880-1076-11ea-9fab-eb48dc68cc36.PNG">

Ipad also showing the same error

<img width="883" alt="Capture8" src="https://user-images.githubusercontent.com/48469090/69633795-e907a880-1076-11ea-9fab-eb48dc68cc36.PNG">

**Comment by sathiyam-optisol** [comment]
<img width="388" alt="Capture9" src="https://user-images.githubusercontent.com/48469090/69638828-7819be00-1081-11ea-9470-eff7839737b9.PNG">
 
I changed that **Angular.json**
This time **working fine** Chrome , Ipad .
But Not working IE-11
<img width="882" alt="Capture5" src="https://user-images.githubusercontent.com/48469090/69639004-c62ec180-1081-11ea-8260-a6d04e44bd31.PNG">

**Comment by stephanrauh** [comment]
OK, let's analyze this step-by-step:

Your package.json indicates you're adding the pdf.js distribution from npm. That won't work, for two reasons: I've updated the PDF viewer to pdf.js 2.3.200, and ngx-extended-pdf-viewer already brings it's own copy of pdf.js. Plus, this copy is a modified version of Mozilla's version. It contains several customizations for Angular.

So I suggest you remove the pdf.js copy from the package.json.

**Comment by stephanrauh** [comment]
Originally, you've already added both the ES5 version and the ES2015 version of the JavaScript files in the `angular.json`.

- Add the two files `pdf-es5.js` and `viewer-es5.js` if you need to support Internet Explorer.
- If you don't need IE11 support, add `pdf.js` and `viewer.js` instead. 

Adding both versions only confuses the PDF viewer.

**Comment by stephanrauh** [comment]
Using the browser selection (`const _isIE11 = ...`) is clever, but I'm not sure if it works. For the sake of simplicity, stick to the `*-es5` files if you need IE11 support. Usually you don't need to set `defaultOption.workerSrc` because it's found automatically (if you're using the standard folders).

**Comment by stephanrauh** [comment]
As a rule of thumb, I suggest you clone the showcase on your machine: https://github.com/stephanrauh/extended-pdf-viewer-showcase.

It's the reference implementation. Get the showcase up and running on your machine. I guess it'll support IE11 and iPad out-of-the-box.

After that, compare the sourcecode of the showcase with your project. Usually, the differences are in the `package.json` and the `angular.json`.

Hope that helps!

Best regards,
Stephan

**Comment by sathiyam-optisol** [comment]
I removed that angular.json and package.json
**angular.json**
<img width="624" alt="Capture11" src="https://user-images.githubusercontent.com/48469090/69700987-e3ab6c00-1111-11ea-82ff-0b18945359f7.PNG">

**package.json**
<img width="463" alt="Capture10" src="https://user-images.githubusercontent.com/48469090/69700954-caa2bb00-1111-11ea-83fa-5c8eb57ba5f2.PNG">

It's working Fine.
Thank you @stephanrauh
