### ISSUE TITLE
TextLayerBuilder attribute case error

### ISSUE THREAD

**Issue by productivityindustries** [stephanrauh/ngx-extended-pdf-viewer#1725]
`textlayer-rendered.ts` contains the interface `TextLayerBuilder`, which contains a `viewPort` attribute.

But when reacting to `textLayerRendered`, the passed event contains `source.viewport` (lowercase `P`)

**Comment by productivityindustries** [comment]
actually, by better looking at the code, event from pdf.js should get viewport with

```
event.source.viewport
```

, as `viewport` is a property of PDFPageView, not of TextLayerBuilder

**Comment by stephanrauh** [comment]
No idea what happened there. As you've mentioned, I've declared the wrong type three years ago. Adding insult to injury, the type generated automatically by webpack aren't as helpful as I expected.

I've added `viewport` to PDFPageView and deleted the `TextLayerBuilder` interface.

**Comment by productivityindustries** [comment]
i believe you still need an interface like textLayer builder, since PDFPageView also contains a `textLayer` attribute.

**Comment by productivityindustries** [comment]
see https://github.com/mozilla/pdf.js/blob/3903391f3cbed25806adc4a9874979f7725ec883/web/pdf_page_view.js#L827

**Comment by stephanrauh** [comment]
You're right. Version 16.2.15 fixes this.
