### ISSUE TITLE
Remove debug console logs from prod build

### ISSUE THREAD

**Issue by muuvmuuv** [stephanrauh/ngx-extended-pdf-viewer#1727]
**Describe the bug**
 
I have this console logs since the last update. Could you please remove all logs and put them behind a debug flag? We really would like to avoid any logs in our prod app to avoid exposing any lib information.

![Bildschirm­foto 2023-03-24 um 12 24 35](https://user-images.githubusercontent.com/11534760/227509270-72a26621-b48b-433c-8084-da4cf0fb3c11.png)

**Version info**
- 16.2.11

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]
 
**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug. It's always a good idea to start from a fresh, new project. There's a template project at https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template. A side effect is that writing a reproducer often helps you to find bugs of your code. This spares me the embarrassement of pointing our you bugs. More important, it saves me a lot of time. ngx-extended-pdf-viewer has become so popular that answering issues costs a lot of my spare time, so I appreciate your help.

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**

**Additional context**

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by stephanrauh** [comment]
Yes, you're right. You've run into an intermediate version. My build pipeline doesn't support server-side rendering for some reason, forcing me to publish new version just to be able to test them. That, in turn, resulted in forgotten debug code.

Version 16.2.14 is clean again, and it finally supports server-side rendering out-of-the-box.
