### ISSUE TITLE
window's default  Ctrl+F feature  is lost for the page having ngx-extended-pdf-viewer component

### ISSUE THREAD

**Issue by vineet-verma** [stephanrauh/ngx-extended-pdf-viewer#173]
**Issue- window's default  Ctrl+F feature  is lost**
html page having ngx-extended-pdf-viewer component loses windows's default ctrl+F feature. as soon as I press CTRL+F, pdf viewer's search is enabled to search inside the document but what about the rest of the page search? 
Please let me know if there is any way to disable search of ngx-extended-pdf-viewer component OR some other way to have both search.

**Comment by stephanrauh** [comment]
Try this:

```html
<ngx-extended-pdf-viewer
    [ignoreKeys]="['CTRL+F', 'CMD+F']"
    ...
```
Strictly speaking, it's enough to ignore `CTRL+F`. The other key combination, `CMD+F`, is to support Mac users.

There's also a live demo and documentation: https://pdfviewer.net/keyboard

Best regards,
Stephan

**Comment by vineet-verma** [comment]
Thanks its working.
