### ISSUE TITLE
Ngx Loading issue

### ISSUE THREAD

**Issue by Musthafafazil** [stephanrauh/ngx-extended-pdf-viewer#1734]
I have Two PDF File as Base64 and I have a page changing function in my code. At default, the first base64 given as input to the ngxcomponent  the file is loading with no issue but when i try to move to the second page the ngx component received the second base64 as input but the file is not loading. In the console i get the error like  
```
Cannot read properties of null (reading 'dispatch')  at NgxExtendedPdfViewerComponent.selectCursorToo
```

**Comment by Musthafafazil** [comment]
![Uploading Untitled.png…]()

**Comment by stephanrauh** [comment]
Like this one? It works on my machine, so I need a reproducer to help you. Or you compare your source code to my source code first: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/base64

https://pdfviewer.net/extended-pdf-viewer/base64

**Comment by solita-PerttuLe** [comment]
Same error happening here https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1654

**Comment by stephanrauh** [comment]
@Musthafafazil Can you give me more insight how to reproduce your bug, please? At the moment, I'm clueless. I don't want to let you down, but I don't know how to help you.

I'm closing the ticket now, but I'm still listening to the channel. Feel free to post anything that helps me to help you!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Most likely, you've run into a timing issue. pdf.js is highly asynchronously. That's annoying if you want to switch quickly between two pages, each of them featuring its own copy of ngx-extended-pdf-viewer. Sometimes, it happens that the component is still being destroyed while the second instance is already constructed. Unfortunately, there's nothing I can do about it. It's a architecture decision baked deep into pdf.js. I can add a safe navigation operator to the `selectCursorTool()` method, but that probably only causes the same error to pop up at another line.

Try opening the PDF viewer with a short delay. Maybe `[delayFirstView]="1000"` works. Alternatively, add an `ngIf="showPDFViewer"` to the `<ngx-extended-pdf-viewer>` line, declare the attribute as `public showPDFViewer=false`, and set it to true after a timeout in `ngOnInit()`:

```ts
setTimeout(() => this.showPDFViewer, 1000);
```
If this approach works, try to reduce the timeout to improve the user experience.
