### ISSUE TITLE
Cant hide header and footer when press print in IE

### ISSUE THREAD

**Issue by trongdn84** [stephanrauh/ngx-extended-pdf-viewer#174]
I have problem when I press print in IE 11 it have header and footer I want to remove it How do I can? I dont want to control it in Page setup of browser
![image](https://user-images.githubusercontent.com/55567700/69771075-0e52fe80-11be-11ea-824c-0d7f945573ea.png)
![image](https://user-images.githubusercontent.com/55567700/69771121-42c6ba80-11be-11ea-953b-0370a53c515b.png)

**Comment by stephanrauh** [comment]
No idea. It sounds like a printer driver setting. Check the "preferences" or the "options" tab.

Did you try to print the document using the pdf.js showcase? I bet the same happens there. https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by stephanrauh** [comment]
@trongdn84 I'm closing this ticket now after waiting two weeks. I can only guess that you've managed to solve the issue.
