### ISSUE TITLE
Binding from base64

### ISSUE THREAD

**Issue by troimaclure** [stephanrauh/ngx-extended-pdf-viewer#1760]
Hi, 👋
Me again :) 

- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
Nope
- Does the bug also happen on https://pdfviewer.net/simple?
Yep
- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.
Yep

**Describe the bug**
When i put base64 pdf on it, some elements not binding correctly
In my pdf i have some checkbox checked and it appeler not checked while open it. If i check in your viewee and save as base 64 and open in pdf js , i ts work. 
Its a read binding problem, not on writing. 

**Version info**
- Version of ngx-extended-pdf-viewer 17.0.0-alpha.4

**Demo PDF file**
[application (1).pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/11451176/application.1.pdf)

**Comment by stephanrauh** [comment]
By the look of it, you've prepared everything for me so I can hunt down the bug easily. Thanks! I'm afraid you'll have to wait nonetheless because currently I'm on vacation.

Just to make sure I've got you right: you're talking about the initial state of the checkboxes? And does the bug also appear if you don't set `[formData]`?

**Comment by troimaclure** [comment]
Hey, 

it's about the initial state of the checkboxes yep,

if you try to open the pdf in the https://mozilla.github.io/pdf.js/web/viewer.html you ll see some checkboxes are checked, but in https://pdfviewer.net/simple not. 
Maybe checkboxes default value configured in pdf make a mess. 
If i change checkboxes states in your library and save base64 and open it in pdf.js (or simple browser) , it's worked but not in your library => checkboxes states not binded at initial read. 

I didn't use [formData]. Only base64 simple load. 

Have nice vacation :)

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 17.0.0-alpha.5.

Enjoy!
Stephan

**Comment by troimaclure** [comment]
Thx a lot ! 
See you soon :)
