### ISSUE TITLE
Responsive design do not work

### ISSUE THREAD

**Issue by jesben** [stephanrauh/ngx-extended-pdf-viewer#1762]
`ngx-extended-pdf-viewer uses dynamic CSS rules to show as many buttons as possible in the toolbar. If there are too many buttons, they are shifted into the kebab menu on the right-hand side.`

https://pdfviewer.net/extended-pdf-viewer/mobile

Do not work in version 16.2.16 and 17

**Comment by stephanrauh** [comment]
You're right. How could that miss my attention? Thanks for pointing this out!

**Comment by Blunderchips** [comment]
> You're right. How could that miss my attention? Thanks for pointing this out!

It happens

**Comment by stephanrauh** [comment]
I've started to investigate the topic, but it puzzles me. It seems I've deleted a method call.  Thing is, I don't remember where I called the dynamic CSS adjustment. And how to find something that's gone at an unknown point in time?

**Comment by stephanrauh** [comment]
Please update to version 17.0.0-alpha.8 and tell me if it solves the issue.

@AlexanderFalconi I've just repaired a bug I've introduced when improving compatibility to server-side rendering. I've tested it as good as I can, but I'd appreciate your feedback, too. Does your application still run when you update to ngx-extended-pdf-viewer 17.0.0-alpha.8?

**Comment by AlexanderFalconi** [comment]
I just got around to doing this and it works, builds, and runs.

I don't know if its all in my head or not but it seems way faster.

**Comment by stephanrauh** [comment]
@AlexanderFalconi It's another topic, but did you also test server-side rendering? That's a feature I can't test easily.

**Comment by AlexanderFalconi** [comment]
Yes, this was in response to SSR. It's working right now on
ournevadajudges.com

**Comment by stephanrauh** [comment]
That's great news. Hooray!
