### ISSUE TITLE
Custom Search functionality input instead of the custom find bar

### ISSUE THREAD

**Issue by KhadijaSaoulajane** [stephanrauh/ngx-extended-pdf-viewer#1766]
I'm trying to implement a searchbar to be able to search in the document. I've read the documentation and saw the way to customize the findbar and not how to use a custom made find component. 

My search input is like this. what should I do in the searchPDF function to be able to search the document like the normal find input that is integrated in the library ? : 
  ```
<ion-searchbar  (ionChange)="searchPdf($event.target.value)"></ion-searchbar>

 <ngx-extended-pdf-viewer #pdfViewer [enablePrint]="false" [showBorders]="false"
                             [showOpenFileButton]="false" [showPagingButtons]="false" [showPresentationModeButton]="false"
                             [showPrintButton]="false" [showPropertiesButton]="false" [showRotateButton]="false"
                             [showSecondaryToolbarButton]="false" [showSidebarButton]="false" [showSpreadButton]="false"
                             [showZoomButtons]="false" [showDrawEditor]="false" [showTextEditor]="false"
                             [zoom]="'page-width'"
                             (pdfLoadingStarts)="changeIcons()"
                             [src]="pdfLink" [useBrowserLocale]="true"
    ></ngx-extended-pdf-viewer>
```

Thanks!

**Comment by stephanrauh** [comment]
Probably the easiest and most flexible solution is using the `NgxExtendedPdfViewerService`. I've documented it here: https://pdfviewer.net/extended-pdf-viewer/find.

**Comment by stephanrauh** [comment]
If my comment helps you, please tell me, so I know I can close the ticket.

Thanks in advance
Stephan

**Comment by KhadijaSaoulajane** [comment]
I've already read it and tried to implement it but I didn't manage to..
<img width="478" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/52927283/bf6ee211-7f7c-4e4a-a871-926dd82ac141">
What is the method that is called on this search bar ?

**Comment by KhadijaSaoulajane** [comment]
--

**Comment by stephanrauh** [comment]
At the moment, I can't run a test myself. However, there's the working showcase demo, and if I understand you correctly, it's similar to what you're trying to do. Have a look at these source codes - they might help you: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/find

**Comment by KhadijaSaoulajane** [comment]
Yes that's exactly what I based off my draft. and I get the error shown above

**Comment by stephanrauh** [comment]
Can you send me a reproducer project? That's a complete project showing the error, but without forcing me to install any additional stuff like databases. I'm afraid I can't have a look at it this week, but I can try (without promises - private life can be demanding!) to inspect your reproducer project next week.

**Comment by stephanrauh** [comment]
Please update to version 17.0.0-alpha.9. I haven't published it yet, but I'm probably going to publish it this weekend. The new version fixes your bug.

Best regards,
Stephan
