### ISSUE TITLE
Error on closing modal with content ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by tiesgr** [stephanrauh/ngx-extended-pdf-viewer#1767]
I am calling a pdf document using ngx-extended-pdf-viewer in angular everything works fine until I close the modal. I get the following error

```
ERROR TypeError: Cannot read properties of null (reading 'removeEventListener')
    at Object.unbindWindowEvents (viewer-3.5.531.min.js:44:33497)
    at ngx-extended-pdf-viewer.mjs:4133:46
    at timer (zone.js:2405:41)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26237:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at invokeTask (zone.js:487:34)
    at ZoneTask.invoke (zone.js:476:48)
    at data.args.<computed> (zone.js:2385:32)
```
I tried to create a function while closing the modal in order to unsubscribe from pdf functionality.

 ```ts
Modaldismiss(){
    if (this.pdfViewerSubscription) {
      this.pdfViewerSubscription.unsubscribe();
      this.pdfViewerSubscription = null;
    }
    this.modalService.dismissAll();
      // Unsubscribe from the PDF viewer subscription
  }
```
And calling it into my html file with the following code

```html
<ng-template #pdfModal let-modal>
              <div class="modal-header">
                <h5>Country: <br />{{ file.countryName }}</h5>
                <h5 class="modal-title" id="pdfModalLabel">
                  File Name: <br />{{ file.certName }}
                </h5>
                <button
                  mat-mini-fab
                  color="warn"
                  class="close"
                  aria-label="Close"
                  (click)="Modaldismiss()"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <ngx-extended-pdf-viewer
                  [src]="previewUrl"
                  [height]="'900px'"
                  [useBrowserLocale]="true"
                  [textLayer]="true"
                  [showHandToolButton]="true"
                >
                  ></ngx-extended-pdf-viewer
                >
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  mat-flat-button
                  color="warn"
                  (click)="Modaldismiss()"
                >
                  Close
                </button>
              </div>
            </ng-template>
```
but this did not work too.

Any ideas from where to start I would be grateful.

Thank you in advance,

Nick

**Comment by tiesgr** [comment]
Hello Stephan,
I also wonder if there is a bug regarding dom because the modal creates a new element. The pdf viewer is being called inside the modal as the content.
So when I close it I have implemented as you have seen a function to unsubscribe from any functionalities that come with the viewer.
I have read the documentation and I conclude to unsubscribe from the pdf viewer's subscriptions but this didn't solve the error. 
Do you know if there is any subscription that hungs regarding the removeeventviewer while a pdf element is being created in the dom? 
The error is triggered when I close the modal. 
I will review again my code if I am calling it twice.
Either way at least my app continues working any time I open and closing a new modal.
Thank you for your reply.
Best regards
Nick

**Comment by tiesgr** [comment]
Hello Stephan,

I have set [minifiedJSLibraries]="false" from debugging It is like when closing the modal to call the 
unbindWindowEvents() twice.

I have reviewed my code and I am not doing something more than this
TS FILE
```
Modaldismiss() {
    if (this.pdfViewerSubscription) {
      //Unsubscribe from the PDF viewer subscription
      this.pdfViewerSubscription.unsubscribe();
      this.pdfViewerSubscription = null;
      (<any>window).PDFViewerApplication.unbindEvents();
      (<any>window).PDFViewerApplication.unbindWindowEvents();
      (<any>window).PDFViewerApplication.close();

      this.modalService.dismissAll();
    }
  }
```

html file
```
 <div class="modal-body">
                  <ngx-extended-pdf-viewer
                    [src]="previewUrl"
                    [height]="'900px'"
                    [useBrowserLocale]="true"
                    [textLayer]="false"
                    [showHandToolButton]="false"
                    [minifiedJSLibraries]="false"
                  >
                  </ngx-extended-pdf-viewer
                  >
 </div>
```
Can I try to add to the library a null-safety operator to see if this will work?

Thank you 
Best regards

**Comment by stephanrauh** [comment]
Yeah, sure. Go for it! The good news is I'm back, so I can care about your bug myself, but if you send me a pull request, I'd be very happy. I want this library to be a community effort!

**Comment by stephanrauh** [comment]
No problem. As it turns out, my latest change caused the bug. Too bad you ran into it!

**Comment by stephanrauh** [comment]
Please update to version 17.0.0-alpha.7 and tell me if it solves the issue.

Thanks in advance,
Stephan

**Comment by tiesgr** [comment]
Dear Stephan,

I have updated to 17.0.0-alpha.7 and it solved the issue.
Thank you!

Best regards
Nick
