### ISSUE TITLE
Loading pdfjs for direct usage (implement an optional custom loader)

### ISSUE THREAD

**Issue by MikeDabrowski** [stephanrauh/ngx-extended-pdf-viewer#1769]
Hi, I migrated from ng2-pdf-viewer and pdfjs-dist and while the 'viewer' part worked out of the box, the pdfjs-dist part of my code does not. I need to check the number of pages of the uploaded pdf, so I was using pdfjs-dist.getDocument(blob) and then numPages.

To do so here, I need to get a hold on pdfjs fork. I read 2 issues where you suggest to load them using script tag. However when I do so and attempt to call getDocument Im getting MIME error. I read in 3rd issue that the file may be missing. And it is, but it seems to be a name typo.

pdf-3.5.533.worker.min.js vs pdf-3.5.533-worker.min.js <- difference being a dash not a dot

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/17836911/45f97b09-65f7-411f-99e2-e4b4f21a47ab)

and my loading function was taken from one of issues here:

```typescript
private loadPdfJs() {
    // @ts-ignore had to add this because it threw an error
    if(!window['ngxZone']) {
      // @ts-ignore
      window['ngxZone'] = this.ngZone;
    }
    // @ts-ignore
    if (!window['pdfjs-dist/build/pdf']) {
      const assets = pdfDefaultOptions.assetsFolder;
      const versionSuffix = getVersionSuffix(assets);
      const script = document.createElement('script');
      script.src = this.locationService.normalize(
        assets + '/pdf-3.5.533.min.js',
      );
      script.type = 'text/javascript';
      script.async = true;
      document.getElementsByTagName('head')[0].appendChild(script);
    }
  }

```

Could anyone help me load and use the pdfjs ?

**Comment by stephanrauh** [comment]
My library already has a lot of history, so maybe the hints you've found aren't useful nowadays. I don't think you have to load pdf.js yourself. NgxExtendedPdfViewer loads it lazily and my fork adds a number of improvements, so it's better to stick to it.

To access the viewer, use this line:

```typescript
const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
```

`numPages` is part of the `PdfDocumentProxy`. I can't test it now, but I suppose you can access it like so:
```ts
PDFViewerApplication?.pdfDocument?.numPages;
```

BTW: If my hint helps you, please tell me, so I know I can close the issue.

Best regards,
Stephan

**Comment by MikeDabrowski** [comment]
I can try it tomorrow but the case is that I render the pdf in a different place than where I need the numPages. And both have to work after reload.

I was looking at `PDFViewerApplication` but it assumes that pdf is loaded using your library (and therefore rendered already). My case where I need numPages is just on the upload, to determine the way we process pdfs. Its not even the same pdf we render. So your hint wont help

**Comment by stephanrauh** [comment]
I see. That's inconvenient. pdf.js pollutes the global namespace. It adds global variables to the `window` object, so I don't know how to loads to different copies of pdf.js.

Maybe you can copy the code I'm using to load my fork of pdf.js. My viewer only loads pdf.js if it's not already in memory, so this approach might work. Here's the first line of the code loading pdf.js: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/5e46ab1d94d10242c92609dc39df483d39f2c4ad/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L969

**Comment by MikeDabrowski** [comment]
I am fine with loading your fork so that should prevent having different copies. Maybe your code could be rearranged so that it exposes the 'loading' tools and also have some kind of retention mechanism - to avoid reloading if already loaded.

For now I started cherry-picking your loader to see if it does the job. I have to say this lib is impressive amount of work, and got some features we might need in the future. For now I only need numPages and a way to render the pdf, which are also possible using plain pdfjs-dist. 

For references:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/606
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/799

**Comment by stephanrauh** [comment]
@MikeDabrowski What's your current state of the art?

As for the retention mechanism: it's already there:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/5e46ab1d94d10242c92609dc39df483d39f2c4ad/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L972
(and similarly in line 927 for the viewer*.js file).

I can make it more flexible if you give me a hint what precisely you need.

As for exposing the loading mechanism: sure, why not. How fast do you need it? Any suggestion what the API might look like?

**Comment by MikeDabrowski** [comment]
Current state of affairs is that I used raw pdfjs for now (needed to fix it fast), but i saw what features are coming for us in the future and this lib will certainly be revisited.

The retention mech you linked is in the component itself and I'm not sure if this is the best place.

My thinking is that if you expose the loader and thus making the pdfjs available in any place in the app (not only if the component has been loaded), the component may not be the best place to load the lib anyway. 

I'd move it to a dedicated service, and set this service to load with the module maybe. 

Maybe module could expose forRoot/forFeature to load pdfjs for whole app or from feature module.

And to answer how quickly: this year would be nice, no pressure on my end.
I could even try to make PR if pdf features will happen sooner in our project, and I'm going to need this lib.

**Comment by stephanrauh** [comment]
That's a generous deadline. :) 

Using a service sounds promising. I don't want to force developers to modify their module files, so I need to think about how to make it optional. Plus, I want to support standalone components. Sounds like a good reason to start a deep dive into the new standalone components!

**Comment by stephanrauh** [comment]
BTW, pull requests are always welcome.

**Comment by stephanrauh** [comment]
I'm afraid I'm still short of time, so I reluctantly close this ticket.
