### ISSUE TITLE
Word search that contains special characters

### ISSUE THREAD

**Issue by helthbrazil** [stephanrauh/ngx-extended-pdf-viewer#177]
When I search for a word in Portuguese such as "projecao" the library should also search for "projeção" ignoring special characters when searching, just like the google chrome pdf reader does.

This would facilitate search applications where the alphabet uses these special characters.

**Comment by stephanrauh** [comment]
Sorry for answering late - I've spent the last couple of days in the hospital. Currently, I've got no idea if I can activate lexical search, but I'll have a look at it.

**Comment by helthbrazil** [comment]
> Sorry for answering late - I've spent the last couple of days in the hospital. Currently, I've got no idea if I can activate lexical search, but I'll have a look at it.

Thanks. I hope your health improves

**Comment by stephanrauh** [comment]
I've just published version 1.8.0 featuring the advanced search. Note that there's a small breaking change: now you need to add `loadash.deburr` to your package.json (`npm install loadash.deburr --save`).

There's a live demo at https://pdfviewer.net/find.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/3045767/70946663-dc63e800-2057-11ea-9c32-0229d3e5e275.png">

<img width="255" alt="image" src="https://user-images.githubusercontent.com/3045767/70946719-fd2c3d80-2057-11ea-94a8-7b68d4979974.png">

**Comment by helthbrazil** [comment]
Thank you very much. Congratulations

**Comment by stephanrauh** [comment]
@helthbrazil One last thing: I need a portuguese translation of "ignore accents and diacritics". What do you suggest?

**Comment by helthbrazil** [comment]
"Ignorar acentuação"

**Comment by stephanrauh** [comment]
Obrigado! Your translation will ship with the next version.
