### ISSUE TITLE
Differences between e-books

### ISSUE THREAD

**Issue by turingtext-Shuang** [stephanrauh/ngx-extended-pdf-viewer#1770]
I have compiled this list based on Alibaba's e-book and I'm not sure if it will be helpful to developers.

https://docs.google.com/spreadsheets/d/1yNQvYMpU4BEEiMPw02beXQaLTqgKE_0US5XMziAONP0/edit?usp=sharing

alibaba e-book url: https://static.alibabagroup.com/reports/fy2022/ar/ebook/en/17/index.html

**Comment by stephanrauh** [comment]
Nice! I can't promise I'll address your list in the short term, but in the mid-to-long term, your list might be useful to fix the annoying bugs you've reported and to add missing features. Thanks!

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.
