### ISSUE TITLE
Events for opening and closing the search form area.

### ISSUE THREAD

**Issue by YurchenkoAndrew** [stephanrauh/ngx-extended-pdf-viewer#1773]
Good day.
Please tell me the events of opening and closing the area of the search window.
I need to add a close button to the search area. Template overridden, button added.
But I can't find what event to trigger to close the area with the search form.
Thanks in advance.
![2023-05-30_16-59-52](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/19759393/a2fb9d8f-3db8-4e81-9717-64362605b232)

**Comment by stephanrauh** [comment]
Currently, there are no such events. I can build them for you. I guess it makes sense to add attributes like

- [ ] `[(findDialogVisible)]`
- [ ] `[(propertiesDialogVisible)]`

In the meantime, you can close the find dialog by programmatically clicking the magnifying-glass button:

```ts
document.querySelector('#viewFind').click();
```

**Comment by stephanrauh** [comment]
Your feature has landed with version 17.2.0.

Enjoy!
Stephan
