### ISSUE TITLE
render fails when using esbuild builder 

### ISSUE THREAD

**Issue by suryapratap** [stephanrauh/ngx-extended-pdf-viewer#1774]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
   - No

- Does the bug also happen on https://pdfviewer.net/simple?
   - No 

- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.

   - Attached a reproduction using angular esbuild
[ngx-extended-pdf-viewer-esbuild.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/11620991/ngx-extended-pdf-viewer-esbuild.zip)

**Describe the bug**

- Follow instructions at https://pdfviewer.net/extended-pdf-viewer/simple to create a simple demo

- change the builder to esbuid

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/956538/cd4b3852-7b71-4cd7-a8b4-ee49481adf34)

**Version info**

- Version of ngx-extended-pdf-viewer:
    -  16 and higher

**Comment by stephanrauh** [comment]
Are you talking about this error message?

```
Uncaught SyntaxError: import declarations may only appear at top level of a module [viewer-3.5.534.min.js:1](http://localhost:4200/assets/viewer-3.5.534.min.js)
```

If so, I'm confused. It seems esbuild adds an import statement to my JavaScript files - but that's bad because it doesn't play well with the way I load the files. Any idea how to prevent esbuild from modifying my JavaScript files?

**Comment by stephanrauh** [comment]
As it turns out, this is an Angular bug. Please update your project to Angular 16.0.4, and everything works like charm. I've uploaded an example project to https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue1774.

**Comment by stephanrauh** [comment]
BTW, thanks for making me aware of esbuild. Currently, it's very early-bird, forcing developers to modify their project in unexpected places. Nonetheless, it's blazing fast. I'm looking forward to the final version!

**Comment by surya-ascent-portal** [comment]
Aah... I would have held on for a couple of days more if I knew the latest update will solve the issue. Thanks for the update. The viewer is really wonderful, really appreciate the effort you put into it.

**Comment by suryapratap** [comment]
Aah, I would have waited a couple of days more if I knew the latest angular update will resolve the issue. Really appreciate the time you put in this project. It's a wonderful library to work with.
