### ISSUE TITLE
Sidebar is not visible/toggled when clicking on "show document outline" button in sidebar

### ISSUE THREAD

**Issue by nibinki** [stephanrauh/ngx-extended-pdf-viewer#178]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?: no
- Does the bug also happen on https://pdfviewer.net/simple? : no 

**Describe the bug**
In my application  i enabled these configurations
```html
  <ngx-extended-pdf-viewer #pdfViewer
                                [showPropertiesButton]=false
                                    [showRotateButton]=false
                                    [showOpenFileButton]=false
                                    [showPrintButton]=false
                                    [showSecondaryToolbarButton]=false
                                    [showDownloadButton]=false
                                    [showBookmarkButton]=false
                                    [showSidebarButton]=true
                                   
                                    [(sidebarVisible)]="sidebarVisible"
                                [src]="pdfURL"
                                [page]="pdfPage"
                                [zoom]="auto"
                                [showSidebarOnLoad]=false
                                [handTool]=false
                                useBrowserLocale="true">
                                </ngx-extended-pdf-viewer>
```
initially sidebar is not visible and not loaded and when the screen is expanded i am setting  `this.sidebarVisible = true;` and page loads perfectly as shown below

![image](https://user-images.githubusercontent.com/36858559/70072976-0e1f8c80-161e-11ea-91d5-10b99ea7c6a5.png)

when i click on "show document outline" in sidebar,  sidebar is not visible or toggled and i have to again click on show sidebar button to make it visible

![image](https://user-images.githubusercontent.com/36858559/70073020-27283d80-161e-11ea-92bb-8914db0c09da.png)

i observed that if i am not using  `[(sidebarVisible)]="sidebarVisible"` in configuration then this issue is not coming ..but my requirement is to hide sidebar when screen size is less and show it fully when screen size is higher . Please help

Also is that possible to show document outline first instead of Thumbnails 

**Version info**
- Version of ngx-extended-pdf-viewer :  "ngx-extended-pdf-viewer": "^1.8.0-rc.0",
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files) default files

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] : 78

**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**

**Additional context**

**Comment by stephanrauh** [comment]
Probably your issue is a combination of two things:

- You've set `[showSidebarOnLoad]=false`. This isn't in line with `[(sidebarVisible)]="sidebarVisible"`.
- During the initialization of the PDF viewer, I confused `showSidebarOnLoad` and `sidebarVisible`. Version 1.8.0 fixes this. Plus, `showSidebarOnLoad` now is officially deprecated in favor of `sidebarVisible`.
