### ISSUE TITLE
showFindButton is not respected on initial load.

### ISSUE THREAD

**Issue by ManuelRauber** [stephanrauh/ngx-extended-pdf-viewer#1787]
**Describe the bug**
1. Go to https://pdfviewer.net/extended-pdf-viewer/hiding-buttons
2. Take a look at the default options and that "showFindButton" is turned off
3. Take a look at the preview: find button is still visible.

The issue is in `pdf-find-button.component.html`:

```html
<button type="button" [class.invisible]="!textLayer" [class]="showFindButton | responsiveCSSClass: ''" id="viewFind"
```

When `showFindButton` is turned off, `responsiveCSSClass` will set CSS class `invisible`, but `[class.invisible]` will remove it again because the text layer is turned on.

Toggling `showFindButton` will make the button disappear, because `[class.invisible]` is not re-evaluated again due to no change to `textLayer`.

**Expectation**
`showFindButton` hides the button no matter if `textLayer` is turned on/off.

**Comment by stephanrauh** [comment]
Thanks a lot for your detailed description and your analysis. It helped me to understand the issue quickly!

**Comment by stephanrauh** [comment]
To my surprise, this ugly hack solves the issue:
```html
<button
  type="button"
  [class]="textLayer ? '' : 'invisible'"
  [class]="showFindButton | responsiveCSSClass : ''"
  class="toolbarButton"
  id="viewFind"
  ...
```
However, adding the `class` attributes, two of them being `[class]` (in brackets) - well, that doesn't feel right to me. Do you happen to know if Angular support this officially?

**Comment by ManuelRauber** [comment]
> To my surprise, this ugly hack solves the issue:
> 
> ```
> <button
>   type="button"
>   [class]="textLayer ? '' : 'invisible'"
>   [class]="showFindButton | responsiveCSSClass : ''"
>   class="toolbarButton"
>   id="viewFind"
>   ...
> ```
> 
> However, adding the `class` attributes, two of them being `[class]` (in brackets) - well, that doesn't feel right to me. Do you happen to know if Angular supports this officially?

Uhm, I'm not sure about that. However I'd prefer not to have a hacky solution. :)

**Comment by stephanrauh** [comment]
Version 17.0.1 includes my quick hack. It should fix your issue, but I'll keep this issue open until I've implemented a bullet-proof and future-safe solution.

**Comment by ManuelRauber** [comment]
> Version 17.0.1 includes my quick hack. It should fix your issue, but I'll keep this issue open until I've implemented a bullet-proof and future-safe solution.

Yep, the quick hack fixes the issue. :)

**Comment by stephanrauh** [comment]
Version 17.1.0 ships with a non-hacky solution.
