### ISSUE TITLE
Can we customise the html view of attributes/features provided?

### ISSUE THREAD

**Issue by vijay-flexiloans** [stephanrauh/ngx-extended-pdf-viewer#179]
Firstly would like to praise this package, it's very helpful.

I wanted to know wether we can change the position of buttons, etc. Like for my use case i want to show zoom option on extreme right, is it possible to do so? if yes how?

ps- i tried editing the DOM using developer tools, it obviously works there, is there a way to give custom html/css?

**Comment by stephanrauh** [comment]
Yes, we can! I was playing with this idea for a couple of weeks myself. I‘d also like to add a plugin system for custom buttons.

Give me some time: currently, I‘m sick, so there‘s little progress apart from answering a ticket every once in  a while. But I’ll be back soon!

**Comment by stephanrauh** [comment]
The feature has landed with version 2.0.0-alpha.18. I'm sure there's a lot that can be improved, so I'll probably add more options over time. Currently, you can modify the toolbar, the menu, and the findbar.
