### ISSUE TITLE
Please remove all debug log messages

### ISSUE THREAD

**Issue by ManuelRauber** [stephanrauh/ngx-extended-pdf-viewer#1790]
In the code there seem to be some debug log messages. Please remove them to not spam the console. Or turn them into real log messages using your logger.

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/1ecd421d6adf9c689589b5fa8970e669f0c6fb79/projects/ngx-extended-pdf-viewer/src/lib/sidebar/pdf-sidebar/pdf-sidebar-content/pdf-sidebar-content.component.ts#L132-L136

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/740791/d4355169-393d-40cb-be2f-48dbf6eb5ace)

**Comment by stephanrauh** [comment]
Oops. Sure thing. I'm on it!

**Comment by stephanrauh** [comment]
Please update to version 17.0.1. It fixes your issue. Actually, it fixes both of your issues, but I'll keep #1787 open because my quick workaround feels just to "hacky".
