### ISSUE TITLE
Disable scroll when editing

### ISSUE THREAD

**Issue by BossuytWannes** [stephanrauh/ngx-extended-pdf-viewer#1796]
I'm looking for a way to disable scrolling on the PDF when draw or edit mode is enabled.
Giving weird results when using on tablet.

When you start drawing lines, the pdf is not staying at the same position.
This results a line from left top corner to point where you started drawing.

**Comment by stephanrauh** [comment]
Yeah, that makes sense. I've observed a similar problem some time ago, but I thought to have solved it. Do you happen to know if I can reproduce your bug with a trackpad on my laptop?

**Comment by BossuytWannes** [comment]
I was unable to reproduce this on a laptop with trackpad.
Can only reproduce this on a mobile device where you zoom into the pdf and start drawing.

**Comment by stephanrauh** [comment]
OK. That's inconvient, but that's the way it is.

@calixteman Did you already use your free ink tool on a tablet or a smartphone? @BossuytWannes reports that the screen scroll when you start painting. Did you already solve this problem?

**Comment by stephanrauh** [comment]
@BossuytWannes It's always painful for me to test stuff on a real mobile device. The connection between my laptop and my iPad is flaky. So maybe I should simply ask you first.

I've found two solutions that look promising. First, there's the CSS solution. When activating the paint mode, I add a CSS class to the `.viewer` div containing this rule:
```CSS
.no-scroll {
  overflow: hidden;
}
```
The other option is to suppress the `touchmove` gesture using JavaScript:
```JS
docuement.querySelector(".viewer").addEventListener('touchmove', function (event) {
  event.preventDefault();
}, { passive: false });
```
Do you happen to know if one of these solutions does the trick? Can you fire up your debugger and test the idea?

**Comment by BossuytWannes** [comment]
Does the draw button have a specific id or class to know when active?

**Comment by BossuytWannes** [comment]
@stephanrauh seems to work with the workaround you provided.

`  onPagesLoaded(event) {
    const button = document.getElementById('editorInk');
    button?.addEventListener('click', () => {
      console.log('clicked');
      this.editing = !this.editing;

      const div = document.getElementById('viewer');
      if (this.editing) {
        div?.addEventListener('touchmove', this.disableScroll, true);
      } else {
        div?.removeEventListener('touchmove', this.disableScroll, true);
      }
    });
  }`
  
  `  <ngx-extended-pdf-viewer #pdfViewer *ngIf="contentLoaded"
  [showSecondaryToolbarButton]="false"
  [base64Src]="document" useBrowserLocale="true"
  [minifiedJSLibraries]="false"
    [mobileFriendlyZoom]="true"
    (pagesLoaded)="onPagesLoaded($event)"
  ></ngx-extended-pdf-viewer>`

**Comment by calixteman** [comment]
Are you able to reproduce your issue when opening a pdf in Firefox ? or with https://mozilla.github.io/pdf.js/web/viewer.html ?
If yes you should file a bug either on [Bugzilla](https://bugzilla.mozilla.org/) or on [pdf.js](https://github.com/mozilla/pdf.js/issues).
If I remember correctly, I had some similar issues when I implemented the editing feature and the solution was to use `touch-action: none;` to prevent them.

**Comment by BossuytWannes** [comment]
In browser I have no issues, the implementation is in native browsers from smartphones. I've implemented this library in an Ionic project, can only reproduce this issue when viewing on mobile device.

As stated in my previous comment, I was able to use a workaround to disable it, thanks for the help.

**Comment by stephanrauh** [comment]
I've added `touch-action: none` to the `#viewerContainer`. Now it works properly.

I've also added a CSS class called `.ngx-extended-pdf-viewer-prevent-touch-move`. It's added to the document as long as one of the editors is active. This way I managed to fix a weird scrolling issue of my showcase. I've messed up my flex layout, so the entire page used to start scrolling. Adding a `touch-action: none` rule fixed this, with one exception: when I start painting, the page scrolls to the bottom. That's why in the showcase, painting always starts with a vertical line.

However, that's a problem of the showcase, so I'm going to close this issue soon.

Along the way, I've added the event `(annotationEditorModeChanged)` that fires after activating or hiding one of the editors.

**Comment by stephanrauh** [comment]
@BossuytWannes You can remove your work-around after updating to version 17.4.0.
(At the time of writing there's only a 17.4.0-alpha.0, but it does the trick just as well).

**Comment by stephanrauh** [comment]
Version 17.4.0 and the documentation have landed.

**Comment by BossuytWannes** [comment]
@stephanrauh is it possible that this issue has slipped back in on version 21.4.6?
Only have this if you put your browser on mobile mode.
