### ISSUE TITLE
 Consider logLevel when using autoheight warning.

### ISSUE THREAD

**Issue by 0biJanKenobi** [stephanrauh/ngx-extended-pdf-viewer#1798]
Is it possible to query the log level when generating the warning for autoheight?

if (this.logLevel >= VerbosityLevel.WARNINGS) {
            console.warn(
              "The height of the PDF viewer widget is zero pixels. Please check the height attribute. Is there a syntax error? Or are you using a percentage with a CSS framework that doesn't support this? The height is adjusted automatedly."
            );
}

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/245bc99e46b6d73cfb296ae113f220c7fe543858/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1308

**Comment by stephanrauh** [comment]
Yes, of course. I'm not sure it's a good idea to ignore the message, but "greater or equal than warning" is fine by me.

Do you know a use-case where this message occurs? Until now, I've only seen it when I did a mistake.

**Comment by stephanrauh** [comment]
Your enhancement will ship with the next release (probably later this week).

Enjoy!
Stephan
