### ISSUE TITLE
Karma tests failing as v17.3.0

### ISSUE THREAD

**Issue by Blunderchips** [stephanrauh/ngx-extended-pdf-viewer#1799]
As of bumping to v17.3.0 our karma tests are failing to run. We have not changed any configuration on our side with the update. We use firefox as a runner. We don't actually test anything with the library other than a `it should create` on a component.

**Describe the bug**
- Karma tests are failing

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/c3a97dad-d05a-4d3b-a71c-36e422b947a8)

**Version info**
- Version of ngx-extended-pdf-viewer: **v17.3.0**

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/076b4a0b-3301-467e-8640-ef3253f4b1e5)

Not sure if there is anything else I can pass along?

**Comment by stephanrauh** [comment]
My Playwright tests still work, so I'm a bit puzzled. I don't have a clue where the exception is raised.

- Do you Karma tests still work with version 17.2.0?
- Can you see the stacktrace? If so, please set the attribute `[minifiedJSLibraries]="false"`. 

I've found and fixed a mistake, but if accesses `PDFViewerApplicationOptions`, not `PDFViewerApplication`, so I doubt updating to version 17.3.1 will help.

**Comment by Blunderchips** [comment]
> My Playwright tests still work, so I'm a bit puzzled. I don't have a clue where the exception is raised.
> 
> * Do you Karma tests still work with version 17.2.0?
> * Can you see the stacktrace? If so, please set the attribute `[minifiedJSLibraries]="false"`.
> 
> I've found and fixed a mistake, but if accesses `PDFViewerApplicationOptions`, not `PDFViewerApplication`, so I doubt updating to version 17.3.1 will help.

Yes worked on 1.7.2. We use renovate to manage our dependencies so the only change in PR with failing tests is a version bump for this library. I added in the flag you mentioned, above but we are not getting any other info. Given them another read could it be failing destruction on clean up? I see that the same test passes and then fails on `destroy`.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/b4ba81d0-e1ae-4738-91c5-adc42b5fdf1d)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/eabe0e50-5d44-455c-911d-1418789d38a4)

**Comment by stephanrauh** [comment]
Makes sense. Please try version 17.3.2. It should fix the issue.

Unfortunately, I haven't been able to reproduce your issue with my Playwright tests yet. I've seen two different errors, though, and at least one of them is a thing of the past now.

**Comment by Blunderchips** [comment]
Hi @stephanrauh yes as of `17.3.2` our tests are passing again. Thank you for the assistance!

**Comment by stephanrauh** [comment]
I've found and fixed some other errors that happen when destroying the PDF viewer early.
