### ISSUE TITLE
Get annotations like html links

### ISSUE THREAD

**Issue by salserofada** [stephanrauh/ngx-extended-pdf-viewer#180]
Hi,
I'd like to know if there is a way to get annotation like html links from text layer with the viewer ?
Thank's a lot for the done job!!!

**Comment by stephanrauh** [comment]
@salserofada Sorry for answering late - I've been a couple of days in the hospital. May I ask why you've closed the ticket? Did you solve the issue?

Truth to tell, I didn't even understand your question. Probably it's a feature of PDF I've never seen. Can you explain it again, please? And does ngx-extended-pdf-viewer support it?
