### ISSUE TITLE
Enable developers to populate the sidebar with custom content

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1803]
The sidebar of the PDF viewer of the The Royal Society shows innovative uses of the sidebar. ngx-extended-pdf-viewer should support stuff like this, too!

https://royalsocietypublishing.org/doi/epdf/10.1098/rsos.230376

<img width="1736" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/5fd78031-aec6-41e2-bd49-83164fb6476b">

<img width="1736" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/5018ae23-2c48-4e4d-94f6-af266ac57cfc">

<img width="1736" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/47a9d043-60aa-4f31-ba55-0c4981cbad93">

**Comment by Tweniee** [comment]
@stephanrauh i would be good if good to have a issue template so that everyone will be able to understand the current plus the expected behavious of the issue, and how to solve it(Optional).

this will build out community too.
whats say?

**Comment by stephanrauh** [comment]
@Tweniee Actually, there is an issue template, but I ignored it when I created this particular ticket because I already knew what I wanted to achieve. :) 

In this particular case, I saw a web page that implemented a custom sidebar. So I thought it might be a good idea to allow developers to define their own side bar and populate it with whatever content they like. Images, data from a database, whatever. Giving developers maximum flexibility is always a challenge, so this ticket is currently a dreaming-about-a-bright-future ticket. I don't see I can implement it anytime soon. 

A part of it has to be implemented in the core library, so I'd be surprised if the community manages to send me a solution. I'd love it, but I haven't seen a community PR involving changes in pdf.js yet. Please prove me wrong!

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.
