### ISSUE TITLE
Unable to write with editor

### ISSUE THREAD

**Issue by asadmkhan** [stephanrauh/ngx-extended-pdf-viewer#1813]
I am using the editor feature, but it doesn't write anything on screen.

Angular Version 15.2.9
"ngx-extended-pdf-viewer": "^18.0.0-alpha.3"

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/28774748/460242c0-0719-4ff8-8806-ba1cb37555d0)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/28774748/0cf92470-b009-40c1-9784-347aa4b113f9)

**Comment by stephanrauh** [comment]
That's unexpected. It's hard to diagnose your bug with so little information, so I'm giving you some pointers allowing you to dig deeper yourself:

- First of all, visit https://mozilla.github.io/pdf.js/web/viewer.html and tell me if the draw feature works over there.
- Probably it's just a sloppy choice of words: you say "it doesn't write", but you've selected the draw tool, so it's more like a pen.
- Does the draw editor work on your machine when you visit my showcase https://pdfviewer.net?
- Is there an error message in your browser's console?
- Just a wild shot: does it work with other documents? For example, one of the documents you can download from my showcase?
- Another wild shot, if everything else fails: what does your DOM look like? Each page of the PDF file is a canvas, and on top of the canvas there should be a div bearing the CSS class `annotationEditorLayer`, as shown in the screenshot:
<img width="1565" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/5eccbc71-db9c-4ed3-95e0-ee801730eef6">

**Comment by asadmkhan** [comment]
> That's unexpected. It's hard to diagnose your bug with so little information, so I'm giving you some pointers allowing you to dig deeper yourself:
> 
> * First of all, visit https://mozilla.github.io/pdf.js/web/viewer.html and tell me if the draw feature works over there.
> * Probably it's just a sloppy choice of words: you say "it doesn't write", but you've selected the draw tool, so it's more like a pen.
> * Does the draw editor work on your machine when you visit my showcase https://pdfviewer.net?
> * Is there an error message in your browser's console?
> * Just a wide shot: does it work with other documents? For example, one of the documents you can download from my showcase?
> * Another wide shot, if everything else fails: what does your DOM look like? Each page of the PDF file is a canvas, and on top of the canvas there should be a div bearing the CSS class `annotationEditorLayer`, as shown in the screenshot:
> 
> <img alt="grafik" width="1565" src="https://user-images.githubusercontent.com/3045767/254985464-5eccbc71-db9c-4ed3-95e0-ee801730eef6.png">

First of all, visit https://mozilla.github.io/pdf.js/web/viewer.html and tell me if the draw feature works over there. **YES**

Probably it's just a sloppy choice of words: you say "it doesn't write", but you've selected the draw tool, so it's more like a pen.
**Pen is shown but it does not draw/write anything**

Does the draw editor work on your machine when you visit my showcase https://pdfviewer.net/?
**YES it works!**

Is there an error message in your browser's console?
**There is no error message just one warning "The height of the PDF viewer widget is zero pixels. Please check the height attribute"**

Just a wide shot: does it work with other documents? For example, one of the documents you can download from my showcase? 
**It doesnt works in my application, on other live demos it works**

Another wide shot, if everything else fails: what does your DOM look like? Each page of the PDF file is a canvas, and on top of the canvas there should be a div bearing the CSS class annotationEditorLayer, as shown in the screenshot:
**DOM is different, some elements inside annotationEditorLayer are missing, please check attachd screen shots
i only have 1 data-editor-rotation** 

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/28774748/cd743f0a-20ff-47b3-92bc-4c247cd52ffa)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/28774748/a5fd6148-ec0b-43c7-a208-1161084832b2)

**Comment by stephanrauh** [comment]
OK. Now I'm officially puzzled! Maybe it's a CSS problem:
- Check the size and the position of the .annotationEditorLayer div. It should cover the page.
- Check the opacity. Maybe you're writing with invisible ink.
- Or you're drawing in the background. What happens if you increase the z-index or delete the other layers in the developer tools?
- You can also check the size and position of the data-editor-rotation div. It should be a box around your drawing, allowing to move and to resize it.

**Comment by stephanrauh** [comment]
Any progress?

**Comment by asadmkhan** [comment]
> 

The error was in my stylesheet, its fixed now, thanks for the hint

**Comment by stephanrauh** [comment]
Hooray!
