### ISSUE TITLE
Unable tu see a Portfolio PDF document

### ISSUE THREAD

**Issue by plemond10** [stephanrauh/ngx-extended-pdf-viewer#1815]
We have create a Portfolio PDF which contains many PDF.

The viewer does not show the content of any PDFs

**Comment by stephanrauh** [comment]
Tell me more. I'm happy to help you, but I need to know more details. You know, at the moment you've simply told me that it doesn't work on your machine. I can't see your source code, so I'm clueless.

**Comment by stephanrauh** [comment]
I didn't hear from you for several days, so I assume you've manage to solve the bug. I'm closing the ticket now.

**Comment by plemond10** [comment]
actually I don’t have the proper tools to share or make a document for testing. I’ll look foward et comme back when I figure howEnvoyé de mon iPhoneLe 25 juill. 2023 à 16:16, Stephan Rauh ***@***.***> a écrit :﻿
I didn't hear from you for several days, so I assume you've manage to solve the bug. I'm closing the ticket now.

**Comment by stephanrauh** [comment]
D'accord!
