### ISSUE TITLE
Default Property Pane always Visible

### ISSUE THREAD

**Issue by Creature123** [stephanrauh/ngx-extended-pdf-viewer#1817]
**I need your help!**
I have just followed the tutorial to install the package. I have followed all the steps mentioned in https://pdfviewer.net/extended-pdf-viewer/getting-started for Angular App.

But the default property dialog with  Subject, and Keywords are always getting opened.
When I try to cancel the / Close the dialog I am getting this Error

Uncaught (in promise) Error: The overlay is currently not active.
    at OverlayManager.close (viewer-3.5.549.min.js:44:73356)
    at PDFDocumentProperties.close (viewer-3.5.549.min.js:44:85510)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1725:16)

My Angular Version is : 14.0.0

**Comment by stephanrauh** [comment]
That's very strange. Did you add the PDF viewer to an existing project? My recommendation is to start with a fresh project, install ngx-extended-pdf-viewer, and confirm that it works. After that, you can use this fresh project to compare it to your existing project. Usually, this helps people to find the problem quickly.

BTW, Angular 14 should be fine.

To get a fresh new project with a PDF viewer, do this:

- Create a new project with `ng new my-favorite-project`
- `cd my-favorite-project`
- `ng add ngx-extended-pdf-viewer` (and accept all the defaults)
- replace the content of `app.component.html` with `<app-example-pdf-viewer></app-example-pdf-viewer>`
- `ng s -o`

If you're still stuck, don't hesitate to reach out to me. However, I need more details to help you. I suspect you've got a CSS problem. The error message says that the property dialog is not visible, but you say it is visible indeed, so probably the dialog is shown accidentally. Custom CSS sometimes does that.

**Comment by Creature123** [comment]
Hi Stephan,
Your suspect is correct! I am trying to use your package in an existing  Application Since I got a new requirement from the client. I have checked with a fresh project, and the package works as expected.
In the existing project apart from **ngx-extended-pdf-viewer**, the following packages are already in use :
1. ng-bootstrap/ng-bootstrap : 13.1.0
2. bootstrap: 5.2.3
3. font-awesome: 4.7.0
4. ngx-bootstrap: 5.2.0
5. rxjs: 7.5.0

Since I don't have any requirement to show the property dialog, is there any way to close this component call from your code?

**Comment by stephanrauh** [comment]
To be honest, I doubt the dialog is open. I plan to implement an attribute like `[(propertiesDialogVisible)]`, but it wouldn't help you because you'd just run into the error message you've already shown me.

If it's open, there's an additional attribute in the DOM:
![grafik](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/ce397e8a-2507-4050-a4dc-a3500c5bb9d5)

You can hide the dialog with a CSS rule. However, I suspect that Bootsstrap has a CSS rule that shows the dialog accidentally. Try to find the offending CSS rule and overwrite it.

**Comment by stephanrauh** [comment]
Any progress?

**Comment by stephanrauh** [comment]
I didn't hear from you for a while. I'm closing the ticket now.
