### ISSUE TITLE
PDF file does not load on the first attempt but loads successfully on reloading the page

### ISSUE THREAD

**Issue by scry-UrjitDesai** [stephanrauh/ngx-extended-pdf-viewer#1820]
Hey, I have made a custom Angular component that renders an ngx-extended-pdf-viewer component. 
This component fetches a URL and is supposed to display the corresponding PDF. The issue I am facing is that it does not load the PDF correctly on the first go but when I refresh the page, the PDF is loaded correctly. 

Sometimes it gets loaded on the first try and sometimes it does not.

Parent component code:
 
```
<app-custom-pdf *ngIf="dataLoaded" [documentId]="documentID"> </app-custom-pdf>
```

Custom component HTML:
```
<ngx-extended-pdf-viewer
  #pdfViewer
  [(src)]="pdfSrc"
  [(page)]="page"
  pageViewMode="multiple"
  (pdfLoaded)="onPdfLoaded($event)"
  (pageRendered)="onPageRendered($event)"
  useBrowserLocale="true"
  [delayFirstView]="3000"
></ngx-extended-pdf-viewer>
```

Custom component TypeScript:

```
async ngOnInit(): Promise<void> {
    await this.getPdfDocument();
  }

  async ngOnChanges(changes: SimpleChanges) {
    console.log('on changes= ', changes);
    if ('documentId' in changes) {
      await this.getPdfDocument();
    }
  }

async getPdfDocument() {
    console.log('this.documentId= ', this.documentId);
    try {
      const pdfDataResponse = await this.documentService.getDocumentPdfbyId(
        this.documentId
      );
      const blob = this.base64toBlob(pdfDataResponse.data, 'application/pdf');
      setTimeout(() => {
        this.pdfSrc = blob;
      }, 1000);
    } catch {
      //error
    }
  }
```

As you can see I already have tried using [delayFirstView]="3000" and a setTimeout() way, but this does not seem to work. Any help is appreciated. Thank you!

ngx-extended-pdf-viewer Version: "18.0.0-alpha.3"

**Comment by stephanrauh** [comment]
You don't need `[delayFirstView]`. I should remove this properties. It just survived because developers never throw anything away.

I don't spot any obvious error in your code (but maybe that's because it's late in the evening). However, here's a working example of how to implement your feature: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/blob

BTW, you don't have to convert Base64 to a blob. You can also user the `[base64Src]` attribute (as shown here: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/base64).

**Comment by scry-UrjitDesai** [comment]
I am also using another library (ng2-pdfjs-viewer) to render a pdf on some other route before this. Could this be the issue?

**Comment by stephanrauh** [comment]
Well, maybe. I think ng2-pdfjs-viewer runs in an iFrame, so it shouldn't pollute the global namespace, but I'm not sure.

**Comment by stephanrauh** [comment]
In any case, both libraries use different version of pdf.js, so incompatibilites aren't surprising.

**Comment by stephanrauh** [comment]
Any progress?

**Comment by scry-UrjitDesai** [comment]
Yes, it was because of using 2 different libraries. It worked perfectly when I removed the pdf component being displayed by the other library.

**Comment by stephanrauh** [comment]
Good to know. I really thought the iFrame approach allows ng2-pdfjs-viewer to exist peacefully with my library. It's a bit sad to learn that it doesn't.
