### ISSUE TITLE
page label not updated

### ISSUE THREAD

**Issue by patelsumit5192** [stephanrauh/ngx-extended-pdf-viewer#1821]
HTML 
```
<ngx-extended-pdf-viewer #pdfViewer
             [customToolbar]="multiToolbar"
             [textLayer]="true"
             [(zoom)]="zoomingScalingVal"                                   
             [src]='pdfBlobUrl'>
</ngx-extended-pdf-viewer>
 <ng-template #multiToolbar>
<pdf-page-number id="pageNumber"></pdf-page-number>
<pdf-next-page id="next"  ></pdf-next-page>
<pdf-previous-page id="previous" ></pdf-previous-page>
</ng-template>
```

I have added 3 buttons(page number, previous, next) on my HTML side. when I press the next or previous button, the page is changed but the pagelabel is not updated in Pagenumber.

can you provide me with a working sample?

**Comment by stephanrauh** [comment]
Drop the id from `<pdf-page-number>`. That should do the trick. `<pdf-page-number>` contains an input field with the same id, and pdf.js is confused by the duplicate id.

**Comment by stephanrauh** [comment]
BTW, if you want to implement your own page label component, you can use `[(page)]` and `[(pageLabel)]` to retrieve the page number and label in Angular.

**Comment by patelsumit5192** [comment]
Yup,it's working fine.
