### ISSUE TITLE
Mousewheel zoom not working in iframe

### ISSUE THREAD

**Issue by jcerar** [stephanrauh/ngx-extended-pdf-viewer#1830]
When ngx-extended-pdf-viewer is embedded in an iframe any zooming performed with the mousewheel zooms the parent html page instead of the pdf document inside the iframe.
This is evident in the [side by side demo](https://pdfviewer.net/extended-pdf-viewer/side-by-side). 

Loading https://mozilla.github.io/pdf.js/web/viewer.html into an iframe does not display this behavior.

**Comment by stephanrauh** [comment]
Oops. I didn't expect that. Strange! Maybe it's even a feature - or rather, an unintended side-effect of a feature: some time ago, I was asked to zoom only if the mouse is inside the PDF viewer. The original pdf.js viewer catches every mousewheel even, ngx-extended-pdf-viewer does not. Maybe the iframe is considered to be outside, so the event is deliberately ignored.

During the next two weeks (or so) I'm in a digital detox phase. In other words, more likely than not, I won't fix your bug as fast as usual. Please apologize the inconvience!

**Comment by stephanrauh** [comment]
Actually, in the side-by-side demo the mouse wheel doesn't zoom at all, neither the entire document nor the PDF document.

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 18.0.0-beta.4.

**Comment by jcerar** [comment]
Nice job, thanks!
