### ISSUE TITLE
Warning: TT: undefined function: 32

### ISSUE THREAD

**Issue by JanBuerger** [stephanrauh/ngx-extended-pdf-viewer#184]
I always get a console log when I open a pdf file with chrome.
"Warning: TT: undefined function: 32"

It seems to be a known Issue:
https://github.com/mozilla/pdf.js/issues/3768#issuecomment-36468349

Is there a way to suppress these warnings and just show real errors since I can not do anything about it?

**Comment by stephanrauh** [comment]
With version 1.8.1, I've improved the messages. I've also introduced the parameter `logLevel`. Setting
```html
<ngx-extended-pdf-viewer logLevel="0" ...>
```
removes the error messages from the console window.

**Comment by vedantgour** [comment]
I am facing same issue and I am not able to access toolbar

**Comment by stephanrauh** [comment]
@vedantgour You are facing which issue? And what's your problem with the toolbar?

If you're referring to the `TT: undefined function: 32` message, don't ask me. I don't know what this means, and it's out of my scope. I assume you see the same message in Firefox (or the pdf.js showcase https://mozilla.github.io/pdf.js/web/viewer.html). If so, please open a ticket at the pdf.js project (https://github.com/mozilla/pdf.js/issues).
