### ISSUE TITLE
Hey stephanrauh! I see the drag-drop of the original pdfJs can be flexibly resized for both height and width but in ngx-extended-pdf-viewer I see it only reszie the width of the image! Do you have a fix for this?

### ISSUE THREAD

**Issue by nguyenvanbinh31012001** [stephanrauh/ngx-extended-pdf-viewer#1848]

**Comment by stephanrauh** [comment]
Sounds like a duplicate of #1824. Is that correct?

**Comment by Congchuabongbong** [comment]
> Sounds like a duplicate of #1824. Is that correct?

That's right! Do you have any solution for this problem yet?

**Comment by nguyenvanbinh31012001** [comment]
Do you have a solution for this problem?

**Comment by stephanrauh** [comment]
Version 18.0.0-beta.5 is going to solve the problem. As usual, no promises, but I suppose I'm going to publish the new version this week-end.

**Comment by nguyenvanbinh31012001** [comment]
thank you my friend!

**Comment by Congchuabongbong** [comment]
Hi StepPhanrauh, is there any way i can get all the lists of stamEditor, inkEditor, textEditor! I want to manage it when the user deletes or adds and retrieves their list!
