### ISSUE TITLE
Prevent pageRendered event after zoom action

### ISSUE THREAD

**Issue by cleanguy025** [stephanrauh/ngx-extended-pdf-viewer#1849]
**Version**: 15.2.2
In the demo [(https://pdfviewer.net/extended-pdf-viewer/pages-loaded)](https://pdfviewer.net/extended-pdf-viewer/pages-loaded) I see the pageRendered event was triggered after zoom action. Is there any way I can prevent this event ?

Or how can I keep the page's width and height value when I zoom in/out browser ?

**Comment by NgTienToan** [comment]
same problem !!!

**Comment by stephanrauh** [comment]
Why do you consider it a problem? Zooming requires the PDF viewer to render the page again. In a nutshell, that's precisely what zooming does: it shows the page in a different resolution. So it's logical that the render events are triggered. What's wrong with that?

**Comment by cleanguy025** [comment]
I'm using dynamic components via ViewContainerRef.createComponent (page is hostView ). So when the render events are triggered, the viewContainer changes. All components I created were lost.

So I consider how I can prevent this event when the page is in a different resolution.
