### ISSUE TITLE
Custom toolbar error!

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#1852]
There is something wrong in the custom toolbar! I am using ngx-extended-pdf-viewer version 18.0.0-beta.5 but cannot use the functions when custom toolbar! So, I see in your example that is also not working!
https://pdfviewer.net/extended-pdf-viewer/custom-toolbar

**Comment by Congchuabongbong** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/344fcb05-0987-4f31-95c8-ce1a55e30ab5)

**Comment by stephanrauh** [comment]
Oops. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
Version 18.0.0-beta.6 fixes the bug.

Enjoy!
Stephan

**Comment by Congchuabongbong** [comment]
thanks bro!
