### ISSUE TITLE
Drawing issue

### ISSUE THREAD

**Issue by BossuytWannes** [stephanrauh/ngx-extended-pdf-viewer#1853]
When drawing on a pdf, sometimes the lines don't show.
The color of the line is black when drawing, once you release the line disappears.

If you zoom, sometimes the lines reappear on certain zoom levels.
If I send the base64 back to my API to create the pdf, the lines do show on the generated PDF.

The viewer is shown on a mobile device (ipad).

**Comment by stephanrauh** [comment]
@BossuytWannes I believe that's a problem of the base library. Can you reproduce the bug on https://mozilla.github.io/pdf.js/web/viewer.html? It might also be a CSS problem, but you say "sometimes", so I don't believe that.

@Calixteman Does this ring a bell? Did you encounter disappearing lines in the ink editor before?

**Comment by stephanrauh** [comment]
BTW, if you want me to do something about this ticket, please send me a reproducer. You know, I can't fix a but I've never seen.

Thanks in advance
Stephan

**Comment by calixteman** [comment]
Can you reproduce in Firefox in using the link above or with the build-in pdf viewer ?
Can you reproduce in Chrome with the link above ? 
Can you check how it behaves on Windows ? Mac ? Linux ?
A screenshot could be helpful.

**Comment by stephanrauh** [comment]
@BossuytWannes In this particular case, a short video might be even more helpful than a screenshot. Plus a look into the console window. Does it show any error message?

**Comment by calixteman** [comment]
I just tried on an ipad (5e generation and version 15.4) in using https://mozilla.github.io/pdf.js/web/viewer.html in Safari and it wfm.

**Comment by BossuytWannes** [comment]
Will try to provide the additional data next week.

**Comment by stephanrauh** [comment]
Any news? I'll close the ticket now, but once you send me new insight, I can open it again.
