### ISSUE TITLE
Update PDF.js 

### ISSUE THREAD

**Issue by peopledrivemecrazy** [stephanrauh/ngx-extended-pdf-viewer#1854]
My app relies on this bug fix: https://github.com/mozilla/pdf.js/issues/16863

Thanks.

**Comment by stephanrauh** [comment]
You may be lucky. Chances are your bugfix is already included in the bleeding-edge branch of version 18.0.0-beta.5. If not, it's going to be included soon - but I can't promise a precise delivery date, because I'm busy these days. It may be anthing from later this evening to three weeks.

**Comment by peopledrivemecrazy** [comment]
Thank you for your quick response,

I am on `18.0.0-beta.5`. This change isn't patched into this release.

**Comment by stephanrauh** [comment]
Did you check the bleeding edge branch? But you're right, it's likely I updated pdf.js after releasing the new version.

**Comment by stephanrauh** [comment]
Please check out version 18.0.0-beta.6. You can use the stable branch of pdf.js: I've bumped up the version after noticing that Mozilla published the 3.10 version this week-end.

Enjoy!
Stephan

**Comment by peopledrivemecrazy** [comment]
Woohoo! Thank you.
