### ISSUE TITLE
Something went wrong when i click two times on print pdf! 

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#1857]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/6b19c794-5f33-4e64-8668-0927c41b05d9)
The first time I press the print function then I cancel it and the next time I press it it doesn't show the message preparing even though it still shows previerw but it throws an error like picture!

**Comment by stephanrauh** [comment]
Yes, that's a bug I observed myself, too. At the time, I put it on the big pile of tasks, because the PDF file still prints. It's just the progress indicator that's missing. But you're right, the pile of unfinished task has become a lot smaller now, so it's time to address these things, too.

**Comment by stephanrauh** [comment]
I believe an optimization I did three years ago backfired. Starting with version 18.0.0-beta.8, the error is gone.
