### ISSUE TITLE
How to manage stamEditor, inkEditor, textEditor?

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#1858]
Hi StepPhanrauh, is there any way i can get all the lists of stamEditor, inkEditor, textEditor! I want to manage it when the user deletes or adds and retrieves their list!

**Comment by Congchuabongbong** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/39f71cce-d068-43b5-a059-4bf1312f23c4)
With this information how can I get the source of the image

**Comment by stephanrauh** [comment]
I don't know how to pass the image. I'll dig into the code sooner or later, but with low priority. My `addEditorAnnotation()` method does not allow you to add the image (yet). 

During the next few months - probably until end of Oktober - I'm short of time. So I invite you to send me a pull request. I believe all you need to know to implement the feature is in the vicinity of this line:

https://github.com/stephanrauh/pdf.js/blob/325c39b469115b17d9ddb8cb1f7c452e77f65328/src/display/editor/stamp.js#L115

**Comment by stephanrauh** [comment]
Please follow the discussion at #1868 - I'm going to track progress regarding the images over there.

To dos left:
- [ ] document `PdfViewerService.getSerializedAnnotations()`

**Comment by Congchuabongbong** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/124a657a-79ea-4ab1-9b58-20395884c084)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/76718b9c-8e7e-4ff7-8ed7-796bd78b6fbf)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/12121dcd-234f-448c-8c25-c35c588dd845)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/c7b592c0-4942-48dc-8d9a-44ceb0a4a6bc)

**Comment by Congchuabongbong** [comment]
I have done that!

**Comment by stephanrauh** [comment]
You've done what? I can only guess: you've managed to insert the image? If so, how did you do it?
