### ISSUE TITLE
Remove await import from viewer.min.js

### ISSUE THREAD

**Issue by jpike88** [stephanrauh/ngx-extended-pdf-viewer#1864]
This import is triggering an issue with the vite bundler used in angular 17.

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/865818c1ef3c4c0e926b5b8741ee90a1b0577990/projects/ngx-extended-pdf-viewer/assets/viewer-3.10.543.js#L1752C7-L1752C40

https://github.com/vitejs/vite/discussions/5690

It would be good to maybe remove that import line somehow, instead of waiting for vite to upstream a fix to angular cause they're clearly taking ages to do it.

Current workaround is that on post install I do a sed command to turn that `await import` to `console.log`

**Comment by stephanrauh** [comment]
That makes sense. I'm busy these days, but I'll fix this before publishing version 18. If I get it correctly, the "await import" statement isn't used anywhere in active code. It's only used by debug code.

**Comment by stephanrauh** [comment]
Your bugfix is going to land soon with version 18.0.0-beta.8 or 18.0.0 (if I decide to publish the final version today).

**Comment by jpike88** [comment]
working, thank you!

**Comment by stephanrauh** [comment]
I've updated the source code of version 17 without releasing it yet. The bugfix is going to land next time I release a version 17.
