### ISSUE TITLE
How to insert/drag and drop an image with ngx-extended-pdf-viewer?

### ISSUE THREAD

**Issue by donascimentomarcelo** [stephanrauh/ngx-extended-pdf-viewer#1868]
I'm trying to insert or drag and drop an image on my PDF. I've found a way to import images via options, and it'd work perfectly if I could do the same thing dragging and dropping.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/20614813/b931a58e-c1e2-44ea-8cc6-ace734fd72da)

As you can see, the QR Code number one, I did drag and drop, however, I cannot attach it to my PDF and get the coordinates.
The QR Code number two I used the import option, where I imported the image to my PDF and I could get the coordinates from there.

I thought I could use the "addEditorAnnotation" command to add an image to my PDF, like that:

```typescript
const drawing: ImgEditorAnnotation = {
      annotationType: 15,
      img: "/assets/myImage.jpeg" 
      opacity: 1,
      paths: [... ],
      pageIndex: 0,
      rect: [...],
      rotation: 0,
    };
this.pdfViewerService.addEditorAnnotation(drawing);
``` 

It would resolve my issue, but I could not find any interface to pass an image path as a parameter. 

Is there another way to drop my image on the PDF and get the coordinates of its position?

**Comment by stephanrauh** [comment]
I don't know how to pass the image. I'll dig into the code sooner or later, but with low priority. My `addEditorAnnotation()` method does not allow you to add the image (yet). 

During the next few months - probably until end of Oktober - I'm short of time. So I invite you to send me a pull request. I believe all you need to know to implement the feature is in the vicinity of this line:

https://github.com/stephanrauh/pdf.js/blob/325c39b469115b17d9ddb8cb1f7c452e77f65328/src/display/editor/stamp.js#L115

**Comment by stephanrauh** [comment]
I'm afraid I'm still short of time, so I reluctantly close this ticket.
