### ISSUE TITLE
Custom build works in test project but not in bigger production project.

### ISSUE THREAD

**Issue by fi4sk0** [stephanrauh/ngx-extended-pdf-viewer#1871]
**Describe the bug**
Sorry, not actually a bug, but a cry for help. I'm completely puzzled

I built ngx-extended-pdf-viewer using a custom version of pdf.js, following exactly the steps in https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md
This did work and I can `npm install` the package into another angular test project using `npm install ../pdf/ngx-extended-pdf-viewer/dist/ngx-extended-pdf-viewer`. Using it in the test project also works but installing it into my actual production project, the console is spammed with:

```
../../pdf/ngx-extended-pdf-viewer/dist/ngx-extended-pdf-viewer/fesm2020/ngx-extended-pdf-viewer.mjs:460:13-27 - Error: 
export 'ɵɵresetView' (imported as 'i0') was not found in '@angular/core' 
(possible exports: ANALYZE_FOR_ENTRY_COMPONENTS, APP_BOOTSTRAP_LISTENER, APP_ID, APP_INITIALIZER, ApplicationInitStatus, ApplicationModule, ApplicationRef, Attribute, COMPILER_OPTIONS, CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrategy, ChangeDetectorRef, Compiler, CompilerFactory, Component, ComponentFactory, ComponentFactoryResolver, ComponentRef, ContentChild, ContentChildren, DEFAULT_CURRENCY_CODE, DebugElement, DebugEventListener, DebugNode, DefaultIterableDiffer, Directive, ElementRef, EmbeddedViewRef, ErrorHandler, EventEmitter
``` 
(the list goes on)

and compilation fails.

**Version info**
- Custom version based on 18.0.0-beta.6

So this is me actually just looking for pointers. My changes in pdf.js and the resulting package of ngx-extended-pdf-viewer do work, but only in an otherwise empty test project. It fails to compile (npm start) on my actual, bigger project and this is leaving me puzzled. I updated all the angular libraries to the same versions as in my test project, also making sure to remove .angular, node_modules and package-lock.json and reinstalling everything.

Removing the locally installed package and installing ngx-extended-pdf-viewer from npmjs (npm install ngx-extended-pdf-viewer) resolves the issue, but obviously I don't have the needed changes I've made.

Thanks for reading!

**Comment by fi4sk0** [comment]
Additional info:
I installed from npm and replaced the files with the ones from the dist/ folder of my custom build and this works. So probably it’s a webpack issue or my project setup is flawed. So feel free to close this issue, but I’m still very much interested on how to actually resolve this.

keep up the great work @stephanrauh !

**Comment by stephanrauh** [comment]
This sounds like an Ivy issue. Error messages containing Greek characters usually mean that you're using an Ivy library in a pre-Ivy project. Converting your production project to Ivy should do the trick.

Sometimes you can't update to the Ivy compiler. However, in 2023, this should be a thing of the past. At least, I hope so. As to my (limited) experience, embracing the Ivy compiler does not cause compatibility problems. Just give it a try!

If you're stuck with the old compiler for some reason, you need to go back to version 10.5.0. That's the last version supporting both rendering engines.

**Comment by stephanrauh** [comment]
As for the custom build of pdf.js: I recommend using my fork instead of Mozilla's fork. I've added quite a few customizations and bug fix, so I'd be surprised if ngx-extended-pdf-viewer runs flawlessly on a stock pdf.js.

Here's the address of my fork: https://github.com/stephanrauh/pdf.js/

**Comment by stephanrauh** [comment]
I'll keep the issue open for a while. Please tell me if my hints solve your issue, so I know I can safely close the ticket.

**Comment by fi4sk0** [comment]
Hi @stephanrauh , thanks for you answer! I did use your fork of pdf.js 

I'm on Ivy (Angular 16 and i didn't opt-out) and I since your package works flawlessly when I install it using `npm install ngx-extended-pdf-viewer` and still works when I just copy the files my custom `dist/ngx-extended-pdf-viewer` folder into the already existing `node_modules/ngx-extended-pdf-viewer` (i know, bad practice, just for testing), I assume it has something to do with the symlinks created by installing local packages or with my project setup. 

Also also ran into problems because of too many watched files, which is a webpack issue, so this all tells me I'm doing something wrong on my side and ngx-extended-pdf-viewer was just the one thing too much that made my setup break. Anyhow, I'm still thankful for any advice, but feel free to close this issue and thanks again @stephanrauh !

**Comment by stephanrauh** [comment]
When developing ngx-extended-pdf-viewer, I'm using your bad practice, too. :) The only problem I observed is it doesn't play well with modern Angular's caching. Plus, Hot Module Reloading is broken.

Your talking about Webpack, and I'm curious: are you using a custom Webpack configuration? The last time I saw such a thing was when I evaluated JHipster last year. Most of the time, stock Angular does an impressive job.

**Comment by fi4sk0** [comment]
> Your talking about Webpack, and I'm curious: are you using a custom Webpack configuration?

No, nothing special. A while ago I had to increase the `fs.inotify.max_user_watches`, but that was pretty much the only thing. 

But since we you mentioned Angular caching
My development process is really clumsy: I make changes to `mypdf.js`, execute `updateMozillasPdfViewer.sh`, execute `npm run showcase`, run `npm pack` in the `dist/ngx-extended-pdf-viewer` folder, reinstall the viewer locally in my project (using the tar.gz output of npm pack) check my changes only to find out that I can't see my changes, delete `.angular`, delete `node_modules`, reinstall, forget half of the things I should have done, reinstall Ubuntu, change the office and then it works. 

Sorry, just ranting, but do you have advice on how to do this more efficiently? I'm basically just hacking some things into the `pdf_find_controller`, so a shortcut would be great!

**Comment by stephanrauh** [comment]
I feel you. That's one of the reasons why my showcase still uses Angular 15. The other reason is that Angular 16 ceases to support flex layout.

When testing an Angular 16 project, I added deleting the `.angular` folder to my build script. The other difference to your approach is that I don't use symlinks. I understand npm offers decent support for symlink, but I couldn't wrap my head around it, so I was happy to learn that copying the binaries into the `node_modules` folder does the trick, too.

These days, my workflow simply consists of typing `npm run full` and brewing and drinking a cup of coffee because it takes so long. :)

**Comment by fi4sk0** [comment]
@stephanrauh what do you think about not copying pdf.js into the ngx-extended-pdf-viewer project, but keeping it separate during development. Instead, you could dynamically load the viewer from localhost:8888/.../viewer.js from the running grunt process of pdf.js. 

Part of that would be to incorporate the showcase into the ngx-extended-viewer workspace so you end up with two running processes:
- the grunt process that keeps hosting an updated version of viewer.js and 
- ng serve to host the ngx-extended-pdf-viewer alongside with the showcase

I noticed that you're adding an zone.runOutsideAngular to the viewer file, .. so that probably won't be easy in the proposed environment, but it might work without, but somewhat slower..? What do you think?

**Comment by stephanrauh** [comment]
That's an interesting idea. The browser will reject port 8888 because of the CORS protection, but I guess we can work around this limitation by setting up a `proxy.conf` file.

You're right, the `runOutsideAngular` bit is only a performance optimization. Plus, it simplifies the stack traces. Even so, I'm frustrated that zone.js wraps itself around almost every asynchronous method call, including method calls inside pdf.js. I'd love to stop that because the zone.js wrappers make debugging difficult.
