### ISSUE TITLE
Drawing on a specific PDF file shows a draw container on the right side in the modes (landscape/portrait).

### ISSUE THREAD

**Issue by Aareonick** [stephanrauh/ngx-extended-pdf-viewer#1872]
**Describe the bug**
- Opening a specific PDF in and start trying to draw on it.
- Unable to draw on the PDF but i can draw on the draw container next to it (see pucture below).

![pdf-issue](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144929856/d5432695-f20b-4df2-bf19-d3cfd42f7941)
(Next to the PDF there is a drawfield in portrait modes when the PDF is in landscape mode.)

![pdf-issue-2](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144929856/92f70a01-1f1e-423b-b1b7-ca641ad9606a)
(When rotating it they both change and it doesn't fix the draw issue.)

Any idea how this can happen and how to fix it? Is this some issue with the PDF file or something with handeling the modes (landscape/portrait) at start of loading a PDF within the pdf-viewer?

**Version info**
Tested on versions:
- 16.2.16 (has the issue)
- 17.4.1 (has the issue)
- 18.0.0-beta.6 (no issues)

**Demo PDF file**
Happen with a specific PDF file but currently can't upload it because of GDPR.

**Comment by stephanrauh** [comment]
Strange. Does is happen with every landscape PDF? FWIW, I couldn't reproduce it here: https://pdfviewer.net/extended-pdf-viewer/custom-toolbar. Any ideas?

**Comment by Aareonick** [comment]
No this only happens with this specific PDF file (from what i could test). I tryed other landscape PDF files internal and external by uploading it on the URL u mentioned above but this seems to work fine.

I am currently trying to make this PDF GDPR proof and im going to test if the issue persist within the URL u mentioned, If so i will upload the PDF so it can be reproduced.

**Comment by stephanrauh** [comment]
You're right, GDPR and copyright laws are important. If you don't manage to make your file GDPR proof, you can share it with me using a private GitHub repository or by sending me an email.

However, this sounds like a very specific problem, so I'm reluctant to promise too much. I can promise to have a look, but the real expert on the topic is @Calixteman. I assume the problem also happens on https://mozilla.github.io/pdf.js/web/viewer.html ?

**Comment by calixteman** [comment]
I just created a pdf in landscape mode and I can't reproduce neither in Firefox nightly nor in the web viewer.
If you can reproduce with your pdf in one of the above context, feel free to share the pdf with me on my pro email.

**Comment by stephanrauh** [comment]
@calixteman Thanks a lot for chiming in to quickly! TBH, it's possible that I caused the bug... maintaining a custom fork of pdf.js is quite a challenging task. :)

**Comment by Aareonick** [comment]
I attempted removing the personal information on the specific PDF file but when i do and save it the issue seems to be gone and can't reproduce it anymore.

I tested the issue some more on a clean Angular (v16.2.0) project and i can tell that using version "16.2.16"  or "17.4.1" seems to have the issue on this specific PDF file. Using version "18.0.0-beta.6" doesn't seem to have any issues with this file.

I can also tell that there is no issue (all versions) when editing and adding text. Only the draw field seems to have this issue.


Currently i cannot upload/send the PDF yet. I will let u know when i can.

**Comment by stephanrauh** [comment]
@Aareonick Please run a test on https://mozilla.github.io/pdf.js/web/viewer.html (and click the "upload" button). If you can reproduce the bug over there, it's a pdf.js bug. Otherwise, it's my bug.

Thanks in advance,
Stephan

**Comment by Aareonick** [comment]
@stephanrauh I tested it on "https://mozilla.github.io/pdf.js/web/viewer.html" and it seems everyting is working.

**Comment by stephanrauh** [comment]
Oops. That's unexpected!

**Comment by calixteman** [comment]
You can send it to me ONLY if you can reproduce on [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html), else it's just a bug for Stephan.

**Comment by stephanrauh** [comment]
Send the file to webmaster1 at beyondjava dot de (with the "at" and "dot" replaced by the corresponding special characters).

**Comment by stephanrauh** [comment]
I forgot too answer - but better late than never, they say... I've downloaded your file and tried several times to reproduce the bug. I couldn't. I'm giving up now. If you've got additional insight, feel free to re-open the ticket again.
