### ISSUE TITLE
How to disable the hand icon

### ISSUE THREAD

**Issue by scry-UrjitDesai** [stephanrauh/ngx-extended-pdf-viewer#1873]
Hey, in my application I want to disable the hand icon that we see on the pdf page. I want to access the underlying canvas and have mouse pointer events on it which I am able to achieve. I tried using- 

```html
 <ngx-extended-pdf-viewer
    [src]="src"
    [(page)]="page"
    (pdfLoaded)="onDocumentLoad($event)"
    (pageRendered)="onPageRendered($event)"
    [showHandToolButton]="false"
    [textLayer]="false"
  ></ngx-extended-pdf-viewer>
```
Version-"ngx-extended-pdf-viewer": "18.0.0-beta.6",

but the hand icon is still visible and scrolls.

**Comment by stephanrauh** [comment]
I see. Does `[handTool]="false"` solve the issue for you?

**Comment by scry-UrjitDesai** [comment]
Yes, it does. Thanks! 
Great Library ! Appreciate how quick you are in addressing the issues.

**Comment by stephanrauh** [comment]
Hooray! And thanks for your kind words! That's what keeps an open-source developer like me going!
