### ISSUE TITLE
PDF viewer not working - viewer.js and pdf.worker.js are not getting loaded

### ISSUE THREAD

**Issue by anand896** [stephanrauh/ngx-extended-pdf-viewer#1876]
I have set up my angular project in singleSPA (micro-frontend). I am using the latest version of 'ngx-extended-pdf-viewer'. 

I am getting the bellow error. I checked the console but there is no error.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/cccba270-646c-472e-8315-c8a814d7a6c4)

After debugging i found out that pdf.min.js file is getting loaded properly but viwer.js and pdf.worker.js are not getting loaded. Now i am not able to figure out why is this happening.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/e29c9780-d4a7-47cd-b093-eab248d03a01)

I have added the config in anguler.js file
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/5cb35c56-d726-4826-850a-a6ee0a29d76b)

Also i have added this code in component.ts (pdfDefaultOptions.assetsFolder = '/test-app/assets';). Since this is a micro-fronded project so to target the correct URL i have added this path like this. (/test-app/assets).

I have installed the fresh angular project without singleSPA(microfrontend) to check whether the error is getting there or not. But the PDF viewer working fine over there. So I am not able to figure out the root cause. 

Please help me to resolve this issue.

**Comment by stephanrauh** [comment]
SingleSPA = https://single-spa.js.org/ ?

**Comment by anand896** [comment]
Yes

**Comment by anand896** [comment]
> SingleSPA = https://single-spa.js.org/ ?

yes

**Comment by stephanrauh** [comment]
After reading my source code, I'm puzzled. Please help me by debugging your code.

Before you do, please set `[minifiedJSLibraries]="false"`. After loading your application, open the file `ngx-extended-pdf-viewer.module` (or something like this - I don't remember the precise name) in your browser's debugger and add a breakpoint to these lines:

```ts
  private loadPdfJs() {
    globalThis['ngxZone'] = this.ngZone;
    this.ngZone.runOutsideAngular(() => {
      if (!window['pdfjs-dist/build/pdf']) {
        this.needsES5().then((needsES5) => {
          if (needsES5) {
            if (!pdfDefaultOptions.needsES5) {
              console.log(
                "If you see the error message \"expected expression, got '='\" above: you can safely ignore it as long as you know what you're doing. It means your browser is out-of-date. Please update your browser to benefit from the latest security updates and to enjoy a faster PDF viewer."
              );
            }
            pdfDefaultOptions.needsES5 = true;
            console.log('Using the ES5 version of the PDF viewer. Your PDF files show faster if you update your browser.');
          }
          window['ngxZone'] = this.ngZone;
          if (this.minifiedJSLibraries) {
            if (!pdfDefaultOptions.workerSrc().endsWith('.min.js')) {
              const src = pdfDefaultOptions.workerSrc();
              pdfDefaultOptions.workerSrc = () => src.replace('.js', '.min.js');
            }
          }
          const pdfJsPath = this.getPdfJsPath('pdf', needsES5);
          const script = this.createScriptElement(pdfJsPath);
          document.getElementsByTagName('head')[0].appendChild(script);
        });
      }
      if (!(globalThis as any).webViewerLoad) {
        this.loadViewer();  // <<<<< Your bug seems to happen here
      }
    });
  }

...
  private loadViewer(): void {
    window['ngxZone'] = this.ngZone;
    this.ngZone.runOutsideAngular(() => {
      if (!window['pdfjs-dist/build/pdf']) {
        setTimeout(() => this.loadViewer(), 25);
      } else {
        this.needsES5().then((needsES5) => {
          const viewerPath = this.getPdfJsPath('viewer', needsES5);
          const script = this.createScriptElement(viewerPath);
          document.getElementsByTagName('head')[0].appendChild(script);
        });
      }
    });
  }
```

My best guess is that singleSPA confuses my algorithm by doing black magic. But what's really going on, beats me. Especially since you're saying there are no traces in the console window.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
BTW, I'd like to learn more about singleSPA. Does it play well with Angular? Did you run into problems? Is it hard to set up? I guess this ticket is not the right place to discuss this - feel free to send me an email to webmaster1 at beyondjava dot de (replacing the "at" and "dot" with the corresponding special characters).

**Comment by anand896** [comment]
> ```ts
> loadViewer
> ```


Getting this error. Looks like something related to NgZone 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/a2d9414d-ab14-4804-a389-86529939d108)
 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/59589e16-7206-4de1-89d8-fa40a2fb7ab1)

I have checked in my project so i found that i am using this in my project for singleSPA setup.
**import { NgZone } from '@angular/core';**

also i am using **zone.js** npm package.

**Comment by anand896** [comment]
> BTW, I'd like to learn more about singleSPA. Does it play well with Angular? Did you run into problems? Is it hard to set up? I guess this ticket is not the right place to discuss this - feel free to send me an email to webmaster1 at beyondjava dot de (replacing the "at" and "dot" with the corresponding special characters).

Yes, it works good.

**Comment by stephanrauh** [comment]
NgZone is broken? At the moment, I'm clueless. What about the `this` pointer? Does it point to a different object using plain vanilla Angular and using singleSPA?

**Comment by anand896** [comment]
> NgZone is broken? At the moment, I'm clueless. What about the `this` pointer? Does it point to a different object using plain vanilla Angular and using singleSPA?

For loadPDF and loadViewer both function it is targeting ngx-extended-pdf-viewer.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/ebf71491-cf6d-4179-b381-9b43fd98d5eb)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/f6adf5a5-2b64-44bc-8ff5-00aa12def158)


for your ref adding debugger step by step screenshots
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/1af535d9-05de-4136-bbee-45b6788d8aee)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/dd296549-d139-4f63-9c76-c661a728206d)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/2792359f-8842-4feb-a927-06e8fd2d05c8)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/76e66fad-e720-4ad1-bc38-e542927f3651)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/798cfa74-6fca-49c4-ad1b-574ccae46a75)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/5cc1bc0f-c4d9-4cba-88fb-902ccd9ee633)

Now here i got redirected to zone.js
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/f4b555f5-9edf-41b5-8fc9-535b431d1c68)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/ca1dc97d-1ec0-443b-af12-90e99dbe8227)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/773657fa-87b2-485f-b8f3-05f00c2d7d9c)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/0b36853c-6f9a-47dc-a748-1fb4b2b8af10)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/9a38e2b2-2740-4eba-8bda-48600118f008)

**Comment by anand896** [comment]
@stephanrauh waiting for reply. Any idea why is this pdf viewer breaking?

**Comment by stephanrauh** [comment]
After reading your long list of screenshots I'm even more clueless. All I can do is to express my gratitude to you for going to such lengths. It's obvious there must be a bug, and there must be a way to hunt it down. Does the debugger ever hit lines 4127-4179? That's where loading `viewer-*.js` is triggered.

You've also asked why the worker file isn't loaded. That happens inside pdf.js. As far as I remember, `viewer-*.js` triggers this. But `viewer.js`happens to be one of the files that aren't loaded, so it's not surprising the worker file isn't loaded.

**Comment by anand896** [comment]
> After reading your long list of screenshots I'm even more clueless. All I can do is to express my gratitude to you for going to such lengths. It's obvious there must be a bug, and there must be a way to hunt it down. Does the debugger ever hit lines 4127-4179? That's where loading `viewer-*.js` is triggered.
> 
> You've also asked why the worker file isn't loaded. That happens inside pdf.js. As far as I remember, `viewer-*.js` triggers this. But `viewer.js`happens to be one of the files that aren't loaded, so it's not surprising the worker file isn't loaded.

4127 getting loaded. 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/a5719612-21f0-4f45-a3ce-b9bac768c31a)

But Line 4179 is not loading.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/fe10dd0f-4abe-48a0-aaba-c0effcdb701c)

**Comment by stephanrauh** [comment]
I assume you mean "executed" instead of "loaded". When the debugger executes line 4129, the file `pdf-*.js` is loaded. You can see this be checking the network tab before and after executing the line.

A few lines before, the viewer is loaded. This code should be executed several milliseconds later. Can you check this? If it isn't loaded, can you find out why not?

```js
loadViewer() {
                   ...
                    const viewerPath = this.getPdfJsPath('viewer', needsES5);
                    const script = this.createScriptElement(viewerPath);
                    document.getElementsByTagName('head')[0].appendChild(script);
```

**Comment by anand896** [comment]
loadViewer() getting executed. but not going inside the else block. it's recursively executing if block.

From where this getting set-> window['pdfjs-dist/build/pdf']

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/1a329259-268c-4705-8670-4b0723be8348)

**Comment by stephanrauh** [comment]
It's one of the first lines of pdf-*.js. Can you check if `globalThis['pdfjs-dist/build/pdf']` is set? Just type it in the console window after reaching line 4030 (or maybe a little later, because the code might be loaded asynchronously.

**Comment by anand896** [comment]
> It's one of the first lines of pdf-*.js. Can you check if `globalThis['pdfjs-dist/build/pdf']` is set? Just type it in the console window after reaching line 4030 (or maybe a little later, because the code might be loaded asynchronously.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/1e0e14ed-3f45-44ed-9bae-fb856c453559)

**Comment by stephanrauh** [comment]
What a nasty bug!

**Comment by stephanrauh** [comment]
When I tried it myself, the value appeared after hitting the breakpoint four times. Maybe that happens on your machine, too?
<img width="309" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/2c5f6cad-1165-40d2-ae8b-7a8f6f95ea3e">

**Comment by anand896** [comment]
> When I tried it myself, the value appeared after hitting the breakpoint four times. Maybe that happens on your machine, too?

I hit this almost 15 times. Same response.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/daa60963-7e8f-44e8-9f9a-1bd96f429076)

**Comment by stephanrauh** [comment]
Another option might be to wait for `globalThis.pdfjsLib`. Can you give this a try, too?

**Comment by stephanrauh** [comment]
It seems singleSPA actively removes global variables.
https://single-spa.js.org/docs/ecosystem-leaked-globals/

**Comment by stephanrauh** [comment]
Version 18.0.0-beta.7 implements a partial solution. Please run a test with it. Unfortunately, I'm afraid the new version runs into an error a second later: the library relies on `globalThis.webViewerLoad()`, and that's probably deleted by singleSPA, too. Run the test nonetheless, because if you run into the new bug, I know I'm on the right track.

Thanks in advance,
Stephan

**Comment by anand896** [comment]
I have installed 18.0.0-beta.7 but still PDF viewer not working. no error in the console.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/e8a3d878-84e3-419c-a371-bef79137b95a)

globalThis['pdfjs-dist/build/pdf'] also returning undefined 

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/5f6d084e-3cb4-4a89-8a3d-3ef0366ea616)

**Comment by anand896** [comment]
@stephanrauh It looks like in pdf-*.js only "pdfjs-dist/build/pdf" not getting set.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/544cab40-cb00-402d-97cc-40a3524935c3)

**Comment by stephanrauh** [comment]
We're getting closer. I wasn't aware that singleSPA uses a different module loader.

Did you check if `globalThis.pdfjsLib` is set? If so, I could use it.

**Comment by anand896** [comment]
No. Only these getting set.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/907538fc-4e15-4143-9381-62b40795d035)

Also, I am using **"@angular-builders/custom-webpack": "^13.1.0"** webpack package to set up the single spa application.

https://www.bitovi.com/blog/how-to-build-a-single-spa-angular-application

**Comment by stephanrauh** [comment]
Looks promising. BTW, Thanks for sending me the link to the tutorial. I already wanted to ask you to send me a reproducer because I'm so busy these days.

**Comment by stephanrauh** [comment]
I didn't build an singleSPA application yet - but I've fixed a mistake. If you're lucky, version 18.0.0-beta.9 does the trick.

**Comment by anand896** [comment]
This error coming

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/b3b0add9-981c-4c2d-a611-05f46ad2ddf5)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/3977f7f7-3ea6-4037-827d-bfad19cadddd)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/43780071/c2cb1d4a-35a5-4a11-a9da-3e44707d13bc)

**Comment by stephanrauh** [comment]
Damn. I'm afraid that's a side effect of the different module system, and I can't solve it. One of these days, I'll build an example application to see what's going on, but I don't think I'll find a solution.

**Comment by stephanrauh** [comment]
I'm giving up. But maybe you can send me a simple reproducer?

**Comment by ietabhi** [comment]
When i debug i found amd is causing some issue but not able to find exact issue.
We have define.amd = {} and after this code never go inside iffe

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7829397/04b49b56-ef95-4489-879e-9c020cc5a67a)

**Comment by stephanrauh** [comment]
Well, my library does not work with AMD modules. I'm not sure I could make it work, even if I wanted to. But Angular is an opinionated framework, and it doesn't use AMD modules, so I suspect Angular doesn't play well with this module system. It's one of those thing I don't even try because it looks like an uphill race.

Be that as it may, I wonder why you've set `define.amd={}`. Is this only the default value? Maybe it's a left-over from earlier times? Or do you populate the object over time?

**Comment by ietabhi** [comment]
Sorry about confusion, my application is inside SPA container and we have system.js and amd.js as prerequisite.
So define and amd is added into window object and causing issue for me. 

I am not able to bypass this condition which is checking with "define.amd" and iffe stop working as it come out of this method and pdf.js i not loading.
