### ISSUE TITLE
Displaying two pdfs on the same screen

### ISSUE THREAD

**Issue by scry-UrjitDesai** [stephanrauh/ngx-extended-pdf-viewer#1878]
Hey, I want to display 2 pdfs side-by-side simultaneously on the same screen. I also want to be able to access both the pdfs and the underlying page canvases and perform some actions on them. How can I achieve this ?

I read through this- https://pdfviewer.net/extended-pdf-viewer/side-by-side but the example is not very clear. 

Sample HTML
```html
<ngx-extended-pdf-viewer
[src]="src1"
(pdfLoaded)="onDocumentLoad1($event)"
></ngx-extended-pdf-viewer>

<ngx-extended-pdf-viewer
[src]="src2"
(pdfLoaded)="onDocumentLoad2($event)"
></ngx-extended-pdf-viewer>
```  

Sample TS
```ts

ngOnInit() {
      src1= // fetch pdf1
      src2= // fetch pdf2
}

onDocumentLoad1(event) {
   // access the first pdf pages programmatically
}

onDocumentLoad2(event) {
   // access the second pdf pages programmatically
}
```

**Comment by stephanrauh** [comment]
You need to wrap the PDF viewer in iFrames. That's not an elegant solution, but the only one I found. You can try to use an approach like https://gist.github.com/asik-sk/cb1c528ea3ab17a6b32a0fea236f0111 to integrate the PDF viewers more tightly to you application. I haven't tried this yet, so I don't know if this works.

Here's are the relevant snippets of the source code of my demo:
https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/6580cb357efd349868f130c3eab88ae7acc7726a/src/app/extended-pdf-viewer/side-by-side/side-by-side.component.html#L40-L41

https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/6580cb357efd349868f130c3eab88ae7acc7726a/src/app/extended-pdf-viewer/iframe/iframe.component.ts#L1-L19

https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/6580cb357efd349868f130c3eab88ae7acc7726a/src/app/extended-pdf-viewer/extended-pdf-viewer-routing.module.ts#L104
