### ISSUE TITLE
Lazy load global libraries

### ISSUE THREAD

**Issue by g3344** [stephanrauh/ngx-extended-pdf-viewer#188]
Hi, thanks for the great pdf viewer!

This is more of an enhancement.

To cut down on the main bundle size is there a way to lazy load the global libraries (i.e., reduce the 150kb gzip loaded globally, and only load with viewer)?  

For example:

 ```json
"scripts": [
              {
                "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf-es5.js",
                "lazy": true
              },
              {
                "input": "node_modules/ngx-extended-pdf-viewer/assets/viewer-es5.js",
                "lazy": true
              }
            ]
```

When I try to do the above, I then add the files back into the component ts, like below:

```javascript
    const script = document.createElement('script');
    script.src = 'pdf-es5.js';
    script.type = 'text/javascript';
    script.async = true;
    script.charset = 'utf-8';
    document.getElementsByTagName('head')[0].appendChild(script);

    const script2 = document.createElement('script');
    script2.src = 'viewer-es5.js';
    script2.type = 'text/javascript';
    script2.async = true;
    script2.charset = 'utf-8';
    document.getElementsByTagName('head')[0].appendChild(script2);
```

The lazy files get added, but there's an error, which is likely a timing issue

`core.js:4002 ERROR TypeError: window.webViewerLoad is not a function`

**Comment by stephanrauh** [comment]
You make it sound so simple. Awesome! I'm pretty sure this approach works. I agree the error message probably a timing issue - and it's probably easy to avoid by modifying the Angular component class `ngx-extended-pdf-viewer-component.ts`. Thanks for the hint!

**Comment by stephanrauh** [comment]
This feature has landed a few versions ago.
