### ISSUE TITLE
The sidebar does not work in the version 18.0.1

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#1882]
Hi,
To reproduce the issue, go to this page:
https://pdfviewer.net/extended-pdf-viewer/custom-toolbar and try to open the sidebar (component <pdf-toggle-sidebar>): nothing happen.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/14161954/129cf07d-d7b3-4ef6-b5cb-430180d936f0)

Let me know if you cannot reproduce it.
Thanks a lot
Luc

**Comment by stephanrauh** [comment]
Yes, I've managed to reproduce the bug. Luckily, only the custom toolbars demo is affected. However, that's a popular feature, so I'll have to have a look at it soon.

**Comment by stephanrauh** [comment]
Just a short update: I'm working on a solution, but it's not as easy as it should be.

**Comment by lucho78** [comment]
Thanks for this update. Let me know once you will have ship a fix I can test it.
Cheers
Luc

**Comment by stephanrauh** [comment]
Your bugfix has landed a few seconds ago. I still wonder if there are side-effects, but I don't think so. Please run a test on version 18.0.2.

A la prochâine
Stephan

**Comment by lucho78** [comment]
Super thanks a lot. I will test it at least on monday. I let you know if I find something special.
Cheers
Luc
