### ISSUE TITLE
Pencil Icon color change

### ISSUE THREAD

**Issue by Tweniee** [stephanrauh/ngx-extended-pdf-viewer#1884]
I have a scenario where i need to hard code the color of the pencil tool where on a specific condition i can restrict the user to use the red color only or blue or any other color on specific condition, .
in short i want to send a color code as a property binding to the lib and accordingly pencil tool will have the color and when using the pencil tool user will not be able to change the color of it and only use the pencil in that color only
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/93429474/e3d74f3b-bc8a-4385-8cd1-b445f101cae3)

**Comment by stephanrauh** [comment]
Makes sense. I can't promise you to deliver the feature quickly. Currently I'm very busy. I'm scheduling it for the next version.

**Comment by Tweniee** [comment]
If you can guide, I want to contribute too.

**Comment by stephanrauh** [comment]
That's great news! Here's your guidance:

It seems you can use the event bus to modify the color, the thickness, and the opacity. The original implementation looks like so:
https://github.com/stephanrauh/pdf.js/blob/6d319357c859554a7ca5b3355405fd1195b45c0f/web/annotation_editor_params.js#L36-L60

You can use the same event bus to set default values for color, thickness, and opacity, as this code snippet shows:
https://github.com/stephanrauh/pdf.js/blob/6d319357c859554a7ca5b3355405fd1195b45c0f/web/annotation_editor_params.js#L62-L81

You can probably access the event bus in Typescript like so:
```ts
const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
PDFViewerApplication.eventBus.dispatch('annotationeditorparamschanged', { AnnotationEditorParamsType.INK_COLOR: '0000FF' });
PDFViewerApplication.eventBus.dispatch('INK_COLOR', '0000FF');
```

I'm not sure about this. I suppose this requires some debugging to get it right.

The rest is an exercise in diligence. I suggest you implement `@Input()` and `@Output()` bindings for color, thickness, and opacity in NgxExtendedPdfViewerComponent, and use them to define the default values of the editor popup:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/881eece73d4f5a461aa6d7c81d79ae0c01f89468/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.html#L83-98

You've also mentioned you want to lock these values. Probably it's a good idea to hide the corresponding sliders and the color-picker if the developer sets an attribute like `[showEditorColorPicker]="false"`.

Wrapping it up, it seems the ticket requires some diligence, but it's easier than expected. If you need more help, don't hesitate  to reach out to me.

Thanks in advance,
Stephan

**Comment by Tweniee** [comment]
Certainly, I will begin by investigating this issue, and debugging is definitely required.
let me start ASAP

**Comment by stephanrauh** [comment]
Awesome! When you debug the core library, set `[minifiedJSLibraries]="false"`. The lines I showed you above are probably in the file `viewer-*.js` or (less probably) in `pdf-*.js`.

**Comment by Tweniee** [comment]
I am working on this feature, the project is running perfectly but i think i am missing something,

@stephanrauh  can you share the steps to run and after changing anything it should reflect on it.

**Comment by stephanrauh** [comment]
I think you're looking for https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md. Step 9 mentions an npm token. I'm not entirely sure, but I believe you can ignore this.

**Comment by madhuputtam1992** [comment]
Hello Everyone,

I am currently seeking a solution to the problem, and I have attempted to manipulate the input fields. However, I have noticed that as soon as I click on the PDF, the values reset to the editor's default settings.

I would greatly appreciate any assistance or guidance on this matter.

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.

**Comment by Tweniee** [comment]
I tried many methods (event bus etc) but it was like one way I found then a dead end, can you give a better flow of how this event works in color picking

**Comment by Tweniee** [comment]
@stephanrauh

**Comment by stephanrauh** [comment]
Oops, sorry about that - after admitting that I'll never manage to solve the ticket someone else opened a similar ticket, and this time, I solved it... have a look at https://pdfviewer.net/extended-pdf-viewer/editor-setting.

In particular, your can modify the pencil color by calling `ngxExtendedPdfViewerService.editorInkColor("#FF0000")`.
