### ISSUE TITLE
Text being edited by any user

### ISSUE THREAD

**Issue by Tweniee** [stephanrauh/ngx-extended-pdf-viewer#1885]
I am working with adding text inside the pdf and sending the file the backend as blob and getting it from the API, 

- but if user 1 entered text inside the pdf and save it to the DB
- but now user 2 can edit the pdf in there own computer(Different Computer) can edit the text from pervious user 

this is not what i want if i add text that needs to be created in a new version of pdf and no one can change once saved

**Comment by stephanrauh** [comment]
That's beyond the scope of this library. If I get you correctly, you store the text in the database. If you want to add this text to the PDF, you'll need to create a new PDF. You can use one of the countless PDF manipulation libraries. For example, if you're using Java in the back-end, I'm pretty sure you can use iText to read the PDF, add the text, and create a new, immutable PDF file from it.

**Comment by Tweniee** [comment]
So it senerio is whenever i add text to pdf using 'T' icon 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/93429474/80514642-e624-476e-ba66-d0d4c9699fae)
and after writing anything on the pdf i save the file to the DB in BLOB.
but other user from other computer retreive it from the DB using the GET API, and double click on the text.
then the text that is entered by me is being editted by then, i was expected that the blob file created a new PDF and let the next user works on the new version?

**Comment by stephanrauh** [comment]
I see. Thing is, the editor has been implemented slightly differently. It doesn't modify the PDF file as such. It simply adds annotations to the PDF file. A classical example of such an annotation is a comment. It's simply a layer on top of the PDF file. So there's no way to prevent other users from modifying these annotations. From a technical point of view, there's no way to tell your modifications from your co-worker's modifications.

**Comment by Tweniee** [comment]
okay thanks for your response but i was thinking one thing, what if
**Backend receives the BLOB(with Text)
1. Backend Server convert the blob into a new file.
2. then using the background process convert that new Pdf to blob again 
3. then store it into the DB 

SO will this work ?

**Comment by stephanrauh** [comment]
Yes, I think this approach works.
