### ISSUE TITLE
Error  No provider for NgxExtendedPdfViewerService!

### ISSUE THREAD

**Issue by antonioalexl** [stephanrauh/ngx-extended-pdf-viewer#1893]
Hi, I'm using the latest version and I'm trying to use this service, https://pdfviewer.net/extended-pdf-viewer/blob (Download Blob)
   and I get the error:

NullInjectorError: R3InjectorError (AppModule) [NgxExtendedPdfViewerService -> NgxExtendedPdfViewerService -> NgxExtendedPdfViewerService]:
    NullInjectorError: No provider for NgxExtendedPdfViewerService!

Could anyone help me please?

**Comment by stephanrauh** [comment]
What did you do, precisely? I've tried to reproduce your bug by adding the service to the constructor of the compatibility demo (https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/compatibility-tests/common/demo/src/app/absolute-asset-path/absolute-asset-path.component.ts):

```ts
export class AbsoluteAssetsPathComponent {
  public visible = false;

  constructor(public service: NgxExtendedPdfViewerService) {
    pdfDefaultOptions.assetsFolder = 'http://localhost:4200/assets';
    if (window.location.search.includes('bleeding-edge')) {
      pdfDefaultOptions.assetsFolder = 'http://localhost:4200/bleeding-edge';
    }
  }
```

However, it compiles without problems. Maybe you've got a corrupt npm_modules folder? Try to delete it and to run `npm install` again.

**Comment by antonioalexl** [comment]
I removed and reinstalled the library and solved my problem. Thank you and congratulations for the work.
