### ISSUE TITLE
Pagination broken in version 18

### ISSUE THREAD

**Issue by brucker-g** [stephanrauh/ngx-extended-pdf-viewer#1896]
The pagination seems broken in version 18, (it's working fine on version 17.4.7). 
When clicking on the next page button it is skipping a page.
Exemple : When on a 14 page document, if I'm on page 1 and clicking on the next button page it's going to page 3 instead of page 2.

1. Go to [Viewer showcase](https://pdfviewer.net/extended-pdf-viewer/base64)
2. Click on 'Next page button'
3. It's going to page 3 instead of page 2

**Comment by stephanrauh** [comment]
Oops. I guess that's a side-effect of the improved custom buttons. I just wonder why I didn't notice during the long beta phase? Even the automated tests have failed. It seems I need to improve my QA!

**Comment by MelaniaStewart** [comment]
Hi there.  I just last week using this component and noticed the pagination error.  Is there any updates on this.  Is there anyway I can help fix this issue? It is a big one for us.  I am disabling the paging for now, until I find a resolution.  Do you know if there is another pdf viewer out there I can use (temporarily)  Please let me know. Thanks!!

**Comment by stephanrauh** [comment]
Your bugfix has shipped with version 18.1.0.

**Comment by MelaniaStewart** [comment]
Hi stephan
I am about to get test this.
Can not see the new version.
Can you please send me the link?
Thanks
Melania

**Comment by stephanrauh** [comment]
I've published version 17.4.8 a few seconds after publishing version 18.1.1, and that's confused npm, and by extension, it probably has confused you. Nonetheless, the version is there. Here you are:
https://www.npmjs.com/package/ngx-extended-pdf-viewer/v/18.1.1

**Comment by MelaniaStewart** [comment]
Hi stephan
I deployed your fix and it fixed the issue.
I really appreciate it.
Melania
