### ISSUE TITLE
Checkbox prints as a very small dot not an X

### ISSUE THREAD

**Issue by NexPlex** [stephanrauh/ngx-extended-pdf-viewer#1897]
Hi happy to help with debugging but not sure where to start. I saw on a different thread printing is often related to CSS but I can't see the connection.

I'm using "ngx-extended-pdf-viewer": "^17.4.6",

PDF looks like this
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/34607168/7a06cff8-502c-4b32-a8e8-b916d461deb2)

PDF Prints like this
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/34607168/b74bfbcf-3518-4767-a7af-e48a02ad7108)

It makes it very hard to see. Any suggestions?

**Comment by stephanrauh** [comment]
As for debugging - some time ago, I've written a walk-through: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1431#issuecomment-1162091452

**Comment by stephanrauh** [comment]
I'm closing the ticket now. I'm confident the problem is your CSS code, and I hope my walk-through helped you to identify the problem.
