### ISSUE TITLE
Open multiple instances of the PDF viewer at the same time

### ISSUE THREAD

**Issue by MihirManek** [stephanrauh/ngx-extended-pdf-viewer#190]
**Is your feature request related to a problem? Please describe.**
I am trying to display more than one PDFs at the same time, but it gives an error on the console saying "You're trying to open two instances of the PDF viewer. Most likely, this will result in errors.". Also, the second PDF does not load when the component is bought in view.

**Describe the solution you'd like**
An ability to open multiple PDFs at the same time.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by stephanrauh** [comment]
I'm afraid that's not possible. Maybe you (or someone else) have got an idea how to make this possible, but right now, I'm clueless.

Thing is, the Mozilla team have created the underlying PDF viewer, pdf.js, to display PDF files in Firefox. They didn't write it to be used somewhere else. In particular, they never thought about embedding the PDF viewer in a HTML file. Let alone embedding it in an Angular application.

With some effort, I managed to embed pdf.js nonetheless, but it's almost impossible to go further. The PDF viewer uses global variables (the "window scope"). We'd have to convert these global variables into - say - object properties. In theory, that's possible, but it'd take more time than I have. Plus, I don't want to break compatibility to future versions of pdf.js, so we'd have to proceed carefully.

So my current recommendation is to put the PDF viewer into an iFrame. That's the approach of https://www.npmjs.com/package/ng2-pdfjs-viewer. So you can either either that project, or wrap ngx-extended-pdf-viewer in an iFrame.

@Snuffleupagus @timvandermeij Is my analysis correct? Feel free to correct me if I'm wrong!

Best regards,
Stephan

**Comment by timvandermeij** [comment]
I'm also only aware of the `iframe` approach. Note that we're always looking for ways to reduce usage of global variables, so any feedback for this is always welcome, for example by opening an issue or pull request with improvements. One example is the version 2.0 release of PDF.js where we removed the global `PDFJS` object and other patches where usage of `window` is reduced.

**Comment by stephanrauh** [comment]
I'll close this ticket for the moment. Nonetheless, I'll keep it in mind.

**Comment by sieuanhung001** [comment]
Hi team,
Has this feature been updated?

**Comment by stephanrauh** [comment]
No, not yet. I didn't find enough spare time to examine how to put the viewer into an iFrame or in a WebComponent.

**Comment by stephanrauh** [comment]
No. Currently, diligent developers open new tickets faster than I can solve them. However, you can put the PDF viewer in a WebComponent or an iFrame yourself and tell us whether it works or not. I guess you can easily run such a test within a work-day.

**Comment by stephanrauh** [comment]
No, there are no updates. IMHO the workaround described at https://pdfviewer.net/extended-pdf-viewer/side-by-side work well enough.

**Comment by RubioN** [comment]
You can find the source code here
https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/side-by-side

**Comment by stephanrauh** [comment]
I've improved the demo as requested. Thanks for pointing this out!

**Comment by aminasharaf** [comment]
Hi...Is there any solution for this problem? Is there a way to get the HTML currently being viewed from ngx-extended-pdf-viewer without it trying to create another instance?

**Comment by stephanrauh** [comment]
No, there are no news on the topic.

**Comment by stephanrauh** [comment]
That sounds like a misunderstanding. My showcase demo works and it displays two instances of ngx-extended-pdf-viewer side-by-side. 

The workaround works by putting ngx-extended-pdf-viewer into an iFrame. That's not the same as displaying a PDF file natively in an iFrame. You can still benefit from the added value of ngx-extended-pdf-viewer.

However, the work-around is not perfect. Putting ngx-extended-pdf-viewer in an iFrame amounts to starting an independent Angular application which can't communicate with it's parent application. For example, `(pageChange)` isn't propagated to the parent application.

On the long, I want to overcome this limitation. But it's not easy. Both the pdf.js team and I started to stop polluting the global namespace, but we're not there yet. More to the point, I believe the pdf.js team have done there homework, but I haven't finished it yet.

**Comment by stephanrauh** [comment]
As for your question: the demo does use `<app-iframe>`, but it's a bit convoluted:

- The `<iframe>` uses the path `src="/extended-pdf-viewer/iframe/cdk"`. 
- This path is implemented by the router: `{ path: 'iframe/:id', component: IFrameComponent }`. 
- Finally, `IFrameComponent` is `<app-iframe>`:
  ```ts
   @Component({ selector: 'app-iframe', ... })
   export class IFrameComponent
   ```

**Comment by rizwanswati** [comment]
though i manged display two PDFs side by side using ifram approach but there is huge problem in context of my use case.
basically pdf uploaded gets OCRD. backend return cordinates of the OCR and i draw annotation boxes over pdf, also a table shows the extracted info which when hovered over, draws a line towards annotation box on pdf, now i need to show 2nd pdf on same page and achieve same functionality over it that when i hover over it, it draws lines from table to both the PDFs on right and left. this requires a lot of data to passed among ngx-extended-pdf-viewer iframs and the main component. after a lot of searching and trying out multiple solutions.. i am now clueless ..

**Comment by stephanrauh** [comment]
@rizwanswati Instead of wrapping ngx-extended-pdf-viewer in an iFrame, it should be possible to wrap it in a WebComponent. WebComponents can communicate with the outer world (and vice versa), so I guess this solves your issue.

**Comment by rizwanswati** [comment]
> @rizwanswati Instead of wrapping ngx-extended-pdf-viewer in an iFrame, it should be possible to wrap it in a WebComponent. WebComponents can communicate with the outer world (and vice versa), so I guess this solves your issue.

i tried this solution today, but unfortunately, i didn't work either. Even wrapping it up in two totally separate WebComponents. Ifram allow very narrow to no manipulation options. at this point, i think there is no solution to this.

**Comment by stephanrauh** [comment]
What a pity. I'll try myself one of these days, but I suppose you've tested it thoroughly, so I won't be more successful than you.

**Comment by mayurThakkar** [comment]
Hi @stephanrauh, is the issue resolved?

**Comment by stephanrauh** [comment]
No, I didn't work on this topic recently.
