### ISSUE TITLE
Range is not getting added to the request headers

### ISSUE THREAD

**Issue by prashantchvn** [stephanrauh/ngx-extended-pdf-viewer#1903]
I am trying to stream the pdf using partial content requests
when I am trying to make the request on my spring boot server
the range header is not added in my request header as it should append the Range header on the request
<img width="960" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/48098832/2b2569f0-ce13-44b6-b058-f7a2aba42741">
that's why my spring boot server is throwing 400 bad request because I've configured server like that
here is the component
```
<ngx-extended-pdf-viewer [src]="'http://localhost:8080/gcp/partial/pdf'" [authorization]="`Bearer ${token}`">
</ngx-extended-pdf-viewer>
```
here is the request header for this api call
```
GET /gcp/partial/pdf HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en
Connection: keep-alive
Host: localhost:8080
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36
sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile: ?1
sec-ch-ua-platform: "Android"
```

any further helps will be appreciated
thank you

**Comment by stephanrauh** [comment]
Weird. I've just opened the showcase and it does send range headers. Are we talking about the same topic?
<img width="1848" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/cc57d348-2a7a-4e0d-878a-98ed9a1da4b0">

At second thought: your screenshot shows only one request. Maybe your PDF file is small enough to load without pagination. That's just an educated guess - I don't know if there's such an algorithm. But looking at my showcase, I also see that the first request doesn't have a range request header, and I faintly remember that the request is canceled after a while. That's why the first request - which asks for the entire file - is followed by several partial requests.

<img width="992" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/665c3097-de80-4c91-8b66-ba6f055a8466">

You might also want to check the behaviour of https://mozilla.github.io/pdf.js/web/viewer.html. That's basically the same application, just without Angular.

**Comment by prashantchvn** [comment]
its weird but I've developed two api's to test this 
the node one which have this code for get api
```
app.get('/pdf', async (req, res) => {

      /** Calculate Size of file */
      const { size } = await fileInfo(samplePDF);
      const range = req.headers.range;
      console.log(size)
  
      /** Check for Range header */
      if (range) {
        /** Extracting Start and End value from Range Hea der */
        let [start, end] = range.replace(/bytes=/, "").split("-");
        start = parseInt(start, 10);
        end = end ? parseInt(end, 10) : size - 1;
  
        if (!isNaN(start) && isNaN(end)) {
          start = start;
          end = size - 1;
        }
        if (isNaN(start) && !isNaN(end)) {
          start = size - end;
          end = size - 1;
        }
  
        // Handle unavailable range request
        if (start >= size || end >= size) {
          // Return the 416 Range Not Satisfiable.
          res.writeHead(416, {
            "Content-Range": `bytes */${size}`
          });
          return res.end();
        }
  
        /** Sending Partial Content With HTTP Code 206 */
        res.writeHead(206, {
          "Content-Range": `bytes ${start}-${end}/${size}`,
          "Accept-Ranges": "bytes",
          "Content-Length": end - start + 1,
          "Content-Type": "application/psdf",
          "Access-Control-Allow-Origin": "http://localhost:4200/"
        });
  
        const readable = createReadStream(samplePDF, { start, end });
        pipeline(readable, res, err => {
          console.log(err);
        });
  
      } else {
  
        res.writeHead(200, {
          "Access-Control-Expose-Headers": "Accept-Ranges",
          "Access-Control-Allow-Headers": "Accept-Ranges,range",
          "Accept-Ranges": "bytes",
          "Content-Length": size,
          "Content-Type": "application/pdf",
          "Access-Control-Allow-Origin": "http://localhost:4200"
        });
  
        if (req.method === "GET") {
            const readable = createReadStream(samplePDF);
            pipeline(readable, res, err => {
              console.log(err);
            });	   
        } else {
          res.end();
        }
      }

});
```
for this case when I am giving `http://localhost:3000/pdf` as a url to attribute `src` it is behaving normal 
<img width="950" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/48098832/75e4e0c4-fde9-4736-9044-f62e095b84ce">
but when I add `<ngx-extended-pdf-viewer [src]="'http://localhost:3000/pdf'" [authorization]="'Bearer kjasdhfjskdfsdkjfh'">
` [authorization] it starts throwing CORS error all of the sudden
<img width="960" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/48098832/44fbd8b3-c95f-40fe-ae38-c87fa822f42d">
that's the another problem
and when I give the java server's api route to [src] it stops sending Range header in my case
here I am attaching the java code snippet as well 
```
@Override
	public ResponseEntity<byte[]> getMultiPartPdf(String rangeHeader,
			HttpServletResponse response) throws IOException{
		logger.info("getting multipart pdf files");
		logger.info(rangeHeader);
		String pdfFilePath = "classpath:static/sample2.pdf"; // Adjust the path as needed
		Resource resource = resourceLoader.getResource(pdfFilePath);
		Long size = resource.contentLength();
		String range = null;
		Long start = null,end = null;
		if (rangeHeader != null && rangeHeader.startsWith("bytes=")) {
			range = rangeHeader.substring("bytes=".length());
			String[] startEnd = range.split("-");
			if (startEnd.length == 2) {
				start = Long.parseLong(startEnd[0]);
				end = Long.parseLong(startEnd[1]);
			} else if (startEnd.length == 1) {
				start = Long.parseLong(startEnd[0]);
				end = size - 1; // Replace 'size' with your actual size value
			}
			if (start >= size || end >= size) {
				response.setStatus(HttpServletResponse.SC_REQUESTED_RANGE_NOT_SATISFIABLE);
				response.setHeader("Content-Range", "bytes */" + size);
				response.getWriter().close();
				return ResponseEntity.status(416).body(null);
			}
			HttpHeaders headers = new HttpHeaders();
			headers.add("Content-Range", "bytes " + start + "-" + end + "/" + size);
			headers.add("Accept-Ranges", "bytes");
			headers.add("Content-Length", String.valueOf(end - start + 1));
			headers.add("Content-Type", "application/pdf");
			Path filePathObj = Paths.get(resource.getFile().getAbsolutePath());
			byte[] bytes = Files.readAllBytes(filePathObj);
			return new ResponseEntity<>(bytes, headers, HttpStatus.PARTIAL_CONTENT);
		}else{
			ResponseEntity.status(204).body("invalid range headers");
		}
		return ResponseEntity.ok(null);
	}
```
here is the snippet of angular as well
`<ngx-extended-pdf-viewer [src]="'http://localhost:8080/gcp/partial/pdf'" [authorization]="'Bearer kjasdhfjskdfsdkjfh'">`
and here is the curl request for this [src] which is an java spring boot server
```
curl 'http://localhost:8080/gcp/partial/pdf' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:4200' \
  -H 'Referer: http://localhost:4200/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-GPC: 1' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36' \
  -H 'authorization: Bearer kjasdhfjskdfsdkjfh' \
  -H 'sec-ch-ua: "Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  --compressed ;
```
screenshot for the same curl
<img width="953" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/48098832/d93e3561-ae26-48da-8094-67cf2e731f74">
here in this case the Header Range is not being send to backend
@stephanrauh do we have any other way to load our pdf in extended-pdf-viewer instead of directly giving an `[src]="path of the get api url"` can we use any `Observable` to fetch the pdf bytes instead,
I've checked for few blogs I am not getting any proper example in which we are using any observable to fetch file instead of directly giving URL
any further assistance will be helpful.

**Comment by prashantchvn** [comment]
@stephanrauh any code snippet for spring boot implementation will be helpfull
thank you

**Comment by brucker-g** [comment]
You can call your API and then create an URL like this from the response of the call : 

`url = URL.createObjectURL(httpResponse.body)`

and pass the result in `[src]='url'`

**Comment by mkumar92** [comment]
Accept-Ranges: bytes
Access-Control-Allow-Methods: GET, HEAD, PUT, POST, DELETE
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers: Accept-Ranges, Content-Length, Content-Range


you have to add these thing in api response headers and make sure your pdf is linearized or not.

**Comment by prashantchvn** [comment]
Thank you all the issue is resolved
It was backend side conflicts which were causing the package to stream the pdf
thank you all for their suggestions

**Comment by stephanrauh** [comment]
I'm glad to hear this!
