### ISSUE TITLE
DOM getting freeze if the pdf have 10-15k pages

### ISSUE THREAD

**Issue by mkumar92** [stephanrauh/ngx-extended-pdf-viewer#1906]
If i try to load large pdf ( which have 10-15k pages in pdf ) the full page getting freeze.

version -  [18.0.2](https://www.npmjs.com/package/ngx-extended-pdf-viewer/v/18.0.2).

Is there any option to add virtuall scroll to clear the unused DOM in pdf viewer ?

**Comment by stephanrauh** [comment]
Try the single-page mode. You loose infinite scrolling, but single-page mode copes well with huge documents.

https://pdfviewer.net/extended-pdf-viewer/page-view-mode
