### ISSUE TITLE
Problem viewing signatures in signed document

### ISSUE THREAD

**Issue by drpjl** [stephanrauh/ngx-extended-pdf-viewer#1910]
Hey do we support showing digital signatures ?

The test.pdf was generated using 

https://docs.criipto.com/signatures/

There is no signature displayed.  Works OK with other pdf viewers (sorry I was sure how I tested with your list of URLS I should try first !)    But I did test by creating the test project as you asked.

<img width="1389" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/87026417/51574de2-f21e-4817-8fb6-580d6837a4e5">

[test.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/13006074/test.pdf)

**Comment by drpjl** [comment]
Ooops sorry 

 [showUnverifiedSignatures]="true"

**Comment by stephanrauh** [comment]
I've opened your test file on https://pdfviewer.net/extended-pdf-viewer/signatures, and the signature is there. What am I doing differently?

The console messages are strange indeed. The warning "unimplemented field type Sig" shouldn't be there - at least not on my machine that manages to render the signatures. 

The other warning "validation is not supported" tells you exactly that: at the momemt, there's no algorithm to validate the signature, so showing the signature is risky. There's no way to tell a valid signature from a fraud one.

**Comment by stephanrauh** [comment]
BTW, I assume you're using version 17 of my library?

**Comment by drpjl** [comment]
Sorry  I was not clear.

My post 

[showUnverifiedSignatures]="true"

Was me realising that I needed this setting for the signature to display.  Sorry I did not make this clear.  I would have deleted my question but this was not an option.

**Comment by stephanrauh** [comment]
No worries. I'm happy you've managed to solve the issue, and I'm even more happy you've managed to do so without my help. Maybe my documentation isn't all that bad! :)

Best regards,
Stephan
