### ISSUE TITLE
I am not able to modify the rangeChunkSize for the partial content

### ISSUE THREAD

**Issue by prashantchvn** [stephanrauh/ngx-extended-pdf-viewer#1918]
**I need your help!**
I'm trying to modify the property rangeChunkSize where I want to fetch 1MB of data in each request how can we do that 
any example to fetch 1MB of data in each partial request will be helpful
as well as I want to load whole file at once without waiting for scroll
at this point it is fetching data when we are scrolling I just want to load whole data and then stop making API calls

**I'm using this version of extended-pdf-viewer "ngx-extended-pdf-viewer": "^9.0.0-alpha.4"**
Thank you

**Comment by prashantchvn** [comment]
could you please show me the example or codesandbox snipped to edit the rangeChunkSize option
it will be more helpful for me
as well just to clarify my ngx-extended-pdf-viewer version is 9.0.0-alpha.4

**Comment by stephanrauh** [comment]
```ts
import { pdfDefaultOptions } from 'ngx-extended-pdf-viewer';
```

**Comment by prashantchvn** [comment]
I've logged the pdfDefaultOptions
it is showing this in console
`{
    "cursorToolOnLoad": 0,
    "defaultUrl": "",
    "disableHistory": false,
    "disablePageLabels": false,
    "enablePrintAutoRotate": false,
    "enableWebGL": false,
    "eventBusDispatchToDOM": false,
    "externalLinkRel": "noopener noreferrer nofollow",
    "externalLinkTarget": 0,
    "historyUpdateUrl": false,
    "imageResourcesPath": "./images/",
    "maxCanvasPixels": 16777216,
    "pdfBugEnabled": false,
    "removePageBorders": false,
    "renderer": "canvas",
    "renderInteractiveForms": true,
    "sidebarViewOnLoad": -1,
    "scrollModeOnLoad": -1,
    "spreadModeOnLoad": -1,
    "textLayerMode": 2,
    "useOnlyCssZoom": false,
    "viewOnLoad": 0,
    "cMapPacked": true,
    "disableAutoFetch": true,
    "disableCreateObjectURL": false,
    "disableFontFace": false,
    "disableRange": false,
    "disableStream": false,
    "isEvalSupported": true,
    "maxImageSize": -1,
    "pdfBug": false,
    "postMessageTransfers": true,
    "verbosity": 1,
    "workerPort": null,
    "assetsFolder": "assets",
    "doubleTapZoomFactor": "page-width"
}`
@stephanrauh are you sure that rangeChunkSize can be modified for version 9.0.0-alpha.4

**Comment by stephanrauh** [comment]
No, I'm not sure because that's an unsupported version. I've added support for range request on August 14, 2021. If version 9.0.0-alpha.4 is older than that, range requests are not support, if it's younger, they are supported.

In any case, please update to version 18. It's always a bad idea to use an alpha version in production.
