### ISSUE TITLE
The resource from “https://localhost:44440/assets/pdf-3.10.548.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

### ISSUE THREAD

**Issue by roopeshkurian** [stephanrauh/ngx-extended-pdf-viewer#1919]
When I upgraded to the new version (18.1.3)  I got a "404 Not Found" error for https://localhost:44440/assets/pdf-3.10.548.min.js
But with same configuration everything works good in  ngx-extended-pdf-viewer@18.1.1 

It wont work in  ngx-extended-pdf-viewer@18.1.2. 

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/15811922/a8b8dd9c-2c49-4190-896e-0ce5ff417171)

In my angular.json, I have 
     "assets": [
              "src/assets",            
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              } 

 Working version
　　18.1.1

 Not Working versionｓ
　　18.1.2
　   18.1.3

Can you please look in to this ?

**Comment by stephanrauh** [comment]
Oops, sorry. You're right, the JavaScript files were missing. Version 18.1.4 fixes this.

**Comment by roopeshkurian** [comment]
Thanks for identifying the problem.  I really appreciate your help.

**Comment by roopeshkurian** [comment]
Hi,
I have one more concern 
Now pdf file is loading properly. But in console, I have /assets/locale/locale.properties 404 (Not Found) error. 
Do you have any idea about it?

**Comment by stephanrauh** [comment]
No, I'm afraid I haven't. Please check if your locale folder is a subfolder of the assets folder, and whether it's complete. Judging from your `angular.json`, it is both there and complete, so I'm puzzled. Check it anyways, please. Maybe there's a subtle typo or misconfiguration?
