### ISSUE TITLE
 Checkboxes are all initially checked when opening a PDF in Version 18.1.4.

### ISSUE THREAD

**Issue by Sluuuush** [stephanrauh/ngx-extended-pdf-viewer#1920]
Hey, I found a bug in Version 18.1.4 and thought maybe you know why this behavior is happening

**Bug Description:**

Upon opening a PDF with an AcroForm containing checkboxes in version 18.1.4, all checkboxes are automatically checked, which was not the case in version 18.0.1. This issue seems to have resurfaced in the latest version.

**Steps to Reproduce:**

Open a project where Version 18.1.4 is installed.
Choose to open a PDF with an AcroForm that has checkboxes.
Observe that all checkboxes are checked upon opening the PDF.

**Version Information:**

Software Version: 18.1.4

**Additional Details:**

I attempted to reproduce this issue in a fresh project to eliminate any project-specific factors, and the problem persisted in both the new project and the existing one. (Version 18.0.1 worked fine in the new project)

**Demo PDF file**
[beschreibbares_PDF_Formular_Bestellung.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/13114978/beschreibbares_PDF_Formular_Bestellung.pdf)

**Comment by stephanrauh** [comment]
This sounds both weird and disturbing. The onyl form-related change I did was #1887 - but it should work the other way round.I didn't expect it to check all the checkboxes.

**Comment by luke-rogers** [comment]
We are also seeing this issue in `17.4.8`

**Comment by nilsKr3** [comment]
We also had the issue with 18.1.4 furthermore radio buttons are not displayed as selected at all. Going back to 18.0.1 fixed it for us.

**Comment by stephanrauh** [comment]
Please update to version 18.1.8. Now the checkboxes behave as they should.

**Comment by stephanrauh** [comment]
To dos left:
- [ ] publish the bugfix in version 17, too

**Comment by stephanrauh** [comment]
Please update to version 18.1.9. It fixes a corner case I'd forgotten in version 18.1.8.
