### ISSUE TITLE
PDF form field focus/blur events

### ISSUE THREAD

**Issue by luke-rogers** [stephanrauh/ngx-extended-pdf-viewer#1928]
**Is your feature request related to a problem? Please describe.**
We process the form fields from the PDF and render our own version of the form to make it easier for the user to fill in the fields. We render our version to the side of the PDF viewer, so the user can see both the PDF and our form, and can fill in the form using either. We would like to be able to highlight the field in our form when the user focuses it in the PDF and preferably vice versa too. 

**Describe the solution you'd like**

- Event for focus and blur of PDF form fields
- Solution to manually focus (highlight) a field when a user focuses in our form

**Describe alternatives you've considered**
No alternatives exist within the current feature set

**Additional context**

**Comment by stephanrauh** [comment]
The fields are regular `<input>` fields, so you should be able to add the event listeners yourself when receiving the `annotationLayerRendered` event. Does this sound like a solution?

**Comment by luke-rogers** [comment]
This sounds like it has potential, I'll take a look into it.

Happy for this ticket to be closed. I'll comment again if it doesn't quite give us what we are looking for.
