### ISSUE TITLE
Make use of ngx-scrollbar as a replacement for the seemingly unmaintained perfect-scrollbar

### ISSUE THREAD

**Issue by Hely0n** [stephanrauh/ngx-extended-pdf-viewer#1929]
**Is your feature request related to a problem? Please describe.**
I want to have a "perfect scollbar" :) like in the examples, but as you know, the library doesn't work well anymore. So I found https://github.com/MurhafSousli/ngx-scrollbar which could be mighty successor

**Describe the solution you'd like**
A tutorial of how to replace the native scrollbar with the ngx-scrollbar in the docs/demos would be enough, I think. 

**Describe alternatives you've considered**
If it's not possible to use this library, maybe a "Custom scrollbar" manual would fit in docs, with some css snippets for a popular scrollbar design (like perfect-scrollbar for example).

**Additional context**
Unfortunately, I'm still kind of a newbie in angular and have difficulties to achieve something like this myself, so I can't help much. 
If someone have already done this and knows how to do it, I would be thankful if you could post an explanation as a comment here.

**Comment by stephanrauh** [comment]
I'll have a look at it, but not immediately.

**Comment by Hely0n** [comment]
Thank you!

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.
