### ISSUE TITLE
PDF Viewer is being broken on SSR side in case of using pageViewMode property

### ISSUE THREAD

**Issue by ad-mars** [stephanrauh/ngx-extended-pdf-viewer#1932]
Thank you for your work.

I have been using this library for a while, then I had to apply SSR to my project. In case I use property `pageViewMode`, server side is getting broken. Client side works fine. 

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/13711314/782a310f-6b1d-4c8e-b250-3e8c3b1b0c66)

Library version: **18.1.4**
Angular version: **15.1**

Code: 
`<ngx-extended-pdf-viewer *ngIf="pdfSrc"
                                 [src]="'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'"
                                 [pageViewMode]="'infinite-scroll'"
                                 height="80vh">
</ngx-extended-pdf-viewer>`

Steps for reproducing:
Install angular with SSR and run "npm run dev:ssr"

It seems the problem is here:
`const PDFViewerApplicationOptions = window.PDFViewerApplicationOptions;`

**Comment by stephanrauh** [comment]
Please update to version 18.1.6. It should fix the issue.
