### ISSUE TITLE
Second created instance of PDF Viewer component fails on rendering; after first instance is destroyed.

### ISSUE THREAD

**Issue by Anonynym3845937** [stephanrauh/ngx-extended-pdf-viewer#1933]
**Repro:**
- Create instance of PDF Viewer component and present it within a container.
- Load PDF document.
- -> PDF is presented properly.
- Clear the container containing the PDF Viewer.
- Nullify any pointers to it.
- Recreate instance of PDF Viewer component and present it within a container (same container or different one).
- Load PDF document (different one).

**Expected**:
 - PDF document is loaded and presented.

**Actual**:
 - Get Console error: and doesn't present the PDF
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/141650248/3dc20bfc-7555-46a6-b03f-932546cc0337)

---

This was not a problem with earlier version of the PDF Viewer component **^4.0.0"**, but is with current **^18.1.4**.

---

On  the first passthrough that function in the stack trace (that is causing the error above), the eventBus is present:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/141650248/da047518-5cb4-4c63-bac0-743a11d7ad6b)

On the next one (the one causing error), the eventBus is null:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/141650248/5dec7711-9271-43ed-992f-84effd2e8e67)

---

The code we use to recreate the PDF Viewer component is as follows:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/141650248/fb50f602-51b0-4b58-9cb6-33a6e8c43be2)

---

**Versions:**

npm --version
8.19.4

node --version
v16.20.1

packages.json
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/141650248/a3b10ec0-37f0-4e40-8800-450994271c02)

**Comment by stephanrauh** [comment]
Sounds like a bug. Does it help when you open the new instance with a short timeout? pdf.js is highly asynchronous, so it takes a while until it has properly shut down.

**Comment by LereveLabs** [comment]
We are having this same problem.  We recently upgraded Angular to 15

**Comment by stephanrauh** [comment]
Can you send me a reproducer, please?

**Comment by LereveLabs** [comment]
We ended up refactoring the code so that we only had to instantiate one instance of the pdf viewer, passing the source of the pdf into the component rather than rendering multiple components each with the pdf viewer in it

**Comment by stephanrauh** [comment]
Ah, that's clever. Another option is putting the PDF viewer in an iFrame, as shown here: https://pdfviewer.net/extended-pdf-viewer/side-by-side. It's an ugly solution, but it works.

**Comment by Anonynym3845937** [comment]
@LereveLabs We need to display multiple instance - we are using a dock manager.

Adding the delay worked.

I tried setting the srcbase64 multiple times, but the next set doesn't reload the new pdf content.
