### ISSUE TITLE
I want to know if pdf content type is binary/octet-stream, range works on this type also?

### ISSUE THREAD

**Issue by mkumar92** [stephanrauh/ngx-extended-pdf-viewer#1935]
version - 18.1.0

**Comment by stephanrauh** [comment]
I'm not aware on any differences depending on the content type, so I guess it is supported. But then, you wouldn't open a ticket if everything works as intended. Tell me more!

**Comment by stephanrauh** [comment]
I haven't heard from you for several weeks, so I'm closing this ticket now.
