### ISSUE TITLE
Add attribute to hide 'Add image' button

### ISSUE THREAD

**Issue by cah-ken** [stephanrauh/ngx-extended-pdf-viewer#1936]
**Is your feature request related to a problem? Please describe.**
Every button seems to have an attribute to hide except the 'Add image' button (see image of documentation).

**Describe the solution you'd like**
Add attribute to hide button.

**Describe alternatives you've considered**
I am currently using css to hide the button, but it would be nice to have a proper attribute like all the other buttons.

**Additional context**
Here is an image of the documentation at https://pdfviewer.net/extended-pdf-viewer/hiding-buttons that displays that every button can be hidden besides the 'Add image' button.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/111090516/341c43f9-a5e2-41d8-a8d0-6e8e0f4197f5)

**Comment by stephanrauh** [comment]
That makes sense. Putting it on my to-do list.

**Comment by Hely0n** [comment]
I was in the same situation, and I found out there is actually is an attribute to hide it, but it's not listed there. It's called `[showStampEditor]="false"`

**Comment by cah-ken** [comment]
That solved it.  Thanks!
