### ISSUE TITLE
Annotations don't get displayed correctly

### ISSUE THREAD

**Issue by PatrickZimmerer** [stephanrauh/ngx-extended-pdf-viewer#1937]
I am using version 18.1.4

When fetching Annotations some of them are not displayed on the PDF, this error occurs when a PDF has multiple pages, for example, I had a PDF with 6 pages, and annotations get loaded and displayed correctly for pages 1 & 2, but for the rest of the pages, they don't get rendered, the annotations get loaded correctly from the database and are provided with the correct page index, I also tried the workaround from a past Issue https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1825#issuecomment-1691060375 but this doesn't work and should be fixed in 18.0.0-beta.4

**Comment by jfl-tel** [comment]
this is probably an issue with pdfjs directly not ngx-extended-pdf-viewer
I know I add somme issue with annotation and it was fix in v4.0.189
https://github.com/mozilla/pdf.js/pull/17216

**Comment by PatrickZimmerer** [comment]
So we are not using pdfJs in our project currently, only the ngx-extended-pdf-viewer which is using pdfJs under the hood is that correct? 
Can I do something to fix this bug?

**Comment by jfl-tel** [comment]
yes it is correct, so you need to check if the bug is present in pdfjs latest
if not then it's fixed and you will need to wait for the next ngx-extended-pdf-viewer that will use (4.0.189)
When I found my bug, I open an Issue in pdfjs with a bugfix suggestion, and it was quickly fixed

**Comment by stephanrauh** [comment]
@PatrickZimmerer Please fill in some details. I assume you're trying to programatically add annotations to a PDF file that has already been loaded by ngx-extended-pdf-viewer. If so, it'll be very difficult to reproduce the bug with pdf.js. I'd also need a reproducer, because I don't think I a reproduce your issue in my limited spare time.

On the other hand, if you've run into a problem with a PDF file that already has the annotations, please open your file in the showcase of pdf.js (https://mozilla.github.io/pdf.js/web/viewer.html#page=1&zoom=auto,-213,792). If you can reproduce the bug over there, please report it to the Mozilla team. Just make sure you don't mention my project. pdf.js is the PDF viewer of Firefox, so they tend to solve only bugs that also show in Firefox.

**Comment by stephanrauh** [comment]
@jfl-tel I'm afraid pdf.js 4.0 won't come soon. They've added a couple of breaking changes, and that sounds like a lot of work for me. The changelog doesn't read that dramatic, but you never know.

**Comment by jfl-tel** [comment]
@stephanrauh do you think before Christmas ?

**Comment by stephanrauh** [comment]
I've learned the hard way not to make promises... but , yes,I hope I'll be able to update to 4.0 before Christmas.

**Comment by PatrickZimmerer** [comment]
> @PatrickZimmerer Please fill in some details. I assume you're trying to programatically add annotations to a PDF file that has already been loaded by ngx-extended-pdf-viewer. If so, it'll be very difficult to reproduce the bug with pdf.js. I'd also need a reproducer, because I don't think I a reproduce your issue in my limited spare time.
> 
> On the other hand, if you've run into a problem with a PDF file that already has the annotations, please open your file in the showcase of pdf.js (https://mozilla.github.io/pdf.js/web/viewer.html#page=1&zoom=auto,-213,792). If you can reproduce the bug over there, please report it to the Mozilla team. Just make sure you don't mention my project. pdf.js is the PDF viewer of Firefox, so they tend to solve only bugs that also show in Firefox.

I'll look into creating a reproducer, the weird thing is that the annotations get loaded from the database correctly (with the needed ```pageIndex``` etc.) but adding those to the pdf with the ```addEditorAnntotation()``` and passing in the annotation as an argument works perfectly fine but just up until the second page, any annotations further down the pdf won't get added even though they have an pageIndex > 1

**Comment by stephanrauh** [comment]
Chances are you're adding the annotations too early. The PDF file is rendered lazily. Only the first few pages are shown immediately. Try adding the annotations when the event `(annotationLayerRendered)`. This event is fired when the annotation layer of a page has been rendered. In other words, you'll receive it multiple times.

**Comment by stephanrauh** [comment]
I'm closing the ticket now because I haven't heard from your for two weeks. However, if you send me a reproducer, I'll have a look at it and re-open the ticket if necessary.
