### ISSUE TITLE
Add options to hide the "Add image" icon.

### ISSUE THREAD

**Issue by Aareonick** [stephanrauh/ngx-extended-pdf-viewer#1942]
**Is your feature request related to a problem? Please describe.**

Our application had two modes read-only and edit modes. Depending on the mode some items will be shown or hidden. Currently I am unable to hide the "Add image" option within the toolbar.

**Describe the solution you'd like**

A option (boolean) to show/hide the "Add image" icon.

**Describe alternatives you've considered**

Didn't find any alternative solutions.

**Additional context**

![afbeelding](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144929856/dae41400-74b2-47fc-be89-f44d58f646c1)

**Comment by stephanrauh** [comment]
The property exists. It's just called a bit weird: `[showStampEditor]`.

I've added the attribute to the showcase demo.
