### ISSUE TITLE
Double "Infinite scroll" label/text.

### ISSUE THREAD

**Issue by Aareonick** [stephanrauh/ngx-extended-pdf-viewer#1943]
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
Could not find the "Infinite scroll" option.
- Does the bug also happen on https://pdfviewer.net/simple?
Yes.
- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.
Did not try this yet because of a simple label/text issue.

**Describe the bug**
![afbeelding](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144929856/6ce23a66-fed3-4c66-997a-520ef5bbdd43)

**Version info**
- 18.1.4 (Possibly also in other 18.x.x versions.)

**Demo PDF file**
Not needed.

**Comment by stephanrauh** [comment]
Weird bug. The source is identical to the source of the other menu items.

**Comment by stephanrauh** [comment]
Please update to version 18.1.5. It should fix your bug.
