### ISSUE TITLE
pdf-toggle-secondary-toolbar element doesn't work (regression)

### ISSUE THREAD

**Issue by majora2007** [stephanrauh/ngx-extended-pdf-viewer#1953]
I have the following code:
```html
<ngx-extended-pdf-viewer
      #pdfViewer
      [src]="readerService.downloadPdf(this.chapterId)"
      [authorization]="'Bearer ' + user.token"
      height="100vh"
      [(page)]="currentPage"
      [textLayer]="true"
      [useBrowserLocale]="true"
      [showHandToolButton]="true"
      [showOpenFileButton]="false"
      [showPrintButton]="false"
      [showRotateButton]="false"
      [showDownloadButton]="false"
      [showPropertiesButton]="false"
      [(zoom)]="zoomSetting"
      [showSecondaryToolbarButton]="true"
      [showBorders]="true"
      [theme]="theme"
      [backgroundColor]="backgroundColor"
      [customToolbar]="multiToolbar"
      [language]="user.preferences.locale"

      (pageChange)="saveProgress()"
      (pdfLoadingStarts)="updateLoading(true)"
      (pdfLoaded)="updateLoading(false)"
      (progress)="updateLoadProgress($event)"
    >
    <ng-template #multiToolbar>
      <div style="min-height: 36px" id="toolbarViewer" [ngStyle]="{'background-color': backgroundColor, 'color': fontColor}">
        <div id="toolbarViewerLeft">
          <pdf-toggle-sidebar></pdf-toggle-sidebar>
          <pdf-find-button></pdf-find-button>
          <pdf-paging-area></pdf-paging-area>
        </div>

        <pdf-zoom-toolbar ></pdf-zoom-toolbar>

        <div id="toolbarViewerRight">
          <pdf-hand-tool></pdf-hand-tool>
          <pdf-select-tool></pdf-select-tool>
          <pdf-presentation-mode></pdf-presentation-mode>


          <!-- This is not yet supported by the underlying library
          <button (click)="toggleBookPageMode()" class="btn btn-icon toolbarButton">
              <i class="toolbar-icon fa-solid {{this.bookMode !== 'book' ? 'fa-book' : 'fa-book-open'}}" [ngStyle]="{color: fontColor}" aria-hidden="true"></i>
              <span class="visually-hidden">{{this.bookMode !== 'book' ? 'Book Mode' : 'Normal Mode'}}</span>
          </button> -->

          <button class="btn btn-icon mt-0 mb-0 pt-1 pb-0 toolbarButton" [ngbTooltip]="bookTitle">
            <i class="toolbar-icon fa-solid fa-info" [ngStyle]="{color: fontColor}" aria-hidden="true"></i>
            <span class="visually-hidden">{{bookTitle}}</span>
          </button>

          <button *ngIf="incognitoMode" (click)="turnOffIncognito()" class="btn btn-icon mt-0 mb-0 pt-1 pb-0 toolbarButton">
            <i class="toolbar-icon fa fa-glasses" [ngStyle]="{color: fontColor}" aria-hidden="true"></i><span class="visually-hidden">{{t('incognito-mode')}}</span>
          </button>

          <!-- This is pretty experimental, so it might not work perfectly -->
          <button (click)="toggleTheme()" class="btn btn-icon mt-0 mb-0 pt-1 pb-0 toolbarButton">
            <i class="toolbar-icon fa-solid {{this.theme === 'light' ? 'fa-sun' : 'fa-moon'}}" [ngStyle]="{color: fontColor}" aria-hidden="true"></i>
            <span class="visually-hidden">{{this.theme === 'light' ? t('light-theme-alt') : t('dark-theme-alt')}}</span>
          </button>

          <button class="btn btn-icon col-2 col-xs-1 mt-0 mb-0 pt-1 pb-0 toolbarButton" (click)="closeReader()">
            <i class="toolbar-icon fa fa-times-circle" aria-hidden="true" [ngStyle]="{color: fontColor}"></i>
            <span class="visually-hidden">{{t('close-reader-alt')}}</span>
          </button>

          <div class="verticalToolbarSeparator hiddenSmallView"></div>
          <pdf-toggle-secondary-toolbar></pdf-toggle-secondary-toolbar>
        </div>

      </div>

    </ng-template>
```
    
In a recent (not latest, but a few releases ago perhaps) update, this code no longer works and the toolbar does not render anything inside. 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/735851/bce69fc4-2915-453c-9b5c-c88402c2b7e3)

I checked the demo site and it is working and just wondering if you can see what's wrong? 

**Version info**
- Version of ngx-extended-pdf-viewer: 18.1.6 

**Demo PDF file**
This happens on every pdf. 

There isn't really a change log per release (I guess there is, just found one nestled in the [code](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/279dcb0b0ebade0ff402038cd07ef68085e8b4a0/projects/ngx-extended-pdf-viewer/changelog.md) ), but I did scan the commits to see if anything stood out.

**Comment by majora2007** [comment]
Looking at the code, my only thinking is the component might be getting confused and thinking it needs to hide based on viewport:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/secondary-toolbar/pdf-secondary-toolbar/pdf-secondary-toolbar.component.html

**Comment by majora2007** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/735851/1ff4a5fa-484c-4d57-b85b-4715de6692fc)

Okay sorry to spam you but I'm positive it's the shy button that is hiding all the buttons. Based on my markup, I can't understand how it's getting confused. I have no css that even interacts with that popup and i'm using it in a full browser.

**Comment by stephanrauh** [comment]
Don't worry about spamming me. You've run into a break change introduced with version 18.0.0. I bet your application runs without changes in the 17.x.x versions. And you're right, while I did document both the breaking change and the new way of defining custom toolbars, I documented it sort of in the dark. It's easy to miss my hints.

In particular, I forgot to write a migration guide. I'm putting this on my to-do list!

Starting with version 18, the `<pdf-shy-button>` is your friend. That's a special wrapper class for buttons in the main toolbar. "Shy" means that the button hide in the secondary toolbar if screen estate gets scarce.

So you'll have to convert every `<button>` in your toolbar to a `<pdf-shy-button>`. I've tried to describe the new approach here: https://pdfviewer.net/extended-pdf-viewer/custom-toolbar. If the documentation confuses me, or if you've got an idea how to improve it, please tell me. I hope the conversion is pretty straight-forward. Maybe the biggest challenge is keeping in mind that the `[action]` property takes a closure as parameter.

The icons might be a challenge, too. I don't know if it's possible to use your FontAwesome icons without changes. However, if you can convert your icons to SVG images, you're good to go. Luckily, the FontAwesome page nowadays offers SVG. For example, your "fa-glasses" icon has a SVG representation here: https://fontawesome.com/icons/glasses?f=classic&s=solid

As for your Tailwind (?) classes, I hope you won't need them, but if you do, maybe I need to add two attributes. At the time being, there's no option to pass different CSS classes to the buttons in the main toolbar and to the buttons in the secondary kebab menu. Please open a new feature ticket if you need this feature (but you can keep the text short because I'm already familiar with the problem).

**Comment by stephanrauh** [comment]
To-dos left:

- [ ] write a migration guide for custom toolbars

**Comment by majora2007** [comment]
I think there is some misunderstanding (but also bad news for me). So the shy button I can understand. It is a way to allow for it to automatically collapse into the secondary toolbar popover. 

However, for me, the secondary toolbar popover is completely empty and not showing the default buttons. Even if I take my toolbarViewerRight div and remove all buttons within it, the `pdf-toggle-secondary-toolbar` still has nothing in it on render. 

I tried rolling back to older versions, but wasn't able to find the version where this was working as expected.

**Comment by stephanrauh** [comment]
Since version 18, you have to define every button in the toolbar in order to populate the kebab menu. On small screens (or narrow windows), the hand tool, the select tool, and the presentation mode button should be in the menu. On large screens, when there's plenty of space, they are in the main toolbar. This can lead to an empty menu.

The CSS class decides the breakpoint. A few buttons - like "document properties" - never show in the main toolbar:
```html
[cssClass]="show | responsiveCSSClass : 'always-in-secondary-menu'"
```
I guess you need to add the missing menu items. Here's my default configuration:

```html
<ng-template #defaultToolbar>
  <div id="toolbarViewer">
    <div id="toolbarViewerLeft">
      <pdf-toggle-sidebar [show]="showSidebarButton" [sidebarVisible]="sidebarVisible"></pdf-toggle-sidebar>
      <pdf-find-button [showFindButton]="showFindButton" [textLayer]="textLayer" [findbarVisible]="findbarVisible"></pdf-find-button>
      <pdf-paging-area [showPagingButtons]="showPagingButtons"></pdf-paging-area>
    </div>
    <pdf-zoom-toolbar [showZoomButtons]="showZoomButtons" [zoomLevels]="zoomLevels"></pdf-zoom-toolbar>
    <div id="toolbarViewerRight">
      <pdf-document-properties [show]="showPropertiesButton"></pdf-document-properties>
      <pdf-no-spread [scrollMode]="scrollMode" [show]="showSpreadButton"></pdf-no-spread>
      <pdf-odd-spread [scrollMode]="scrollMode" [show]="showSpreadButton"></pdf-odd-spread>
      <pdf-even-spread [scrollMode]="scrollMode" [show]="showSpreadButton"></pdf-even-spread>
      <pdf-single-page-mode
        [show]="showSinglePageModeButton"
        [pageViewMode]="pageViewMode"
        (pageViewModeChange)="updatePageViewMode($event)"
        [scrollMode]="scrollMode"
      ></pdf-single-page-mode>
      <pdf-vertical-scroll-mode
        [show]="showVerticalScrollButton"
        [pageViewMode]="pageViewMode"
        (pageViewModeChange)="updatePageViewMode($event)"
        [scrollMode]="scrollMode"
      ></pdf-vertical-scroll-mode>
      <pdf-horizontal-scroll
        [show]="showHorizontalScrollButton"
        [pageViewMode]="pageViewMode"
        (pageViewModeChange)="updatePageViewMode($event)"
        [scrollMode]="scrollMode"
      ></pdf-horizontal-scroll>
      <pdf-wrapped-scroll-mode
        [show]="showWrappedScrollButton"
        [pageViewMode]="pageViewMode"
        (pageViewModeChange)="updatePageViewMode($event)"
        [scrollMode]="scrollMode"
      ></pdf-wrapped-scroll-mode>
      <pdf-infinite-scroll
        [show]="showInfiniteScrollButton"
        [pageViewMode]="pageViewMode"
        (pageViewModeChange)="updatePageViewMode($event)"
        [scrollMode]="scrollMode"
      ></pdf-infinite-scroll>
      <pdf-book-mode
        [show]="showBookModeButton"
        [pageViewMode]="pageViewMode"
        (pageViewModeChange)="updatePageViewMode($event)"
        [scrollMode]="scrollMode"
      ></pdf-book-mode>
      <pdf-hand-tool [showHandToolButton]="showHandToolButton"></pdf-hand-tool>
      <pdf-select-tool [showSelectToolButton]="showHandToolButton"></pdf-select-tool>
      <pdf-rotate-page [showRotateButton]="showRotateButton" [clockwise]="true" [counterClockwise]="false"> </pdf-rotate-page>
      <pdf-rotate-page [showRotateButton]="showRotateButton" [clockwise]="false" [counterClockwise]="true"> </pdf-rotate-page>
      <pdf-presentation-mode [showPresentationModeButton]="showPresentationModeButton"></pdf-presentation-mode>
      <pdf-open-file [showOpenFileButton]="showOpenFileButton"></pdf-open-file>
      <pdf-print [showPrintButton]="showPrintButton"></pdf-print>
      <pdf-download [showDownloadButton]="showDownloadButton"></pdf-download>

      <pdf-editor [showDrawEditor]="showDrawEditor" [showTextEditor]="showTextEditor" [showStampEditor]="showStampEditor"></pdf-editor>
      <pdf-toggle-secondary-toolbar [showSecondaryToolbarButton]="showSecondaryToolbarButton"> </pdf-toggle-secondary-toolbar>
    </div>
  </div>
</ng-template>
```

**Comment by majora2007** [comment]
I didn't forget about this, just on a holiday. Once I'm back I'll try implementing this. Seems like a lot has changed since I first integrated the app and I may need a redesign to fit the library usage.

**Comment by stephanrauh** [comment]
Enjoy your days off!

**Comment by stephanrauh** [comment]
I've run into the empty secondary menu myself now: #1987

**Comment by stephanrauh** [comment]
I suppose after solving #1987 this ticket is solved, too.

**Comment by majora2007** [comment]
Will try out the fix later this year. I have a big PDF update planned for my software, so will work on this library then. Cheers and thanks for the continued work on the library.
