### ISSUE TITLE
Lazy loading support for large pdf files

### ISSUE THREAD

**Issue by redrubytech** [stephanrauh/ngx-extended-pdf-viewer#1956]
I use this plugin for loading large PDF files.
The only complaint is that the document is loaded and browable in flipbook view only after downloading the whole document locally in browser cache.
For smaller file this works well, but for files of larger size (say 200 mb) this is really annoying.
It is good to have part loading / lazy loading provision of the document so that the user will not see the difference

**Comment by stephanrauh** [comment]
Does your server support range requests? Please check this. Range requests allow the library to load only the pages it really needs.

Generally speaking, the book mode library I'm using is a bit capricious. It has a couple of short-comings that are hard to debug. I'm not surprised it behaves weirdly if pushing it to its limits.

However, the file size shouldn't be one of these limits. The number of pages might be a problem. But apart from that, everything should work fine. The library renders the pages lazily. In fact, each time I test I observe that the library renders the pages too lazily. Every once in a while I see a blank page, and I don't know why this happens.

What you're telling me is the opposite problem. That puzzles me - but maybe the answer is really "activate range requests on your server". If it isn't, can you send me the offending PDF file, please?
