### ISSUE TITLE
Angular 17 and above

### ISSUE THREAD

**Issue by MasonVX** [stephanrauh/ngx-extended-pdf-viewer#1957]
I already updated my project to angular 17 and unfortunately the lib requires angular <17. 

I can use it locally by using the --force flag for installing and I haven't seen any issue regarding this. Would it be possible to simply allow angular 17 in the package.json? The automatic build in my repo does not allow to use it at the moment.

I've also seen, that some libraries just say >13 since the last big braking change was then. Would it make sense here? I don't know how much deprecated functions are being used.

To be honest, I don't know whether it would be a better approach or not.

**Comment by stephanrauh** [comment]
Consider it done! I've been ill for the last couple of weeks, and still don't feel well, so Angular 17 took me by surprise. To be honest, I completely forgot to run a test and to update the requirements of my library.

**Comment by stephanrauh** [comment]
As for declaring compatibility above version 12 - I'm not sure about that. This simple entry in the package.json is sort of saying "I've tested it, and you can use the library with Angular 17/18/19/.../42 without thinking twice". I'm not sure I want to make such a bold claim for a library that's downloaded 60.000 times a week. Sooner or later there will be a breaking change, so maybe it's better to err on the safe side. I know from experience how frustrating this is when you're using a library. But I think luring trusting developers into updating their application, only to learn it's broken, is even more frustrating.

**Comment by MasonVX** [comment]
Thanks for the quick response.

That's why I wrote that I'm not sure what the better approach is. You solution is the probably the right one. 
There is one thing: in the keywords there is still  "Angular 12 - 16", mentioned. Since it is not really relevant maybe something for a future release.

**Comment by stephanrauh** [comment]
Good point. I've fixed that. It'll show in npm soon.

For some reason, almost all my Playwright tests fail, but it seems to be a minor CSS issue. I guess Angular 17 compatibility looks good. The only exception I've found is the schematics: Angular 17 omits modules by default, and `ng add ngx-extended-pdf-viewer` doesn't cope with that yet.

**Comment by SoyDiego** [comment]
Hi @stephanrauh, I found this issue and I have read all the comments but I continue with the doubt.
It is working good in Angular 17 or not yet?

Thanks for your work! :)

**Comment by MasonVX** [comment]
Hi @SoyDiego,
I did not have any issue yet since the update.

**Comment by stephanrauh** [comment]
@SoyDiego It works. The only reason why the showcase is still using Angular 15 is that Angular Material 16+ has become so ugly.

**Comment by SoyDiego** [comment]
> @SoyDiego It works. The only reason why the showcase is still using Angular 15 is that Angular Material 16+ has become so ugly.

Thanks for your fast reply. I will implement in my project :)

**Comment by stephanrauh** [comment]
If you run into trouble, don't hesitate to tell me!

**Comment by SoyDiego** [comment]
> If you run into trouble, don't hesitate to tell me!

Thanks again, I will be here if I have problems :)

**Comment by SoyDiego** [comment]
Hi @stephanrauh, I installed in my project (Angular 16.9.1 at the moment) and works perfectly!
Tomorrow I will upgrade to Angular 17.
Meanwhile I want to ask about a warning that I have when I open a pdf:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/19764334/0bd0ccf7-af63-4c7f-8851-a3abd3140e6d)

It is possible to hide or solve the warning?

Thank you again and if you prefer my questions in new issues, I can create it. Let me know :)

**Comment by stephanrauh** [comment]
Now you know why it's an alpha version. :) Sure, I'll care about these messages. Until a few days ago, there were roughly 50 or 100 missing translations... comparing to that, the current version is just great!

Maybe it'll take a while until the editor-highlight messages are solved. That's a brand-new feature that's currently being developed. Usually the team adds the translations a bit later. Only the infinite-scroll message is my task.

**Comment by SoyDiego** [comment]
> Now you know why it's an alpha version. :) Sure, I'll care about these messages. Until a few days ago, there were roughly 50 or 100 missing translations... comparing to that, the current version is just great!
> 
> Maybe it'll take a while until the editor-highlight messages are solved. That's a brand-new feature that's currently being developed. Usually the team adds the translations a bit later. Only the infinite-scroll message is my task.

Oh ok, thanks again @stephanrauh for you replies. 
I will check more the code and if I can contribute and make a PR in something, I will try too.

Thanks! :)
