### ISSUE TITLE
showBorders is not turning off the borders

### ISSUE THREAD

**Issue by ishanuda** [stephanrauh/ngx-extended-pdf-viewer#197]
Hi,
Setting showBorders="true/false" does not turn off the border as in the demo page.

`"ngx-extended-pdf-viewer": "^2.0.0-alpha.2",`

Regards

**Comment by stephanrauh** [comment]
You're confusing me. Which demo page are you referring to? This one? https://pdfviewer.net/display-options

Does the feature work on the demo page, but it doesn't work on your machine?

**Comment by ishanuda** [comment]
Hi,
Thank you for the quick reply,

Yes, the feature is working in the demo, but not in my pc.

regards

**Comment by stephanrauh** [comment]
@ishanuda Please checkout the showcase https://github.com/stephanrauh/extended-pdf-viewer-showcase. Now, the `showBorders` feature should work in the local copy of the showcase.

If it does, you can compare your project to the showcase project. Usually that helps you finding the problem.

Please report if you've managed to solve the bug, so I know I can close the ticket. Thanks in advance!
Stephan

**Comment by stephanrauh** [comment]
I just realize the feature hasn't made into the IE11 code. Are you using the EcmaScript5 compatible code?

**Comment by stephanrauh** [comment]
I've published the IE11 compatible version. Until I hear from you, I assume this bug has been fixed.
