### ISSUE TITLE
i18n not working on some toolbar buttons (rotation, fullscreen)

### ISSUE THREAD

**Issue by dbellemin** [stephanrauh/ngx-extended-pdf-viewer#1972]
As seen in the showcase, some button titles of the toolbar are not translated even though the translation exists : (screenshot from the showcase with french translation)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2300149/bb94d093-776a-4957-b3df-9e805e2c85f8)
Some components use invalid attribute name for l10nId (missing case or additional -)

I'll open the PR. Amazing work otherwise ^^

**Comment by stephanrauh** [comment]
I've accepted your PR and mentioned you in the change log. Merci beaucoup!

**Comment by stephanrauh** [comment]
Your bug fix has landed with version 18.1.9.

**Comment by dbellemin** [comment]
Wow, thanks a lot! 🚀
