### ISSUE TITLE
Error regeneratorRuntime after ng build

### ISSUE THREAD

**Issue by sailorphoenix** [stephanrauh/ngx-extended-pdf-viewer#199]
Hello,

I am new in Angular and I have a problem after building my app (Angular 8).
When I open my pdf, this error appear in my console:
Uncaught ReferenceError: regeneratorRuntime is not defined
This is in pdf.js which is minified.
I don't understand why. Perhaps, I am missing something?

Here my version of the library 
    `"ngx-extended-pdf-viewer": "2.0.0-alpha.0",`

And my config angular.json 
```
            "assets": [  {
              "glob": "**/*",
              "input": "node_modules/ngx-extended-pdf-viewer/assets/",
              "output": "assets/"
            }],
```

Thank you so much!

**Comment by stephanrauh** [comment]
Strange. Sounds like a Babel error. Are you using `@babel/polyfill`? 

Maybe there's an old version of `regenerator-runtime` in your package-lock.json.

https://stackoverflow.com/questions/53558916/babel-7-referenceerror-regeneratorruntime-is-not-defined

**Comment by sailorphoenix** [comment]
I am not using @babel/polyfill, I have checked after few stackoverflow old answers for this error.
And for regenerator-runtime :
`    "regenerator-runtime": {
      "version": "0.11.1",
      "resolved": "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz",
      "integrity": "sha512-MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg==",
      "dev": true
    },
`
When I checked <script>, I saw pdf.js called in <head> but all others scripts like polyfill are called into <body> element. Perhaps, this is my problem? Pdf script must be included into <body> and not before all others scripts?

Thank you!

**Comment by stephanrauh** [comment]
Did you add pdf.js to the HTML header yourself? If you didn't, you probably see the effect of lazy loading. The statement to add pdf.js is added to the header, but that happens some time after loading the page, and it triggers an asynchrounous load.

You could add the current version of `regenerator-runtime` to the package.json. Maybe that solves the problem. pdf.js uses the library internally.

**Comment by sailorphoenix** [comment]
Hi,
So, I upgraded `regenerator-runtime` with the lastest version. My error disappears but new messages are displayed : 

```
Warning: Setting up fake worker.
pdf.worker.js:1 showUnverifiedSignatures false
```

I saw a paragraph about fake worker in the documentation. So, I assumed that it's fine. But the pdf is not displayed. This is normal with these messages on my console ? 

Thank you!

**Comment by sailorphoenix** [comment]
For my last comment, the fake worker warning (not error my bad), I don't understand this one. I have pdf, pdf.worker and viewer loaded. So what did I miss?

**Comment by stephanrauh** [comment]
Well - that's precisely the problem. It's confusing, I know. It took me more than a year to understand it.

It's simple: the message means you've loaded the file `pdf-worker.js` eagerly. It's already in memory when the PDF viewer initializes. So pdf.js decides to use this copy of the file.

The drawback is that this approach doesn't allow you to use service workers. Pdf.js uses service workers to decouple page rendering from UI interactions. In other words, service workers are a huge performance boost. I couldn't believe it when I tried to load a 100-megabyte PDF file. Without service workers you need several minutes of patient waiting. With service workers the PDF file is almost rendered instantaneously.

Here's the surprise: all you need to do to activate service workers is not to load the `pdf-worker.js` file. Just remove it from the `scripts` section of the `angular.json` (but make sure it's copied to `/assets/pdf-worker.js`).

You'll be rewarded by superior performance, and the warning is gone.

**Comment by stephanrauh** [comment]
As for the other message: I've forgotten to remove debug code when I release the version. The message simply means that pdf.js doesn't display digital signature. That's good, because the pdf.js team hasn't managed to implement the feature completely, but it's bad because many people want to display signatures, even if pdf.js can't verify the signature reliably yet.

**Comment by stephanrauh** [comment]
Remains the fact that your PDF file isn't displayed. Currently, I don't have a clue. I don't know enough about your project. Just one guess: Many CSS frameworks set the height of your PDF viewer to zero pixels. Did you try adding the attribute `height="100vh"`?

**Comment by sailorphoenix** [comment]
For pdf-worker, I haven't add it to scripts part on angular.json. This is so weird.
For height attribute, I have set by default `height="80vh"` 
The fact is, the library and my pdf work fine with ng serve --aot but not with Wamp and ng build, something goes wrong :/
What most important functions can I debug to find my problem?

**Comment by sailorphoenix** [comment]
Do I need specific configurations for Wamp Server? Something to enable or disabled absolutely?

**Comment by stephanrauh** [comment]
What is Wamp? Sounds a bit like LAMPP... is it a web server?

**Comment by stephanrauh** [comment]
This one? http://www.wampserver.com/

**Comment by sailorphoenix** [comment]
My bad! It's like LAMPP server :)
Yes, it is. It provides a localhost with database, apache and php environment.

**Comment by stephanrauh** [comment]
Currently, I'm using a MacBook, so I can't install Wamp myself. However, looking at the description:

> WampServer est une plate-forme de développement Web sous Windows pour des applications Web dynamiques à l’aide du serveur Apache2, du langage de scripts PHP et d’une base de données MySQL. Il possède également PHPMyAdmin pour gérer plus facilement vos bases de données.

I don't see anything special. Apache2 is simply a webserver. There's nothing that can go wrong. So probably the Angular build is broken.

**Comment by stephanrauh** [comment]
Two ideas:

- I don't know what the `--aot` flag does in 2020, but I haven't seen it for a long time. Better use `--prod`.
- You can also publish the developer build on your WAMP server. Just to see what's happening. I've often seen project that run fine in developer mode while being broken in production mode. That'd give us a hint where to hunt down the bug.

**Comment by stephanrauh** [comment]
> For pdf-worker, I haven't add it to scripts part on angular.json. This is so weird.

Indeed. That's one of the reasons why I've created the project https://github.com/stephanrauh/extended-pdf-viewer-showcase. You can clone it, run it, and it should behave exactly like https://pdfviewer.net. If it does, you can start to compare the configuration of the showcase with your project.

**Comment by sailorphoenix** [comment]
Omg, I did it :) It works!
Thank you for all your suggestions. I had some caches on my website but my problem was resolve with the adding of pdf.js and viewer.js on `scripts` after runtime.js.
So, I have the warning about fake worker but it's fine now :)

Thank you again!

**Comment by stephanrauh** [comment]
Awesome! May I ask what caused your original problem with the regenerator runtime? My best guess is you're using a third-party library using an old version of the regenerator (or Babel, or whatever). Is that correct?

BTW, I'll close the ticket now, but I'm still listening to it. 

Best regards,
Stephan

**Comment by sailorphoenix** [comment]
You're totally right. It's babel-runtime my first problem. It's required an old version of regenerator-runtime. 

`    "babel-runtime": {
      "version": "6.26.0",
      "resolved": "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz",
      "integrity": "sha1-llxwWGaOgrVde/4E/yM3vItWR/4=",
      "dev": true,
      "requires": {
        "core-js": "^2.4.0",
        "regenerator-runtime": "^0.11.0"
      },
      "dependencies": {
        "regenerator-runtime": {
          "version": "0.11.1",
          "resolved": "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz",
          "integrity": "sha512",
          "dev": true
        }
      }
    },`
Added the last version of this library solve my first problem. Actually, the version of this library is 0.13.0.

Thank you again for your time, your help and your expertise.

Best regards,

**Comment by stephanrauh** [comment]
It looks like I've simply forgotten to close the ticket. Doing it now.
