### ISSUE TITLE
Zoom drowndown shows NaN% during load time

### ISSUE THREAD

**Issue by paucls** [stephanrauh/ngx-extended-pdf-viewer#1992]
**Describe the bug**
When the PDF viewer is loading for first time a pdf, the zoom dropdown displays as an optin "NaN%".
![dropdown_nan](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2535738/df2f57bd-aab1-40fa-a9ab-7e9fb2a04532)

This can be there for a few seconds for user with slow internet connections.

Showing NaN% is clearly a bug. We could say that nothing should be displayed until real options are loaded.

**Version info**
 Version of ngx-extended-pdf-viewer 18.1.4

**Code investigation**
I believe the bug is in the code around the PdfZoomDropdownComponent.valueToZoomLevel function.

**Demo PDF file**
Any file would reproduce it.

**Comment by stephanrauh** [comment]
Your bugfix has landed in version 18.1.11 and 19.0.0-alpha.4.
