### ISSUE TITLE
files size is too heavy after created the production build, is there any option to decrease the file size ?

### ISSUE THREAD

**Issue by the-dev-adonis** [stephanrauh/ngx-extended-pdf-viewer#2007]
Angular -  15
pdf viewer version - 18.1.0

Total pdf viewer files size - around 25mb

**Comment by moberwasserlechner** [comment]
I have the same problem. Maybe it is possible to remove the not needed translations somehow?

**Comment by stephanrauh** [comment]
Sure. I can't do much about the _file_ size, but it's possible to reduce the directory size. I assume you're using the default `angular.json` configuration generated by the schematics. If so, you can fine-tune the `angular.json`.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/0a6e918e-6ce7-4548-9fd3-602b8adc198a)

- Drop the `inline-locales folder`. It's gone with version 19, anyways.
- Drop the `additional-locale` folder. It shouldn't be there in the first place. Luckily, it's only a few bytes.
- Only copy the subfolders of the `locale` folder. But include the file `locale/locale.properties`. Starting with version 19, this file is renamed to `locale/locale.json`.
- If you're sure you don't need legacy browser support, drop the `*-es5` files.
- Finally, you can omit the non-minified files, retaining only the `*.min.js` files.

All this only reduces the size of the distribution bundle. There's not effect on the network traffic of the application.

BTW, I've got a minor improvement: starting with version 18.1.13 and 19.0.0-alpha.4, the file `viewer.js` shrinks significantly.

**Comment by stephanrauh** [comment]
I suppose the images folder is superfluous, too, but I didn't verify this yet.

**Comment by the-dev-adonis** [comment]
@stephanrauh  solution is looking good. Is there any solution to reduce the network traffic also in slow internet ?

**Comment by stephanrauh** [comment]
No, I'm afraid there no such solution. The base library - pdf.js - ships huge files, and there's nothing I can do about it. You can see the file sizes here https://unpkg.com/browse/pdfjs-dist@4.0.269/build/ and here https://unpkg.com/browse/pdfjs-dist@4.0.269/web/.

Possible options for you might be implementing a PWA application or using the native PDF viewer of your browser.

**Comment by moberwasserlechner** [comment]
I tried the proposed solution and here are my results.

I successfully tested this config with `v19.0.1` and Angular 16 on Chrome, FF and Safari as well as iOS 16.5, 17.x and Android 13 using Capacitor 5.

Note: There are 2 version of viewer, pdf.worker, pdf.sandbox and pdf present in the lib's asset folder. I only included the latest (v4) and so far I could not find any downsides.

```
            {
                "glob": "**/*.{js,mjs}",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/",
                "ignore": [
                  "**/*es5.*", "**/viewer-3.*", "**/pdf-3.*", "**/pdf.worker-3.*", "**/pdf.sandbox-3.*"
                ]
              },
              {
                "glob": "**/locale.json",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale",
                "output": "/assets/locale"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale/de",
                "output": "/assets/locale/de"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale/en-US",
                "output": "/assets/locale/en-US"
              }
```

The same config as part of a shortened "angular.json"

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "my-angular-16-app": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "tsconfig.app.json",
            "polyfills": [ "zone.js" ],
            "assets": [
              "src/.well-known",
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest",
              {
                "glob": "**/*.{js,mjs}",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/",
                "ignore": [
                  "**/*es5.*", "**/viewer-3.*", "**/pdf-3.*", "**/pdf.worker-3.*", "**/pdf.sandbox-3.*"
                ]
              },
              {
                "glob": "**/locale.json",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale",
                "output": "/assets/locale"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale/de",
                "output": "/assets/locale/de"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale/en-US",
                "output": "/assets/locale/en-US"
              }
            ],
            "styles": [
              "src/styles.scss"
            ],
            "allowedCommonJsDependencies": [],
            "scripts": [],
            "extractLicenses": false,
            "ngswConfigPath": "ngsw-config.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "serviceWorker": true,
              "extractLicenses": true,
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
      }
    }
  }
}
```
This results in those files in my dist/assets folder

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/1049938/cb27e9e5-757a-4ae2-a4af-fad48a6f61fd)

**Comment by stephanrauh** [comment]
Thanks for point out that I'm still shipping version 3.9. You're right, that's not necessary. I've fixed that in version 19.0.2.

I suppose you can also delete the non-minified files. That slashes another three megabytes.

BTW, I wasn't aware that the glob syntax is so flexible. Awesome!

**Comment by the-dev-adonis** [comment]
@stephanrauh could you pls add this on V-18 also ? Bcoz my angular project is in V-15, pdf viewer V-19 is not supported on my project.

**Comment by moberwasserlechner** [comment]
Hi Stephan, at first thanks for removing the v3 files from the lib. :)

I tried to remove the non-minified files as well, but both in development and production configuration there are errors:

development
```
Beim Laden der PDF-Datei trat ein Fehler auf.

PDF.js v4.0.728 (build: d5cf764cb)
Message: Setting up fake worker failed: "error loading dynamically imported module: http://localhost:4200/assets/assets/pdf.worker-4.0.728.mjs". viewer-4.0.728.min.mjs:21:55850

Uncaught (in promise) Error: Setting up fake worker failed: "error loading dynamically imported module: http://localhost:4200/assets/assets/pdf.worker-4.0.728.mjs".
    _setupFakeWorker pdf-4.0.728.min.mjs:21
    _setupFakeWorker pdf-4.0.728.min.mjs:21
    terminateEarly pdf-4.0.728.min.mjs:21
    onWorkerError pdf-4.0.728.min.mjs:21
    _initialize pdf-4.0.728.min.mjs:21
    PDFWorker pdf-4.0.728.min.mjs:21
    getDocument pdf-4.0.728.min.mjs:21
    open viewer-4.0.728.min.mjs:21
    open viewer-4.0.728.min.mjs:21
    openPDF ngx-extended-pdf-viewer.mjs:4983
    Babel 3
    ZoneAwarePromise Angular
    _asyncToGenerator Babel
    Angular 3
    openPDF ngx-extended-pdf-viewer.mjs:4972
    ngOnChanges ngx-extended-pdf-viewer.mjs:5195
    Babel 2
pdf-4.0.728.min.mjs:21:172427
    invoke zone.js:368
    run zone.js:129
    scheduleResolveOrReject zone.js:1257
    invokeTask zone.js:402
    runTask zone.js:173
    drainMicroTaskQueue zone.js:581
    (Async: promise callback)
    nativeScheduleMicroTask zone.js:557
    scheduleMicroTask zone.js:568
    scheduleTask zone.js:392
    scheduleTask zone.js:216
    scheduleMicroTask zone.js:236
    scheduleResolveOrReject zone.js:1247
    resolvePromise zone.js:1184
    makeResolver zone.js:1100
    wrapper zone.js:1116
    (Async: promise callback)
    wrapped zone.js:1489
    ZoneAwarePromise zone.js:1411
    then zone.js:1488
    open viewer-4.0.728.min.mjs:21
    invoke zone.js:368
    run zone.js:129
    scheduleResolveOrReject zone.js:1257
    invokeTask zone.js:402
    runTask zone.js:173
    drainMicroTaskQueue zone.js:581
    (Async: promise callback)
    nativeScheduleMicroTask zone.js:557
    scheduleMicroTask zone.js:568
    scheduleTask zone.js:392
    scheduleTask zone.js:216
    scheduleMicroTask zone.js:236
    scheduleResolveOrReject zone.js:1247
    resolvePromise zone.js:1184
    makeResolver zone.js:1100
    wrapper zone.js:1116
    (Async: promise callback)
    wrapped zone.js:1489
    ZoneAwarePromise zone.js:1411
    then zone.js:1488
    _setupFakeWorker pdf-4.0.728.min.mjs:21
    terminateEarly pdf-4.0.728.min.mjs:21
    onWorkerError pdf-4.0.728.min.mjs:21
    invokeTask zone.js:402
    runTask zone.js:173
    invokeTask zone.js:483
    invokeTask zone.js:1631
    globalCallback zone.js:1662
```
production on iOS 16.5

```
[log] - Warning: Setting up fake worker.
⚡️  [error] - Beim Laden der PDF-Datei trat ein Fehler auf.

PDF.js v4.0.728 (build: d5cf764cb)
Message: Setting up fake worker failed: "Importing a module script failed.".
```

My asset folder looks like this:

<img width="734" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/1049938/d1c6dce5-8304-4a19-9d27-4938d0518eb1">

**Comment by stephanrauh** [comment]
@the-dev-adonis OK, you're right, version 18 accidentally contains version 4.0 of the PDF viewer. I can fix this when I publish version 18 again. However, I don't want to do that now. Switching between the versions is always an error-prone task, and it takes a lot of time. That's why I started shipping the wrong files in the first place.

However, the unused files don't do any harm (except wasting disk space and probably deteriorating my carbon footprint). I suggest you simply add the `ignore` pattern to the glob of your `angular.json`, pretty much the way Michael described above, only the other way round. You'll want to exclude the 4.0* files.

**Comment by stephanrauh** [comment]
@moberwasserlechner Please update to version 19.0.3. Now the minified worker is loaded unless `[minifiedJSLibraries]="false"`.

<img width="580" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/5a3ef9e2-cf4e-49db-89ee-e506bf1baff1">

**Comment by moberwasserlechner** [comment]
Hi @stephanrauh,

using version `19.0.3` with the minimized files all my test PDFs render correctly although these error messages still appear.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/1049938/b13c0fa0-cf57-42ba-9cad-ce0d34bd34d9)

The lib tries to load the non-minimized file for `sandbox` and as it is not there fails.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/1049938/9d6450da-4028-4abf-9639-486bef8c5d59)

This is my assets config in `angular.json` using the minimized files, no es5 and 2 languages (de, en):

```
              {
                "glob": "**/*.min.{js,mjs}",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/",
                "ignore": [
                  "**/*es5.*"
                ]
              },
              {
                "glob": "op-chaining-support.js",
                "input": "node_modules/ngx-extended-pdf-viewer/assets",
                "output": "/assets"
              },
              {
                "glob": "**/locale.json",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale",
                "output": "/assets/locale"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale/de",
                "output": "/assets/locale/de"
              },
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale/en-US",
                "output": "/assets/locale/en-US"
              },
```

Finally some very small issues I caught while testing:

* Although I'm on version `19.0.3` this log message still shows `19.0.2` due to the version setting in `viewer-4.0.728.mjs`L6639
```
PDF 72bad61efb8038f04b4164025a1c34f5 [1.5 OpenPDF 1.3.34 / Team Conductor] (PDF.js: 4.0.728 [d5cf764cb])  modified by ngx-extended-pdf-viewer 19.0.2 [ngx-extended-pdf-viewer.mjs:5875:24](webpack:///node_modules/ngx-extended-pdf-viewer/fesm2022/ngx-extended-pdf-viewer.mjs)
```
* My `logLevel` is on `VerbosityLevel.ERRORS` but the above log message is still shown. So are a punch of others but I guess that's a pdf.js issue.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/1049938/1414c794-ff14-4692-b4df-8d90611b8c22)

None of the above prevents me from using the lib so please no rush ;). I'm really grateful that you build such great library and reacted that fast. Thanks again.

**Comment by KillerCodeMonkey** [comment]
for newer version you also need the `assets/op-chaining-support.js` file

**Comment by stephanrauh** [comment]
If everything goes according to plan, you won't need the `op-chaining-support.js` file in version 21. I've got an idea how to do it in memory.
