### ISSUE TITLE
"Error in print preview display."

### ISSUE THREAD

**Issue by luisuyasan** [stephanrauh/ngx-extended-pdf-viewer#2012]
**I need your help!**
"I have a problem, and it's that when I click on the printer icon in the PDF, when the print modal opens, it's showing the entire page, and I need it to only show the PDF. Please help, I haven't been able to solve it. Thank you."

**Comment by stephanrauh** [comment]
This sounds like a CSS problem. More likely than not, your CSS framework overrides the CSS rules of the PDF viewer.

Please have a look at https://pdfviewer.net/extended-pdf-viewer/troubleshooting (and scroll down to the "Trouble with printing" section), where I've collected some common problems and workaround, plus a strategy how to debug the problem so you can solve it yourself.

**Comment by stephanrauh** [comment]
I've closed the issue because I hope you can solve the issue now yourself - but if you've still got trouble, don't hesitate to add your comments below.
