### ISSUE TITLE
Impossible to delete texts and drawings  on mobile devices (IOS, Andorid)

### ISSUE THREAD

**Issue by Giuseppe-EyesEurope** [stephanrauh/ngx-extended-pdf-viewer#2016]
Hi, 
the problem encountered is the impossibility of deleting any data entered using the text or drawing insertion function.

Once you have inserted/drawn something, using mobile devices  (although it is possible to select the data) it is not possible to delete it.  **Note**: if we use the plugin on a browser it is possible using the delete key on the keyboard.

It's therefore impossible to somehow delete what has been inserted with the text and drawing functions!

We checked the documentation and there is no "roll-back" button or even better a "delete selection".
Can you help us in any way or give us more information?

**Version info**
- Version of ngx-extended-pdf-viewer: 18.1.13

**Comment by stephanrauh** [comment]
@Calixteman Some time ago, we've already talked about the missing delete functionality on mobile devices. As far a I remember, you said Mozilla doesn't intend to implement such a functionality. However, the editor is evolving rapidly, so maybe I'm not up-to-date anymore. What's the current state of the art?

**Comment by Giuseppe-EyesEurope** [comment]
Hi, I was considering opening for pdfjs (https://github.com/mozilla/pdf.js/issue), but first I tried using the demo on git from mobille (https://mozilla.github.io/ pdf.js/web/viewer.html) and, in this, by selecting what has been entered, a delete button appears (see attached photo), which however does not currently appear in the plugin. It is possible to insert it as it currently works on pdfjs.

![img-delete](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/153085258/75e1520e-2e8c-45a6-a5a4-570fc9043075)

**Comment by stephanrauh** [comment]
Awesome! More likely than not, I've simply missed a new CSS rule (or something like that). Thanks for pointing that out!

**Comment by stephanrauh** [comment]
I've started to update the CSS.

**Comment by stephanrauh** [comment]
Versions 17.0.7 and 17.1.0 now ship with the missing CSS.
