### ISSUE TITLE
The number of pages is not displaying, but only in the production environment.

### ISSUE THREAD

**Issue by voibhiv** [stephanrauh/ngx-extended-pdf-viewer#2034]
For some reason, when I'm in my production environment, the number of pages in the PDF is not being displayed. It works fine in the homologation and development environments. Can someone help me?

**Comment by voibhiv** [comment]
The page number should appear inside the PDF pages, in the footer.

**Comment by stephanrauh** [comment]
Can you add a screenshot, please?

**Comment by voibhiv** [comment]
#### TESTING ENVIRONMENT 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/60460526/6387f4ac-33b4-40b0-8c77-7c1b30a8e6a9)

#### PROD
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/60460526/f76e6deb-d2ea-49d7-b88e-4dd6627c56ad)

**Comment by voibhiv** [comment]
For some reason, the page numbers do not appear in the production environment. Unfortunately, I cannot share a complete image due to sensitive information.

**Comment by stephanrauh** [comment]
Obrigado! That's weird. The PDF pages are images. There's no reason why a part of this image - technically a `<canvas>` - is visible in one environment and invisible in the other.

What happens if you deactivate the text layer? Does the page footer disappear in the test environment?

**Comment by voibhiv** [comment]
How can i desactivate the text layer?

**Comment by stephanrauh** [comment]
You can also open your PDF file on my showcase (https://pdfviewer.net) and on Mozilla's showcase (https://mozilla.github.io/pdf.js/web/viewer.html). Does the page number show in these showcases?

As for deactivating the text layer: see https://pdfviewer.net/extended-pdf-viewer/textlayer. Basically, it's simply adding the attribute `[textLayer]="false"`.

**Comment by voibhiv** [comment]
Hey, the page numbers are doing great in showcases. 

Even tried [textLayer]="false", and it's cool. But in production? No clue what's going on there.

**Comment by voibhiv** [comment]
Is there a way to hide the footer today, or am I just having bad luck? Haha.

**Comment by stephanrauh** [comment]
The footer is part of your PDF file. Otherwise it wouldn't show in Mozilla's showcase. I assume it also shows in Acrobat and every other PDF reader.

Did you check the console and the network tab of your browser's developer tools? Are there any error messages in production?

**Comment by stephanrauh** [comment]
If you've got a PDF editor at hand, you can double-check if the footer belongs to the PDF file.

A wild shot: disable JavaScript. Maybe there's some JavaScript embedded in your PDF file generating the footer.

```ts
  constructor() {
    pdfDefaultOptions.enableScripting = false;
  }
  ```
  
  https://pdfviewer.net/extended-pdf-viewer/scripting

**Comment by voibhiv** [comment]
The console looks ok: 

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/60460526/3353be5b-830d-4f5a-a22e-34025b9a670e)

I try this enableScripting also and got the same :(

**Comment by voibhiv** [comment]
Haha, for some reason, when my user downloads the PDF, it also doesn't show the number of pages. That's really weird!

**Comment by stephanrauh** [comment]
I still wonder if the page footer is really part of your PDF file, or if there's some magic adding it. You can inspect the canvas in the DOM. My Firefox offers the feature "take a screenshot of this node", but I'm not sure if that's a feature of Firefox or if I've added a plugin. However, you can modify the size of the canvas. If the page footer starts to move, it's part of the PDF file, and there's no conceivable reason why it's missing sometimes.

I also wonder what happens when you print the PDF file.

**Comment by voibhiv** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/60460526/7b932178-e288-46a9-9983-3262130dcc47)

For some reason, it's appearing in testing, but in production, it doesn't show up. Idk why, haha.

**Comment by voibhiv** [comment]
> I still wonder if the page footer is really part of your PDF file, or if there's some magic adding it. You can inspect the canvas in the DOM. My Firefox offers the feature "take a screenshot of this node", but I'm not sure if that's a feature of Firefox or if I've added a plugin. However, you can modify the size of the canvas. If the page footer starts to move, it's part of the PDF file, and there's no conceivable reason why it's missing sometimes.
> 
> I also wonder what happens when you print the PDF file.

There is a way to resize the size of the canvas directly in the code?

**Comment by stephanrauh** [comment]
Your code snippet shows the text layer. The canvas is below the text layer. In the DOM, you usually find it above.

The `<span>` looks like every other `<span>` generated by pdf.js. In theory, you can even debug it: it's appended in the method `appendText()`.  There's only one such method in the entire project, so you can find it easily (unless you're using the minified version). However, the method is called very often, so debugging is probably not an option.

However, you can inspect the DOM of your production installation. Does the text layer show the footer?

Other ideas: maybe you've run into a caching problem and you're using different versions of the PDF engine. Or maybe the PDF file itself is different. What happens when you download the PDF file from production and open it in my showcase?

> There is a way to resize the size of the canvas directly in the code?

I was referring to the developer tools of the browser. There you can modify everything. It just won't survive the next page refresh - it's a debugging tool.

**Comment by voibhiv** [comment]
> Other ideas: maybe you've run into a caching problem and you're using different versions of the PDF engine. Or maybe the PDF file itself is different. What happens when you download the PDF file from production and open it in my showcase?

When I download the file from production, it doesn't appear. Very weird, especially considering that it works perfectly in my testing environments.

**Comment by voibhiv** [comment]
> #### TESTING ENVIRONMENT
> ![image](https://private-user-images.githubusercontent.com/60460526/292302642-6387f4ac-33b4-40b0-8c77-7c1b30a8e6a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODY5NDYsIm5iZiI6MTcwNDM4NjY0NiwicGF0aCI6Ii82MDQ2MDUyNi8yOTIzMDI2NDItNjM4N2Y0YWMtMzNiNC00MGIwLThjNzctN2MxYjMwYThlNmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE2NDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNTYzNjZkYjU4NDRjMjM2NDQxMTI4YWNiMmUwNjA2OGM0NjgwMjYxYWQ4ZmM2M2UyZDUxMzk4ODgwNTczOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uCCnAEOItNhG_T8O4k19ILJan_cnnfcqeQsdBrABRhI)
> 
> #### PROD
> ![image](https://private-user-images.githubusercontent.com/60460526/292302981-f76e6deb-d2ea-49d7-b88e-4dd6627c56ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODY5NDYsIm5iZiI6MTcwNDM4NjY0NiwicGF0aCI6Ii82MDQ2MDUyNi8yOTIzMDI5ODEtZjc2ZTZkZWItZDJlYS00OWQ3LWI4OGUtNGRkNjYyN2M1NmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE2NDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODEwY2QxNGYzZWViNmUzMmUxYzM0MmE0MWE3MDZmYjExYzdiOTVkOTcwNzJmM2IzMmMzYjgyZGM4YWEwZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i5DyReVCu2pf5KH4W7ZEW29-cFCTr5piSAhjcubIhC4)

How the pdf-viewer understand automatically this pages? it's by defaut? there's some way to access that?

**Comment by stephanrauh** [comment]
No idea. I'm pretty sure it has something to do with your particular PDF. The idea of PDF files is that they always look the same, no matter on which device you read it or on which printer you print it. Footers that are sometimes there and sometimes gone - well, that's not the idea of the PDF file format.

When you download the same PDF file from the test environment and the production environment, are these files identical? Maybe the files are modified by the environment or they are generated slightly differently.

**Comment by voibhiv** [comment]
Yes, they are! The problem is that this only happens in production. 

The PDF is not uploaded by the user; instead, we create a blob from a service and then load it into your viewer. It's built by my user.

**Comment by voibhiv** [comment]
Hey bro, good news! I found the problem, and it was on our side. We're using an API that transforms HTML into PDF, and the issue was in that API. Nothing to do with your library! Sorry for the lost time. I'll close the issue. Thanks for all the help!

**Comment by stephanrauh** [comment]
Awesome! I'm glad you've found the problem! Oh, and don't worry about wasting my time - helping other developer is part of the fun of open source. This time, I couldn't help much, but it was fun nonetheless. It's like solving a crossword puzzle. :)
