### ISSUE TITLE
Book mode zoom issue

### ISSUE THREAD

**Issue by That1GuyWhoSucks** [stephanrauh/ngx-extended-pdf-viewer#2035]
Howdy,

When using the "book" mode and quickly changing the page the zoom on the page gets changed to "1.7009803921568627" as seen by the "currentZoomFactor" event. Can be reproduced on the docs page here by clicking the right page or left page quickly. 
https://pdfviewer.net/extended-pdf-viewer/book-mode
I have not been able to find any workarounds. Both screenshots below were taken from the site above before and after the bug respectively.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/79329354/a7a420fc-4810-41d5-b530-6ca65e0b4d00)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/79329354/9474a1a0-8a8e-49fe-8d2e-143a3ce0ee1c)

**Comment by stephanrauh** [comment]
Yes, zooming in or out is broken. But maybe there's a workaround. You can force initializing the PDF viewer by hiding it and showing it a fraction of a second later. Maybe this approach also works when called during the `(zoomChange)` event.

```

**Comment by That1GuyWhoSucks** [comment]
This alone does not appear to work, I added a `visible` var to the component and tried both using the `hidden` and `ngif` to hide the component. Both resulted in errors upon trying to reload, maybe it will work with more tinkering but I'm hoping there is a more simple solution. Perhaps is it possible just rate limit the amount of page turns per second?

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.
