### ISSUE TITLE
Custom PdfJs on Stable branch

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2037]
I'm customizing your pdfJs on the 3.10 stable branch. I see you deleted the webServer file in the test folder so I can't run it. Is there a way for me to generate that webServer file?

**Comment by stephanrauh** [comment]
You can find the missing files upstream: https://github.com/mozilla/pdf.js

I've deleted the files after running into countless annoying merge conflicts. I never run the test suite of pdf.js, so I that only slowed me down. While I'm writing this, I wonder if my forks passes the tests of pdf.js. I've modified the base library in quite a few places. Most of the time I've added functions, so there shouldn't be problems, but I'm not sure.
