### ISSUE TITLE
Error Custom

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2038]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/29aadae5-6e2e-4ea6-845a-e550322482d3)

**Comment by Congchuabongbong** [comment]
I've imported CommonModule and done everything I can but I can't fix it

**Comment by Congchuabongbong** [comment]
I'm cloning your 18.1.x branch and running npm start. Then I go to the dist folder and run npm pack then I install the packed library. It has the error as shown in the photo. I have checked it quite carefully but don't know the cause of the error

**Comment by Congchuabongbong** [comment]
I'm customizing some functionality in pdfJs on your 3.10 branch. and after customizing I used branch 18.1.x of your ngx-extended-pdf to build it but it seems like it's not working or am I missing any steps? I am using angular 16 and node 18. After installing the custom library, I get the above error! But I installed it on the Angular 13 project and didn't have any problems? please help me!!!

**Comment by Congchuabongbong** [comment]
Is it due to this problem? related to aot?
https://github.com/angular/angular/issues/45378

**Comment by stephanrauh** [comment]
I suppose you've managed to find and solve the issue?

For everyone who stumbled upon this ticket in future: you find the walkthrough here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md.
