### ISSUE TITLE
Good idea for customizing additional functions or modifying the functions of buttons on the toolbar.

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2039]
Currently I want to add more function buttons on the toolbar, I have to do the following steps:
1. I have to add more logic in the PdfJs core library (so 
Of course I will also build the library following your steps
 this is required ).
2. I have to create a toolbar identical to your toolbar to ensure other functions are still present and then add some buttons related to the functions I add or customize.
So is there any way to optimize or make it easier to customize or add more functions while still keeping the remaining functions intact?

**Comment by Congchuabongbong** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/aeb48a78-bc4b-44cb-9299-19787bd71716)
Also, I don't know if this is an error or not, but I have to set customToolbar via @Input for it to work, but the use of viewChild as shown below does not! I tried copying your toolbar exactly and haven't customized anything but it still doesn't work when I set it via ngAfterViewInit in my project but via @Input as shown above it works.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/c086b184-c9a6-4115-9d85-e1d868dd803b)

**Comment by stephanrauh** [comment]
I don't think you need to modify the core library, pdf.js. You only need to do this if you want to display the PDF file differently.

Most users are happy with the TypeScript API. Did you already find my documentation?
https://pdfviewer.net/extended-pdf-viewer/customization and https://pdfviewer.net/extended-pdf-viewer/custom-toolbar

I admit this part of the documentation isn't great - if you have ideas how to improve it, or if you don't understand it, please tell me. Feedback helps me improving it.

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.
