### ISSUE TITLE
Change zoom causes zoom level label to not show correctly

### ISSUE THREAD

**Issue by Blunderchips** [stephanrauh/ngx-extended-pdf-viewer#2045]
Not stopping us from using the library at all just looks a little weird :)

**Describe the bug**

Scroll zooming on documents causes the zoom label to not show. To replicate, go to a document and hold the control key and scroll up and down. On "normal" zoom levels a label shows (125%, 100%, 50%, etc.)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/f17a3ac1-fa65-4eb3-850a-963306f1e153)
Zooming in on Brave browser

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/f826b8ae-aab0-49a8-886f-f65c97c45b4b)
Zooming in on Google Chrome

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/8d545c5f-025f-4e4b-955e-8b1413add315)
Zooming out to 100% (Brave)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/33868322-7cb2-4161-b927-0515c797250e)
Zooming out (Brave)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/84981edf-2160-475c-a2ed-a42060e6dbe9)
Zooming out to 125% (Google Chrome)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/8dd3fafd-34bb-4da0-95a8-742bdd70011f)
Instrestily, on our application we see a `NaN%`. (Brave)

**Version info**
- Version of ngx-extended-pdf-viewer: `19.0.2`

**Comment by stephanrauh** [comment]
Holy moly... you right!

**Comment by stephanrauh** [comment]
What's even more surprising: it still works properly on https://pdfviewer.net/extended-pdf-viewer/zoom. Maybe the difference if the space between the number and the percentage sign. There's no such space in the zoom demo.

**Comment by stephanrauh** [comment]
Version 19.0.4 is going to fix this soon.

**Comment by Blunderchips** [comment]
Thank you! Lemme know if/when you need a hand testing :)

**Comment by stephanrauh** [comment]
I've published the new version, but after that, I observed that initially the dropdown shows "NaN%" again, at least in the i18n demo. Adding insult to injury, in the i18n the zoom jumps from "auto" to "10%" when I hit the "-" button. So I'm reopening the ticket again... :)

**Comment by stephanrauh** [comment]
Version 19.0.5 solved the issue (at least mostly - the NaN% is visible for a very short time).
