### ISSUE TITLE
Extra break lines are ignored when PDF is loaded

### ISSUE THREAD

**Issue by artstalker** [stephanrauh/ngx-extended-pdf-viewer#2054]
The bug is reproducible on https://pdfviewer.net/extended-pdf-viewer/forms (Running on Angular 17.0.8, pdf.js 4.0.730, and ngx-extended-pdf-viewer 19.0.4)

1. Open Forms demo
2. Add a line break in other Job Experience field between any items

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2846956/322e8bdc-e2e9-49a4-b185-f1f7a95f44ec)

3. Save the PDF file.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2846956/7402b739-0971-4c02-8ced-6567b267462e)

4. Open the saved PDF file.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2846956/4a87893a-d2f4-4b06-be5e-0874c30123f4)

Expected result: The extra line break we added is displayed
Actual result: The extra line break is gone

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2846956/4309c29e-9683-4905-a226-9566383acc68)

If you open a saved PDF in any PDF viewer, the extra line break is displayed there, but when opened in ngx-extended-pdf-viewer, extra line breaks are gone.
Is it some option that can be disabled in the configuration, or is it a bug?

**Comment by stephanrauh** [comment]
You're right. I guess it's a bug of the base library, pdf.js. I can reproduce it both in Firefox and on https://mozilla.github.io/pdf.js/web/viewer.html. The screenshot shows the same document in Firefox (background) and in the "preview" application of MacOS:
<img width="1587" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/46015d04-3cbd-41a1-b655-0226a5f69d88">

Please report the bug at https://github.com/mozilla/pdf.js/issues. Make sure to fill their bug form meticulously and tell them you've managed to reproduce the bug in Firefox. They often close tickets for formal reasons, so it's important to mention Firefox.

**Comment by artstalker** [comment]
Thanks Stephan,

I logged the ticket https://github.com/mozilla/pdf.js/issues/17492
