### ISSUE TITLE
Does it work with CSP(Content Security Policy)?

### ISSUE THREAD

**Issue by binbinwinwin** [stephanrauh/ngx-extended-pdf-viewer#2055]
Hi,

After I set CSP to my project, It seems that CSP will block the pdf plugins.

So I want to know that the ngx-extended-pdf-viewer have any solution to this problem?(ex: set the nonce value)

![CSP](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/28702502/e51d0768-fad8-478d-9df8-292acf1a686a)

**Comment by stephanrauh** [comment]
I'm not aware of any inline scrips. Can you open the debugger and tell me what happens in line 1148, please?

**Comment by binbinwinwin** [comment]
> I'm not aware of any inline scrips. Can you open the debugger and tell me what happens in line 1148, please?

Sure, here's it is.
![0](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/28702502/b64c6b1d-a991-49c3-af11-40a296b5d6fe)

**Comment by stephanrauh** [comment]
I see. Yes, maybe I can do something about it. Generally speaking, I don't think that the PDF viewer supports CSP well. It requires too many exception because it supports too many feature. A tentative CSP declaration might be this:

```
<meta http-equiv="Content-Security-Policy" content="connect-src 'self' blob;script-src 'wasm-unsafe-eval';default-src 'self' 'unsafe-inline'; img-src 'self' data:;require-trusted-types-for 'script';">
```
(plus an exception to load code from localhost and your target domain, but I couldn't figure out the syntax. Maybe you can help me?)

**Comment by binbinwinwin** [comment]
> I see. Yes, maybe I can do something about it. Generally speaking, I don't think that the PDF viewer supports CSP well. It requires too many exception because it supports too many feature. A tentative CSP declaration might be this:
> 
> ```
> <meta http-equiv="Content-Security-Policy" content="connect-src 'self' blob;script-src 'wasm-unsafe-eval';default-src 'self' 'unsafe-inline'; img-src 'self' data:;require-trusted-types-for 'script';">
> ```
> 
> (plus an exception to load code from localhost and your target domain, but I couldn't figure out the syntax. Maybe you can help me?)

The declaration below is my CSP declaration

<meta http-equiv="Content-Security-Policy" content="default-src 'self' https://example.com/; style-src 'self' 'nonce-example'; script-src 'self' 'nonce-example'; img-src 'self' data:;">


The 'unsafe-inline' can let the CSP allows different source's css and scripts and make the PDF viewer work with CSP, but it's not safe so I can't use it.

The solution for me is to set (nonce) value to let CSP allows the PDF viewer's sources.
So is it possible that we can add nonce value into the <style></style> tag?

**Comment by stephanrauh** [comment]
Yes, I think that's possible, but I don't know which value the nonce attribute should have. The documentation reads like it's a random number that has to change with every request. But that doesn't make sense?

**Comment by binbinwinwin** [comment]
> Yes, I think that's possible, but I don't know which value the nonce attribute should have. The documentation reads like it's a random number that has to change with every request. But that doesn't make sense?

Actually, the purpose of setting a random number is to prevent attackers from easily guessing the corresponding nonce value. Therefore, we just need to set an attribute (nonce) for the PDF viewer, and ensure its value can match with the CSP.

ex:
html -> <style nonce="example123"></style>
CSP -> <meta http-equiv="Content-Security-Policy" content="style-src 'self' 'nonce-example123'">

**Comment by stephanrauh** [comment]
When I publish version 19.4.0, the PDF viewer works with this configuration:

```html
<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types default pdf-viewer dompurify angular angular#unsafe-bypass angular#bundler; default-src 'self'; script-src 'self' *; connect-src *; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src *; object-src 'none'">
```

**Comment by stephanrauh** [comment]
The improved CSP support has shipped with version 19.4.0.

**Comment by EpicVoyage** [comment]
I am working on a patch which will remove the requirement for `unsafe-inline` - at least for the features I am using.

**Comment by stephanrauh** [comment]
I'm looking forward to your solution!

**Comment by stephanrauh** [comment]
Short update:
I'm using this CSP declaration:
```html
<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types default pdf-viewer dompurify angular angular#unsafe-bypass angular#bundler; default-src 'self'; script-src 'self' *; connect-src *; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; frame-src *; object-src 'none'">
```

That's quite a long list of exceptions. If you know how to make it shorter, please tell me. I'd like to use the CSP declaration for the showcase, but I can't because ngx-markdown isn't compatible with CSP (or I'm too stupid to configure it properly :) ).

**Comment by EpicVoyage** [comment]
Certainly, I will plan to make time to look at this next week.

**Comment by stephanrauh** [comment]
@EpicVoyage Thanks in advance! It'd be a lot easier if I could run the showcase with CSP, but until I manage to do so, I appreciate your help! Please use version 22.1.0-alpha.2 or later, I've fixed a couple of CSP problems in this version.

**Comment by EpicVoyage** [comment]
Hey Stephan, I have loaded this a couple of times to test the CSP functionality but our site is still using Angular 16, which limits my testing. I will plan to revisit this once we have a chance to upgrade.
