### ISSUE TITLE
Add a title and image/graphic above tool bar

### ISSUE THREAD

**Issue by randyparis** [stephanrauh/ngx-extended-pdf-viewer#2064]
I'm trying to find a way to add a custom title/name and graphic(icon) to the viewer above the toolbar as a sort of header/descriptor. Right now I'm loading the viewer into an iframe in an html which contains the viewer which seems to take forever to load. Here's a link to a sample of that 'solution'. https://www.randyparis.com/RPArchive_update/assets/writing/manuscript_pdfs/ngx-pdf-viewer/index.html?pdf=WG
Hoping for something that would look similar but just be a straight viewer load, which I'm guessing would speedup the load/display.

**Comment by stephanrauh** [comment]
I'm afraid something's wrong with your server. Even your front page is remarkably slow. You've optimized the page so most people won't even notice, but looking at the network tab it seems the server sends only a few dozen kilobytes per second. I've doublecheck with https://www.webpagetest.org/. In the US, the speed seems to be better, but it's not good.

Using an iFrame shouldn't be a problem. I'm using the approach myself here: https://pdfviewer.net/extended-pdf-viewer/side-by-side. To my surprise, the demo is currently broken, but even so you can watch the downloads and initialization in the developer tools. It's a lot faster than your demo.

However, I don't have a clue how to make your server faster. A small improvement is activating gzip or Brotli. Caching and range requests are already active, so the second time I visit your demo I can start reading after 10 seconds (as opposed to several minutes with an empty cache).

As for your question: no, that's not possible. But I don't see why you need it. Nor do I see why you need the iFrame. You can move the header and the image to the Angular application. I've simulated it using the developer tools, and it worked like charm.

**Comment by stephanrauh** [comment]
I'm not sure if you did anything - but today, your demo page is a lot faster. With cache disabled, today it loads within 9 seconds. Yesterday it was between 2 and 3 minutes.

**Comment by randyparis** [comment]
Thank you for checking again. It seems to be idiosyncratic. It loaded a little quicker for me as well. But not by much. 
I really appreciate your responsiveness to all this.

I got the heading and then a blank viewer until the pdf popped into view. I’m wondering if there’s a way to show the pdf loading progress while the viewer is blank like that. At least give a user a sense it’s not broken.

I filed a trouble ticket with my provider and this is the response I got:

Thanks for the update and patience, the Markup Languages like HTML and CSS are interpreted on client side. With your plan of action by delegating a huge PDF file interpreted through HTML on the client side is definitely going to take some time. We can see that if we visit the URL you have mentioned, the half of the page loads instantly but the PDF part takes its time. I think with a 66 paged PDF file loading in client browser in few seconds is normal. The next time it loads quickly from browser cache.

(I’m also in process of putting that header stuff into the html component)


Randy

**Comment by stephanrauh** [comment]
As for the loading spinner: there used to be a loading spinner, but the Mozilla team removed it for some reason unknown. However, you can build your own loading spinner:

- Here's a nice introduction to writing loading spinners: https://medium.com/@christianlydemann/the-four-ways-to-create-loading-spinners-in-an-angular-app-a5938b67752d
- I stopped reading after reviewing the first spinner. It seems to do the trick. Add an `*ngIf` to the `<div id="loader">`and tie it to a TypeScript variable which is initially true: `<div id="loader" *ngIf="isLoading">`.
- Capture an event like `(pdfLoaded)` or `(pageRendered)`. The event listener simply sets `isLoading = false;`.

You can also use the event `(progress)` to track the progress in percent.

**Comment by randyparis** [comment]
Thanks, Stephan,

I think a percent progress indicator would be great, and I tried implementing that. But I kept getting errors when I included the event in the <ngx-extended-pdf-viewer> tag per your showcase example.  I’m not an accomplished Angular/TS user, so I probably messed up the  @Component({ … }) example, not understanding what to put within the brackets or where/how to instantiate it.

If you could clarify that or point me to a more rudimentary or detailed explanation of a working progress percent sample somewhere else, I would much prefer implementing that over a spinner.

Meanwhile I will definitely check out that link. If nothing else I could probably get it to display a ‘loading’ message.

Again, your geeroust attention to my little project is very much appreciated.

Randy
