### ISSUE TITLE
Cannot deploy the latest version 19.0.x

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#2065]
Hi,
I've tried the latest version of the module. It works fine with 'ng serve but when I compile it the pdf is not shown.
I did not change the procedure since a while and it works fine with the version 18.

What should I change in the build to make it work?
Thanks
Luc

**Comment by stephanrauh** [comment]
Bonsoir Luc, maybe it's the same problem as #2066. The base library now uses *.mjs files instead of *.js files. Sometimes this requires extra configuration.

If that's not the problem, can you see something in the console or the network tab?

**Comment by lucho78** [comment]
Thanks for your reply Stephan but there is something weird on my side:
Here the network traces on my browser:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/14161954/d91ec6fd-3838-4752-a602-f9320b7d454b)

Why the viewer file is not downloaded like in the previous version:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/14161954/7af1acd1-d85a-4ab5-89fa-be25aee4816a)

I've checked and my assets folder contains all the files needed
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/14161954/21434696-0f4c-4943-8a74-f940d374c482)

Any suggestions?
Thanks  a lot
Cheers
Luc

**Comment by stephanrauh** [comment]
I'm confused. The preview tab in your screenshot seems to indicate the JavaScript file is downloaded, but you say it's not?

The only idea crossing my mind is that the file ending has changed to `*.mjs`. JavaScript interprets `mjs` files differently than `*.js` files, so that's nothing I can change. Maybe your server needs additional configuration to ship this file as a JavaScript file.

**Comment by lucho78** [comment]
Sorry my previous message was not very clear.
Basically the file pdf-4.xx.min.mjs is correctly downloaded. 
But the file **viewer-4.0.730.mjs is not included in the DOM** so not downloaded on the local machine.

For your information, I'm doing the test with a local server (local tomcat embedded in Spring boot)

**Comment by stephanrauh** [comment]
I see. Please add a breakpoint at the `loadViewer()` method. Is it ever called?
<img width="695" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/f900e018-763d-4d72-9457-e31a5e0a52f5">

Until recently, I always found the method by opening the file `ngx-extended-pdf-viewer.mjs`, but it seems in production mode you have to find the method in the `main.js`.

**Comment by lucho78** [comment]
Hi Stephan,
First thanks a lot for your support. I really appreciate :-)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/14161954/950fa604-1201-4922-817d-761a651c5830)
It seems that the method "script.onload" is never triggered for me.
The code on the line 400348 is never called. So the method "loadViewer" is never called.

Any idea?
Thanks
Luc

**Comment by stephanrauh** [comment]
No idea. If the first `<script>` is added properly to the DOM and if it triggers loading the pdf.js file, and if that's successful, it's hard to imagine why `onload()` is not called. That's a basic JavaScript functionality.

Did you try different browsers? And did you try `[minifiedJSLibrary]="false"`? Maybe it has something to do with a virus scanner or an ad blocker (but that's a far shot).

**Comment by stephanrauh** [comment]
You could also try to update to version 19.0.6. It fixes the viewer if it's running in an iFrame. Maybe the same bug fix helps you, too.

**Comment by lucho78** [comment]
I've tried with the version 19.0.6 with the parameter [minifiedJSLibrary]="false".
I get the same behavior with chrome.

With firefox, I get the following exception:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/14161954/229a86da-4bbe-4414-8923-439eff4c6a04)
Same behavior if [minifiedJSLibrary]="true"...

Any other ideas?
Thanks a lot
Luc

**Comment by stephanrauh** [comment]
Yes, I'm back to my first theory. You must configure Spring Boot correctly. It seems it isn't familiar with *.mjs files. Something along these lines. I didn't test them, they may be buggy, but you get the idea:

```java
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/**/*.mjs")
                     ...
    }

    @Override
    public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
        configurer.mediaType("mjs", new MediaType("text", "javascript"));
    }
}
```

**Comment by lucho78** [comment]
Super thanks a lot for your great support. The following config on Spring boot solves my issue.
 @Override
    public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
        configurer.mediaType("mjs", new MediaType("text", "javascript"));
    }
