### ISSUE TITLE
Not loading in production (IIS) environment

### ISSUE THREAD

**Issue by drullo** [stephanrauh/ngx-extended-pdf-viewer#2066]
The viewer works great in development.  But once it's deployed to production, it fails to show the document.  It seems to partially render the viewer, but the document isn't there and there's an error in the console that indicates that it can't find the mjs file.  If have confirmed that the asset files are properly deployed to the production environment.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/10358672/0b8f0b69-ba49-481c-a82c-9404f97507e8)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/10358672/f39bec21-51bf-411b-b8f8-4e7bf45677bf)

I don't know if it matters, but my Angular router is configured with `useHash: true`.  I don't know if that somehow confuses the pdf viewer, regarding the path of the .mjs files.  But the path that it refers to in the error above, does not include the hash symbol (#) that the URL contains throughout the app.

**Comment by drullo** [comment]
I figured it out.  I just had to define a MIME type for .mjs files in my IIS environment.

**Comment by stephanrauh** [comment]
Interesting. I'm glad you've figured it out!

For the record: `useHash: true` plays well with the library.
