### ISSUE TITLE
pre load some images on the pdf

### ISSUE THREAD

**Issue by bryanwac** [stephanrauh/ngx-extended-pdf-viewer#2068]
Hi, I would like to load some images on the pdf without using the load image button, they would be rendered with the pdf, is it possible ? Could not find docs abt it.

Would like to:
 Load some images right inside the pdf OR add the images to a list and drag/drop'em to the pdf

**Comment by stephanrauh** [comment]
I'm afraid that's beyond the scope of the library. You could try to request the feature at the base library pdf.js: https://github.com/mozilla/pdf.js/issues
