### ISSUE TITLE
The viewer is broken if [src] is omitted

### ISSUE THREAD

**Issue by bryanwac** [stephanrauh/ngx-extended-pdf-viewer#2071]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/dff23a10-8d22-401b-bdec-a1eff9898d9e)
the image above shows how my html is rn and I'm trying to get the page render and rendered, and tryied to get the pdfLoaded and it did not work as well.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/e83cf233-2d58-4494-acd1-151c44d3d0b2)
Both logs on the print above are not showing, my project is runnin angular 16

**Comment by bryanwac** [comment]
this are my versions:


  "dependencies": {
    "@angular/animations": "^16.2.12",
    "@angular/cdk": "^16.2.12",
    "@angular/cli": "^16.2.11",
    "@angular/common": "^16.2.12",
    "@angular/compiler": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/forms": "^16.2.12",
    "@angular/google-maps": "^16.2.12",
    "@angular/material": "^16.2.12",
    "@angular/material-moment-adapter": "^16.2.12",
    "@angular/platform-browser": "^16.2.12",
    "@angular/platform-browser-dynamic": "^16.2.12",
    "@angular/router": "^16.2.12",
    "@asymmetrik/ngx-leaflet": "^16.0.1",
    "@babel/runtime": "^7.23.8",
    "@fullcalendar/angular": "^6.1.10",
    "@fullcalendar/core": "^6.1.10",
    "@fullcalendar/daygrid": "^6.1.10",
    "@fullcalendar/interaction": "^6.1.10",
    "@fullcalendar/list": "^6.1.10",
    "@fullcalendar/timegrid": "^6.1.10",
    "@ng-select/ng-select": "^11.2.0",
    "@tinymce/tinymce-angular": "^7.0.0",
    "@types/google-maps": "^3.2.2",
    "@types/leaflet": "^1.9.8",
    "apexcharts": "^3.41.0",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^3.31.0",
    "crypto-js": "^4.1.1",
    "fs": "0.0.1-security",
    "html2canvas": "^1.4.1",
    "install": "^0.13.0",
    "jquery": "^3.7.0",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.8.1",
    "leaflet": "^1.9.4",
    "leaflet-control-geocoder": "^2.4.0",
    "leaflet-routing-machine": "^3.2.12",
    "moment": "^2.24.0",
    "ng-apexcharts": "^1.6.0",
    "ng2-currency-mask": "^13.0.3",
    "ngx-doc-viewer": "^2.0.5",
    "ngx-dropzone": "^3.0.0",
    "ngx-extended-pdf-viewer": "^19.0.4",
    "ngx-mask": "^16.4.2",
    "ngx-mat-select-search": "^7.0.5",
    "ngx-owl-carousel-o": "^16.0.0",
    "npm": "^8.19.4",
    "path": "^0.12.7",
    "popper.js": "^1.15.0",
    "rxjs": "^7.8.1",
    "socket.io-client": "^2.5.0",
    "togeojson": "^0.16.0",
    "tooltip.js": "^1.3.2",
    "tslib": "^2.6.0",
    "xlsx": "^0.14.5",
    "zone.js": "^0.13.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.11",
    "@angular/compiler-cli": "^16.2.12",
    "@angular/language-service": "^16.2.12",
    "@fortawesome/fontawesome-free": "^6.4.0",
    "@types/googlemaps": "^3.43.3",
    "@types/jasmine": "^3.7.0",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "css-loader": "^6.9.0",
    "gulp-sass": "^4.0.2",
    "jasmine-core": "^3.8.0",
    "jasmine-spec-reporter": "^5.0.0",
    "karma": "^6.4.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "^4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "^7.0.0",
    "style-loader": "^3.3.4",
    "ts-node": "^8.3.0",
    "tslint": "^6.1.0"
  },
  "type": "module"
}

**Comment by stephanrauh** [comment]
At first glance, your code looks good. Compare it to https://pdfviewer.net/extended-pdf-viewer/pages-loaded. This demo shows the events that are emitted. Since updating to pdf.js 4.0 some events seem to have gone, but the events you've mentioned should still be there.

**Comment by bryanwac** [comment]
tryied almost all of this list, none works. leme show u my full component:
this is what I did, place annotations, remove it, but cant really use the standard events that r available in the selector

`
import { ChangeDetectionStrategy, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { FreeTextEditorAnnotation, Line, NgxExtendedPdfViewerComponent, NgxExtendedPdfViewerService, PdfLoadedEvent, pdfDefaultOptions } from 'ngx-extended-pdf-viewer';
import { PageRenderEvent } from 'ngx-extended-pdf-viewer/lib/events/page-render-event';

@Component({
  selector: 'app-pdf-viewer',
  templateUrl: './pdf-viewer.component.html',
  styleUrls: ['./pdf-viewer.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PdfViewerComponent {

  public addedAnnotations: any[] = [];
  public pageIndexControl: FormControl = new FormControl;

  @ViewChild('pdfViewer', { static: false }) pdfViewer: NgxExtendedPdfViewerComponent;

  constructor(private pdfService: NgxExtendedPdfViewerService, private el: ElementRef) {
    pdfDefaultOptions.doubleTapZoomFactor = '150%'; // O valor padrão é '200%'
    pdfDefaultOptions.maxCanvasPixels = 4096 * 4096 * 5; // O valor padrão é 4096 * 4096 pixels,
  }

  public async addTextEditorForPage(pageNumber: number): Promise<void> {
    const pageSize = await this.getPageSize(pageNumber);
    console.log(`Page ${pageNumber} - Orientation: ${pageSize.orientation}`);

    const lines = await this.pdfService.getPageAsLines(pageNumber);
    const firstLineHeight = lines.length > 0 ? lines[0].height : 0;

    const rectWidth = pageSize.orientation === 'landscape' ? lines[lines.length - 1].width - 20 : firstLineHeight;

    const textEditorAnnotation: FreeTextEditorAnnotation = {
      annotationType: 3,
      color: [0, 0, 0],
      fontSize: 13,
      value: `ABCABCABC TEST`,
      pageIndex: pageNumber - 1, // Índices de página começam do 0
      rect: [
        100, // espaço entre a borda da esquerda e o texto
        0,
        0,
        rectWidth,
      ],
      rotation: 0,
    };
    this.addedAnnotations.push(textEditorAnnotation);
    this.pdfService.addEditorAnnotation(textEditorAnnotation);
  }

  getAllAnnotations() {
    console.log(this.pdfService.getSerializedAnnotations());
  }

  removeAnnotationsType3() {
    const filter = (serial: any) => serial.annotationType === 3;
    this.pdfService.removeEditorAnnotations(filter);
  }

  removeAnnotationOnPage() {
    const filter = (serial: any) => serial.pageIndex === this.pageIndexControl.value - 1;
    this.pdfService.removeEditorAnnotations(filter);
  }

  public async addTextEditorsForAllPages(): Promise<void> {
    const pageCount = this.pdfService.numberOfPages();

    for (let i = 1; i <= pageCount; i++) {
      await this.addTextEditorForPage(i);
    }
  }

  private inferOrientation(lines: Line[]): 'portrait' | 'landscape' {
    const totalWidth = lines.reduce((sum, line) => sum + line.width, 0);
    const totalHeight = lines.reduce((maxHeight, line) => Math.max(maxHeight, line.height), 0);

    return totalWidth > totalHeight ? 'portrait' : 'landscape';
  }

  private async getPageSize(pageNumber: number): Promise<{ width: number; height: number; orientation: 'portrait' | 'landscape' }> {
    const lines = await this.pdfService.getPageAsLines(pageNumber);
    const pageWidth = lines.reduce((maxWidth, line) => Math.max(maxWidth, line.width), 0);
    const pageHeight = lines.reduce((totalHeight, line) => totalHeight + line.height, 0);
    const orientation = this.inferOrientation(lines);
    console.log(lines)
    console.log(orientation);
    return { width: pageWidth, height: pageHeight, orientation };
  }

  public onPageRender(event: any): void {
    console.log('page render waiting', event);
  }

  public onPageRendered(event: PageRenderEvent): void {
    console.log('event=' + event)
  }

  public onEvent(event: PdfLoadedEvent): void {
    console.log(this.pdfViewer.pdfLoaded)
    console.log('pdfLoad=' + event)
  }

  public pageChange(event: any) {
    console.log(event)
  }
}

`

**Comment by bryanwac** [comment]
did some upgrade:
I'm trying to use this events on the pdf loaded by the open file button, when I use it like this:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/5120d83e-2a0f-4131-bd8f-83545419d5c9)

I get this on console:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/2f9e72ed-d036-4a3f-85bd-4265f9e578e7)

So, I need to download the file to my host, and use it on src tag

**Comment by stephanrauh** [comment]
OK. I've navigated to https://pdfviewer.net/extended-pdf-viewer/pages-loaded. The demo contains a default document loaded from the server, but that's not what you're interested in, so I ignored the initial messages.

Next, I've opened a local file. The demo receives these messages:
```
21:08:41 progress Event type: Object Event: {"type":"load","total":279412,"loaded":65536,"percent":23.45496972213076}
21:08:41 progress Event type: Object Event: {"type":"load","total":279412,"loaded":279412,"percent":100}
21:08:41 progress Event type: Object Event: {"type":"load","total":279412,"loaded":279412,"percent":100}
21:08:41 progress Event type: Object Event: {"type":"load","total":279412,"loaded":279412,"percent":100}
21:08:41 thumbnailDrawn Event type: Object Event: {"thumbnail":{"__zone_symbol__clickfalse":[{"type":"eventTask","state":"scheduled","source":"HTMLAnchorElement.addEventListener:click","zone":"<root>","runCount":0}]},"container":{"__zone_symbol__keydownfalse":[{"type":"eventTask","state":"scheduled","source":"HTMLDivElement.addEventListener:keydown","zone":"angular","runCount":0}],"__zone_symbol__scrolltrue":[{"type":"eventTask","state":"scheduled","source":"HTMLDivElement.addEventListener:scroll","zone":"<root>","runCount":0}]},"pageId":1}
...
21:08:41 thumbnailDrawn Event type: Object Event: {"thumbnail":{"__zone_symbol__clickfalse":[{"type":"eventTask","state":"scheduled","source":"HTMLAnchorElement.addEventListener:click","zone":"<root>","runCount":0}]},"container":{"__zone_symbol__keydownfalse":[{"type":"eventTask","state":"scheduled","source":"HTMLDivElement.addEventListener:keydown","zone":"angular","runCount":0}],"__zone_symbol__scrolltrue":[{"type":"eventTask","state":"scheduled","source":"HTMLDivElement.addEventListener:scroll","zone":"<root>","runCount":0}]},"pageId":25}
21:08:41 pageRender Event type: Object Event: {"pageNumber":1}
21:08:41 pageRendered Event type: Object Event: {"pageNumber":1,"cssTransform":false,"timestamp":46590.90000009537,"error":null}
21:08:41 layersloaded Event type: Object Event: {"layersCount":0}
21:08:41 outlineLoaded Event type: Object Event: {"outlineCount":0,"currentOutlineItemPromise":{"__zone_symbol__state":true,"__zone_symbol__value":false}}
21:08:41 annotationEditorModeChanged Event type: Object Event: {"mode":0}
21:08:41 annotationLayerRendered Event type: Object Event: {"pageNumber":1,"error":null}
21:08:41 attachmentsloaded Event type: Object Event: {"attachmentsCount":0}
21:08:41 annotationEditorLayerRendered Event type: Object Event: {"pageNumber":1,"error":null}
21:08:41 pageRender Event type: Object Event: {"pageNumber":2}
21:08:41 pdfLoaded Event type: Object Event: {"pagesCount":25}
21:08:41 pageRendered Event type: Object Event: {"pageNumber":2,"cssTransform":false,"timestamp":46618.5,"error":null}
21:08:41 annotationLayerRendered Event type: Object Event: {"pageNumber":2,"error":null}
21:08:41 annotationEditorLayerRendered Event type: Object Event: {"pageNumber":2,"error":null}
```
Finally, I scrolled down. Each time a new page becomes visible, these messages are added:
```
21:10:05 pageRender Event type: Object Event: {"pageNumber":3}
21:10:05 pageRendered Event type: Object Event: {"pageNumber":3,"cssTransform":false,"timestamp":131271.60000014305,"error":null}
21:10:05 annotationLayerRendered Event type: Object Event: {"pageNumber":3,"error":null}
21:10:05 annotationEditorLayerRendered Event type: Object Event: {"pageNumber":3,"error":null}
21:10:05 pageChange Event type: Number Event: 2
```
The list of events seems to be pretty complete. What's missing? Does it look differently on your machine?

**Comment by stephanrauh** [comment]
BTW, the "=null" in your console is because you've omitted the `$event` parameter in the HTML snippet.

Oh, and I suspect you want to explain me something that's obvious for you, but for some reason, I don't get it. Be patient with me!

Obrigado,
Stephan

**Comment by bryanwac** [comment]
The problem is, if I do not load any PDF docs on the src right on the component load, the events wont work for any doc I could possible add with the file input. I need to load a doc first, to add another using the file input button. I think thats what I'm trying to explain I guess

**Comment by stephanrauh** [comment]
That's a weird bug! On second thought, it's not astonishing because the PDF viewer isn't initialized correctly when you don't set the `src` attribute. I'm not sure I can do something about it, but I'll have a look.

**Comment by stephanrauh** [comment]
It wasn't as difficult as expected. Updating to version 19.2.0 solves your bug.

Best regards,
Stephan
