### ISSUE TITLE
enableScripting=true => Fields with formatting option (d.mm.yyyy) are not shown until clicked on them

### ISSUE THREAD

**Issue by ErnestoDev1** [stephanrauh/ngx-extended-pdf-viewer#2072]
**Bug description**
1. Pdf contains Text-Fields with Formatting option for dates (dd.mm.yyyy)
2. The ngx-extended-pdf-viewer has the enableScripting-Option set to true
3. The pdf will be prefilled with formdata for these fields
4. Error: The fields with the formatting are not shown, without formatting option it is shown.
5. If clicked on the empty field, the date-value is shown.

**Code**
```ts
import { Component } from '@angular/core';
import { testdata } from './data';
import { FormDataType, pdfDefaultOptions } from 'ngx-extended-pdf-viewer';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'pdf-viewer-test';

  formData : FormDataType = testdata;
  constructor() {
    pdfDefaultOptions.renderForms=true;
    pdfDefaultOptions.enableScripting=true;
    pdfDefaultOptions.enableXfa = true; 
  }
  public setFormData(data: FormDataType | any) {
      console.log(JSON.stringify(data));
  }
}

import { FormDataType } from "ngx-extended-pdf-viewer";
export const testdata : FormDataType = {
    "field_1_format": "16.01.2024",
    "field_2_format": "15.01.2024"
};
```

**Version info**
- Version of ngx-extended-pdf-viewer: 17.4.10
- Angular-Version: 15.2.0

**Demo PDF file**
The Pdf contains two fields. The first one without formating-option, the second with formatting-option
[Datefield_Format.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/13950251/Datefield_Format.pdf)

**Comment by stephanrauh** [comment]
IMHO, the fields should show, so this sounds like a bug.

However, what happens when you open the file in Firefox or https://mozilla.github.io/pdf.js/web/viewer.html? I suspect the base library behaves a bit odd. Can you confirm this? Of course, there's no pre-filling, but shouldn't the format show immediately?

**Comment by ErnestoDev1** [comment]
I think, it is a bug in the base library. The updatefromsandbox - event delivers in the details an empty string as formattedValue.
If opened in the pdf.js-Demo the format is not shown, but it validates correctly. The bug is, that the prefilled value is overwritten by an empty string.
Do you have a workaround?

**Comment by stephanrauh** [comment]
No, I'm sorry, I don't have a workaround. I suggest opening a bug ticket at https://github.com/mozilla/pdf.js/issues. When you write the ticket, please take into account that pdf.js is the PDF viewer of Firefox. It's not meant to be integrated into other applications. So it's better not to mention my project. Just tell them what's going wrong in Firefox.

**Comment by stephanrauh** [comment]
Did you already file a bug at Mozilla's issue tracker?
