### ISSUE TITLE
remove div.buttons from editToolBar

### ISSUE THREAD

**Issue by bryanwac** [stephanrauh/ngx-extended-pdf-viewer#2075]
I want to remove the .buttons from editToolbar. since it bugs the app out like this:

this div appears when u add an annotation.
Tryied this:
```ts
    const textEditor = document.querySelector('.textEditor');
    if (textEditor) {
      const buttonsDiv = textEditor.querySelector('.buttons');
      if (buttonsDiv) {
        buttonsDiv.setAttribute('hidden', 'hidden');
      }
    }
```

and did not work, because everytime I click an annotation, it recreates the div again.

If u click to move an annotation, and it size + buttons div size is bigger then the page size, u cant posit it. Like, I cant posit on the bottom of a page cz of the buttons div beeing to big.

Example of the bug:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/a7f6c18d-cc16-4c7e-a0cf-198b7ee4bc87)

cannot do this ^^^^^^

because it replaces the div to this place:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/6dc75ab9-5dbd-424b-9dd1-b8ffa2a3f06b)

**Comment by stephanrauh** [comment]
Please elaborate. Why do you want to remove the buttons? Which bug do they cause? Where does the "assinado digitalmente" item come from?

Maybe these two options already help you:
https://pdfviewer.net/extended-pdf-viewer/responsive-design
https://pdfviewer.net/extended-pdf-viewer/custom-toolbar

**Comment by bryanwac** [comment]
Its a digital signer I'm workin in, and I cant sign the bottom cz of the buttons div size, and they do not answer to disable on .ts or css like:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/6ed113e5-cfec-4433-b31c-11aad21e8133)

or:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/3694849a-5017-4ac7-87bb-aad6bb61ea18)


like the images I sent before, I cant sign the bottom of the pages because the buttons div do not let me overpass the edges of the page

**Comment by stephanrauh** [comment]
Is using native PDF signatures an option? https://pdfviewer.net/extended-pdf-viewer/signatures

**Comment by stephanrauh** [comment]
You can get rid of the buttons by using a custom toolbar that doesn't contain them.

**Comment by stephanrauh** [comment]
I wonder where you've added your signature div. I'd put it inside the `.page` div so it scrolls with the page. #2074 reads like you're already doing that, but if you were, the toolbar wouldn't mess up your page.

**Comment by BulletQQ** [comment]
Perhaps @bryanwac meant that the annotations have problems with CSS and the display of the delete button, @stephanrauh , if you open your example and try to add any of the annotations, you will see that the elemnt is too large and the delete button is very compressed and far away from the text itself.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/49062308/87720e8a-ba7b-429a-98b7-a574c63e84d6)

**Comment by bryanwac** [comment]
exactly what @BulletQQ  said! Was trying to explaing that, sorry for the missunderstanding! That would fix the problem form, the height of the buttons div is really being a problem for me. If it's possible to make a button like in refered #2016 post would be awesome, or just make a way to get rid of that div :x

**Comment by bryanwac** [comment]
I managed to remove the div:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/a5edbb4d-c87b-4bdc-a1da-868e34d2c63d)

still having the resizer with double click on the div, and I did this:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/7aae6316-6c10-472d-95e3-d353ce6d5850)
Improving the css for this button can realy be good for the lib,

**Comment by bryanwac** [comment]
Now this is what the native delete button looks like:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/2da3adf2-75e6-4035-a9fd-e878cddd2cb9)

`public editStylesOfEditToolBar() {
    let editToolbarList = document.getElementsByClassName('editToolbar');

    for (let i = 0; i < editToolbarList.length; i++) {
      let editToolBarElement = editToolbarList[i] as HTMLElement;

      // Definir a altura da div editToolBarElement para 12 pixels
      editToolBarElement.style.height = '15px';

      // Adicionar a classe 'custom-style' à div editToolBarElement (opcional, apenas para fins de estilo)
      editToolBarElement.classList.add('custom-style');

      // Procurar pela div.buttons dentro de editToolBarElement
      let divButtons = editToolBarElement.querySelector('.buttons') as HTMLElement;

      if (divButtons) {
        // Iterar sobre os filhos de divButtons
        let buttons = divButtons.getElementsByTagName('button');

        for (let j = 0; j < buttons.length; j++) {
          let button = buttons[j] as HTMLElement;

          button.classList.add('mat-button', 'mat-icon-button');

          button.style.height = '20px';
          button.style.width = '20px'

          button.style.position = 'absolute';
          button.style.top = '10';
          button.style.right = '0'
          button.style.backgroundColor = '#4562a3'
          button.style.color = 'white'
          button.style.border = '0'
          button.style.borderRadius = '5px'
          

          button.innerHTML = '<i class="fa-solid fa-trash"></i>' 
        }
      }
    }
  }`

**Comment by bryanwac** [comment]
closed this issue as I managed a way to improve the pdfjs delete button on .ts as I showd in the code

**Comment by bryanwac** [comment]
Np! I was able to solve this and the editor is really good lookin rn! btw tw for your support and sorry for all the issues that I've openned this days lol
