### ISSUE TITLE
Can't relocate annotation block

### ISSUE THREAD

**Issue by bryanwac** [stephanrauh/ngx-extended-pdf-viewer#2076]
https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/55cf6a1a-dde4-43d5-b902-24941da32238

The video above shows something that is messing with my annotations, lemme show how to find it.

If u add an Annotation like I did, using a function, like this:

`public async addTextEditorForPage(pageNumber: number): Promise<void> {
    const textEditorAnnotation: FreeTextEditorAnnotation = {
      annotationType: 3,
      color: [0, 0, 0],
      fontSize: 10,
      value: `SIGNATURE TEST`,
      pageIndex: pageNumber - 1, // Índices de página começam do 0
      rect: [
        70, // espaço entre a borda da esquerda e o texto
        0,
        0,
        this.pageHeight - 30, //posicao baseada na orientação da pagina
      ],
      rotation: 0,
    };
    this.addedAnnotations.push(textEditorAnnotation);
    this.pdfService.addEditorAnnotation(textEditorAnnotation);

    this.editStylesOfEditToolBar();
  }`

The signature will pop in the place I choose. And the element inspector will show it like this:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/c55a78a0-edad-43c8-99d5-2fed46f6c3fd)

The annotation is inside this 2 editor blocks, external and internal.

The bug shown in the video:

I only can move the annotation below it's X axis, if I resize using this tool:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/b5a01edb-57ea-4310-9952-eaea0bfd915e)

If I resize using this and only this slider, the annotation become movable. I tryied a lot to move or set properties bymyself to alow the move like this:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/09ade8d9-347b-4a77-a0d4-e879037758ff)

I tryied to move/edit all the relationed divs and nothing worked, can u give me a hint or any tip to fix this ?

**Comment by bryanwac** [comment]
https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/0f88f8fc-4495-45ff-9437-dab64c0830fd

This is the behavior of the annotation block after I resize it.

The only attributes that change on resize are the style on both editor block as u can see below:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/cae7fbf8-07f0-4880-ac99-e5481286c52b)

**Comment by bryanwac** [comment]
this below is the file that shows on pdfjs how the editor set the fontSize but actually it did not helped me to solve the bug by myself:
https://github.com/mozilla/pdf.js/blob/master/src/display/editor/freetext.js#L401

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug on https://pdfviewer.net, without using the programmatic API.

**Comment by stephanrauh** [comment]
Please update to version 19.1.0. I believe the problem was some missing CSS I've added in version 19.0.7 and 19.1.0.
