### ISSUE TITLE
Support of pagesLoaded

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#2081]
Hi Stephan,
I saw in the documentation that the following event does not work anymore with the version 19:
(pagesLoaded)

Do you plan to fix this issue or you plan to not support this feature anymore?
Thanks a lot in advance.
Regards
Luc

**Comment by stephanrauh** [comment]
I don't have a clue what's going wrong, so I can't fix it. A pdf.js promise I'm using stopped resolving.

Adding insult to injury, I've put the library to maintenance mode until somebody tells me what the EU Cyber Resilience Act means. If my library - being a derivative of a part of Firefox - has to fulfil the same obligation as a browser, I'll have to shut it down before the Act become effective. I'd appreciate legal advice (see #2049).

**Comment by lucho78** [comment]
Thanks a lot for your reply.

**Comment by anurag-shj** [comment]
@stephanrauh Could you please look into this issue that I'm facing:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2098

**Comment by stephanrauh** [comment]
I'm closing this ticket now. It's confusing that `(pagesLoaded)` is gone, but there are many other events you can use, so it shouldn't be much of a problem.

**Comment by stephanrauh** [comment]
I've found and fixed the `(pagesLoaded)` bug. It's going to ship with version 19.0.7.

**Comment by lucho78** [comment]
Super thanks it works.
