### ISSUE TITLE
Angular 11 support?

### ISSUE THREAD

**Issue by cencio91** [stephanrauh/ngx-extended-pdf-viewer#2092]
Hi,

is there a version suitable for Angular 11?

thank you very much

**Comment by stephanrauh** [comment]
The oldest version supporting Angular 11 stems from June 2022. It's not a good idea to use such an old, unsupported version, but of course, from a technical point of view, it's possible. Just be aware this is calling for trouble as soon as the European Cyber Resilience Act comes into effect.
