### ISSUE TITLE
Load pdf file from url

### ISSUE THREAD

**Issue by bryanwac** [stephanrauh/ngx-extended-pdf-viewer#2095]
It's planned any day to implement a load, in src tag from url?

**Comment by bryanwac** [comment]
My problem is: I have to load a file into the viewer, but I dont want to put it directly in the src tag

**Comment by bryanwac** [comment]
Now even I did undertand it better. If the viewer is loaded, he needs a src file to be able to start listening the events, so, if I initialize the component withou a src, the events gonna be broken.

This is the first point. The second point is, I cant, via TS change the src file, if just do not load or change the src. Even tyied to emit the srcChanged event.

**Comment by stephanrauh** [comment]
I think you're looking for https://pdfviewer.net/extended-pdf-viewer/base64 and https://pdfviewer.net/extended-pdf-viewer/blob.

BTW: you're right, when you leave both `src` and `base64Src` empty, the PDF viewer is broken. There's already an open ticket, so I'm closing this ticket now.
