### ISSUE TITLE
Print button doesn't work

### ISSUE THREAD

**Issue by BulletQQ** [stephanrauh/ngx-extended-pdf-viewer#2096]
Hello, if you open the demo https://pdfviewer.net/extended-pdf-viewer/simple and try to click on the "Print" button, you will get the error "Warning: The PDF is not fully loaded for printing." In the original PDF.js this button works. Any idea how to fix this?
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/49062308/ab9ef4a7-a597-442f-b0bf-d9548600a1ba)

**Comment by BulletQQ** [comment]
This is most likely due to setTimeout in preparation for printing

**Comment by stephanrauh** [comment]
The bugfix has shipped with version 19.1.0.
