### ISSUE TITLE
PDF all time prints one page at blank :/

### ISSUE THREAD

**Issue by miguel5612** [stephanrauh/ngx-extended-pdf-viewer#2097]
Bug:

Whenever we press the print button on a pdf with a single page, it automatically prints a second page, there is no way to set the print range to always print only pages with text.

How to:

Navigate to: https://pdfviewer.net/extended-pdf-viewer/options

Press print logo.

View, the print preview has two pages...

Its the same with all PDF's.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/18131167/8cf4a7c7-be60-436b-93b2-8fb44817a392)

**Comment by stephanrauh** [comment]
That's very strange. I've tried to reproduce it with the same website as you did, and there's only a single page, as you can see below.

However, that's a common problem, and it's always related to CSS. The PDF viewer tries to use the maximum page size, and sometimes it guesses a few pixels wrong. To solve the issue, add this CSS rule to your global `styles.(s)css`:

```css
@media print {
  #printContainer > .printedPage {
    width: 99%;
  }
}
```

<img width="2056" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/57d0cf85-62cf-4194-b4f0-f005d586c235">
