### ISSUE TITLE
PDF not rendering initially; requires triggering action (e.g., zoom or rotate) to display content

### ISSUE THREAD

**Issue by anurag-shj** [stephanrauh/ngx-extended-pdf-viewer#2098]
I encountered an issue where the PDF content is not displayed upon initial loading of the component. It seems to partially render the viewer, but the document isn't there. The viewer remains blank until I perform an action such as clicking on the zoom or rotate button.

```html
<ngx-extended-pdf-viewer *ngIf="selectedImageExtension === 'pdf'" [src]="selectedImage"
    zoom="page-fit" [textLayer]="false" [enableDragAndDrop]="false" [enablePrint]="false"
    [ignoreKeyboard]="true" [showBookmodeButton]="false" [showDownloadButton]="false"
    [showFindButton]="false" [showDrawEditor]="false" [showHandToolButton]="false"
    [showOpenFileButton]="false" [showUnverifiedSignatures]="false" [showStampEditor]="false"
    [showTextEditor]="false" [showVerticalScrollButton]="false"
    [showWrappedScrollButton]="false" [showSpreadButton]="false" [showSidebarButton]="false"
    [showSecondaryToolbarButton]="false" [showPropertiesButton]="false" [height]="pdfHeight">
</ngx-extended-pdf-viewer>
```

**Expected Behavior:**
The PDF content should be displayed upon the initial loading of the ngx-extended-pdf-viewer component without the need for additional actions.

![issue](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/153087686/1a713013-64a2-45e0-9a8f-c84d0be524d7)

**Comment by anurag-shj** [comment]
@stephanrauh

**Comment by stephanrauh** [comment]
Can you send me a reproducer? That's a minimal but complete project allowing me to see the problem within five minutes.

**Comment by AndyKorek** [comment]
I was able to reproduce that.
The weird thing is I use the Viewer on 2 Projects, with the same version 18.0.02
One Project Renders the PDF, the other does not.

My hotfix was to set the Zoom on Init but, that's kind of ugly ;I

**Comment by stephanrauh** [comment]
I guess I can close the ticket because you've found a workaround.

Maybe the problem has something to do with the localstorage where pdf.js stores the initial zoom factor. What happens if you empty it?

**Comment by anurag-shj** [comment]
It is fixed. Thanks
