### ISSUE TITLE
Update PDF.js to the latest stable version

### ISSUE THREAD

**Issue by BulletQQ** [stephanrauh/ngx-extended-pdf-viewer#2099]
Hello @stephanrauh , please, if you can update the version of pdf.js in your project to the latest stable version at the moment v4.0.379. I'm sure this will solve most of the problems

**Comment by stephanrauh** [comment]
@BulletQQ The bleeding edge branch already is on 4.0.379. Does it solve the problems you've mentioned?

**Comment by stephanrauh** [comment]
Version 19.1.0 updates pdf.js to 4.0.397 in the stable branch and 4.1 in the bleeding-edge branch.

**Comment by BulletQQ** [comment]
@stephanrauh Thank you very much for working on this component, judging by your demo site, all the problems that I noticed have now been fixed. please tell me how exactly you fixed the problem of “printing” the document? It’s just that now I can’t download your latest version because I made a lot of changes to PDF.js (without creating a fork) and I wanted to fix the “printing” problem for myself.

**Comment by stephanrauh** [comment]
It was a very strange bug in the TypeScript code:
<img width="712" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/e32b3949-6f7f-424e-a42f-d1df3b14fc65">
plus an equally strange bug in the JavaScript code:
<img width="675" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/ae75435b-b004-47cd-ba6d-72973918ff77">

The first bug caused the viewer to never finish initializing. The second bug stopped the viewer from detecting that it managed to load every page.

**Comment by BulletQQ** [comment]
I got you, thanks again, if there are any errors I will let you know about them
