### ISSUE TITLE
Support flipbook animation

### ISSUE THREAD

**Issue by jesussanzdev** [stephanrauh/ngx-extended-pdf-viewer#210]
Hi! 

I've seen the current version supports an odd spread view:

**Features**

- standard display or even / odd spreads (like a book)

I would like to know if you could implement a flipbook animation mode. It would be very useful for commercial-oriented projects. There are old javascript libraries and plugins such as turnjs but I'm facing a lot of dependencies problems when I try to implement them on my angular solutions. (Implement any 3rd party javascript, in general, it's a pain in the ass without a wrapper and of course it's against angular good practices.)

Nowadays I think there is no wrapper or library that supports this feature. The last one I've tried is Raffaele Morganti's: https://github.com/RaffaeleMorganti/pdf-viewer

But it's really difficult to integrate with lazy loading. I have to customize the javascript dependencies in order to load the scripts correctly.

Check the example below:

http://www.turnjs.com/

Greetings and have a good day!

**Comment by stephanrauh** [comment]
¡Hola Jesús!,

I've already spent several weeks with the book flip. Raffaele has done a great job, and he's helped me a lot to port it to ngx-extended-pdf-viewer. However, I wasn't happy with my approach, so I put aside this project for a while.

What I'm looking for is a pure-CSS solution. I'd also accept a JavaScript solution if it's not to heavy on the CPU. I've seen many tutorials indicating such a CSS-only solution exists, but I didn't manage to get it up and running. Let alone integrating it into the PDF viewer. You know, the bulk of the pdf.js isn't my code. I'm just using Mozilla's implementation, carefully modifying a few bits here and there, hoping to be careful enough to survive the next update of pdf.js.

I can share my code with you (if you don't mind seeing a lot of late-night hacking). :) I'm also open for pull-request. I'm also sure I'll resume this project one day or another. However, I feel like I've got a lot to learn about CSS before I do. Implementing such a great page-flip like Kindle doesn't on the iPad doesn't seem to be easy. Truth to tell, I expect it to be in the 20-50 lines range, but I don't think it's easy to write these 20 lines.

Hasta la próxima,
Stephan

**Comment by stephanrauh** [comment]
Also see #161

**Comment by jesussanzdev** [comment]
Good morning Stephan! Thank you for responding so quickly!

I've already checked #161 that's why I mentioned Raffaele's solution. I'm still fighting to implement a viable solution on my project, your code would be very useful, in fact, I'd appreciate it a lot. 

I can try to improve your approach, but I can't guarantee if I'll be succesful. My CSS skills need to be perfectioned too! Hahaha : 3

Thanks a lot again. 

¡Nos vemos pronto, caballero!

**Comment by stephanrauh** [comment]
Aqui tienes: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/page-turn-effect

Please note it's not the best implementation I've ever made. It's mostly late-night hacking. I'm not even sure the latest version works. It's a JavaScript-based solution requiring a lot of CPU power. As far as I remember, it almost worked. However, I had a lot of trouble

- getting the animation right (especially after zooming in or out)
- switching between "book mode" and the other "spread" modes
- browsing and scrolling reliably between the pages of the book
- and so on.

I'm pretty sure it's a not that difficult to implement the features if you aren't limited to late evenings. A large part of my problem was I confused myself all the time. Being fully awake helps with this kind of bugs. :)

By the way, the reason why I didn't simply embraced Raffaele's solution was the copyright. AFAIK the license of turn.js isn't compatible to the Apache V2 license. I also wasn't happy to use jQuery or jQueryUI, but that wasn't the showstopper.

I'm looking forward to your solution! Feel free to approach me by email at "webmaster1 arroba beyondjava.net". En castellano u inglés, me da igual! :)

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Another hint: 90% of the implementation went to `pdf-book.ts` and `book.ts`. I tried to separate the general page flip effect (`book.ts`) from the PDF-related code in `pdf-book.ts`. However, that didn't work perfectly. 

I've also added a number of change to `viewer.js`. Following the Raffale's route, I've marked these changes with at `//$FB` comment. 

To merge these changes to the main branch, we'd have to add these changes to `modify-viewer.js`. However, that's not today's job. It's just what's necessary to make the solution future-proof. The `modify-*.js` scripts make it easy to update to a new version of Mozilla's pdf.js library.

**Comment by stephanrauh** [comment]
@jesussanzdev I'd like to close this ticket because npm punishes project that solve their bugs lazily. But don't get me wrong: I'm still interested in the feature. I'll keep listening to the ticket. When you've got news, just comment here.

Greetings to Zaragoza
Stephan
