### ISSUE TITLE
Is there an option to disable the ability to attach an image to a PDF?

### ISSUE THREAD

**Issue by Blunderchips** [stephanrauh/ngx-extended-pdf-viewer#2109]
Is there an option disable this button here?

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7081037/d0445739-996b-4880-a166-0c7f66381afb)

I am not seeing it in the docs, there is a non-zero chance I am just blind... I am looking for is away prevent users from attaching images.

**Comment by stephanrauh** [comment]
The feature has a silly name, so I wouldn't call you blind... you're looking for `[showStampEditor]`.
