### ISSUE TITLE
console log error : [fluent] Missing translations in en-us: pdfjs-page-scale-height

### ISSUE THREAD

**Issue by randyparis** [stephanrauh/ngx-extended-pdf-viewer#2112]
I'm experiencing a slight delay in the viewer loading, which displays a message in the div it sits in. But its covered up too quickly to read it. It appears like some sort of quick glitch before the viewer covers it up. I'm wondering if it's related to the error message in the console: `[fluent] Missing translations in en-us: pdfjs-page-scale-height.` or if it could be canvas related

Angular CLI: 17.0.10
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin x64

Angular: 17.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.10
@angular-devkit/build-angular   17.0.10
@angular-devkit/core            17.0.10
@angular-devkit/schematics      17.0.10
@angular/cli                    17.0.10
@angular/ssr                    17.0.10
@schematics/angular             17.0.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
**

using latest version of viewer 

this is all local dev right now, no online sample yet, but I could put one up if it helps

**Comment by stephanrauh** [comment]
- I don't see the console message in version 19.1.0. Can you double-check? Maybe it's gone now.
- Maybe you can catch the message by taking a screen cast and playing the video frame-by-frame.

**Comment by randyparis** [comment]
Here’s a screen shot from a video capture of the load and log of the  Chrome console

￼￼

**Comment by stephanrauh** [comment]
I'm afraid your screen shot didn't manage to cross the Atlantic. I can see you've tried to embed an image, but it didn't work for some reason.

**Comment by randyparis** [comment]
That’s what pops up for an instant before the viewer/pdf. I am not trying to embed an image, so I don’t know where the heck that "miniature of the page” is supposed to be coming from. Thought the viewer might be looking for some info from the pdf file to display before the document load. Here’s the video I grabbed that frame from.
￼

**Comment by stephanrauh** [comment]
I suspect the email interface swallows your videos and images:

<img width="1155" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/238fe8b7-bbc7-4ae1-b2b3-66c58debb10e">

**Comment by randyparis** [comment]
Well, that’s weird.

I’ll try troubleshooting this a bit longer. If I can’t figure it out I’ll set the test version up on my website to view and send you a link if it’s still acting strange.

**Comment by randyparis** [comment]
If you didn’t get the still screen shot, it was the standard broken image icon with a message that said ‘miniature of the page’. I was thinking that meant hat the viewer was looking for something in or about the pdf that it couldn’t find.

btw - glad your feeling good enough to reply to this stuff and I very much appreciate your attentiveness.

randy

**Comment by stephanrauh** [comment]
It seems the pdf.js core team have changed their translation key, and I didn't notice:
<img width="287" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/e4259d0f-9f00-426e-80f7-634fb57c7eb9">
Even if you don't speak German, you'll probably notice there's something wrong with the second entry of the drop-down menu. So this error is more than a weird console message. It has impact on the UI.

**Comment by wishmaster-** [comment]
Hi there,
I'm guessing this is the same issue? Or is this a deployment issue?

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/7646231/ef25424a-c205-4da9-a43e-90b874a9618d)

Language should be German
using version 19.2.2

**Comment by stephanrauh** [comment]
Looks like a deployment issue. Please check the network tab. Are there any 404 messages?

Maybe you've updated from an earlier version of ngx-extended-pdf-viewer. The filenames (and the file format) of the language files has changed recently. I wonder if the i18n files made it into your deployment package. It should look like so:
<img width="1190" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/ca9f3a7f-360b-4287-a993-3be8794a051c">
...
<img width="1203" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/1f3e48d1-fee1-448e-9477-1e73669d20dc">

**Comment by stephanrauh** [comment]
BTW, I wonder why this ticket is still open. Chances are I've already solved it.

**Comment by stephanrauh** [comment]
Randy, it this still an open ticket? I'd like to close it now.

**Comment by randyparis** [comment]
So very sorry. yes, by all means close it.
