### ISSUE TITLE
Is there any way i can get access to PDFDocumentProxy ?

### ISSUE THREAD

**Issue by farisshomali** [stephanrauh/ngx-extended-pdf-viewer#2118]
Hi, i need to access the pdf document proxy at pdf viewer init state... how can i do it ?

**Comment by stephanrauh** [comment]
You can use the inofficial low-level API:
```JavaScript
PDFViewerApplication.pdfDocument.getPage(1)
```
The type definition files are here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/types

**Comment by farisshomali** [comment]
@stephanrauh Thanks !

another question please... can you help me with a "How to re-render annotation layer" ??

Please if you can help me this that will be awesome
