### ISSUE TITLE
Pdf viewer just shows blank grey background after loading

### ISSUE THREAD

**Issue by BIINBELLLO** [stephanrauh/ngx-extended-pdf-viewer#212]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple?

**Describe the bug**
Hi, I don't know if this is a bug or an implementation error on my side, but I have been trying to implement the ngx-extended-pdf-viewer and it just hasn't been displaying the pdf file. What I want to actually do is get a url to a file on the server and pass it to the src attribute, so I first decided to try out the package by passing a link to a file inside the assets folder, but it still won't display it.

**Version info**
- Latest version, installed today
- Latest versions

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]
 - Version [e.g. Version 79.0.3945.130 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**
I get this error if I intentionally omit a letter from the url,
![error1a](https://user-images.githubusercontent.com/22405338/74691346-b89d5980-51e2-11ea-8ec1-e8db01ea31a4.png)

When I coorect it and reload the page, I get a blank screen below.
![error1](https://user-images.githubusercontent.com/22405338/74691436-19c52d00-51e3-11ea-9e83-a59cfab3ad18.png)

I am sure that I have installed the package correctly, imported it into my app module, used the component correctly and also added the reference to the asset files in my angular.json file. I also added the scripts to the script section of the angular.json file.

Please help, I really need this to work. Thanks

**Additional context**
Please help.

**Comment by stephanrauh** [comment]
Whow... an error without a single trace in the console. Sounds like a hard problem. Let's see what I can do for you!

First of all, I'd like you to check if the PDF file works. That's easy. Open it on https://pdfviewer.net/simple. If that fails (granted, that's unlikely), please open it on https://mozilla.github.io/pdf.js/web/viewer.html. If that fails, too, there's something wrong with your PDF document. The core library, pdf.js, supports most of the PDF standard, but it's not perfect yet.

After that, I'd like to check if the pdf viewer works on your machine at all. It's almost certain it does, but please do it nonetheless. It's always good to ensure a potential source of errors hasn't hit you. So please check out the showcase https://github.com/stephanrauh/extended-pdf-viewer-showcase, compile it on your machine and tell me it's able to display your PDF file.

I'm pretty sure it is. 

The next steps is to compare your local copy of the showcase to your project. Usually, that helps to find subtle differences.

If you're still stuck, things get difficult. Here are a few ideas: the PDF viewer relies heavily on asynchronous code, and it only works if the window is visible. Plus, it doesn't allow multiple PDF files on the same screen. For example, if you're using a carousel, you have to hide every PDF viewer except the one shown by the carousel. Often, it helps to show the PDF file later (by making it visible on `ngAfterViewInit` or even later, using a `setTimeout()`). Sometimes there's a simple alternative: set the attribute `delayFirstView` to, say, 2000 milliseconds.

Does any of the hints help you?

**Comment by BIINBELLLO** [comment]
I waited for a reply from you, didn't get it earlier. So I opted for one of the alternatives you mentioned, and it works perfectly. I'd try it out on another project and let you know of the outcome. Thanks

**Comment by stephanrauh** [comment]
Ok, let's close the ticket. I'm glad you've found a solution!

Best regards,
Stephan
