### ISSUE TITLE
ng build (CLI 17) doesn't seem to create a workable version on my remote Apache server

### ISSUE THREAD

**Issue by randyparis** [stephanrauh/ngx-extended-pdf-viewer#2135]
Trying to replace an 'older' viewer build with a new one in same folder (different viewer names) but the structure of the latest ng build isn't the same, and it throws 404 errors. If I try to navigate to new viewer using same url path (with new name) I get a full 404 response, if i try to extend the url to a 'browser' folder with or without the index.html in the path, I get my new index host  page, but 404 errors on its image and pdf assets.
Here's a url to the 'browser' folder version: https://www.randyparis.com/RPArchive_update/assets/writing/manuscript_pdfs/my-new-pdfviewer/browser/?pdf=ARK2
and here's a url to the original version: https://www.randyparis.com/RPArchive_update/assets/writing/manuscript_pdfs/ngx-pdf-viewer/index.html?pdf=ARK3
(They are calling different pdf files from the different builds)
Here's a screen shot of the file structures from their respective dist folders:
Original (the second url):
![Screenshot 2024-02-03 at 3 26 53 PM](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/8271981/fe651d86-ce83-4437-a70b-6541878dda2a)
Here's a screen shot of the new dist build (the 1st url):
![Screenshot 2024-02-03 at 3 25 45 PM](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/8271981/a3d6ad2f-abff-45b8-959c-5661552ee203)

I found some documentation on Angular.io about deployment to Apache which suggested adding some code to an .htaccess to redirect 404 to index.html, but it didn't work. If I put it in the root folder of the 'site', it goes to the site's index. If I put it in the host folder of the viewer, it just returned a file/structure page with a 'browser' 'link', which showed the same result as url 1 above.
These are the pdf files for those two urls (I own the copyrights)
[ARK_2_1970_Story.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/14154558/ARK_2_1970_Story.pdf)
[ARK_3_Story_Poem.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/14154559/ARK_3_Story_Poem.pdf)

The original was:
Angular CLI: 14.1.1
Node: 20.11.0 (Unsupported)
Package Manager: npm 10.2.4 
OS: darwin x64

the New project is:
Angular CLI: 17.0.9
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin x64
- Version of ngx-extended-pdf-viewer

**Comment by stephanrauh** [comment]
The problem is the `baseHref` in your new `index.html`.  Your new Angular application tries to load everything from the root folder. You can fix this in the `index.html` of your Angular project. Try setting `baseHref="."`. Your old application omitted the base hrefs, maybe that's also an option.

The different folder structure indicates you've activated pre-rendering. I don't see the pre-rendered files in your screenshot, but it seems to work. Maybe you've configured Angular to pre-render only the root file?

As for the `.htaccess` configuration: that's necessary to support routing on an Apache server. Routing means your Angular application has different pages, each of them having a different URL. That URL doesn't point to a real file (unless you've activated pre-rendering). So you have to configure Apache to use the `index.html` instead. Angular parses the rest of the URL and renders the requested page.

I don't think that's your problem, but you'll need it as soon as you configure a router, so here's the configuration I'm using on `https://pdfviewer.net`:
```
# If an existing asset or directory is requested go to it as it is
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
RewriteRule ^ - [L]

Options +FollowSymLinks

# If the requested resource doesn't exist, use index.html

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !index
RewriteRule (.*) index.html [L]
```

**Comment by stephanrauh** [comment]
Your Apache server sends the JavaScript files without MIME type. You probably need to configure that in the `.htaccess` file.

```
<IfModule mod_mime.c>
  AddType text/javascript js mjs
</IfModule>
```

**Comment by stephanrauh** [comment]
To understand the local error message, I'd need to see your source code. I suppose you've defined a router? I suppose the router tries to interpret the file name "?pdf=..." as an Angular route.

BTW, pre-rendering is a cool feature. If configured correctly, it can make your web application feel considerably faster.

**Comment by randyparis** [comment]
That .htaccess code snippet worked!

It takes a while to resolve the viewer and load the pdf. but it worked.  Thank you very much.

I will try out pre-rendering next.

Again, thanks for your diligence. I am still learning to walk w angular

Randy Paris

**Comment by randyparis** [comment]
Hello,

Sorry to keep pestering you, but this is getting so close to working properly it’s hard to leave it alone. It loads the desired pdf, but it’s still very slow, and the load progress doesn’t register on the progress bar until it actually appears in the viewer.  Until the progress bar appears, it displays the broken image link  and text. Also the console log of the onPageRendered function does not appear to get console.log ('pageindex=' + pageIndex);

I’m obviously groping in the dark at the monet. Getting a bit frazzled.

here’s the URL: https://randyparis.com/RPArchive_update/assets/writing/manuscript_pdfs/my-new-pdfviewer/browser/?pdf=ARK2

here’s what I did:

I altered the angular.json ‘pre-render’ to 

	   "scripts": [],
            "server": "src/main.server.ts",
            "prerender": true,
            "ssr": {
              "entry": "server.ts"
            }

the ssr string was already in there.

Altered the app components html to include the page and pageRendered attributes like this
	 <ngx-extended-pdf-viewer
  [src]="'assets/ARK_2_1970_Story.pdf'"
  (progress)="onEvent('onProgress', $event)"
  (pageRendered)="onPageRendered()"
 [(page)]=“page”

and Altered the component to include

  public spreadMode: 'off' | 'even' | 'odd' = 'off';
  public page: any;

  constructor(private pdfViewerService: NgxExtendedPdfViewerService) {
    pdfDefaultOptions.ignoreDestinationZoom = true;
  }

  public onPageRendered(): void {
    if (!this.pdfViewerService.isRenderQueueEmpty()) {
      // try again later when the pages requested by the pdf.js core or the user have been rendered
      setTimeout(() => this.onPageRendered(), 100);
    }

    const pagesBefore = this.spreadMode === 'off' ? 2 : 2;
    const pagesAfter = this.spreadMode === 'off' ? 2 : 5;
    let startPage = Math.max(this.page - pagesBefore, 1);
    let endPage = Math.min(this.page  + pagesAfter, this.pdfViewerService.numberOfPages());

    const renderedPages = this.pdfViewerService.currentlyRenderedPages();

    for (let page = startPage; page <= endPage; page++) {
      const pageIndex = page - 1;
      if (!this.pdfViewerService.hasPageBeenRendered(pageIndex)) {
          this.pdfViewerService.addPageToRenderQueue(pageIndex);
          console.log ('pageindex=' + pageIndex);
          break; // break because you can request only one page at a time
      }
    }
  }
