### ISSUE TITLE
How to load a pdf from an external URL outside assets folder

### ISSUE THREAD

**Issue by JoseIsra** [stephanrauh/ngx-extended-pdf-viewer#2136]
Hi
Hi guys, In my app the use of pdfs is just with the URL of these pdfs. I've seen in the examples that all the pdfs are loaded using the assets folder (the pdf needs to be downloaded it to be used) but what can I do if my pdf is just coming from an external URL and I want to load it?.
There are CORS errors in the console when the app is trying to fetch the pdf URL either in development/production mode.
Thanks you.

**Version info**
- My current version is : 19.2.0

**Demo PDF file**
For example this dummy file : https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

**Comment by stephanrauh** [comment]
Yes, CORS is a pain. Short answer: you can't load a PDF file from a third-party server.

However, if you own that server, you can add a CORS header. This way you can tell the browser to trust the URL. Otherwise, the browser assumes it has been hacked and refuses to show the PDF file.

**Comment by stephanrauh** [comment]
Also see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

https://www.baeldung.com/spring-cors

https://medium.com/zero-equals-false/using-cors-in-express-cac7e29b005b
