### ISSUE TITLE
Fullscreen option in mobile

### ISSUE THREAD

**Issue by ikermonk** [stephanrauh/ngx-extended-pdf-viewer#215]
Hi,

Thanks for you Angular component. It's very usefull for us.

We've a little bit problem in mobile. We need to use fullscreen option and in mobile is not working. We configure component to can show it (https://prnt.sc/r4qf9q), but isn't show it (https://prnt.sc/r4qfnn).  Howeber, in other devices yes (https://prnt.sc/r4qgo4).

Can you help us?

Thanks,

**Comment by stephanrauh** [comment]
That's a side-effect of responsive design. Both Mozilla's pdf.js and my component hide widgets that aren't used often on small screens. As you can imagine, that's a lot of guesswork. We simply can't know who needs what, and it differs from project to project.

Just add a CSS statement to your global `styles.css`:

```css
#outerContainer button.presentationMode {
    display: block;
}
```
Please tell me if the solution works, so I know I can safely close the ticket.

Best regards,
Stephan

**Comment by ikermonk** [comment]
Hi Stephan,

Don't worry, we understand yo ;)

We try your solution and works to show in mobile, but the problem is that it doesn't work. 
Look at the following video: https://drive.google.com/file/d/1VCmZiHYmaDyumx-rWL7OvziT7lhzxDpP/view

Maybe the problem is Ionic? Displaying in browser runs correctly.

Thanks,

**Comment by ikermonk** [comment]
Hi Stephan, 

We continue testing and we achieve to work in Android, but not in IOS. 

Do you know why?

Thanks!!

**Comment by stephanrauh** [comment]
That's really strange. I don't believe Ionic causes problems. It's also the first CSS problem occurring on iOS, but not on Android. The first CSS problem I've encountered, that is. 

How familiar are you with CSS? Some time ago I've written a "survival guide" to give less-experienced CSS developer an idea what's going on. I don't know you, but maybe the article helps you, too: https://beyondjava.net/gentle-introduction-css

Generally speaking, it helps to make the CSS selector more specific. That amount to adding more keywords to it. For debugging purposes, you can also add the suffix `!important`. But that's mostly guesswork. It's better to use the developer tools of your browser to hunt down the problem (as I've described in the article).

It's just annoying you can't do that on an iOS device. Or does Xcode allow you to peek into the CSS rules engine?

**Comment by stephanrauh** [comment]
Version 2.1 give you all the flexibility to solve the issue. For example, you can replace the standard toolbar with a custom toolbar. Plus, I'll probably add an option to shift the buttons to the secondary toolbar programmatically. This way, the algorithm is more flexible than the standard CSS rules because it knows which buttons you've configured away.

I'm closing this ticket now.

Best regards,
Stephan
