### ISSUE TITLE
stamped image not showed

### ISSUE THREAD

**Issue by atiwat061013** [stephanrauh/ngx-extended-pdf-viewer#2151]
I have an issue when stamp image with lib IronPDF in dotnet core version6. To preview that PDF, I use this ngx-extended-pdf-viewer with based64, but I found that the image is not displayed. However, if I use the URL, it is showed normally.

[pdf999.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/14278397/pdf999.pdf)
<img width="679" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/77142599/c5ed9182-b39b-4755-b923-8b1c92268a2e">

**Comment by stephanrauh** [comment]
Please tell me more. Where should the image be?

The only thing I found out so far is your PDF contains a signature. That's the blue text "developer 1". It shows once you add the attribute `"[showUnverifiedSignature]="true"`. Then the PDF looks like so:
<img width="1051" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/88efa9f6-b72f-419b-8260-552520a09e58">

**Comment by atiwat061013** [comment]
blue text "Developer 1" is my image. 
From what I added [showUnverifiedSignature]="true" It has shown the image. 
But what if I don't want the "This PDF file contains a digital signature" warning? Can I hide it?
