### ISSUE TITLE
The pdf viewer cannot render some Unicode characters inside pdf

### ISSUE THREAD

**Issue by kubydog** [stephanrauh/ngx-extended-pdf-viewer#216]
**Describe the bug**
I have a pdf file using 90ms-RKSJ-H.bcmap. The file was stored at AWS. Every time rendering it, our application need send a request for it. However, some Japanese characters cannot be rendered. I investigated the issue and found it send two requests:
<img width="1674" alt="Screen Shot 2020-02-19 at 15 52 40" src="https://user-images.githubusercontent.com/12166284/74886184-9450a100-53cb-11ea-8ccb-cb66d766dbe8.png">, requested url paths were quite different. This looks not correct.
<img width="837" alt="Screen Shot 2020-02-19 at 15 38 48" src="https://user-images.githubusercontent.com/12166284/74886392-22c52280-53cc-11ea-9057-183a0dc58b77.png">
<img width="872" alt="Screen Shot 2020-02-19 at 15 37 15" src="https://user-images.githubusercontent.com/12166284/74886395-25277c80-53cc-11ea-87c6-43310a827b95.png">
Then I looked into the code inside Viewer.js and Viewer-es5.js. There is a setting called cMapUrl with a value '../web/cmaps/'. Inside the ngx-extended-pdf-viewer project, there is a cmaps folder under assets
<img width="405" alt="Screen Shot 2020-02-20 at 10 37 28" src="https://user-images.githubusercontent.com/12166284/74886718-070e4c00-53cd-11ea-8927-327fddd8feb9.png">
However in our application node_modules, the cmaps folder is not exist
<img width="546" alt="Screen Shot 2020-02-20 at 10 39 54" src="https://user-images.githubusercontent.com/12166284/74886840-5a809a00-53cd-11ea-957f-3f721af7a832.png">
I'm not sure whether this is the cause of the issue or not. Could you help check this problem?

**Version info**
- Version of ngx-extended-pdf-viewer
1.8.4
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)
default

**Desktop (please complete the following information):**
Chrome, IE, FireFox

**Demo PDF file**
Here is an example pdf using Adobe-Korea1-UCS2.bcmap
[CHIR-CHIR-MENU.compressed.1.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4228102/CHIR-CHIR-MENU.compressed.1.pdf)

**Comment by leo6104** [comment]
Please update to 2.0.0-alpha.x .

**Comment by stephanrauh** [comment]
Also have a look at #208. You may also want to check your angular.json settings. Since version 2.0.4, the CMAP files are part of the node_modules folder, but earlier versions of my documentation didn't tell you to copy the CMAP files to the assets folder.

**Comment by stephanrauh** [comment]
BTW, thanks for the reproducer file. It looks tasty! :)

**Comment by stephanrauh** [comment]
BTW, please tell me even if updating solves your problem, so I know I can safely close the ticket.

**Comment by kubydog** [comment]
Updated to the latest, issue solved. Thanks

**Comment by stephanrauh** [comment]
That's great news!
