### ISSUE TITLE
Viewer tears/distorts when user pinches to zoom on iOS

### ISSUE THREAD

**Issue by sipelepis** [stephanrauh/ngx-extended-pdf-viewer#2163]
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? **NO**
- Does the bug also happen on https://pdfviewer.net/simple? NO
- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`. https://github.com/sipelepis/REPRODUCER-PdfViewerTearsOnPinchZoom_ionic_angular_iOS

**Describe the bug**
I have an **Ionic  Capacitor + Angular** project. In this project, I have a feature which allows user to view a pdf from link, I am using _ngx-extended-pdf-viewer_ for this feature. 

This plugin works well on browser and android. However, on iOS, I found a bug with the pinch-zoom capability of the plugin. When I start to pinch-zoom in, the viewer seems to tear/distort. But after a while, it will be revert back to normal. bug happens on all pdf files.

1. Clone the repo
2. run _npm install_
3. run _ionic build_
4. run _ionic capacitor build ios_
5. run the app on an emulator or a physical device (preferrably on an iPad 10th gen).
6. use the pinch-zoom to zoom in and out
7. check if its tearing/distorted on pinch

**Version info**
- Version of ngx-extended-pdf-viewer ^18.1.14

**Demo Video*

https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/68763761/67a572c8-4ee4-47e7-8354-dffc7e824d42

**Comment by stephanrauh** [comment]
Thank you  very much for providing the video and the reproducer! I've managed to reproduce the bug and to simplify the recipe to reduce it. The bug also occurs on a MacBook running Safari Version 17.3.1 (19617.2.4.11.12). Even better, it also occurs on https://mozilla.github.io/pdf.js/web/viewer.html.

Unfortunately, that's not good news for you. It's a browser bug. There's nothing I can do. Please open a bug ticket here: https://bugs.webkit.org/ (at least I hope that's the correct URL).
