### ISSUE TITLE
pdf-rotate-page input improvements

### ISSUE THREAD

**Issue by ilyakonrad** [stephanrauh/ngx-extended-pdf-viewer#2168]
Hi! I'm new to the project and I'm trying to create a wrapper component for this PDF viewer.
I need to create a custom toolbar and there is one confusing thing that docs don't cover.
I want to include rotate page buttons but in the reverse order: left and then right.
In order to achieve this and not go the css route, I have to have this funny looking code:
```html
<pdf-rotate-page [clockwise]="false" [counterClockwise]="true"></pdf-rotate-page>
<pdf-rotate-page [clockwise]="true" [counterClockwise]="false"></pdf-rotate-page>
```
If I leave out any pair of these input properties, it doesn't render properly.

I suppose it's because the component supports showing both buttons at the same time and moreover it is the intended use of this component.
However I think it could be improved by adding a property like
```ts
@Input() reverse: boolean = false
```
which would simplify my use this much
```html
<pdf-rotate-page [reverse]="true"></pdf-rotate-page>
```

**Version info**
- 19.2.2

**Comment by stephanrauh** [comment]
Whow, you've found a clever workaround!

You're right, I should have defined the two buttons as two separate components in the first place, but I was to lazy. I guess I can still do it without introducing a breaking change. I'll add the two components and declare `<pdf-rotate-page>` deprecated.

Your idea is clever, too, but I think separate components are even simpler and more flexible.

**Comment by stephanrauh** [comment]
Starting with version 19.4.0, you can use `<pdf-rotate-page-cw>` and `<pdf-rotate-page-ccw>`. The old component still exists for compatibility reasons.
