### ISSUE TITLE
Cambiar Icono De pdf-open-file

### ISSUE THREAD

**Issue by luis-cosillo** [stephanrauh/ngx-extended-pdf-viewer#2179]
No encontre donde colocar mi duda hay forma de cambiarle el icono en la barra al pdf-open-file. Para cambiar icono color ponerle tooltip ???

**Comment by stephanrauh** [comment]
Necesitas una barra de herramientas personalizada. Puedes utilizar la barra de herramientas predeterminada como base: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/lib/toolbar/pdf-toolbar

Cópialo y sustituye la línea que importa el botón estándar "abrir archivo":

```html
     ...
      <pdf-presentation-mode [showPresentationModeButton]="showPresentationModeButton"></pdf-presentation-mode>
      <my-pdf-open-file [showOpenFileButton]="showOpenFileButton"></my-pdf-open-file>
     ...
```

El nuevo componente debe ser una copia del componente original (https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/lib/toolbar/pdf-open-file). En teoría, puedes usar un buton HTML estandar, pero el `<pdf-shy-button>` es mas flexible. Sabe como esconder en el menú secundario en patallas pequeñas.

```html
<pdf-shy-button
  [cssClass]="showOpenFileButton | responsiveCSSClass : 'hiddenMediumView'"
  primaryToolbarId="openFile"
  title="Open File"
  l10nId="pdfjs-open-file-button"
  l10nLabel="pdfjs-open-file-button-label"
  image="<svg style='width: 24px; height: 20px' viewBox='0 0 24 24'><path fill='currentColor' d='M14,2L20,8V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V4A2,2 0 0,1 6,2H14M18,20V9H13V4H6V20H18M12,12L16,16H13.5V19H10.5V16H8L12,12Z' /></svg>"
  [order]="200"
  [action]="onClick"
>
</pdf-shy-button>
```
Puedes cambiar el icon con el atributo `image`. Por defecto, la etiqueta y el tooltip del buton son generado por los atributos `l10n...`. Borra estas lineas. Ahora, puedes combiar la etiqueta y el tooltip por el atribute `title`:

```html
<pdf-shy-button
  [cssClass]="showOpenFileButton | responsiveCSSClass : 'hiddenMediumView'"
  primaryToolbarId="openFile"
  title="¿Por que no abres el archivo?"
  image="<svg style='width: 24px; height: 20px' viewBox='0 0 24 24'><path fill='currentColor' d='M14,2L20,8V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V4A2,2 0 0,1 6,2H14M18,20V9H13V4H6V20H18M12,12L16,16H13.5V19H10.5V16H8L12,12Z' /></svg>"
  [order]="200"
  [action]="onClick"
>
</pdf-shy-button>
```

<img width="354" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/4e45d733-b52d-45a9-aa06-0d5ae4be047f">

<img width="319" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/cca9739a-66ad-457a-96b2-d2b38483a9db">

**Comment by luis-cosillo** [comment]
gracias muy amable, logre cambiarlo, como mejora seria bueno que pudieras ponerle un icono de google, fontawesone. Solo eso le faltaria como sugerencia.

Muchas gracias por tu apoyo.

**Comment by luis-cosillo** [comment]
si exacto es bastante comun y eso ayudaria un monton. Pero mientras analizas ahorita funciona muy bien.

**Comment by luis-cosillo** [comment]
otra consulta el control al ponerlo

<pdf-shy-button
    [cssClass]="showOpenFileButton | responsiveCSSClass : 'hiddenMediumView'"
    primaryToolbarId="openFile"
    title="Buscar Archivo"
    l10nId="pdfjs-open-file-button"
    l10nLabel="pdfjs-open-file-button-label"
    image="<svg xmlns='http://www.w3.org/2000/svg' height='24' viewBox='0 -960 960 960' width='24'><path d='M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H600v-80h160v-480H200v480h160v80H200Zm240 0v-246l-64 64-56-58 160-160 160 160-56 58-64-64v246h-80Z'/></svg>"
    [order]="200"
    [action]="onClick">
</pdf-shy-button>

y al abrir la ventana para seleccionar archivos me muestra todos los archivos hay forma que le delimite solo los *.PDF??

**Comment by stephanrauh** [comment]
Quizas es posible. Hay el atributo `accept`. No funciona en todos los dispositivos, pero funciona en los ordinadores:
https://caniuse.com/?search=input%20accept

**Comment by stephanrauh** [comment]
The `accept=".pdf,application/pdf"` restriction is going to ship later today (version 19.4.0).
