### ISSUE TITLE
Highlighting Text Doesn't work

### ISSUE THREAD

**Issue by joywinmissier** [stephanrauh/ngx-extended-pdf-viewer#218]
```xml
<ngx-extended-pdf-viewer
        [handTool]="false"
        [showFindButton]="true"
        (handToolChange)="getSelect($event)"
      ></ngx-extended-pdf-viewer>
```

used the ngx package as mentioned above, but i was not able to see any colors when i highlight any text in pdf using mouse ( click and select the line), also how to retrieve the highlighted text in typescript code (example: like consoling that highlighted value using console.log)

**Comment by stephanrauh** [comment]
Try adding `[textLayer]="true"`. Your configuration should work, too, but sometimes `ngx-extended-pdf-viewer` omits the text layer even if it's needed. I've fixed the bug in the current 2.0.0-alpha version, but older versions suffered from this bug.

As for `(handToolChange)`: that's the event that's fired when switching between the "hand tool mode" and the select mode.

Extracting the selected text is a good idea. It's clearly beyond the scope of Mozilla's pdf.js project, so `ngx-extended-pdf-viewer` doesn't offer it, either. But let me have a look. Maybe it's a simple task.

**Comment by joywinmissier** [comment]
can you add extracting the selected text value feature to this package ? could you pls inform the status whether this fix will be implemented

**Comment by joywinmissier** [comment]
i am using alpha version only but [textLayer]="true" was not working i was not able to highlight the text when i drag over the text using mouse

**Comment by stephanrauh** [comment]
After doing some research, I'd like to ask you to implement the feature yourself. I'll tell you how to do that in a minute.

Why?

The solution relies on the selection API. To my surprise, this API is supported by every major browser, including Internet Explorer 11. But it's an experimental feature. It's not an accepted standard. It's merely an early draft of such a standard. Actually, the current version of the draft has been published today (!), so we can expect nasty surprises like breaking changes.

Plus, I didn't find out yet how to limit the event to the PDF viewer. My approach catches every selection. I could limit it to the PDF viewer. The first answer of https://stackoverflow.com/questions/48950038/how-do-i-retrieve-text-from-user-selection-in-pdf-js shows the way how to do this. However, it doesn't feel right yet. It's better to wait until the dust has settled, and to help early adopters like you extended the PDF viewer yourself.

That said, here's my solution:

```xml
  private getSelectedText() {
    return (window as any).getSelection().toString();
  }

  public registerSelectionListener() {
    document.addEventListener('selectionchange', (event: any) => {
      const text = this.getSelectedText();

      if (text) {
        console.log(text);
      }
    });
  }
```

You might also want to register the same event listener on the `window` object. It seems some browsers implement it on the document, while others use the window.

Use the solution at own risk!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
BTW, as for your missing text layer: what happens when you drag over a text up and down? Does the text move? You can also check the HTML sourcecode. Is every page just an image, or is there a text layer, like in this example:

![image](https://user-images.githubusercontent.com/3045767/75387453-abb7ee80-58e3-11ea-87d8-1155d07a7b22.png)
