### ISSUE TITLE
Popups are open and cannot be closed

### ISSUE THREAD

**Issue by doooot** [stephanrauh/ngx-extended-pdf-viewer#2192]
Hi,
I am using ngx-extended-pdf-viewer in my Angular 16 app and have some troubles. Seems like all pop-ups are visible and cannot be closed (screenshot)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/15938673/b039f04f-7ba6-41e5-aeb0-d5f1fbb43b7f)

The first popup (I moved it a bit from the top to see the message and it says "Preparing document for printing…") is totally unresponsive, and when I click "Close" on the popup underneath, I have an error "Error: The overlay is currently not active."

Did anyone have similiar problem? Do you have any solution for that?

**Comment by stephanrauh** [comment]
Did my hint help you? I'm closing the ticket now because I've seen similar problems often - but it'd be nice to know for sure!

Best regards,
Stephan
