### ISSUE TITLE
Not able to run .mjs files anymore in business central platform

### ISSUE THREAD

**Issue by jbaan** [stephanrauh/ngx-extended-pdf-viewer#2196]
**Describe the bug**
As of version 4.0, almost all files in the npm package to have the .mjs format. However in some old web platforms, like MS Business Central this mime type extension cannot be used. That means we need to stay on 3.0 version. 
Are there more people having this issue?

**Comment by stephanrauh** [comment]
I hope the community chimes in... in the mean time, here are my two pence: it wasn't my decision to migrate to the *.mjs format. I was caught by surprise, too. But I'm afraid there's no (easy?) way back. Node.js treats *.mjs files different than *.js files.

However, our runtime environment isn't node.js. It's the browser. Is the difference between *.mjs and *.js a thing in browser country? I learned the hard way that many servers don't support *.mjs files in 2024, although it's got seven years of history.

**Comment by papes1ns** [comment]
I'm experiencing the same issue with the project I'm working on that is hosted on Azure. The requests for the `.mjs` files are resulting in a 404 despite the files existing in the assets directory.

I'm looking into the issue as well. Currently am not able to replicate the file server error when running the prod bundle locally following [Angular's guide for using lite-server](https://angular.io/guide/deployment#simple-deployment-options) to test.

I confirmed the `pdf-4.0.850.min.mjs` is in the assets directory alongside other static assets that are served just fine.

Will update if I learn more. Sounds like the MS file server we are using is refusing to serve `.mjs` files?

**Comment by stephanrauh** [comment]
@Timvandermeij I wonder if I can simply rename the distribution files to *.js again. The advantage of *.mjs files is you can use `import` and `export`. However, looking at your distribution https://www.npmjs.com/package/pdfjs-dist, I don't see any `import`. It's all replaced by Webpack.

What am I missing?

**Comment by jbaan** [comment]
I really like the functionality of the ngx-extended-pdf-viewer so continued to get it working in Business Central. Using the npm package in Angular will build a vendor.js file, which is fine and workable in Business Central, which means then only remaing .mjs files are in the assets folder (pdf.mjs, pdf.worker.mjs and viewer.mjs). So I pointed for the the pdfDefaultOptions to to the cdn.jsDeliver
pdfDefaultOptions.assetsFolder = `https://cdn.jsdelivr.net/npm/ngx-extended-pdf-viewer@19.4.1/assets`;

This will start the pdf viewer in Business central, but now there is a bug in the loadViewer code, that is replacing all .js to .mjs for the workerSrc, even the .js in the word .jsDeliver

if (pdfJsPath.endsWith('.mjs')) {
                        const src = pdfDefaultOptions.workerSrc();
                        pdfDefaultOptions.workerSrc = () => src.replace('.js', '.mjs');
                    }

Then it will try to find the workerSrc on mjsDeliver

https://cdn.mjsdelivr.net/npm/ngx-extended-pdf-viewer@19.4.1/assets/...worker.mjs

**Comment by JJRimorin** [comment]
Also encountering the same problem but with the viewer.ftl file. The project is hosted in Azure but the file is not found. Upon checking the assets folder, the file is there alongside other static files

**Comment by stephanrauh** [comment]
@JJRimorin What happens if you enter the URL of the *.ftl file? Is the browser able to load and show it?

**Comment by stephanrauh** [comment]
@jbaan Oops. That's a use-case I wasn't aware of!

**Comment by capraibex** [comment]
We are hosting our project also at Azure and had the situation where the .mjs files didn't load and the following error message was shown in the browsers devConsole:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/32867660/c27e4a0b-9798-4b5b-b135-b3877009bde2)

We solved the problem by overwriting the _Content-Type_ with the correct "text/javascript".
You can do this in the Azure Portal -> CDN -> Settings -> Rules Engine
by adding the following rule:
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/32867660/2382cbd8-180c-48f3-87b9-7dcb8b0c786c)

Maybe this is of help for someone encountering similiar issues
FYI @papes1ns @JJRimorin @stephanrauh

**Comment by JJRimorin** [comment]
Here's the error I'm getting @stephanrauh 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/100825638/2dd52e10-6bce-472f-a15f-892b4fa053fa)

And if I enter the *.ftl in the browser, it throws an Error 404 though the file is in the assets folder.

**Comment by stevenknox** [comment]
@JJRimorin what do you mean you changed the file type? Im having the same issue on windows.. do you mean change it to something like viewer.txt  ? and if so how does ngx-extended-pdf-viewer know to look for the different file type?

**Comment by JJRimorin** [comment]
@stevenknox our webserver does not recognized the *ftl so I change the file type into a recognizable file type. I think the package just only check the file link which is in the locale.json and the package will handle the file itself. Refer to the image below.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/100825638/f92ac34a-9746-416a-ae0f-49dcc8d6b87c)

**Comment by stephanrauh** [comment]
@JJRimorin First of all, I'm happy you've found a solution! I just wonder why you locale files land in the folder `assets/pdf`. You've shown the relevant part of the `angular.json`, so I'd expect your target folder to match the folder structure of `node_modules/ngx-extended-pdf-viewer`:
<img width="264" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/f521849e-4a23-43c4-9e0f-3978b9106f25">

**Comment by stephanrauh** [comment]
@jbaan @papes1ns Does the hint of @capraibex help you? It's what I try to explain in the first place, but I'm not familiar with your server, so I couldn't provide you with a decent walk-through.

@capraibex Thank you very much for chiming in and sharing your insight with us!

**Comment by papes1ns** [comment]
Yes! Appreciate y'all for pointing me in the right direction @stephanrauh and @capraibex.

I ended up adding a line like this to our reverse proxy config
```
<staticContent>
  <mimeMap fileExtension=".mjs" mimeType="text/javascript" />
</staticContent>
```

Now the browser can GET those PDF.js v4 asset files successfully.

**Comment by stephanrauh** [comment]
To dos left:
- [ ] document how to configure the most popular servers correctly
- [ ] check if we really need *.mjs files

**Comment by habtista-peco** [comment]
> @JJRimorin what do you mean you changed the file type? Im having the same issue on windows.. do you mean change it to something like viewer.txt ? and if so how does ngx-extended-pdf-viewer know to look for the different file type?

Hey, on Windows, add the following to your web.config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>

<system.webServer>
 <staticContent>
  <mimeMap fileExtension=".mjs" mimeType="text/javascript" />
  <mimeMap fileExtension=".ftl" mimeType="text/plain" />
 </staticContent>
</system.webServer>

</configuration>
```

**Comment by stephanrauh** [comment]
@habtista-peco Would you mind to add with server you're using?

**Comment by stevenknox** [comment]
This was how i resolved in .NET 8 as adding the MIME Type to IIS didnt work for me 

```csharp 
var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".ftl"] = "text/plain"; 

app.UseStaticFiles(new StaticFileOptions
{
    ContentTypeProvider = provider
});```

**Comment by venkycoder422** [comment]
@capraibex which you give a solution CDN->Rules engine setting cost any amount? or any other solution if it cost?

**Comment by stephanrauh** [comment]
@venkycoder422 Why do you think it does cost something if you're configuring the server?

**Comment by venkycoder422** [comment]
@capraibex I had a research on it so I found this documentation it's telling clearly allowing CDN costs.... 

But one more I have tried @papes1ns solution <staticContent>
  <mimeMap fileExtension=".mjs" mimeType="text/javascript" />
</staticContent>     on web.config it working fine now.

**Comment by peopledrivemecrazy** [comment]
I'm having the same issue with AWS Amplify hosting. I don't see an option to add mime types based on file extensions.

**Comment by stephanrauh** [comment]
I've asked ChatGPT. It's answer looks sensible, but as so often, I don't know whether it's a plausible hallucination, so please report wether the answer was useful or not:

You can configure AWS Amplify to deliver *.mjs files with the Content-Type header set to "application/javascript". This is particularly important for ensuring that browsers correctly interpret these files as JavaScript modules.

To configure the Content-Type for *.mjs files in AWS Amplify, you will need to adjust the settings in your project's amplify.yml file or directly modify the headers through the AWS Management Console. Here are the general steps you can follow:

    Amplify Console Configuration:
        Go to the AWS Amplify Console, and select your application.
        Navigate to "Rewrites and redirects" under the "App settings" tab.
        Here, you can add a new rule to set the Content-Type for *.mjs files:
            Source address: </^.*\.mjs$/> (This regex matches any .mjs files)
            Target address: <Enter the same as source address>
            Type: 200 (Rewrite)
            Add a header: Content-Type: application/javascript

    Editing the amplify.yml File:
        If you prefer to configure headers via the amplify.yml file, you can specify custom headers under the customHeaders section. Here is an example snippet you might include in your amplify.yml:

        yaml

        customHeaders:
          - pattern: '*.mjs'
            headers:
              - key: 'Content-Type'
                value: 'application/javascript'

        This configuration ensures that any .mjs files served by Amplify are delivered with the correct MIME type.

By setting up these configurations, you ensure that all .mjs files served by your AWS Amplify application are treated as JavaScript modules by the browsers, which is essential for proper module functionality. Make sure to test your configuration changes in a development environment before deploying them to production to avoid any disruptions.

**Comment by stephanrauh** [comment]
I've failed to go back to the old *.js files. It's not entirely impossible, but it's beyond my scope. More to the point, I'm afraid it's a lot of work, and there's only so much I can do in my leisure time. So unless you're ready to talk to my boss and to pay my work, I'll stick to the new *.mjs files. I'm a consultant, so hiring me is always an option, but unless you do, this project is a 100% leisure time project.

To dos left:
- [ ] add a page describing the problem and collecting solutions to the showcase

**Comment by stephanrauh** [comment]
@jbaan Your bugfix is going to land with version 20.0.0-alpha.3.

**Comment by bh3605** [comment]
If anyone stumbles along this issue and is using an Azure Web App, this web.config will work for you as it did for me. The `.mjs` and `.ftl` mappings will get you working.
```
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
            <mimeMap fileExtension=".importmap" mimeType="application/importmap+json" />
            <mimeMap fileExtension=".mjs" mimeType="application/javascript" />
            <mimeMap fileExtension=".ftl" mimeType="text/html" />
        </staticContent>
        <rewrite>
            <rules>
                <rule name="Main Rule" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

**Comment by bh3605** [comment]
@stephanrauh I posted a fix above. Mapping `.mjs` as `text/javascript` didn't work, but `application/javascript` did.

**Comment by stephanrauh** [comment]
@bh3605 I've added your configuration to the documentation in the showcase.
