### ISSUE TITLE
No way I could hide the side bar (contents).

### ISSUE THREAD

**Issue by rasheeek** [stephanrauh/ngx-extended-pdf-viewer#2206]
I am using the PDF viewer in an Ionic Angular application, everything works fine, but for mobile I dont see any way to close the side bar. I see this issue already submitted years back [issue](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/6)

My code

```
   <ngx-extended-pdf-viewer
  [showBookModeButton]="false"
  [showDownloadButton]="false"
  [showDrawEditor]="false"
  [showFindButton]="false"
  [showHorizontalScrollButton]="false"
  [showInfiniteScrollButton]="false"
  [showPagingButtons]="false"
  [showPrintButton]="false"
  [showPropertiesButton]="false"
    [showSecondaryToolbarButton]="false"
    [showSidebarButton]="false"
    [showSpreadButton]="false"
    [showToolbar]="false"
    [src]="pdfSrc"
    [page]="initialPage"
    zoom="page-fit"
    (pageChange)="onPageChange($event)"
    useBrowserLocale="true"
    (pagesLoaded)="onPagesLoaded($event)"
  ></ngx-extended-pdf-viewer>
```

![Screenshot_1710112948](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/52084424/76015198-01b3-4da8-9dd7-5c3edaec80eb)

**Version info**
1.8.0-rc.1

**Comment by stephanrauh** [comment]
Oh, oh, version 1.8.0-rc.1? Please update to the current version - that's 19.4.x. You'll benefit from a ton of improvements and bug fixes! In particular, if I fix a bug for you, I only fix the newest version. 

You're looking for the attribute `[(sidebarVisible)]`. It's an old attribute - but I don't know if it was already there in version 1.8.0. But I think so.

There's also a showcase page containing a live demo: https://pdfviewer.net/extended-pdf-viewer/custom-sidebar
