### ISSUE TITLE
PDF viewer quality has been degraded

### ISSUE THREAD

**Issue by rohsingh16** [stephanrauh/ngx-extended-pdf-viewer#2207]
While viewing training documentation in our training page's PDF Viewer the screenshot quality is poor and blurry. However, when downloading the same training, the screenshot quality improves. 

Please let me know any configuration to address the same.

**Comment by stephanrauh** [comment]
"Has been degraded" sounds like "it used to be better"? That's unlikely, but if so, please tell me when it got worse.

Generally speaking, most documents render fine. I don't have a clue why your document is blurry. You can try to increase the attribute `[printResolution]`. By default, it's 150. When you increase it, rendering slows down. When I implemented the attribute a long time ago, the upper limit was 1100 dpi, but that depends on the PDF file.
