### ISSUE TITLE
Disable ctrl+p option

### ISSUE THREAD

**Issue by Srikanth9142** [stephanrauh/ngx-extended-pdf-viewer#222]
**I want to develop webapp where users access the pdf files within the app**

**It will be very easy for Developers to choose the this module but when user click ctrl + p and then save as pdf then the pdf will be downloaded for them. I would like to disable this feature**

**I would like to thanks for the power packed module.I personally liked it**

**Comment by stephanrauh** [comment]
You can hide the print dialog: `[showPrintButton]="false"` plus `window.print=function(){}` and `[ignoreKeys]="[CTRL+P]"`. This prevents printing entirely. 

Unfortunately, there's no way to allow printing while removing the "save as PDF" option.

**Comment by Srikanth9142** [comment]
I tried this [showPrintButton]="false" and [ignoreKeys]="[CTRL+P]" but not solved!! I tried ignoring 'P' and 'N' keys they worked fine but ctrl+p is not ignored
![Screenshot (262)](https://user-images.githubusercontent.com/40908115/75605906-316ab280-5b0d-11ea-90f7-d2cc033fc390.png)

**Comment by stephanrauh** [comment]
I wonder if I should add an option like, say, `enablePrinting="false"`. That'd allow me to address the root of the problem.

@Srikanth9142 (and @ everybody): What's your opinion?

**Comment by stephanrauh** [comment]
@Srikanth9142 Ping? Are you still there?

**Comment by Srikanth9142** [comment]
> @Srikanth9142 Ping? Are you still there?

yes iam waiting for the update to use in my webapp

**Comment by stephanrauh** [comment]
Great! There you are: `[enablePrint]="false"` has landed in version 2.0.0-alpha.17.

Enjoy!
Stephan

**Comment by Srikanth9142** [comment]
Thank you so much for the update!!
