### ISSUE TITLE
Thumbnails loading in sidebar - by scrolling show first a broken image until the thumbnail has been loaded

### ISSUE THREAD

**Issue by webarp** [stephanrauh/ngx-extended-pdf-viewer#2224]
Hi,

the viewer is amazing. Thanky you for an amazing job.

I've noticed a small issue if a pdf has too many pages.

The thumbnails on the sidebar are loading an empty img tab (<img alt="miniature of the page" class="thumbnailImage">) until the actual thumbnail is loaded.

By fast scrolling, the browsers are showing a broken image for a few seconds and afterwards the thumbnail. Once the thumbnails are loaded, this doesn't happen anymore. It happens only by initial scrolling.

You can also see it here, in your sample:

https://pdfviewer.net/extended-pdf-viewer/simple 

Open the sidebar and scroll fast the thumbnails.

It would be great if you can show a loading icon as src as long as the thumbnail loads or completely remove the img tag before a thumbnail has been loaded.

Your fix is very much appreciated.

Regards
![PDF-viewer](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/54836347/d93a84d4-e592-41f6-b2f9-89f5db238892)

**Comment by Preitelio** [comment]
Hi
yes I've noticed that too, that would be a nice update. :) 
I hope you can implement it.

Thank you for your work

**Comment by stephanrauh** [comment]
I've also noticed it, but on my local developer machine, everything loads to fast it never managed to catch my attention. :) You're right, let's fix this. It should be easy. 

In the meantime, I believe you can even do it yourself with a bit of global CSS:
```css
#thumbnailView img.thumbnailImage {
   display: none;
}
#thumbnailView div[data-loaded="true"] img.thumbnailImage {
   display: unset;
}
```
Please consider the code snippet as pseudo-code - I always forget the precise syntax, I'm sure there's a bug or two.

**Comment by webarp** [comment]
Hi Stephan,

thank you very much for your fast reply.

It worked like a charm. :)

Best Regards

**Comment by stephanrauh** [comment]
Starting with version 19.5.0, you don't need the additional CSS. Thumbnails are hidden by default until they have been rendered.

**Comment by webarp** [comment]
Thank you very much, Stephan
