### ISSUE TITLE
PdfHighlightEditorComponent  already working?

### ISSUE THREAD

**Issue by APOSWE** [stephanrauh/ngx-extended-pdf-viewer#2228]
Hello!

First of all, great pdf-viewer!!

Is the PdfHighlightEditorComponent already working?
I'm using Version 19.4.1, set the AnnotationEditorMode to 9 and there is still no possibility to highlight because the button is hidden?
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/115154268/16023fa4-e30a-42b9-861e-dc527aec772b)
Unfortunately I couldn't find any further information, please help :)

Thanks in advance!

**Comment by stephanrauh** [comment]
Yes, it's working. But it's still deactivated. I'm waiting until the pdf.js activates it by default. I can only guess, but I suppose there are still some open issues. That's also the reason why I haven't documented the feature yet. That, and a lack of time to spare. :)

To see the preview, just enter this line in the developer tools while the PDF viewer is running:
```html
document.querySelector("#editorHighlight").hidden=false;
```
I've yet to add an image to the button, so all you see is a "gap in the teeth" of the toolbar, but when you click the gap, you can see the highlight editor in action.

**Comment by stephanrauh** [comment]
I've just removed the "hidden" attribute and noticed the highlight editor does not work properly.

**Comment by stephanrauh** [comment]
I've fixed a bug in version 19.6.0. Now the feature should work. I've also removed the `hidden` attribute.

**Comment by APOSWE** [comment]
Yeah button is working now. But it looks like that ParamsToolbar is not working.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/115154268/fbd90e3b-1d92-4547-aca1-7b9a831481e9)
19.4.1

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/115154268/0ee422f7-b706-4ad5-9a2f-88f7ca433728)
19.6.1

I also added a hostlistener to close any toolbar with the first press of ESC. And with the second to the main mode.
(AnnotationEditorTypeValue is not exported yet)
`
// HostListener for control the modes
  @HostListener("document:keydown", ["$event"])
  handleKeyboardEvent(event: KeyboardEvent) {
    // First ESC ist to close the ParamsToolbar, second to close the mode

    let anyClosed = false;
    if (event.key === "Escape") {
      // first hide toolbar
      anyClosed = this.#hideParamsToolbar(anyClosed);

      // if all hidden, switch to main mode
      if (!anyClosed && this.currentAnnotationEditorMode > 0) {
        this.#switchBackToMainMode();
      }
    }
  }

  #switchBackToMainMode() {
    switch (this.currentAnnotationEditorMode) {
      case 3 /* editorModeFreeText */:
        document.getElementById("editorFreeText")?.click();
        break;

      case 9 /* editorModeHighlight */:
        document.getElementById("editorHighlight")?.click();
        break;

      case 13 /* editorModeStamp */:
        document.getElementById("editorStamp")?.click();
        break;

      case 15 /* editorModeInk */:
        document.getElementById("editorInk")?.click();
        break;

      default:
        break;
    }
  }

  #hideParamsToolbar( anyClosed: boolean) {
    const highlightToolbar = document.getElementById("editorHighlightParamsToolbar");
    if (!highlightToolbar?.classList.contains("hidden")) {
      highlightToolbar?.classList.add("hidden");
      anyClosed = true;
    }
    const freeTextToolbar = document.getElementById("editorFreeTextParamsToolbar");
    if (!freeTextToolbar?.classList.contains("hidden")) {
      freeTextToolbar?.classList.add("hidden");
      anyClosed = true;
    }
    const freeInkToolbar = document.getElementById("editorInkParamsToolbar");
    if (!freeInkToolbar?.classList.contains("hidden")) {
      freeInkToolbar?.classList.add("hidden");
      anyClosed = true;
    }
    const freeStampToolbar = document.getElementById("editorStampParamsToolbar");
    if (!freeStampToolbar?.classList.contains("hidden")) {
      freeStampToolbar?.classList.add("hidden");
      anyClosed = true;
    }
    return anyClosed;
  }
`

**Comment by stephanrauh** [comment]
The broken button is now gone (and it's displayed properly if you're using the bleeding edge branch of pdf.js). Other than that, I think the highlight editor works. What's missing?

For some reason, the highlight popup doesn't hide when clicking the button twice. I guess that's an open bug.
