### ISSUE TITLE
Disabling Page Flip Animation in Version 19

### ISSUE THREAD

**Issue by inthej** [stephanrauh/ngx-extended-pdf-viewer#2238]
Hello ngx-extended-pdf-viewer Team,

I'm currently using version 19.4.1 of ngx-extended-pdf-viewer in my Angular project, and I've encountered an issue with the duration of the page flip animation. The animation time feels excessively long, and I'm looking to speed it up as much as possible.

Despite trying different methods, including manipulating CSS and JavaScript, the animation still seems slow. I would appreciate any guidance on how to adjust or disable this animation. Additionally, if there are any plans to include a feature for controlling animation speed in a future release, that information would be very helpful.

Thank you for your assistance and for the excellent work on this library!

Best regards,
INTHEJ

**Comment by stephanrauh** [comment]
This sounds like you're looking for the single-page mode. Combine it with even or odd spread, and you've got the book mode without page flip animation.

https://pdfviewer.net/extended-pdf-viewer/page-view-mode
