### ISSUE TITLE
Print Icon Click Pdf open in New Tab

### ISSUE THREAD

**Issue by prasanthnsn11** [stephanrauh/ngx-extended-pdf-viewer#224]
Is There any feature or any options To open the pdf in a new tab while Clicking on the print icon in the pdf viewer to open the view in new Tab in Browser ??

**Comment by stephanrauh** [comment]
With version 2.0.0, you can do that. Just hide the regular print button and replace it with a "open in new tab" button.

**Comment by stephanrauh** [comment]
I've implemented the feature for you. Have a look at https://pdfviewer.net/custom-toolbar and choose the "additional buttons" demo. I suppose that's all you need. But here's the sourcecode, just in case: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/master/src/app/custom-toolbar
