### ISSUE TITLE
Error Retrieving Annotations with ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by pramane2309** [stephanrauh/ngx-extended-pdf-viewer#2242]
**Description**
Hello,
I've encountered an error while using ngx-extended-pdf-viewer in my project. Here's a summary of the issue:

1. I'm using ngx-extended-pdf-viewer to display a PDF with a form using formData as the source.
2. I've added an annotation using the draw editor.
3. I want to check if the user creates an annotation from the draw editor (I want to use annotation type = 15) and then enable a button.
4. I used the getSerializedAnnotations function from the API to check this.
5. However, I'm encountering an error: "TypeError: e.serialize is not a function."
6. This error occurs when calling the getSerializedAnnotations function.

WIthout a form it's working

**DATA SET**

`{
    "63R": {
        "value": "fakeValue"
    },
    "66R": {
        "value": "fakeValue"
    },
    "67R": {
        "value": "fakeValue"
    },
    "68R": {
        "value": "fakeValue"
    },
    "69R": {
        "value": "fakeValue"
    },
    "70R": {
        "value": "fakeValue"
    },
    "71R": {
        "value": "fakeValue"
    },
    "72R": {
        "value": "fakeValue"
    },
    "73R": {
        "value": "fakeValue"
    },
    "74R": {
        "value": "fakeValue"
    },
    "pdfjs_internal_editor_0": {
        "_initialOptions": {},
        "_uiManager": {
            "_eventBus": {},
            "viewParameters": {
                "realScale": 1.4666666666666668,
                "rotation": 0
            },
            "highlightColors": {},
            "direction": "ltr"
        },
        "_focusEventsAllowed": true,
        "_l10nPromise": null,
        "doNotMove": true,
        "parent": {
            "pageIndex": 0,
            "div": {
                "__zone_symbol__pointerdownfalse": [
                    {
                        "type": "eventTask",
                        "state": "scheduled",
                        "source": "HTMLDivElement.addEventListener:pointerdown",
                        "zone": "angular",
                        "runCount": 0
                    }
                ],
                "__zone_symbol__pointerupfalse": [
                    {
                        "type": "eventTask",
                        "state": "scheduled",
                        "source": "HTMLDivElement.addEventListener:pointerup",
                        "zone": "angular",
                        "runCount": 0
                    }
                ],
                "__zone_symbol__ON_PROPERTYpointerdown": null,
                "__zone_symbol__ON_PROPERTYpointerup": null
            },
            "viewport": {
                "viewBox": [
                    0,
                    0,
                    595.276,
                    841.89
                ],
                "scale": 1.4666666666666668,
                "rotation": 0,
                "offsetX": 0,
                "offsetY": 0,
                "transform": [
                    1.4666666666666668,
                    0,
                    0,
                    1.4666666666666668,
                    0,
                    0
                ],
                "width": 873.0714666666667,
                "height": 1234.7720000000002,
                "rawDims": {
                    "pageWidth": 595.276,
                    "pageHeight": 841.89,
                    "pageX": 0,
                    "pageY": 0
                }
            },
            "drawLayer": {
                "pageIndex": 1
            }
        },
        "id": "pdfjs_internal_editor_0",
        "height": 0.07837985474241398,
        "width": 0.16797737138280852,
        "pageIndex": 0,
        "name": "inkEditor",
        "div": {
            "__zone_symbol__focusinfalse": [
                {
                    "type": "eventTask",
                    "state": "scheduled",
                    "source": "HTMLDivElement.addEventListener:focusin",
                    "zone": "angular",
                    "runCount": 0
                }
            ],
            "__zone_symbol__focusoutfalse": [
                {
                    "type": "eventTask",
                    "state": "scheduled",
                    "source": "HTMLDivElement.addEventListener:focusout",
                    "zone": "angular",
                    "runCount": 0
                }
            ],
            "__zone_symbol__pointerdownfalse": [
                {
                    "type": "eventTask",
                    "state": "scheduled",
                    "source": "HTMLDivElement.addEventListener:pointerdown",
                    "zone": "angular",
                    "runCount": 0
                }
            ],
            "__zone_symbol__keydownfalse": [
                {
                    "type": "eventTask",
                    "state": "scheduled",
                    "source": "HTMLDivElement.addEventListener:keydown",
                    "zone": "angular",
                    "runCount": 0
                }
            ]
        },
        "annotationElementId": null,
        "_willKeepAspectRatio": true,
        "rotation": 0,
        "pageRotation": 0,
        "pageDimensions": [
            595.276,
            841.89
        ],
        "pageTranslation": [
            0,
            0
        ],
        "x": 0.010503196426016404,
        "y": 0,
        "isAttachedToDOM": true,
        "deleted": false,
        "color": "#e75432",
        "thickness": 0.5402164714880331,
        "opacity": 1,
        "paths": [
            [
                [
                    [
                        0.43531647645900856,
                        124.46424504788753
                    ],
                    [
                        0.43531647645900856,
                        41.147102190744654
                    ],
                    [
                        82.80567361931615,
                        -0.5114692378266942
                    ],
                    [
                        166.122816476459,
                        41.147102190744654
                    ]
                ]
            ]
        ],
        "bezierPath2D": [
            {}
        ],
        "allRawPaths": [],
        "currentPath": [],
        "scaleFactor": 0.8791022255752546,
        "translationY": 0,
        "translationX": 0,
        "canvas": {},
        "ctx": {}
    }
}`

**Version info**
- 19.5.1 & 17.4.3

**Demo PDF file**
i can't share the pdf file at this time

**Comment by stephanrauh** [comment]
Sorry for responding late. I've noticed the bug yesterday and solved it. Please update to the latest version (19.6.6 or higher).

Until version 19.6.6, removing editors also removed form fields. I've fixed that, too.

**Comment by stephanrauh** [comment]
Both bug fixes have landed with version 19.7.0.
