### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by sagarp4412** [stephanrauh/ngx-extended-pdf-viewer#2245]
I'm using **Angular Version 13.3** with SSR. Now, I've installed **"ngx-extended-pdf-viewer": "^13.5.3"** Into my project.
It's working well. But when I run with SSR it throw errors and website going to to stop with 402 Bad Getaway signal

Please have a look at this screenshot:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/15952897/93844db6-f5f9-4b37-98b7-ca8bf7f99dc5)

**Comment by stephanrauh** [comment]
The current version of the PDF viewer is 19.5.1. Please use this version. More likely than not, it fixes your bug. If it doesn't, you've defined the console filter yourself, and you'll have to modify it:

```ts
globalThis['ngxConsoleFilter'] = (_level: string, _message: any): boolean => {
  return true;
};
```

**Comment by stephanrauh** [comment]
BTW, at the time of writing, it's better to use version 19.4.x. I've accidentally introduce some minor bugs. If everything goes according to plan, these bugs are gone after the Easter holiday, so you can resume using version 19.5.x next week.

**Comment by sagarp4412** [comment]
As per your suggestion, I've installed 19.4.1 but it's not compatible with angular version 13.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/15952897/93edfdc2-5ad6-486c-b8a3-2cde54633c7a)

**Comment by sagarp4412** [comment]
Now, I've Installed "ngx-extended-pdf-viewer": "^16.2.16" version. And now again facing **ReferenceError: Window is not defined** Error.
Can you please tell me how can I resolve it?

**Comment by sagarp4412** [comment]
As per your suggestion, I've added ngxConsoleFilter In my angular component. But when I run through SSR still get errors. 
**ReferenceError: Window is not defined**

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/15952897/3f549efe-88de-4c86-aeea-357675510c42)

**Comment by stephanrauh** [comment]
I've answered this some time ago, but it seem my answer is lost. So please apologize me for answering late!

This is how I've solved the SSR issue:

```ts
  constructor(private pdfService: NgxExtendedPdfViewerService, @Inject(PLATFORM_ID) private platformId: any, private windowRefService: WindowRefService) {
    if (windowRefService.nativeWindow) {
      globalThis['ngxConsoleFilter'] = (level: string, message: any): boolean => {
        if (message?.includes && message?.includes('modified by ngx-extended-pdf-viewer')) {
          this.version = message;
          return false;
        }
        return true;
      };
    }
```
and 
```ts
import { Injectable } from '@angular/core';
function _window(): any {
  // return the global native browser window object
  return window;
}
@Injectable()
export class WindowRefService {
  get nativeWindow(): any {
    return _window();
  }
}
```

**Comment by stephanrauh** [comment]
I've just run into a similar issue myself. SSR seems to be quite a challenge!
<img width="899" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/b9e0e507-8b03-4e10-9d3e-64182ec50a58">

**Comment by stephanrauh** [comment]
Now the `NgxExtendedPdfViewerService` also supports SSR.

**Comment by sagarp4412** [comment]
Thank you. It's working
