### ISSUE TITLE
Text select with range

### ISSUE THREAD

**Issue by APOSWE** [stephanrauh/ngx-extended-pdf-viewer#2246]
Hello again 😊!
I would like to add a toolbar option where I can select an area and read the text within that area.
The area should be marked with a frame.
Some of the functions are already available.
- Select text
- Draw frames
Is it possible to add new toolbar functions from outside?
Is it anyhow possive to subscribe on an event "text selected".

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/115154268/93422fcd-2f7d-4c36-a8bb-5cf77db8a0db)

I was looking for some hours now and and unfortunately I didn't get much further...

**Comment by stephanrauh** [comment]
- You can define custom toolbar. They allow you to add additional buttons.
- The "select text" function is simply standard HTML. There's an invisible text layer above the PDF canvas. Usually, the text layer is using the wrong font, but it's almost perfectly matched with the text in the canvas, and selecting makes the invisible text visible. You can try the `selectionchange` event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/selectionchange_event
- Reading a text in an arbitrary rectangle probably isn't easy, but you should be able to iterate over every child of the text layer and use `getBoundingClientRect()` to find the `<span>` within the rectange: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by stephanrauh** [comment]
Does this answer your question? If so, please close the ticket.

BTW, when you've got a working solution, would you mind to share it with the community? It'd be a great addition to the showcase.

Thanks in advance,
Stephan

**Comment by APOSWE** [comment]
We will see 😊 I'll try and give my best! 
I'm also still in the process of understanding the basic ideas behind the structure of the library. It's just a lot to start with!
It would be great if we could share it with the community! 
I'll keep you informed!
Alex
