### ISSUE TITLE
Text within the text block is printed upside down (independent line)

### ISSUE THREAD

**Issue by bryanwac** [stephanrauh/ngx-extended-pdf-viewer#2255]
Hi, has been a while since we talk !

Now I'm facing this error:

I am using this function to add a text-block into my pdf on page with pageNumber X:

```ts
public async addTextEditorForPage(pageNumber: number): Promise<void> {

    let usuario = JSON.parse(this.storage.read('usuario'));
    let cpfFormatado = usuario?.documento?.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/, '***.$2.$3-**');

    const textEditorAnnotation: FreeTextEditorAnnotation = {
      annotationType: 3,
      color: [0, 0, 0],
      fontSize: 10,
      value: `Assinado digitalmente por:\n${usuario.nome}.\nDocumento: ${cpfFormatado}`,
      pageIndex: pageNumber - 1, // Índices de página começam do 0
      rect: [
        70, // espaço entre a borda da esquerda e o texto
        0,
        0,
        this.pageHeight - 30, //posicao baseada na orientação da pagina
      ],
      rotation: 0,
    };
    this.addedAnnotations.push(textEditorAnnotation);
    this.pdfService.addEditorAnnotation(textEditorAnnotation);
    this.editStylesOfEditToolBar();
  }
```
  
  The text is correctly added, and displayed this way:
  
  
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/ce31bd65-ae2f-4c64-ad52-3fd77dc8b32b)

And I am using the line below to save PDF as blob:

```ts
const blob = await this.pdfService.getCurrentDocumentAsBlob();
```

the blob is uploaded on aws and I save it to my database.

==============================================

I am facing this issue here that I would like to use ur help:

If I just add the text-block, and do not resize it / move it, this happens:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/70102177/1c9670ee-f7ad-40d3-b708-bf48fd76ce4b)

The text-block moves left and up sides, and all lines on the text-block turn upside down.

I could not replicate this on ur trial version, cz If I place a text-block there, with content, and do not resize or move, the block is not gettin printed on pdf when I download it.

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug. It's really strange:

- Printing renders the text upside-down and with the wrong font size.
- After downloading the document, Chrome doesn't render the text at all. Apple Preview and Firefox display the text upside-down.
- I can move the test to the left, to the right, and up, but I can't move it downwards.

**Comment by stephanrauh** [comment]
It seems to be a problem with your coordinates.

- `right` must be greater than `left`. Otherwise, the text is rendered upside-down.
- if the difference between `left` and `right` is too small, the font size is adjusted so the text fits into the box. That's why my reproducer seems to ignore the font size.
- `bottom=0` prevents the text from being moved downwards. 
 
So you've defined a box that spans almost the entire page but it only zero pixels wide. That confuses other PDF renderers and the printer. It's weird that the print function is confused because it's the same renderer. But maybe there's a small difference.
