### ISSUE TITLE
Locale.json getting from same domain when setting assetsFolder

### ISSUE THREAD

**Issue by YaromichSergey** [stephanrauh/ngx-extended-pdf-viewer#2259]
Trying to use library files from different domain to cache it. pdfDefaultOptions.assetsFolder setting to static.domain.com for example but locale(locale.json) files requested from current(mydomain.com/assets/locale/locale.json). Is it possible to also ask locale from assetsFolder? It's bug?

**Comment by stephanrauh** [comment]
I've set `pdfDefaultOptions.assetsFolder = 'http://127.0.0.1:4200/assets'` and now it loads the pdf.js resource files from "127.0.0.1" (instead of using "localhost"). So I don't think there's a bug. What does your configuration look like?

**Comment by YaromichSergey** [comment]
All resource files loaded from assetsFolder except of locale. 
We have something like https://{dynamicname}.domain.com. All resources we want to take from https://static.domain.com. We faced with issue with cache so we decided to make own version for assets. And full assetsFolder looks like 'https://static.domain.com/assets/version19_5' and in angular.json move files to assets/version19_5.Files  'mjs' works fine, but assets(also locally) trying to request from /assets/locale. We expect /assets/version19_5/locale.

**Comment by YaromichSergey** [comment]
Hi, any other news about this?

**Comment by stephanrauh** [comment]
I'm afraid I don't have any news. I don't know how to reproduce your issue. And it's hard to solve an issue I can't see. Maybe you can help me with an idea how to reproduce it?

**Comment by YaromichSergey** [comment]
Steps to reproduce:
1. After installing files, in angular.json 
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/pdfview3/"
              },
2. In component, which using ngx-extended-pdf-viewer, in ngOnInit(can be something else) 
pdfDefaultOptions.assetsFolder = 'https://static.' + environment.mainDomain + '/assets/pdfview3'; 
And when we trying to use like this, javascript files works as expected, but locale trying to fetch from http://localhost:4200/assets/locale/locale.json (expecting http://localhost:4200/assets/pdfview3/locale/locale.json).

Looks like assets/locale hardcoded and not related to assetsFolder variable.

**Comment by YaromichSergey** [comment]
assetsFolder it's sample how we want to use it. In localhost, i try to emulate to show you, what I'm expecting. Hope you undestand idea and it might be enough.

**Comment by stephanrauh** [comment]
I've followed your steps and ended up with https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue2259. It works flawlessly. Can you clone or download my reproducer and check whether it works on your machine, too? That should enable you to hunt down the difference between your project and my project.

<img width="808" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/231b7f81-f941-4661-b4b3-70a9db3da40a">

**Comment by YaromichSergey** [comment]
That works fine on your project. But when I'm trying to use on own, still have 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/21965993/8cd551d0-eb55-4b9c-9266-58774f7aae5f)

**Comment by stephanrauh** [comment]
I don't have a clue. You can set `[minifiedJSLibraries]="false"` and debug the source code to find out where the locale path is set. It's probably in the `viewer-*.mjs` file:
```js
  static async #getPaths() {
    try {
      const { href } = document.querySelector(`link[type="application/l10n"]`);
      const paths = await fetchData(href, /* type = */ "json");

      return { baseURL: href.replace(/[^/]*$/, "") || "./", paths };
    } catch {}
    return { baseURL: "./", paths: Object.create(null) };
  }
``´

**Comment by stephanrauh** [comment]
Did you make any progress? I don't want to let you down, but I really don't have a clue how to help you. 

You've mentioned it works in my project, and I assume that means you've cloned my project and it works on your machine, too. So it's almost certainly not a problem of my library. Hence, I'm closing the ticket now.

That's doesn't mean I'll stop supporting you. Feel free to add comments to the tickets, and I'll read and answer them. I still hope we'll figure it out together!

Best regards,
Stephan

**Comment by maertz** [comment]
Hey there, a few years later and someone is still running into the same issue — simply trying to point to a different assets folder using a non-relative path. For anyone else who ends up finding this thread, this might be the solution.

```
        <ngx-extended-pdf-viewer
          [localeFolderPath]="'/assets/ngx-extended-pdf-viewer/locale'"
        ></ngx-extended-pdf-viewer>
```

```
    pdfDefaultOptions.assetsFolder = '/assets/ngx-extended-pdf-viewer';
    pdfDefaultOptions.workerSrc = () => `/assets/ngx-extended-pdf-viewer/pdf.worker-${pdfjsVersion}.min.mjs`;
    pdfDefaultOptions.wasmUrl = () => '/assets/ngx-extended-pdf-viewer/wasm/';
    pdfDefaultOptions.cMapUrl = () => '/assets/ngx-extended-pdf-viewer/cmap/';
    pdfDefaultOptions.standardFontDataUrl = () => '/assets/ngx-extended-pdf-viewer/standard_fonts/';
```
