### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by wisespace-io** [stephanrauh/ngx-extended-pdf-viewer#226]
**Describe the bug**

Not able to enable textLayer in order to display the find button. The same error happens if I try to set [handTool]="false"

**Version info**
"ngx-extended-pdf-viewer": "2.0.0-alpha.15",
"@angular/core": "8.2.14",

**To Reproduce**
In order to display the Find button I need to enable textLayer as informed by the console warning:

> ngx-extended-pdf-viewer.js:929 Hiding the "find" button because the text layer of the PDF file is not rendered. Use [textLayer]="true" to enable the find button.

If I add  [textLayer]="true", I get the error message below:

> ERROR TypeError: Cannot read property 'classList' of null
>     at NgxExtendedPdfViewerComponent.activateTextlayerIfNecessary (ngx-extended-pdf-viewer.js:951)

**Comment by stephanrauh** [comment]
I've created a reproducer for you: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue226

Here's the catch: the reproducer doesn't reproduce the bug. What am I doing wrong?

**Comment by wisespace-io** [comment]
@stephanrauh Your reproducer helped me to figure out the problem.

I am migrating from "ngx-extended-pdf-viewer": "1.8.4", so I used to have the setting below in angular.json:

            "scripts": [
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js",
              "node_modules/ngx-extended-pdf-viewer/assets/viewer.js"
            ]

It works fine with the current version, unless you enable textLayer. So, I removed it and added 

              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }

Thank you.

**Comment by wisespace-io** [comment]
@stephanrauh I display the PDFs in a modal dialog. So, I noticed that when I open the dialog and display the document for the first time it works fine, however when I close the dialog and open again to display the same document or another document I get the classlist error. It only happens when I have  [textLayer]="true".

**Comment by stephanrauh** [comment]
@wisespace-io Feel free to send a PR to my reproducer. The GitHub repository is already there. :)

**Comment by wisespace-io** [comment]
@stephanrauh Yeap, I should have created a PR, but I was working in own repository.

https://github.com/wisespace-io/ngx-extended-pdf-issue226

If you prefer I can create a PR. 

Steps to reproduce:

 1. Click the Open PDF button.
 2. Check the PDF
 3. Click close button
 4. Click open  PDF button again
 5. PDF will not render, check the console.

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug myself a couple of minutes ago. Maybe I've already solved it. I'll double-check with your reproducer in a few minutes.

**Comment by stephanrauh** [comment]
Good news: after adding a second bugfix, ngx-extended-pdf-viewer also works on your reproducer. It seems to be a timing problem.

Please update to ngx-extended-pdf-viewer 2.0.0-alpha.16 to solve the bug.

Before I forget: thanks for the reproducer. It helped me to find the second bug. Keep up the good work!

Best regards,
Stephan

**Comment by wisespace-io** [comment]
@stephanrauh Thank you for your prompt action. It's greatly appreciated.
