### ISSUE TITLE
PDF keeps loading until I scroll

### ISSUE THREAD

**Issue by biswajit-unified** [stephanrauh/ngx-extended-pdf-viewer#227]
**Describe the bug**
I have this viewer on same page with hidden state. PDF viewer is only displayed when a button is clicked. When I want to show the pdf viewer clicking on button I got console error: "offsetParent is not set -- cannot scroll". Then just a small size (10 KB) PDF keeps loading. But if I scroll into the viewer as soon as I show the viewer, it loads very fast.

**Version info**
- Version of ngx-extended-pdf-viewer
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: chrome
 - Version: 80.0.3987.122 (Official Build) (64-bit)

**Demo PDF file**
[sample2.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4291592/sample2.pdf)

**Screenshots**
__1. Loading view__
![Screenshot from 2020-03-05 13-18-26](https://user-images.githubusercontent.com/58461485/75959243-d6a5d200-5ee3-11ea-97df-6309443a26d8.png)

__2. console error__
![Screenshot from 2020-03-05 13-09-15](https://user-images.githubusercontent.com/58461485/75959186-b413b900-5ee3-11ea-9f68-a3052b421489.png)

**Comment by biswajit-unified** [comment]
Thanks for your reply. Please give me a couple of days so that I can reproduce the issue on test server.

**Comment by biswajit-unified** [comment]
Now, I am setting the pdf url when the pdf viewer is visible. The error is gone now.

**Comment by stephanrauh** [comment]
I see. I also had difficulties when initializing a hidden PDF viewer. No idea why that's not possible. Thanks for keeping me in the the loop!

**Comment by alsoicode** [comment]
@biswajit-unified Hello. I have the same issue when using pdf viewer within a Twitter Bootstrap tabbed navigation element.

I tried creating a ViewChild to get the instance and then set the base64Src, which isn't working at all. What's strange is that the tabs, which are iterated over from state data, work the first time, but after I try to show the same PDF again in a new tab element, I get:

ui_utils.js:128 offsetParent is not set -- cannot scroll

until I do something like resize the window, and then the PDF will render.

@stephanrauh any thoughts on what might be causing that?

**Comment by stephanrauh** [comment]
@alsoicode If you send me a reproducer, I'll happily have a look at it. In the meantime, tabbed navigation rings a bell. I had the same problem with the tabs of Angular Material.

Tabbed navigation often means that the PDF viewer is rendered while it's still invisible. That, in turn, means certain JavaScript methods don't return sensible values. pdf.js relies on such a method to implement scrolling. I've spend several hours to fix this nuisance, but it's not that easy.

So the recommended workaround is to add an `ng-if` to the `<ngx-extended-pdf-viewer>` element. By default, the pdf viewer is hidden, and it's shown only after activating the tab. The bottom line being you know for sure it's visible before activating it.

**Comment by alsoicode** [comment]
Thanks @stephanrauh that does give me an idea on how to control the rendering.
