### ISSUE TITLE
Changing PdfScrollMode resets the active page number

### ISSUE THREAD

**Issue by majora2007** [stephanrauh/ngx-extended-pdf-viewer#2275]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? No
- Does the bug also happen on https://pdfviewer.net/simple? Yes
- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`. Not Needed

**Describe the bug**
A clear and concise description of what the bug is. For example:
1. Open a PDF in vertical (or default) page view
2. Navigate to page 6
3. Change to Horizontal page mode

**Expected**
- Re-render in new mode on page 6

**Actual**
- Re-render in new mode and page is reset to 1

**Version info**
- 18.1.14

**Demo PDF file**
This happens on the simple reader, it is a library bug.

**Comment by majora2007** [comment]
I took a preliminary look at the code and see that when changing page mode, you are re-loading the pdf. Likely the page loss is occurring there.

**Comment by stephanrauh** [comment]
Which part of the code triggers the reload? Is it the pdf.js code?

**Comment by majora2007** [comment]
It was `openPDF2()` being called from the setting of the page mode. I was able to workaround it on my code by setting a timeout of 100ms and resetting the page number manually. 

I tried to look at your patched pdf.js, but wasn't able to actually find it (if it's just under assets, that is some hard code to read lol)

**Comment by stephanrauh** [comment]
It gets easier if you set `[minifiedJSLibraries]="false"`.

**Comment by stephanrauh** [comment]
I believe you're using `[(page)]="page"` or `[(pageLabel)]="pageLabel"`. If that's true, version 19.7.1 solves the problem.

I just hope the bug fix doesn't introduce follow-up bug... but I didn't find any bugs during my tests.

Best regards,
Stephan

**Comment by majora2007** [comment]
Awesome, thanks for the quick turnaround. I'll be sure to give it a through shakeout.
