### ISSUE TITLE
Hi , 

### ISSUE THREAD

**Issue by Hakkim-obs** [stephanrauh/ngx-extended-pdf-viewer#229]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple?

**Describe the bug**

**Version info**
- Version of ngx-extended-pdf-viewer
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**

**Additional context**

**Comment by stephanrauh** [comment]
Hi! Nice to meet you!

(Jokes aside: it seems you've accidentally opened a second issue without changing the default template).
