### ISSUE TITLE
We are hosting our project also at Azure and had the situation where the .mjs files didn't load and the following error message was shown in the browsers devConsole:

### ISSUE THREAD

**Issue by venkycoder422** [stephanrauh/ngx-extended-pdf-viewer#2297]
> We are hosting our project also at Azure and had the situation where the .mjs files didn't load and the following error message was shown in the browsers devConsole:
> ![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/32867660/c27e4a0b-9798-4b5b-b135-b3877009bde2)
> 
> We solved the problem by overwriting the _Content-Type_ with the correct "text/javascript".
> You can do this in the Azure Portal -> CDN -> Settings -> Rules Engine
> by adding the following rule:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/32867660/2382cbd8-180c-48f3-87b9-7dcb8b0c786c)

> Maybe this is of help for someone encountering similiar issues
> FYI @papes1ns @JJRimorin @stephanrauh
> 

_Originally posted by @capraibex in https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2196#issuecomment-2005853323_

**Comment by venkycoder422** [comment]
@capraibex is it cost any amount if we allow the above?

**Comment by stephanrauh** [comment]
I'd be very surprised if configuring the server results in additional costs. Nonetheless, I'll try to get rid of the *.mjs files in version 20. At the moment, I can't promise anything - I don't know whether it works.
