### ISSUE TITLE
Pdf show loading icon and blank page until we click on pdf page or scroll or do some actions.

### ISSUE THREAD

**Issue by karnprem90** [stephanrauh/ngx-extended-pdf-viewer#23]

**Comment by stephanrauh** [comment]
The PDF viewer doesn't behave like that on my machine. So I need your help to reproduce your problem.

- Please check out the demo (the root project of this repository). Does the PDF viewer show the same problems? If so, you're probably using another browser or another OS than I do.
- Talking of which: which operating system do you use? Which browser? Which version of Angular?
- Are there any messages on the JavaScript console?
- If you don't manage to find the problem, please send me a reproducer. That's a small but complete application I can simply download and run.

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
@karnprem90 Any news on the topic? Did you manage to solve the bug?

**Comment by stephanrauh** [comment]
Sigh. Reluctantly, I'm closing the bug, simply because I don't have a clue how to reproduce it. 

Send me a reproducer and I'll happily re-open the ticket and work on it.
