### ISSUE TITLE
Hi , Is there any possible ways to navigate browser setting through pop-up window after clicking the Print button.

### ISSUE THREAD

**Issue by Hakkim-obs** [stephanrauh/ngx-extended-pdf-viewer#230]
(text deleted because it was simply the default text)

**Comment by stephanrauh** [comment]
I'm sorry, but that's not possible. As soon as you hit the print button, your operating system takes over.

What you can do is using the new customization feature of ngx-extended-pdf-viewer 2.0.0. It allows you to replace the print button with your custom print button. You can use this to implement an intermediate popup. That, in turn, allows you to implement everything that can be implemented within the browser.
