### ISSUE TITLE
Is it possible to delete a signature form field ?

### ISSUE THREAD

**Issue by farisshomali** [stephanrauh/ngx-extended-pdf-viewer#2300]
I know that unverified signature fields can't be used but is there any possible way to delete them from the form ?

I accessed the signature fields like this:
```ts
    this.ngxService.getFormData().then(form => {
      let signatureFields = form.filter(el => (el as any)['fieldAnnotation'].fieldType === "Sig")
    })
```

**Comment by stephanrauh** [comment]
Unverified signature can be displayed. It's just that I can't verify them, so I insist on adding a red warning above the PDF file.

I'm not sure if I want to support filtering annotations. I'm afraid that undermines trust in PDF files. However, if you insist, you can modify the JavaScript method `PDFPageProxy.getAnnotations()`.
