### ISSUE TITLE
Support signatures tool

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2302]
I'm developing a tool that supports adding a signature list and can draw it like an image. Right now I think it's pretty good! Can you add this to an existing product?

**Comment by Congchuabongbong** [comment]
![Uploading 267604739-76718b9c-8e7e-4ff7-8ed7-796bd78b6fbf.png…]()

**Comment by Congchuabongbong** [comment]
![267605184-c7b592c0-4942-48dc-8d9a-44ceb0a4a6bc](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/46593f90-569c-4ecf-bd14-ef75ebf3a12c)

**Comment by Congchuabongbong** [comment]
![267604739-76718b9c-8e7e-4ff7-8ed7-796bd78b6fbf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/1347c8b5-2bb8-4aeb-a169-61c3b9c02ef2)
![267605150-12121dcd-234f-448c-8c25-c35c588dd845](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/a9c83165-1f56-4d9c-8109-72cb9300ffa1)
![267605184-c7b592c0-4942-48dc-8d9a-44ceb0a4a6bc](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/ae794825-4928-4480-bc5a-b342186ad8da)

**Comment by stephanrauh** [comment]
You're right, your tool looks promising. Nice work! However, I didn't understand your question:
> Can you add this to an existing product?
When you say "product", what are your referring to? Maybe the PDF file?

**Comment by Congchuabongbong** [comment]
I mean you can consider integrating this into your ngx-extended-pdf-viewer

**Comment by Congchuabongbong** [comment]
I will summarize what I have custom added in pdfJs and send it to you! Do you use facebook or skype?

**Comment by stephanrauh** [comment]
Sounds good! No, I don't use Facebook, nor do I use Skype. I prefer email. articles at beyondjava dot de is good channel for stuff like that.

**Comment by Congchuabongbong** [comment]
OKe, I will send you soon! What's your email? I'll send it to you as soon as I'm done

**Comment by stephanrauh** [comment]
As I've mentioned before: articles at beyondjava dot de. Replace the "at" and the "dot" by the corresponding special characters.

**Comment by stephanrauh** [comment]
I'm closing the ticket now because there's nothing I can do at the moment.
