### ISSUE TITLE
PDF Stamp Html Dragged 

### ISSUE THREAD

**Issue by elvispdosreis** [stephanrauh/ngx-extended-pdf-viewer#2313]
I need to create a stamp to mark a signature area, I need to add an HTML element that shows me the x and y position, and the element can be dragged between pages, has anyone already implemented this solution?

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/15267623/07b1df8d-a3ee-4857-8eb6-51154fc94e32)

**Comment by stephanrauh** [comment]
I'm closing the ticket now because there's nothing I can do and because the community didn't chime in in five weeks.

To add an HTML element on top of the PDF file, you can capture the event `(textLayerRendered)` and add the HTML element to the text layer.
