### ISSUE TITLE
Advanced Settings on print previewing

### ISSUE THREAD

**Issue by Boomcu** [stephanrauh/ngx-extended-pdf-viewer#232]
Hi, 
I am using ngx-extended-pdf-viewer in my angular7 project with base64 files. If i print a pdf via chrome it provide me some advanced options like "scale: fit to paper" but if i print the same pdf via my project with using  ngx-extended-pdf-viewer this options dont displaying. How can i use it? 
(First screenshot is what i want secon is what i get)
![asd](https://user-images.githubusercontent.com/35002668/76747285-f6fa4a00-6789-11ea-86ca-f2f42c36b25b.png)
![Adsız](https://user-images.githubusercontent.com/35002668/76747504-493b6b00-678a-11ea-8557-3b2c0a402d66.png)

**Comment by stephanrauh** [comment]
I'm afraid there's little I can do for you.  Google Chrome uses its own PDF viewer. They can access native APIs, so they can modify the print dialog.

ngx-extended-pdf-viewer delegates printing to the browser. All it does is to prepare the PDF files as a collection of images, each of them representing a page. After that, it hides the rest of the page using a media query and calls the standard print dialog of the browser.

The print dialog of the browser is beyond my influence, so I'm afraid I can't help you. 

Best regards,
Stephan
