### ISSUE TITLE
Cancel Rendering is not a function

### ISSUE THREAD

**Issue by achapman009** [stephanrauh/ngx-extended-pdf-viewer#2322]
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). No
- Does the bug also happen on https://pdfviewer.net/simple? Yes

**Describe the bug**
1. Go to (https://pdfviewer.net/extended-pdf-viewer/simple)
2. Click on any option that leaves the pdf-viewer like https://pdfviewer.net/extended-pdf-viewer/intro
3. In the console you will see the error this._cancelRendering is not a function

In my application I am getting this issue when I load the pdf-viewer up in a tab and it stops my pdf from rendering, as well as when I exit.

**Version info**
- 20.0.0

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/20817730/a92ccce6-8ada-4d7e-8417-d4972eb6baa7)

**Comment by stephanrauh** [comment]
Version 20.0.1 fixes the problem. Thanks for pointing this out!
