### ISSUE TITLE
Display position is not aligned when selecting text in Firefox

### ISSUE THREAD

**Issue by myl1992** [stephanrauh/ngx-extended-pdf-viewer#2323]
Hello, I am using the text selection tool in different browsers with ngx-extended-pdf-viewer, the position of the selected text displayed in Firefox is significantly different from the actual location, but it works fine in Google Chrome.

text selection in firefox:
![图片](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/16110864/e697a5c7-1b2a-4bbc-ad8e-dd062afeff6f)

text selection in google chrome:
![图片](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/16110864/c95d92cd-9d6c-404d-9c15-58c3d63749a4)

Version info: v19.7.1
Demo pdf link: https://arxiv.org/pdf/1402.7022.pdf

I'm not sure if this is an issue with pdf.js, please help me take a look. Thank you

**Comment by stephanrauh** [comment]
You can open your file in https://mozilla.github.io/pdf.js/web/viewer.html to find out whether it's a pdf.js problem or my problem.

**Comment by myl1992** [comment]
I opened the pdf.js demo file in Firefox browser and compared it with the presentation of pdf.js
demo file in ngx-extended-pdf-viewer:
![extend](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/16110864/33495315-3caf-436a-92e6-9cb699356432)
demo file in pdf.js:
![pdfjs](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/16110864/613c9169-d3be-471c-94f7-7f3458c446c0)

Version info: v19.7.1
Demo pdf link: https://github.com/mozilla/pdf.js/blob/master/web/compressed.tracemonkey-pldi-09.pdf

**Comment by stephanrauh** [comment]
That might shed some light on the mystery. I've tried to reproduce your issue in the showcase, and it works fine - see the screenshot. Can you open the tracemonkey file on https://pdfviewer.net and confirm that, please?

If the selection is correct on https://pdfviewer.net, but not in your application, than your CSS files are causing the problem. This kind of problems is always a bit hard to hunt down. Compare the CSS rules of the text layer in both projects using the Chrome developer tools. With some patience, you'll find the difference, and you'll be able to fix it.

If so, please tell me, so I know I can safely close the ticket.

<img width="2053" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/d3bc589b-4dcc-46c2-86c0-268c8160ab6e">

**Comment by myl1992** [comment]
You are right, it works fine in https://pdfviewer.net/.  I think it may be due to some css conflicts caused by other introduced components. Next, I need to do some checks. 
Thank you very much~

**Comment by stephanrauh** [comment]
I'm closing the ticket now. I hope you've managed to find the root problem in the meantime!

Best regards,
Stephan
