### ISSUE TITLE
Drawing Annotations on the PDF, like Squares, Rectangle, circles etc.

### ISSUE THREAD

**Issue by balabk57** [stephanrauh/ngx-extended-pdf-viewer#2332]
In the current version of the viewer, we can draw only using the pen tool, right? or we can add, remove the annotations programmatically. 

what I am expecting is like, pre-defined annotation shapes like, lines, square, rectangle, etc..(like in adobe acrobat reader).

**Comment by stephanrauh** [comment]
@Calixteman That's another popular feature. Do you have any plans to add stuff like this to pdf.js?

**Comment by stephanrauh** [comment]
I'm closing the ticket because it's out of my scope.

If you want to implement a simple solution, you can capture the `(annotationLayerRendered)` event and add custom HTML element to the annotation layer.
