### ISSUE TITLE
Annotation  do not show up in the Chrome Pdf Viewer

### ISSUE THREAD

**Issue by tobi08151405** [stephanrauh/ngx-extended-pdf-viewer#2336]
When adding an image annotation to a pdf, downloading the pdf and then opening the pdf in the internal Pdf-Viewer of Chrome, the annotated image does not show up.

This does not occur when viewing the pdf with the firefox pdf-viewer or okular.

It also does not occur when using https://pdfviewer.net/simple or the mozilla pdf viewer.

**Version info**
"ngx-extended-pdf-viewer": "19.6.1"

**Demo PDF file**
[9b1e8a20-7108-4487-9093-871ef050a333.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/15341676/9b1e8a20-7108-4487-9093-871ef050a333.pdf)

**Comment by vectorkovacspeter** [comment]
same issue here

**Comment by stephanrauh** [comment]
I'm afraid I can't reproduce your issue. I took your document and added a PNG, a free text and a free-hand drawing to the PDF. After downloading and opening it in Chrome, it still looked fine. During one attempt, the text was truncated, but that's now what you're reporting, so I'm puzzled. Only Safari looks a bit odd.

<img width="2044" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/2907506e-ae96-4a40-b3d9-0ce245376162">

<img width="2056" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/24d5bad2-fb10-4374-aadb-58d5f51fad7b">

<img width="2056" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/c79679e9-9678-4c1a-989d-b904e2a43062">

<img width="1316" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/dc671722-3666-4a87-a510-c16664c7ea4e">

**Comment by stephanrauh** [comment]
I haven't heard from you for five or six weeks. I'm closing the ticket now.
