### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by JGrancha** [stephanrauh/ngx-extended-pdf-viewer#2348]
A few days ago the new version 18 came out but in version 20.2 and version 20.5.0-alpha.0 an error appears when trying to do an npm install because the version of @angular/common@>=16.0.0 <18.0. 0

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/5517910/711aa923-b9d3-4cdb-abb4-125397784905)

Do you plan to update this dependency so that it can be updated to version 18 of Angular? 

Thank you

**Comment by stephanrauh** [comment]
What? The Angular team waits until I go to vacations, and then they publish a new version? :)

Just kidding - for some reason (possibly traveling Italy) I really missed the new version, and you're right, I ought to fix that ASAP. I ran a quick test. The library seems to be compatible to Angular 18.

In the meantime, you can use `npm install --force`. Of course, that's not a solution I'd recommend for production, but at least for version 20.5.0, I can promise I'll fix the issue soon. I'm not sure about version 20.2.0. If testing version 20.5.0 takes too much time, I'll have to publish a fix for version 20.2.x, but that'd be painful.

**Comment by JGrancha** [comment]
Jajajaja.

Don't worry, just being on version 20.5.0 is enough.

Thanks for the work you do.

**Comment by stephanrauh** [comment]
The bug fix has shipped with version 20.5.0-alpha.1.

Enjoy!
Stephan

**Comment by JGrancha** [comment]
Thanks!!!
