### ISSUE TITLE
I have pdf with annotations. Are there an option to show/hide them?

### ISSUE THREAD

**Issue by NazarKalytiuk** [stephanrauh/ngx-extended-pdf-viewer#2359]
In Google Chrome default viewer there is a button show/hide annotations.
<img width="1542" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/16141974/6790e945-3ebd-49b8-9265-ecd56f1a35e6">
In the library these annotations render, but I didn't find how to hide them or get as JSON etc.

I added an annotation with the macos books app.
[pdfsample annorated.pdf](https://github.com/user-attachments/files/15551835/pdfsample.annorated.pdf)

**Comment by stephanrauh** [comment]
OK. Let me ponder about it. The idea of hiding annotation is new to me, so I'd like to think about it.

As for exporting the annotations: Does `NgxExtendedPdfViewerService.getSerializedAnnotations()` do the trick for you?

**Comment by NazarKalytiuk** [comment]
`Does NgxExtendedPdfViewerService.getSerializedAnnotations() do the trick for you?` - No, it returns only annotations made with the library.
I want this primary to be able to download files with and without annotations. And it is preferable to use native annotations.

**Comment by stephanrauh** [comment]
You can simply hide the annotations with CSS:
```css
.annotationEditorLayer, .annotationLayer {
    display: none;
}
```

Of course, that doesn't remove the annotations from the PDF file, it only hides them from the user.

To remove the annotations entirely, you have to access a low-level API:
```ts
const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;

if (!PDFViewerApplication?.pdfDocument?.annotationStorage) {
   ... // remove everything from the annotationStorage hash table
}
```
Note that probably changing the `annotationStorage` doesn't re-render the page.

**Comment by stephanrauh** [comment]
BTW, if you only want to remove editor annotions, you can use `pdfViewerService.removeEditorAnnotations()`, as shown on https://pdfviewer.net/extended-pdf-viewer/export-annotations.
