### ISSUE TITLE
Page glitch + pageLabel override

### ISSUE THREAD

**Issue by inescaipiro** [stephanrauh/ngx-extended-pdf-viewer#2361]
Using ngx-extended-pdf-viewer in Angular.

When I  click next page or scroll down, for a split second the page being loaded/rendered appears in the bottow right corner, this also happens when I open the file and the pdf is being loaded, the page appears in a corner for a split second before it appears correctly.

Also I would like to know if there is a way to override the embedded pagination in the pdf so that the pageLabel always matches the actual page number.

I have attached an example of a pdf where these issues happen.

I am a beginner so I apreciate any help or tips you can give me!

[EmailAttachmentFile_20240521111613_4 (11).pdf](https://github.com/user-attachments/files/15608725/EmailAttachmentFile_20240521111613_4.11.pdf)

**Comment by stephanrauh** [comment]
I'm afraid I can't reproduce your page glitch. Can you reproduce it in my showcase (https://pdfviewer.net)?

As for the page numbers: I'm afraid the only way is using a custom toolbar. You have to replace the `<pdf-paging-area>` by a custom component. 

https://pdfviewer.net/extended-pdf-viewer/custom-toolbar and https://pdfviewer.net/extended-pdf-viewer/customization document how to customize the toolbar.

**Comment by inescaipiro** [comment]
Thank you for your help!

I was able to solve the paging issue like you said and apparently the glitch disappeared, maybe it was related to the page number.
