### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'PdfSecondaryToolbarComponent' before initialization

### ISSUE THREAD

**Issue by sumitborhade** [stephanrauh/ngx-extended-pdf-viewer#237]
I'm getting below exception. Am I missing anything here?
Thank you.

app.module.ts
--------------
```

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HttpClientModule } from '@angular/common/http';
import {PdfViewerModule} from 'ng2-pdf-viewer';
import {NgxExtendedPdfViewerModule} from 'ngx-extended-pdf-viewer';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    HttpClientModule,
    PdfViewerModule,
    NgxExtendedPdfViewerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
app.component.html
-------------

```
<ngx-extended-pdf-viewer
      [src]="pdfSrc"
      useBrowserLocale="true"
      height="80vh"
    ></ngx-extended-pdf-viewer>
```

Exception on Chrome console
---------------------
ngx-extended-pdf-viewer.js:2215 Uncaught ReferenceError: Cannot access 'PdfSecondaryToolbarComponent' before initialization
    at Module../node_modules/ngx-extended-pdf-viewer/__ivy_ngcc__/fesm2015/ngx-extended-pdf-viewer.js (ngx-extended-pdf-viewer.js:2215)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.component.ts (app.component.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:84)

**Comment by stephanrauh** [comment]
Is there a message like "circular dependency"?

**Comment by stephanrauh** [comment]
@sumitborhade Please update to version 2.1.2 of ngx-extended-pdf-viewer. I couldn't reproduce the bug, but I've got a plausible theory what's causing it, so I'm positive the bug is solved. If I'm wrong, just tell me.

Best regards,
Stephan
