### ISSUE TITLE
Is it possible to add watermark to the signature or the whole PDF?

### ISSUE THREAD

**Issue by Hencefor** [stephanrauh/ngx-extended-pdf-viewer#2370]
I need to show the unverified signature，but the signature cannot be displayed intact. I think watermark or mosaic on the signature can solve this problem, but I am not sure how to do it. Can you help me ?

**Comment by stephanrauh** [comment]
No, I can't. That's beyond my skill set. However, you can ask the Mozilla team at https://github.com/mozilla/pdf.js/issues. The build the base library I'm using. However, don't mention my project. The pdf.js team is responsible for the PDF viewer of Firefox, and usually they reject every ticket that's not related to Firefox.

**Comment by Hencefor** [comment]
I think I should find another way to add watermark, thanks for answering my question!

**Comment by stephanrauh** [comment]
Maybe the problem was something completely different: in version, 15, signatures weren't displayed at all. Version 15.0.0-alpha.3 fixes the bug.
