### ISSUE TITLE
Is it possible to make toolbar sticky and responsive in the pdf viewer

### ISSUE THREAD

**Issue by NaivedyaMishra1** [stephanrauh/ngx-extended-pdf-viewer#2375]
Is it possible to make toolbar sticky and responsive in the pdf viewer. Please let me know if there is any approach or property already there. thanks

**Comment by stephanrauh** [comment]
You can either use the `customFreeFloatingBar` (see https://pdfviewer.net/extended-pdf-viewer/custom-toolbar) and add some CSS to it to make it sticky. Or you can use slightly more CSS to make the default toolbar sticky. At the end of the day, it's only a `<div>`, so you can achieve many things with CSS magic.

As for responsiveness - the default toolbar supports responsive design (see https://pdfviewer.net/extended-pdf-viewer/responsive-design). If you're defining your own custom free floating bar, you can also use the responsive design CSS classes of your CSS framework.

**Comment by stephanrauh** [comment]
I'm closing the ticket now because I believe I've managed to answer your question. If not, don't hesitate to ask.

Best regards,
Stephan
