### ISSUE TITLE
Custom sidebarContainer

### ISSUE THREAD

**Issue by wisespace-io** [stephanrauh/ngx-extended-pdf-viewer#238]
Apparently I can not customize the sidebarContainer, I would like to hide the outline and attachments buttons. Also add a new button. I can do something like below, but it is only drawing over the sidebarContainer:

        <div id="sidebarToggle">
            <div id="sidebarContainer"> 
                <div id="additionalSidebarContainer">
                    <div id="toolbarSidebar"></div>
                </div>
            </div>
        </div>

**Comment by stephanrauh** [comment]
You're right, I shied away from customizing the sidebar. It's partially generated in JavaScript, so it may be a major challenge to make it customizable. It was already on my list, but thanks for opening the topic! Now I know at least two people want to customize the sidebar, so I can adjust my priorities.

**Comment by stephanrauh** [comment]
Related to #236. I hope to solve #236 by making the sidebar customizable.

**Comment by stephanrauh** [comment]
The customizable sidebar has landed with version 4.0.0. Have a look at https://pdfviewer.net/custom-sidebar.

**Comment by wisespace-io** [comment]
@stephanrauh I do not know how I did not notice this change before. Thank you for implementing it.
I see that I can hide the items and change the buttons. However, I can not add my own button and display a different content on **sidebarContent**. Apparently I can just hide the existent options: thumbnail, outline and attachments.

    <div id="sidebarContent">
      <div id="thumbnailView"></div>
      <div id="outlineView"></div>
      <div id="MyContainer"></div>
    </div>

For what I can see, it is not supported, right?

**Comment by wisespace-io** [comment]
@stephanrauh After playing around, I was able to do what I wanted. As I do not need to display the toolbar, I used the "without toolbar" example and was able to overwrite the sidebarContent, result of my test below.

<img width="784" alt="sidebarform" src="https://user-images.githubusercontent.com/18601893/98662564-45c3a800-2348-11eb-9060-987611290835.png">

**Comment by stephanrauh** [comment]
@wisespace-io Nice! Would you like to share a code snippet, so I can add it to the showcase?
