### ISSUE TITLE
Specify An Image when adding an image

### ISSUE THREAD

**Issue by OssNass** [stephanrauh/ngx-extended-pdf-viewer#2384]
The current behavior of adding image is opening requires the browsing for local image

Is there a possibility to maintain the same image adding feature but without the browsing window, I mean I want to be able to add a specific image to the PDF with the ability to change size and location using drag and drop.

The current method of adding a specific image doesn't allow for drag and drop resize, while adding a general image does.
I would like to fusion these 2 methods

**Comment by stephanrauh** [comment]
I think this workaround solves your issue:

- Activate the "image editor" menu by clicking it: `document.querySelector("#primaryEditorStamp").click()`
- after that use the API described in https://pdfviewer.net/extended-pdf-viewer/annotation-layer-api

Best regards,
Stephan

**Comment by OssNass** [comment]
I kind feel dump, as after I posted this I figured it out

**Comment by stephanrauh** [comment]
Welcome to my world :) - but seriously, you have a point. There are attributes for many other buttons, so why's the attribute for the "stamp editor" missing? And shouldn't a "high level API" provide an option to activate dragging? At the moment, I'm drowning in a flood of new tickets, but once the tide recedes, I'll probably add these features.
