### ISSUE TITLE
Radio button form selects multiple values

### ISSUE THREAD

**Issue by NexPlex** [stephanrauh/ngx-extended-pdf-viewer#2386]
"ngx-extended-pdf-viewer": "^17.4.6",
"@angular/cdk": "16.2.12",
"@angular/common": "16.2.12",

The radio button might have five choices: 1, 2, 3, 4, and 5. If Value 4 is set, both 4 and 5 show with an X in the PDFViewer. In other viewers, only value 4 shows as checked. See the sample below. 

If value 2 is set. 2, 3, 4, 5 show a X in PDFViewer

PDFViewer
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/34607168/531d5b01-da25-4fa9-b198-88760e5654a4)

Edge, Acrobat, or Chrome 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/34607168/62595cf7-c202-45dc-aa78-96d0f1dfb1f3)

Sample File
[1-ca-prepare-advance-directive-en.pdf](https://github.com/user-attachments/files/15932375/1-ca-prepare-advance-directive-en.pdf)

**Comment by NexPlex** [comment]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/34607168/69fde6fe-cf8d-4a1e-8586-3178a5a8f4ad)

I'm trying to debug this issue. I saw this image on another post. How do I display the annotations in the console?

**Comment by NexPlex** [comment]
This issue is similar to https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2204. I upgraded to "ngx-extended-pdf-viewer": "^20.2.0". Which solved the issue.

**Comment by stephanrauh** [comment]
That's great news! I was reading your ticket and thought "oh no, not again". :) Bugs with checkboxes or radio buttons usually require a lot of debugging and investigation. So I'm really glad that a simple update solved the matter for you!

Best regards,
Stephan
