### ISSUE TITLE
link in new tab

### ISSUE THREAD

**Issue by alexucgit** [stephanrauh/ngx-extended-pdf-viewer#2388]
"ngx-extended-pdf-viewer": "20.5.0-alpha.4",

```ts
  ngOnInit(): void {
    pdfDefaultOptions.externalLinkTarget = LinkTarget.BLANK;
  }
```

the on link opens in a new tab only the first time I click on it

**Comment by stephanrauh** [comment]
I can sort of confirm this. The feature does work in the showcase (http://localhost:4200/extended-pdf-viewer/links) - but it seems that it's always one click late. There's something strange going on here!

**Comment by stephanrauh** [comment]
Version 21.0.0-beta.1 fixes the bug. Can you confirm this?

**Comment by alexucgit** [comment]
I did some preliminary tests and it seems to have been resolved
