### ISSUE TITLE
Helper Tag Not Removed on Component Destroy in ngx-extended-pdf-viewer v20.2.0

### ISSUE THREAD

**Issue by moorthyptm** [stephanrauh/ngx-extended-pdf-viewer#2389]
I am using ngx-extended-pdf-viewer version 20.2.0. The PDF viewer is attached to a mat dialog. Each time I open the dialog, ngx-extended-pdf-viewer creates a helper tag:

`
<input id="fileInput" hidden="" type="file" accept=".pdf,application/pdf">
`
However, when the component is destroyed, this tag is not removed (not properly cleaned up). This isn't a big issue for 3 to 4 clicks, but in my case, I am using a legacy Bootstrap CSS package that overrides:

```css
hidden input[type=file] {
     display: block; 
}

```

So this issue is clearly visible to me. I request that the temporary code be cleaned up when the component is destroyed.

As a temporary fix, I will override the CSS to hide the helper tag, but we need to ensure that the temporary code is cleaned up when the component is destroyed to prevent memory leaks.

same thing reproduced in the pdfviwer.net [Just switch multiple navigations and check dom]
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/30429951/db68098a-f587-4bd6-a05a-ac2993fd55ce)

Thanks!

Version info

Version of ngx-extended-pdf-viewer: 20.2.0

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 20.5.1.

Enjoy!
Stephan

**Comment by moorthyptm** [comment]
**Thanks** @stephanrauh  for the  quick action
