### ISSUE TITLE
Rotate not working

### ISSUE THREAD

**Issue by fiedler-itlabs** [stephanrauh/ngx-extended-pdf-viewer#2392]
**Describe the bug**
Try to rotate a document

**Version info**
- Version of ngx-extended-pdf-viewer - latest

**Comment by stephanrauh** [comment]
Several other buttons are also affected.

**Comment by stephanrauh** [comment]
Version 20.5.2 fixes the bug. Thanks a lot for pointing this out!

Enjoy
Stephan
