### ISSUE TITLE
filenameForDownload is not working instead the filename is being taken from the document title.

### ISSUE THREAD

**Issue by NaivedyaMishra1** [stephanrauh/ngx-extended-pdf-viewer#2393]
Hi Stephan,
I  am using  ngx-extended-pdf-viewer version 19.5.1". I am trying to set the filename of the downloaded document through the filenameForDownload attribute but the filename is being taken from the document title . Could you please help me on this, thanks. Also thanks for replying to my other issues.

**Comment by stephanrauh** [comment]
This sounds like a bug.

As for version 19.5.1: with very few exceptions, I don't support older versions, so I'm afraid you'll have to update to version 21.0.0 to benefit from my bugfix.

**Comment by stephanrauh** [comment]
Well, I tried to reproduce your issue and failed. Everything works as intended. Maybe there's a typo?

I've added the attribute to the default demo of the showcase, so you can see it in action: https://pdfviewer.net/extended-pdf-viewer/simple
