### ISSUE TITLE
Support for angular 18

### ISSUE THREAD

**Issue by s-torrisi** [stephanrauh/ngx-extended-pdf-viewer#2395]
Hello,
the library seems not compatible at the moment with Angular 18.

Is there something I can do to help update it? I'm new to open source software.

If not, do you have any info on when will it be updated?

**Comment by fiedler-itlabs** [comment]
I'm not the maintainer - but I have integrated ngy-extended-pdf-viewer in our Angular 18 project (18.0.5) without any problems. 
What is your problem?

**Comment by s-torrisi** [comment]
My bad!
I didn't try to delete the package lock file before filing this issue, I did now and it seems to be working.

I'm closing the issue, sorry!

**Comment by stephanrauh** [comment]
I'm glad you've managed to solve the issue! And it's even nicer to open my computer this evening and be greeted with a "problem solved" message... not being compatible with Angular 18 sounded nasty! :)
