### ISSUE TITLE
 Unable to display available digital signatures

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2398]
I have a digitally signed pdf file and I tried displaying it on pdfJs and it still works fine but displaying it on ngx-extended-pdf-viewer doesn't work. so I put the file below:
[1.pdf](https://github.com/user-attachments/files/16010465/1.pdf)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/d3da311f-b1ed-49ea-8ebb-719d2e6cf73b)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/db4cdfcb-16c6-4cb6-b599-9231003e4f96)

**Comment by Congchuabongbong** [comment]
[Uploading f26b4888-7e7f-40e8-b6f6-b41465864d6a.pdf…]()

**Comment by stephanrauh** [comment]
Actually, it is working. Did you activate `[showUnverifiedSignatures]="true"`?
<img width="1845" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/805c7c0a-ab52-4224-9047-dc4d4f7b4cc6">
<img width="1847" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/de9bc878-1f54-4994-ae3a-2716c551791b">

**Comment by Congchuabongbong** [comment]
Hey Stephanrauh,
Is there a way for me to click on the digital signature and display the information?

**Comment by stephanrauh** [comment]
No, I'm afraid not. I'd love to implement such a feature, but I'm not an expert at cryptography. More to the point, I don't know anything about it. I'd happily accept pull requests, but I can't do that myself.
