### ISSUE TITLE
PDF is not opening in MacOS version 13 safari browser 16

### ISSUE THREAD

**Issue by Vasanthi78** [stephanrauh/ngx-extended-pdf-viewer#2402]
I had used the package version of 20.2.0 of ngx-extended-pdf-viewer for displaying the pdf in my project.

The PDF viewer works absolutely fine with windows, iPad and android pad.

I came across an issue of it not loading in **safari browser version 16** alone, in **MacBook(Version 13 Ventura OS)**

It works on Chrome browser thou.

This can be witnessed using https://pdfviewer.net/extended-pdf-viewer/simple as  well.

**Comment by stephanrauh** [comment]
What about version 20.5.2? There was a Safari bug, and I've solved it with version 20.5.0.

**Comment by Vasanthi78** [comment]
@stephanrauh , Upgraded to version 20.5.2, and still facing the same issue. Unable to load the pdf in Safari browser 16 version.

**Comment by stephanrauh** [comment]
Then you'll probably have to downgrade until you find a version that's compatible to Safari 16. But before we give up, let's have a look at the error message. What's going wrong, precisely? And can you solve it by setting the attribute `[forceUsingLegacyES5]="true"?

**Comment by Vasanthi78** [comment]
Surprisingly, I have no errors thrown too.
I will check with the attribute mentioned and try.

**Comment by Vasanthi78** [comment]
@stephanrauh, 

Issue without using `[forceUsingLegacyES5]="true" was that, the (pdfLoaded) event was not finished and at the same time no error on the (pdfLoadingFailed) too.

As suggested I used `[forceUsingLegacyES5]="true" and we it up and running now in safari 16.
But I have observed another issue, when in when toggling between multiple PDF's it is throwing transport destroyed error.

1. Is there a reason why we force using the es5 for safari 16?
2. How do we overcome this ?
3. How do we handle the transport destroyed in the safari browser?

**Comment by stephanrauh** [comment]
The pdf.js team has set the browser requirements a bit aggressively, so now many not-so-old browsers don't work. I've implemented code to detect this, but it doesn't cover Safari 16 yet.

The `transport` error message is basically only a warninig. It means that you're destroying the viewer while it's still rendering. You can use `NgxConsoleFilter` to suppress this warning if it becomes too annoying.

**Comment by stephanrauh** [comment]
The current version 21.0.0-alpha.6 automatically detects Safari 16 and loads the ES5 files.
