### ISSUE TITLE
Unable to Disable Browser PDF Print Dialogue Opening on Ctrl + P Keypress

### ISSUE THREAD

**Issue by jayeshsony** [stephanrauh/ngx-extended-pdf-viewer#2403]
I attempted to apply a solution to disable the default behavior in web browsers where pressing Ctrl + P opens a print dialogue for PDF documents. However, the solution I implemented did not work as expected due to conflicts with internal functionalities of the browser. Despite my efforts, the print dialogue continues to open when Ctrl + P is pressed on a PDF document within the browser. This issue aims to investigate alternative approaches or workarounds to successfully prevent the print dialogue from opening on Ctrl + P keypress for PDF files, considering the challenges posed by the browser's internal functionality.

**Comment by stephanrauh** [comment]
I've investigated the topic a few years ago, and the sad truth is you can't suppress `CTRL` + `P`. Try as I might, the browser would always ignore my attempt to override this key combination.

I've documented this (albeit slightly hidden) on https://pdfviewer.net/extended-pdf-viewer/keyboard.

**Comment by stephanrauh** [comment]
BTW, I don't know why you want to suppress CTRL+P - but overriding `window.print` might be an option.

```js
window.print = () => {
  console.log("Sorry, this application does not allow you to print.");
}
```

**Comment by jayeshsolankiii** [comment]
> BTW, I don't know why you want to suppress CTRL+P - but overriding `window.print` might be an option.

@jayeshsony and I are working together and the reason behind suppressing CTRL+P is to avoid blank pages in the PDF. Whenever we try to print PDF directly from this PDF Viewer then some pages are blank at the start and in between PDFs that's why we need to suppress CTRL+P.

It looks perfect same as when we downloaded the PDF.

**Comment by stephanrauh** [comment]
I see. Actually, blank pages are almost always caused by CSS problems. I suppose you're using a CSS framework that overrides the print rules of pdf.js. Have a look at https://pdfviewer.net/extended-pdf-viewer/troubleshooting - there's a section dedicated to blank pages when printing.
