### ISSUE TITLE
showBorders Property only works after the 2nd time of opening a modal with the pdf-viewer

### ISSUE THREAD

**Issue by dusto2020** [stephanrauh/ngx-extended-pdf-viewer#2407]
In my case I came across a bug I believe. I have a button that opens a fullscreen modal which displays my PDF.

 I have borders set to false but they still show up. 
 Only after closing the modal and opening it the second time, they disapear. 

I cannot explain how it happens, anyone have any ideas?

I am using ionic with angular

**Comment by stephanrauh** [comment]
I've managed to confirm the bug. Thanks for pointing that out!

**Comment by stephanrauh** [comment]
Version 21.0.0-alpha.5 fixes the bug.

Enjoy!
Stephan
