### ISSUE TITLE
20.5.0 and above: Base href is added to absolute assert path when loading js

### ISSUE THREAD

**Issue by hs65** [stephanrauh/ngx-extended-pdf-viewer#2411]
We discoverd a strange behavior after the update from version 20..5.0-alpha-3. The path to load scripts contains now the base href as prefix even if the assets path has been set to an absolute path. It it looks like: http://localhost:4000/app/frontend/http://localhost:4000/static/frontend/assets/viewer-4.3.657.min.mjs

Our code to set the path to the assets has not been touched. The src attributes in the html page are set correctly.

Is comes definately from ngx extended pdf viewer since a rollback brings back the working one.

**Comment by stephanrauh** [comment]
How can I reproduce the bug? I tried with 
```html
<base href="http://localhost:4200/" />
```
but that didn't make any difference.

**Comment by hs65** [comment]
I have no idea. All what I can give you is the screenshot from the browser console: 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/107344166/c3b5bfc0-df96-4a31-aaec-3f8856df3336)

You can see that the browser is trying to load the script from a wrong path. Switch back to 20.5.0-alpha.4 and it is working. Update to 20.5.0 and it is not working.

Here, you can see that the script src is set correct: 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/107344166/9bd0406a-f16f-418d-a4e0-a65bba548c32)

BTW: You removed also the CSP "registration": Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256...

**Comment by stephanrauh** [comment]
As for the CSP directive: the problem is a Safari bug forced me to add JavaScript instead of simply loading the file. How can I make this CSP compatible again? At the moment, I want to focus on the improved loading algorithm but if you know the solution by heart, I'd happily pick it up:
```ts
    const script = document.createElement('script');
    script.async = true;
    script.type = 'module';
    script.className = `ngx-extended-pdf-viewer-script`;
    // this.pdfCspPolicyService.addTrustedJavaScript(script, sourcePath);
    const body = `
      import { webViewerLoad, PDFViewerApplication, PDFViewerApplicationConstants, PDFViewerApplicationOptions } from './${viewerPath}';
      const event = new CustomEvent("ngxViewerFileHasBeenLoaded", {
        detail: {
          PDFViewerApplication,
          PDFViewerApplicationConstants,
          PDFViewerApplicationOptions,
          webViewerLoad
        }
      });
      document.dispatchEvent(event);
      `;
    script.text = body;
    return script;
```

**Comment by hs65** [comment]
The CSP rule is not a problem at the moment. I set the directive in our shell script.

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug. The base href is innocent. The problem is the absolute path in `pdfDefaultOptions`,  and somehow the snippet I show you above is broken. Consider it done!

**Comment by stephanrauh** [comment]
Version 21.0.0-alpha.2 is going to ship your bugfix soon.

Enjoy!
Stephan
