### ISSUE TITLE
Update of FormData in Angular component is not updated in PDF 

### ISSUE THREAD

**Issue by lvornholt** [stephanrauh/ngx-extended-pdf-viewer#2414]
This might not be a Bug - because in the example on you showcase page is working fine.

To describe what I'm doing and what I can not figure out. 
The initial load a PDF file and FormData is working fine. But when I update the formData they are not transported into the form of the PDF file. 

HTML-Template
```html
    <ngx-extended-pdf-viewer
      [src]="getPDFPath(index)"
      [(formData)]="formData"
... >
```
Component-File

```ts
  public get formData(): { [fieldName: string]: string | number | boolean } {
    return this.forms[this.currentIndex];
  }

  public set formData(data: { [fieldName: string]: string | number | boolean }) {
    this.forms[this.currentIndex] = data;
  }
```

When logging the data in setter and getter of FormData - I can see that the set is not necessary because of the two way binding. The data ist already updated. Also when using the event (formDataChange) I see that changes made within in the PDF form are known in the angular component. 

But when changing the FormData based in e.g. a button click from the component I can see when debugging that formData is updated and set is called. I also can see that the Getter is called from the html-Template (from the code within ngx-extended-pdf-viewer - Tag) and the logged formData that are returned from the Getter are changed but the Form in the PDF is not getting any update. 

Also when Changing the [src] (to a different PDF files) and [(formData)]  (based on the new PDF file) nether the update not the initial load of formData is working. The PDF is updated but not FormData are displayed. 

I'm not sure what i can do - the updates from within the PDF are working great but I can not update the Form in the PDF from the outside (only an initial load is working) no updates. 

- Is there any chance to see the working example of "https://pdfviewer.net/extended-pdf-viewer/forms" 
- Is there something else to do beside the twoWay binding (e.g. call an update function)

PS: 
after switching the PDF and formData the object coming from the pdf (formDataChange)  is not the same that was/is set in formData.

Thanks a lot

**Comment by lvornholt** [comment]
sorry - no version numbers in the issue:
"@angular/core": "^17.1.2",

I tried with : 
"ngx-extended-pdf-viewer": "^19.4.1",
and 
"ngx-extended-pdf-viewer": "^20.5.2",

**Comment by stephanrauh** [comment]
To be honest, I don't have the slightest idea when you combine modifying `[src]` with `[(formData)]`. It should work, but I never tried. So I'd like to focus on your other topic first. When `[formData]` changes, the change should be visible in the PDF file.

Come to think of it, maybe you've modified an attribute within your `formData` object. That might not work because Angular doesn't detect the change. Try embracing the immutability pattern - i.e. use a new copy instead of modifying an existing object:

```ts
this.formData = {...this.formData, firstName: "Jane", surname: "Doe"};
```
It's a wild shot, but maybe that's the problem?

**Comment by lvornholt** [comment]
Your wild shot seems to be an Bullseye. That solved my problem - Thank you very much - I also removed the GETTER SETTER functions for formData and just used a variable and updated my data Array my self with the update event and always use the Shallow copy to update formData
