### ISSUE TITLE
Pdf viewer not initialized when used inside an iframe

### ISSUE THREAD

**Issue by iHarishankar** [stephanrauh/ngx-extended-pdf-viewer#2416]
Hi Stephan!!, Since I have a to render multiple pdfs in a single page I  used to iframe to render the ngx pdf viewer . The iframe is displayed inside a modal . I ran into some errors when the viewer was made visible . 

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/114674462/cbdcdf07-f462-4d3c-a35d-01e9ab52ff05)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/114674462/f219d797-32b6-45c8-9db1-b84e63e93ed3)

The package version is : 20.2.0

The pdfviewer initialization works fine if rendered normally(without an iframe). This might not be the bug though .

**Comment by stephanrauh** [comment]
Try adding a timeout to delay showing the PDF viewer. Sometimes the PDF viewer tries to initialize before the modal is visible, and that results in an error.

If this solves your issue, please drop a short note so I know I can close the ticket.

**Comment by iHarishankar** [comment]
Thanks for your reply , will try and let you know Stephan

**Comment by iHarishankar** [comment]
Could you help in configuring the delay for the viewer

**Comment by iHarishankar** [comment]
Thanks man !! It is working!!

**Comment by stephanrauh** [comment]
Hooray! When I wrote my hint yesterday, I thought by myself "you have to add the actual source code", but it was late in the evening and - well, you've managed, although it cost you a couple of hours.

For everyone who's reading this and wonders what the "timeout" hint is about: have a look at https://pdfviewer.net/extended-pdf-viewer/troubleshooting and scroll down to the section "No PDF file shown - error message "offsetParent not set - cannot scroll" in the console". There's a code example.
