### ISSUE TITLE
angular 18 issue

### ISSUE THREAD

**Issue by RichardBoyder** [stephanrauh/ngx-extended-pdf-viewer#2417]
**I need your help!**
a peculiar error I am facing. 

**Describe the bug**
added to standalone component and get this error:
![Screenshot 2024-07-04 at 10 17 34](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/16017411/f759519d-6fd5-436b-8aa8-a1cb52c968c7)

I used the code :
 <ngx-extended-pdf-viewer
    [src]="'https://pdfobject.com/pdf/sample.pdf'"
    [height]="'auto'" 
    [textLayer]="true"
    [showHandToolButton]="true"
    [filenameForDownload]="'Public Domain.pdf'"> 
</ngx-extended-pdf-viewer>

added :
@Component({
  selector: 'app-cvguides',
  standalone: true,
  imports: [NgxExtendedPdfViewerModule],
  templateUrl: './cvguides.component.html',
  styleUrl: './cvguides.component.scss'
})
export class CvguidesComponent {

}

**Version info**
latest version

**Demo PDF file**

https://pdfobject.com/pdf/sample.pdf

**Comment by RichardBoyder** [comment]
never mind resolved.. I installed the example on and it added what needed in angular.json.. sorry about that

**Comment by RichardBoyder** [comment]
closing

**Comment by stephanrauh** [comment]
Don't worry... we've all been there! I'm glad you've manage to solve the issue!

Best regards,
Stephan
