### ISSUE TITLE
getCurrentDocumentAsBlob fails with viewer-4.4.703.mjs

### ISSUE THREAD

**Issue by dcastroviejo** [stephanrauh/ngx-extended-pdf-viewer#2430]
Not sure how to report this, if it is a Mozilla bug, or a compatibility issue between ngx-extended-pdf-viewer and pdf.js
I've installed ngx-extended-pdf-viewer: "^21.0.0-alpha.6", which installs viewer-4.4.703.mjs

Now when I want to export a pdf calling _**NgxExtendedPdfViewerService.getCurrentDocumentAsBlob()**_
I follow the path and the method _**async _exportWithoutAnnotations()**_ from the **viewer-4.4.703.mjs** file is called, and there is a reference: **_this._ensureDownloadComplete();_** where that method is not declared anywhere in the file. Thus I get the error
_**Uncaught (in promise) Error: Error when saving the document: this._ensureDownloadComplete is not a function**_

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/8260973/afd124fd-5853-4f0a-b7f2-89371604c1b6)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/8260973/c854f4ca-a775-4eba-aee9-77c078fa97a7)

**Comment by stephanrauh** [comment]
You're right. The method was removed four weeks ago, and I didn't notice. Thanks for pointing this out!

**Comment by dcastroviejo** [comment]
No problem, glad to help.
In the meantime I installed an earlier version.
Best regards

**Comment by stephanrauh** [comment]
Version 21.0.0-alpha.7 fixes the bug. Thanks for pointing this out!

Enjoy,
Stephan
