### ISSUE TITLE
Support for Chunk Loading of PDF Files

### ISSUE THREAD

**Issue by igino-dedomenico** [stephanrauh/ngx-extended-pdf-viewer#2431]
Hi,

I am using the ngx-extended-pdf-viewer library in my Angular application and I would like to enable the functionality to load PDF files in chunks, page by page, rather than loading the entire file at once. This is important to improve performance and user experience when viewing large PDF files.

What I have tried:

I searched the official documentation and examples, but I couldn't find clear references on how to implement this functionality on the frontend (FE).
I explored the component's configuration options, but I couldn't find anything specific for chunk loading except for 2 options that are already set to false by default.
The documentation provides instructions on how to configure the backend (BE) to support chunk loading, but I couldn't find any instructions on how to configure the frontend (FE) to use this functionality.
Questions:

Can you provide an example or guidance on how to configure this functionality on the frontend (FE)?
Additional Information:

Version of ngx-extended-pdf-viewer in use: 16.2.16
Version of Angular: 14
Below is an example:

```html
<ngx-extended-pdf-viewer
      *ngIf="src !== null"
      [base64Src]="src.split(',').pop()"
      backgroundColor="#ffffff"
      [height]="height"
      [useBrowserLocale]="true"
      [showDownloadButton]="false"
      [showPrintButton]="false"
      [showFindButton]="false"
      [showOpenFileButton]="false"
      [showPresentationModeButton]="false"
      [showRotateButton]="false"
      [showPropertiesButton]="false"
      [showSelectToolButton]="false"
      [showSpreadButton]="false"
      [showScrollingButton]="false"
      [showZoomButtons]="showZoomButtons"
      [handTool]="false"
      pageViewMode="single"
      [showBorders]="true"
      (pageChange)="onChangePage($event)"
      (pagesLoaded)="onPagesLoaded($event)"
      [ignoreKeyboard]="true"
      [replaceBrowserPrint]="true"
      [useBrowserLocale]="true"
      [showHandToolButton]="showHandToolButton"
      [(zoom)]="zoomAttribute"
      (currentZoomFactor)="!showZoomButtons && updateZoomFactor($event)"
      [minZoom]="currentZoomFactor"
      [maxZoom]="currentZoomFactor"
      [showUnverifiedSignatures]="true"
      [showDrawEditor]="false"
      [showTextEditor]="false"
    >
    </ngx-extended-pdf-viewer> `

I also tried replacing [base64Src] with [src], but it didn't change anything.

Thank you in advance!

**Comment by stephanrauh** [comment]
Simply provide a URL in the `[src]` attribute. If the back-end if configured correctly, the library uses either range-request or streaming to load the PDF file as efficiently - and non-blocking - as possible.

If your PDF file has a huge number of pages, activating the single-page mode will improve the performance of the library. You won't notice for file with less than 1000 pages, but it's clearly noticeable with 10.000 pages.

Trying to split the PDF file yourself won't work. I'm not sure if you're doing this - the attribute `[base64Src]="src.split(',').pop()"` makes it look like you're doing fancy stuff.

**Comment by stephanrauh** [comment]
Does this answer your question? I hope so, so I'm closing the ticket now. Feel free to drop a comment if you still got questions.

Best regards,
Stephan

**Comment by igino-dedomenico** [comment]
Hi, @stephanrauh  ty for the answer, i change the code and verify, i tell u if work ty
