### ISSUE TITLE
Error while loading pdf: TypeError: Cannot set properties of undefined (setting '_src') - srcChangedEvent not fired

### ISSUE THREAD

**Issue by hs65** [stephanrauh/ngx-extended-pdf-viewer#2433]
Loading the extended pdf viewer with a default path set in html lead to the following error. The pdf is loaded fine.

TypeError: Cannot set properties of undefined (setting '_src')
    at reportSourceChanges (ngx-extended-pdf-viewer.mjs:4841:18)
    at EventBus.dispatch (viewer-4.4.698.mjs:1369:9)
    
 The event "srcChange" is not fired.

**Comment by stephanrauh** [comment]
Next time, please fill in more details. I was able to reproduce and fix the bug, but that wasn't because of your bug description. Only the stack trace showed me what went wrong.

Be that as it may - version 21.0.0-alpha.7 fixes the bug. Thanks for pointing this out!

Enjoy,
Stephan

**Comment by hs65** [comment]
Thank you very much!

Excuse me for the Shorts description.

Stephan Rauh ***@***.***> schrieb am Fr., 12. Juli 2024,
23:02:

**Comment by stephanrauh** [comment]
You're welcome! I hope I didn't sound too harsh - it was meant to be a polite reminder, but when I read my lines today, it sounds a bit unfriendly. Sorry about that!
