### ISSUE TITLE
Programmatically open all comments in a PDF in order to find text within them

### ISSUE THREAD

**Issue by garydeng01** [stephanrauh/ngx-extended-pdf-viewer#2435]
Hello. This might be more of a question than an issue or feature request right now.

I'm wondering if there is a way to programmatically open all the comments on a PDF when the PDF loads? The reason for wanting to do this is to be able to search within the text of the comments without needing to manually open them first.

Using the browser's "find", I can find text within comments if they are opened; i.e. I first mouse-click on the comment in order to open it. The desire is to be able to search through all of these comments without having to manually open them first.

Thanks

![image](https://github.com/user-attachments/assets/52c9b038-6c1b-4b7f-ba15-e52c8c7d651b)

![image](https://github.com/user-attachments/assets/3fcbe210-61bd-4c81-b8f4-fa72bea1a297)

**Comment by stephanrauh** [comment]
To be honest, I don't know much about comments in PDF files. Can you send me an example file, please?

**Comment by garydeng01** [comment]
Here's a PDF sample that might help. Thanks.

[harmonyone-user-guide-abbrev-comment.pdf](https://github.com/user-attachments/files/16199756/harmonyone-user-guide-abbrev-comment.pdf)

**Comment by stephanrauh** [comment]
You can catch the event `(annotationLayerRendered)` and click every `.popupTriggerArea` to open the popup:

```html
<ngx-extended-pdf-viewer
      [src]="'./assets/pdfs/The Public Domain - Enclosing the Commons of the Mind.pdf'"
      [page]="2"
      [zoom]="'auto'"
      (annotationLayerRendered)="onAnnotationLayerRendered($event)"
>
</ngx-extended-pdf-viewer>
```

```ts
public onAnnotationLayerRendered(event: AnnotationLayerRenderedEvent): void {
    event.source.div.querySelectorAll('.popupTriggerArea').forEach((popupTriggerArea) => {
      console.log("Click on popupTriggerArea");
      (popupTriggerArea as HTMLElement).click();
    });
```

If you're using version 19.2.1 or higher, you'll probably also want to update to version 21.0.0-alpha.9 because earlier versions clip popup that are outside the page. I'm going to publish this version later today.
