### ISSUE TITLE
CSP-Issues since 20.5.2

### ISSUE THREAD

**Issue by dfoxg** [stephanrauh/ngx-extended-pdf-viewer#2440]
**Describe the bug**
We upgraded the pdf-viewer from 20.2.0 to 20.5.2 and are now getting some errors regarding our content security policy. We do not allow unsafe-inline for script-src.

You introduced a change in this [commit](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pdf-script-loader.service.ts#L83) where a script-tag is dynamically generated and added to the DOM. This doesnt work without the csp-setting unsafe-inline for script-src.

Would it be possible to load that script from a static file located at the assets? That would remove that issue.

Thanks! If you need further information, give me a hint :)

**Version info**
- 20.5.2

**Comment by stephanrauh** [comment]
Actually - no. I want to solve your issue. It's already on my list, although I don't find the GitHub ticket right now. But I believe there must be a better way to solve it. Generating the script dynamically solved a nasty bug with Safari, and as a side-effect, it simplified my code.

At the moment, I've got two ideas:
- I hope it's possible to define a CSP policy allowing me to add code generated dynamically. Do you know if that's possible?
- Maybe I can `import` the JavaScript code in a simple Angular component. That'd solve many problems. The only drawback is the budget limit of the compiler is always complaining - but then, the only reason why it's not complaining now is that's I'm cheating. Angular isn't aware of the multi-megabyte files.

**Comment by dfoxg** [comment]
Thanks for your quick response!

When you add content into a script tag (so inside of <script> here <script>), the CSP would disallow that. 

The `import` of the content should work, since it then gets bundled into the angular files. If you want I can test it!

**Comment by stephanrauh** [comment]
Yes, it seems I need your help. Importing the JS code in a component is difficult because I've just moved it into a service to allow reusing it. Adding insult to injury, the Angular compiler wouldn't allow me to import an *.mjs file. After asking my dear friend ChatGPT, I came up with a promising solution. The method

```ts
  private loadCoreLibrary(): Promise<boolean> {
    return new Promise((resolve) => {
      const coreLibraryPath = this.getPdfJsPath('pdf');
      const script = this.createScriptElement(coreLibraryPath);
      script.onload = () => {
        resolve(true);
      };
      script.onerror = () => {
        resolve(false);
        script.onerror = null;
      };

      document.body.appendChild(script);
    });
  }
```

can be replaced by this method:

```ts
  private async loadCoreLibrary(): Promise<void> {
    debugger;
    const coreLibraryPath = this.getPdfJsPath('pdf');
    const module = await import('/' + coreLibraryPath);
  }
```
Take into account this is just a smoke test - so ignore adding the preceding `/`. 

Thing is, the Angular compiler doesn't like it. It reports a long message that exceeds the console window buffer, so I don't know what it want to tell me. The console window contains some JavaScript code, some base64 encoding, some CSS, and something that looks like the *.ftl files. I'm puzzled. What's going on? Does the Angular compiler try to resolve the `await import` statement at compile time? If so, why?

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/d187f858-ad43-4f65-a54f-4ffd0087194a">

**Comment by stephanrauh** [comment]
What about using a nonce or a hash? IMHO that should be possible:

```html
<!-- On the server side, calculate the hash -->
const scriptContent = "console.log('Hello, world!');";
const hash = crypto.createHash('sha256').update(scriptContent).digest('base64');

<!-- Include the hash in the CSP header -->
Content-Security-Policy: script-src 'sha256-${hash}' 'strict-dynamic' 'unsafe-inline' https: http:;

<!-- Inline script that matches the hash -->
<script>
  console.log('Hello, world!');
</script>
```

or

```html
<!-- On the server side, generate a nonce -->
const nonce = crypto.randomBytes(16).toString('base64');

<!-- Include the nonce in the CSP header -->
Content-Security-Policy: script-src 'nonce-${nonce}' 'strict-dynamic' 'unsafe-inline' https: http:;

<!-- Use the nonce in the script tags -->
<script nonce="${nonce}">
  // Your dynamically generated script
</script>
```

**Comment by datev-df** [comment]
Using nonces, at least at our projects, would be complicated, since we deliver the frontend files via nginx, so there is no nodejs environment which could dynamicly generate those.

The hash could work, but if the content is dynamic (it is, at least at the moment due to the `viewerPath` parameter in the `createScriptImportElement` method.), we would need to update the hash everytime.

**Comment by dxxbbf** [comment]
Could you push your changes to a test-branch? I would like to deep dive into the compiler error :)

**Comment by stephanrauh** [comment]
Please run a test on version 21.0.0-alpha.11. I've merged pdf.js and viewer.js into a single file and load them from and URL again. However, I try to detect CSP in order to avoid loading the `op-chaining-support.js` file if that's possible. Now I'm curious. Does this approach work?

**Comment by dxxbbf** [comment]
Thanks for working on it over the weekend!

I´m gonna test it and give you an update.

I got one questions after looking at the commit:
- why do you need to check if an csp is applied in [line 40 of `pdf-script-loader.service.ts`](https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/34dbbe674812b31ab81736089b6ff6622ff33689#diff-0382fbde1fdfdd2142808ccce2885a1b29c9d2aaab4de941ae565d50516dfd19R40)? I think the Promise-way should work even if no csp is applied.

**Comment by stephanrauh** [comment]
Well, I'm trying to detect CSP in order to get rid of one request. If there's no CSP, we can add the browser capability detection as an inline script. Otherwise, we have to load the file containing the detection from the server.

**Comment by dxxbbf** [comment]
With the Version `21.0.0-alpha.11` we dont have a CSP issue anymore - thanks!

But now when we try to print (Controll + P) we get following error:
```
ReferenceError: PDFViewerApplication is not defined
    at printPdf (viewer-4.4.715.min.mjs:46:310711)
    at viewer-4.4.715.min.mjs:46:130054
    at u.invokeTask (polyfills-KTKZVV2N.js:1:7035)
    at _.runTask (polyfills-KTKZVV2N.js:1:2337)
    at E.invokeTask [as invoke] (polyfills-KTKZVV2N.js:1:8107)
    at P (polyfills-KTKZVV2N.js:1:14971)
    at H (polyfills-KTKZVV2N.js:1:15267)
    at x (polyfills-KTKZVV2N.js:1:15560)
```



> Well, I'm trying to detect CSP in order to get rid of one request. If there's no CSP, we can add the browser capability detection as an inline script. Otherwise, we have to load the file containing the detection from the server.

Ok, if you need it regarding performance, i see. But looks weird 😂


This [line](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pdf-script-loader.service.ts#L137) gonna trigger a lot of reporting systems. But i dont have a better idea to check if a csp is applied..

**Comment by stephanrauh** [comment]
Version 21.0.0-alpha.12 solved the printing issue.

Thanks for the hint regarding eval() - I'm going to remove this check in favor of an attribute, so developers can decided whether they prefer to run the inline script or to load it from the server.

**Comment by dxxbbf** [comment]
Sounds great, thank you a lot!

**Comment by stephanrauh** [comment]
Version 21.0.0-beta.1 introduced the attribute `[useInlineScripts]`. I've also added a showcase page: https://pdfviewer.net/extended-pdf-viewer/csp.

Can you send me the settings required for CSP? Last time I tried, this combination worked, but since then many things have changed:
```html
<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types default pdf-viewer dompurify angular angular#unsafe-bypass angular#bundler; default-src 'self'; script-src 'self' *; connect-src *; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src *; object-src 'none'">
```

**Comment by dxxbbf** [comment]
Thank you!

maybe you can go with that one 
```
default-src 'none'; script-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; require-trusted-types-for 'script'; trusted-types default pdf-viewer dompurify angular angular#unsafe-bypass angular#bundler;
```

**Comment by stephanrauh** [comment]
Short update: I'm using this CSP declaration:
```html
<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types default pdf-viewer dompurify angular angular#unsafe-bypass angular#bundler; default-src 'self'; script-src 'self' *; connect-src *; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; frame-src *; object-src 'none'">
```

That's quite a long list of exceptions. If you know how to make it shorter, please tell me. I'd like to use the CSP declaration for the showcase, but I can't because ngx-markdown isn't compatible with CSP (or I'm too stupid to configure it properly :) ).

**Comment by dfoxg** [comment]
Hi @stephanrauh,

thats quite a short CSP compared to mine.. 

Maybe you should remove the stars from the directives (e.g. `script-src 'self' *`).
