### ISSUE TITLE
Evenbus Null When Destroy Component

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2441]
In my program, when I change the language, I will destroy the component and recreate a new component. I have placed ngx-extended-pdf-viewer in my component and when my component is destroyed, ngx-extended-pdf-viewer also destroy. And what's unusual is that I posted the image below. I debugged and realized that the eventbus in PDFViewerApplication was null, so when I created a new component, windown.PDFViewerApplication = null. I am using version 18.1.x!
![image](https://github.com/user-attachments/assets/3360c41b-5404-4c3f-b504-f43884b6717d)
![image](https://github.com/user-attachments/assets/02e13c34-9e57-41d8-899e-05a2a56cd375)

**Comment by stephanrauh** [comment]
When you say you're using version 18.1, are you referring to the version number of ngx-extended-pdf-viewer, or to the Angular version?

Since version 20.5.x, I'm thoroughly changing and optimizing the way the library is loaded. I believe that many users benefit from a major performance boost. That's a major change, so I'm running into your kind of bug all the time.

However, I believe version 21.0.0-alpha.10 works reliably. Can you give it a try, please?

**Comment by Congchuabongbong** [comment]
The version I mentioned above is the version of ngx-extended-pdf-viewer. I cannot upgrade to a higher version because my angular project is using version 11.x.x and I have to build version 18.x.x of ngx-extended-pdf-viewer to be compatible with my angular project.

**Comment by Congchuabongbong** [comment]
I'm wondering why when ngx-extended-pdf-viewer destroy you set evenbus to null. So when recreating the component, it still retrieves the only PDFViewerApplication instance from the window. This leads to the eventBus being set to null. Are you missing something to recreate the eventbus? And finally, if I create multiple ngx-extended-pdf-viewer components, they will only share one PDFViewerApplication, not each ngx-extended-pdf-viewer component will have an independent instance, right? Thank you for reading and grateful you helped me with this problem

**Comment by stephanrauh** [comment]
In version 18, every instance of the viewer uses its own copy of `PDFViewerApplication`. That's the new feature of version 21: it's re-using `PDFViewerApplication`.

You can add a delay between closing and opening a PDF viewer. pdf.js is highly asynchronous, so I suspect `ngDestroy` and `ngOnInit` run at the same time - and that's bound to fail. Can you give it a try and tell me if it works?

```
onst wait = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms));
};

const exampleFunction = async () => {
    // destroy old component
    await wait(100);
   // open new component (or make it visible with *ngIf="true" after waiting)
};
```

**Comment by Congchuabongbong** [comment]
I tried this way but eventBus still has a null value. I have debugged but still don't see any part to reset the value for eventBus or reset the PDFViewerApplication state after you have cleaned it up in ngDestroy?

**Comment by stephanrauh** [comment]
I faintly remember that the instance of `PDFViewerApplication` without the `eventBus` is the new instance. There's a timing problem, and `ngDestroy` tries to remove the new instance. However, I wonder why the problem hits you. As far as I remember - I'm 90% sure - the i18n demo of the showcase never ran into this particular problem. It uses a simple timeout of zero milliseconds to destroy and re-create the viewer:

```ts
 public set language(language: string) {
    ...

    this.hidePdfViewer = true;
    setTimeout(() => {
      this.hidePdfViewer = false;
    });
  }
```

**Comment by stephanrauh** [comment]
Please try version 21.0.0-beta.1. I believe it solves the issue.
