### ISSUE TITLE
Access underlying PDFJS lib

### ISSUE THREAD

**Issue by moussa-b** [stephanrauh/ngx-extended-pdf-viewer#2443]
**Is your feature request related to a problem? Please describe.**
I want to access the underlying PDFJS library in order to be able to use it and check if a file is password protected or not

**Describe the solution you'd like**
I would like a way to access the underlying PDFJS library

**Describe alternatives you've considered**
No alternative for the moment

**Comment by stephanrauh** [comment]
That's not a big deal:
- Prior to version 21: use `window.PdfViewerApplication`
- Starting with version 21: use the `PDFNotificationService` to get the instance of the viewer:
```ts
constructor(
    public notificationService: PDFNotificationService,
  ) {
    effect(() => {
      this.PDFViewerApplication = notificationService.onPDFJSInitSignal();
      if (this.PDFViewerApplication) {
          // put your algorithm here
      }
    });
  }

**Comment by moussa-b** [comment]
Hi @stephanrauh thanx a lot for this update, I am using version 18.1.14 of ngx-extended-pdf-viewer. I tried using window.PdfViewerApplication but I didn't manage to solve my issue : 
1. The library is lazyloaded, which is blocking me because I want to put the function that check if a file is secured with a password in a service in order to reuse it everywhere I need it in my webapp
2. I am not sure how do I use `window.PdfViewerApplication` to access the underlying PDFJS lib in order to test if a file is secured with a password

**Comment by stephanrauh** [comment]
Are you referring to a file that hasn't been loaded yet? That might be difficult, because my library is a PDF viewer. Nothing more and nothing less. You can probably check if the file is protected by a password after loading it, but that also means that the user is already seeing the password dialog. I take it you want to avoid that?
