### ISSUE TITLE
Cannot print any document.

### ISSUE THREAD

**Issue by grondiG** [stephanrauh/ngx-extended-pdf-viewer#2452]
Using library when I try download any document locally or on preview site of the library i cannot do it. 
![obraz](https://github.com/user-attachments/assets/c02b0b7b-c015-48c4-a054-76036a34b110)
I'm still getting this error and cannot do anything with it. Using latest version. 
<img width="449" alt="Zrzut ekranu 2024-07-22 o 12 13 26" src="https://github.com/user-attachments/assets/9add5e4c-c400-4c1f-a4af-77c468fd9c5b">

**Comment by stephanrauh** [comment]
Version 21.0.0-alpha.12 fixes this bug. Thanks for pointing this out!
