### ISSUE TITLE
Print Preview of ngx-pdf-viewer is not displaying properly for pdf files contained landscaped and portrait mode pages in files. 

### ISSUE THREAD

**Issue by umedSut** [stephanrauh/ngx-extended-pdf-viewer#2455]
Hello There!

We've been having an issue with the PDF Viewer displaying and print feature using the print functionality of ngx-pdf-viewer

Version info
"ngx-extended-pdf-viewer": "^19.5.1",

**Desktop **
Browser: Chrome Version 126.0.6478.128 (Official Build) (64-bit)
Edge: Version 126.0.2592.113 (Official build) (64-bit)

**Step To Reproduce : ** 
my original pdf will have pages mixed of landscaped and portrait mode. and when i am using ngx-pdf-viewer print feature from tooltip i can see that landscaped page size is applied to all the pages in print preview and portrait pages are rotated to the landscaped view along with all contents. 

original pdf contain landscaped  page size = 11 * 8.5 inches
original pdf contain portrait page size = 8.5 * 11 inches

During print preview all the pdf pages is having size of 11 * 8.5 inches and all portrait pages is converted to landscaped pages. 

Note: ngx-pdf download feature is downloading proper files with all proper pages and sizes. (above issue is only for print)

same behavior applied to  chrome, edge and firefox browser.

**Comment by stephanrauh** [comment]
Does this demo equal your scenario? It's printing both portrait and landscape pages correctly:
https://pdfviewer.net/extended-pdf-viewer/mobile

**Comment by umedSut** [comment]
Hi @stephanrauh 

yes i have similar pdf structure mixed of landscape and portrait mode (similar to above demo url pdf) 

https://pdfviewer.net/extended-pdf-viewer/mobile
In this demo also i can able to see the pdf loaded properly on the ngx-pdf-viewer. but for the print feature on print preview i can see that second portrait mode page is converted to landscape and the content is also rotated on print preview feature. and in preview all the pages are using the same page size. 

Current issue is for print feature on print preview because our files behavior is changing during print. 

**PFA for reference:**
<img width="952" alt="PdfViewerIssue" src="https://github.com/user-attachments/assets/e4655bca-a8c8-437c-a6cb-344d9755c49a">

I have tried adding the  [mobileFriendlyZoom] property but print preview window still having the same issue. 

**Note:**
 we have to print the files on the original format.

**Comment by stephanrauh** [comment]
I see. You want the opposite of what everybody else wants. :) Most people are happy with the auto-rotation because otherwise there's plenty of white space, which seems to be wasting paper.

The `mobileFriendlyZoom` attribute has nothing to do with printing - it's just that the document happened to be in the demo that shows how to use the PDF viewer in an industrial environment where workers are wearing gloves.

**Comment by stephanrauh** [comment]
You're looking for `enablePrintAutoRotate`:

```ts
  constructor() {
    pdfDefaultOptions.enablePrintAutoRotate = false;
  }
```

I've documented (or hidden the documentation?) it here: https://pdfviewer.net/extended-pdf-viewer/options

**Comment by stephanrauh** [comment]
Version 21.0.0-beta.1 adds the attribute `[enablePrintAutoRotate]`. Plus, there's a live-demo on https://pdfviewer.net/extended-pdf-viewer/print-range (fourth tab).

**Comment by umedSut** [comment]
Thanks @stephanrauh   for help. yes by using [enablePrintAutoRotate]=false we can control the rotation of page. 

if we are going with [enablePrintAutoRotate]=false
Is There is any way we can avoid the extra space on portrait pages?. i know the extra spacing is added because we have landscape page present on files.

**Comment by stephanrauh** [comment]
There's extra space on portrait pages? When I "print" the demo file of my showcase to a PDF file, I don't see any extra space. Is it different when printing on real paper? This is what it looks like when I tried to reproduce your issue:
[PdfShowcase.pdf](https://github.com/user-attachments/files/16433111/PdfShowcase.pdf)

**Comment by stephanrauh** [comment]
When disabling auto rotation, the printed file looks like so:
[Portrait.pdf](https://github.com/user-attachments/files/16433163/Portrait.pdf)
You're right, there's a lot of white space, but I'm afraid that's what happens when you try to avoid rotation. The page uses the maximum available space.

Maybe your printer has advanced options, but the PDF viewer can't access them. All it can do is rendering the pages as images and print them.
