### ISSUE TITLE
Error: <path> attribute d: Unexpected end of attribute.

### ISSUE THREAD

**Issue by Avejack** [stephanrauh/ngx-extended-pdf-viewer#246]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
404 Not Found...

- Does the bug also happen on https://pdfviewer.net/simple?
Yes!

**Describe the bug**
I am not aware if that breaks anything or not but it is an Error showing up in the developer console so i think it should get fixed.

**Version info**
- Version of ngx-extended-pdf-viewer
^3.0.0-beta.1

- Version of Angular
^9.0.0

- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)
Do i need to include them manually other than adding this to the angular.json:
```json
{
      "glob": "**/*",
      "input": "node_modules/ngx-extended-pdf-viewer/assets/",
      "output": "/assets/"
}
```
because i didn't... So i guess: default files?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

**To Reproduce**
Since this "bug" is happening in the demo page i guess i don't need to provide a separate project.

1. Go to your Demo page: https://pdfviewer.net/simple
2. Open the developer Console
3. See 4 times the same error "Error: <path> attribute d: Unexpected end of attribute. Expected number..."

Again: I am not sure if this error even breaks anything but i just wanted to point this error out to you. Great library!

**Comment by stephanrauh** [comment]
Thanks for pointing this out. I've fixed this bug in version 3.0.0-beta.2. Would you mind to run a quick check an tell me if it works on your machine, too?

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
> because i didn't... So i guess: default files?

Yeah, you're right. That's a left-over from an earlier version when I published both versions in parallel. I'll remove the confusion section. THX!

**Comment by nikolaits** [comment]
Hi @stephanrauh,
The issue is no longer reproducible on my side with version `3.0.0-beta.2`.
Thanks

**Comment by stephanrauh** [comment]
Great. Thanks!

Best regards,
Stephan
