### ISSUE TITLE
Arrow keys should only trigger pagination if the focus is in the PDF viewer

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#2463]
Reported by @jessiepotts in #126:

I'm having an issue when navigating left and right on the tabs of a material tab group.  Using the arrow keys to move back and forth across the tabs are paging up and down within the PDF viewer despite the viewer not having focus.  

The issue is reproducible in the "Angular PDF viewer showcase" available here: [https://pdfviewer.net/extended-pdf-viewer/simple](https://pdfviewer.net/extended-pdf-viewer/simple).  The top left of the page includes a mat-tab-group, selecting one of the tabs with the sample PDF loaded and then moving left and right on the tabs using the keyboard arrow keys demonstrates how the pages are changing in the PDF viewer.

Keyboard navigation is important for accessibility, so let's try to find a keyboard binding that doesn't interfere with it.

_Originally posted by @jessiepotts in https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/126#issuecomment-2251772836_

**Comment by jessiepotts** [comment]
@stephanrauh, thanks for taking this on.  Sorry I did not say so earlier. I headed out of town shortly after reporting what I was experiencing and only recently returned.

BTW - I think the ngx-extended-pdf-viewer component is excellent.  Thank you for your time on it.

**Comment by stephanrauh** [comment]
I believe (or hope?) I've found a decent solution. It has landed with version 21.3.2. If you find any problem, don't hesitate to tell me.

Enjoy!
Stephan
