### ISSUE TITLE
showTextEditor showDrawEditor how to revert changes before save?

### ISSUE THREAD

**Issue by wider2** [stephanrauh/ngx-extended-pdf-viewer#2469]
Extended pdf viewer is a nice tool
but i have a question about "editor" buttons
How can i revert changes, when user input some text or draw lines?
may be some kind of history logs exist ?

**Comment by stephanrauh** [comment]
It's not exactly a history, but I guess you're looking for `this.pdfViewerService.getSerializedAnnotations()`. New annotations are added at the end of the list.

For removing annotations have a look at https://pdfviewer.net/extended-pdf-viewer/export-annotations.
