### ISSUE TITLE
Promise.allSettled is not a function at MessageHandler._deleteStreamController (pdf.js:7225)     at MessageHandler._processStreamMessage (pdf.js:7164)

### ISSUE THREAD

**Issue by japhari** [stephanrauh/ngx-extended-pdf-viewer#247]
pdf.js:7225 Uncaught (in promise) TypeError: Promise.allSettled is not a function
    at MessageHandler._deleteStreamController (pdf.js:7225)
    at MessageHandler._processStreamMessage (pdf.js:7164)

Am getting that error after rendering file. any clue ?

**Comment by stephanrauh** [comment]
Just update zone.js.

For some reason, Angular locks zone.js to an old version. Update it to the latest version, and you've get stuff like `Promise.allSettled`. I didn't encounter any disadvantage after updating to the latest version in my Angular 7 application.

Isn't that a strange bug?
