### ISSUE TITLE
IE11 compatibility is broken

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#248]
@lucho78 reports in #239 that version 3.0.0-beta.2 doesn't work with Internet Explorer 11.

**Comment by stephanrauh** [comment]
@lucho78 Version 3.0.0-beta.3 restores IE11 compatiblity. I still see two errors:

- the scale select box look ugly (at least in German language). I start to believe I'd rather replace the original implementation I've borrowed from pdf.js by my own select box.
- The button "first page", "last page", and "rotate" are disabled. But this doesn't seem to have to do with IE 11. Strange thing is that doesn't happen in my default test project.

**Comment by stephanrauh** [comment]
@lucho78 Do you have an idea why the showcase is broken on IE11? I'm not sure that's important, but it's a bit embarrassing.

**Comment by lucho78** [comment]
Hi Stephan,
I've checked on IE11 and it works for me. So the behavior is the same as Chrome for example. But I still have the issue https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/249
