### ISSUE TITLE
Turn off the auto jump-to-page when a phrase is found

### ISSUE THREAD

**Issue by rmdorsey** [stephanrauh/ngx-extended-pdf-viewer#2482]
I'm using the find by regex feature to search for multiple phrases.  It works well, but it forces the PDF viewer to jump to the different pages where it's finding the phrase.

I'd like for there to be an option to turn off the action that jumps to the page where the phrase is found.

Thank you!

**Comment by stephanrauh** [comment]
In other words, you're less interesting in finding stuff but in highlighting it. At least that's what I remember from previous discussions, and it makes sense to me.

Maybe it's a good idea to support both features simultaneously:

- The user (or the programmer) can use the find bar / the find API the way it always worked
- and programmers can highlight text with a regular expression, and that doesn't interfere with the "find" functionality.

**Comment by rmdorsey** [comment]
I'll create a separate feature request for the other search feature I brought up in another thread.  For this one it might be helpful to show you the issue I'm experiencing with in a short video: 

https://github.com/user-attachments/assets/1f2472cd-ce1f-47f6-9b5b-ce54d6dc1fb2

**Comment by stephanrauh** [comment]
Your feature is going to land in version 21.2.0.

**Comment by rmdorsey** [comment]
> Your feature is going to land in version 21.2.0.

Awesome!  Any ETA on when that release might be?

**Comment by stephanrauh** [comment]
Version 21.2.0 has landed.

I've added the attribute `dontScrollIntoView` to `NgxExtendedPdfViewerService.find()`:

```ts
    const numberOfResultsPromises = this.ngxExtendedPdfViewerService.find(this._searchtext2, {
      highlightAll: this.highlightAll2,
      matchCase: this.matchCase2,
      wholeWords: this.wholeWord2,
      matchDiacritics: this.matchDiacritics2,
      dontScrollIntoView: this.dontScrollIntoView2,
      useSecondaryFindcontroller: true
    });
```

**Comment by rmdorsey** [comment]
Excellent.  Thank you!  This should work with regex too, correct?  I'm not seeing that parameter in your example code above...

**Comment by stephanrauh** [comment]
Thanks for reminding me. The embarrassing truth is, I simply forgot, and to make sure I don't keep forgetting it, I've opened #2509.
