### ISSUE TITLE
The button class changes all buttons default padding, top and bottom in the project

### ISSUE THREAD

**Issue by diegopaciottiGB** [stephanrauh/ngx-extended-pdf-viewer#2485]
After installing the new release into my project, found all button standard sizes changed, found out to be a class called button from the pdf viewer that sets padding, top and bottom of every button without any distinction to 0px.

**Comment by stephanrauh** [comment]
Yes, you're right. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
Version 21.1.1 has landed and fixes the problem.

Enjoy!
Stephan
