### ISSUE TITLE
Templates for secondary toolbar don't work

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#249]
@lucho78 reports in #239 that version 3.0.0-beta.2 that the secondary toolbar can't be opened if there's a custom primary toolbar.

```html
<ng-template #additionalButtons>
            <div id="toolbarViewer">
                <div id="toolbarViewerLeft">
                    <pdf-toggle-sidebar></pdf-toggle-sidebar>
                    <div class="toolbarButtonSpacer"></div>
                    <pdf-paging-area></pdf-paging-area>
                </div>
                <div id="toolbarViewerRight">
                    <button type="button" *ngIf="isOnChrome" class="toolbarButton fas fa-print" (click)="onPrintClick()"></button>
                    <div class="verticalToolbarSeparator hiddenSmallView"></div>
                    <pdf-toggle-secondary-toolbar></pdf-toggle-secondary-toolbar>
                </div>
                <pdf-zoom-toolbar></pdf-zoom-toolbar>
            </div>
        </ng-template>
```
![image](https://user-images.githubusercontent.com/14161954/78015501-c568ad80-7349-11ea-9468-c777df6112e9.png)
In this case nothing is opened.

**Comment by stephanrauh** [comment]
@lucho78 I've tried to write a reproducer. I've inserted your source code, but it works fine. I can open the secondary toolbar without problems. I guess there's a difference between our approaches. Mind to have a look?

https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue249

Best regards,
Stephan

**Comment by stephanrauh** [comment]
@lucho78 Any news on this topic?

**Comment by lucho78** [comment]
Oh sorry Stephan it was an issue from my side. You can close this ticket. Thanks for your support

**Comment by stephanrauh** [comment]
OK!
