### ISSUE TITLE
Leaking styles break app-layout

### ISSUE THREAD

**Issue by schreibse** [stephanrauh/ngx-extended-pdf-viewer#2490]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html?no
- Does the bug also happen on https://pdfviewer.net/simple? no
- Can you write a reproducer based on a freshly created project? yes, see stackblitz link at bottom

**Describe the bug**
A clear and concise description of what the bug is. For example:
1. Go to stackblitz demo and open preview in new tab
2. Inside the pdf preview component, interact with zoom buttons or select one of the available presets
4. Layout breaks (most of the time) 

Since the layout only breaks while interacting with the ngx-extended-pdf-viewer I guess there are leaking styles and/or javascript changes elements it should not? Please note that the stackblitz example is very basic and it looks worse for the real application, but I can't share that, therefore I included screenshots
First image shows the correct app layout (toolbars, spacing as it should be)
Second image shows broken layout after interacting with the zoom settings of ngx-extended-pdf-viewer , the toolbars are gone and on the left side suddenly there is an empty space

Third image shows the broken layout of the stackblitz demo, half the screen is black

**Version info**
ngx-extended-pdf-viewer 21.1.1
FireFox 129.0 (64-bit)
Chrome 127.0.6533.100 (Official Build) (64-Bit)

[stackblitz](https://stackblitz.com/github/schreibse/extended-pdf-preview-layout)
![01](https://github.com/user-attachments/assets/27c8e5f4-4ed1-4767-87e7-a36106fc0d31)
![02](https://github.com/user-attachments/assets/5ef89788-2b6d-4370-a898-22d96d1e370a)

![03](https://github.com/user-attachments/assets/2ff10b3d-69d1-460e-aa33-cc6cfaf418c0)

**Comment by stephanrauh** [comment]
That's unexpected. At the moment, I don't have an idea what might go wrong. You're right, it looks like leaking CSS rules, but that doesn't match my theory of what happens when zooming. 

Maybe - but that's a wide shot - CSS zooming has something to do with it. That's an optimization that rendered a quick but blurry preview of the zoomed page by applying a CSS rule, and replacing it by the properly rendered image a few milliseconds later.

**Comment by schreibse** [comment]
As long as the issue can be reproduced creating the stackblitz was worth it, if I can help with the fix I will do my best

**Comment by stephanrauh** [comment]
It seems the black bar is a hidden canvas element that's not as hidden as it should be:
<img width="846" alt="image" src="https://github.com/user-attachments/assets/ad4f8669-6202-4086-b9a1-f381f6348b57">

**Comment by stephanrauh** [comment]
Your bug fix is going to land with version 21.3.6 soon.

**Comment by schreibse** [comment]
just updated to 21.3.6 and now works like a charm (see [stackblitz](https://stackblitz.com/github/schreibse/extended-pdf-preview-layout)) , thank you

**Comment by mapelpapel** [comment]
Unfortunately, the bug still seems to be there in some cases. 
I was using the viewer in an older version and used the same workaround as shown in #2543 to hide the element. 
After updating to 21.4.0 the canvas-element is still displayed as such, that it introduces a scrollbar in my app where there should not be one. Hiding it completely still solves the issue.
![image](https://github.com/user-attachments/assets/4b828f85-2264-4e6e-87ab-11ea00c8fcec)

**Comment by stephanrauh** [comment]
I've added the workaround to version 21.4.1. Let's hope the bug is gone for good now!
