### ISSUE TITLE
PDF not load

### ISSUE THREAD

**Issue by keval0706** [stephanrauh/ngx-extended-pdf-viewer#2491]
I need your help

I am facing below error

**Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.   pdf-4.1.887-es5.mjs:1**

I am using
> Chrome V127.0.6533.100
> Angular V16.2
> Zone.Js V0.13.3
> ngx-extended-pdf-viewer V20.0.0-alpha.2 (also tried 20.0.0-alpha.3)

Recently, I have upgraded my Angular App from v12.2 to v16.2, this is happening after version upgraded, before I was using 10.0.0-alpha.1.

![Uploading 357038123-15885397-315b-42f4-ae48-994001621e95.png…]()

**Comment by stephanrauh** [comment]
We had similar issues several times in the past:

- first of all, please check if the requested file is in your dist folder when running `ng b`. The error message might mean that the file isn't there.
- If so, please check that your server supports `*.mjs` files. Many servers don't recognize this file type.

**Comment by keval0706** [comment]
I am loading file using base 64 string, not using any file link.
How to check that server is supporting *.mjs files or not?

**Comment by itzhackB** [comment]
> This issue has been fixed.
> 
> My server was not allowing `*.mjs` file, I have added it to config file which has resolved this issue.
> 
> Thanks for support

Hi
I am experiencing the same problem, can you explain how you solved it?

**Comment by stephanrauh** [comment]
Look here: https://pdfviewer.net/extended-pdf-viewer/troubleshooting
