### ISSUE TITLE
Docu Site Attributes don´t show: No data found

### ISSUE THREAD

**Issue by Julian-B90** [stephanrauh/ngx-extended-pdf-viewer#2493]
https://pdfviewer.net/extended-pdf-viewer/attributes

![image](https://github.com/user-attachments/assets/10be470d-df03-4508-9ef9-440cbb4c8e18)

**Comment by stephanrauh** [comment]
Oops. What's happened?

**Comment by stephanrauh** [comment]
Oh. A line feed happened.

**Comment by stephanrauh** [comment]
I've published the bugfix.
