### ISSUE TITLE
bind page number

### ISSUE THREAD

**Issue by HongshanLi** [stephanrauh/ngx-extended-pdf-viewer#25]
Is it possible to bind the displayed page to a property in the component, where ngx-extended-pdf-viewer is used? For example, after I displayed a pdf in ngx-extended-pdf-viewer and scrolled down to page 5, how 
should I inform my typescript code that I am currently on page 5?

**Comment by stephanrauh** [comment]
I'm not sure whether it's possible, but it sounds like a good idea. I'll have a look at it.

**Comment by stephanrauh** [comment]
I've implemented two-way binding for `[(page)]` and published it with version 0.9.18.

Thanks for the inspiration! And sorry for delivering it late - you've caught me while moving to another town, so bear with me!

Best regards,
Stephan
