### ISSUE TITLE
no preview after hide and show with ngIf

### ISSUE THREAD

**Issue by lijishbhavan** [stephanrauh/ngx-extended-pdf-viewer#250]
i am trying to hide and show a pdf with 
<div *ngIf="showReport" >
    <ngx-extended-pdf-viewer [base64Src]="base64String" backgroundColor="#ffffff [height]="'90vh'" [useBrowserLocale]="true" [handTool]="false" [showHandToolButton]="false" >
    </ngx-extended-pdf-viewer>
  </div>

but the thing is once hide , and show back the pdf file preview is not getting getting refreshed..
again need to reload the page to get the preview.
please help

**Comment by stephanrauh** [comment]
Please send me a reproducer (a small but complete application that shows the error and doesn't require me to install any third-party stuff). The default application at https://github.com/stephanrauh/ngx-extended-pdf-viewer has a "hide/show" toggle button, and it works. So probably you've configured something different.

**Comment by stephanrauh** [comment]
Let's close the ticket. I've waited a month for an answer. As I've said above, `*ngIf` works fine in my demo applications.
