### ISSUE TITLE
Do not reload pdf.worker every time

### ISSUE THREAD

**Issue by legraina** [stephanrauh/ngx-extended-pdf-viewer#2504]
**Is your feature request related to a problem? Please describe.**
The pdf worker is reloaded every time I change of pdf. It's 1.4Mb that is downloaded each time. It's an issue as I'm rendering many small pdf files and I'd like to be able to load them in advance and being able to view them without an internet connection.

**Describe the solution you'd like**
I'd like to be able to cache the worker once, or at least for the complete life of the component integrating the viewer.

**Describe alternatives you've considered**
I'm trying to build the worker myself and pass it to the viewer.

**Additional context**
<img width="738" alt="image" src="https://github.com/user-attachments/assets/3cfe0bba-e31b-4d8a-9511-74654add0c72">

**Comment by legraina** [comment]
I've dug a little more into the issue, and it seems that a worker could be passed to the open() function in the viewer. However, this method is not called directly, and we cannot add the field 'worker' to the input. It would need some modification of the code to do so. For example, the worker could be initialized in the run function (when the component is initialized, and then passed to the sub functions). I think it seems to be a minor modification and should improve the efficiency of the code when loading multiple pdfs.

**Comment by Julian-B90** [comment]
Thank you for your issue :-) maybe you have time to make a fork and create a pull request for this?

**Comment by stephanrauh** [comment]
Julian, it seems Antoine accepted your challenge. Thanks a lot to both of you!

**Comment by stephanrauh** [comment]
The feature is going to land with version 21.3.0. 

Enjoy!
Stephan
