### ISSUE TITLE
Find + Highlight all missing `selected` class

### ISSUE THREAD

**Issue by Hypercubed** [stephanrauh/ngx-extended-pdf-viewer#2507]
**Steps to Reproduce**
In the show case, open the find bar.
Enter a common word found multiple times in the page.
Turn on "Highlight All"
Hit next a couple times.

**Expected Results**
The exact found version should appear in green, while other highlights appear in blue.
<img width="642" alt="image" src="https://github.com/user-attachments/assets/9a9bffb6-8bf9-4aaa-af26-108c8dfea587">

**Actual Results**
All highlights appear blue, no indication of the found text.  Found item is missing the `selected` class.
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/19b2820a-8709-4f3c-ad51-cd818868c8e5">

**Version info**
- ngx-extended-pdf-viewer v21.2.1 (>v21.1.2)

**Comment by stephanrauh** [comment]
So I guess it's good I didn't publish the new version yet... or is 21.2.0 also affected?

**Comment by Hypercubed** [comment]
Seen locally on @latest, verified on showcase with 21.2.1.  I didn't go back and check the local version... but looks like it was 21.2.0.  So yes... 21.2.0 and 21.2.1.

**Comment by Hypercubed** [comment]
I don't see the issue on https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by Hypercubed** [comment]
I did a quick look of changes in 21.2.1 but haven't seen anything obvious.

**Comment by stephanrauh** [comment]
OK, then let's fix the bug soon. Thanks a lot for checking the versions!

**Comment by stephanrauh** [comment]
OK, got it. Since 21.2.0, there are to independent find controllers, and I've forgotten to take into account that both have there own selected find result. As a consequence, the selected item is highlighted, and it's un-highlighted a millisecond later.

**Comment by stephanrauh** [comment]
I've fixed the bug and published the changes on the showcase. I'm going to publish the new version later this week-end.

**Comment by stephanrauh** [comment]
The bug fix has landed with version 21.3.0.
