### ISSUE TITLE
Alignment of icons

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#251]
Hi Stephan,
On the version 3.0.0 some buttons are not well aligned
![image](https://user-images.githubusercontent.com/14161954/78242117-bfa5d000-74e1-11ea-8e38-33cc56bf1696.png)
It's the case for the zoom selection (small arrows on the right) and the icons to rotate (too munch on bottom).
Could you please fix it.
Thanks
Luc

**Comment by stephanrauh** [comment]
Will do! Thanks for making me aware of it!

As for the small double: it drives me nuts. Currently, I wonder if I should postpone releasing the final version 3.0.0 until this is fixed. I don't believe I can fix it with the current design. But I'm already moving to Material Design (or Mozilla's Photon design, which is surprisingly similar), so I'd like to redesign the zoom drop-down menu, anyways. I hope I'll be able to find a solution that works on every browser including IE11, with every language, and even with `mobileFriendlyZoom` out-of-the-box.

**Comment by stephanrauh** [comment]
BTW, if anyone want to submit a pull request solving the issue, you're welcome!

**Comment by stephanrauh** [comment]
A slight improvement has landed with version 3.0.0-beta.5. But I'm still unhappy with the current state of responsive design, so there's still work to do. Sometimes the right-hand buttons are pushed down when the screen size is roughly 800-900 pixels wide.

**Comment by lucho78** [comment]
Thanks Stephan,
Please change from 4px to 8px for the arrows on the zoom selection

![image](https://user-images.githubusercontent.com/14161954/78571808-f30c9580-7826-11ea-81df-012ca45c4bf3.png)

Thanks
Luc

**Comment by stephanrauh** [comment]
OK! Consider it done.
