### ISSUE TITLE
Writing with pen, scrolling with hand

### ISSUE THREAD

**Issue by legraina** [stephanrauh/ngx-extended-pdf-viewer#2512]
**Is your feature request related to a problem? Please describe.**
I would be nice to be able to do one action with the pen (writing if the pen started the event) and still be able to scroll with the hand.

**Describe the solution you'd like**
I have been able to deactivate the writing for the hand, but the scrolling remains deactivated.

**Describe alternatives you've considered**
I've tried to remove the div focus to prevent scroll or to not deactivate the hand tool, but none are working.

**Additional context**
Could you point me where the scroll is disabled, so I can find a way around it. I'll push a pull request once done.

Thanks !

**Comment by stephanrauh** [comment]
Phew. I remember I've actively deactivated scrolling, but at the moment, I don't find it. However, I remember it wasn't possible to draw because the page started scrolling. Is there a work-around for pens?

**Comment by stephanrauh** [comment]
Have a look at the CSS class `ngx-extended-pdf-viewer-prevent-touch-move`. I've added it because the page started scrolling when trying to draw. Maybe that's what you're looking for?

**Comment by legraina** [comment]
Thanks, I've looked at it, but it's not enough. However, the touch-action css field is the right one.
I've just pushed a branch where I'm replacing this field by using preventDefault on TouchMove instead. I'm also keeping track of the pointer type used when click on the pencil icon and only using this pointer to draw. It means that you can write with the pencil and scroll with your hand.

**Comment by stephanrauh** [comment]
@legraina I've migrated your changes to the source files. Unfortunately, in the bleeding edge branch, the `ink.js` file has been modified a lot, so I'm not sure I've managed to put your changes into the correct places. Can you check this, please?

I've also noticed a bug. I don't have a pen, so I draw with my fingers. And that doesn't work after activating the ink editor. Only when I tap the screen a second time, I can draw. How can we solve this?

**Comment by legraina** [comment]
> I've also noticed a bug. I don't have a pen, so I draw with my fingers. And that doesn't work after activating the ink editor. Only when I tap the screen a second time, I can draw. How can we solve this?

There was a bug for the first use as the listener is only added on the first click. I've moved the listener in its own class, and I'm now initializing it on loading. It has fixed the bug on my side.

**Comment by legraina** [comment]
> Unfortunately, in the bleeding edge branch, the `ink.js` file has been modified a lot, so I'm not sure I've managed to put your changes into the correct places. Can you check this, please?

It seems ok. I've moved some pointer related members and functions to the class PointerType:
class PointerType:
    static current: null;
    constructor();
    destroy(): void;
    windowPointerDown(event: any): boolean;

I've removed the argument for:
    resetPointerType(): void;

**Comment by stephanrauh** [comment]
I assume #2530 is obsolete, and I can focus on #2531?

At first glance, your changes look fine by me. The only reason I won't add them to https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/src/display/editor/ink.js and https://github.com/stephanrauh/pdf.js/blob/4.5/src/display/editor/ink.js is a nasty headache. I hope it's gone tomorrow, so I my brain works properly again! 

BTW, instead of working with the huge combined files, you can also clone https://github.com/stephanrauh/pdf.js. That's my fork of Mozilla's viewer. You can run it with `npm install && gulp server`. IMHO this approach is much more convenient if you're working on the base library.

**Comment by legraina** [comment]
Indeed, #2531 is the right one.

I didn't know for pdf.js, but it will indeed be way easier to work with :)

**Comment by stephanrauh** [comment]
Now it works even without pen. Merci beaucoup!

Your improvement has landed with version 21.3.6.

Best regards
Stephan
