### ISSUE TITLE
In e2e test with chromium:headless the PDF is not rendered

### ISSUE THREAD

**Issue by Julian-B90** [stephanrauh/ngx-extended-pdf-viewer#2513]
We use testcafe for our e2e test. 

**Version info**
- Version of ngx-extended-pdf-viewer 21.1.2

***Screenshot from e2e test**
![image](https://github.com/user-attachments/assets/b60314d6-9801-4d67-a98a-74e3d4abbe86)

**Comment by stephanrauh** [comment]
Could it be related to #2510?

**Comment by Julian-B90** [comment]
Maybe i will test it.

**Comment by Julian-B90** [comment]
We have found the issue It was nginx:

We add this:
```nginx
types {
    # additional mime types
    application/javascript mjs;
}
```

**Comment by stephanrauh** [comment]
nginx? Ah, you've mentioned Testcafe. I was looking in the wrong corners. :)
