### ISSUE TITLE
Compare two PDF side by side 

### ISSUE THREAD

**Issue by santoshprakash** [stephanrauh/ngx-extended-pdf-viewer#252]
Can we use this component to compare two pdf side by side? I have tried to use pdfjs/pdf viewser for the same but not able to do that. can anyone help me

**Comment by stephanrauh** [comment]
No, you can't. That's the one of the design decision of ngx-extended-pdf-viewer that's stupid in retrospect, but it's almost impossible to change now.

So I reluctantly send you to ng2-pdfjs-viewer. That's another fine library doing more or less the same as my library. It's less ambitious, so there are less options, but it has one key advantage: the pdf viewer runs in an iFrame. That isolates it from the rest of the world. That, in turn, allows you to display two PDF files side-by-side.

When it comes to comparing, you may want even more feature, such as synchronized scrolling. I'm afraid that's out of the scope of every PDF viewer I know.

**Comment by stephanrauh** [comment]
But maybe there's hope. What happens if you wrap the PDF viewer in a webcomponent? That should isolate the namespace of the PDF viewer from the namespace of the Angular application (and every other PDF viewer on the same page).

I'm going to try that this weekend.

**Comment by stephanrauh** [comment]
BTW, I'm pretty sure you can't wrap the PDF viewer in a web component yourself, so you don't have to wait for me. If you do, please tell me about the result!

**Comment by stephanrauh** [comment]
I'm tracking the topic in #254, so I won't re-open this ticket. I'm working on it nonetheless.
