### ISSUE TITLE
PageRenderedEvent.pagesCount -> PageRenderedEvent.pageNumber

### ISSUE THREAD

**Issue by dapriett** [stephanrauh/ngx-extended-pdf-viewer#253]
`pagesCount` should be `pageNumber` in PageRenderedEvent

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/c2aac9e8932ff433ceafe3c1e3dcccb71b1525f8/projects/ngx-extended-pdf-viewer/src/lib/events/page-rendered-event.ts#L3

Thanks!

**Comment by stephanrauh** [comment]
Right your are! I've fixed this. The bugfix is probably going to land in version 3.0.0-beta.5.

**Comment by stephanrauh** [comment]
The improvement has landed with version 3.0.0-beta.5.
