### ISSUE TITLE
Helper Tag Not Removed on Component Destroy in ngx-extended-pdf-viewer v21.3.2

### ISSUE THREAD

**Issue by EnosoRobinBecker** [stephanrauh/ngx-extended-pdf-viewer#2532]
Hello,
the bug I am reporting has alreday been fixed in version 20.5.1 (see https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2389), but it seems to be back .
When I navigate to a page, that uses the pdf-viewer, then leave the page and the component is destroyed, the input is still standing in the html DOM. 
`<input id="fileInput" hidden="" type="file" accept=".pdf,application/pdf">`
I am able to reproduce this issue on your demo system.

![input bug](https://github.com/user-attachments/assets/82193adc-0e70-4c48-941f-f3221a7b15db)

My thanks in advance

Version info: 21.3.2
Also tested on the latest version: 21.3.5

**Comment by stephanrauh** [comment]
Your bug fix is going to land with version 21.3.6 soon.

**Comment by EnosoRobinBecker** [comment]
Hey stephanrauh, thank you very much for your quick fix!
