### ISSUE TITLE
Cant print range of 1-1

### ISSUE THREAD

**Issue by priveraussi** [stephanrauh/ngx-extended-pdf-viewer#2534]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). No
- Does the bug also happen on https://pdfviewer.net/simple? Yes

**Describe the bug**
1. Go to https://pdfviewer.net/extended-pdf-viewer/print-range
3. Try to print range 1 to 1
4. Nothing happens when you click print

**Version info**
- 21.3.5

**Comment by stephanrauh** [comment]
How come nobody noticed before? Thank you very much for pointing this out!

**Comment by stephanrauh** [comment]
Your bug fix is going to land with version 21.3.7 soon.

Enjoy!
Stephan
