### ISSUE TITLE
Pdf form field is reset when entering and exiting the field

### ISSUE THREAD

**Issue by AlexBarthelemy** [stephanrauh/ngx-extended-pdf-viewer#2538]
Hello,

I have a bug in my app when I'm using this library.

I can reproduce the case in the showcase : 

1. Go to https://pdfviewer.net/extended-pdf-viewer/forms
2. In the form field (of the form, not the pdf) 'Lucia', enter something ("Lucia Perez" for example) => in the pdf, the field has been updated (OK)
3. In the PDF, If I go in and out of the field "Lucia Perez", the value (in the field of the pdf) is reset to "Lucia" (KO)

**Comment by stephanrauh** [comment]
Good new for you, bad news for me: I can confirm this bug. That's nasty. It's always hard to hunt down form bugs!

**Comment by AlexBarthelemy** [comment]
Hello Stephan,

Do you have an estimated correction date?

Thanks

**Comment by stephanrauh** [comment]
No, I'm afraid not. At the moment, I'm ill, which slows down bug fixing considerably.

**Comment by birya** [comment]
Hello Stephan,

I experience the same issue. I have couple of fields in PDF that I need to populate using type script after values are inserted in other fields. Component only emits 'formDataChange' event when PDF fields are populated using keyboard.

It seems like issue connected with not updating "fieldAnnotation.value" property when "formData" is changed programatically.

Hope you can find the solution.

Thank you!

**Comment by stephanrauh** [comment]
I've found and fixed the bug. The bugfix is going to land soon with version 22.0.0-alpha.3.

The root problem was a "formatted value" that still had the old value, so it was restored on blur. Now two-way binding sets the formatted value to null, which solves the problem.

Enjoy!
Stephan

**Comment by AlexBarthelemy** [comment]
Hello Stephan,

Thanks you very much for you reactivity !

Alexandre
