### ISSUE TITLE
Multiple instances in same page

### ISSUE THREAD

**Issue by pchand89** [stephanrauh/ngx-extended-pdf-viewer#254]
When I am trying to add multiple viewer in same page its updating the first one always, other does not display anything though i have provided different src for both.Please help with this asap. Attaching screen shot below. Note: src is generated dynamically at runtime.
![image](https://user-images.githubusercontent.com/25003400/78331390-90579780-75a3-11ea-8509-e979c578dcf8.png)

**Comment by stephanrauh** [comment]
That's the one of the design decision of ngx-extended-pdf-viewer that's stupid in retrospect, but it's almost impossible to change now.

So I reluctantly send you to ng2-pdfjs-viewer. That's another fine library doing more or less the same as my library. It's less ambitious, so there are less options, but it has one key advantage: the pdf viewer runs in an iFrame. That isolates it from the rest of the world. That, in turn, allows you to display two PDF files side-by-side.

When it comes to comparing, you may want even more feature, such as synchronized scrolling. I'm afraid that's out of the scope of every PDF viewer I know.

**Comment by stephanrauh** [comment]
But maybe there's hope. What happens if you wrap the PDF viewer in a webcomponent? That should isolate the namespace of the PDF viewer from the namespace of the Angular application (and every other PDF viewer on the same page).

I'm going to try that this weekend.

Also see #252.

**Comment by stephanrauh** [comment]
BTW, I'm pretty sure you can't wrap the PDF viewer in a web component yourself, so you don't have to wait for me. If you do, please tell me about the result!

**Comment by stephanrauh** [comment]
@pchand89 Just a little sign-of-life: I didn't find the time to examine web components yet, but it's still top on my list. Stay tuned!

**Comment by stephanrauh** [comment]
After thinking about the topic for a while, I suspect it's too difficult to implement this feature soon. So I'm closing the ticket for the moment.
