### ISSUE TITLE
Regarding Multiple Instances of pdf viewer

### ISSUE THREAD

**Issue by shresth7001** [stephanrauh/ngx-extended-pdf-viewer#2541]
Please let me know if we have any way to create multiple instances of pdf viewer in a single page web application.

**Comment by rohan-gosavi** [comment]
You can create multiple iframes and host multiple instances in it. But be careful if you load large number of pdfs it will degrade the performance of app.

**Comment by stephanrauh** [comment]
Please have a look at https://pdfviewer.net/extended-pdf-viewer/side-by-side for a live demo.

In the long run, I'd like to enable using multiple instances without the iFrame workaround. Version 21 is a huge step towards this goal, but I suspect it's still a long way to go. The good news is now it looks like a sensible goal. Before version 21 I considered it impossible. :)

**Comment by stephanrauh** [comment]
Not really. But I suspect they've already managed. It's just me who's lagging behind. :)
