### ISSUE TITLE
Black box under page content when changing the zoom

### ISSUE THREAD

**Issue by EnosoRobinBecker** [stephanrauh/ngx-extended-pdf-viewer#2543]
Hello,
I found a small bug. When I have a pdf file that only has one page and I change the zoom of the file, there is popping up a black box at the bottom of the page. I was able to reproduce this behaviour on your demo system. Steps to reproduce:

- Select a demo
- Upload a pdf file that only has 1 page
- Change the zoom, so that the size of the shown document changes
- Scroll down to the bottom of the page

I could fix this temporary via css as shown below, so this issue is not really urgent I guess.
```
.hiddenCanvasElement {
	display: none;
}

```
![image](https://github.com/user-attachments/assets/520730d9-75ca-4419-ada6-0b296f6daae6)

Version: 21.3.5

**Comment by stephanrauh** [comment]
That's the same bug as #2490. Updating to version 21.3.7 should solve the issue.

BTW, I also thought about using your CSS solution, but I didn't dare because I wasn't sure the code breaks if the canvas is invisible. Is your text layer rendered correctly?

**Comment by EnosoRobinBecker** [comment]
Hi, thank you for your response.
To your question: Yes, so far I can see it, my text is rendered correctly when using the CSS.
