### ISSUE TITLE
Option to display title in main Toolbar

### ISSUE THREAD

**Issue by mapelpapel** [stephanrauh/ngx-extended-pdf-viewer#2552]
I am currently using a completely custom right part on the main Toolbar:
![image](https://github.com/user-attachments/assets/6d8f242c-526a-44bb-8a46-807d8d31a987)
Now I want to change this to the proper way with `pdf-shy-button` elements. Therefore, it would be great to have the option to display the title in the main toolbar like in the image.

My idea would be to add the attribute `titleCssClass`. It uses the same classes as `cssClass`. 
The default should be `always-in-secondary-menu` to not have a breaking change. 
This is better than just a boolean (which would be better than nothing), because it would allow hiding the title before the button gets moved to the secondary Toolbar when the viewer gets smaller.

`cssClass` should also override `titleCssClass` if it is less visible. For example: `titleCssClass='always-visible'` should not override `cssClass='always-in-secondary-menu'` and show the title when the icon is in the secondary toolbar. The same applies to the responsive classes in between.

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by stephanrauh** [comment]
Your requirement makes sense, but it seems to be to restrictive. It solves your issue, but a short time later, another developer is going to a have similar - but slightly different - requirement. How can we provide a more general solution?

**Comment by mapelpapel** [comment]
I don't know if you have something specific in mind which leads to your opinion that my idea is too restrictive. If so, please let me know :). I tried to come up with some more ideas so it would be more general:
- No override of the `titleCssClass`. Let the developer decide if he wants to show a title without an icon in the main toolbar
- A second new attribute `shortTitle` similar to `title` (there probably is a more suitable name, I can't come up with right now, but it's most likely shorter because of limited space). If set, this title is displayed in the main toolbar when the button is displayed based on the `titleCssClass`. If not set, `title` should be displayed

In general, I tried to adapt my idea to use already existent functionality and concepts (mainly the cssClass here)

**Comment by mapelpapel** [comment]
@stephanrauh Ping in case you missed my answer :)

**Comment by stephanrauh** [comment]
At the moment, I'm short of leisure time, so there's no progress yet.

Maybe it's possible to use nested components:

```html
<pdf-shy-button ... >
  <input [(ngModel)]="fontSize">
  <button>Set Font Size</button>
</pdf-shy-button>
```

Your original idea also makes sense to me, I just wonder if there's someone out there needing more flexibility.

**Comment by mapelpapel** [comment]
I tried your suggestion but could not get it working. 
I would suggest leaving this issue open for a while until you can fit it in. Maybe someone else comes up with another spin to it in the meantime.

**Comment by stephanrauh** [comment]
Oh, sorry for the misunderstanding. When I said "maybe it's possible" I meant "maybe I can make it possible". I know that it doesn't work like that right now, and I'm sorry I caused extra work for you!

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by stephanrauh** [comment]
I've started to implement the nested components, so I'll close this ticket now. You can track the progress in #2684.
