### ISSUE TITLE
Print Layout Option Missing

### ISSUE THREAD

**Issue by achapman009** [stephanrauh/ngx-extended-pdf-viewer#2555]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). Yes, but i am having trouble finding an issue for it. Requesting information if you are aware of any.
- Does the bug also happen on https://pdfviewer.net/simple? Yes
- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.

**Describe the bug**
1. Try to print any document
2. Layout option is missing (portrait or landscape), I see this happening in PDF.js demo as well. It shows up for a second then gets hidden. Are you aware of a way to override this behavior so we have a choice when printing? I have tried using setting enablePrintAutoRotate to false.

**Version info**
- Version of ngx-extended-pdf-viewer: 21.3.8"

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Comment by stephanrauh** [comment]
I wouldn't call this a bug. Browsers are able to hide the option if they detect there's only a single sensible option. I suspect that's what happening. The CSS rules of the `#printContainer` seem to ensure that. I suspect that the margin setting and/or the width setting are responsible for hiding the option.

**Comment by stephanrauh** [comment]
I'm closing the ticket because it doesn't feel like a bug. Quite the contrary, I'd call it a feature: the PDF viewer rotates the pages automatically to use the maximum available space, so the portrait/landscape option isn't needed.

**Comment by achapman009** [comment]
Thanks for the response @stephanrauh.

If anyone comes across this and needs the print orientation option to show up, I added the following to a global stylesheet:

// This forces the print preview to have orientation option
@page {
  size: auto !important;
}
