### ISSUE TITLE
No 'annotationEditorEvent' when adding a text with 'HighlightEditor'

### ISSUE THREAD

**Issue by afnan-davia** [stephanrauh/ngx-extended-pdf-viewer#2556]
**Bug description**
In Angular, when I add highlight annotations on text (or even without it being on text), no event is fired. However, if I delete (with the context menu button or with DEL button) the annotation, a 'removed' event is fired without no issue.

**Reproduction**
1. Use an editor with "annotationEditorEvent". For example:
```html
<ngx-extended-pdf-viewer [src]="'https://pdfobject.com/pdf/sample.pdf'"  [textLayer]="true (annotationEditorEvent)="onAnnotationEditorEvent($event)">
```
In the Angular component:
```javascript
onAnnotationEditorEvent(event: any): void {
       console.log('Event annotationEditorEvent: ', event);
}
```
2. Add a highlight on any text: no event is fired

**Version info**
- Version 21.4.0, tested on Chrome 127.0 on a MacOS 14.6.1

**Demo PDF file**
[sample.pdf](https://pdfobject.com/pdf/sample.pdf)

**Comment by stephanrauh** [comment]
Version 20.4.1 is going to add the event.

Enjoy!
Stephan
