### ISSUE TITLE
secondaryToolbarComponent issue if it's not displayed

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#256]
In the latest version I get the following exception:
core.js:4061 ERROR TypeError: Cannot read property 'checkVisibility' of undefined
    at NgxExtendedPdfViewerComponent.push.../../node_modules/ngx-extended-pdf-viewer/__ivy_ngcc__/fesm5/ngx-extended-pdf-viewer.js.NgxExtendedPdfViewerComponent.onResize (ngx-extended-pdf-viewer.js:2333)
    at NgxExtendedPdfViewerComponent.push.../../node_modules/ngx-extended-pdf-viewer/__ivy_ngcc__/fesm5/ngx-extended-pdf-viewer.js.NgxExtendedPdfViewerComponent.ngOnInit (ngx-extended-pdf-viewer.js:1295)

![image](https://user-images.githubusercontent.com/14161954/78569236-99ef3280-7823-11ea-9c6b-f4bf788f55d8.png)

The problem here is that the secondaryToolbarComponent is hidden (no extra menu). Could you please fix this issue.
Thanks
Luc

**Comment by stephanrauh** [comment]
I can't see how hiding the secondary toolbar causes the bug. I've added a guard nonetheless. Maybe the check is called to early, or I've missed something.

**Comment by stephanrauh** [comment]
I've published the feature in version 3.0.0-beta.8.

BTW, I believe the version is mature enough to call it a release. @lucho78 Do you agree? If so, I'd like to publish the final version tomorrow (Wednesday).

A tout a l'heur
Stephan

**Comment by lucho78** [comment]
Hi Stephan
Maybe the last point that you should fix before creating a release is the following warning occurred during the build:
Warning: Entry point 'ngx-extended-pdf-viewer' contains deep imports into 'C:/01.Projects/08.Mosaic/01.GIT/mosaic/angular-frontend/node_modules/rxjs/internal/Subject'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

Thanks a  lot for your great support.
Cheers
Luc

**Comment by stephanrauh** [comment]
Oops. You're right, there was one deep import. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
The bugfix has landed. I've also added a onDestroy() method that removes the dynamic CSS when the PDF viewer is closed. I know there are several open issues, but I still hope that makes for a great Easter edition! :)

Best regards (and happy Easter!)
Stephan
