### ISSUE TITLE
 Promise.withResolvers is not a function. (In 'Promise.withResolvers()', 'Promise.withResolvers' is undefined)  URL: capacitor://localhost/assets/pdf.worker-4.6.687.min.mjs

### ISSUE THREAD

**Issue by dodomui** [stephanrauh/ngx-extended-pdf-viewer#2565]
Unable to run ngx-extended-pdf-viewer on iOS device using Ionic + Capacitor.
Receive below error when trying to open the PDF file using blob and base64.

**Describe the bug**
TypeError: Promise.withResolvers is not a function. (In 'Promise.withResolvers()', 'Promise.withResolvers' is undefined)
⚡️  URL: capacitor://localhost/assets/pdf.worker-4.6.687.min.mjs
⚡️  pdf.worker-4.6.687.min.mjs:21:1354152

**Version info**
- Version of ngx-extended-pdf-viewer 21.4.0

**Comment by stephanrauh** [comment]
Please update zone.js to the latest version.
