### ISSUE TITLE
GET viewer-4.6.688.min.mjs NS_ERROR_CORRUPTED_CONTENT

### ISSUE THREAD

**Issue by addielmoldes** [stephanrauh/ngx-extended-pdf-viewer#2577]
I have this error when trying to display a pdf file
![Screenshot from 2024-09-22 03-17-30](https://github.com/user-attachments/assets/2bd44319-5e84-4dbe-b9b4-e2636ccf65e9)

I'm running Angular v18.2.4, ngx-extended-pdf-viewer v21.4.1, my browser is Mozilla Firefox 130, also I'm using angular-architects' native federation for micro-frontends architecture, my OS Manjaro Linux and NodeJs v20.13.10

**Comment by stephanrauh** [comment]
You have to configure your server such that it supports *.mjs files. This file type has been around for years, but for some reason unknown, many servers still don't recognise these files as JavaScript. Have a look at https://pdfviewer.net/extended-pdf-viewer/troubleshooting - I've explained the problem and the solution for a few popular servers.

**Comment by roopeshkurian** [comment]
I am also facing almost similar issue. I am using Angular 18.2.x. When I checked the node_modules folder I could not see viewer-4.6.688.min.mjs

![image](https://github.com/user-attachments/assets/8051f086-d114-4698-b3d0-eac73fcd0e75)

But I can see viewer-4.6.688.mjs 
Can you please check ?
I really appreciate your help

**Comment by addielmoldes** [comment]
The way I solved this was by adding these lines in angular.json file

![image](https://github.com/user-attachments/assets/ce916a60-b929-408e-9037-e7d4dc2a9e0c)

**Comment by roopeshkurian** [comment]
I already have this in my angular.json file. ngx-extended-pdf-viewer version 21.4.1 is working great. But when I am trying to install new version(21.4.3) its giving me this error. When I checked node modules assets folder , I could not find viewer-4.6.688.**min**.mjs

**Comment by KillerCodeMonkey** [comment]
yes, i can confirm the file is missing in latest release.

the viewer tries to load min.mjs, but only a .mjs file is there

**Comment by vwiencek** [comment]
I have the same issue
when I upgraded ngx-extended-pdf-viewer 20.5.2 to 21.4.3 I got the same problem
file `viewer-4.6.688.min.mjs` is missing

**Comment by stephanrauh** [comment]
Holy moly. Yes, you're right, as a side effect of publishing a new 18.x version, I accidentally included the wrong version of the pdf.js files.

Sorry about that, and sorry for responding late - I'm ill, so my responses are a bit sluggish.

Best regards and thanks a lot for pointing that out
Stephan

**Comment by chandramuralis** [comment]
How is this issue resolved? is there any specific version I should use?

**Comment by KillerCodeMonkey** [comment]
I am using [21.4.5](https://github.com/stephanrauh/ngx-extended-pdf-viewer/releases/tag/21.4.5)

and it is working there.

**Comment by chandramuralis** [comment]
> I am using [21.4.5](https://github.com/stephanrauh/ngx-extended-pdf-viewer/releases/tag/21.4.5)
> 
> and it is working there.

What version of pdfjs-dist are you using?

**Comment by KillerCodeMonkey** [comment]
i do not care, because my angular.json is just grabbing the *.mjs|js files ;-) 

So i am using the version that is part of that release.

**Comment by stephanrauh** [comment]
> What version of pdfjs-dist are you using?

Don't use pdfjs-dist. That won't work. ngx-extended-pdf-viewer uses its own fork of pdf.js, and it contains customizations that are not part of pdfjs-dist. I'm not even sure if you'll be able to see a PDF page using pdfjs-dist.

**Comment by stephanrauh** [comment]
The easiest way to get started is using the schematic, as described here: https://pdfviewer.net/extended-pdf-viewer/getting-started

**Comment by chandramuralis** [comment]
> The easiest way to get started is using the schematic, as described here: https://pdfviewer.net/extended-pdf-viewer/getting-started

This worked perfectly. Thanks for quick response @stephanrauh / @KillerCodeMonkey
