### ISSUE TITLE
Preparing-Print-Dialog stretching whole viewport

### ISSUE THREAD

**Issue by mapelpapel** [stephanrauh/ngx-extended-pdf-viewer#2578]
While upgrading from version 10 to version 21 of the viewer, I got a bug regarding the preparing-print-dialog. I could narrow it down to version upgrade 12-13. (Forced the version with the latest Angular 17 code)
Version 12.1.2:
![Screenshot 2024-09-20 104341](https://github.com/user-attachments/assets/8962ebe6-379f-4b2d-b883-16e65914680b)

Version 13.0.0:
![Screenshot 2024-09-20 104842](https://github.com/user-attachments/assets/4052a96b-d6ff-4a51-9d6a-7dad4f64ef60)

This bug is still present in my application when using the newest version of the viewer. But it seems to be a 'me'-problem, since it can't be reproduced on your demo site.

The workaround for it looking okay for now is:
`#printServiceDialog {
    max-width: 400px;
  }`

Maybe you find time to take a look at it. I could also try to narrow it down to a specific alpha version or provide some Dev-Tools information, but for now I don't know what to look for there.

**Comment by stephanrauh** [comment]
Yes, I'm 99% sure this bug has something to do with your particular setup. Even so, it would be interesting to find out what happened.

Just a wide show: at some point in time pdf.js converted the overlay `<div>` tags to proper `<dialog>`.  Maybe that was between version 12 and 13 of my library?

**Comment by stephanrauh** [comment]
I'm closing the bug now because I haven't heard from you for two weeks.
