### ISSUE TITLE
The print is off the page

### ISSUE THREAD

**Issue by tarun04** [stephanrauh/ngx-extended-pdf-viewer#258]
If you look at the attachment, it adds extra on right and bottom.

![image](https://user-images.githubusercontent.com/14960107/78804526-3cc3c000-798e-11ea-8525-a67b396d4bd4.png)

**Comment by stephanrauh** [comment]
Please check your CSS framework. More likely than not, that's the culprit. There are several closed issues here dealing with the topic. Please have a look at them, they're full of helpful info. I've also mentioned the topic in the showcase.: https://pdfviewer.net/troubleshooting

Maybe using Austin Walker's solution is all you need:
```css
@media print {
  body {
    min-width: auto !important;
  }
}
```

**Comment by stephanrauh** [comment]
Here's a selection of useful issues: #143, #148 and #175. As far as I remember, there are even more issues, but I guess that should give you a headstart to solve the problem.

If it doesn't, don't hesitate to tell me. I'm closing this ticket now, but I'm still listening to this channel.

Best regards,
Stephan

**Comment by tarun04** [comment]
> Please check your CSS framework. More likely than not, that's the culprit. There are several closed issues here dealing with the topic. Please have a look at them, they're full of helpful info. I've also mentioned the topic in the showcase.: https://pdfviewer.net/troubleshooting
> 
> Maybe using Austin Walker's solution is all you need:
> ```css
> @media print {
>   body {
>     min-width: auto !important;
>   }
> }
> ```

It worked. 

Thank you

**Comment by stephanrauh** [comment]
I'm glad to hear that! Not everybody reaches out to tell me - you've gained extra kudos for that!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, brace yourself for breaking changes. But I hope the new version fixes more bugs than it causes. Apart from workaround, which may be broken.

**Comment by mohan2001c** [comment]
> > Please check your CSS framework. More likely than not, that's the culprit. There are several closed issues here dealing with the topic. Please have a look at them, they're full of helpful info. I've also mentioned the topic in the showcase.: https://pdfviewer.net/troubleshooting
> > Maybe using Austin Walker's solution is all you need:
> > ```css
> > @media print {
> >   body {
> >     min-width: auto !important;
> >   }
> > }
> > ```
> 
> It worked.
> 
> Thank you

Added this solution, but it doesn't works for me.

**Comment by stephanrauh** [comment]
Version 7.0.0 of ngx-extended-pdf-viewer? That'd be a very old version, and at the moment, this project is a one-man show, so I'm awfully sorry, but I can't offer support for old versions. I'd like to do, but it's simply not possible.

Nonetheless, I believe CSS is the problem, and you should be able to hunt it down yourself by following the instructions at https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1431#issuecomment-1162091452.

**Comment by mohan2001c** [comment]
Thank you for your reply, I'll follow what you said.
