### ISSUE TITLE
PDF Viewer Text Layer Highlighting Issue

### ISSUE THREAD

**Issue by imskrishnan** [stephanrauh/ngx-extended-pdf-viewer#2590]
I used to have access to `PDFPageView.textLayer.textDivs` as of ngx-extended-pdf-viewer version 15 and angular version 14, but after upgrading the ngx-extended-pdf-viewer version to ^20.5.2 and angular to version 17, Im no longer having access to `PDFPageView.textLayer.textDivs`, and instead having to access it through `PDFPageView.textLayer.highlighter.textDivs`. This is causing highlighting issues and inaccuracies from highlighting perspective. Are you aware of this and is there any workaround? Thanks.

**Comment by Julian-B90** [comment]
I think this is related to this issue #2494, could you test a larger version 21.3.1?

**Comment by stephanrauh** [comment]
@imskrishnan I remember being caught unawares by this change. I should have documented it as a breaking change, but on the other hand, using the internal API of pdf.js is always at your own risk. I try to make it availably to you, type safety included, but if the Mozilla team decides to change their API, there's little I can do about it.

That said, you've already found out how to fix it, but you seem to be unhappy about it. What are your problem with highlighting, precisely? My best guess would be you've run into a timing issue, so try to add a timeout and see if it helps.

**Comment by imskrishnan** [comment]
Hi @stephanrauh, thanks for reaching out and I apologize to you about the delayed response. So I am accessing the page as:
const page = PDFViewerApplication.pdfViewer.getPageView(currentHighlightPageNumber - 1); where `page` is of type `PDFPageView`. I want access to the `textDivs` property of the `page`. Earlier - with ngx-extended viewer 15, I used to get it directly as `page.textLayer.textDivs.forEach` for getting access to the spans and calculate left, top, right and bottom styles - but with version 20.5.2 and angular version 17 - Im no longer having access to that. Could you let me know what happened or are you aware of any breaking changes? 

Thanks @Julian-B90 for your suggestion. But upgrading to the suggested version doesn't seem to resolve the issue. My application is globally scoping the PDFViewerApplication. But even after using `PDFNotificationService.onPDFJSInitSignal()` im still seeing the same issue and the highlighting is messed up.

**Comment by stephanrauh** [comment]
First of all, it's correct that that `textDivs` array has moved to the `highlighter` object. I don't know why that happened. It was a design decision of the base library that was a nasty surprise to me, too.

However, I think you can work with the new API as well as with the old one. Maybe you have to modify your code. It might be a good idea to catch the event `(textLayerRendered)`. The parameters of this event allow you to access the divs of the page that has been rendered. The old API allowed you to access the divs without waiting for the event. But I'm not sure that's an advantage. Thing is, the text layer is rendered lazily. If you've got a multi-page document, most text layers don't exist yet. But you can safely access them after receiving the `(textLayerRendered)` event.

I've tested this approach like so:

```html
<ngx-extended-pdf-viewer
      [src]="..."
      (textLayerRendered)="onTextLayerRendered($event)">
</ngx-extended-pdf-viewer>
```
```ts
onTextLayerRendered($event: TextLayerRenderedEvent) {
  console.log($event.pageNumber + " contains these text divs:", $event.layer.highlighter.textDivs);
}
```

**Comment by stephanrauh** [comment]
I'm closing this issue because I hope I've managed to answer your question and that you're able to solve the breaking change now. If not, don't hesitate to tell me!

Best regards,
Stephan
