### ISSUE TITLE
PDF cannot be displayed without specifying minifiedJSLibraries=false

### ISSUE THREAD

**Issue by ngochien9x** [stephanrauh/ngx-extended-pdf-viewer#2592]
Hi, 
I am using the version "ngx-extended-pdf-viewer": "^21.4.0" (package-lock 21.4.3). Today I was noticed that the PDF cannot be displayed, I try to specify the minifiedJSLibraries=false and it works, however, with the default setting (true), I got in the web console:
GET ...... assets/viewer-4.6.688.min.mjs net::ERR_ABORTED 404 (Not Found)

![image](https://github.com/user-attachments/assets/44b4d775-ba53-4293-b6c1-fae9e4fb8cd1)

Could you please take a look?
Thanks

**Comment by stephanrauh** [comment]
Version 21.4.4 fixes this. It was a silly mistake of mine, caused by publishing a bugfix of version 18 before publishing a new version 21.4.x.

**Comment by ngochien9x** [comment]
> Version 21.4.4 fixes this. It was a silly mistake of mine, caused by publishing a bugfix of version 18 before publishing a new version 21.4.x.

Thanks for the quick fixing
