### ISSUE TITLE
Additional Locale Is Not Applied / missing translations

### ISSUE THREAD

**Issue by Buckwich** [stephanrauh/ngx-extended-pdf-viewer#2594]
**Description**
1. Open any pdf with a non english language. Eg on https://pdfviewer.net/extended-pdf-viewer/i18n
2. open find bar (Ctrl+F)
3. Notice the `match each word` is not translated

![image](https://github.com/user-attachments/assets/caf8fc78-58f7-46dd-b447-d3513da2affd)

I looked a bit at the code and noticed that the strings 

``` 
unverified-signature-warning = This PDF file contains a digital signature. The PDF viewer can't verify if the signature is valid. Please download the file and open it in Acrobat Reader to verify the signature is valid.
pdfjs-infinite-scroll-button-label = Infinite scroll
pdfjs-find-multiple-checkbox-label = match each word
pdfjs-find-regexp-checkbox-label = regular expression
``` 

are not part of the `locale` but `addional-locale`. Infinite Scroll for example is also not translated. 

If you give me a hint on how you would like to handle those addional-locale files I could take a look at it myself. One idea I have is to merge them with locale files during build. Or is the idea that it should be merged on runtime

**Version info**
- Using version on pdfShowcase (stable): Running on Angular 18.2.3, pdf.js 4.6.688, and ngx-extended-pdf-viewer 21.4.5
- Same issue in BleedingEdge: Running on Angular 18.2.3, pdf.js 4.7.643, and ngx-extended-pdf-viewer 21.4.5

**Comment by stephanrauh** [comment]
Yes, you're right. These days, I have a hard time catching up, but it's definitely something I want to fix!

The bleeding edge branch has another problem: clicking the find icon doesn't open the find bar.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by stephanrauh** [comment]
Version 22.0.0-alpha.4 fixes the bug. Or both bugs, the find button opens the find bar again.

Enjoy!
Stephan
