### ISSUE TITLE
Add ResizeObserver for zoom

### ISSUE THREAD

**Issue by MichaelRoemerTR** [stephanrauh/ngx-extended-pdf-viewer#2595]
The automatic zoom and other options are not functional when a parent container size changes.

Could the same [ResizeObserver](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/871c8c75b73d255b8b96d2cc4039011911c75b0c/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L2296) that is now used for the toolbar layout be applied to the zoom?

**Comment by stephanrauh** [comment]
Can you elaborate, please? What's broken, precisely? When I open http://localhost:4200/extended-pdf-viewer/simple, open the developer tools, and reduce the window width, the zoom adjusts when the window get narrower.

How can I reproduce your issue? You know, you suggestion definitely sounds like a good idea, it's just I need to understand what's going wrong before I can fix it.

**Comment by MichaelRoemerTR** [comment]
@stephanrauh Thanks for your attention to this. Here is an example repo: https://github.com/roemermt/pdf-viewer-zoom-resize-container 

Just resize the div with at the bottom right corner of the div. This is a rudimentary example of my use-case.

**Comment by stephanrauh** [comment]
Thanks for providing the example repo!

Currently, I'm both ill and busy, so it's likely I'll forget your issue. If I do, can you remind me in, say, two weeks?

**Comment by stephanrauh** [comment]
Version 22.0.0-alpha.2 implements your idea. I've added a small delay to prevent that the document is re-rendered while the user is still resizing. Otherwise CPU usage goes through the roof, and despite that, the page is blank. Not the best combination. :)

**Comment by MichaelRoemerTR** [comment]
@stephanrauh Thanks for your work!
