### ISSUE TITLE
Cannot use both customSidebar and customThumbnail together

### ISSUE THREAD

**Issue by gauravumrani** [stephanrauh/ngx-extended-pdf-viewer#2599]
I tried using both, but only 1 works customSidebar, If I remove customSidebar then customThumbnail works

**Comment by Julian-B90** [comment]
Yes, that is correct. 

If you are using a customSidebar you will need to implement the sidebar yourself. If you only want to change the thumbnail, you can use customThumbnail. 

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/871c8c75b73d255b8b96d2cc4039011911c75b0c/projects/ngx-extended-pdf-viewer/src/lib/sidebar/pdf-sidebar/pdf-sidebar.component.html

**Comment by gauravumrani** [comment]
How can I use both?

**Comment by gauravumrani** [comment]
<div [ngClass]="{'full-screen-wrapper': fullScreen}">
  <ngx-extended-pdf-viewer #pdfViewer [(page)]="page" [src]="src" [customToolbar]="additionalButtons"
    [showBorders]="false" [sidebarVisible]="fullScreen" [zoom]="zoom" [activeSidebarView]="1"
    [customThumbnail]="checkBoxThumbnail" [customSidebar]="fancySidebar" (thumbnailDrawn)="onThumbnailDrawn($event)" (pageChange)="onPageChange($event)" (pagesLoaded)="onPagesLoaded()">
  </ngx-extended-pdf-viewer>

  <ng-template #checkBoxThumbnail>
    <a class="pdf-viewer-template">
      <div class="thumbnail" data-page-number="PAGE_NUMBER">
        <input id="thumbnail-cbx-PAGE_NUMBER" data-page-number="PAGE_NUMBER" [formControlName]="selectedPages.controls['page_PAGE_NUMBER'].value" class="thumbnail-checkbox" type="checkbox"/>
        <div class="thumbnail-text"></div>
        <div class="image-container">
          <img class="thumbnailImage" />
        </div>
        <div class="page_number">
          Page PAGE_NUMBER
        </div>
      </div>
    </a>
  </ng-template>

  <ng-template #fancySidebar>
    <div id="sidebarContainer" class="mt-5">
      <div id="additionalSidebarContainer">
        <div id="toolbarSidebar">
          <div id="outlineOptionsContainer" class="splitToolbarButton toggled">
            <div>Select Pages</div>
            <input type="text" class="form-control form-control-sm" placeholder="00" />
          </div>
        </div>
      </div>
      <pdf-sidebar-content></pdf-sidebar-content>
      <div id="sidebarResizer" class="hidden"></div>
    </div>
  </ng-template>

  <ng-template #additionalButtons>
    <div id="toolbarViewer" class="ind-pdf-viewer" [ngClass]="{'full-screen': fullScreen}">
      <div id="toolbarViewerLeft"></div>
      
      <div class="ind-document-pages">
        {{page}} / {{totalPages}} Pages
      </div>
      <div id="toolbarViewerRight">
        <pdf-zoom-dropdown class="invisible"></pdf-zoom-dropdown>
        <select class="ind-document-zoom" [(ngModel)]="zoom" id="role">
          <option value="auto">Auto</option>
          <option value="page-fit">Page Fit</option>
          <option value="50%">50%</option>
          <option value="75%">75%</option>
          <option value="100%">100%</option>
        </select>
        <div (click)="onExpandClick()" tabindex="0" role="button" class="ind-document-expand">
          <img src="icons/linear/expand.svg" />
        </div>
      </div>
    </div>
  </ng-template>
</div>

**Comment by stephanrauh** [comment]
I guess the problem is I've implemented code to support custom toolbars in the default sidebar, and I suppose you haven't copied this code into your sidebar implementation. Have a look at this class (or rather, at the entire folder and its parent folder): https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/sidebar/pdf-sidebar/pdf-sidebar-content/pdf-sidebar-content.component.ts

**Comment by stephanrauh** [comment]
@Julian-B90 You seem to have put some thought to the issue, so I've added you as assignee. If you guys feel there's something I have to do - such as improving the documentation or filling some gap of the implementation - don't hesitate to tell me.

**Comment by Julian-B90** [comment]
@gauravumrani  can you try this?

```html
<div [ngClass]="{'full-screen-wrapper': fullScreen}">
  <ngx-extended-pdf-viewer #pdfViewer [(page)]="page" [src]="src" [customToolbar]="additionalButtons"
    [showBorders]="false" [sidebarVisible]="fullScreen" [zoom]="zoom" [activeSidebarView]="1"
    [customSidebar]="fancySidebar" (thumbnailDrawn)="onThumbnailDrawn($event)" (pageChange)="onPageChange($event)" (pagesLoaded)="onPagesLoaded()">
  </ngx-extended-pdf-viewer>

  <ng-template #checkBoxThumbnail>
    <a class="pdf-viewer-template">
      <div class="thumbnail" data-page-number="PAGE_NUMBER">
        <input id="thumbnail-cbx-PAGE_NUMBER" data-page-number="PAGE_NUMBER" [formControlName]="selectedPages.controls['page_PAGE_NUMBER'].value" class="thumbnail-checkbox" type="checkbox"/>
        <div class="thumbnail-text"></div>
        <div class="image-container">
          <img class="thumbnailImage" />
        </div>
        <div class="page_number">
          Page PAGE_NUMBER
        </div>
      </div>
    </a>
  </ng-template>

  <ng-template #fancySidebar>
    <div id="sidebarContainer" class="mt-5">
      <div id="additionalSidebarContainer">
        <div id="toolbarSidebar">
          <div id="outlineOptionsContainer" class="splitToolbarButton toggled">
            <div>Select Pages</div>
            <input type="text" class="form-control form-control-sm" placeholder="00" />
          </div>
        </div>
      </div>
      <pdf-sidebar-content 
        [customThumbnail]="checkBoxThumbnail"
      ></pdf-sidebar-content>
      <div id="sidebarResizer" class="hidden"></div>
    </div>
  </ng-template>

  <ng-template #additionalButtons>
    <div id="toolbarViewer" class="ind-pdf-viewer" [ngClass]="{'full-screen': fullScreen}">
      <div id="toolbarViewerLeft"></div>
      <!-- In Full Screen, middle section shows Filename -->
      <div class="ind-document-pages">
        {{page}} / {{totalPages}} Pages
      </div>
      <div id="toolbarViewerRight">
        <pdf-zoom-dropdown class="invisible"></pdf-zoom-dropdown>
        <select class="ind-document-zoom" [(ngModel)]="zoom" id="role">
          <option value="auto">Auto</option>
          <option value="page-fit">Page Fit</option>
          <option value="50%">50%</option>
          <option value="75%">75%</option>
          <option value="100%">100%</option>
        </select>
        <div (click)="onExpandClick()" tabindex="0" role="button" class="ind-document-expand">
          <img src="icons/linear/expand.svg" />
        </div>
      </div>
    </div>
  </ng-template>
</div>
```

**Comment by gauravumrani** [comment]
It worked, Thank you @Julian-B90
