### ISSUE TITLE
Error when destroying component

### ISSUE THREAD

**Issue by achapman009** [stephanrauh/ngx-extended-pdf-viewer#260]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple?
I can not test this error on the demos.

**Describe the bug**

When destroying component that is using the ngx-extended-pdf-viewer I am getting the following error:

this.document.removeElement is not a function at DynamicCssComponent.ngOnDestroy.

This seems to keep the pdf-viewer in memory, so the next time i load the viewer up i am receiving the error that 2 pdf viewers exist.

**Version info**
- Version of ngx-extended-pdf-viewer 3.0.0
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files) default

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 64 bit.
 - Browser [e.g. chrome, safari] Edge Chromium, Google Chrome, Mozilla Firefox

**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:
1. Implement a ngx-extended-pdf-viewer within a component.
2. You can either toggle the component to render or place an if statement on the selector for the pdf-viewer itself.
2. Toggle the viewer with a button to remove it from the DOM. The error will pop when its trying to be destroyed.

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)
I have tested with multiple PDF files, the same issue exists.

**Screenshots**

Here is the error log I am getting from the console:
![image](https://user-images.githubusercontent.com/20817730/79149481-39b53f00-7d95-11ea-9cc0-53a0311636cf.png)

**Additional context**

This was not an issue with previous releases, it may be tied to something new in pdf.js.

**Comment by thecodemonk** [comment]
Just implemented this component 20 minutes ago and I'm getting it when navigating away from page component that this is implemented in.

**Comment by stephanrauh** [comment]
Oops. That's an unexpected bug, and it doesn't look good. I'm putting it top on my list.

**Comment by stephanrauh** [comment]
Weird bug. No idea how it slipped my testing. Be that as it may, your bugfix has landed with version 3.0.1.

Enjoy!
Stephan
