### ISSUE TITLE
Printing Blank Page Before Each Page Of PDF

### ISSUE THREAD

**Issue by jayeshsony** [stephanrauh/ngx-extended-pdf-viewer#2600]
I've raised this issue before [Issue Link](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2403). At that time, I wanted to disable the PDF viewer in the browser, and you helped me by providing the necessary code. Now, I want to address the issue of printing blank pages. Some time ago, my senior applied CSS changes that managed to remove most blank pages, but there is still first page that is blank. Although he applied the margin-bottom property to fix the issue, the first page remains blank. Can you help me add CSS to ngx-extended-pdf-viewer? Please let me know where to add the class name and how to apply properties in the CSS file

**Comment by stephanrauh** [comment]
Well, it depends on your definition of help. I can't tell you which CSS rule to fix, but I can tell you how to hunt down the issue yourself. Usually, that's even more satisfying, unless your boss is standing behind your and expects you the deliver the solution within the hour.

Please open https://pdfviewer.net/extended-pdf-viewer/troubleshooting and navigate to the section "Trouble with printing". In particular, the sub-section "Hunting down other printing issues" is interesting to you. It contains a link to an issue where I described to to debug printing.

You should to that with https://mozilla.github.io/pdf.js/legacy/web/viewer.html in parallel. That's the showcase of the base library, so you can see how printing is meant to work. If you're using my library, there's additional CSS code that might mess up printing, and of course, your own CSS rules might interfere with printing. The general idea is to define your CSS rules such that they don't influence `#printContainer`.

I'd like to keep the issue open until you've managed to resolve the issue, so please tell me when you've finished!

**Comment by jayeshsony** [comment]
Thanks for sending the document! It helped me understand the issue clearly, and I was able to resolve it because of your insights. I really appreciate your support!
