### ISSUE TITLE
It never prints 1st page if only 1st page is provided

### ISSUE THREAD

**Issue by gauravumrani** [stephanrauh/ngx-extended-pdf-viewer#2602]
Input parameter

```
const range = {
      from: 1,
      to: 500,
      included:[1],
    } as PDFPrintRange;
    this.pdfViewerService.print(range);
```

In source code, 
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/871c8c75b73d255b8b96d2cc4039011911c75b0c/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.service.ts#L219

Page count starts with 1 which is okay, but on next function call, 
It increases the index with 1 
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/871c8c75b73d255b8b96d2cc4039011911c75b0c/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.service.ts#L228

So validation of range starts from page 2 always

**Comment by gauravumrani** [comment]
Closing this as I was using little older version

**Comment by stephanrauh** [comment]
Sounds like a duplicate of #2534.

**Comment by stephanrauh** [comment]
BTW, even though your issue has vanished into thin air, I'd like to thank you for pointing it out. You've added an excellent bug analysis - and that's something I don't see every day. Awesome!
