### ISSUE TITLE
scroll change event emit  

### ISSUE THREAD

**Issue by bacemayadi2** [stephanrauh/ngx-extended-pdf-viewer#2604]
**Is your feature request related to a problem? Please describe.**
i need to track if user is really reading document  and how long is he reading 
**Describe the solution you'd like**
event emitted whenever  user scroll up down or click button up or down 
**Describe alternatives you've considered**
using infinite scrolling  but  i lose the top bar  
page change event but if page is too long would make it so reading tracking not so accurate as i want to have relatively small  idle time to track real engagement

**Comment by stephanrauh** [comment]
That's a fairly exotic use-case, so I won't modify the library for it. There are already so many attributes and events that it gets confusing for newbies.

However, you can add a scroll listener yourself. You can read the scroll position like so:
```ts
console.log(document.getElementById('viewerContainer').scrollTop);
```
