### ISSUE TITLE
Layers: disable all / groups

### ISSUE THREAD

**Issue by claralta** [stephanrauh/ngx-extended-pdf-viewer#2613]
**Is your feature request related to a problem? Please describe.**
We use the viewer for topography, which means lots and lots of layers, but most of the time we only want to isolate a few for viewing

**Describe the solution you'd like**
Checkboxes for layers (as is right now), as well as one per "group", and for all layers.

**Additional context**
We're currently on v18 because of an old Angular/Material version, but should switch soon hopefully, so sorry if this is already available in some way in new versions

**Comment by stephanrauh** [comment]
I'm not an expert on layers. Are there groups of layers? The demo https://pdfviewer.net/extended-pdf-viewer/layers makes me think so - but it's the only PDF I've got using groups of layers. Can you send me an example without violating copyright?

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by stephanrauh** [comment]
IMHO your request makes sense, but it should be addressed by the core library. Please open a report at https://github.com/mozilla/pdf.js/issues.
