### ISSUE TITLE
scrollPageIntoView: "1" is not a valid pageNumber parameter.

### ISSUE THREAD

**Issue by stargur** [stephanrauh/ngx-extended-pdf-viewer#2615]
So i need to load the component more than 1 time on a single page at different circumstances and when i do i get this 
error

**scrollPageIntoView: "1" is not a valid pageNumber parameter.** 

the first PDF loads perfectly but the rest does not. The error also occures event when i apply the same file to all the components.

I am using version : 21.4.5

**Comment by stephanrauh** [comment]
Yes, displaying multiple PDF files side-by-side on the same HTML page doesn't work yet. It's on my long-term plan, but it'll take a while. In the meantime, you can put the viewers into an iFrame, as described here: https://pdfviewer.net/extended-pdf-viewer/side-by-side

**Comment by stephanrauh** [comment]
I've just uploaded a new version of the documentation. I hope it explains the side-by-side workaround better then the previous version.
