### ISSUE TITLE
Annotations: click events & granular control?

### ISSUE THREAD

**Issue by prelol** [stephanrauh/ngx-extended-pdf-viewer#2616]
Hi stephanrauh,

I'm using annotations to draw rectangles on some parts of a pdf.
Now I need a event to trigger some code whenever the user clicks an annotation.

The best attribute i could find was 'annotationEditorEvent' but it only triggers on adds, removes and edits.
Is there an event that fires when an annotation is clicked?

In addition, is it possible to hide or disable the move and delete controls when an annotation *is* clicked? 

Any hints would be helpful!

Thanks in advance

**Comment by stephanrauh** [comment]
I suppose you can implement the click listener yourself. The annotations are `<div>` tags, so you can add an `onClick` handler after creating it.

As for hiding the move and delete controls: yes, you can do that by applying some CSS.
