### ISSUE TITLE
Search icon not working

### ISSUE THREAD

**Issue by Miedziaq** [stephanrauh/ngx-extended-pdf-viewer#2624]
Search icon is doing nothing. Even on your website with example. Stable version and bleeding-edge.
newest Edge, Firefox, Chrome.

in local environment Angular 16.2.9, pdf 4.7.688

**Comment by stephanrauh** [comment]
The latest version (22.0.0-alpha.3, published last evening) solves the issue. I've updated the showcase now, so it's fixed there, too.
