### ISSUE TITLE
Sidebar is broken

### ISSUE THREAD

**Issue by Miedziaq** [stephanrauh/ngx-extended-pdf-viewer#2625]
In version 4.7.688 sidebar is not working, when i set sidebarVisible: true its fine.
In other way its always closed, clicking the button changes nothing.
When i spy on sidebarVisibleChange event, this was called 5 times on click.       3 times with visible:true 2 times with visible:false

What the hell..

Angular 16.2.9

**Comment by stephanrauh** [comment]
The latest version (22.0.0-alpha.3, published last evening) solves the issue. I've updated the showcase now, so it's fixed there, too.

**Comment by Miedziaq** [comment]
ok i will check soon. thx :D
