### ISSUE TITLE
Adding a note to the highlighted text

### ISSUE THREAD

**Issue by ldu2** [stephanrauh/ngx-extended-pdf-viewer#2628]
**Is your feature request related to a problem? Please describe.**
I think it'd be very helpful if we can add a feature where we can add notes to the highlighted text. It explains why the text is highlighted and provides more information.

**Describe the solution you'd like**
I think something like this would be nice. The highlighted text is made by your library already. I opened it the PDF reader and once it's clicked on. It pops up an additional option to add comment.

![Screenshot (63)](https://github.com/user-attachments/assets/fc56c10a-ec20-4fb0-88bd-6e8caf9ff27f)

**Describe alternatives you've considered**
I haven't consider an alternative solution yet. But let me know if there's any other ideas.

**Additional context**
I'm open to implement this feature also. Can you point me to the place where I can make the related changes? Thanks a lot!

**Comment by stephanrauh** [comment]
If you're not in a hurry, the best strategy is to reach out to the pdf.js team and to offer to send a pull request. @Calixteman can probably help you. If you go this road, please keep in mind that pdf.js is the PDF viewer of Firefox. Your feature should make many Firefox users happy.

The other question is how to implement this in PDF. It's possible, but don't ask me how to do that - I simply don't know. But you can ask ChatGPT - it has several ideas that sound promising, and pdf.js already supports popups (see https://github.com/mozilla/pdf.js/blob/93961e28022d74bc14764c5bbe3e2d25383c3b21/src/display/annotation_layer.js#L112).

So I guess most of the work is extending https://github.com/mozilla/pdf.js/blob/master/src/display/editor/highlight.js.

**Comment by stephanrauh** [comment]
I'm closing the ticket because I'm already drowning in tickets. However, I encourage you to submit the pull request!

Best regards,
Stephan
