### ISSUE TITLE
Encountering 'pdfManager is null' error when navigating away from a page displaying a PDF using ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by kulabanta** [stephanrauh/ngx-extended-pdf-viewer#2639]
In our web application, we display PDF documents on a page using ngx-extended-pdf-viewer. We have observed that, sporadically, if the PDF has not fully loaded in ngx-extended-pdf-viewer and we attempt to navigate away from the document page, we encounter the following error.
```
"exception": {
    "message": "pdfManager is null",
    "stack": "BaseExceptionClosure@/assets/viewer-4.6.688-es5.mjs:5601:6766\n@/assets/viewer-4.6.688-es5.mjs:5601:6840\n@/assets/viewer-4.6.688-es5.mjs:5762:3\n"
  },
 ```
**Version info**
- 21.4.6

**Comment by stephanrauh** [comment]
I'm afraid there's nothing I can do about it. pdf.js is highly asynchronous, and if you're destroying the PDF viewer while it's still initializing errors are inevitable.

However, you can implement a log filter to ignore these messages: https://pdfviewer.net/extended-pdf-viewer/filtering-console-log
