### ISSUE TITLE
An error occurred while loading the PDF. 

### ISSUE THREAD

**Issue by Prasanth-FrontendDeveloper** [stephanrauh/ngx-extended-pdf-viewer#264]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple? **Yes**

**Describe the bug**
Pdf file is not loading while using the http link in [src] attribute. For example Amazon s3 link or normal link http://gahp.net/wp-content/uploads/2017/09/sample.pdf.

**Version info**
- Version of ngx-extended-pdf-viewer - **3.0.0.**
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files) - **"scripts": [
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
              "node_modules/ngx-extended-pdf-viewer/assets/viewer.js",
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js"]**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - **Chrome**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**
![IMG_20200413_223040](https://user-images.githubusercontent.com/61708858/79352941-11c20900-7f58-11ea-8ce3-7b4ff2470b5a.png)

**Additional context**

**Comment by stephanrauh** [comment]
Yeah, the good old CORS problem. It's a protection against hackers. As a side effect, it also drives developers nut.

Have a look at https://juristr.com/blog/2016/11/configure-proxy-api-angular-cli/ for in-depth information and a solution. However, I'm not sure if Juri's `proxy.conf.json` file still works. When I needed it two days ago, I had to use a slightly different version:

```json
{
  "/api": {
    "target": {
      "host": "www.beyondjava.net",
      "protocol": "https:",
      "port": 443
    },
    "secure": true,
    "logLevel": "debug",
    "changeOrigin": true
  }
}
```
