### ISSUE TITLE
Feature Request: Allow Direct Access to Edited PDF for Custom Download or Backend Submission

### ISSUE THREAD

**Issue by AmmarBaig135** [stephanrauh/ngx-extended-pdf-viewer#2640]
**Feature Request:** Enable Access to Edited PDF File for Backend Submission or Custom Download

**Description:** I'm using ngx-extended-pdf-viewer to allow users to upload and edit PDF files, such as adding signatures or annotations. However, I've encountered a limitation: the library does not provide a way to directly access the edited PDF data in memory. This prevents me from sending the modified file to a backend API or implementing a custom download functionality.

Currently, the built-in download button works as expected, allowing users to download the edited file with annotations or signatures. However, we need the ability to programmatically access the edited PDF data so that we can either send it to our server or implement a custom download button within our application. When we attempt to implement a custom download function, it only allows downloading the original unedited file, as we don’t have access to the modified document in memory.

**Proposed Solution:** Would it be possible to expose a method or event that provides access to the current, edited state of the PDF file in memory? For instance:

- An API method like getEditedPdf() that returns the PDF file with all user modifications.
- An event like onPdfEditComplete that triggers when a user finishes editing and provides the updated PDF file.

**Use Case:** This feature would be incredibly useful for applications that require users to:

- Submit signed documents to a backend service for storage.
- Download the modified version of the PDF after making changes.

**Potential Implementation:** If feasible, perhaps an option to export the edited file as a Blob or ArrayBuffer could be added. This would allow developers to handle the file in various ways, like creating an API call or allowing custom file downloads.

Thank you for considering this feature! This would greatly enhance the flexibility and functionality of ngx-extended-pdf-viewer in workflows involving document editing and submission.

**Comment by stephanrauh** [comment]
I think [this](https://pdfviewer.net/extended-pdf-viewer/export-file) is what you're looking for:

```ts
constructor(private pdfViewerService: NgxExtendedPdfViewerService) {}

  public blob: Blob | undefined;
  
  public async export(): Promise<void> {
    this.selectedTabIndex = 2;
    this.blob = await this.pdfViewerService.getCurrentDocumentAsBlob();
  }
}
```
