### ISSUE TITLE
APIs for detecting secondary toolbar click events

### ISSUE THREAD

**Issue by imskrishnan** [stephanrauh/ngx-extended-pdf-viewer#2641]
Hi @stephanrauh, can you please let me know if you expose any apis for the pdf viewer that lets me detect click events for the secondary toolbar button options - like the Vertical Scrolling and Horizontal Scrolling? This is part of requirement where I need to disable Spread buttons when Horizontal scrolling is being clicked, and I think Spreads don't take effect anyways when Horizontal scrolling is enabled.

Thanks,
Santhosh

**Comment by stephanrauh** [comment]
These menu items can also be part of the primary toolbar, so let's tackle the more general question if you can catch changes of the scroll or spread options.

Yes, you can, and it's easy. Both `[(spread)]` and `[scrollMode]` are two-way binding attributes. So you'll want to define an event handler for `(scrollModeChanged)`.
