### ISSUE TITLE
Custom ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2646]
hi stephan rauh, I customized your ngx-extended-pdf-viewer library, basically I just added a few features for a business in my personal project. Specifically, I customized it on ngx-extended-pdf-viewer version 18.1.x. Now I'm having a bit of trouble determining which branch in extended-pdf-viewer-showcase and mypdf.js will be equivalent to the ngx-extended-pdf-viewer 18.1.x version.
![image](https://github.com/user-attachments/assets/7ada5de1-a9db-4886-aed6-2d88c9cbba49)

These are pdfjs folders in ngx-extends-pdf-viewer version 18.1.x, it has two pdfJs versions. since i also added some logic to pdfJ i need to make sure that when i run npm start in ngx-extends-pdf-viewer it automatically builds it all for me

![image](https://github.com/user-attachments/assets/012bfec9-aa73-4307-8fac-e5635a523a6b)
Thanks a lot

**Comment by stephanrauh** [comment]
The correct version number of pdf.js is 3.10. You can see this here: https://www.npmjs.com/package/ngx-extended-pdf-viewer/v/18.1.9?activeTab=code

Sorry for adding the 4.0 files. That was an annoying accident. These kind of errors are the reason why I try to avoid to fix a bug in an older version.

The corresponding version of the showcase seems to be this one: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/dd91eb41fa647148e0a351d37b8cfffeb17844ec. Usually I add a commit called "published version 18.1.13" (but I haven't written a script for that yet, so don't rely on it).
