### ISSUE TITLE
404 when trying to access to min.js file

### ISSUE THREAD

**Issue by albertB4work** [stephanrauh/ngx-extended-pdf-viewer#2647]
When trying to render the document i obtain a 404 error

ngx-extended-pdf-viewer.mjs:1513: GET http://localhost:4200/assets/ngx-extended-pdf-viewer/viewer-4.7.697.min.mjs net::ERR_ABORTED 404 (Not Found)

I did the steps written here:
https://pdfviewer.net/extended-pdf-viewer/getting-started

the pdfUrl is fine because before we used an iframe and the document was visible, also tested with a pdf in assets folder

**Comment by albertB4work** [comment]
This is what I put in my angular.json assets array

{
    "glob": "**/*",
    "input": "node_modules/ngx-extended-pdf-viewer/assets/",
    "output": "/assets/"
 }

**Comment by stephanrauh** [comment]
I suppose you've managed to solve the issue? For anyone reading this ticket: the first URL looks a bit odd to me. The path should be `localhost:4200/assets/viewer-*.*.mjs`. The additional `ngx-extended-pdf-viewer` in the path looks a bit odd. If you run into a similar issue, you can try to debug this function:
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/df7d5ca3fdaa53b93013f56b544b81260995978c/projects/ngx-extended-pdf-viewer/src/lib/options/pdf-default-options.ts#L16-L22

**Comment by vDupindev** [comment]
Hello,
I have the same problem with "@angular/core": "^18.2.0".
I tried with latest ngx-extended-pdf-viewer version and 21.4.5.
I have the same problem.

![image](https://github.com/user-attachments/assets/e29dfdd0-3af2-43e8-ae91-5e6a727f2695)

**Comment by stephanrauh** [comment]
@vDupindev Did you configure the `angular.json` correctly?

```json
       "assets": [
              ...
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets",
                "output": "/assets/"
              },
```

**Comment by vDupindev** [comment]
Yes:
![image](https://github.com/user-attachments/assets/46f43dbd-cf2f-4e7a-b980-616736706b09)

I tried recommended way on this page: [](https://pdfviewer.net/extended-pdf-viewer/getting-started)

**Comment by stephanrauh** [comment]
When you run `ng build`, are the JavaScript files there?

**Comment by vDupindev** [comment]
I have this listing: 
![image](https://github.com/user-attachments/assets/3749e7e9-8f43-4aca-9c33-816dffd26996)

**Comment by stephanrauh** [comment]
So that's why the browser can't find them. :) But that's strange: the 4.6.688 files belong to an older version of ngx-extended-pdf-viewer - most likely version 21.4.5. You can see that here: https://www.npmjs.com/package/ngx-extended-pdf-viewer/v/21.4.5?activeTab=code

Running `npm clear && npm install && ng build` should copy the correct set of files to the assets folder. Maybe the Angular cache causes trouble, so delete it, just in case (`rm -r ./angular/cache`). If you're using Windows, the commands are slightly different, but I hope you get the gist of it.

**Comment by vDupindev** [comment]
Yes it's maybe because after the first fail, i tried an old version of ngx-extended-pdf-viewer.

After these steps it's ok:

- change the version manually in the package.json to 22.0.0
- run npm install
- remove /dist folder
- run ng build
- ng serve

**Comment by vDupindev** [comment]
I don't know why there was a problem on my first install.
Thanks for your reactivity. ;)
