### ISSUE TITLE
Browser Crash by Scrolling

### ISSUE THREAD

**Issue by windykarie** [stephanrauh/ngx-extended-pdf-viewer#2654]
we have been using the library to view pdf in our application. However, if there is more pages (50 or above), upon zooming in and scrolling, the browser will crash. The likelihood of crash is higher if the number of page is higher.

if any of you has faced similar issue and is there any suggestions or workaround for it?

thank you so much

**Comment by stephanrauh** [comment]
Which browser and which version of the PDF viewer are you using? Is there a console message? Can you reproduce the error with the base library (https://mozilla.github.io/pdf.js/legacy/web/viewer.html)?

**Comment by stephanrauh** [comment]
I don't know how to reproduce the bug, and nobody else has chimed in. So I'm closing the bug now.
