### ISSUE TITLE
Bug: addImageToAnnotationLayer fails on pages not yet rendered

### ISSUE THREAD

**Issue by AmmarBaig135** [stephanrauh/ngx-extended-pdf-viewer#2656]
### Description:

I am trying to add an image to all pages of a PDF using addImageToAnnotationLayer in ngx-extended-pdf-viewer. However, I am facing the following issues:

1. The image is applied correctly only to the first few pages, while other pages remain unaffected.
The following warning appears in the console:
`Warning: paste: "Cannot read properties of undefined (reading 'deserialize')".`
2. If I manually scroll to the end of the document to ensure all pages are rendered before calling the function, the image attaches correctly to all pages.
3. I suspect this happens because the annotation layer isn't fully initialized for pages that haven't been rendered yet. I also tried explicitly rendering each page using renderPage(page) before calling addImageToAnnotationLayer, but this approach did not resolve the issue. Below is the code I'm using:

```ts
async addImageToVisiblePages(image: string): Promise<void> {
    const pages: number = this.pdfViewerService.numberOfPages();
    console.log("Number of pages:", pages);

    const promises = [];

    for (let page = 0; page < pages; page++) {
      console.log("Processing page:", page);

      const parameters: PdfImageParameters = {
        urlOrDataUrl: image,
        page: page,
        left: 160,
        bottom: 150,
        right: 300,
        top: 200,
        rotation: 0,
      };

      console.log("Parameters:", parameters);

      // Explicitly render the page before adding the image
      const renderedPage = this.pdfViewerService.renderPage(page);
      console.log(`Rendered page: ${page}`, renderedPage);

      promises.push(this.pdfViewerService.addImageToAnnotationLayer(parameters).catch((error) => {
        console.error(`Failed to add image to page ${page + 1}:`, error);
      }));
    }

    await Promise.all(promises);
}
```

### Steps to Reproduce:

1. Load a multi-page PDF in ngx-extended-pdf-viewer.
2. Call the addImageToVisiblePages function to add an image to every page.
3. Observe that the image is applied only to the initially rendered pages, and the rest remain unaffected.
4. Manually scroll to the end of the document and then re-execute the function. This time, the image is added to all pages.

**Expected Behavior:** The image should be added to all pages without requiring manual scrolling.

**Actual Behavior:** The image is added only to the rendered pages. Unrendered pages fail to display the image, and a warning about deserialize appears in the console.

### Questions:

1. Is there a specific method to ensure that all pages (including annotation layers) are fully rendered before calling addImageToAnnotationLayer?
2. Is this a bug or a limitation in ngx-extended-pdf-viewer?
3. Can you provide guidance on how to achieve this functionality?

**Comment by stephanrauh** [comment]
I've updated the documentation.

**Comment by gelezayka** [comment]
Hi, I use the annotationLayerRendered event to add annotation, but when adding annotation I get the error: Warning: paste: "Cannot read properties of undefined (reading 'deserialize')."

But work fine if i use annotationEditorLayerRendered event for add annotation.

What am I doing wrong?  Or is it somehow necessary to describe this in the documentation too?

Thanks!


<img width="1005" height="73" alt="Image" src="https://github.com/user-attachments/assets/10566ff2-0a3d-4318-841e-58f55ae147c9" />

**Comment by stephanrauh** [comment]
@gelezayka You're doing everything right. `(annotationEditorLayerRendered)` is the correct event. That's because the editor annotations are not added to the annotation layer, but to another layer, the annotation editor layer. Only after saving and reloading the annotations makes it to the annotation layer.
