### ISSUE TITLE
How to find TextLayerRendered and wanted event callback

### ISSUE THREAD

**Issue by iamrajaraj** [stephanrauh/ngx-extended-pdf-viewer#266]
Please enable the textLayerRendered callback event, because immediate to text layer rendered i am adding some addition CSS to highlight some text. 

Currently I can do it using (PageLoad) event but when ever find, zoom in/out , navigation occurs text layer is re-written but my styling added before got vanished, hence enabling (textLayerRendered) event as in ng2-pdf-viewer will help me. Thanks

**Comment by stephanrauh** [comment]
`(textlayerRendered)` has landed with version 3.1.0. Thanks for suggesting this!

BTW: Your use-case sounds like a great demo on https://pdfviewer.net. If you've got an idea how to demonstrate the feature, just tell me!

**Comment by iamrajaraj** [comment]
Thanks stephanrauh, for immediate update and release.

Can you please fix this  https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/267 bug to test this feature

**Comment by iamrajaraj** [comment]
Verified and textlayerRendered is working now. 

https://www.npmjs.com/package/ngx-extended-pdf-viewer/v/3.1.0 but the event name give as (textLayerRendered) but its actually (textlayerRendered), please correct it

**Comment by stephanrauh** [comment]
Consider it done. I've kept the old version to avoid a breaking change. If I don't forget it :), I'm going to remove it with version 4.0.0.

**Comment by stephanrauh** [comment]
The feature has landed with version 3.2.0.
