### ISSUE TITLE
Hi . I need feature, when you find words in document , you can also set them color , and will be great , when I also can set color for each word

### ISSUE THREAD

**Issue by denyk443245235** [stephanrauh/ngx-extended-pdf-viewer#268]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I'm always frustrated when [...]"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by denyk443245235** [comment]
I develop project , where you have learning and training words , and I need to highlight each group of this words , in different colors

**Comment by stephanrauh** [comment]
@iamrajaraj Can you help @denyk443245235 ?

**Comment by denyk443245235** [comment]
I think , it will be very use useful , for many developer , because  when you can highlight different groups of words in different colors , it looks better, more clearly

**Comment by iamrajaraj** [comment]
@denyk443245235, Using (textlayerRendered) callback, call your own method which does some action on pdf text.
In my case used this callback and checking is there matching words which i gave and if its presents on text layer adding css to that text like 
`html:
(textlayerRendered)=callBackMyMethod($event);

typescript:

callBackMyMethod(event){
  $(.textLayer).contains("sometext").css("background-color":"red");
}`

**Comment by stephanrauh** [comment]
Any suggestion what a useful and flexible API could look like? Or is it enough to add a demo to the showcase that uses the `(textLayerRendered)` approach?

**Comment by stephanrauh** [comment]
I've added your use-case to the demos: https://pdfviewer.net/textlayer. The demo shows what can be achieved with the text layer, and it also shows the limits of this approach.

Enjoy!
Stephan
