### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'AbortException' of 'globalThis.pdfjsLib' as it is undefined.

### ISSUE THREAD

**Issue by the-dev-adonis** [stephanrauh/ngx-extended-pdf-viewer#2687]
Facing some time but not reproduce after reload and after this error pdf viewer not rendering showing blank state.

Can you please help me out to solve this issue.

Code snippet {snip} DFLinkService{setDocument(e,t=null){}}const{AbortException:k,AnnotationEditorLayer:B,AnnotationEditorParamsType:N,AnnotationEditorType:F,Ann {snip}

version - 20.5.2
angular v - 17.2.2

**Comment by the-dev-adonis** [comment]
Is this due to textlayer or something else ?

**Comment by stephanrauh** [comment]
No, this is not related to the text layer. It's this source code: 
https://github.com/stephanrauh/pdf.js/blob/b2f48e0961143a707a68138e4d5cf76cabeb0ce8/web/pdfjs.js#L17

**Comment by stephanrauh** [comment]
I don't have a clue how your error happens. It sounds like a weird racing condition. However, if you update to version 22.1.0-alpha.2, the error is gone for good. Your bug report allowed by to tidy up a particularly hacky part of the code.

Thanks!
Stephan
