### ISSUE TITLE
PDF Viewer Search throwing an error in the console

### ISSUE THREAD

**Issue by imskrishnan** [stephanrauh/ngx-extended-pdf-viewer#2692]
Hi @stephanrauh,

I recently upgraded my application to Angular 17 and PDF viewer version 21. Im running into this error when searching for terms in the pdf. Heres the screenshot of the error im seeing in the console:

![Screenshot 2024-12-17 at 8 32 34 PM](https://github.com/user-attachments/assets/d2ad2c53-88ac-49f0-a893-8c54d831972c)

It says that the `The PDF viewer hasn't finished initializing. Please call find() later.` and it doesn't highlight any terms in the PDF. I have verified that the PDF has apparently finished loading and is visible on the screen, I get this when I type each term in the search box. I wanted to know if you had encountered the same issue anywhere else before and wanted to know if you might know whats going on here? 

Thanks,
Santhosh

**Comment by stephanrauh** [comment]
I'm not able to reproduce your issue at https://pdfviewer.net/extended-pdf-viewer/find, so I guess I'm missing something. Can you send me a reproducer? That's a simple, minimal but functional project showing the bug.

I suspect you're calling `find()` very early. What happens if you run it after a timeout of, say, 100 milliseconds? Or 500?

**Comment by stephanrauh** [comment]
Another idea is that you're using a second copy of `NgxExtendedPdfViewerService`. This should be a global object - best put it into the root module. That's the default, but of course, you can configure it differently - and maybe that's a pitfill with standalone components.

**Comment by kobalt42z** [comment]
I can reproduce the issue by injecting PdfExtendedService into my custom search service, which I then inject into a component. In that setup, the error is thrown. However, if I inject the PdfExtendedService directly into the component and trigger the search, it works correctly.

**Comment by stephanrauh** [comment]
Maybe it's a timing problem, and your custom search service calls the find method too early. Try delaying the search until `(onPdfLoaded)` or the first `(pageRendered)` event has fired:

```ts
onPdfLoaded() {
  this.isPdfReady = true;
  // Now search is safe to use
}

performSearch() {
  if (!this.isPdfReady) {
    console.warn('PDF not ready yet');
    return;
  }
  // Proceed with search
}
```
