### ISSUE TITLE
Failed to construct 'Headers': Invalid name

### ISSUE THREAD

**Issue by wider2** [stephanrauh/ngx-extended-pdf-viewer#2693]
Angular 17 
ngx-extended-pdf-viewer@22.0.1

```
viewer-4.7.701.min.mjs:23  ERROR TypeError: Failed to construct 'Headers': Invalid name
    at PDFNetworkStreamFullRequestReader._onHeadersReceived (
```
I have tried to add custom header but no luck

```html
[httpHeaders]="customHeaders"
```
```ts
  customHeaders = new HttpHeaders({
    'Content-type': 'application/pdf',
    'Authorization': 'Bearer your-token',
    'Custom-Header': 'CustomValue'
  });
```

**Comment by stephanrauh** [comment]
Good question. My showcase never calls `_onHeadersReceived()`, so I can't reproduce the bug. However, the bug occurs in this source code:

```ts
    const responseHeaders = new Headers(fullRequestXhr.getAllResponseHeaders().trim().split(/[\r\n]+/).map(x => {
      const [key, ...val] = x.split(": ");
      return [key, val.join(": ")];
    }));
``` 

Set `[minifiedJSLibraries]="false"`, open `viewer-*.mjs` in the browser's debugger, and add a breakpoint. I bet `fullRequestXhr.getAllResponseHeaders()` returns a weird header, causing `new Header()` to throw an exception.

That, in turn, makes me believe your server configuration causes the bug.

**Comment by wider2** [comment]
yes, breakpoint shows this

length
: 
0
name
: 
"getAllResponseHeaders"
arguments
: 
[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28) at PDFNetworkStreamFullRequestReader._onHeadersReceived (http://localhost:4200/assets/viewer-4.7.701.mjs:10304:29) at NetworkManager.onStateChange (http://localhost:4200/assets/viewer-4.7.701.mjs:10193:22) at XMLHttpRequest.wrapFn (http://localhost:4200/polyfills.js:8569:35) at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8199:171) at http://localhost:4200/main.js:342758:49 at AsyncStackTaggingZoneSpec.onInvokeTask (http://localhost:4200/main.js:342758:30) at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8199:54) at Object.onInvokeTask (http://localhost:4200/main.js:343072:25) at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8199:54) at ZoneImpl.runTask (http://localhost:4200/polyfills.js:7996:39) at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:8276:26) at invokeTask (http://localhost:4200/polyfills.js:8921:12) at globalCallback (http://localhost:4200/polyfills.js:8962:23) at XMLHttpRequest.globalZoneAwareCallback (http://localhost:4200/polyfills.js:8982:12)]

**Comment by stephanrauh** [comment]
That's a bit difficult to decipher. What is it you're showing? Maybe be screenshot of the debugger view helps.

**Comment by wider2** [comment]
i found the solution

const resultBlob = new Blob(chunks, { type: 'application/pdf' });

thats all

**Comment by stephanrauh** [comment]
Ah, I see. You're reading the file from a Blob instead of reading it from the server. I'm glad you've figured it out!
