### ISSUE TITLE
Fails to load PDF when navigating between pages in Ionic Angular

### ISSUE THREAD

**Issue by mozhuilungdsuo** [stephanrauh/ngx-extended-pdf-viewer#2696]
# Bug Report: ngx-extended-pdf-viewer fails to load PDF when navigating between pages in Ionic Angular

## Describe the Bug
When using `ngx-extended-pdf-viewer` in an Ionic Angular project with two pages displaying PDFs (e.g., `/summary` and `/receipt`), the PDF viewer fails to load the document when navigating between these pages.

## Steps to Reproduce
1. Open the "Summary" page that uses `ngx-extended-pdf-viewer` to display a PDF.
2. Navigate to a different route (e.g., "Day", "Month", "Week", or "Year" filters) — the PDF viewer works as expected.
3. Navigate to the "Receipt" page that also uses `ngx-extended-pdf-viewer`.
4. The PDF fails to render.

Similarly:
- If the "Receipt" page is opened first, and then the "Summary" page is visited, the same issue occurs.

## Expected Behavior
The PDF viewer should reload and display the new document correctly, regardless of the navigation history.

## Environment
- **Ionic Angular version:** 8.0.0
- **ngx-extended-pdf-viewer version:** 21.3.2
# Video of issue
- [https://youtube.com/shorts/Razqt9cHiNA](https://youtube.com/shorts/Razqt9cHiNA)

**Comment by mozhuilungdsuo** [comment]
- Console error when pdf is not rendering

<img width="858" alt="Screenshot 2024-12-23 at 12 05 09 PM" src="https://github.com/user-attachments/assets/ff46e246-df92-4f0d-b24e-97f205b60f3c" />

**Comment by mozhuilungdsuo** [comment]
I solved the issue by using a common ionic page to render all my pdf related stuff. Is there any workaround to this? As i want to have a separation of concerns related to my business logic.

**Comment by stephanrauh** [comment]
Usually, adding a short timeout helps. Hide the PDF viewer when the page renders (`@if (showPDF)` or `*ngIf showPDF`) and set the flag after 100-200 milliseconds:
```ts
public ngOnInit() {
  setTimeout(() => this.showPDF = true, 200);
}
```
I don't have a good explanation of your particular bug, but both initializing and destroying the PDF viewer takes some time, and much of it is done asynchronously. Without the timeout, you're both constructing and destroying the viewer simultaneously.

Your error also occurs when the PDF viewer initializes without being visible. In this case, a timeout also can help.

**Comment by stephanrauh** [comment]
If this helps, please tell me so I can safely close this ticket.

**Comment by mozhuilungdsuo** [comment]
@stephanrauh  Yes that helped a lot.  Thanks a lot and awesome package.
