### ISSUE TITLE
It contains meaningless "j" at the source code.

### ISSUE THREAD

**Issue by free270** [stephanrauh/ngx-extended-pdf-viewer#27]
It contains meaningless "j" at  the "/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.html" line 54.

![image](https://user-images.githubusercontent.com/35786822/50865399-eb263180-13e8-11e9-88cf-151f62c6556f.png)

**Comment by stephanrauh** [comment]
Thanks for pointing this out!

And please apologize my delayed answer. I've been moving to another town, and you can imagine how much work this is.
