### ISSUE TITLE
canvasWrapper layer width not fitting to web viewer

### ISSUE THREAD

**Issue by iamrajaraj** [stephanrauh/ngx-extended-pdf-viewer#271]
canvasWrapper layer width is not fitting to web viewer. If you make it as 545px looks pretty good.

**Comment by stephanrauh** [comment]
Mind to explain? What‘s broken? Have you got a screenshot?

**Comment by iamrajaraj** [comment]
Please ignore the width size i suggested above, as its dynamic we can't limit to one.

**But for actual issue please have look into below screen shot**

![image](https://user-images.githubusercontent.com/16011060/79583167-61383e80-80ea-11ea-99eb-d5e2f5c2dbbb.png)

**For debug I just did canvaslayer disable then the text layer look good and fit to web view**
![image](https://user-images.githubusercontent.com/16011060/79583517-d4da4b80-80ea-11ea-8230-094cc294e463.png)

**Comment by stephanrauh** [comment]
I've never seen this bug on my machine. Can you send me a reproducer, please?

**Comment by stephanrauh** [comment]
Let's close the ticket after two weeks of silence. I don't know how to reproduce the bug.

**Comment by PhuocHoangMinhNguyen** [comment]
The smaller the browser width, the more content will be hidden (as image below). How can I manipulate the width of the canvas?
![image](https://user-images.githubusercontent.com/54832887/230255180-cfcc98b3-66f4-4f52-b670-5b927df16164.png)
![image](https://user-images.githubusercontent.com/54832887/230255308-9cf4a7c7-ea01-4817-b498-44e75902e200.png)
![image](https://user-images.githubusercontent.com/54832887/230255434-3b0e13bf-4b19-45f1-af46-81ca2c79b9d2.png)
