### ISSUE TITLE
Broken view - viewer cutting spaces & mess characters

### ISSUE THREAD

**Issue by chenZafrir** [stephanrauh/ngx-extended-pdf-viewer#272]
I use angular 8,
The problem is at follows - the viewer shows the PDF like this:
![problem1](https://user-images.githubusercontent.com/25902373/79752822-8f519480-831d-11ea-9dd9-881eab244c57.jpg)

while the original PDF look like this:
![image](https://user-images.githubusercontent.com/25902373/79752954-c758d780-831d-11ea-8c7c-dffc246cb042.png)

It happens in chrome and edge browsers.
When downloading the PDF to local storage using the viewer - the pdf look good.
the code is as follows:
`<ngx-extended-pdf-viewer language="he" [src]="'assets/tlush.pdf'" useBrowserLocale="true" height="100vh"></ngx-extended-pdf-viewer>`

**Comment by stephanrauh** [comment]
This reminds me of #208. Are you using a current version of ngx-extended-pdf-viewer? Is the CMAP folder copied your `dist/assets/cmaps` folder?

**Comment by stephanrauh** [comment]
@chenZafrir Did my hint help you?

**Comment by chenZafrir** [comment]
@stephanrauh I use version 3.2.1 and I can see that there is a "cmaps" folder inside node_modules\ngx-extended-pdf-viewer\assets. Is this what you mean?

**Comment by stephanrauh** [comment]
Yes. When you run a `ng build`, this folder should be copied to the dist folder, so the PDF reader can access it at runtime.

As far as I know, it's only necessary for a couple of East Asian languages.

Maybe you can also ask @leo6104 who helped me to solve the original bug.

**Comment by chenZafrir** [comment]
After running ng build I can see the cmaps folder copied to dist\assets\cmaps successfully.
I tried varied PDF files and it happens in all of them.

**Comment by chenZafrir** [comment]
@stephanrauh 
The problem solved by removing the following css:
```
*{
	outline: none;
	direction: rtl;
}
```

**Comment by stephanrauh** [comment]
Glad you've found it! Just to be sure: this CSS code isn't part of ngx-extended-pdf-viewer, correct? At least, I didn't find it, so I assume it's part of your application (or your CSS framework).

**Comment by chenZafrir** [comment]
> Glad you've found it! Just to be sure: this CSS code isn't part of ngx-extended-pdf-viewer, correct? At least, I didn't find it, so I assume it's part of your application (or your CSS framework).

That's correct :)
