### ISSUE TITLE
Question: Zoom Rendering

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#273]
Is there a way to know after clicking on zoom in or out, to know when all the pages have finished rendering?

The reason is that on mobile, when user taps multiple time quickly on zoom in, at times we get some change detection errors. So we are trying to find a way to prevent this. Thanks!

**Comment by stephanrauh** [comment]
I think so. There are the events `(pageRendered)` and `(textLayerRendered)`.

The problem with `(pageRendered)` is that it fires each time a page is rendered. It doesn't wait until every page is rendered. On the other hand, I suspect PDF.js doesn't render every page. I guess (without being sure) that it's using a clever lazy rendering algorithm.

**Comment by pedrojrivera** [comment]
Ok. Thanks...I'll test that and see. 
In the meantime we added debounce to our toolbar buttons click events to prevent emitter "overload"

**Comment by stephanrauh** [comment]
I'll close the ticket for the moment. Nonetheless, I'd like to hear from you when you've solved the bug or failed to do so.

Best regards,
Stephan

**Comment by pedrojrivera** [comment]
@stephanrauh We were able to solve the issue. Here is the code we used to solve the random mobile errors by only permitting another zoom only when the previous request has completed. 

FYI, we built our own custom toolbar because our app is using material design principles. 

We have stress tested this solution and seems to work perfectly.

```
  private _pageRendered: boolean;
  ...
  onPageRendered(_event: PagesLoadedEvent) {
    this._pageRendered = true;
  }
  ...
  /**
   * Zoom in on the document using the toolbar button
   */
  onZoomIn() {
    // 1000% is the max pfdjs permits
    if (this._zoom === '1000') {
      return;
    }
    if (this._pageRendered) {
      this._pageRendered = false;
      this._eventBus.dispatch('zoomin');
    }
  }

  /**
   * Zoom out on the document using the toolbar button
   */
  onZoomOut() {
    // 10% is the min pfdjs permits
    if (this._zoom === '10') {
      return;
    }
    if (this._pageRendered) {
      this._pageRendered = false;
      this._eventBus.dispatch('zoomout');
    }
  }
...
```

<img width="713" alt="pdf-viewer" src="https://user-images.githubusercontent.com/32545483/79974337-26763380-8467-11ea-85c1-f4bb16210566.png">

**Comment by stephanrauh** [comment]
The source code look surprisingly simple and elegant. Nice! I wonder if I should add this to the documentation, or even to the library itself. If you've got an idea what a useful showcase page might look like, just tell me (or send me a pull request).

**Comment by stephanrauh** [comment]
As for the custom toolbar: it looks great. Can I talk you into contributing it to the showcase as a demo? It'd be an excellent addition to https://pdfviewer.net/custom-toolbar.

The showcase runs on Angular Material, so chances are you can even use the dropdown widgets without having to change a lot.

**Comment by pedrojrivera** [comment]
Let me see how I could do that as our custom toolbar is a separate component. It's not using your custom toolbar implementation because we had built our version before version 2 had come out.

Because of that we had to basically turn off the pdfjs toolbar and also hide some other pdfjs elements that we didn't want like the progress bar, etc.

But briefly the way we do it is that in our custom viewer component we incorporate both the toolbar and the ngx-pdf-viewer. Then in the toolbar component we control actions by way of bindings and emitters.

```
<app-pdf-viewer-toolbar>
    [pdfData]="pdfData"
    [renderTextLayer]="renderTextLayer"
    [renderPrintButton]="renderPrintbutton"
    [renderDownloadButton]="renderDownloadButton"
    [(showSearch)]="showSearch"
    [(handTool)]="handTool"
    [(textSelectionTool)]="textSelectionTool"
    [(zoom)]="zoom"
    ...
    ...
</app-pdf-viewer-toolbar>

<ngx-extended-pdf-viewer
      [delayFirstView]="200"
      [base64Src]="document"
      [language]="language"
      useBrowserLocale="false"
      height="initial"
      logLevel="0"
      ...
      ...
</ngx-extended-pdf-viewer>
```
