### ISSUE TITLE
ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by Prasanth-FrontendDeveloper** [stephanrauh/ngx-extended-pdf-viewer#274]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple? **No**

**Describe the bug**
I have been loading the data using base64 in the property of [base64Src], the data gets loaded correctly but I'm getting this error. **' ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.'**

**Version info**
- Version of ngx-extended-pdf-viewer - 3.0.0.
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files) - **"scripts": [
"node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
"node_modules/ngx-extended-pdf-viewer/assets/viewer.js",
"node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js" ]**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - **chrome**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**
![IMG_20200421_213227](https://user-images.githubusercontent.com/61708858/79887140-df148680-8417-11ea-9649-60d873a6afd3.png)

**Additional context**

**Comment by stephanrauh** [comment]
Looks like this error: https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings

However, with so little information, I don't have a clue how to help you. I suppose the error does not happen when you display the "lorem ipsum" PDF file?

**Comment by Prasanth-FrontendDeveloper** [comment]
Please let me know what information do you need from my end.

**Comment by Prasanth-FrontendDeveloper** [comment]
Please let me know what information do you need from my end.
This error is exactly happening while displaying the PDF file or I'm getting this error by using this attribute **[base64Src]**  . Not only for this pdf file, for all the pdf files getting the same error.
<ngx-extended-pdf-viewer
            [base64Src]="base64"
            [useBrowserLocale]="true"
            [contextMenuAllowed]="false"
            [showDownloadButton]="false"
            [showBookmarkButton]="false"
            [showOpenFileButton]="false"
            [textLayer]="false"
            [showPrintButton]="false"
            [showHandToolButton]="false"
            [height]="'65vh'">
            </ngx-extended-pdf-viewer>
[TestPDF-1.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4512003/TestPDF-1.pdf)

**Comment by stephanrauh** [comment]
OK, now I'm looking a bit less puzzled. The PDF file you've attached is a regular PDF file. It's not encoded as a base64 file. So why are you using the `[base64Src]` attribute? Is there some process concerting the file to a base64 encoded string? If so, can you send me the base64 encoded string, too?

**Comment by Prasanth-FrontendDeveloper** [comment]
While uploading I'm using this TestPDF-1.pdf but viewing the file I will get a response as base64 format only.

**Comment by Prasanth-FrontendDeveloper** [comment]
base64 encoded string:

[Base64Data.docx](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4512269/Base64Data.docx)

**Comment by stephanrauh** [comment]
You're saving a simple text file as *.docx? My copy of word refused to open it, so I was stuck until I tried to open it with VS code. :)

If I'm not mistaken, the file contains several carriage returns (e.g. `\n`or even `\n\r`). It's possible that the PDF viewer can't cope with these CRs.

**Comment by stephanrauh** [comment]
I just copied your Base64 string into the default demo of ngx-extended-pdf-viewer (i.e. into this file: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/src/app/pdfBase64.ts). The PDF file opens without error. The suspected CRs don't seem to have any negative effect.

In other words: I can't reproduce your bug.

**Comment by stephanrauh** [comment]
I've pushed the change to GitHub so you can clone the repository and check if it works on your machine. When you do so, you have to run ´npm run win-package` or `npm run unix-package` once to compile the latest version of the PDF viewer. After that, it's a regular Angular CLI project, so you can start it with `ng s -o`.

**Comment by Prasanth-FrontendDeveloper** [comment]
@stephanrauh Thank you for checking from your end. I cloned the repo and checked from my end there is no error. And then I updated the vendor.js to 1.0.4 the issue I faced, now it's solved after updating the vendor.js. **Note: Is there any way or any library to view the doc file and ppt file also it should not allow the context menu it will be very useful.**

**Comment by stephanrauh** [comment]
That's great news!

As for the context menu: just add `[contextMenuAllowed]="false"`.

**Comment by stephanrauh** [comment]
As for Powerpoint and Word: you need a different tool for that. All I can do for you is googling, but I guess that's not much help. :)

Best regards,
Stephan
