### ISSUE TITLE
Some texts missing in pdf viewer, but not in native browser

### ISSUE THREAD

**Issue by limcheepei** [stephanrauh/ngx-extended-pdf-viewer#275]
Refer to the attached PDF document, texts that are overlay (names, signature, date fields) are missing when viewing thru pdf viewer. However, when viewing thru Chrome (as native), the texts appear.

**Version info**
- Version of ngx-extended-pdf-viewer is 1.7.5

**Desktop (please complete the following information):**
 - Windows 7
 - Browser: Chrome 80.0.3987.163

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

[sample.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4513573/sample.pdf)

**Comment by stephanrauh** [comment]
I'm pretty sure that same happens on https://mozilla.github.io/pdf.js/es5/web/viewer.html. Please test your document there. 

Mozilla's PDF viewer doesn't implement the entire set of annotations. I guess that's the problem you've run into.

As for the signature: you can activate `[showUnverifiedSignatures]="true"`. But use it at your own risk. The signatures are displayed though they aren't verified. In other words: it's possible you might display a forged signature.

**Comment by stephanrauh** [comment]
I haven't heard from for for more  than a week, so I suppose I can close the issue. As mentioned above, I believe the Mozilla team can solve the bug, not me.

**Comment by rajatmittal** [comment]
Some text missing while getting PDF file in ngx-extended-pdf-viewer, getting this issue in IE11.
While some files are displaying fine.

**Comment by stephanrauh** [comment]
I've dropped IE11 support, at least officially. If you send me a broken PDF file, I'll happily start debugging. But I can't promise anything - debugging pdf.js in IE11 is a pain in the, well, you know where. BTW, it's a good idea to open a new issue because your issue seems to be IE11 specific.

**Comment by robotestyukon** [comment]
Hi,
using ngx-extended pdf viewer(14.0.5) in angular application where the text in pdf is getting blurred or sometimes not rendering properly in chromium browsers(chrome,edge,etc) 
attached the screenshot and the pdf url https://moneyandme.pgimindiamf.com/api/v1/portal/pdf/PDF_2118943213 for reference.
![image](https://user-images.githubusercontent.com/123447793/214240833-42bd4406-496e-419a-af2f-689c4e1fbf1c.png)

 url to access : https://moneyandme.pgimindiamf.com/household-budget/articles/4-Steps-to-Financial-Wellbeing
 
 Please provide solution for this.

**Comment by stephanrauh** [comment]
@robotestyukon Currently, I'm using your PDF as the default demo of my local copy of the showcase. I didn't see problems yet, but I'm observing it for a couple of days.

BTW, it's better to open a new ticket, otherwise I'll never find your comment again. Also, I believe this is a bug of the base viewer. Please check if the problem also occurs on https://mozilla.github.io/pdf.js/web/viewer.html. If so, please open a ticket at Mozilla's repository.
