### ISSUE TITLE
Toolbar buttons in secondary toolbar

### ISSUE THREAD

**Issue by Seharad** [stephanrauh/ngx-extended-pdf-viewer#276]
Although 'showSecondaryToolbarButton' is set to false, buttons on the first toolbar are moved to the second toolbar on narrow screens and disappear into nothing.

**Comment by stephanrauh** [comment]
Yes. That's the intended behavior. If there's not enough space to display the buttons, there's no point in displaying them. Otherwise, the layout of the toolbar is broken.

If you prefer to modify this behavior, I suggest using a custom toolbar.
