### ISSUE TITLE
Message: PDFDocument: stream must have data

### ISSUE THREAD

**Issue by avarndell** [stephanrauh/ngx-extended-pdf-viewer#28]
getting the above message when getting the Uint8Array of the pdf.  Does the src support this?

**Comment by stephanrauh** [comment]
Difficult to say. That's one of the badly documented parts of Mozilla's PDF viewer. Uint8Array does ring a bell, so chances are I've already fought the same error, too.

We've managed to display a PDF file we've received as a `Blob` using this function:

```html
<ngx-extended-pdf-viewer [src]="URL.createObjectURL(someBlob)">
</ngx-extended-pdf-viewer>
````

I suppose it's easy to convert your int array to such a `Blob` or to a data URL.

Hope that helps! (and please report back, so other developers benefit from your experience)
Stephan

**Comment by stephanrauh** [comment]
@avarndell  Dear Anette,

you've closed this ticket. More likely than not, this means you've solve the issue. Would you mind to give us a clue what the trick is? Your story may help another programmer. Plus, it gives me the opportunity to improve the documentation or the library.

Thanks in advance,
Stephan
