### ISSUE TITLE
onPagesLoaded and onPageRendered firing too early

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#283]
I don't know exactly how to explain so I am attaching a screen video so you can see.

We recieve a pdf as base64 content, then the pdf-viewer fires the onPagesLoaded but the document hasn't fully loaded from the server. So what happens is that a blank page is displayed with a page count of 1.

Once the document has been fully received it fires onPagesLoaded and onPageRendered again and I see the expected document correctly.

package.json
=========
    "ngx-extended-pdf-viewer": "^3.2.3",
    "@angular/core": "^9.1.3",

[large_pdf.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4541303/large_pdf.zip)

**Comment by stephanrauh** [comment]
That's something caused by the base PDF viewer, so I guess you should report the issue here: https://github.com/mozilla/pdf.js/issues

However, I don't think it's a bug. Maybe I didn't document `(pagesLoaded)` correctly. What is the value of `$event`? It's a bit weird that `(pageRendered)` is fired so early. Again, what's the value of `$event`?

I suppose you're observing the result of the asynchronous processing of pdf.js - although I have to admit the result looks a bit odd in your video.

**Comment by pedrojrivera** [comment]
I don't know if this is everything you need, but I attached a document with the console log and event values.

Let me know if I need to provide you with anything else.  Thanks!

[Console.log](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4542096/Console.log)

**Comment by stephanrauh** [comment]
Does your server support range requests? I'm not sure, but that might help you.

**Comment by pedrojrivera** [comment]
@stephanrauh Just wanted to give you an update on how we solved the issue.

First we noticed the premature firing of the events when loading large pdf documents from our server that are made up mostly scanned documents. Since the server sends the data across as binary data, it could take a few seconds to fully load. 

**Our Solution:**
We implemented an http interceptor to track when requests have fully loaded the content. A typical loaderInterceptor that will turn on or off a progress bar on the screen. The loading progress bar will only go away once the content is fully loaded and the onPagesLoaded() has fired. Works very well. 

It was inspired by this site:

https://medium.com/@zeljkoradic/loader-bar-on-every-http-request-in-angular-6-60d8572a21a9

The user experience and the screen flow is very acceptable as now the user visually can see when the document is ready to be interacted with.

Hopefully this could help anyone else who may be experiencing the same problem.

**Comment by stephanrauh** [comment]
@pedrojrivera Thanks for the update! I'll keep the ticket open until I've read the link and made up my mind whether and how to document it.

FWIW, I was still trying to reproduce the scenario. I suspected large documents had to do something with it, but even with my big documents, everything look fine enough. I'm glad you've managed to find the cause and to apply a workaround!

BTW: if you haven't done so, check the range request bit. I'm not 100% sure, but range requests have specifically been invented to display huge documents quickly, so they might help you.
