### ISSUE TITLE
Use custom components instead of defined by <ngx-extended-pdf-viewer>

### ISSUE THREAD

**Issue by portah** [stephanrauh/ngx-extended-pdf-viewer#287]
It's tough to explain, because I have not come up with a solution. I can provide example end explain the inconvenience and maybe together we could find out something. But first, a big thank you for the library it is very helpful.

There are libraries like angular materials out there one of them https://clarity.design/.
 And sometimes there is a way to use provided css but sometimes not. So for instance, menu has transformed into the code:
```html
    <div class="pdf-nav" fxLayout="row" fxLayoutGap="10px" fxFlex="51px;">

      <button class="btn btn-icon btn-link" (click)="pdfsidenav.toggle()" title="Toggle Sidebar" tabindex="11" data-l10n-id="toggle_sidebar">
        <clr-icon shape="bars"></clr-icon>
      </button>
      <button id="viewFind" class="btn btn-icon btn-link" title="Find in Document" tabindex="12" data-l10n-id="findbar">
        <clr-icon shape="search"></clr-icon>
      </button>
      <div fxFlex>&nbsp;</div>
      <div>&nbsp;</div>
      <button id="firstPage" class="btn btn-icon btn-link hiddenSmallView" title="Go to First Page" tabindex="56" data-l10n-id="first_page">
        <clr-icon shape="step-forward-2 down"></clr-icon>
      </button>

      <!-- <button class="pageUp btn btn-icon btn-link" title="Previous Page" id="previous" tabindex="13" data-l10n-id="previous">
              <clr-icon shape="caret left"></clr-icon>
          </button>
          <button class="pageDown btn btn-icon btn-link" title="Next Page" id="next" tabindex="14" data-l10n-id="next">
              <clr-icon id="next" shape="caret right"></clr-icon>
          </button> -->
      <div fxLayout="row" class="pages">
        <input clrInput type="number" id="pageNumber" placeholder="Page" value="1" size="5" min="1" tabindex="15" data-l10n-id="page">
        &nbsp;
        <div style="white-space: nowrap; margin-top: 0.2rem;">of {{bookData?.numPages}}</div>
        <!-- <div id="numPages" style="white-space: nowrap; margin-top: 0.2rem;"></div> -->
      </div>

      <button id="lastPage" class="btn btn-icon btn-link hiddenSmallView" title="Go to Last Page" tabindex="57" data-l10n-id="last_page">
        <clr-icon shape="step-forward-2"></clr-icon>
      </button>
      <div fxFlex>&nbsp;</div>
      <button id="zoomOut" class="btn btn-icon btn-link" title="Zoom Out" tabindex="21" data-l10n-id="zoom_out">
        <clr-icon shape="zoom-out"></clr-icon>
      </button>
      <button id="zoomIn" class="btn btn-icon btn-link" title="Zoom In" tabindex="22" data-l10n-id="zoom_in">
        <clr-icon shape="zoom-in"></clr-icon>
      </button>
      <div class="hiddenSmallView">
        <select id="scaleSelect" clrSelect title="Zoom" tabindex="23" data-l10n-id="zoom" (change)="zoomChanged($event)">
          <option id="pageAutoOption" title="" value="auto" selected="selected" data-l10n-id="page_scale_auto">Automatic</option>
          <option id="pageActualOption" title="" value="page-actual" data-l10n-id="page_scale_actual">Actual Size</option>
          <option id="pageFitOption" title="" value="page-fit" data-l10n-id="page_scale_fit">Page Fit</option>
          <option id="pageWidthOption" title="" value="page-width" data-l10n-id="page_scale_width">Page Width</option>
          <option id="customScaleOption" title="" value="custom" disabled="disabled" hidden="true"></option>
          <option title="" value="0.5" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 50 }'>50%</option>
          <option title="" value="0.75" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 75 }'>75%</option>
          <option title="" value="1" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 100 }'>100%</option>
          <option title="" value="1.25" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 125 }'>125%</option>
          <option title="" value="1.5" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 150 }'>150%</option>
          <option title="" value="2" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 200 }'>200%</option>
          <option title="" value="3" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 300 }'>300%</option>
          <option title="" value="4" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 400 }'>400%</option>
        </select>
      </div>


      <!-- <div fxLayout="row" fxFlex.gt-md class="find">
          <input clrInput type="text" autocomplete="off" id="findInput" title="Find" placeholder="Find in document…" tabindex="91" data-l10n-id="find_input">
          <button id="findPrevious" class="btn btn-icon btn-link" title="Find the previous occurrence of the phrase" tabindex="92" data-l10n-id="find_previous">
            <clr-icon shape="rewind"></clr-icon>
          </button>
          <button id="findNext" class="btn btn-icon btn-link" title="Find the next occurrence of the phrase" tabindex="93" data-l10n-id="find_next">
            <clr-icon shape="fast-forward"></clr-icon>
          </button>
        </div> -->

      <div fxFlex></div>

      <button class="hiddenSmallView btn btn-icon btn-link" title="Switch to Full Screen" tabindex="31" (click)="fullscreen()">
        <clr-icon shape="resize-up"></clr-icon>
      </button>

      <button id="print" class="hiddenSmallView hiddenMediumView btn btn-icon btn-link" title="Print" tabindex="33" data-l10n-id="print">
        <clr-icon shape="printer"></clr-icon>
      </button>

      <button id="download" class="hiddenSmallView hiddenMediumView btn btn-icon btn-link" title="Download" tabindex="34" data-l10n-id="download">
        <clr-icon shape="download"></clr-icon>
      </button>

      <button (click)="bookmarkAdd(viewBookmark.href)" class="bookmark btn btn-icon btn-link" title="Current view (copy or open in new window)" tabindex="35" data-l10n-id="bookmark">
        <clr-icon shape="bookmark"></clr-icon>
        <a #viewBookmark id="viewBookmark" class="bookmark hidden"></a>
      </button>
      <!-- <div class="verticalToolbarSeparator hiddenSmallView"></div> -->
      <button id="secondaryToolbarToggle" title="Tools" class="btn btn-icon btn-link" tabindex="36" data-l10n-id="tools">
        <clr-icon shape="ellipsis-vertical"></clr-icon>
      </button>
      <div>&nbsp;</div>
    </div> <!-- menu done -->

```

When I used this code in the way suggested 
```
<pdf-toolbar custom content: [customToolbar]  >
```

To clarity styles, yours or pdfjs styles were applied.

So the easiest way to deal with custom menu/side nav right now is to add navigation with ID like in viewer.

<img width="1011" alt="Screen Shot 2020-05-06 at 4 40 17 PM" src="https://user-images.githubusercontent.com/2335092/81226176-69ccb800-8fb8-11ea-8246-1a31e65a80cd.png">

Almost the same work was done to make a native material side nav

```html
 <mat-sidenav #pdfsidenav mode="over" (opened)="sideBarOpened()" (closed)="sideBarClosed()">

    <div class="pdf-nav" fxLayout="row" fxLayoutGap="10px">
      <div>&nbsp;</div>
      <button id="viewThumbnail" class="btn btn-icon btn-link" title="Show Thumbnails" tabindex="2">
        <clr-icon shape="view-cards"></clr-icon>
      </button>
      <button id="viewOutline" class="btn btn-icon btn-link" title="Show Document Outline (double-click to expand/collapse all items)" tabindex="3">
        <clr-icon shape="view-list"></clr-icon>
      </button>
      <button id="viewAttachments" class="btn btn-icon btn-link" title="Show Attachments">
        <clr-icon shape="bars"></clr-icon>
      </button>
      <div fxFlex>&nbsp;</div>
      <button (click)="pdfsidenav.close()" class="btn btn-icon btn-link" title="Close menu">
        <clr-icon shape="close"></clr-icon>
      </button>
    </div>
    <div id="sidebarContent" style="top: 49px;">
      <div id="thumbnailView" style="width: 100%; height: 100%;">
      </div>
      <div id="outlineView" class="hidden">
      </div>
      <div id="attachmentsView" class="hidden">
      </div>
    </div>
  </mat-sidenav>
```

<img width="1012" alt="Screen Shot 2020-05-06 at 4 40 38 PM" src="https://user-images.githubusercontent.com/2335092/81226178-69ccb800-8fb8-11ea-9d53-441b490e31a9.png">

I have not upload my project to github yet (extremely pre pre initial work) to give better example, but I will.

Is it possible to utilize angular directives to apply pdfjs properties like an idea, so instead of using `<pdf-zoom-toolbar >` we use `scaleSelect` directive which would apply required properties? Or your goal is to give ngForm properties, for all the events, so ppl could attach whatever they want?

```html
<select scaleSelect clrSelect title="Zoom" tabindex="23" data-l10n-id="zoom" (change)="zoomChanged($event)">
          <option id="pageAutoOption" title="" value="auto" selected="selected" data-l10n-id="page_scale_auto">Automatic</option>
          <option id="pageActualOption" title="" value="page-actual" data-l10n-id="page_scale_actual">Actual Size</option>
          <option id="pageFitOption" title="" value="page-fit" data-l10n-id="page_scale_fit">Page Fit</option>
          <option id="pageWidthOption" title="" value="page-width" data-l10n-id="page_scale_width">Page Width</option>
          <option id="customScaleOption" title="" value="custom" disabled="disabled" hidden="true"></option>
          <option title="" value="0.5" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 50 }'>50%</option>
          <option title="" value="0.75" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 75 }'>75%</option>
          <option title="" value="1" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 100 }'>100%</option>
          <option title="" value="1.25" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 125 }'>125%</option>
          <option title="" value="1.5" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 150 }'>150%</option>
          <option title="" value="2" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 200 }'>200%</option>
          <option title="" value="3" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 300 }'>300%</option>
          <option title="" value="4" data-l10n-id="page_scale_percent" data-l10n-args='{ "scale": 400 }'>400%</option>
        </select>
```

**Comment by stephanrauh** [comment]
Wait - you've managed to replace the standard sidebar by your custom toolbar? Render me impressed! You know, allowing for a custom sidebar is high on my list, second only to fixing bugs... but there's always a bug, so there's little progress with respect to new features. :)

**Comment by portah** [comment]
For side nav you have to change code too, not just html.
Maybe it will be better if I upload my project on github to give you links and whole repository. W8 couple mins

**Comment by stephanrauh** [comment]
If I get you right, your question is the last paragraph. In general, I like the idea. Let me ponder about it. Maybe you're right, using directives instead of components might make the design more flexible.

On the other side, I assumed most people want to modify the toolbar more radically. The directive approach makes it easier to apply new face paint (aka custom CSS). Is that the reason why you'd prefer directives over components?

Come to think of it, maybe we can use both. `<pdf-zoom-toolbar>` is a building block you can use or drop. However, if you're using it, it contains a standard `<select>` tag powered by an Angular directive. Would such an approach help you?

**Comment by stephanrauh** [comment]
Don't hurry - here in Germany it's close to midnight, so I'm afraid I won't manage to review your code today. :)

**Comment by stephanrauh** [comment]
Just one thought: whatever we do, I'd like to avoid breaking changes. They are not taboo - this is JavaScript, not Java! - but I don't want to frustrate any diligent developer who's just doing their work. If there's a breaking change, I want developers to rejoice because it opens new opportunities. 

Of course, that's a goal I'll never reach - but you get the idea. Any breaking change should be worth the pain.

**Comment by portah** [comment]
I do not like my solution for zoom. When I use this pdfjs's IDes pdfjs replaces text. So I have "automatic" it adds "Automatic Zoom". I just found your solution https://pdfviewer.net/zoom here, maybe this approach is the right one. Directives I believe could add ID property to a component and pdfjs would do the rest.

**Comment by portah** [comment]
And here is the file component that shows pdf-viewer https://github.com/portah/librarian/tree/master/src/app/BookView

**Comment by stephanrauh** [comment]
Yeah, replacing stuff is easier than modifying existing stuff. That's why I suggested the approach sketched in https://pdfviewer.net/custom-toolbar in the first place. Under the hood, the "zoom" demo simply uses the `[zoom]` property.

Several components are hard-wired by pdf.js. So they're hard to change. The zoom drop-down is one of them. But with current versions of ngx-extended-pdf-viewer, that should be a problem of the past. If you replace the default zoom by your own component, there's simply an invisible dummy zoom that doesn't do anything.

**Comment by stephanrauh** [comment]
Does your librarian project require a backend? Or can I simply clone and run it without further ado?

**Comment by portah** [comment]
It requires back-end, and it is in https://github.com/portah/librarian/tree/master/api

you have to install 'meteor' from https://www.meteor.com/install just run `curl https://install.meteor.com/ | sh` (linux, macos), then packages to install in `api` dir. and then npm run api

**Comment by portah** [comment]
Ah, also, in `api` dir make `private` dir and put config file `settings.json` 

```json
{
  "walkingDirs": ["/path/to/pdfs"],
  "extensions": [".pdf", ".epub"],
  "cors_package": true
}

```

**Comment by portah** [comment]
And the last part in `api` in `package.json` either remove `MONGO_URL=mongodb://localhost:27017/bookstorage` then meteor will use internal mongodb or change the url :)
Probably that is it to start the project :)

**Comment by portah** [comment]
On second thought, maybe not directives but something like here https://github.com/angular/components/tree/master/src/material/sidenav. Like if no `mat-sidenav-content` provided then dummy https://github.com/angular/components/blob/master/src/material/sidenav/sidenav-container.html

**Comment by stephanrauh** [comment]
Is there anything I should do in this ticket? I'm closing it now because I haven't heard from you since a while.

**Comment by portah** [comment]
I'm still here :) I thought you would like to add angular's sidebar. So were just waiting for questions.

**Comment by stephanrauh** [comment]
I'm afraid I've lost it after this long thread... would you mind to summarize your idea in a few lines again?

**Comment by stephanrauh** [comment]
The more successful the library get, the faster new issues are opened. In other words: I've given up hope to solve this ticket any time soon. Please apologize me closing this ticket. No insult intended: I know this thread has a lot of useful insight, so I'm closing it reluctantly!
