### ISSUE TITLE
Background color cannot be set to white

### ISSUE THREAD

**Issue by BerendWouters** [stephanrauh/ngx-extended-pdf-viewer#29]
When trying to set the backgroundColor to "#fff" (or alike), it's not being applied. However, when trying other combinations, the color is being applied correctly.

**Comment by stephanrauh** [comment]
Ahem. That sounds surprising. You cannot set the background color to white, but pink does work?

**Comment by stephanrauh** [comment]
Incredible. It seems to be true. #fefefe works, but #ffffff is ignored. No idea what's going on.

**Comment by stephanrauh** [comment]
I've published ngx-extended-pdf-viewer 0.9.22, which *should* solve the problem. However, I'm still trying to understand what's going on, so maybe there are unexpected side-effects.
