### ISSUE TITLE
Error when I tried to add Hand Tool and Select Tool to custom toolbar

### ISSUE THREAD

**Issue by belp-blg** [stephanrauh/ngx-extended-pdf-viewer#290]
```
<ngx-extended-pdf-viewer
  #pdfViewer
  [customToolbar]="additionalButtons"
  [src]="pdfSrc"
  [height]="'86vh'"
  [useBrowserLocale]="true"
  [textLayer]="true">
</ngx-extended-pdf-viewer>

<ng-template #additionalButtons>
  <div id="toolbarViewer">
    <div id="toolbarViewerLeft">
      <pdf-toggle-sidebar></pdf-toggle-sidebar>
      <div class="toolbarButtonSpacer"></div>
      <pdf-find-button [showFindButton]="true" [textLayer]="true"></pdf-find-button>
      <pdf-paging-area></pdf-paging-area>
    </div>
    <div id="toolbarViewerRight">


      <pdf-hand-tool></pdf-hand-tool>
      <pdf-select-tool></pdf-select-tool> 

     
      <pdf-open-file></pdf-open-file>
      <pdf-presentation-mode></pdf-presentation-mode>
      <pdf-print></pdf-print>
      <pdf-download></pdf-download>
      <pdf-bookmark></pdf-bookmark>
      <div class="verticalToolbarSeparator hiddenSmallView"></div>
      <pdf-toggle-secondary-toolbar></pdf-toggle-secondary-toolbar>
    </div>
    <pdf-zoom-toolbar ></pdf-zoom-toolbar>
  </div>
</ng-template>
```
I've got error message:

> 'pdf-hand-tool' is not a known element:
> 1. If 'pdf-hand-tool' is an Angular component, then verify that it is part of this module.
> 2. If 'pdf-hand-tool' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>     </div>
>     <div id="toolbarViewerRight">
>       [ERROR ->]<pdf-hand-tool></pdf-hand-tool>
>       <pdf-select-tool></pdf-select-tool>

But parameter **[showHandToolButton]="true"** works perfectly for the standard layout.

**Comment by stephanrauh** [comment]
Please try again with version 3.3.0. I've forgotten to add the two components to the public API.

**Comment by belp-blg** [comment]
I've just tried with version 3.3.0 and have got the same error.

**Comment by stephanrauh** [comment]
Right you are. That's what you get from trying to publish a bug fix during a hurried lunch break. :)

Please try version 3.3.1. It fixes the bug. This time for real.

Best regards,
Stephan

**Comment by belp-blg** [comment]
Fixed. Thank you. :)
