### ISSUE TITLE
Right margin and lower margin in the print preview

### ISSUE THREAD

**Issue by ExeRamirez** [stephanrauh/ngx-extended-pdf-viewer#291]
Hi! Thanks for this great job! I only have one problem

**Checks**
- [X] Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- [X] Does the bug also happen on https://pdfviewer.net/simple?

**Bug**
Print Preview adds a right margin and a lower margin on all documents and with any sheet setting.

**Version info**
- Version of ngx-extended-pdf-viewer: 3.2.7

**Desktop**
 - OS: Windows 10 Pro v1909
 - Browser: Chrome
 - Version:  81.0.4044.138

**Screenshots**
![image](https://user-images.githubusercontent.com/42702570/81766899-774cdb00-94ad-11ea-8a00-00ae19203508.png)

**Comment by stephanrauh** [comment]
Which CSS framework are you using? This bug is usually caused by side-effects of your CSS code. For example, Bootstrap causes a border that looks pretty much like your screenshot. Also see https://pdfviewer.net/troubleshooting.

**Comment by stephanrauh** [comment]
Here's a selection of useful issues: #143, #148 and #175. As far as I remember, there are even more issues, but I guess that should give you a headstart to solve the problem.

**Comment by ExeRamirez** [comment]
> Which CSS framework are you using? This bug is usually caused by side-effects of your CSS code. For example, Bootstrap causes a border that looks pretty much like your screenshot. Also see https://pdfviewer.net/troubleshooting.

Thanks! Solved with [https://pdfviewer.net/troubleshooting](url) **printing (aka: compatibility to Bootstrap and other CSS frameworks)** :
![image](https://user-images.githubusercontent.com/42702570/81862484-2d610500-9540-11ea-800b-51ec08f9addc.png)

**Comment by stephanrauh** [comment]
That's great news! Thanks for reaching out and telling me your success story!

Best regards,
Stephan
