### ISSUE TITLE
Show Rotate Buttons in the Custom Toolbar -> toolbarViewerRight

### ISSUE THREAD

**Issue by ExeRamirez** [stephanrauh/ngx-extended-pdf-viewer#292]
Hi!

In the Custom Toolbar (toolbarViewerRight) not exist the possibility to show the rotate buttons.

For example, to print or download I can use:
![image](https://user-images.githubusercontent.com/42702570/81848796-0ac4f100-952c-11ea-9f5f-782a97067453.png)

So... Will it be possible to add ![image](https://user-images.githubusercontent.com/42702570/81848641-cc2f3680-952b-11ea-90db-0431cdb43281.png)?

Thanks!

**Comment by stephanrauh** [comment]
The component is called ` <pdf-rotate-page>`. As far as I can see, it's already there. Can you double-check this, please?

**Comment by ExeRamirez** [comment]
oh, i didn't know, sorry! Thanks for the indication, it works!
