### ISSUE TITLE
Feature: Remove the top bar

### ISSUE THREAD

**Issue by BerendWouters** [stephanrauh/ngx-extended-pdf-viewer#30]
When all functionalities have been set to false, the top bar remains visible. This is a weird effect, because now only an empty top bar is visible, which serves no purpose.

It seems overriding this in CSS would be a solution, yet this is not possible due to inline styles.

**Comment by stephanrauh** [comment]
First of all: sorry for answering late. I was moving to another town during the last couple of months. That left little time for open source.

You're right. Deactivating every functionality wasn't the use-case I wrote the library for. That's the explanation why it's ill supported. But not that you say it, my library definitely should support it.

Consider it done with one of the next releases!

**Comment by stephanrauh** [comment]
Should be solved by now.

**Comment by BerendWouters** [comment]
We actually stopped using the pdf-viewer, but I'll verify it somewhere later this week anyway :)

**Comment by stephanrauh** [comment]
@BerendWouters You seem to have long weeks. :) Never mind, I'll close the ticket now.
