### ISSUE TITLE
Custom Search Functionality

### ISSUE THREAD

**Issue by kunjesh1** [stephanrauh/ngx-extended-pdf-viewer#304]
I want to implement my custom search functionality .I want to  know which part of code I should change.

**Describe the solution you'd like**

I want to basically split the word and do the fuzzy search.

**Comment by stephanrauh** [comment]
Implementing a fuzzy search requires modifying the base library. I've done something similar when I implemented the "ignore diacritics" feature, so you can simply follow my trail. 

- You have to load your own copy of `viewer.js`. For instance, you can copy it to the assets folder and load it with an old-school `<script>` tag.
- Maybe you have to load `pdf.js` first. You can use the original file.
- In `viewer.js`, find every line commented with "#177" and add a similar implementation. 
- The core feature is implemented [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/d574d579670ff2b87f8f53c5fe4c8a262fccb881/projects/ngx-extended-pdf-viewer/src/assets/viewer.js#L5825) and [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/d574d579670ff2b87f8f53c5fe4c8a262fccb881/projects/ngx-extended-pdf-viewer/src/assets/viewer.js#L5800)

**Comment by stephanrauh** [comment]
One last question: Would you like to donate the fuzzy search to the library?

**Comment by kunjesh1** [comment]
Thanks. Yeah sure , I will donate it to the library once I have implemented that.

**Comment by stephanrauh** [comment]
Awesome, thanks!

**Comment by stephanrauh** [comment]
@kunjesh1 Have you managed to implement the feature already?

**Comment by kunjesh1** [comment]
Hi stephanrauh, sorry for the late reply. I am trying to implement the search with basically  splitting some text from the beginning and end then creating a median startIndex and endIndex.But it is getting into infinite loop.Do you have any suggestions.How to approach the problem?

Please refer the below code.

`   _calculatePhraseMatch(query, pageIndex, pageContent, entireWord, ignoreAccents) { // #177
          if (ignoreAccents) { // #177
            pageContent = window.deburr(pageContent); // #177
            query = window.deburr(query); // #177
          } // #177

          const matches = [];
          const queryLen = query.length;
          let matchIdx = -queryLen;
          let startPosition = [];
          let endPosition = [];

          while (true) {

            // console.log(pageContent);
            matchIdx = pageContent.indexOf(query, matchIdx + queryLen);
            // console.log(query.split(" "));
            let tempArrayChunk = query.split(" ");
            tempArrayChunk = tempArrayChunk.filter(item => item != " " && item != "").map(item => item.trim());
            let tempMatchId = -tempArrayChunk[0];

            for (let i = 0; i < tempArrayChunk.length / 2; i++) {
              // console.log(pageContent);
              tempMatchId = pageContent.indexOf(tempArrayChunk[i], tempMatchId + tempArrayChunk[i].length);
              console.log("Individual index", tempArrayChunk[i], tempMatchId);
              startPosition.push(tempMatchId);
            }
            tempMatchId = -1;
            for (let i = tempArrayChunk.length - 1; i > tempArrayChunk.length / 2; i--) {
              // console.log(pageContent);
              tempMatchId = pageContent.indexOf(tempArrayChunk[i], tempMatchId + tempArrayChunk[i].length);
              endPosition.push(tempMatchId);
            }

            startPosition = startPosition.filter(item => item != -1);
            console.log(startPosition);
            // console.log("entire word", entireWord);

             if (matchIdx == -1) {
              matchIdx = -1;
              break;
            }
            else {
              matchIdx = startPosition[0];

            }
            endPosition.filter(item => item != -1);
            console.log(startPosition, endPosition);
            if (startPosition.length === 0) {
              break;
            }
            console.log(startPosition);

            if (entireWord && !this._isEntireWord(pageContent, matchIdx, queryLen)) {
              continue;
            }
            console.log(startPosition[0]);
            matches.push(startPosition[0]);
          }

          this._pageMatches[pageIndex] = matches;
          console.log(pageIndex, "matches", matches);
        }
`

**Comment by stephanrauh** [comment]
I didn't run the code yet. However, just by reading the code, I didn't spot the infinite loop yet.

However, I'd recommend using a slightly different approach. There's a popular algorithm, the Levenstein distance, that should help you a lot. For example, this one looks promising: https://gist.github.com/andrei-m/982927#gistcomment-2059365

It's highly optimized code, so don't worry if it's hard to read. The other code snippets of the gist should help you.

Another approach is using a library. Unfortunately, I didn't find a good match to pdf.js yet. Maybe you could give https://fusejs.io/ a shot, but it's based on objects, not on long string. So you'd end up converting strings to objects.

**Comment by kunjesh1** [comment]
Thanks Stephanrauh. I will definitely try this one.

**Comment by stephanrauh** [comment]
After some research, I've found a promising library on node.js. Standing tall at 11.500.000 downloads per week, I'd try it first:

https://www.npmjs.com/package/fast-levenshtein

**Comment by kunjesh1** [comment]
Okay cool.So, after installing I have to import it to the viewer.js right?

**Comment by stephanrauh** [comment]
Oh. Good question. Maybe it's easier to implement it in the original pdf.js source first. That'd be here: https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js

So all you need to do is to run a `npm fast-levenshtein`, add a require statement to the `pdf_find_controller`, and you're good to go. You can run the pdf.js demo with `gulp server`.

We can figure out later how to add the feature to ngx-extended-pdf-viewer. I reckon it's simply running `gulp generic`. After that, the Levenshtein dependency should be part of `viewer.js`.

**Comment by kunjesh1** [comment]
I have cloned the pdf.js and declared the npm module in pdf_find_controller.js .But it is giving me reference error.

var levenshtein = require('fast-levenshtein');

error:Uncaught (in promise) ReferenceError: require is not defined
    at pdf_find_controller.js:19
![Screenshot from 2020-06-06 02-50-52](https://user-images.githubusercontent.com/16972191/83923800-98e56d80-a7a0-11ea-8dd6-72d543a93a80.png)

**Comment by stephanrauh** [comment]
It took me a while do figure things out, too. I've prepared a prototype of the fuzzy search here: https://github.com/stephanrauh/pdf.js.

**Comment by kunjesh1** [comment]
Thanks.I have cloned that .But, one thing I have noticed that.Suppose the search text is long. The search is slow.Like consider this text "Wehave implementedadynamiccompiler for JavaScript "  for the default PDF  it works but it is slow.

**Comment by stephanrauh** [comment]
Yes, the complexity of the Levenshtein similarity algorithm is O(n³). There's no way to avoid that.

However, if we insist that the beginning of the search phrase has at least some similarity to the beginning of the text, we can speed up things a lot. I've just pushed such an optimization. If assumes that at least three of the first five characters are identical.

**Comment by stephanrauh** [comment]
Async is a good idea. Pushing the search to a service worker may be even more effective. However, I shy away from the complexity.

**Comment by stephanrauh** [comment]
I've implemented a prototype of the fuzzy search algorithm and published it on https://pdfviewer.net/find.

However, I think we need to tweak the fuzzy search a bit. Maybe your first idea was good: calculate the distance of the search term and the text of the PDF file based on individual words. I guess most people don't want to see search result consisting of to words. For example, currently "love" matches "hello Verena", which is a bit unexpected.

@kunjesh1 Would to like to pick up my work and try to improve the algorithm? If so, it suffices to use the https://github.com/stephanrauh/pdf.js repository. I've re-structured my project. Now it doesn't use the modify-scripts. Instead, my fork of the pdf.js repository is the base library.

**Comment by kunjesh1** [comment]
Awesome @stephanrauh . I would like to work on this.Right now, I am researching how service.worker works in javascript as I am new to this language :) I think the searching in all the pages parallely using async will make it fast.What do you think? Have you added this fuzzy search to the new version of the library?  

One more concern currently I am working on a use case where I have to crop a certain section of pdf and send it to OCR to the ML model. Can we add a cropping tool to the library using cropper.JS 
https://fengyuanchen.github.io/cropperjs/  which will basically allow user to crop the section of PDF and send it as an output in the form of data URL or JPEG which will reduce the latency. What say?

**Comment by stephanrauh** [comment]
That's three questions. Let's answer them one by one.

Yes, I've added the fuzzy search prototype to the library. I've also made it a version 4.0.0. Currently, it's an alpha version because I've changed the build process radically and because the fuzzy search is a usable prototype, but it's still a prototype to be improved.

You can test the fuzzy search on https://pdfviewer.net/find. That's a huge document - more than 600 pages - so it's a great test for performance.

**Comment by stephanrauh** [comment]
As for async and the service worker: async is good because it doesn't block. As far as I can see, the search already runs asynchronously. 

Service workers can add a huge performance boost. However, I'm afraid you might be disappointed. The root problem is that the algorithm slows down with the square of the length of the input. So even a tenfold performance improvement may only give you two or three additional letters.

Plus, it's not easy to use a service worker. Adding insult to injury, the search implementation hasn't been implemented with a service worker in mind. You might have to change so much we'll never be able to merge the changes from Mozilla's pdf.js project again.

That's why I'm looking at other approaches, such as comparing individual words instead of comparing the entire text. That's an extra layer of complexity, too, but it might be worth the pain.

On the other hand, if you'd like to learn service workers: go for it! It's a good usecase. If the solution is simple enough, I'd like to add it to the libraries - but I can't make promises, because being compatible to pdf.js despite the 100+ modifications is quite a challenge.

**Comment by stephanrauh** [comment]
As for cropping: that's a use-case few other users have. So you have to give it a twist to make it useful for more users.

For example, I imagine a general export functionality might be useful to many users. Currently, printing is the only export. Maybe we could add a method extracting a particular page as an image.Actually, pdf.js already offers this feature, but it's far from being a plain, simple API.

The idea is that you crop the images yourself once you've got the image.

**Comment by FrancescoDiMaggio** [comment]
Hello everyone, do you have any update about the fuzzy-search feature in this wrapper?

**Comment by stephanrauh** [comment]
I believe fuzzy search works well enough, so we can call it a version soon.

@kunjesh1 When you've made progress, just send me a pull request. I'm closing the ticket now.

**Comment by kunjesh1** [comment]
Okay cool
