### ISSUE TITLE
 CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by javid-abd** [stephanrauh/ngx-extended-pdf-viewer#31]
BUG

Access to fetch at 'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf' from origin 'https://dashboard.finna.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I can't use any remote URL for pdf rendering. All of these point out this CORS problem. It used to work properly but it seems something as changed.

@angular/core 7.2.2
@angular/cli 7.2.3

**Comment by javid-abd** [comment]
@stephanrauh I can only properly render the pdf files by using "Allow-Control-Allow-Origin: *" chrome extension which is not a solution to fix the issue

**Comment by stephanrauh** [comment]
The CORS policy protects you from hacker attacks. You know, your application uses two different servers: your node.js server responsible for serving your application, and the third-party server serving the PDF file.

Your browser can't know that it's ok to load the PDF file. It only knows that hackers love redirecting users to third-party websites. For example, you're doing online-banking, and a hacker does a man-in-the-middle attack. Every keystroke is copied to the hackers website. As you can imagine, that's your road to unhappiness.

To protect you from these attack, every browser except Internet Explorer blocks third-party website access. There's nothing you can do on the client side.

What you can do, is to ask the administrator of the server side, to send the "Access-Control-Allow-Origin" header. If they're working in the same company as you do, they know what to do. If you really want to access a third-party PDF file, neither I nor your admins can help you. You have to download the PDF file on the server side and serve it from there.

Hope that helps! If it doesn't, please don't hesitate to ask me again. I'll keep listening even after closing the ticket.
