### ISSUE TITLE
Unexpected server response - could not load content assets pdf.worker.js.map

### ISSUE THREAD

**Issue by dreweird** [stephanrauh/ngx-extended-pdf-viewer#314]
**Describe the bug**
I clone the repository extended-pdf-viewer-showcase and serve it in google chrome browser.

![Untitled](https://user-images.githubusercontent.com/16024897/82627607-5b6bd680-9c1d-11ea-8792-fb33dc4b7acb.png)

**Version info**
{
  "name": "pdf-showcase",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "postbuild": "node compress.js",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.7",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.1.7",
    "@angular/compiler": "^9.1.7",
    "@angular/core": "^9.1.7",
    "@angular/flex-layout": "^9.0.0-beta.31",
    "@angular/forms": "^9.1.7",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.1.7",
    "@angular/platform-browser-dynamic": "^9.1.7",
    "@angular/router": "^9.1.7",
    "angular-material-icons": "^0.7.1",
    "classlist.js": "^1.1.20150312",
    "hammerjs": "^2.0.8",
    "ngx-extended-pdf-viewer": "^3.3.2",
    "ngx-markdown": "^9.1.1",
    "ngx-perfect-scrollbar": "^9.0.0",
    "perfect-scrollbar": "^1.5.0",
    "prismjs": "^1.20.0",
    "rxjs": "^6.5.5",
    "tslib": "^1.13.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.6",
    "@angular/cli": "^9.1.6",
    "@angular/compiler-cli": "^9.1.7",
    "@angular/language-service": "^9.1.7",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^14.0.4",
    "brotli": "^1.3.2",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.2",
    "node-dir": "^0.1.17",
    "ts-node": "~8.10.1",
    "tslint": "^6.1.2",
    "typescript": "^3.7.0 < 3.8.0"
  }
}

**Comment by stephanrauh** [comment]
Unexpected indeed. Can you see in the network tab which response the server sent? Otherwise, you could try to add a breakpoint in line 915 of the viewer.js. It seems the root cause of the error is silently swallowed when the error is caught and re-thrown.

**Comment by stephanrauh** [comment]
Did you manage to solve the issue?
