### ISSUE TITLE
how to extract position of a text selection

### ISSUE THREAD

**Issue by souravprakashjena** [stephanrauh/ngx-extended-pdf-viewer#321]
**Additional context**
When a user select a text inside the pdf viewer how we can extract the position of that text @stephanrauh

**Comment by stephanrauh** [comment]
I don't know. This is a feature that's implemented by the browser, not by the PDF viewer. So there's no "select" event. There's not even a CSS class that marks the selected text.

So I guess you have to do something fancy. StackOverflow suggest this solution:

```javascript
s = window.getSelection();
oRange = s.getRangeAt(0); //get the text range
oRect = oRange.getBoundingClientRect();
```
