### ISSUE TITLE
Closing a PDF viewer while it's still running a search causes error messages

### ISSUE THREAD

**Issue by mohnishswamy** [stephanrauh/ngx-extended-pdf-viewer#322]
Uncaught (in promise): UnknownErrorException: Cannot read property 'getPage' of null

**Comment by stephanrauh** [comment]
Please give me some context. What did you do? What does your sourcecode look like? You can use the template project https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template to create a reproducer project.

**Comment by stephanrauh** [comment]
I'm closing the ticket now. If you tell me how to reproduce the bug, I'll happily re-open the ticket.

**Comment by RepentAndBelieveTheGospel** [comment]
I have encountered this error with the following setup:

I am using PrimeNG's Table component to display clickable rows, which open the viewer in another component by way of an auxiliary route and routerLink.

<ng-template pTemplate="body" let-searchResult>
  <tr [pSelectableRow]="searchResult"
        [routerLink]="['', {outlets: {viewer: []}}]"
        [state]="{searchTerm: getSearchTerm(searchResult.text)"}>
  </tr>
</ng-template>

In the viewer component, I've added a custom back button to the toolbarViewerRight element:

<div id="toolbarViewerRight">
  <div class="back">
    <a [routerLink]="['', {outlets: {viewer: null}}]">
      <button pButton
              type="button"
              icon="pi pi-times">
      </button>
    </a>
  </div>
</div>

In the pagesLoaded event, I've placed the call to findController.executeCommand('find'):

pagesLoaded() {
  if (this.searchTerm) {
      this.pdfViewer.findController.executeCommand('find', {
          caseSensitive: false,
          findPrevious: undefined,
          highlightAll: true,
          phraseSearch: true,
          query: this.searchTerm
      });
  }
}

I've noticed that if I open the viewer and close it fast enough, I get two errors in the console:

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'query' of null
TypeError: Cannot read property 'query' of null
    at PDFFindController.get _query [as _query] (pdf_find_controller.js:279)
    at PDFFindController._calculateMatch (pdf_find_controller.js:558)
    at pdf_find_controller.js:731
    at ZoneDelegate.invoke (zone-evergreen.js:368)

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getPage' of null
TypeError: Cannot read property 'getPage' of null
    at pdf_find_controller.js:642
    at ZoneDelegate.invoke (zone-evergreen.js:368)

Another way I can reproduce it is by opening the viewer and using the search functionality, and while the search is being executed, I use the back button to close the component; it's easier if the document has many pages. I have reached the conclusion that the library will throw these errors if it is being closed while the search is still ongoing.

I have tried to find a way to stop the search process, but haven't been successful. I've found this event listener while looking for a solution, which fires every time a match is found on a page:

this.pdfComponent.pdfViewer.eventBus.on('updatefindmatchescount', data => {
    this.searchMatchesLength = data.matchesCount.total;
});

I hope this proves useful.

**Comment by stephanrauh** [comment]
I agree with your analysis. pdf.js uses a lot of asynchronous processing, so this kind of errors are more or less invevitable. I'm not sure it's a good idea to make the find controller more resilient, but I can have a look at it.

**Comment by RepentAndBelieveTheGospel** [comment]
Thank you for you prompt response. In case you can't do anything about the find controller, maybe you can consider adding an attribute to prevent these annoying errors from showing up in the console.

**Comment by stephanrauh** [comment]
I've managed to reproduce the bug and I've added some fault-tolerance.
