### ISSUE TITLE
showPagingButtons not behaving as expected

### ISSUE THREAD

**Issue by vrmerlin** [stephanrauh/ngx-extended-pdf-viewer#323]
**Describe the bug**
The showPagingButtons flag is on. I can see the buttons, and the "forward" and "backward" buttons are working fine, but the "first" and "last" page buttons are not working at all.

**Version info**
I am using 3.3.1, which matches the PdfShowcase version

**Desktop (please complete the following information):**
 - Chrome Version 81.0.4044.138
 

**To Reproduce**
Just loaded a PDF, and the general navigation is fine. It's just these two buttons are are misbehaving. Note in screenshot that only the "forward" button is active.

<img width="210" alt="Screen Shot 2020-05-26 at 2 10 25 PM" src="https://user-images.githubusercontent.com/7755554/82950770-bf163c80-9f5a-11ea-8f25-a8b2564fe50f.png">

**Comment by stephanrauh** [comment]
If I get you right, the problem is that the buttons are always deactivated.

However, it works here: https://pdfviewer.net/keyboard. What's the difference?

**Comment by vrmerlin** [comment]
I know we are on an older version of angular 8.0.0-beta.4. Could that be related? Other than that, it seems like a pretty straightforward flag.

**Comment by vrmerlin** [comment]
Also, i'm noticing the two "rotate" buttons are also non-functional. Might be related.

**Comment by vrmerlin** [comment]
Here's what I'm seeing:

<img width="210" alt="Screen Shot 2020-05-26 at 2 10 25 PM" src="https://user-images.githubusercontent.com/7755554/82953791-431ef300-9f60-11ea-94e8-4696a23ce588.png">

**Comment by vrmerlin** [comment]
Also, when i click on the "next page" button, then the "previous page" button enables, as expected.

**Comment by stephanrauh** [comment]
I remember I had some difficulty to get the feature run stable. It might be caused by your beta version of Angular. I guess that's easy to test. Probably you've got a good reason why you don't update to a final release, but it should be possible to do that for a quick text. Maybe parts of your application are broken by the update, but with chances are you can open the PDF page.

Alternatively, you can try to debug the code. The relevant parts are:

```typescript
export class PdfLastPageComponent {
  public disableLastPage = true;

  @ViewChild('button')
  private button: ElementRef<HTMLButtonElement>;

  constructor(private notificationService: PDFNotificationService) {
    const subscription = this.notificationService.onPDFJSInit.subscribe(() => {
      debugger; // <<< is this ever called?
      this.onPdfJsInit();
      subscription.unsubscribe();
    });
  }

  public onPdfJsInit(): void {
    debugger; // <<< is this ever called?
    const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
    PDFViewerApplication.eventBus.on('updateuistate', event => this.updateUIState(event));
  }

  public updateUIState(event: UpdateUIStateEvent): void {
    debugger; // <<< this should be called after each page navigation
    this.disableLastPage = event.pageNumber === event.pagesCount;
    this.button.nativeElement.disabled = this.disableLastPage;
  }

}
```

As you can see in the code snippet, simply setting the property and relying on the change detection of Angular didn't suffice. I also had to disable or enable the native element. Maybe you've run into a similar bug of Angular 8.0.0-beta.4.

**Comment by stephanrauh** [comment]
I'll close the ticket now. If you've got new insight, don't hesitate to re-open the issue.

**Comment by vrmerlin** [comment]
Sorry, I needed a few days to do the COTS upgrades. I upgraded to Angular 9 (and PrimeNG 9), and the problem is persisting.  I'll keep investigating.

**Comment by stephanrauh** [comment]
All right. It's a pity you didn't solve the issue yet. Keep me in the loop. I'll help you if I can.

Best regards,
Stephan

**Comment by vrmerlin** [comment]
Good news! So, it turns out a previous developer (who has since left the team) had done a copy and paste of your old beta version into our code tree, and the way i had it configured, it was grabbing some of that instead, messing things up. I removed what he had done, and things work fine now. :-)

**Comment by stephanrauh** [comment]
I see. I guess he tried to fix a bug. But obviously, the bugfix had side-effects in the long run. :)
