### ISSUE TITLE
IE11 Invalid argument at Anonymous Function in viewer-es5.js after Angular 9 migration

### ISSUE THREAD

**Issue by Wisdomb33r** [stephanrauh/ngx-extended-pdf-viewer#325]
**Describe the bug**
When using ngx-extended-pdf-viewer on Internet Explorer 11, the library is raising an Invalid argument error. The PDF is correctly displayed, but the error is very annoying because it triggers a very high-level ErrorHandler we have in our application.

It is raised before this line in the development console logs : 
```
PDF viewer: ngx-extended-pdf-viewer running on pdf.js 2.4.456
```

This error is NOT raised on any other browser I tested, namely Edge, Firefox and Chrome. This error appeared after migrating our project from Angular 8 to Angular 9, so it suppose it is related to this migration.

**Version info**
- Version 3.3.3

**Desktop (please complete the following information):**
 - Internet Explorer 11 running on Windows 10

**To Reproduce**
I'm joining to this discussion a reproduction project. It is very minimal, all I did are these steps :
 - ng new pdf-viewer-test
 - adding a few libraries in the dependencies
 - adapting angular.json to add the ngx-extended-pdf-viewer assets to the project (lines 25 to 29)
 - adding a TypeScript config for es5 (tsconfig-es5.app.json)
 - adapting angular.json to add an es5 configuration for IE compatibility (lines 65 to 72 and 85 to 87)
 - adapting package.json to add a start-ie configuration for serving es5 compilation
 - use ngx-extended-pdf-viewer component directly in app.component.html
 - start the project with npm start, check Firefox, Edge and Chrome have no error message
 - start the project with npm run start-ie, open Internet Explorer 11, press F12 for the dev console, load http://localhost:4200 and check if there is an error message in the console. Indeed there is.

Notes :
 - during npm start, the Angular CLI has a log line `Compiling ngx-extended-pdf-viewer : es2015 as esm2015`
 - during npm run start-ie, the Angular CLI has a log line `Compiling ngx-extended-pdf-viewer : module as esm5`

This is the normal process I guess, but worth noting it.

**Demo PDF file**
The PDF file is directly in the code as a base64 encoded string. It does display correctly on all browsers (including Internet Explorer 11). It is a swiss public document, dont mind the content, I verified it can be shared. The error in log is not file-dependent, the error is raised with any PDF file I could find.

**Additional context**
I tried a production build of my project and deployed the generated files on a web server (Tomcat). I had the same error message. The final bundling with differential loading seems consistent with the local ng serve using es5 configuration. Please note that I did not check this production build process for the minimal reproduction project I'm sharing.

[pdf-viewer-test.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4687896/pdf-viewer-test.zip)

**Comment by stephanrauh** [comment]
Does the "find" functionality still work? I assume it's broken because of the bug. Can you check this, so I know we're talking about the same bug?

**Comment by stephanrauh** [comment]
I've found the bug. A simple "_" was missing in the ES5 version. 

Please update to version 3.3.4.  It should fix your bug. If it doesn't, don't hesitate to tell me and to re-open the ticket.

**Comment by Wisdomb33r** [comment]
I updated to the latest version and it seems to work fine.
Thank you so much for your very fast patch.

**Comment by stephanrauh** [comment]
Your reproducer and your precise error description helped me a lot. So it's me who's to say "thanks!"
