### ISSUE TITLE
PDF viewer is unusable on small screens with high zoom factor

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#326]
@smrutiranjan727 reports in #44:

> Hi, right, when u resize the browser window everything is working fine as u r saying, the problem is when u zoom in the context of the dashboard inside the browser (browser window remain the same ,but u do zoom in/out). The problem was not PDF file itself, but the rest of the page which was not resizing, playing around with the parameters of the other components of the dashboard i fixed it somehow, not that smothly as i would expect, but it is ok. Thanks you very much for your support!

I am also having the same problem. @Miliks Could you please provide the fix here? I'm really going though a tough time for this in my project.

@stephanrauh Steps to reproduce the issue :
1. Increase your Browser's Zoom level (I'm not talking about the Zoom of ngx-extended-pdf-viewer).
2. Reduce the window width of your browser to the least possible width.
3. Now, you should be able to find the issue. The pdf is shown just partially, the full width of the pdf is not visible.
Please help with the fix. Thanks.

**Comment by stephanrauh** [comment]
Are you referring to this effect? Basically, all I can see is that the scroll bar of the PDF file is missing. But the combination of 500% zoom and minimal browser size looks pathological to me, anyways. Can you send me a screenshot that shows you bug in a more useful situation?

![image](https://user-images.githubusercontent.com/3045767/82740285-b39ef780-9d47-11ea-9d8e-c9002371e290.png)

![image](https://user-images.githubusercontent.com/3045767/82740293-c3b6d700-9d47-11ea-955b-04db85475c57.png)

**Comment by stephanrauh** [comment]
Hi. Thanks for your quick response.
Yes. I have the same issue. But my zoom level is not so high though. And yes, showing the scroll bar at least would fix the issue.
![Screenshot_20200524-034438](https://user-images.githubusercontent.com/18301541/82741568-1d7fc700-9d71-11ea-80b1-7befd2a90903.jpg)
As you can see, half of the pdf is hidden and no way I can scroll to view the hidden content.

**Comment by stephanrauh** [comment]
@smrutiranjan727 answered in #44:

And I think the width of the control also matters. As you can see the right side part of the pdf viewer control is hidden.

**Comment by smrutiranjan727** [comment]
Yes, correct. The problem appears to be when browsing the site on a smartphone. It seems to be fine with the latest smartphones. But what the elderly people do is, they increase their display size in their smartphone's settings menu so that they can view the things bigger on the screen. Doing that also affects the browser's zoom level.

I myself own an OnePlus 6T, which has a pretty big display and the pdf appears correctly in browser. But I was able to replicate the issue by increasing the display size in my display settings menu.

**Comment by stephanrauh** [comment]
I'm zooming all the time, too. :)

**Comment by smrutiranjan727** [comment]
Is there any work around until we get the permanent fix?

**Comment by stephanrauh** [comment]
Did you already discover the experimental pinch gesture support? https://pdfviewer.net/touch-gestures

It's experimental because a) the makers of pdf.js ran into all kinds of trouble when they tried to implement it, so I'm careful, and b) because I want limit the pinch gesture to the area of the PDF file. If you increase the PDF file, the PDF file is zoomed. If you pinch outside the PDF file, the entire page is zoomed. Currently, this part of the implementation is incomplete. But I believe it's useful even today.

**Comment by smrutiranjan727** [comment]
Just updated the package to v3.3.4 and tried the pinch gesture option. It seems to be pretty good.

Although some part of the control to the right is hidden, at least I could zoom in and drag the pdf to view the hidden content.

Note: I tried on my phone with the highest zoom available in display settings. But not sure how it would react in phones with a smaller display size.

**Comment by stephanrauh** [comment]
That's great news! Try it for a couple of days and tell me if there are any problems. If I don't hear from you after a week, I'm going to close the ticket.

**Comment by stephanrauh** [comment]
I'll keep the issue in mind. However, soon there's going to be a workaround when I'm starting to implement #367, so I'm closing the ticket now.

**Comment by hemanth110702** [comment]
Keep the content center option checked, so that you can properly zoom in and zoom out

<img width="708" height="692" alt="Image" src="https://github.com/user-attachments/assets/0c13519f-dc55-4555-9db1-fcb7c68f8cb1" />

**Comment by stephanrauh** [comment]
@hemanth110702 Thanks a lot - but your screenshots shows the built-in PDF viewer of GitHub, not ngx-extended-pdf-viewer.

Sorry! :)

Best regards,
Stephan
