### ISSUE TITLE
IE11-Print Preview Failed to Pop Up for Large Sized PDF

### ISSUE THREAD

**Issue by toniKantemirov** [stephanrauh/ngx-extended-pdf-viewer#330]
Hello.
When i click print icon in IE-11 and  after "preparing document for printing window" pops up and fully prepares, the print preview window did not pop up  for Large Sized PDF(for example 13 megabytes). 
To compare: If we load the smaller sized PDF document, the print preview window does pop up. Please see attachment 
[A17_FlightPlan.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4711208/A17_FlightPlan.pdf) - for comparison
In Chrome everything works good.

**Version info**
- Version of ngx-extended-pdf-viewer - 2

**Desktop ()**
 - Browser [basically Internet Explorer-11]

**Comment by stephanrauh** [comment]
I've tried to open the Apollo 17 flight plan with the showcase of the base library: https://mozilla.github.io/pdf.js/es5/web/viewer.html

After a while, IE11 crashes. I guess that's simply too much for this browser. It looks like an out-of-memory error or something like that. You know, the print preview renders each page as an image. In this case, that's 600+ images.

**Comment by stephanrauh** [comment]
I won't fix this bug because it's a problem of the base library. You can report it here: https://github.com/mozilla/pdf.js/issues

But it seems to be a good use-case to justify partial printing, as requested in #243. Maybe that feature helps you, too.

**Comment by stephanrauh** [comment]
A programmatic print API has landed with version 3.5.0. It still doesn't prevent the user from hitting CTRL+P or the print button of the toolbar, but it's a start. You can now define which pages you want to print. Maybe this helps you with managing the large documents on IE11.

The documentation is available at https://pdfviewer.net/print-range.

**Comment by toniKantemirov** [comment]
Thank you for your answer, and for paying attention to this ticket with a problem so quickly.

regards,
Anton
