### ISSUE TITLE
Version mismatch error on Angular 4

### ISSUE THREAD

**Issue by venkat4541** [stephanrauh/ngx-extended-pdf-viewer#336]
I'm getting the following error while trying to integrate ngx-extended-pdf-viewer into my project.

**Steps followed:**
1.  npm i ngx-extended-pdf-viewer --save
2. Imported into the respective module: import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';
3. Added the necessary html.

`ERROR in Metadata version mismatch for module ~../../node_modules/ngx-extended-pdf-viewer/ngx-extended-pdf-viewer.d.ts, found version 4, expected 3, resolving symbol ....Module in ~../../../../index.ts`

Please note that paths above have been replaced with '...' for work privacy reasons.

**Comment by stephanrauh** [comment]
Are you using Angular 4? It's not impossible to run ngx-extended-pdf-viewer with Angular 4, but basically it amount to copying every file into your project instead using the library. At https://pdfviewer.net/getting-started there's a description how to do it.

If you want me to continue  analyzing the bug, I suggest you send me a reproducer based on the template project https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template.

**Comment by stephanrauh** [comment]
Oh, I'm sorry - somehow I missed your headline. So it's really an Angular 4 incompatibility problem. ngx-extended-pdf-viewer is compiled with Angular 7 to compile Angular 6+7, but I didn't want to go back beyond that.

**Comment by venkat4541** [comment]
I appreciate your looking into this. I saw a page which mentioned about Angular 4 in the website documentation and this error was looking unrelated to Angular version, so I created this issue. Sorry about that.

**Comment by stephanrauh** [comment]
Don't be! It took me several minutes - well, several quarters of an hour - to realize this might be an Angular 4 bug. The error message doesn't say so, does it?

I hope you'll manage to get the PDF viewer up and running. If you run into trouble, don't hesitate to tell me. If possible, send me a reproducer, because this is a leisure time project, and usually the reproducers help me to find the bug much more quickly.
