### ISSUE TITLE
Onload callback

### ISSUE THREAD

**Issue by dadepra** [stephanrauh/ngx-extended-pdf-viewer#34]
Hi Stephan let me know how I can call a callback function when document is loaded from server? There are something like (after-load-complete) of ng2-pdf-viewer ?

**Comment by stephanrauh** [comment]
Sounds like a sensible request to me. `ngx-extended-pdf-viewer` is simply a wrapper around pdf.js, so I can't implement the feature if it hasn't been implemented by Mozilla. However, there's a ticket that sounds promising: https://github.com/mozilla/pdf.js/issues/5601

**Comment by dadepra** [comment]
Understand, thank for your replay!

**Comment by stephanrauh** [comment]
Since version 0.9.19 there's a new event `(pagesLoaded)` you can use.
