### ISSUE TITLE
Add a programmatic API to extract a page as image or as text

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#341]
It seems many developers don't just want to display PDF file, they also want to process them. One of the feature requests is to

- extract the text of a page (if there's a text layer)
- extract the PDF page as an image.

**Comment by stephanrauh** [comment]
@kunjesh1 How do you like the current prototype?

**Comment by stephanrauh** [comment]
The feature has landed three weeks ago. Let's close the ticket.

**Comment by kunjesh1** [comment]
@stephanrauh Sorry for late reply, I have tried the PDF crop using cropper JS in angular but failed :( 
![Screenshot from 2020-07-07 00-51-37](https://user-images.githubusercontent.com/16972191/86631791-2dcfc680-bfec-11ea-83ad-2ab43627ff34.png)

**Comment by kunjesh1** [comment]
`import { Component, OnInit, ElementRef, ViewChild, EventEmitter, Output } from '@angular/core';

import Cropper from "cropperjs";
import * as PDFJS from "pdfjs-dist";
import * as $ from 'jquery';
import { OcrService } from '../../../services/ocr.service';
import { CourseService } from '../../../services/course.service';
import { ActivatedRoute } from '@angular/router';

var __PDF_DOC,
  __CURRENT_PAGE,
  __TOTAL_PAGES,
  __PAGE_RENDERING_IN_PROGRESS = 0,
  __CANVAS,
  __ZOOMFLAG = false,
  pdf_url,
  scale_required = 0,
  __canvasWidth,
  __canvasHeight,
  __CANVAS_CTX;


function showPDF(pdf_url) {
  $("#pdf-loader").show();
  //append parameters when not hardcoded "https://cors-anywhere.herokuapp.com/" + pdf_url
  PDFJS.getDocument("../../../assets/document.pdf").promise.then(function (pdf_doc) {
    __PDF_DOC = pdf_doc;
    __TOTAL_PAGES = __PDF_DOC.numPages;

    // Hide the pdf loader and show pdf container in HTML
    $("#pdf-loader").hide();
    $("#pdf-contents").show();
    $("#pdf-total-pages").text(__TOTAL_PAGES);

    // Show the first page
    showPage(1, 0);
    // __canvasHeight = $('#pdf-canvas').height();
  }).catch(function (error) {
    // If error re-show the upload button
    $("#pdf-loader").hide();
    $("#upload-button").show();

    alert(error.message);
  });;
}

function showPage(page_no, scale) {
  __PAGE_RENDERING_IN_PROGRESS = 1;
  __CURRENT_PAGE = page_no;

  // Disable Prev & Next buttons while page is being loaded
  $("#pdf-next, #pdf-prev").attr('disabled', 'disabled');

  // While page is being rendered hide the canvas and show a loading message
  $("#pdf-canvas").hide();
  $("#page-loader").show();

  // // Update current page in HTML
  $("#pdf-current-page").text(page_no);
  console.log(__CURRENT_PAGE);

  // Fetch the page
  __PDF_DOC.getPage(page_no).then(function (page) {
    // As the canvas is of a fixed width we need to set the scale of the viewport accordingly
    scale_required = (__CANVAS.width / page.getViewport(1).width) + scale;
    console.log(scale_required);

    // Get viewport of the page at required scale
    var viewport = page.getViewport(scale_required);

    // Set canvas height
    __CANVAS.height = viewport.height;

    var renderContext = {
      canvasContext: __CANVAS_CTX,
      viewport: viewport
    };

    // Render the page contents in the canvas
    page.render(renderContext).then(function () {
      __PAGE_RENDERING_IN_PROGRESS = 0;

      // Re-enable Prev & Next buttons
      $("#pdf-next, #pdf-prev").removeAttr('disabled');

      // Show the canvas and hide the page loader
      $("#pdf-canvas").show();
      $("#page-loader").hide();

      // Return the text contents of the page after the pdf has been rendered in the canvas
      return page.getTextContent();
    }).then(function (textContent) {
      // Get canvas offset
      var canvas_offset = $("#pdf-canvas").offset();

      // Clear HTML for text layer
      $("#text-layer").html('');

      // Assign the CSS created to the text-layer element
      $("#text-layer").css({ left: 0 + 'px', top: 0 + 'px', width: __canvasWidth + 'px' });

      console.log($("#text-layer").get(0));
      // Pass the data to the method for rendering of text over the pdf canvas.
      PDFJS.renderTextLayer({
        textContent: textContent,
        container: $("#text-layer").get(0),
        viewport: viewport,
        textDivs: []
      });
    });
  });
}

@Component({
  selector: 'app-pdf-viewer',
  templateUrl: './pdf-viewer.component.html',
  styleUrls: ['./pdf-viewer.component.scss']
})

export class PdfViewerComponent implements OnInit {

  @Output() demoStr = new EventEmitter<string>();
  cropflag = false;
  flag = false;
  demo = "";
  demo1;

  pdf_current_page_event = document.getElementById("pdf-current-page");
  if(pdf_current_page_event) {
    pdf_current_page_event.addEventListener("input", function () {
      console.log("input event fired");
    }, false);
  }

  constructor(private ocrService: OcrService, private courseService: CourseService, private route: ActivatedRoute) {
    console.log(this.pdf_current_page_event);

    console.log(this.route);
    showPDF(pdf_url);
    // this.courseService.generateURL({
    //   "file_path": this.route.snapshot.params.file_path,
    //   "bucket": this.route.snapshot.params.bucket
    // }).subscribe(response => {
    //   // pdf_url = response['data'][0].toString();
    //   console.log(pdf_url);
    //   showPDF(pdf_url);

    // },
    //   err => console.log(err),
    //   () => {

    //     // renderAllPages();
    //     console.log('completed Successfully');

    //   }
    // );

    this.imageDestination = ""
  }

  @ViewChild("pdf_canvas", { static: false })
  public the_canvas: ElementRef;
  public imageDestination: string;
  private cropper: Cropper;

  ngOnInit() {
    __CANVAS = $('#pdf-canvas').get(0);
    console.log(__CANVAS);
    __CANVAS_CTX = __CANVAS.getContext('2d');
    __canvasWidth = $('#pdf-main-container').width();
    __canvasHeight = '700px';
    //reset the orginal value;   
    //  loadPDF();
  }

  saveCrop() {
    this.cropper.destroy();
    this.flag = false;
    this.cropflag = false;

    var blob = this.dataURItoBlob(this.imageDestination);
    var fd = new FormData();
    fd.append("file1", blob, "temp_image");
    console.log(fd.get("file1"));
    console.log(blob);
    this.ocrService.post_OCR(fd)
      .subscribe(response => {
        console.log(response['data']);
        this.demo = response['data'];
        this.demoStr.emit(this.demo);
      },
        err => console.log(err));
  }

  stopCrop() {
    this.cropper.destroy();
    this.cropflag = false;
    this.flag = false;
  }

  // Previous page of the PDF
  prevPage() {
    if (__CURRENT_PAGE != 1)
      showPage(--__CURRENT_PAGE, 0);
  };

  // Next page of the PDF
  nextPage() {
    if (__CURRENT_PAGE != __TOTAL_PAGES)
      showPage(++__CURRENT_PAGE, 0);
  }

  //Zoom in of the PDF
  zoomIn() {
    scale_required = scale_required + 0.25;
    showPage(__CURRENT_PAGE, scale_required);
  }

  //Zoom Out of the PDF
  zoomOut() {
    if (scale_required <= 0.8) {
      return;
    }
    scale_required = scale_required - 0.25;
    showPage(__CURRENT_PAGE, scale_required);
  }

  dataURItoBlob(dataURI) {
    // convert base64/URLEncoded data component to raw binary data held in a string
    var byteString;
    if (dataURI.split(',')[0].indexOf('base64') >= 0)
      byteString = atob(dataURI.split(',')[1]);
    else
      byteString = unescape(dataURI.split(',')[1]);

    // separate out the mime component
    var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];

    // write the bytes of the string to a typed array
    var ia = new Uint8Array(byteString.length);
    for (var i = 0; i < byteString.length; i++) {
      ia[i] = byteString.charCodeAt(i);
    }

    return new Blob([ia], { type: mimeString });
  }

  public startCrop() {

    console.log(this.the_canvas.nativeElement);
    this.cropper = new Cropper(this.the_canvas.nativeElement, {

      zoomable: false,
      scalable: false,

      crop: () => {
        const canvas = this.cropper.getCroppedCanvas();
        this.imageDestination = canvas.toDataURL("image/png");
        console.log(this.imageDestination);
      },
    });
    this.flag = true;
    this.cropflag = true;
  }

  onMouseMove(e) {
    console.log(e);
    this.demo = document.getSelection().toString();
    this.demo1 = this.demo;
    this.demoStr.emit(this.demo);
  }

}`

**Comment by stephanrauh** [comment]
Did you try `NgxExtendedPdfViewerService .getPageAsText_preview()`?

BTW, I'm re-opening the ticket because I the name of the methods shouldn't be `*_preview` in the final release :)

**Comment by kunjesh1** [comment]
It will convert the PDF doc into text or image? Does it work for PDF made of images?

**Comment by stephanrauh** [comment]
Yes and no. It doesn't convert anything. It just extracts what's already there:
- The PDF viewer always renders the PDF as a collection of images, so you can always extract images.
- If the PDF file contains text, and if you've activated the text layer (`[textLayer]="true"`), you can extract this text.
- But there's no OCR reader, so you can't extract text from an image.

**Comment by kunjesh1** [comment]
Ok got it.Thanks

**Comment by stephanrauh** [comment]
I've just finished the implementation using Promises, so you can use async/await soon.

**Comment by kunjesh1** [comment]
Ok cool
