### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by musawershah1598** [stephanrauh/ngx-extended-pdf-viewer#343]
When ever i load an online pdf file from server using src attribute i get the following error in chrome console
```
Access to fetch at 'https://somelink.com/myfile.pdf' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
and on the view below error is shown
![Screenshot from 2020-06-08 14-43-42](https://user-images.githubusercontent.com/20392867/84016340-964c6900-a996-11ea-90ea-b3365294d441.png)

so how can i remove this error

**Comment by stephanrauh** [comment]
Yeah, the good old CORS problem. It's a protection against hackers. As a side effect, it also drives developers nuts.

Have a look at https://juristr.com/blog/2016/11/configure-proxy-api-angular-cli/ for in-depth information and a solution. However, I'm not sure if Juri's `proxy.conf.json` file still works. When I needed it two days ago, I had to use a slightly different version:

```json
{
  "/api": {
    "target": {
      "host": "www.beyondjava.net",
      "protocol": "https:",
      "port": 443
    },
    "secure": true,
    "logLevel": "debug",
    "changeOrigin": true
  }
}
```
