### ISSUE TITLE
Show Find Button does not work

### ISSUE THREAD

**Issue by liqSofia** [stephanrauh/ngx-extended-pdf-viewer#350]
Hello there, 

I have updated the package to the latest version (4.0.0-alpha.4), but I cannot get the find button to be displayed. 

I noticed that this is also happening at 'Customizing the buttons' demo (https://pdfviewer.net/hiding-buttons). But it is there on Simple Demo (https://pdfviewer.net/simple). 

Any help would be greatly appreciated!

Thank you in advance,
Sofia

**Comment by stephanrauh** [comment]
You need a document with text (as opposed to images), and you have to activate the text layer.

**Comment by stephanrauh** [comment]
The attribute I'm referring to is:

```html
<ngx-extended-pdf-viewer
  [textLayer]="true" <!-- enable the find button -->
  ...
```

**Comment by stephanrauh** [comment]
I've updated the troubleshooting section of the showcase (without publishing it yet, but you can see the commit above).

If you don't get along, don't hesitate to ask again.

Best regards,
Stephan
