### ISSUE TITLE
pdf.min.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by AnzilkhaN** [stephanrauh/ngx-extended-pdf-viewer#352]
**Describe the bug**
After npm install , it showing an **error** :: 

> GET http://localhost:4200/assets/pdf.min.js net::ERR_ABORTED 404 (Not Found) - ngx-extended-pdf-viewer.js:855

**Version info**
- "ngx-extended-pdf-viewer": "^3.7.2"

> angular.json :: 
> "assets": [
>               "src/favicon.ico",
>               "src/assets",
>               {
>                 "glob": "pdf.worker.js",
>                 "input": "node_modules/ngx-extended-pdf-viewer/assets",
>                 "output": "/assets/"
>               }
>             ],
>             "styles": [
>               "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css"
>             ],
>             "scripts": [
>               "node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
>               "node_modules/ngx-extended-pdf-viewer/assets/viewer.js"
>             ]

**Screenshots**
![image](https://user-images.githubusercontent.com/43582808/84776718-4b69cb80-affe-11ea-9310-ab0e45950659.png)

**Comment by stephanrauh** [comment]
The configuration in the angular.json has become a lot simpler. Please try this:
```json
"assets": [
    "src/favicon.ico",
    "src/assets",
    {
      "glob": "**/*",
      "input": "node_modules/ngx-extended-pdf-viewer/assets/",
      "output": "/assets/"
    }
  ],
  "scripts": []
```

**Comment by ntdog22** [comment]
Running into the same issue if the assets folder is outputted a directory up. i.e.:

```TypeScript
"assets": [
    {
        "glob": "**/*",
	 "input": "src/assets",
 	 "output": "/assets"
    },
    {
        "glob": "**/*",
	"input": "node_modules/ngx-extended-pdf-viewer/assets/",
	"output": "/assets/"
    },
    ....
],
"scripts": []
```

**OR** if using the `copy-webpack-plugin` with the Angular CLI:

```TypeScript
{
	from: helpers.root("./node_modules/ngx-extended-pdf-viewer/assets/"),
	to: "./assets/"
},
```

as it prefixes the route to use `dist/app/` rather than `/`. In this case, `pdf.min.js` cannot be found. 


Is there a way in which I can override the default path that `ngx-extended-pdf-viewer` uses to load assets? The goal is to change the path from `/assets/pdf.min.js` to `dist/app/assets/pdf.min.js`.
