### ISSUE TITLE
Is there any way to add a new icon in the toolbar of the pdf viewer? 

### ISSUE THREAD

**Issue by prasanthnsn11** [stephanrauh/ngx-extended-pdf-viewer#353]
**Is your feature request related to a problem? Please describe.**
Yes we need to have a new feature in the pdf viewer. An icon with a new functionality that helps us to send a email from the viewer.

**Comment by stephanrauh** [comment]
Yes, that's possible. Have a look at https://pdfviewer.net/custom-toolbar. The fourth demo ("additional buttons") adds an "open in new page" button. You could do the same to implement the email feature.
