### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by rajkumarganesan93** [stephanrauh/ngx-extended-pdf-viewer#356]
There is no option to add watermark and it's styles color etc., Watermark position can be Tile, Center, Header or footer. Also many colors can be add in watermark.

**Comment by stephanrauh** [comment]
Welcome to GitHub, and to ngx-extended-pdf-viewer in particular! I feel very honoured you chose my project to open your first issue!

**Comment by stephanrauh** [comment]
Two weeks without an answer... I suppose you've solved the issue yourself.

In any case, here's a code snippet telling you how to add watermarks to the print: https://github.com/mozilla/pdf.js/issues/7783#issuecomment-346534883

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, any work-around you've implement may stop working. But I expect the new version to solve more bugs than it causes.
