### ISSUE TITLE
Hide / Disable options in the viewer

### ISSUE THREAD

**Issue by amitkhiwal** [stephanrauh/ngx-extended-pdf-viewer#362]
I am using the pdf viewer for an enterprise application where I only want fixed options to be available for user. So how to hide them.

In one of the earlier pdf.js implementation that I was using, there was a viewer.html file in which we could change that viewer options.

**Comment by MKITConsulting** [comment]
Maybe this is sufficient for your needs: https://pdfviewer.net/hiding-buttons.

**Comment by stephanrauh** [comment]
Another option is to use custom toolbars and menus. There's a live demo here: https://pdfviewer.net/custom-toolbar and some documentation here: https://pdfviewer.net/customization

I'm still unhappy with my documentation, so don't hesitate to address me if you run into trouble. 

BTW: the viewer.html file is still there. It's just that this is a different project. pdf.js is the base library I'm building upon.

**Comment by stephanrauh** [comment]
If my hints help you, would you mind to reach out to me so I know I can safely close this ticket?

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
I assume the issue has been solved. If not, don't hesitate to reach out again.
