### ISSUE TITLE
ngx-extended-pdf-viewer won't work within a material tab (4.0.0-alpha.5)

### ISSUE THREAD

**Issue by Columbo1964** [stephanrauh/ngx-extended-pdf-viewer#368]
You can reproduce the behavior with a material tab wrapper  in the extended-pdf-viewer-showcase-master by modifying the  lower section 

`<mat-card class="distance-16 mat-elevation-z8">
  <ngx-extended-pdf-viewer
     [src]="'assets/pdfs/pdf-sample.pdf'"
     [height]="'90vh'"
     [useBrowserLocale]="true"
     [textLayer]="true"
     [showHandToolButton]="true">
  </ngx-extended-pdf-viewer>
</mat-card>`

of the simple-component html code  to this:

`<mat-tab-group>
  <mat-tab>Content 1</mat-tab>
  <mat-tab>
    <mat-card class="distance-16 mat-elevation-z8">
      <ngx-extended-pdf-viewer [src]="'assets/pdfs/pdf-sample.pdf'" [height]="'90vh'" [useBrowserLocale]="true"
        [textLayer]="true" [showHandToolButton]="true">
      </ngx-extended-pdf-viewer>
    </mat-card>
  </mat-tab>
  <mat-tab>Content 3</mat-tab>
</mat-tab-group>`

you get this error on the console:

core.js:4117 ERROR TypeError: Cannot read property 'appendChild' of undefined
    at ngx-extended-pdf-viewer.js:563
    at Array.forEach (<anonymous>)
    at PdfDummyComponentsComponent.push../node_modules/ngx-extended-pdf-viewer/__ivy_ngcc__/fesm5/ngx-extended-pdf-viewer.js.PdfDummyComponentsComponent.addMissingStandardWidgets (ngx-extended-pdf-viewer.js:553)
    at ngx-extended-pdf-viewer.js:1863
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28122)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:503)
    at ZoneTask.invoke (zone.js:492)

Thank you for your support!

**Comment by Columbo1964** [comment]
Those poeple who can read are in a big advantage ...

I found this [https://unpkg.com/browse/ngx-extended-pdf-viewer@1.0.2/README.md](url) and it explains what happens.

At present I have to manage more then expeceted, but for using this viewer I will!!

I modified the html again with the recommended code from the arcticle above:
`<mat-tab-group (selectedTabChange)="activateTab($event.index)">
  <mat-tab label="Before">Content 1</mat-tab>
  <mat-tab label="Document 1">
    <ng-template matTabContent>
      <ngx-extended-pdf-viewer *ngIf="visible[1]" [src]="'assets/pdfs/pdf-sample.pdf'" [height]="'90vh'"
        [useBrowserLocale]="true" [textLayer]="true" [showHandToolButton]="true"> </ngx-extended-pdf-viewer>
    </ng-template>
  </mat-tab>
  <mat-tab label="Document 2">
    <ng-template matTabContent>
      <ngx-extended-pdf-viewer *ngIf="visible[2]" [src]="'assets/pdfs/blind-text-collection.pdf'" [height]="'90vh'"
        [useBrowserLocale]="true" [textLayer]="true" [showHandToolButton]="true"> </ngx-extended-pdf-viewer>
    </ng-template>
  </mat-tab>
  <mat-tab label="After">Content 4</mat-tab>
</mat-tab-group>`

To avoid timeing problems and controlling the active instances I adjusted the typescript component class from the article above to

`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-simple',
  templateUrl: './simple.component.html',
  styleUrls: ['./simple.component.css']
})
export class SimpleComponent implements OnInit {
  constructor() {}

  ngOnInit() {}

  public visible = { 0: true };

  public activateTab(tab: number): void {
    this.hideOtherPDFs();
    setTimeout(() => {
      this.visible[tab] = true;
    }, 100);
  }

  public hideOtherPDFs(): void {
    console.log('Hiding');
    this.visible[0] = false;
    this.visible[1] = false;
    this.visible[2] = false;
    this.visible[3] = false;
  }
}`

**Comment by stephanrauh** [comment]
I agree this is very annoying. The root cause is that pdf.js, the underlying library, has been developed only to be used in Firefox. They didn't think about embedding it in an application.
