### ISSUE TITLE
Provision to add toolbar when it is full screen

### ISSUE THREAD

**Issue by vaishnavi-baliga** [stephanrauh/ngx-extended-pdf-viewer#369]
**Requirement**
I can view my PDF in full screen once I set the property 'showPresentationModeButton' as true and need to view the toolbar as i cant keep clicking or scrolling the next page. 

**How i need it to be**
I have a PDF with 300 pages, when I open the PDF in full screen, i need the toolbar to be visible. I should be able to navigate to different chapters if its a long PDF. So how should or how will i add this toolbar when its in full screen? Either on top or on the side, anyway but i just need a provision to add the same.

**Addition info**
![image](https://user-images.githubusercontent.com/36834245/85870977-694be300-b7eb-11ea-81e0-2cc61c46bdbd.png)

**Comment by stephanrauh** [comment]
Well, that's slightly contradictive. You need a full-screen mode that doesn't span the entire screen. :)

**Comment by stephanrauh** [comment]
Maybe it's even possible. The toolbar is probably hidden by CSS. Scan for the `:fullscreen` CSS rules.

However, added the thumbnail view seem to be impossible, at least with the current version.

**Comment by vaishnavi-baliga** [comment]
> Maybe it's even possible. The toolbar is probably hidden by CSS. Scan for the `:fullscreen` CSS rules.
> 
> However, added the thumbnail view seem to be impossible, at least with the current version.

Thank you for the heads up! Will try using the CSS to make the toolbar visible. Thanks again!! :)
