### ISSUE TITLE
Package size?

### ISSUE THREAD

**Issue by JWess** [stephanrauh/ngx-extended-pdf-viewer#37]
It would be really helpful if you could post something in the README about how much this package affects prod build size. You can see package size by using this type of command:

`ng build --prod --stats-json && npx webpack-bundle-analyzer dist/NAME_OF_PROJECT/stats.json`

Furthermore, it would be even more helpful if you were to compare the size of this package to the competition.

**Comment by stephanrauh** [comment]
| Stat | Parsed | Gzipped |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
main | 2,83 MB | 641 KB | 190 KB |   | chunk {0}   runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
scripts | 1,24 MB | 1,24 MB | 342 KB |   | chunk {1}   main.74f3b3327ea1bf0cb434.js (main) 642 kB [initial] [rendered]
styles |   | 60,9 KB |   |   | chunk {2}   polyfills.e6ec181e21c956dc9a70.js (polyfills) 58.2 kB [initial] [rendered]
  |   |   |   |   | chunk {3}   styles.34b5c5f569254b8b8a5b.css (styles) 60.9 kB [initial] [rendered]
  |   |   |   |   | chunk {scripts}   scripts.94faac2eb5a8b013efa4.js (scripts) 1.24 MB  [rendered]
  |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |  
main | 2,64 MB | 465 KB | 114 KB |   | chunk {0}   runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
scripts | 0 | 0 | 0 |   | chunk {1}   main.658c1882107cb0fa79d9.js (main) 466 kB [initial] [rendered]
styles |   | 60,9 |   |   | chunk {2}   polyfills.e6ec181e21c956dc9a70.js (polyfills) 58.2 kB [initial] [rendered]
  |   |   |   |   | chunk {3}   styles.34b5c5f569254b8b8a5b.css (styles) 60.9 kB [initial] [rendered]

**Comment by stephanrauh** [comment]
The library seems to add a hefty 1445 KB of disk space. The Gzipped archives is much more moderate, adding 476 KB.

**Comment by stephanrauh** [comment]
As for the competition: there's no direct competitor. That's why I wrote the library in the first place.

**Comment by JWess** [comment]
How does your project differ from this one, which is also built on pdfjs? Thanks for being so responsive! https://github.com/intbot/ng2-pdfjs-viewer

**Comment by stephanrauh** [comment]
Todos left:

- [ ] add a memory footprint notice to the readme.md.

**Comment by JWess** [comment]
> How does your project differ from this one, which is also built on pdfjs? Thanks for being so responsive! https://github.com/intbot/ng2-pdfjs-viewer

Full disclosure, I actually tried yours first, but I ran into this error: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/20

**Comment by stephanrauh** [comment]
Oops! I didn't know about the other project. I've spent many hours Googling for it. Weird! :)

Obvious differences: the other project has one commit less, and it's much more popular. We started roughly at the same time, so probably this is the reason why I missed it.

Other than that, the projects look surprisingly similar at first glance.

**Comment by stephanrauh** [comment]
Maybe there's one important difference: ng2-pdfjs-viewer uses PDF.js 2.0.428. As far as I can tell, this is a developer version. My library uses the latest version 2.0.943.

**Comment by stephanrauh** [comment]
Tried to contact the author of ng2-pdfjs-viewer again.

**Comment by stephanrauh** [comment]
@JWess I didn't check this myself, but I've seen you've investigated the topic. Is it correct that the memory footprint of ng2-pdfjs-viewer is larger because it uses the developer version of the PDF viewer?

**Comment by stephanrauh** [comment]
I've added the memory footprint to the README.md file.

**Comment by stephanrauh** [comment]
For whom it may concern: The author of ng2-pdfjs-viewer answered yesterday. The library is dormant at the moment, but the author has plans to update it. So we can hope for an update.

**Comment by stephanrauh** [comment]
I've examined the source code of ng2-pdfjs-viewer. It uses a very clever strategy: it simply wraps Mozilla's PDF viewer in an iFrame. We didn't want to do that in our project, so we went the hard way. That explains why ng2-pdfjs-viewer is much more reliable than my library. However, putting the PDF viewer into an iFrame has a lot of disadvantages. You can open it with certain properties (keyword  `@Input()`), but it's hard to implement the return path (`@Output()`). Plus, I'm not sure if ng2-pdfjs-viewer reacts to changes of the input attribute.

(Truth to tell, ngx-extended-pdf-viewer doesn't react properly to such changes yet, but at least there's no technical obstacle preventing me from implementing such a feature).
