### ISSUE TITLE
Scroll events? Combined pdfs? Customizable sidebar?

### ISSUE THREAD

**Issue by Epsiom** [stephanrauh/ngx-extended-pdf-viewer#374]
Hi,
I'm in the process of using your library to preview signature placement on a pdf, with ie11/edge/safari/opera compatibility.
I'm solving most of my problems by using the event given by the (pagesLoaded) attribute, as most of my problems aren't solved by the API.

As such: 

- Is there a better solution to find the position and scroll of the viewer/pages (to more easily position images as an overlay) ?

- Is there a way to display multiple pdfs as one (I know it's not currently supported, but is there a way for me to append one of the project's variable, or reach an unexplained part of the project) ?

- What is the way to have "direct access to the core API of pdf.js" ?

- Is there a way to customize the sidebar to highlight certain pages (I've read you wanted to make the sidebar more customizable in past forum posts) ?

Any help or fragment of answer would be greatly appreciated.
(IE support is needed, but if an answer that doesn't support it is given, it would still greatly help)

Thanks in advance!

**Comment by stephanrauh** [comment]
- Finding out the position of the pages: I'm not sure if I want to support this. Let me ponder about this for a while. It might be a cool feature, but it's also pretty exotic, I guess. I take it you've found a work-around?

- Multiple PDFs: You could combine the PDF file before sending them to the viewer. That's probably a server-side task. If I want to implement such a feature, I'd have to modify a large part of pdf.js, so I'd loose the ability to update to new versions of pdf.js.

- Low-level access: there's the PDFViewerApplication object and a couple of interfaces. Using this object is always risky because the Mozilla team may change these objects without warning.
```TypeScript
      const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
```

**Comment by stephanrauh** [comment]
As for the sidebar: interesting idea. I'll keep it in mind when I start working on the customizable sidebar. I'm not sure that's an easy task because it probably amount to modifying a lot of the pdf.js code.

**Comment by Epsiom** [comment]
Thanks a lot!

As I said, I used the event returned by (pageLoaded), which contains dom references to the viewer and the pages themselves, which I can then use getBoundingClientRect on to get its coordinates. It however feels maybe a bit far-fetched, hence why I'd like a better solution if it exists.
For the sidebar, I've seen that every page has a class matching its page number. Or I'll use the same dom references if I can manage to find them. Or ViewChild.

I'll give a tiny bit more info tomorrow, as I'm just writing from memory without my notes.

**Comment by Epsiom** [comment]
As I've been saying, I access positions and DOM elements with the event returned from (pagesLoaded).
The viewer can be accessed with event.source.viewer, and the pages with event.source.viewer.children.

For the sidebar, is there a way to avoid removing past thumbnails, appending new ones, or accessing the thumbnail array in any way?
We can currently change the current document with a simple src change, which we could trigger on one of the thumbnail click, or by scrolling to the very bottom.
Would there be any way to access any variables that could help in this way? Or safekeep the DOM elements themselves?
I would like to avoid merging pdfs if I can, especially if it would mean more work in the back, or looking for IE11 compatible solutions for the front.

**Comment by Epsiom** [comment]
I'm finally starting over from scratch from pdf.js since I'll have more control over it, and having multiple documents is a key feature.

**Comment by stephanrauh** [comment]
I'm closing the ticket and open a follow-up ticket for the thumbnail highlighting.
