### ISSUE TITLE
Not possible to highlight when document loaded as blob/base64 type

### ISSUE THREAD

**Issue by vijucalicut** [stephanrauh/ngx-extended-pdf-viewer#375]
--Not possible to highlight the given input on the document, when document loaded as blob/base64 type.
--When giving the file name as a static src it is working fine

**Comment by stephanrauh** [comment]
Unexpected. What do you mean be "highlight"? So far, I only know the highlighting of the find function. Are you referring to that?

**Comment by gokultrivandrum** [comment]
Yes, Same. We are using find functionality to highlight text. But for a downloaded file (assets files) find is working, But when we are trying with a Base64 / Blob one. It is not working.

**Comment by vijucalicut** [comment]
@stephanrauh          
 <ngx-extended-pdf-viewer **[src]="base64Data"** useBrowserLocale="true" [(page)]="highlightPage"
            [showDownloadButton]="false" [showOpenFileButton]="false" [showBookmarkButton]="false"
            [showPresentationModeButton]="true" [showFindButton]="true" [showBorders]="true" height="128vh"
            [showZoomButtons]="true" (updateFindMatchesCount)="updateFindMatchesCount($event)"
            (updateFindState)="updateFindState($event)" [handTool]="false"
            [showHandToolButton]="true">
          </ngx-extended-pdf-viewer>****
For the above src highlight is not working

The below one is working fine, because the file is accessing from local
<ngx-extended-pdf-viewer **[src]="'../../../../assets/mock-api-json/pdf-sample.pdf'"** useBrowserLocale="false"
            [(page)]="highlightPage" [showDownloadButton]="false" [showOpenFileButton]="false"
            [showBookmarkButton]="false" [showPresentationModeButton]="true" [showFindButton]="true"
            [showBorders]="true" height="128vh" [showZoomButtons]="true"
            (updateFindMatchesCount)="updateFindMatchesCount($event)" (updateFindState)="updateFindState($event)"
            [useBrowserLocale]="true" [handTool]="false" [showHandToolButton]="true">
          </ngx-extended-pdf-viewer>

**Comment by stephanrauh** [comment]
Maybe the text layer is missing. Try `[textLayer]="true"`.

**Comment by vijucalicut** [comment]
@stephanrauh Its working now  :)
