### ISSUE TITLE
Chaging the assets folder

### ISSUE THREAD

**Issue by Danyx1980** [stephanrauh/ngx-extended-pdf-viewer#376]
**Is your feature request related to a problem? Please describe.**
Currently the component seems to be looking for the assets folder in [root]/assets/pdf.min.js, the way my project is structured I'd like for it to look somewhere like [root]/someFolder/assets/pdf.min.js.

**Describe the solution you'd like**
An attribute, or config value, where I can specify an absolute or relative route where pdf.min.js is located.

**Describe alternatives you've considered**
Including the script manually somewhere else.

**Comment by stephanrauh** [comment]
Even today you can manually load pdf.js, pdf-worker.js, and viewer.js. The disadvantages are

- you don't benefit from the performance boost provided by the service worker
- you probably won't load the ES5 file for IE11 and MS Edge support (unless you add  a few extra lines to load the correct files depending on your browser).

If ´ngx-extended-pdf-viewer` detects the pdf.js files have already been loaded, if doesn't reload them: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/860ecd7442dbd6224e1f458f3610c85aee978b8c/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L525

**Comment by stephanrauh** [comment]
I've added a field `assetsFolder` to the `defaultOptions`.

**Comment by stephanrauh** [comment]
The feature has landed with version 4.0.0-alpha.6. See the documentation here: https://pdfviewer.net/pdfjs-versions

**Comment by nileshdevdas** [comment]
While creating a angular build we are using the --deploy-url  /xx  
We have updated the assetsFolder to point to xx/assets .  
Everything seems to work great except the locale.properties is still being searched in /assets/locale/locale.properties  and not in /xx/assets/locale.properties while the viewer.js pdf.js and other are picked correctly from the given location post adding the assets folder. We end up getting a lot of locale related warning and issues in the browser console when we load the pdf. The PDF Viewer works okay however the local support does not as the locale.properties is not pointing to the correct folder. 
Any help here would be appreciated 

The Header for Locale
![image](https://user-images.githubusercontent.com/24402152/98777094-25fab580-2416-11eb-80aa-e4a419b9512e.png)

The Header :- For JS loaded 
![image](https://user-images.githubusercontent.com/24402152/98776686-7291c100-2415-11eb-9208-c8902233fabd.png)

**Comment by stephanrauh** [comment]
This looks like a bug. Would you mind to open a new bug ticket and copy your error description into it? This makes tracking progress easier.

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
Just for the record: Nilesh kindly opened the follow-up ticket #548. THX!

**Comment by axell9641** [comment]
How can I change the default folder?

**Comment by stephanrauh** [comment]
You can configure it by setting `pdfDefaultOptions.assetsFolder`.
