### ISSUE TITLE
Not able to build after new update - npm run win-package

### ISSUE THREAD

**Issue by santoshprakash** [stephanrauh/ngx-extended-pdf-viewer#379]
![image](https://user-images.githubusercontent.com/1468777/86225632-1f2a7f00-bba8-11ea-8979-52f012b51f94.png)

**Comment by santoshprakash** [comment]
[error] Error: Could not find the implementation for builder @angular-devkit/build-ng-packagr:build
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (D:\MyWorkPlace\Library\social-document-framwork\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:57:19)
    at BuildCommand.initialize (D:\MyWorkPlace\Library\social-document-framwork\node_modules\@angular\cli\models\architect-command.js:138:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by stephanrauh** [comment]
Strange. Did you run `npm install` first?

**Comment by stephanrauh** [comment]
Maybe you've also run `npm update` or `npm audit fix`. The automated npm update frequently destroys the project by updating two Angular dependencies too eagerly. Last time it happened to me, it looked like so:

```json
"@angular-devkit/build-angular": "^0.901.7",  <<< must be a 0.13.x version (i.e. it's broken!)
    "@angular-devkit/build-ng-packagr": "0.13.9", <<< must be a 0.13.x version
```

**Comment by santoshprakash** [comment]
yes @stephanrauh I hv flowed all the instruction. But not good news for me. I cleaned up everything and close again. 
run npm I and then npm run win-package
Then Im getting this error. 

I was using the old version - 1.7.5, and I was working fine for me. 
"name": "ngx-extended-pdf-viewer",
   "version": "1.7.5",
  "license": "Apache-2.0",

I'm sharing my ng details, hope it helps to guide me
![image](https://user-images.githubusercontent.com/1468777/86323938-632a8c00-bc5b-11ea-9ddc-934607ccb799.png)

**Comment by santoshprakash** [comment]
**Full Steps : -** 

Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\MyWorkPlace>git clone https://github.com/stephanrauh/ngx-extended-pdf-viewer.git
Cloning into 'ngx-extended-pdf-viewer'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 7074 (delta 22), reused 4 (delta 1), pack-reused 7026R
Receiving objects: 100% (7074/7074), 63.97 MiB | 711.00 KiB/s, done.
Resolving deltas: 100% (4517/4517), done.
Checking out files: 100% (737/737), done.

D:\MyWorkPlace>cd ngx-extended-pdf-viewer

D:\MyWorkPlace\ngx-extended-pdf-viewer>code .

D:\MyWorkPlace\ngx-extended-pdf-viewer>npm install
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated rollup-plugin-json@3.1.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
npm WARN deprecated rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> node-sass@4.12.0 install D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\sprakash\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-64_binding.node

> core-js@2.6.11 postinstall D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.12.0 postinstall D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\node-sass
> node scripts/build.js

Binary found at D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> @angular/cli@10.0.1 postinstall D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\@angular\cli
> node ./bin/postinstall/script.js


> ng-packagr@4.7.1 postinstall D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\ng-packagr
> opencollective-postinstall

Thank you for using ng-packagr!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/ng-packagr/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\@angular\compiler-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@7.2.16 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.16 requires a peer of @angular/http@7.2.16 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.38.0 requires a peer of typescript@~3.7.2 but none is installed. You must install peer dependencies yourself.

added 1185 packages from 608 contributors and audited 1193 packages in 257.386s
found 29 vulnerabilities (24 low, 3 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

D:\MyWorkPlace\ngx-extended-pdf-viewer>npm update

D:\MyWorkPlace\ngx-extended-pdf-viewer>npm audit fix
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> node-sass@4.14.1 install D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\sprakash\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-64_binding.node

> node-sass@4.14.1 postinstall D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\node-sass
> node scripts/build.js

Binary found at D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> core-js@3.6.4 postinstall D:\MyWorkPlace\ngx-extended-pdf-viewer\node_modules\@angular-devkit\build-angular\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@7.2.16 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.16 requires a peer of @angular/http@7.2.16 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.38.0 requires a peer of typescript@~3.7.2 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.1000.1 requires a peer of @angular/compiler-cli@>=10.0.0-next.0 < 11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.1000.1 requires a peer of typescript@>=3.9 < 3.10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@10.0.1 requires a peer of @angular/compiler-cli@>=10.0.0-next.0 < 11 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@10.0.1 requires a peer of typescript@>=3.9 < 3.10 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.4.1 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular-devkit/build-angular@0.1000.1
added 448 packages from 185 contributors, removed 75 packages, updated 106 packages and moved 11 packages in 215.819s
fixed 8 of 29 vulnerabilities in 1193 scanned packages
  21 vulnerabilities required manual review and could not be updated

D:\MyWorkPlace\ngx-extended-pdf-viewer>
D:\MyWorkPlace\ngx-extended-pdf-viewer>npm run win-package

> ngx-pdf-viewer-demo@0.0.0 win-package D:\MyWorkPlace\ngx-extended-pdf-viewer
> ng b ngx-extended-pdf-viewer && rmdir dist /S && ng-packagr -p projects/ngx-extended-pdf-viewer/ng-package.json && xcopy /S/E/-Y projects\ngx-extended-pdf-viewer\src\assets dist\ngx-extended-pdf-viewer\assets\

? Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see http://angular.io/analytics. Yes

Thank you for sharing anonymous usage data. Would you change your mind, the following
command will disable this feature entirely:

    ng analytics project off

An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-ng-packagr:build
See "C:\Users\sprakash\AppData\Local\Temp\ng-j3Gj0i\angular-errors.log" for further details.
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngx-pdf-viewer-demo@0.0.0 win-package: `ng b ngx-extended-pdf-viewer && rmdir dist /S && ng-packagr -p projects/ngx-extended-pdf-viewer/ng-package.json && xcopy /S/E/-Y projects\ngx-extended-pdf-viewer\src\assets dist\ngx-extended-pdf-viewer\assets\`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ngx-pdf-viewer-demo@0.0.0 win-package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sprakash\AppData\Roaming\npm-cache\_logs\2020-07-02T06_52_53_702Z-debug.log

**Comment by santoshprakash** [comment]
I changed and try to build, then also I got the same error. 
 "@angular-devkit/build-angular": "0.13.9",
 "@angular-devkit/build-ng-packagr": "0.13.9",


> ngx-pdf-viewer-demo@0.0.0 win-package D:\MyWorkPlace\ngx-extended-pdf-viewer
> ng b ngx-extended-pdf-viewer && rmdir dist /S && ng-packagr -p projects/ngx-extended-pdf-viewer/ng-package.json && xcopy /S/E/-Y projects\ngx-extended-pdf-viewer\src\assets dist\ngx-extended-pdf-viewer\assets\

An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-ng-packagr:build
See "C:\Users\sprakash\AppData\Local\Temp\ng-dVVykR\angular-errors.log" for further details.
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngx-pdf-viewer-demo@0.0.0 win-package: `ng b ngx-extended-pdf-viewer && rmdir dist /S && ng-packagr -p projects/ngx-extended-pdf-viewer/ng-package.json && xcopy /S/E/-Y projects\ngx-extended-pdf-viewer\src\assets dist\ngx-extended-pdf-viewer\assets\`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ngx-pdf-viewer-demo@0.0.0 win-package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sprakash\AppData\Roaming\npm-cache\_logs\2020-07-02T07_00_25_453Z-debug.log

D:\MyWorkPlace\ngx-extended-pdf-viewer>ng b ngx-extended-pdf-viewer
An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-ng-packagr:build
See "C:\Users\sprakash\AppData\Local\Temp\ng-bLK6Z5\angular-errors.log" for further details.

D:\MyWorkPlace\ngx-extended-pdf-viewer>

**Comment by stephanrauh** [comment]
Oops - it seems I accepted a poisoned dependabot update. After pulling the current source to my PC, I ran into the same problem.

**Comment by stephanrauh** [comment]
@santoshprakash Now it works again, even on Windows.

**Comment by santoshprakash** [comment]
its work for me as well, thanks a lot :)
