### ISSUE TITLE
spread Odd

### ISSUE THREAD

**Issue by robertkup** [stephanrauh/ngx-extended-pdf-viewer#38]
Input for Spread Odd for two pages side by side

**Comment by stephanrauh** [comment]
Did I forget this? Thanks for pointing this out!

**Comment by stephanrauh** [comment]
Here I am again. Sorry for the long delay - moving to another town eat up all my available spare time. I hope you didn't give up ngx-extended-pdf-viewer in the meantime!

I've examined your issue this evening. What precisely do you want to achieve? There's a property called `showSpreadButton`. It hides the entire button group "even/odd page". Is this what you're looking for?

Another possibility: do you want to active the "spread odd" option by default when loading the page?

Thanks in advance,
Stephan

**Comment by robertkup** [comment]
The last one is what i need, to active the "spread odd" option by default when loading the page

**Comment by stephanrauh** [comment]
`[spread]` is going to be a three-valued attribute: `odd`, `even`, and `none` (or `off` and `false`).

**Comment by stephanrauh** [comment]
I've published a new version (0.9.20) including your feature.

Note that I'm still working on it. I haven't tested `(spread)` yet, and I didn't implement `[spread]`. But you can already define the spread mode at load time.

**Comment by robertkup** [comment]
Thx, will test it next week

**Comment by robertkup** [comment]
I tested it but the spreadOdd is not working. see attachment for the adjustment
<img width="719" alt="Schermafbeelding 2019-05-13 om 15 23 07" src="https://user-images.githubusercontent.com/22146970/57625147-94498800-7593-11e9-99ba-66f06d1fc5dc.png">

**Comment by stephanrauh** [comment]
Hey, that's almost a pull request! :)

Consider it done. I've already added the missing code, but I'd like to test it before publishing.

**Comment by stephanrauh** [comment]
I've shipped a new version, 0.9.23, including your bugfix. Please have a look at it and tell me if it works.

Thanks in advance,
Stephan

**Comment by robertkup** [comment]
it's not working only one time, something reset the value of the page.

**Comment by stephanrauh** [comment]
Sigh! I didn't manage to spare the time to look at your bug, but I'll do so ASAP.

**Comment by stephanrauh** [comment]
@robertkup I'm optimistic version 0.9.30 solves your bug. I've also added a demo to test the two-way-binding of `[(spread)]`.
