### ISSUE TITLE
Fullscreen option does not work on iPad and mobile devices in ionic

### ISSUE THREAD

**Issue by snagvenkar-cci** [stephanrauh/ngx-extended-pdf-viewer#390]
Hi,

I have used the ngx-extended-pdf-viewer for my ionic project. When I tested the pdf viewer on the iPad device I noticed that the fullscreen icon and the hamburger icon are not clickable. I have followed the solution you suggested in https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/215. I have added the below CSS to make the fullscreen icon visible on iPad:
#presentationMode {
 display: block !important;
}
The icon is now visible but the fullscreen option does not work. Please check the attached screenshot.

![iPad_ngx-extended-pdf-viewer](https://user-images.githubusercontent.com/19834951/86606562-c868df00-bfc5-11ea-8255-34658823f61b.jpg)

**Comment by stephanrauh** [comment]
Is this really your first question on GitHub in years? I feel deeply honored you've chosen ngx-extended-pdf-viewer to raise an issue!

May I ask which version of Ionic you're using? And which version of ngx-extended-pdf-viewer? Plus, does the bug also occur on the desktop with a small browser window?

Best regards,
Stephan

**Comment by snagvenkar-cci** [comment]
Pleasure is all mine, sir.
I'm using ionic version 4.11.2 and ngx-extended-pdf-viewer version 2.1.2
The bug does not occur on a small browser window on the desktop, it only occurs on iPad and mobile devices.

**Comment by stephanrauh** [comment]
THX! Fixing a but that only happens on mobile devices is always difficult, but I'll try my best. 

However, I'll only fix errors in the current version (currently 4.0.0-alpha). This is a leisure-time project, and we all know there's always too little leisure-time. :) If you really need support for an older version, I'd kindly ask you to talk my employer to talk me into helping you. But generally speaking, newer versions are better, so I hope I can convince you to update to the current version.

**Comment by snagvenkar-cci** [comment]
When I tried updating the ngx-extended-pdf-viewer to 4.0.0 version to check if the viewer works fine, I got the following error:
![ngx-extended-pdf-viewer-4 0-error](https://user-images.githubusercontent.com/19834951/86749479-eaf90780-c05a-11ea-93ea-e4d520e6a3b0.jpg)

Can you please help with this?

Thanks,
Sneha

**Comment by stephanrauh** [comment]
Just a guess: maybe npm doesn't recognize the alpha versions properly. Try 4.0.0-alpha.9. 

BTW: I intend to ship the final version soon (this week, if everything works according to the plan).

**Comment by stephanrauh** [comment]
Please have a look at the reproducer I've prepared for you. The fullscreen mode works on my iPad. It looks a bit weird because the rest of the application remains visible, but as far as I see, that's not the bug you're reporting.

Here's the source code of the reproducer: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue390-ionic-fullscreen

It's a standard Ionic 6 project, so you can simply clone it, run `npm install`, and `ionic serve --external`.

The only difference I see is that I didn't install the app locally on my iPad, and that I enabled the fullscreen mode by an attribute:

```html
<ngx-extended-pdf-viewer
  [src]="'/assets/blind-text-collection.pdf'"
  showPresentationModeButton="true"
  useBrowserLocale="true"
  height="80vh"
></ngx-extended-pdf-viewer>
```

Does this help you?

**Comment by snagvenkar-cci** [comment]
Hi,

I tried running this project (issue390-ionic-fullscreen) on the iPad device (via Xcode) using the command: **ionic cordova emulate ios --livereload --target "<deviceName>"**. But the fullscreen mode does not work. The icon itself is not visible. The fullscreen mode works fine on the browser.
Below is the screenshot of the app in the iPad:
![iPad-app](https://user-images.githubusercontent.com/19834951/87973634-73a98600-cae6-11ea-85aa-0986e516baec.png)

**Comment by stephanrauh** [comment]
OK, that narrows down things a bit. At the moment, I'm confused. None of the demos at https://pdfviewer.net shows the "presentation mode" button. Neither does it appear in the right-hand side kebab menu. 

As for the Xcode emulator: how much work is it to get this up and running? I've never done this before, and for some reason unknown, my MacBook refuses to communicate with my iOS devices. I can't even charge them from the computer. Can I run the emulator nonetheless?

**Comment by stephanrauh** [comment]
Oops - the default value of `[showPresentationModeButton]` is `false`. IMHO, that doesn't make sense, but I'm reluctant to change that default because it's already two years old. Did you set `[showPresentationModeButton]="true"`?

**Comment by stephanrauh** [comment]
The Cordova topic is pretty new to me (it used to be all the rave at my company some time ago, but for some reason, nobody's using it today), but this issue seems to indicate that Cordova simply can't activate the full-screen mode:

https://github.com/ionic-team/capacitor/issues/1834

**Comment by snagvenkar-cci** [comment]
> Oops - the default value of `[showPresentationModeButton]` is `false`. IMHO, that doesn't make sense, but I'm reluctant to change that default because it's already two years old. Did you set `[showPresentationModeButton]="true"`?

Yes it is set to true.

**Comment by snagvenkar-cci** [comment]
> The Cordova topic is pretty new to me (it used to be all the rave at my company some time ago, but for some reason, nobody's using it today), but this issue seems to indicate that Cordova simply can't activate the full-screen mode:
> 
> [ionic-team/capacitor#1834](https://github.com/ionic-team/capacitor/issues/1834)

Does this mean that ios devices i.e. iPad and iPhone does not support full-screen mode?

**Comment by stephanrauh** [comment]
I don't know. But it might be so. The Ionic capacitor tickets seems to indicate that. But you're the expert on Cordova, not me! 

I only familiar with the city of Cordoba (worth a visit!), not the framework :)

**Comment by stephanrauh** [comment]
I'm not sure there's anything to do for me. Maybe ng2-pdfjs-viewer is an alternative for you? https://www.npmjs.com/package/ng2-pdfjs-viewer
