### ISSUE TITLE
Is this possible to define a custom PDFDataRangeTransport ?

### ISSUE THREAD

**Issue by f-malet** [stephanrauh/ngx-extended-pdf-viewer#391]
Hello,

First of all thanks for your wonderful library. It is really helpfull.

My question is : is this possible to define a custom PDFDataRangeTransport (object of pdf.js lib) with ngx-extended-pdf-viewer and how to implement it because I have already made this directly with pdf.js but if i could reuse your library it will be the top
I want to custom my PdfDatarangeTransport because I want to stream the PDF and later crypt / encrypt the received data from the streamer.
I try to pass an PDFDataRangeTransport object to attribute [src] but it doesn't work (because Pdf.js accept a PDFDataRangeTransport object in the getDocument Method.
I have this error : 
ERROR ReferenceError: ServiceWorkerOptions is not defined
    at NgxExtendedPdfViewerComponent.openPDF (ngx-extended-pdf-viewer.js:1977)
    at ngx-extended-pdf-viewer.js:1684
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at timer (zone-evergreen.js:2552)

Thank you for your help ;)

**Comment by stephanrauh** [comment]
Thanks for the kind words!

I'm confused: you error description doesn't match the stack trace. Judging from the stack trace, the error happens here:

![image](https://user-images.githubusercontent.com/3045767/86626684-5396a480-bfc7-11ea-9999-f3a8869eeeff.png)

The `[src]` attribute is first accessed roughly 200 lines later. 

Apart from that, your request sounds simple enough. No idea why it isn't supported yet. Can you send me a reproducer, please, or add the source code throwing the error?

Truth to tell, the error message sounds like `viewer.js` hasn't been loaded before accessing it. Would you mind to check this, too?

Best regards,
Stephan

**Comment by f-malet** [comment]
Hello,

I think the error comes from that I need to access to pdfjslib to instantiate transport : 
const transport = new pdfjsLib.PDFDataRangeTransport(size, []); 

And i had to install pdfjs-dist to do that while your library have already this but i don't know how to call it ... 

Here the code in javascript with pdf.js that works fine. I hope this could help you.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PDF</title>

    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/core.min.js"></script>
</head>
<body>
<canvas id="the-canvas"></canvas>
<script>

    var urlLicence = 'http://localhost:8080/licences/pdf';
    var urlFile = 'http://localhost:8080/streamer/pdf';

    // Loaded via <script> tag, create shortcut to access PDF.js exports.
    var pdfjsLib = window['pdfjs-dist/build/pdf'];
    pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';


    async function fetchLicence(pathToResource) {
        return fetch(pathToResource, {
            method: 'get'
        })
            .then(checkContentLength)
            .catch(console.log);
    }

    function checkContentLength(response) {
        return response.json().then((data) => {
            return data.size
        })

    }

    async function getRequest(pathToResource, begin, end) {

        return fetch(pathToResource, {
            method: 'get',
            headers: {
                "range": `bytes=${begin}-${end}`
            }

        })
            .then(checkData)
            .catch(console.log);
    }

    function checkData(response) {
        var rangeHeader = response.headers.get('Content-Range');
        const matches = /bytes (\d+)-(\d+)\/(\d+)/.exec(rangeHeader);

        return response.arrayBuffer().then((buffer) => {
            let result = {
                "size": buffer.byteLength,
                "begin": parseInt(matches[1], 10),
                "data": buffer
            }
            return result
        })


    }

    function _base64ToArrayBuffer(base64) {
        var binary_string = window.atob(base64);
        var len = binary_string.length;
        var bytes = new Uint8Array(len);
        for (var i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        return bytes.buffer;
    }

    async function initPdf() {

        const size = await fetchLicence(urlLicence)


        const transport = new pdfjsLib.PDFDataRangeTransport(size, []);

        transport.requestDataRange = function (begin, end) {

            getRequest(urlFile, begin, end).then((data) => {

                transport.onDataProgress(data.data.byteLength);
                //  transport.onDataRange(begin, output);
                transport.onDataRange(begin, data.data);


            })
        };

        var loadingTask = pdfjsLib.getDocument(transport);


        loadingTask.promise.then(function (pdf) {
            console.log('PDF loaded');

            // Fetch the first page
            var pageNumber = 1;
            pdf.getPage(pageNumber).then(function (page) {
                console.log('Page loaded');

                var scale = 1.5;
                var viewport = page.getViewport({scale: scale});

                // Prepare canvas using PDF page dimensions
                var canvas = document.getElementById('the-canvas');
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                // Render PDF page into canvas context
                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };
                var renderTask = page.render(renderContext);
                renderTask.promise.then(function () {
                    console.log('Page rendered');
                });
            });
        }, function (reason) {
            // PDF loading error
            console.error(reason);
        });
    }

    initPdf()
</script>
</body>
</html>
```

**Comment by stephanrauh** [comment]
After initializing `NgxExtendedPdfViewerComponent`, the lib is available in the window name space:

```js
new window.pdfjsLib.PDFDataRangeTransport(size, []);
```
If you need to access `pdfjsLib` earlier, you'll want to load `/assets/pdf-min.js` or `/assets/pdf-es5.min.js` yourself. I suppose the easiest way to do so is to add it to the `scripts` of the `angular.json`.

**Comment by f-malet** [comment]
Thanks for the answer. I try to call new window.pdfjsLib.PDFDataRangeTransport(size, []); but I have this error : 
Property 'pdfjsLib' does not exist on type 'Window & typeof globalThis'

My code is in a service so, i add these lines in app/module
```
providers: [
    { provide: Window, useValue: window}
],  
```
and in my service to the constructor 
```
constructor(private http: HttpClient, private window: Window) {

}
```
And i have this error when comiling with this line : 
```
const transport = new window.pdfjsLib.PDFDataRangeTransport(10, []);
 ERROR in src/app/shared/services/reader-tools.service.ts:26:34 - error TS2339: Property 'pdfjsLib' does not exist on type 'Window & typeof globalThis'.
    
26     const transport = new window.pdfjsLib.PDFDataRangeTransport(10, []);
```
Do you have an idea why it doesn't work ? Maybe I call to soon. You tell me that the lib is available after NgxExtendedPdfViewerComponent is initalized but how can I be sure it is initialized ? Because i try to pass the object transport to src attribute ... so I need to create my transport before initializing ?

Do you think a transport object can be use like in pdf.js (getDocument) via ngw extended viewer pdf in src attribute ?

**Comment by stephanrauh** [comment]
I wouldn't try to have `window` injected by DI. Maybe that's even possible, but a simple

`new (window as any).pdfjsLib.PDFDataRangeTransport(size, []);``

does the trick just as well.

**Comment by stephanrauh** [comment]
You may be right with the timing bit (although our error message is a compiler message, not a runtime message).

You can test my code snippets in the browser. Open the developer tools, go to the "console" tab, and paste my first code snippet.

**Comment by f-malet** [comment]
I execute the code you provided in a page which have a player well loaded without errors 
`const transport = new (window as any).pdfjsLib.PDFDataRangeTransport(10, []);`

And I have this error :
`
const transport = new (window as any).pdfjsLib.PDFDataRangeTransport(10, []);
VM11880:1 Uncaught SyntaxError: Unexpected identifier`

**Comment by stephanrauh** [comment]
You seem to be confused by TypeScript and JavaScript. Your Angular source code is (usually) TypeScript. By default, there's no type assigned to `window` in TypeScript, so you have to add a type cast. That's the `(window as any)` bit.

The developer console of your browser uses JavaScript. So adding a type cast results in a syntax error. But JavaScript is a dynamic language, so you can simply access `window. pdfjsLib`. If it's there, `transport` has a useful value. If it's not there, your example results in an "undefined is not a function" error message.

**Comment by stephanrauh** [comment]
Your latest answer makes me believe you've solved the problem (or you're going to solve it soon). So I'm closing this ticket now.

**Comment by f-malet** [comment]
Thank you for the help. The previous problem is solved. 

Can you confirm that a PDFDataRangeTransport object can be pass to src attribute ?

If the library accepts transport object, my PDFDataRangeTransport object is not good because I have this error :

ERROR Error: Uncaught (in promise): Error: Invalid parameter object: need either .data, .range or .url
Error: Invalid parameter object: need either .data, .range or .url
    at getDocument (pdf.js:1754)
    at Object.open (app.js:779)
    at NgxExtendedPdfViewerComponent.openPDF (ngx-extended-pdf-viewer.js:2206)
    at ngx-extended-pdf-viewer.js:1684
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)

Have a good day ;)

**Comment by stephanrauh** [comment]
Hm... there must be something wrong with your PDFDataRangeTransport object. Maybe it's undefined or null?

The error message stems from this code:

```javascript
function getDocument(src) {
  const task = new PDFDocumentLoadingTask();

  let source;
  if (typeof src === "string") {
    source = { url: src };
  } else if (isArrayBuffer(src)) {
    source = { data: src };
  } else if (src instanceof PDFDataRangeTransport) {
    source = { range: src };
  } else {
    if (typeof src !== "object") {
      throw new Error(
        "Invalid parameter in getDocument, " +
          "need either Uint8Array, string or a parameter object"
      );
    }
    if (!src.url && !src.data && !src.range) {
      throw new Error(
        "Invalid parameter object: need either .data, .range or .url"
      );
    }
    source = src;
  }
```

Several lines before the error message is thrown, there's an `if` branch dealing with `PDFDataRangeTransport`. So I suggest you set a breakpoint in the `getDocument()` method.

**Comment by f-malet** [comment]
Yes it come from here. The problem is that in my angular component i have an PDFDataRangeTransport object (like below)

```
PDFDataRangeTransport {length: 114889315, initialData: Array(0), progressiveDone: false, _rangeListeners: Array(0), _progressListeners: Array(0), …}
initialData: []
length: 114889315
progressiveDone: false
requestDataRange: (begin, end) => {…}
_progressListeners: []
_progressiveDoneListeners: []
_progressiveReadListeners: []
_rangeListeners: []
_readyCapability: {promise: ZoneAwarePromise, resolve: ƒ, reject: ƒ}
__proto__: Object
```

But when i look the object in pdf.js lib getDocument() methods, src is a standard object and not PDFDataRangeTransport. 

So this test failed 
if (src instanceof PDFDataRangeTransport) { 
}
and i have this error ... 
 "Invalid parameter object: need either .data, .range or .url"

Here the object that didn't match with i passed to ngx-extended-pdf-viewer src attribute. Do you know why  ?
{range: {…}}
range:
cMapPacked: true
cMapUrl: () => '../' + pdfDefaultOptions.assetsFolder + '/cmaps/'
disableAutoFetch: false
disableFontFace: false
disableRange: false
disableStream: false
docBaseUrl: ""
fontExtraProperties: false
isEvalSupported: true
maxImageSize: -1
password: undefined
pdfBug: false
verbosity: 1
__proto__: Object
