### ISSUE TITLE
ngx-extended-pdf-viewer on Server side

### ISSUE THREAD

**Issue by Botz1991** [stephanrauh/ngx-extended-pdf-viewer#393]
Hello!
First of all thanks for your library!

Is it possible to use this library on server side without visual rendering?
This is what i would like to do on the Server side (nodejs):

1. Download a pdf file from an object storage.
2. Use a find(string,options) function with a **fuzzy search** enabled
3. Extract the original found string from the pdf file (through find() function), save it and send it to the Client

It's a kind of preprocessing to not use fuzzy search on the Client side, because it's too slow

Thanks for your help!
Best regards,
Alessio

**Comment by stephanrauh** [comment]
Did you already open the PDF file in a text editor? There's no guarantee, but maybe you can find the text using the raw file.

**Comment by stephanrauh** [comment]
`ngx-extended-pdf-viewer` is a client-side library. However, you can use the base library, `pdf.js` with node.js. Maybe https://github.com/mozilla/pdf.js/tree/master/examples/node gives you a head start.
