### ISSUE TITLE
when changing [url] a new request is sent without considering [httpHeaders]

### ISSUE THREAD

**Issue by Zippovich** [stephanrauh/ngx-extended-pdf-viewer#394]
<ngx-extended-pdf-viewer
        [src]="pdfUrl"
        [httpHeaders]="pdfHttpHeaders"
        useBrowserLocale="true"
        style="display: block; height: calc(100vh - 112px);"></ngx-extended-pdf-viewer>

Request URL: ...../DocumentForm/Preview?formId=12d8c05c-ac76-4fd1-a39c-bffb928ebb76
Request Method: GET
Status Code: 200 OK

Request URL: ...../DocumentForm/Preview?formId=689b6dcc-52ba-4b16-af02-aa670bbfa50c
Request Method: GET
Status Code: 401 Unauthorized

**Comment by stephanrauh** [comment]
Oops. That's also true for `authorization`, `password`, and `logLevel`.

**Comment by stephanrauh** [comment]
Fixed. Please try version 4.0.0-alpha.10.

Probably there's still something to do. When the access token expires, you can't pass a new token to the PDF viewer. Can you verify if this is true?

**Comment by stephanrauh** [comment]
Sorry, I was mistaken... of course `[authorization]`, `[httpHeaders]`, `[password]`, and `[logLevel]` are updated. It was just the documentation that was wrong. I'm closing this ticket now.

**Comment by Zippovich** [comment]
Thank you! It was very fast.
When the access token expires, then a 403 or 401 error will occur, in which case the error is correct.

**Comment by stephanrauh** [comment]
That's having a few days off for you. In the age of Corona, there's nothing to do but to stay at home. :(

I assume it's possible to renew the access token. It should be updated automatically by `[authorization]` or `[httpHeaders]`. If that doesn't work, just tell me.

Best regards,
Stephan
