### ISSUE TITLE
Src attribute and object PDFDataRangeTransport

### ISSUE THREAD

**Issue by f-malet** [stephanrauh/ngx-extended-pdf-viewer#398]
Hello,
First of all, thank you for your library. 

I would like to use because it simplifies the job but I can't. Because I would like to initialize pdf.js with a PDFDataRangeTransport object like the original library allow me to do.
So I pass to ngx-extended-pdf-viewer src attribute an PDFDataRangeTransport object but when I debug the code, I see that in pdf.js lib the object received in getDocument() is not the object given to src attribute.
I give an PDFDataRangeTransport object like that : 
```
PDFDataRangeTransport {length: 114889315, initialData: Array(0), progressiveDone: false, _rangeListeners: Array(0), _progressListeners: Array(0), …}
initialData: []
length: 114889315
progressiveDone: false
requestDataRange: (begin, end) => {…}
_progressListeners: []
_progressiveDoneListeners: []
_progressiveReadListeners: []
_rangeListeners: []
_readyCapability: {promise: ZoneAwarePromise, resolve: ƒ, reject: ƒ}
__proto__: Object

```
And I received a standard object like this (which seems to be a pdfDefaultOptions object) : 
range:
```
cMapPacked: true
cMapUrl: () => '../' + pdfDefaultOptions.assetsFolder + '/cmaps/'
disableAutoFetch: false
disableFontFace: false
disableRange: false
disableStream: false
docBaseUrl: ""
fontExtraProperties: false
isEvalSupported: true
maxImageSize: -1
password: undefined
pdfBug: false
verbosity: 1
proto: Object
```
So, like pdf.js lib test the type of src and the object is not the good I have this error (which is normal) : 

`Invalid parameter object: need either .data, .range or .url`

```
function getDocument(src) {
  const task = new PDFDocumentLoadingTask();
  let source;

  if (typeof src === "string") {
    source = {
      url: src
    };
  } else if ((0, _util.isArrayBuffer)(src)) {
    source = {
      data: src
    };
  } else if (src instanceof PDFDataRangeTransport) {
    source = {
      range: src
    };
  } else {
    if (typeof src !== "object") {
      throw new Error("Invalid parameter in getDocument, " + "need either Uint8Array, string or a parameter object");
    }

    if (!src.url && !src.data && !src.range) {
      throw new Error("Invalid parameter object: need either .data, .range or .url");
    }

    source = src;
  }
```

I saw that the src attribute is typed : 
`src: string | ArrayBuffer | Blob | Uint8Array`
So i had my type : 
`src: string | ArrayBuffer | Blob | Uint8Array | PDFDataRangeTransport;`
But i can't find the code behind the treatment of src attribute.
So i'm wondering if this is possible via your library to call getDocument() with a PDFDataRangeTransport object via src attribute of other ways and if after this call, will the library fully work ?

**Version info**
- 4.0.0-alpha.9

**Desktop (please complete the following information):**
 - Chrome (linux)

Thank you for your help

**Comment by stephanrauh** [comment]
Maybe I've found something. Please update to version 4.0.0-alpha.12. There's no easy way to detect a PDFDataRangeTransport object, so you have to define the `[src]` object as `{range: pdfDataTransport}`.

My example source code doesn't work because I didn't implement the PDFDataRangeTransport object properly, but apart from that, it looks promising:

```typescript
import { Component, OnInit, AfterViewInit } from '@angular/core';

@Component({
  selector: 'app-simple',
  templateUrl: './simple.component.html',
  styleUrls: ['./simple.component.css']
})
export class SimpleComponent implements AfterViewInit {

  public src: any;

  constructor() {}

  ngAfterViewInit() {
    setTimeout(() => {
      console.log((window as any).pdfjsLib);
      console.log((window as any).pdfjsLib.PDFDataRangeTransport);
      this.src = {range:  new (window as any).pdfjsLib.PDFDataRangeTransport(100, [])};
    }, 1000)
   }
}
```

```html
<ngx-extended-pdf-viewer
    [src]="src"
    [height]="'90vh'"
    [useBrowserLocale]="true"
    [textLayer]="true"
    [showHandToolButton]="true">
</ngx-extended-pdf-viewer>
```

**Comment by f-malet** [comment]
Hello,

So I update my ngx-extended-pdf-viewer to the last including your modification : 4.0.0-alpha.12 and I did what you say and it works! 

So now, I have a streamer that crypt the data send and my player receive the data, decrypt and the PDF displays well ;)
Ps: Now I have to test if all standard features works (search it seams to be ok ...)

Thanks a lot ;)

**Comment by stephanrauh** [comment]
Glad to hear this! This was a difficult challenge indeed!

You're testing the standard feature? That's great news, because I want to stop publishing alpha versions and call it a real version soon. Every help is welcome!
