### ISSUE TITLE
Display the number of find results

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#4]
Is it possible to add this functionality? It doesn't show the matches right now (for example 3 of 10 matches)

https://mozilla.github.io/pdf.js/web/viewer.html

Original ticket reported by @javid-abd.

**Comment by stephanrauh** [comment]
@javid-abd I've just published version 0.9.6. This version contains several updates, such as improved internationalization and using the official release 2.0.943. 

Please test if the bug has been fixed. Actually, the number of find results was already shown on my PC before the update, so maybe I've got you wrong or there's another bug I'm not aware of. In any case, please report back so I can close the ticket.

Thanks in advance,
Stephan

**Comment by javid-abd** [comment]
Thanks for the update. It works, however it massively changes all font-size (make them smaller)

**Comment by stephanrauh** [comment]
Oh - you're right. I'll fix it this evening.

**Comment by stephanrauh** [comment]
Please try version 0.9.7. It should solve the problem. Please report back so I know whether I can call it a 1.0.0 soon.

Thanks in advance,
Stephan

**Comment by javid-abd** [comment]
Thanks for the update. I wonder it's possible to set default zoom to Automatic Zoom? Every time I open a pdf document, it shows  zoom % that I previously used

**Comment by stephanrauh** [comment]
You're right - the semi-persistent zoom is a nuisance in many usecases (and probably a blessing in many other usecases). I've opened a ticket to address this (#11).
