### ISSUE TITLE
HandTools

### ISSUE THREAD

**Issue by ocevandaele** [stephanrauh/ngx-extended-pdf-viewer#40]
Hello,
How can do so to select the default "main" tools ?
Thanks !

**Comment by stephanrauh** [comment]
First of all: sorry for answering late. I was moving to another town during the last couple of months. That left little time for open source.

I'm sorry again, but I don't understand your question. What do you want to achieve? Would you mind to elaborate what the default main tools are, and how you want to select them? Are you thinking about a programmatic approach or a user action?

**Comment by stephanrauh** [comment]
OK, I've been a bit slow, but now I believe I've got it. Working on it!

**Comment by stephanrauh** [comment]
`[handTools]` ]published with version 0.9.17 just a minute ago
