### ISSUE TITLE
Page changing issue when binding to page attribute

### ISSUE THREAD

**Issue by MKITConsulting** [stephanrauh/ngx-extended-pdf-viewer#404]
When you bind to the `page` attribute with both a getter and setter like  `[(page)]` the scrolling inside the PDF breaks and jumps to the page beginning whenever you come close to the new page on scrolling. 

I tried to circumvent this behavior by not using this kind of binding but `(pageChange)` event instead. This works like using a `(page)` binding but I also want to be able to set the page number from the outside. Using `[page]` results in the same problem as described above because when the page change event is triggered on half on the scroll view of the new page, the page will jump to the new page. This prohibits smooth page scrolling.

I then tried to set the page attribute by ViewChild binding the ngx-extended-pdf-viewer component and setting the page like this:
```
@ViewChild('pdfComponent') private pdfComponent: NgxExtendedPdfViewerComponent;
...
this.pdfComponent.page = newPageNumber;
```

But this doesn't affect any changes. It would be cool to have a setter that enables to set the PDF.js `PDFViewerApplication.page` attribute in order to change the page.

**Comment by stephanrauh** [comment]
Oops. It shouldn't be that way. I suppose `pdf.js` sends a `(pageChange)` event when you're scrolling - even if the page hasn't changed yet. And the two-way binding mean that `[page]` is set when `(pageChange)` fires. That, in turn, causes `pdf.js` to scroll back to the beginning of the page.

**Comment by stephanrauh** [comment]
So maybe you can prevent this by setting the new page only if it's different from the old page number. Something like this:

```typescript
public set pageNumber(p: number) {
   if (_pageNumber !== p) {
     _pageNumber = p;
  }
}
````

Can you test if this approach works?

**Comment by MKITConsulting** [comment]
Thanks for your input! I got it working with this:

```html
<ngx-extended-pdf-viewer ... 
     [(page)]="activePageNumber">
</ngx-extended-pdf-viewer>
```

```ts
  constructor(private changeDetectorRef: ChangeDetectorRef,...) {...}

  _activePageNumber: number = 1;
  public get activePageNumber(): number {
      return this._activePageNumber;
  }
  public set activePageNumber(p: number) {
      /*if (this._activePageNumber != p) {
          this._activePageNumber = p;
      }*/
  }
  public navigateToPage(newPage: number) {
      this._activePageNumber = newPage;
      this.changeDetectorRef.detectChanges();
  }
```

**Comment by stephanrauh** [comment]
Great! If I read your source code correctly, my idea was almost successful. That gives me hope I can solve the problem in the library itself.

Thanks for the hint!

**Comment by stephanrauh** [comment]
I can't reproduce your bug. However, I've managed to reproduce an `ExpressionChangedAfterItHasBeenCheckedError`. That's probably just as well. I've added a guard preventing `(page)` and ´(pageLabel)` to fire if nothing has changed. I'm positive that fixes your bug, too.

**Comment by stephanrauh** [comment]
After publishing version 4.0.5, the bug *should* be gone. For some reason, it's not possible to use both `[(page)]` and  `[(pageLabel)]` at the same time. I've documented this in the showcase.
