### ISSUE TITLE
While rendering  ngx-exted-pdf-viewer seeing .replaceAll is not a function ERROR for thumbnails in Chrome Version 84

### ISSUE THREAD

**Issue by dheerajm91** [stephanrauh/ngx-extended-pdf-viewer#408]
Hello,

Seeing the console error while rending the pdf viewer and due to which Thumbnails are not loading.
Browser: Using Chrome Version:  84.0.4147.89 (Official Build) beta (64-bit).
Package.json:  "ngx-extended-pdf-viewer": "^4.0.1"
Angualr version: 10.0.3

Using the following code:
<ngx-extended-pdf-viewer [src]="'https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf'" useBrowserLocale="true" height="80vh"></ngx-extended-pdf-viewer>

Steps to Reproduce:
Install new angualr 10 app.
Add the package, update the Angualr.json  and add the module

Console Error:
pdf_thumbnail_viewer.js:201 Unable to initialize thumbnail viewer TypeError: inner.replace(...).replace(...).replaceAll is not a function
    at PdfSidebarContentComponent.createThumbnail (pdf-sidebar-content.component.ts:76)
    at PdfSidebarContentComponent.window.pdfThumbnailGenerator (pdf-sidebar-content.component.ts:41)
    at new t.PDFThumbnailView (pdf_thumbnail_view.js:127)
    at pdf_thumbnail_viewer.js:177
    at ZoneDelegate.invoke (zone.js:386)
    at Object.onInvoke (core.js:27149)
    at ZoneDelegate.invoke (zone.js:385)
    at Zone.run (zone.js:143)
    at zone.js:891
    at ZoneDelegate.invokeTask (zone.js:421)

Please find the screen shots attached below where on click of side bar we see a"set Image" of undefined error and the thumbnails are not loading. Please help me to resolve this issue.

![image](https://user-images.githubusercontent.com/25700737/87622426-b9caa800-c6e8-11ea-9c73-0b5e89d2486e.png)
![image](https://user-images.githubusercontent.com/25700737/87623073-2eeaad00-c6ea-11ea-8379-21673ea1d778.png)

**Comment by dheerajm91** [comment]
Also, please find the screen shot below for thumbnails not loading when menu is opened
![image](https://user-images.githubusercontent.com/25700737/87623034-12e70b80-c6ea-11ea-9ddb-98b8da060811.png)

**Comment by stephanrauh** [comment]
I've fixed the bug in version 4.0.2.

For some reason, this bug doesn't occur on every Chrome. `replaceAll` is going to be implemented in Chrome 85 - so maybe my Chromium browser is already a version ahead. Sorry for the inconvenience!

**Comment by dheerajm91** [comment]
Thank you. It works fine now :)
