### ISSUE TITLE
Unable to load a binary PDF (blob) 

### ISSUE THREAD

**Issue by marioestradarosa** [stephanrauh/ngx-extended-pdf-viewer#41]
Hi there, 

First of all, thanks a lot for this great plugin. I have been able to work with it from NCompass document management system and it is being rendered properly. However, I have a problem with another backend that is sending me over the blob instead of base64.

**Description**
I am receiving from a backend a PDF file and am unable to load into **ngx-extender-pdf-viewer.**

```ts
setPDFDataFromBinary(arg: any) {
    const blob = new Blob([arg], {type: 'application/pdf'});
    this.pdfData = URL.createObjectURL(blob);
  }
```
And then in the stmt viewer component I have:

```ts
 this.stmtPDFBinaryData  = this.mySession.pfData;

---html--
<ngx-extended-pdf-viewer
  [showPrintButton]="false"
  [showPropertiesButton]="false"
  [showBookmarkButton]="false"
  [showOpenFileButton]="false"
  [src]="stmtPDFBinaryData"
  useBrowserLocale="true">
</ngx-extended-pdf-viewer>
```

**Current Behavior:**
This shows in the console:
```ts
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at viewer.js:1101
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
```

**PLEASE NOTE:**
It is not the backend sending the PDF because I am able to download the file and view it in the browser using the following method:

```ts
 downloadFile(arg: any) {
    const blob = new Blob([arg], {type: 'application/pdf'});
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.download =
      this.accountSummaryAppResponse.accountNumber +
      '-' +
      this.statementDate +
      '.pdf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
```

**Comment by marioestradarosa** [comment]
I am closing this as I found the problem. I had to specify `ArrayBuffer`  as `json` in the Angular 7 http client as follows. That did the trick:

```ts
return this.http
      .post<any>(URL, JSON.stringify(args), {
        headers: httpHeaders,
        responseType: 'ArrayBuffer' as 'json',
      })
      .toPromise();

```

**Comment by stephanrauh** [comment]
@marioestradarosa Thanks for opening the issue - not to mention solving it yourself. :)

Remains the question if I can improve the documentation. What's your opinion?

**Comment by marioestradarosa** [comment]
HI @stephanrauh , in general every thing LGTM. However, there is a window for improvement in the examples on how to integrate with PDF content that will be streamed from APIS.
