### ISSUE TITLE
how to hide print progress bar?

### ISSUE THREAD

**Issue by dheerajm91** [stephanrauh/ngx-extended-pdf-viewer#411]
Hello,

**Issue 1:**
[showBorders] property is not working as expected.I have set the [showBorders] to false and i still see the borders. I set it to true and also i still see the borders. 

**Issue 2: Print issue**
import {NgxExtendedPdfViewerService } from 'ngx-extended-pdf-viewer';
Then tried: 
  print() {
    this.printService.print();
  }
how to hide the print progress bar? please suggest - this is very important feature for me.

I have a requirement where i have to just see the standlone PDF with no tool bar and trigger print programatically.

Please help me to resolve these 2 issue or suggest the possible solution.

**Please find the code i am using below:**
 <ngx-extended-pdf-viewer [src]="safeUrl"
    useBrowserLocale="true"
    [showDownloadButton]="false"
    [backgroundColor] ="'white'"
    [showBorders]="showBorders"
    [showPrintButton]="false"
    [showOpenFileButton]="false"
    [handTool]="false"
    [showRotateButton]="false"
    [showPresentationModeButton]="false"
    [showFindButton] = "false"
    [showBookmarkButton]="false"
    [showPropertiesButton]="false"
    [showPagingButtons]="false"
    [contextMenuAllowed]="false"
    [showSidebarButton]= "false"
    [showZoomButtons]="false"
    [showSpreadButton]="false"
    [showScrollingButton]="true"
    [showSecondaryToolbarButton]="false"
    (pageRendered)="callbacktest($event)"></ngx-extended-pdf-viewer>  

Screen shot:
![image](https://user-images.githubusercontent.com/25700737/87840456-5f0a8b00-c865-11ea-84f6-551a43d991f8.png)

Thank you
DJ

**Comment by stephanrauh** [comment]
Would you mind to open a ticket for each issue, please? Otherwise I always loose track when the discussion get longer and longer. It's easy to miss an issue in a multi-issue ticket.

**Comment by stephanrauh** [comment]
The showcase removes the border without problems: https://pdfviewer.net/display-options

**Comment by stephanrauh** [comment]
As for the progress bar, have a look at this demo: https://pdfviewer.net/custom-print-dialog

Basically, it hides the progress bar using this CSS snippet:

```CSS
.pdf-wrapper #printServiceOverlay .dialog {
  display: none !important;
}
```

**Comment by stephanrauh** [comment]
The same demo also shows it's possible to hide the toolbar. https://pdfviewer.net/hiding-buttons shows the the toolbar vanishes after hiding every button. Probably you've missed a button.

**Comment by dheerajm91** [comment]
> Would you mind to open a ticket for each issue, please? Otherwise I always loose track when the discussion get longer and longer. It's easy to miss an issue in a multi-issue ticket.

Sure will do that.

**Comment by dheerajm91** [comment]
> The showcase removes the border without problems: https://pdfviewer.net/display-options

Yes i saw that but when i install a new angualr app and tested the same its not hinding the borders. I will open a new ticket with more information and we can discuss there

**Comment by dheerajm91** [comment]
> As for the progress bar, have a look at this demo: https://pdfviewer.net/custom-print-dialog
> 
> Basically, it hides the progress bar using this CSS snippet:
> 
> ```css
> .pdf-wrapper #printServiceOverlay .dialog {
>   display: none !important;
> }
> ```

Okay looks cool ! will try that
