### ISSUE TITLE
Initial load: [showBorders] when set to true or false on the initial load is not hiding the borders

### ISSUE THREAD

**Issue by dheerajm91** [stephanrauh/ngx-extended-pdf-viewer#412]
Hi,

https://pdfviewer.net/display-options

I looked at the above options and it works fine beacuse initially we are setting it as true and then on toggling on check box we are setting it to false and that works as expdected.

My the main issue is:
Initially when i load or render the page for the first time with sending the "showBorders" as false it does not hide the borders and i believe this might be a bug.

The workaround i did for now is that i am setting the [showborders] as true on initial load and when the (pageRendered) event is triggered, i am setting it to false. But is there a cleaner way than this or any other event you suggest as (pageRendered) event keeps triggerring for every page ? 

Please see if this can be accepted as bug as i it does not hide the borders on initial load with the default value of the [showBorders] is set to false ?

Thank you 
DJ

**Comment by stephanrauh** [comment]
Strange bug. It seems the feature is already broken for a long time, maybe even from the beginning.

The bug fix has landed with version 4.0.3. Thanks for reporting the bug!

Best regards,
Stephan
