### ISSUE TITLE
Add ability to disable scrolling and show one page at a time

### ISSUE THREAD

**Issue by ckmcnall** [stephanrauh/ngx-extended-pdf-viewer#417]
I'm attempting to use this PDF viewer as a way to display a slideshow

If there were an ability to disable scrolling entirely, display only one page at a time, and allow the page to be changed only by the keyboard or by using the page buttons, that would be very helpful!

Currently full-screen mode works somewhat like this, however in my case It would be nice to be able to use it outside of full screen as well.

**Comment by stephanrauh** [comment]
I don't want to modify the PDF viewer for that feature. But maybe a simple CSS hack does the trick. Please try

```javascript
document.querySelector('#viewerContainer').style.overflowY="hidden";
```

Does that help?

Best regards,
Stephan

**Comment by ckmcnall** [comment]
Yes! That solves my problem! Thank you very much!

**Comment by stephanrauh** [comment]
Awesome. I'm always glad to help!
