### ISSUE TITLE
Cannot use controls inside PDF viewer

### ISSUE THREAD

**Issue by NishadAbdul** [stephanrauh/ngx-extended-pdf-viewer#422]
I am using the latest version of ngx-extended-pdf-viewer. Is it possible to use PDF controls like typing on input box, check/uncheck checkboxes, radio etc?

**Comment by stephanrauh** [comment]
I'm afraid I didn't get your question. I'll answer the question I read, but I'm sure that's not what you're referring to.

Yes, sure, all the controls of the PDF viewer are functional. For example, you can enter the page number in the page number input field, you can enter a search term into the "find" input field, and so on.

If that's really your problem, have a look at [my showcase](https://pdfviewer.net/simple). There are plenty of demos, all of them fully functional.

**Comment by stephanrauh** [comment]
@NishadAbdul Did my answer help you?

**Comment by NishadAbdul** [comment]
Thank you for your response.

Actually my question is related to the input controls inside a pdf file. Like a PDF form in which we can enter the details which is not working for me.

**Comment by stephanrauh** [comment]
I see. That's a bug you should report to the base library, i.e. Mozilla's pdf.js. Please open a bug ticket at the bugtracker. But I'm afraid they are reluctant to do something about it.

Maybe I can help you by adding one of the key developers of pdf.js in the loop. @timvandermeij, does pdf.js support embedded forms with input fields and checkboxes? If not, is this something you plan to support?

**Comment by timvandermeij** [comment]
PDF.js currently has experimental support for interactive forms (AcroForms) and completing this feature is tracked in https://github.com/mozilla/pdf.js/issues/7613. Rendering of the forms works now; it's mainly printing and saving the values that's missing but is being implemented right now in a series of pull requests. No timeline as to when it will be completed, but it's in active development.

**Comment by stephanrauh** [comment]
Awesome, @timvandermeij !

@NishadAbdul The good news is that the feature is being developed - but probably it'll ship to late for your project. Sorry about that. This also means that neither ng2-pdf-viewer nor ng2-pdfjs-viewer will help you. As far as I know, there are commercial solutions you could buy. My article https://www.beyondjava.net/angular-pdf-viewers-2020#benefits_of_commercial_solutions has some hyperlinks for you.
