### ISSUE TITLE
Promise.allSettled error

### ISSUE THREAD

**Issue by akshata456** [stephanrauh/ngx-extended-pdf-viewer#424]
I'm using angular v7.1.4 and node v10.21.0.I got below error in console what can i do to prevent this error in log?
Error:
Please update zone.js to version 0.10.3 or higher. Otherwise, you'll see many messages complaining about Promise.allSettled.

**Comment by stephanrauh** [comment]
Well... I've added the error message to avoid confusion. It seems I wasn't successful. :) 

I'd appreciate your feedback: you can I improve the error message? What kept from understanding what I was trying to tell you? I'm not a native speaker of English, so I assume the error is on my side.

That settled, let me answer your question. If you're using Angular 7, you're almost certainly using an old version of zone.js. Have a look at your `package.json`. There's a zone.js entry (unless you've removed it manually). 

This library replaces many standard functions of JavaScript by value-added versions of these functions. It's a massive monkey-patching approach. Unfortunately, the old versions of zone.js only cover old versions of JavaScript. The PDF viewer uses several modern features. So you have to update to a current version of zone.js.

One of these features is `Promise.allSettled()`. That's a method your browser supports (unless you're using Internet Explorer). But adding an old version of zone.js destroys this method. Updating the `package.json` `zone.js` entry to version 0.10.3 or above solves this problem.

**Comment by stephanrauh** [comment]
I haven't heard from you again, so I suppose my answer helped you to solve the issue. I'm closing the ticket now.
