### ISSUE TITLE
Pdf is not displaying.

### ISSUE THREAD

**Issue by pks9862728888** [stephanrauh/ngx-extended-pdf-viewer#437]
Angular CLI: 10.0.4
Node: 10.21.0
OS: linux x64

Pdf is not showing in the webapp. 

In the console it is showing:
```
ngx-extended-pdf-viewer running on pdf.js 2.6.57. 
PDF b3ac4578280e6f0bd92ef63870ddb51f [1.4 Skia/PDF m84 / Chromium] (PDF.js: 2.6.57) modified by ngx-extended-pdf-viewer)
```

I have directly referred to the pdf from my assets folder and I am using the latest version of extended pdf viewer.
```
<ngx-extended-pdf-viewer src="../../../assets/abc.pdf" useBrowserLocale="true" textLayer="true"></ngx-extended-pdf-viewer>
```

**Comment by stephanrauh** [comment]
Did you try to open the same file on https://pdfviewer.net/simple?

**Comment by pks9862728888** [comment]
Yes it is opening in `pdfviewer.net/simple`.

This pdf also opens in `ng2-pdf-viewer.`

I am currently unable to find what might be the issue.

**Comment by pks9862728888** [comment]
It's working now. But when I try to open pdf using firefox in linux and in android, then it shows:

```
PDF.js v2.6.57(build 76c592cf5)
Message: The browser/environment lacks native support for critical functionality used by the pdf.js library. Please use an es5 build instead.
```

So how to solve this issue?

**Comment by stephanrauh** [comment]
That's really weird. Are your Linux Firefox and your Android Firefox old versions? Current versions shouldn't run into this error messae.

**Comment by stephanrauh** [comment]
Before doing anything else, check you're using a current version of zone.js. Something like `^0.10.3`.

**Comment by pks9862728888** [comment]
My version is:

```"zone.js": "~0.10.2"```

**Comment by stephanrauh** [comment]
Strange. Your version of zone.js should do the trick. Maybe I should add an additional check and load the ES5 binaries when the error message pops up. But that'd be a pity because the ES5 version if a bit slower, and many developers might miss they're using the wrong version due to a misconfiguration.

**Comment by pks9862728888** [comment]
Importing `pdf-worker-es5.min.js` throws initialization errors. Importing `pdf-worker.min.js` solved the problem.

Anyway thank you for your help :)
