### ISSUE TITLE
Display pdf file from azure blob file url

### ISSUE THREAD

**Issue by nirav5884** [stephanrauh/ngx-extended-pdf-viewer#438]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

**Describe the bug**
Trying to load the pdf file uploaded in my local azure storage blob (using file url), but getting the error "Trying to use fetch and pass in mode: no-cors".
My local azure storage url is: http://127.0.0.1:10000/container/myfiles/file.pdf

```
<ngx-extended-pdf-viewer
                [src]="fileUrl" [useBrowserLocale]="true" [textLayer]="true" [showHandToolButton]="true">
</ngx-extended-pdf-viewer>
```

**Version info**
- Latest

**Desktop (please complete the following information):**
 - All

**Comment by stephanrauh** [comment]
Sounds like you've run into a CORS problem, tried to solve it, and made it worse by doing so. I've never seen your error message before, but this StackOverflow answer seems to tell you what's going on: https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

**Comment by stephanrauh** [comment]
@nirav5884 Did my hint help you? Can I do anything else for you?

I'm closing the ticket now because I haven't heard from you for almost two weeks.

Best regards,
Stephan
