### ISSUE TITLE
can't visualize pdf using the ngIf element

### ISSUE THREAD

**Issue by Miliks** [stephanrauh/ngx-extended-pdf-viewer#44]
Dear developers,
i was trying to visualize the pdf image using angular 7 with this part of code in html page:
```html
<div *ngIf="floorInfo">
        <ngx-extended-pdf-viewer src ="'/assets/' + floorInfo.image">
        </ngx-extended-pdf-viewer> 
</div>
```
there is no errors, so i do not know what is wrong with the code, but i can see only gray screen of the pdf viewer and the control buttons located in the wrong way on it and no image.
I tried with the static image and everything was working fine, but i need the image to be loaded dynamically based on the selection of the user.
Any idea what am i doing wrong?
Any suggestion is appreciated.
Thanks in advance,
Liudmila

**Comment by stephanrauh** [comment]
I guess the `src` attribute should be put in square brackets (i.e. `[src]`). But that shouldn't be the problem. Try it anyways, please.

**Comment by stephanrauh** [comment]
My first thought was it's the `*ngIf`. But that's unlikely - the PDF viewer works with sliders and tabs (albeit a bit flaky on Windows). So maybe it's really the `[src]` attribute. Without the brackets Angular doesn't interpolate the expression.

**Comment by Miliks** [comment]
Hi Stephan, thanks for the suggestion, looks like it was the problem of the import of the library in wrong module, since the html i was talking about is a one of the several components on the screen, the import have to be defined on the parent module. Anyway with the correct import and putting the square brackets now i can see it. Anothe issue i discovered though is what ones it is visualized the overall page Zoom in and out is working only for the pdf viewer, looks like focus remain on it. REsizing the desctop window all components are reduced/increased correctly, only zooming is not working.
Is there any way to disable it somehow? 
Thansk again

**Comment by stephanrauh** [comment]
I'm afraid I don't understand your remarks concerning the zoom. When set to "automatic resize", the PDF file grows and shrinks with the window. Have a look at this screen recording:

![Ticket](https://user-images.githubusercontent.com/3045767/54780795-f84a7280-4c1a-11e9-902d-8e5cc73d5707.gif)

**Comment by Miliks** [comment]
Hi, right, when u resize the browser window everything is working fine as u r saying, the problem is when u zoom in the context of the dashboard inside the browser (browser window remain the same ,but u do zoom in/out). The problem was not PDF file itself, but the rest of the page which was not resizing, playing around with the parameters of the other components of the dashboard i fixed it somehow, not that smothly as i would expect, but it is ok. Thanks you very much for your support!

**Comment by stephanrauh** [comment]
You've managed to solve the bug? Awesome!

Sorry for the sluggish reponse - I've been conducting Angular trainings for the last couple of working days. Not to mention my private life, which is also demanding at times. :)

**Comment by jmishra1927** [comment]
I am using the ng2-pdf-viewer to display the pdf it is working in all the browser but it is unable to open the pdf in IE 10. only blank page is coming. Please suggest what to do.

**Comment by stephanrauh** [comment]
@jmishra1927 Just switch to `ngx-extended-pdf-viewer`.  Vadim's component is great, but I won't support it.

**Comment by stephanrauh** [comment]
@jmishra1927 If you're really interested in using `ngx-extended-pdf-viewer`, please open a new ticket. Before you do, please check your `angular.json` imports the correct set of files. With the latest version 1.0.0-rc.6, that's `pdf-es5.js`, `pdf-worker-es5.js`, and `viewer-es5.js`.

**Comment by smrutiranjan727** [comment]
> Hi, right, when u resize the browser window everything is working fine as u r saying, the problem is when u zoom in the context of the dashboard inside the browser (browser window remain the same ,but u do zoom in/out). The problem was not PDF file itself, but the rest of the page which was not resizing, playing around with the parameters of the other components of the dashboard i fixed it somehow, not that smothly as i would expect, but it is ok. Thanks you very much for your support!

I am also having the same problem. Wonder to see the issue still exists even after a year. @Miliks Could you please provide the fix here? I'm really going though a tough time for this in my project.

**Comment by smrutiranjan727** [comment]
> Hi, right, when u resize the browser window everything is working fine as u r saying, the problem is when u zoom in the context of the dashboard inside the browser (browser window remain the same ,but u do zoom in/out). The problem was not PDF file itself, but the rest of the page which was not resizing, playing around with the parameters of the other components of the dashboard i fixed it somehow, not that smothly as i would expect, but it is ok. Thanks you very much for your support!

I am also having the same problem. @Miliks  Could you please provide the fix here? I'm really going though a tough time for this in my project

**Comment by stephanrauh** [comment]
Are you referring to this effect? Basically, all I can see is that the scroll bar of the PDF file is missing. But the combination of 500% zoom and minimal browser size looks pathological to me, anyways. Can you send me a screenshot that shows you bug in a more useful situation?

![image](https://user-images.githubusercontent.com/3045767/82740285-b39ef780-9d47-11ea-9d8e-c9002371e290.png)

![image](https://user-images.githubusercontent.com/3045767/82740293-c3b6d700-9d47-11ea-955b-04db85475c57.png)

**Comment by smrutiranjan727** [comment]
Hi. Thanks for your quick response.
Yes. I have the same issue. But my zoom level is not so high though. And yes, showing the scroll bar at least would fix the issue.
![Screenshot_20200524-034438](https://user-images.githubusercontent.com/18301541/82741568-1d7fc700-9d71-11ea-80b1-7befd2a90903.jpg)
As you can see, half of the pdf is hidden and no way I can scroll to view the hidden content.

**Comment by smrutiranjan727** [comment]
And I think the width of the control also matters. As you can see the right side part of the pdf viewer control is hidden.

**Comment by stephanrauh** [comment]
Awesome usecase. It looks like you're displaying a newspaper on a cell phone. I'd never dreamt I'd ever see something like this!

**Comment by stephanrauh** [comment]
I just wonder why you (or your users) increase the browser zoom level. Isn't it more useful to increase the zoom level of the PDF viewer?

**Comment by stephanrauh** [comment]
I've opened a new ticket for you. Let's continue the discussion in #326.

Best regards,
Stephan
