### ISSUE TITLE
Additional details about the PDF loaded.

### ISSUE THREAD

**Issue by ashleyseeto** [stephanrauh/ngx-extended-pdf-viewer#450]
Hi,

This is not a BUG. Just a request. It is possible to extract further details apart from the name of the PDF loaded. Such as
![file_SRC](https://user-images.githubusercontent.com/37030214/91178638-c3ecb700-e728-11ea-9ec8-825b50cf60c3.jpg) from the component ngx-extended-pdf-viewer

Thankyou

Cheers

Ashley

**Comment by stephanrauh** [comment]
Sounds difficult. Many people display PDFs sent from a database or even dynamically generated PDF file, so these details aren't available. Plus, I don't know how range requests work. The load chunks of the file, so I don't know if there's a file size.

But I'll have a look at it!

Best regards,
Stephan

**Comment by ashleyseeto** [comment]
Hi Stephan,

Just to explain a bit better.

The button 'Open File' is simply   <input type="file" (change)="upload($event)" accept=".pdf" />. Once the pdf is selected, I like to gather data about the pdf file so I can upload to Google Firestore Storage. I can do this now by:
upload( event: any )
    {
      console.log(event.target.files[0] )

      this.pdfselect = event.target.files[0];
    }

I'm guessing that the ngx-extended-pdf-viewer is doing the same thing. How can I extract this data as per attached 
![file_SRC](https://user-images.githubusercontent.com/37030214/91256043-a6136680-e7a9-11ea-8fd7-3c1564da3d8f.jpg) such as this.pdfselect = event.target.files[0] from the component.

Cheers

Ashley

**Comment by stephanrauh** [comment]
Your feature has landed with version 6.0.0-beta.6.

**Comment by stephanrauh** [comment]
Live demo at: http://localhost:4200/file-info

Also see #533. There are some interesting metadata that might be worth extracting, too. For example, some of the demo files contain detailed copyright hints.

**Comment by stephanrauh** [comment]
Note that the file size is stored as "maybeFileSize" because sometimes it's just a wild guess. For example, if you're receiving the file as a Base64 encoded string it's hard to say how big the original file was.
