### ISSUE TITLE
pdf.min.js not found 

### ISSUE THREAD

**Issue by hiennm0406** [stephanrauh/ngx-extended-pdf-viewer#456]
I'm have a project using jhipster 6.10. angular 9.0 and ngx-extended-pdf-viewer 4.1.2

I had import everything like https://pdfviewer.net/getting-started show with "JHipster 6.6 + ngx-extended-pdf-viewer 2.0.0+" 👍 

> npm i ngx-extended-pdf-viewer --save

> import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';

> <ngx-extended-pdf-viewer [base64Src]="base64encoded" useBrowserLocale="true" height="80vh"></ngx-extended-pdf-viewer>

But when i run app. pdfview showed but nothing just blank.
and i got 
`GET http://10.xx.xx.xx/assets/pdf.min.js net::ERR_ABORTED 404 (Not Found)`

But jhipster dont have **assets** folder and i dont know how to config here

![image](https://user-images.githubusercontent.com/23075222/91833461-f0488c00-ec70-11ea-97cb-850c110ce605.png)

**Comment by stephanrauh** [comment]
Here's a JHipster demo project for you: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/JHipster-6.6-ngx-extended-pdf-viewer-2.0.0

AFAIK the demo project follows the defaults of JHipster. I've put the PDF file into the folder `src/main/webapp/content`. Probably that's the folder you're looking for.

**Comment by stephanrauh** [comment]
After answering I saw you're referring to the JavaScript files. If my demo project doesn't help you, have a look at the tab "older JHipster or Webpack" of https://pdfviewer.net/getting-started. That's a recipe that _should_ always work.

**Comment by stephanrauh** [comment]
Hope that helps! I'm closing the ticket now, but I', still listening. If you're still in trouble, just answer here.

Best regards,
Stephan

**Comment by hiennm0406** [comment]
Hello. I fixed my bug by add only
`   { from: "./node_modules/ngx-extended-pdf-viewer/assets", to: 'assets' },`
to webpack.common.js  

findout after lot of times debug your project
thanks, I think This need to note in guide page

**Comment by stephanrauh** [comment]
Ah, yes, you're right. I'll add it to the documentation.

**Comment by stephanrauh** [comment]
Oops... the documentation is there, but it isn't shown because I've added a typo to a filename. I'm fixing that. I've also added a couple of lines to the "old JHipster" documentation.

**Comment by stephanrauh** [comment]
The updated documentation is online now. Thanks for pointing this out!
