### ISSUE TITLE
Showcase project does not load the sample PDF in IE11

### ISSUE THREAD

**Issue by mruf** [stephanrauh/ngx-extended-pdf-viewer#463]
**Describe the bug**
The PDF in the Showcase (https://pdfviewer.net/simple) is not loaded when using IE11:

**Version info**
- Version used in the Showcase project

**Desktop (please complete the following information):**
- IE11 on Windows 10

 **Screenshots**
![image](https://user-images.githubusercontent.com/7147271/92697361-83f21a80-f34b-11ea-8c92-13021caf8ed4.png)

**Additional context**
I'm looking for a replacement library for ng2-pdf-viewer which is having issues with IE11 support in the newer versions. Your library explicitly mentions IE11 support and looks very promising so I'd like to use it.

**Comment by stephanrauh** [comment]
Oops. You're right. What's happened? BTW: The base64 demo works.

**Comment by stephanrauh** [comment]
I've just spent an hour hunting down this bug. It's really weird. An exception is raised, but it looks like a `throw undefined`.  Until now, I didn't manage to find the root cause.

**Comment by stephanrauh** [comment]
The culprit is zone.js. The current version 0.11.1 isn't compatible to IE11. Downgrading to version 0.10.3 solves the problem. The team also promises to solve the bug in the upcoming version 0.11.2.

**Comment by stephanrauh** [comment]
I've just tested the showcase with IE11. Everything seems to work.
