### ISSUE TITLE
Refresh function

### ISSUE THREAD

**Issue by Botz1991** [stephanrauh/ngx-extended-pdf-viewer#465]
Hello,
there is a way to refresh pdf document through a function call or similar (via code)?
Because i use canvas on every pdf page to draw over and i need refresh the pdf to delete the drawing on the sheets.

Thanks in advance!

**Comment by stephanrauh** [comment]
Sorry for the delay. I've found a solution. Instead of passing the URL of the pdf file directly, you can also define it like so:

```html
<ngx-extended-pdf-viewer 
         [src]="src"
        useBrowserLocale="true">
</ngx-extended-pdf-viewer>
```

```typescript
    this.src = {
      url: 'assets/Portugues-para-principiantes-1538054164.pdf',
      originalUrl: 'assets/Portugues-para-principiantes-1538054164.pdf',
    };
```

This replaces the `src` with a new object, forcing the PDF viewer to reload:

```typescript
  public onClick(): void {
    this.src = {
      url: 'assets/Portugues-para-principiantes-1538054164.pdf',
      originalUrl: 'assets/Portugues-para-principiantes-1538054164.pdf',
    };
  }
```

**Comment by Botz1991** [comment]
Thanks!
it works with local pdf, but not with pdfs in object storage or on web; is there another solution for that cases?

Thanks in advance

**Comment by stephanrauh** [comment]
IMHO it should work with non-local http(s) URL, but I agree it probably doesn't work with BLOBs. What happens if you set the URL to null for a second (or 100 milliseconds)?

A brute-force workaround to is hide the pdf viewer with an `ng-if` for 100 milliseconds.
