### ISSUE TITLE
ngx-extended-pdf-viewer throws invalid argument and pdf not loading in IE11

### ISSUE THREAD

**Issue by iamrajaraj** [stephanrauh/ngx-extended-pdf-viewer#466]
@stephanrauh - The application works fine in Chrome but the same not working in IE11.

Error ScreenShot

![image](https://user-images.githubusercontent.com/16011060/93362562-bcba5400-f863-11ea-81a7-6a38f94819cf.png)

 - .html
```
<ngx-extended-pdf-viewer [src]="model.contentPdf" useBrowserLocale="true" height="80vh"></ngx-extended-pdf-viewer>
````

 - angular.json
```
"scripts": [ 
  "node_modules/jquery/dist/jquery.min.js",
  "node_modules/bootstrap/dist/js/bootstrap.min.js",
  "node_modules/ngx-extended-pdf-viewer/assets/pdf-es5.js",
  "node_modules/ngx-extended-pdf-viewer/assets/viewer-es5.js"
]
```
 - "ngx-extended-pdf-viewer": "3.2.0"
 - dependencies
``` 
"dependencies": {
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/material": "8.2.3",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@ng-bootstrap/ng-bootstrap": "5.3.0",
    "bootstrap": "4.4.1",
    "browserify": "16.5.0",
    "font-awesome": "4.7.0",
    "jquery": "3.3.1",
    "ngx-avatar": "3.7.0",
    "ngx-extended-pdf-viewer": "3.2.0",
    "ngx-json-viewer": "2.4.0",
    "ngx-toastr": "10.1.0",
    "open-iconic": "1.1.1",
    "rxjs": "6.5.4",
    "tslib": "1.10.0",
    "web-animations-js": "2.3.2",
    "zone.js": "0.10.3"
  }
```

**Comment by stephanrauh** [comment]
Also see #463.

**Comment by iamrajaraj** [comment]
@stephanrauh, Can we consider it as open issue?

**Comment by iamrajaraj** [comment]
Looks `minifiedJSLibraries` property was introduced from v4.0.0. As I am using `"ngx-extended-pdf-viewer": "3.2.0"` getting error message in console as 
```
Template parse errors:
Can't bind to 'minifiedJSLibraries' since it isn't a known property of 'ngx-extended-pdf-viewer'.
```

**Comment by stephanrauh** [comment]
I see. Can you update to a current version? I publish bugfixes only with new versions - that's currently the 5.0 branch.

**Comment by iamrajaraj** [comment]
Have updated to latest version 5.0.0-alpha.3. but issue remains the same. It will be great full if your fixing this issue ASAP for IE11.

**Comment by stephanrauh** [comment]
This afternoon I've played around with IE11 for a while. The good news: it does work, at least with the default demo at https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/master/src. However, it fails to run the showcase. The error message is as weird as can be: `this` is undefined when the `load()` method is called.

I'll try to create a reproducer showing how to get the PDF viewer up and running with IE11. Maybe you can do the same: send me a reproducer showing the bug. Here's a template project to make it easier to create the reproducer: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Well... I've managed to repair the showcase. It works fine with IE11 now. Note that updating to zone.js 0.11.1 breaks IE11 compatibility - but you're still on version 0.10.3, so that's not the problem.

I suggest you checkout the project https://github.com/stephanrauh/extended-pdf-viewer-showcase, get it up and running on your machine and checks that it works with your IE11, too. If it does, compare the showcase project to your project. I guess there's a difference somewhere causing the bug. Or maybe you've found a bug I haven't run into yet.

**Comment by stephanrauh** [comment]
@iamrajaraj Does this help you? If so, I'd like to close this ticket.

**Comment by iamrajaraj** [comment]
@stephanrauh - The Project https://github.com/stephanrauh/extended-pdf-viewer-showcase have checkout to local and its running successfully in IE11. Then I have tried in my code with the latest version 5.0.0-alpha.5. but its still not loading for my code. FYI, getting below attached console error. 

![image](https://user-images.githubusercontent.com/16011060/94142853-85176180-fe8c-11ea-8422-a24696ec4911.png)

I noticed your project having angular 10 but mine is angular 8 hence anything else need to be modified?.

**Comment by stephanrauh** [comment]
> I noticed your project having angular 10 but mine is angular 8 hence anything else need to be modified?.

Everything's possible, but I don't believe so.

The problem with IE11 is it just says "you've got an error, but I won't tell you which one". I found the zone.js error by disabling minification, inspecting every line of the stack trace, and a lot of good luck (or intuition, whatever you like best).

By the way, the new error message look different than the error message you've originally posted. Maybe something's changed?

**Comment by iamrajaraj** [comment]
Yes, Original error when "ngx-extended-pdf-viewer": "3.2.0" and the new error when "ngx-extended-pdf-viewer": "5.0.0-alpha.5"

**Comment by stephanrauh** [comment]
@iamrajaraj Any news? Does the bug still exist?

**Comment by stephanrauh** [comment]
Closing the ticket after several months of silence. Sigh!
