### ISSUE TITLE
View two PDF in the same viewer side by side

### ISSUE THREAD

**Issue by ishanuda** [stephanrauh/ngx-extended-pdf-viewer#467]
Hi,

I see now the library has improved a lot, Is it possible to load two PDF in a single view so that a user can look into two pdf at the same time in a single viewer side by side.

If it is still not possible, is there a plane to implement this kind of feature in the library in the future?

Thank you very much.

**Comment by stephanrauh** [comment]
I'm afraid that's next to impossible. The base library, pdf.js, uses many global variables, so you can't open two PDF files simultaneously. I guess you could do this by putting the PDF viewer into an iFrame (or two iFrames, one for each PDF file). You'd just have to find a solution for simultaneous scrolling (if you need it).

**Comment by Hemanggupta** [comment]
> Hi,
> 
> I see now the library has improved a lot, Is it possible to load two PDF in a single view so that a user can look into two pdf at the same time in a single viewer side by side.
> 
> If it is still not possible, is there a plane to implement this kind of feature in the library in the future?
> 
> Thank you very much.

Did you find any solution for this?

**Comment by stephanrauh** [comment]
Yes, sort of. pdf.js pollutes the global namespace, so displaying two PDF files side-by-side requires a dirty hack. You need to put at least one viewer into an iFrame. Here's the live demo: https://pdfviewer.net/extended-pdf-viewer/side-by-side

The source code of the demo is here: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/side-by-side and here:https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/iframe
