### ISSUE TITLE
View the initial pages of the pdf before it is downloaded completely

### ISSUE THREAD

**Issue by Rebecca90** [stephanrauh/ngx-extended-pdf-viewer#470]
**Is your feature request related to a problem? Please describe.**
Yes, currently the pdf-viewer waits for the entire pdf to be downloaded and then shows it to the user. In cases where the size of the pdf is 100+ mb , the user needs to wait for a long period of time to view the pdf.

**Describe the solution you'd like**
Is there any way, where we could display the pdf pages sequentially while it is getting downloaded simultaneously ? For eg:- when we download/open a pdf file from the browser, we can see the initial pages of the pdf before the entire pdf is downloaded. Eg:-https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf

**Describe alternatives you've considered**
I read somewhere that if a pdf is linearized , it can be viewed as and when the data is received. I tried using a linearized pdf -https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf, but it still waited for the whole pdf to get downloaded and then showed it on the viewer.

**Additional context**

**Comment by stephanrauh** [comment]
Yes, that's possible. If your server supports range requests, the file is displayed while it's still being downloaded.

**Comment by stephanrauh** [comment]
If I've got it right, you can activate range requests on an Apache http server by adding this line to the `.htaccess` file:

```
Header set Accept-Ranges bytes
```

This doesn't seem to work if the file is compressed by Brotli or Gzip. At least, I didn't manage to get it up and running on my showcase. But it works out-of-the-box with `ng serve`. The first request is cancelled by the client, the consecutive request load the file piece by piece. 

![image](https://user-images.githubusercontent.com/3045767/93516246-0ec5ad00-f92a-11ea-92e4-baed03fa82cd.png)

Additional infos: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by Rebecca90** [comment]
Thanks I will try this out.

**Comment by Rebecca90** [comment]
Hi, I tried the range requests approach like you mentioned. However I am still unable to view the document while it is being fetched. I called two apis -one which brings be the first 1MB of the pdf and second which brings the remaining part of the file(approx 19mb). When I assign the src to first 1MB of the file(ArrayBuffer) (since its received first) I get an error message called corrupted pdf. Then when the second api call is complete, I the concatenate the first array buffer with the second array buffer(from second api) and assign to the src . Then the whole pdf is seen and I don't get any error message. Could you please help me out here ?

**Comment by stephanrauh** [comment]
Well... using range requests doesn't mean you have to split the file into slices yourself. It's something the server does. The idea is you simply ask your operations department to configure the server to support range request. Of course, if you've into devops, this amounts to asking yourself. :)

You've mentioned you're using an API. That sounds like there's a REST API delivering the PDF file. Maybe that's the problem. Maybe - just maybe, I'm not an expert on the matter! - the feature works with static files, but not with files served from a REST interface.

**Comment by stephanrauh** [comment]
BTW, a good starting point to debug the issue is https://github.com/stephanrauh/pdf.js/blob/aab5ad67c84c90456f4b2573e9c97a3339f5d71b/src/display/fetch_stream.js#L146.

You need to add the option `[minifiedJSLibraries]="false"` to be able to debug the original source code. Otherwise, debugging isn't much fun. :)

**Comment by Rebecca90** [comment]
Hi, it works now. On the UI side, I assigned the src to an obj ={'url' : 'url of the file', 'rangeChunkSize' : '1024'} .And on the server side we made changes in the way we were sending the file. That worked for us.
Thank you :)

**Comment by stephanrauh** [comment]
That's great news! Can you elaborate which changes you did on the server side? I'd like to add your solution to the documentation.

**Comment by Rebecca90** [comment]
Hi I referred this article in creating my server side changes for handling range requests- https://medium.com/@vishal1909/how-to-handle-partial-content-in-node-js-8b0a5aea216
GitHub repo -https://github.com/phoenixinfotech1984/node-content-range/blob/master/server.js

**Comment by stephanrauh** [comment]
Interesting. I wasn't aware it's so simple to implement the feature. Thanks for the link and the pointer to the repo!

**Comment by stephanrauh** [comment]
Todos left:
- [ ] add the new information to the documentation

**Comment by stephanrauh** [comment]
I've added your links and suggestions to the documentation. Thanks a lot!

Best regards,
Stephan

**Comment by Rebecca90** [comment]
Glad to be of some help ! :)
