### ISSUE TITLE
Will not print the pdf.

### ISSUE THREAD

**Issue by rickdecker** [stephanrauh/ngx-extended-pdf-viewer#472]
The print/view is blank for all pages.  It will print all blanks.
Did some searching found not other reports expect for printing  only the last page on a modal dialog.

Will send attached file, just wondering if I am the only one experiencing this problem.  Easy to implement, looks great but bummed out it will not print the pdf.

Thank you,

Rick
Miami, Florida

**Comment by stephanrauh** [comment]
Please check your CSS framework. More likely than not, that's the culprit. There are several closed issues here dealing with the topic. Please have a look at them, they're full of helpful info. I've also mentioned the topic in the showcase.: https://pdfviewer.net/troubleshooting

Maybe using Austin Walker's solution is all you need:

@media print {
  body {
    min-width: auto !important;
  }
}

**Comment by stephanrauh** [comment]
Here's a selection of useful issues: #143, #148 and #175. As far as I remember, there are even more issues, but I guess that should give you a headstart to solve the problem.

If it doesn't, don't hesitate to tell me. I'm closing this ticket now, but I'm still listening to this channel.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
@rickdecker Did you manage to solve the issue?

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, brace yourself for breaking changes.
