### ISSUE TITLE
Ctrl + Mouse scroliing not working on kendo-dialog 

### ISSUE THREAD

**Issue by winnerys** [stephanrauh/ngx-extended-pdf-viewer#475]
Hi,

In order to zoom in/out pdf content, we can use Ctrl Key + Mouse scrolling as you know.

But If pdf viewer's in kendo-dialog modal, this feature not working at all.
I insert ngx-extended-pdf-viewer into modal due to some requirement.

Is anyone know the solution?

> <kendo-dialog title="View as PDF file" width="90%" height="90%" modal="true" (close)="closePDFViewer()">  
> <ngx-extended-pdf-viewer
>     [base64Src] = "PDFBase64Data"
>     [textLayer] = "true"
>     [useBrowserLocale] = "false"
>     [language] = "ko"
>     [showBookmarkButton] = "false"
>     [showOpenFileButton] = "false"
>     [showPresentationModeButton] = "true"
>     [showHandToolButton] = "true"
>     [zoom] = "'page-width'"></ngx-extended-pdf-viewer></kendo-dialog>

**Comment by stephanrauh** [comment]
I don't own a mouse, so I can't help you. I do everything with the trackpad of my laptop. (No joke!)

But I don't see any reason why CTRL+mouse shouldn't work. Does the Kendo framework intercept the mouse gesture for some reason?

**Comment by winnerys** [comment]
Hi, 
You commented a long time ago, but I checked late because of my personal reasons.
I embedded ngx-extended-pdf-viewer inside solution's screen, and I found it that's a problem of this.
Now I am modifying the source code so that the view is visible in a new window, not modal.
this was solution's limitation. :(
Thank you.

**Comment by stephanrauh** [comment]
I see. Glad you've solved the problem!
