### ISSUE TITLE
[Request] Document how to set the default scroll direction

### ISSUE THREAD

**Issue by wivjek** [stephanrauh/ngx-extended-pdf-viewer#476]
I want to choose the default scroll direction (horizontal or vertical) when I show the pdf.
Actually, I can't.

And I see that when I select one direction, if I switch to a new PDF, the direction is still the same as set on the previous PDF. I don't want that. I want the default vertical direction.

Can you add this feature ? Or explain how to do that ?

**Comment by wivjek** [comment]
I have found : pdfDefaultOptions / scrollModeOnLoad ==> not well documented.
Sorry.
Closing issue

**Comment by stephanrauh** [comment]
@wivjek The nice thing about bad documentation is I can easily improve it. In this case, I just don't know how and where to document this class of features. Any suggestions?

Adding insult to injury, the options aren't documented at the pdf.js project well, either (see https://github.com/mozilla/pdf.js/blob/master/web/app_options.js, https://github.com/mozilla/pdf.js/wiki/Viewer-options, and https://github.com/mozilla/pdf.js/blob/120c5c2261e4d55f3d1d82daab61c9254e243e3f/src/display/api.js#L111).

**Comment by stephanrauh** [comment]
@wivjek Ping? Do you have any suggestion how to document the feature? I'm sure I'll find a solution one day or another - possibly even a good one! - , but you're invited to add any suggestion crossing your mind. Any ideas?

**Comment by wivjek** [comment]
So, about this page : https://pdfviewer.net/options
You say : Most options are very advanced or covered by regular attributes

I think you should list all the options in the documentation page and briefly say:
- which option does what
- also say those for which you do not know (or say something like : dangerous, only for power user, use it at your own risk, ...)
- say which ones are covered by the regular attributes and link them to the correct page

You should also implement few missing but interesting options in regular attributes. For example, this initial issue about "default scroll direction" which is not a regular option but it should...

**Comment by stephanrauh** [comment]
Good idea. It's a long list, it felt like copying the phone book. :) But you're right, the effort pays.

**Comment by stephanrauh** [comment]
Seems to be the same request as #495. I'm closing this one to make tracking progress easier.
