### ISSUE TITLE
Toolbar hides only with explicit [showSecondaryToolbarButton]="true" when all other flags are false.

### ISSUE THREAD

**Issue by dheerajm91** [stephanrauh/ngx-extended-pdf-viewer#479]
I have a scenario where there should not be any tool bar. I took the below HTML code from the
Pdfviewer.net from custom printing.

After pasting the below HTML code, i noticed that i would have to explicitly set [showSecondaryToolbarButton]="true" along with below code only then the tool bar hides.  I believe setting this flag true is incorrect as i am not showing any secondary tool bar and to hide the toolbar it shoud not be true when all other flag's are flase.

Steps to reproduce: Set the [showSecondaryToolbarButton]="false" in the below code and observe.

HTML Code:
```html
<ngx-extended-pdf-viewer
[src]="url"
[useBrowserLocale]="true"
height="calc(100vh - 475px)"
zoom="50%"
[showSidebarButton]="false"
[showFindButton]="false"
[showPagingButtons]="false"
[showZoomButtons]="false"
[showPresentationModeButton]="false"
[showOpenFileButton]="false"
[showPrintButton]="false"
[showDownloadButton]="false"
[filenameForDownload]="false"
[showBookmarkButton]="false"
[showSecondaryToolbarButton]="true"
[showRotateButton]="false"
[showHandToolButton]="false"
[showScrollingButton]="false"
[showSpreadButton]="false"
[showPropertiesButton]="false">
</ngx-extended-pdf-viewer>
```

Issue reproduced with tool bar when all flags are false as suggested in PdfShowcase documentation (Reference: custom Print): 
![image](https://user-images.githubusercontent.com/25700737/94455406-ddd64b00-0167-11eb-924b-f901f7c2b2d0.png)
 

Thank you

**Comment by stephanrauh** [comment]
Indeed. Weird bug. I'm fixing it with version 5.0.0-beta.2. Thanks for reporting!

Best regards,
Stephan
