### ISSUE TITLE
On print size reduce to around 75%

### ISSUE THREAD

**Issue by khatrizeeshan** [stephanrauh/ngx-extended-pdf-viewer#48]
When I print from this control it reduces the size, whereas if i download the file and then print it works fine.

![image](https://user-images.githubusercontent.com/4524896/55076769-14855e00-50b8-11e9-90d6-177a40d893ee.png)

**Comment by khatrizeeshan** [comment]
We have added the following script you mentioned regarding bootstrap in style.scss but did not work in a blank project.

@media screen {
    @import './../node_modules/bootstrap/scss/bootstrap';
}

**Comment by stephanrauh** [comment]
"Blank project" meaning a demo project using both Bootstrap and ngx-extended-pdf-viewer, I assume? Can you share the project with me, so I can have a look myself?

**Comment by stephanrauh** [comment]
At the moment I can't recall the details, and I don't have access to my old source code. What I recall from memory is that somewhere in the Bootstrap library, there's a statement reducing the font size. Or the general zoom level. As a result, everything is rendered a little smaller. You won't mind on a web page, but you'll notice immediately when printing a page. 

To solve the problem, you have to find the CSS statement downscaling everything. 

That proved to be a bit tedious, so I simply deactivated Bootstrap when printing a page. That's what the `@media screen` query does. It imports Bootstrap if and only if you're viewing the page on a screen. 

Alternatively, you can add a media query acting as a counter-poison like so:

```css
@media print {
  font-size: 133%;
}
```

Does this help you? If so, please report back so I know when I can close the ticket.

Thanks in advance,
Stephan

**Comment by khatrizeeshan** [comment]
https://drive.google.com/file/d/1LY2L6ex0t5uxznaI-JlucmAbToRqjvJF/view?usp=sharing

**Comment by stephanrauh** [comment]
I believe I've managed to reproduce your bug. However, it looks more like a 85% reduction (or rather, a reduction by 15% :) ). Does it look similar to my screenshot on your machine?

![image](https://user-images.githubusercontent.com/3045767/55189091-4f14f680-519d-11e9-9c16-f186471b09a6.png)

**Comment by khatrizeeshan** [comment]
Yes

**Comment by stephanrauh** [comment]
Oops - it turned out to be simple. I guess I should improve my documentation. :)

Adding the media query to the global `styles.css` replaces the import in the `Angular.json`file:

```js
           "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.css",  <<< remove this line!
              "src/styles.scss"
          ],
```

**Comment by stephanrauh** [comment]
improved documentation published with version 0.9.17 just a minute ago

**Comment by jos1337** [comment]
the suggested solution:
 @media screen {
    @import './../node_modules/bootstrap/scss/bootstrap';
}
is causing an scss error:
You may not @extend selectors across media queries.

Is there a workaround for this?

**Comment by BGBRWR** [comment]
Instead of this
```css
@media screen {
    @import './../node_modules/bootstrap/scss/bootstrap';
}
```

You can use this
```css
@media print {
  body {
    min-width: auto !important;
  }
}
```

**Comment by stephanrauh** [comment]
Whow, is it really that simple? I've added it to the documentation. Thanks for the hint!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, I don't know what happens to your bugfix. I hope you won't need it, but I can't predict this.
