### ISSUE TITLE
When is the actual 5.0 release ?

### ISSUE THREAD

**Issue by dheerajm91** [stephanrauh/ngx-extended-pdf-viewer#480]
Hi,

I am trying to consume 5.0 in my project and seems like we are in beta now as per the GitHub change versions.
Just wanted to know if there is any ETA for the actual 5.0 release so that i would be able to plan to consume it my project.
Can i assume that actual 5.0 can be released by end this week ?

Thanks

**Comment by stephanrauh** [comment]
Yes, you can. I've implemented everything I want to put into the 5.0 version. Now I'm testing the showcase, and I hope many developers test the beta version and report errors. At the moment, I'm positive we can call it a final release tomorrow or Wednesday.

**Comment by dheerajm91** [comment]
@stephanrauh Just following up to see if we calling it as final release for 5.0 today ?

**Comment by stephanrauh** [comment]
Depends on your time zone... from my perspective, that's a "yes". :) I've just published version 5.0.0. 

Enjoy!
