### ISSUE TITLE
PDF Forms support version 5.0

### ISSUE THREAD

**Issue by 4vitek** [stephanrauh/ngx-extended-pdf-viewer#483]
Hello,
I understand that starting with version 5.0 , PDF files with forms are supported.
This feature works , but how can I store the inserted data?
The changes that made  to an acro form through a viewer could not be saved or downloaded.
Is there a way to accomplish this?

Thank a lot,
Victor

**Comment by stephanrauh** [comment]
@timvandermeij Does pdf.js support storing data that have been entered in a form?

**Comment by timvandermeij** [comment]
Yes, this is supported in the current pre-release version 2.6.347; see https://github.com/mozilla/pdf.js/releases. Storing entered data is supported for AcroForms when downloading the file or printing it.

**Comment by stephanrauh** [comment]
I've found the bug. 

@timvandermeij Like always, thank you very much for the fast reply! It helped me to find where I failed to merge pdf.js 2.6 to my fork correctly.

The bug fix ships with version 5.0.0.

**Comment by timvandermeij** [comment]
No problem; glad to hear it's solved!

**Comment by 4vitek** [comment]
Thank you.
