### ISSUE TITLE
Is it possible to bundle the PDFjs library in Webpack?

### ISSUE THREAD

**Issue by ReedOwens** [stephanrauh/ngx-extended-pdf-viewer#484]
**Describe the request**
This is not a bug but a request for help configuring the project for our usage. 

What we need: No /asset directory and everything in Webpack Bundles

I love the fact that you can switch between different pdfjs versions, however, we will bundle only one into our system and don't need the swapping.   What we do need it to have everything served from WebPack bundles.   Our server only allows for a small number of files to be uploaded and will serve a "flat" directory back.   Because of this, we use Webpack bundles exclusively.   We've looked into the library but can find out how to make this switch easily.   Do we need to for the project and make the changes or is there a simpler approach with your base work? 

 Thanks so much for you assistance.

**Comment by stephanrauh** [comment]
Yes, that's possible. Look at these two lines:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/3b11102c997f446a82d8c4862eb3517953cd594d/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L570
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/3b11102c997f446a82d8c4862eb3517953cd594d/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L594

When you load the libraries pdf.js and viewer.js manually before loading `<ngx-extended-pdf-viewer>`, these two libraries are not loaded again. You can also pre-load `pdf.worker.js`, but that'll ruin the speed of your application. It's better so specify the URL of the `pdf.worker.js` file in the `DefaultOptions` (i.e. here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/3b11102c997f446a82d8c4862eb3517953cd594d/projects/ngx-extended-pdf-viewer/src/lib/options/pdf-default-options.ts#L44).

That's the sketch of the solution. Does it help you?

Best regards,
Stephan

**Comment by ReedOwens** [comment]
OMG, what a quick response.   If only our "paid" library support vendors would respond so quickly.

This looks like what we are looking for.   I appreciate it and will have our team try it out.   I'm sure it's going to work. 

Thanks!
