### ISSUE TITLE
Load all thumbnails on load or load thumbnails of the area scrolled to

### ISSUE THREAD

**Issue by MBogushefsky** [stephanrauh/ngx-extended-pdf-viewer#485]
I can't seem to find a setting for this anywhere in the ngx-extended-pdf-viewer properties or source code. Would you happen to know how to add this?

**Comment by stephanrauh** [comment]
AFAIK the thumbnails are generated lazily. If you never scroll to chapter 2, the thumbnails of the chapter aren't generated. But I'm not sure.

But each time I jumped to a certain page, the thumbnails were generated either in time or with a short delay. You question sounds like this feature is broken?

**Comment by MBogushefsky** [comment]
I see, I noticed that. The feature is not broken, but I believe lacks a feature that adobe reader has. This feature is loading those pages on the scroll of the thumbnail view. Would you happen to know anyway I can accomplish this. I'm willing to go into source code to try to accomplish this if needed.

Thanks and thank you for the very quick response!

**Comment by MBogushefsky** [comment]
This feature also seems to be in the native PDF.js viewer as shown [here](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by stephanrauh** [comment]
In theory, ngx-extended-pdf-viewer is just a wrapper around pdf.js. In practice, I maintain my own fork and merge it every once in a while. So it's possible an error slipped my attention. Nonetheless, I'm surprised that https://mozilla.github.io/pdf.js/web/viewer.html from my showcase (and that I didn't notice it). If there's something to repair, just tell me. I just didn't get it yet.

(These things happen. Sometime I wonder why I didn't get the message when the penny finally drops!)

Be that as it may, I suppose the source code you're looking for is https://github.com/stephanrauh/pdf.js/blob/80e437b5f8b1a7ca145e3e0aa12dffc9a74ac777/web/pdf_sidebar.js#L332. Or it may be in the same class.

**Comment by MBogushefsky** [comment]
Thank you!

**Comment by MBogushefsky** [comment]
Resolved by removing my CSS change. Thank you for your patience.
`#thumbnailView {
    overflow: unset !important;
}`
