### ISSUE TITLE
Scroll the thumbnail view with the main view of the PDF viewer scrolls 

### ISSUE THREAD

**Issue by MBogushefsky** [stephanrauh/ngx-extended-pdf-viewer#486]
The page that you're viewer should match the thumbnail viewer. For example, if you're viewer page 512 then the thumbnail viewer should be at page 512.
I can't seem to find a setting for this anywhere in the ngx-extended-pdf-viewer properties or source code. Would you happen to know how to add this?

**Comment by stephanrauh** [comment]
When I try to reproduce your bug report on https://pdfviewer.net/simple, the thumbnails are always in sync with the main document (with a small delay caused by lazy loading). What do I miss?

Best regards,
Stephan

**Comment by MBogushefsky** [comment]
I meant the scrolling for example, scrolling in the main view should also move the thumbnail scroll. As a possible new feature, but thank you!

**Comment by stephanrauh** [comment]
Right you are... but again, looking at https://pdfviewer.net/simple, scrolling the document always scrolls the thumbnail view, too. Scrolling the thumbnails does not scroll the main area (unless you click on a thumbnail), but I suppose that's what you expect. I can evade the feeling I didn't get the message yet. What do I miss?

**Comment by MBogushefsky** [comment]
Oh I see, you are right. That example does demonstrate what I was hoping for. Although with my implementation of the pdf viewer it doesn't seem to behaving that way. Would there happen to be a certain property or version that has this feature. 

Thanks again for the such quick responses!

**Comment by MBogushefsky** [comment]
You did not miss anything

**Comment by stephanrauh** [comment]
@MBogushefsky Do the tickets #493 and #494 replace this ticket?

**Comment by MBogushefsky** [comment]
Resolved by removing my CSS change. Thank you for your patience.
`#thumbnailView {
    overflow: unset !important;
}`
