### ISSUE TITLE
Seeing spinner/loading icon until cursor is moved and then PDF displays

### ISSUE THREAD

**Issue by dheerajm91** [stephanrauh/ngx-extended-pdf-viewer#489]
Hi 

I am seeing the spinner/loading icon forever and pdf is not loading in the viewer until i move my mouse or open inspect element in chrome.

Problem statement: I see spinner forever and PDF is not displayed if i do not move my mouse.

Screen shot:
![image](https://user-images.githubusercontent.com/25700737/95025639-28603780-0640-11eb-9094-ec8bf37c385a.png)

I managed to find the error in console:
![image](https://user-images.githubusercontent.com/25700737/95025688-79702b80-0640-11eb-8ae9-b2f743ef4047.png)

The problem is if it happens every time, i will undestand that some thing is wrong with the classes.
But it happens twice in every 5 time i open the modal.

Please help me to resolve this. Will you be able to set the default offsetparent so that it will never break ?
Or else how do i handle the offsetParent ? because it works sometimes and not in sometimes? Is there a way to set the offset parent ? Please see if you can add the minimum offsetParent so that there wont be a spinner  ?

Using the below code:
```html
<div bsModal #pdfModal="bs-modal" class="modal" tabindex="-1" [config]="{ignoreBackdropClick: true, backdrop: 'static', keyboard: false}"
     role="dialog">
  <div class="modal-dialog modal-large">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title">View PDF in modal: src {{selectedSource}} <br>
        {{stringSource}}</div>
      </div>
      <div class="modal-body" *ngIf="!selectedSource && stringSource">
     <ngx-extended-pdf-viewer [src]="stringSource" height="100vh" zoom="115%" [useBrowserLocale]="true"
[showBorders]="false" backgroundColor="white" [showSidebarButton]="false" [showFindButton]="false"
[showPagingButtons]="false" [showZoomButtons]="true" [showPresentationModeButton]="false"
[showOpenFileButton]="false" [showPrintButton]="true" [showDownloadButton]="true"
[filenameForDownload]="false" [showBookmarkButton]="false" [showSecondaryToolbarButton]="true"
[showRotateButton]="true" [showHandToolButton]="false" [showScrollingButton]="false" [showSpreadButton]="false"
[showPropertiesButton]="false">
</ngx-extended-pdf-viewer>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" (click)="pdfModal.hide()">Close</button>
        <button class="btn btn-primary" (click)="onPrint()">Print</button>
    </div>
    </div>
  </div>
</div>
```

**Comment by stephanrauh** [comment]
Twice in every five times... that sucks. I know I'm going to annoy you even more with my next words, but I can't help it. Please bear with me. You know, ngx-extended-pdf-viewer is a 100% leasure-time project, so I appreciate every help I can get. I have to admit I've run into the error message you're reporting more than once. Each time, it's been difficult to find out what's going on.

So can I kindly ask you to send me a reproducer? That's a complete but minimal project showing the bug. I've prepare a template project for you: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

If you really want to do me a favor, send me your reproducer as a pull-request. And update it to the latest versions of every library (including mine - I know I've got some home-work to do!) :)

Best regards,
Stephan

**Comment by dheerajm91** [comment]
@stephanrauh For some reason i am not able to raise or submit the pull request to you.
Here is the reproducer project:
[bootstrap-shows-pdf.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/5324494/bootstrap-shows-pdf.zip)

Steps to repro:
Before opening the modal, play with the radio buttons like swapping between the string and blob radio button and then click on the open modal button. you will just observe a spinner untill the cursor is moved.  You would have to try for sometime to reproduce it.

Please let me know if you were able to reproduce it. Also please see if we can have some default parentoffset.. i dont know if that will make senes but just trying to find solution for this problem.

**Comment by dheerajm91** [comment]
Please use this project for Reproducer and i narrowed this down using the below sceanrios:

DOWNLOAD PEROJECT:
[bootstrap-shows-pdf.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/5324550/bootstrap-shows-pdf.zip)


Here is the exact steps to reproduce:
Once you install the node modules and serve the project.

There are 3 radio button:
Just click on multiple radio button and then click on the open modal button.
Then you will see the spinner in the modal and when you move your cursor then only pdf is displayed.

As soon as the screen loaded click on multiple named radio button and then click on open modal.
If its not reproduced, the again try refreshing the browser and follow the click on multiple named radio button and then click on open modal and i am positive that you will be able to reproduce.

I was able to reproduce it in this reproducer project:
![image](https://user-images.githubusercontent.com/25700737/95028708-1e95fe80-0657-11eb-9b97-55b6d4dd114b.png)

**Comment by dheerajm91** [comment]
@stephanrauh  Were you able to reproduce ?

**Comment by dheerajm91** [comment]
@stephanrauh : I feel the problem is when you are using the bsModal directive directly to open the modal with viewer in it.
 
Reproducible with code:
```
<button class="btn btn-link" (click)="openModal(pdfModal)">View Modal</button>


<!-- To avoid multiple modal instances, use bsModal directive to open the modal and display the PDF viewer  -->
<div bsModal #pdfModal="bs-modal" class="modal fade" tabindex="-1" [config]="{ignoreBackdropClick: true, keyboard: false}"
     role="dialog" aria-labelledby="dialog-sizes-name1">
  <div class="modal-dialog modal-large">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title">View PDF in modal</div>
      </div>
      <div class="modal-body">
        <cfw-pdf-viewer *ngIf="url" [src]="url"></cfw-pdf-viewer>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" (click)="pdfModal.hide()">Close</button>
    </div>
    </div>
  </div>
</div>```

**Comment by stephanrauh** [comment]
@dheerajm91 We seem to live in different time zones. I'l try your reproducer this evening, but first I have to go to work. :)

You're right, the modal window sounds like a hot trace. The original PDF viewer has only written to be used as the PDF viewer of Firefox. Making it work in an application wasn't easy, and making it work in a modal window seems to be even more challenging.

**Comment by stephanrauh** [comment]
I believe that https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent mentions the reason:

> offsetParent returns null in the following situations:
> - The element or its parent element has the display property set to none.

By default, the modal doesn't pop up immediately. Instead, it's shown with a nice fade-in effect. That take some time, and at the beginning, the modal is invisible. If the PDF viewer initializes really fast, it tries to scroll the current page into view while it's still impossible. That's a close call. Most of the time, Bootstrap is faster. It's always faster if the developer tools are shown, because they slow down JavaScript.

Adding a delay of 50 milliseconds solved the problem for me. Maybe you'll prefer 100 millisecond. That's still to fast to notice, but the safety margin is larger:

```TypeScript
  openModal(modaltemplate: any): void {
    this.resetSrc();
    this.selectedSource = null;
    setTimeout(() => this.stringSource = this.url, 50); // <<< added delay

    modaltemplate.show();
  }
```

**Comment by stephanrauh** [comment]
I've tried to fix the bug in the PDF viewer. However, this seems to be impossible. It's important that the PDF viewer is visible when it's activated. I'm afraid all I can do is improving the error message.

**Comment by dheerajm91** [comment]
Thats okay no worries :) 
and just checking if there is a way for you to check if you can use setTimeout with 200 0r 100 milliseconds to run scroll into view method so that the element.offsetparent is defined by then ?

If thats not possible, I will put a hack in my code to load the bootstrap modal first and then initialize the PDF viewer with data. Thanks for your time :)

**Comment by stephanrauh** [comment]
To my surprise, it's not possible. It's better to use the workaround.

**Comment by dheerajm91** [comment]
I have a better solution with bootstrap modals : We can use (onShown) callback which will fire once modal is loaded. With this pdf viewer will always have an parentoffset property and will be able to scroll into view.

```
<div bsModal #pdfModal="bs-modal" class="modal" tabindex="-1" [config]="{ignoreBackdropClick: true, keyboard: false}"
  role="dialog" aria-labelledby="dialog-sizes-name1" (onShown)="onModalShown($event)">
```

Thanks for all the help ! Your analysis helped me to narrow down the fix :)

**Comment by stephanrauh** [comment]
That's a good idea! I'll add it to the documentation.
