### ISSUE TITLE
Does it work on Internet Explorer 11?

### ISSUE THREAD

**Issue by vfabregat** [stephanrauh/ngx-extended-pdf-viewer#49]
I know it is an ugly and problematic browser, but we have a requirement to show PDFs in all browsers. I check the library and works smoothly in Edge, Firefox and Chrome. But not load in Internet Explorer and in the developers' tools show a JS error.

![image](https://user-images.githubusercontent.com/6525021/55476485-03d46b00-5617-11e9-95e8-50db88251b62.png)

**Comment by stephanrauh** [comment]
100% agreed on IE11. But wait until you see IE 9, 8 and 7... :)

We're using an older version of ngx-extended-pdf-viewer with IE11. It cost me a lot of time to support it. I can't promise it, but I believe the current version still supports IE11.

Before I start investigating, I'd like to ask you if you've activated the polyfills? If you've generated the project with the Angular CLI 7.3, that's automatically the case, but if you've created the project with an older version, you have to edit the polyfill.js file. The error message looks like a missing polyfill.

**Comment by vfabregat** [comment]
oh, that's sounds the case... let me test it tomorrow and I`ll come back to you with more information. Thank you for your support.

**Comment by vfabregat** [comment]
You were right. I activated the polyfills and it's working now

![image](https://user-images.githubusercontent.com/6525021/55540340-1906d380-56c3-11e9-9756-73aeb5704fd0.png)

Thank you again.

**Comment by stephanrauh** [comment]
That's great news! I've included a polyfills section to the README file.

**Comment by stephanrauh** [comment]
I've published the new documentation with version 0.9.18.
