### ISSUE TITLE
Auto size height depending on size of PDF document

### ISSUE THREAD

**Issue by cvjanick** [stephanrauh/ngx-extended-pdf-viewer#492]
**Is your feature request related to a problem? Please describe.**
Provide an option for automatic height of the viewer similar to the ng2-pdf-viewer the multi-page option in that library simply displays the entire document as a div / inline block. This can be useful for using custom scrolling, overlays and handling custom controls and events in multiple layouts. 

**Describe the solution you'd like**
Provide a similar option in your library even though some features (such as all toolbars) might automatically be disabled (but hopefully still available through the API) . 

**Describe alternatives you've considered**
We are using a custom overlay for multiple document types and need to be able to control the overlay and scrolling of the document in the viewer. ng2-pdf-viewer works in this sense but your library has the more robust API for layers, forms and so on to be able to view and access more content. 

**Additional context**
Let me know what else might be helpful in considering this. For our overlay we are using drag and drop on top of document pages, independent of document type. The overlays are tied to the positioning of the document in the viewer.

**Comment by stephanrauh** [comment]
In a nutshell, you'd like to get rid of the scrollbar?

**Comment by ykamchi** [comment]
Hi guys,

I need this functionality as well. Is there a workaround to achieve this functionality (100% height or anything to remove the scrollbars), until the feature will be available?

Thx,
Yohay

**Comment by stephanrauh** [comment]
If your PDF file is small enough to be rendered in real-time, here's a workaround:

```html
 <ngx-extended-pdf-viewer
    [src]="...'"
    [height]="height"
    [useBrowserLocale]="true"
    (pagesLoaded)="onPagesLoaded($event)"
  >

```

```typescript
  public height = '100vh';

  public onPagesLoaded(event: PagesLoadedEvent): void {
    console.log(event.pagesCount);
    const h = event.source.viewer.clientHeight;
    this.height = (h + 35) + 'px';
  }
```

**Comment by stephanrauh** [comment]
To dos left:

- [ ] trigger page rendering on scrolling (something like `scrollIntoView()`, just the other way round)
- [ ] implement it as a new value of `[height]´- e.g. `[height]="'full-height'"

**Comment by stephanrauh** [comment]
Version 6.2.0-alpha.0 adds scrolling when you select a new page in the sidebar or enter a new page number in the input field. Here's the live demo: https://pdfviewer.net/infinite-scroll

**Comment by stephanrauh** [comment]
The current implementation isn't perfect for very long document, but probably that's not the primary use case. Let's close the ticket.
