### ISSUE TITLE
Not loading thumbnails when scrolling in the thumbnail viewer

### ISSUE THREAD

**Issue by MBogushefsky** [stephanrauh/ngx-extended-pdf-viewer#493]
Hello I'm been going through the source code looking for a fix. I have noticed that the _scrollUpdated function in the viewer.js is not being called regardless of me scrolling in the thumbnail viewer. This is working at https://pdfviewer.net/simple but not in the app I implemented this viewer. I am using ranged requests to getting this document

This is how it is binded
`    this.scroll = (0, _ui_utils.watchScroll)(this.container, this._scrollUpdated.bind(this));`

And this is how I tested
`key: "_scrollUpdated",
    value: function _scrollUpdated() {
	  console.log("THUMBNAIL SCROLL UPDATED");
      this.renderingQueue.renderHighestPriority();
    }`

**Comment by stephanrauh** [comment]
I'd like to ask you the same as in #494: As you've mentioned yourself, the feature works on my machine. I believe you that it's broken in your application, but I can't do much about it without your help. Can you build a minimal program showing the error and send it to me? You can take this project as a basis for the reproducer: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
BTW, debugging becomes a lot easier when you add the attribute `[minifiedJSLibraries]="false"`. When the map files are available (which is the default configuration), you'll see the original source code of https://github.com/stephanrauh/pdf.js in the debugger.

You might also want to scan https://github.com/mozilla/pdf.js/issues. As you may or may not know, ngx-extended-pdf-viewer uses a fork of https://github.com/mozilla/pdf.js, so maybe - just maybe - your bugs has already been reported over there.

**Comment by MBogushefsky** [comment]
Resolved by removing my CSS change. Thank you for your patience.
`#thumbnailView {
    overflow: unset !important;
}`
