### ISSUE TITLE
Thumbnail not scrolling to view when selecting a page

### ISSUE THREAD

**Issue by MBogushefsky** [stephanrauh/ngx-extended-pdf-viewer#494]
When selecting a page in the PDF viewer I was expecting for the thumbnail viewer to go to it. Instead it doesn't do anything unfortunately. This is seen working at https://pdfviewer.net/simple but not in the app I implemented this in. I am using ranged requests to getting this document

The code related to this issue is found in the function 'scrollThumbnailIntoView' in the PDFThumbnailViewer class. This function is called but has no effect on the actual scrolling of the thumbnail viewer

**Comment by stephanrauh** [comment]
The method is called, but doesn't do anything? Strange. Are there error messages in the console window?

As you've mentioned yourself, the feature works on my machine. I believe you that it's broken in your application, but I can't do much about it without your help. Can you build a minimal program showing the error and send it to me? You can take this project as a basis for the reproducer: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

Thanks in advance,
Stephan

**Comment by MBogushefsky** [comment]
Resolved by removing my CSS change. Thank you for your patience.
`#thumbnailView {
    overflow: unset !important;
}`

**Comment by stephanrauh** [comment]
Ah, that explains everything! I'm glad to hear you've found the bug!

Best regards,
Stephan
