### ISSUE TITLE
Need single page mode

### ISSUE THREAD

**Issue by nbaua** [stephanrauh/ngx-extended-pdf-viewer#495]
Problem Area:

We want to implement a page by page view mode for PDF files which is essential for us for reviewing blueprints of construction projects on browser.
We tried with Horizontal scroll mode which still does not fit the requirement exactly.

Why: Because the blueprint documents are not A4 or consistent standard sizes and we prefer the classic click page navigation buttons. Also we prefer scrolling **within the page**, when zoomed at higher values and read tech-details on those PDF pages. 

In nutshell we want a single page loaded in viewport and be able to navigate through the standard prev-next buttons.

Seen the docs,	[scrollMode]="1" can not be applied via HTML markup.
The scrollModeOnLoad also can not be applied via any atrributes.

Feature Request:
[PageViewMode]="Single" ---> Single | Multiple

We believe. This will be helpful in other scenarios too.

Regards,
N Baua

**Comment by stephanrauh** [comment]
Seems to be the same request as #476.

**Comment by stephanrauh** [comment]
OK, you also seem to need to hide every page except the active page. Let's generalize it to three options:

`[PageViewMode]`= "Single | DoublePage | Multiple" `

**Comment by stephanrauh** [comment]
Plus, you need to suppress page-changes when the user scrolls. That's slightly similar to #492. So that'd be two new attributes:

```
[pageChangeOnScrolling]="true | false"
[showScrollbar]="true | false"
```

**Comment by stephanrauh** [comment]
I've started to implement the single-page mode. The current results don't look bad, but it still requires some work. It's not easy to implement such a change to pdf.js.

**Comment by stephanrauh** [comment]
@nbaua `pageViewMode="single"` has landed with version 5.1.0. There's a live demo at https://pdfviewer.net/page-view-mode.

Enjoy!
Stephan

**Comment by nbaua** [comment]
@stephanrauh ,

I can not thank you enough, my apologies could not revert back earlier due to my crashed laptop.
This is what I was after, I did tried to implement on my own, however I must admit, it was kind of a patch, your code is way far better. Thanks again for all your time and effort spent on this.

Regards,
N Baua

**Comment by stephanrauh** [comment]
Your welcome!
