### ISSUE TITLE
Extract Form Data

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#499]
First of all, version 5 is very nice. Especially the ability to have interactive forms. Great job on the last update.

I did a quick search on the PDFJS site and didn't find info on how to extract the data entered on the screen. 

It would be nice if a user would enter some values, then we can have a save button where we could save the values to a table. So user has a long form that they need to fill out but wants to save and pick up later. We could either store the values and reload them or save the PDF to the server with the values in the fields. 

Personally, I would prefer to access the values entered because I can manipulate the PDF on the server side. 

A json array would be a good way to extract the info...{field: name, value: Joe, ...}

**Comment by stephanrauh** [comment]
Maybe `PDFViewerApplication.pdfDocument.annotationStorage` is what you need. The keys of the Json object are a bit weird, at least in my demo file. That probably depends on your PDF generator.

![image](https://user-images.githubusercontent.com/3045767/95480842-a730d980-098c-11eb-8425-b2f975935965.png)

**Comment by stephanrauh** [comment]
@pedrojrivera Did my hint already help you?

**Comment by stephanrauh** [comment]
Please check out version 5.2.0-alpha.0. I've called the attribute `[(formDataSneakPreview)]`. When I've finally decided what the API looks like, I'll rename the attribute to `[(formDataSneak)]`. The source code of the showcase has a running demo: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/master/src/app/forms

**Comment by stephanrauh** [comment]
Your feature has landed with version 5.2.1. I hope I can fine-tune it so it integrates seamlessly into Angular forms (see #511). But the base functionality is already there.

I've published the live demo here: https://pdfviewer.net/forms.

If you're missing something, just tell me.

Enjoy!
Stephan

**Comment by pedrojrivera** [comment]
I have a project coming up where I will make use of this feature. We will be using FormGroups. I will let you know how it goes and if any refinements are needed. From what I saw, it looks like almost everything is there. 

Thanks!

**Comment by stephanrauh** [comment]
Great! I couldn't think of a useful ways to implement a `[formGroup]` attribute, but I guess you've already seen that. Every API I came up with is counter-intuitive.
