### ISSUE TITLE
Font-size bug after updating to 0.9.6 

### ISSUE THREAD

**Issue by Dertcmak** [stephanrauh/ngx-extended-pdf-viewer#5]
First of all, thank you for implementation such a component. Really useful.
 
After last update I got a problem with `font-size`. All of my html elements in `body` changed `font-size`. 

Here is a screenshot: 
![ngx](https://user-images.githubusercontent.com/20361454/48473519-e71ad080-e7f8-11e8-8a95-c3f38d27c41f.png)

**Comment by stephanrauh** [comment]
Oh - you're right. I'll fix this this evening.

**Comment by stephanrauh** [comment]
Please try version 0.9.7. It should solve the problem. Please report back so I know whether I can call it a 1.0.0 soon.

Thanks in advance,
Stephan

**Comment by Dertcmak** [comment]
I just tried 0.9.7 and it worked as expected. The problem has gone. 

Thank you!
Max
