### ISSUE TITLE
PDF zoom is getting changed automatically 

### ISSUE THREAD

**Issue by gokultrivandrum** [stephanrauh/ngx-extended-pdf-viewer#502]
PDF zoom is getting changed automatically, After changing the zoom to 93 % and 125 % using a toggle switch, After that on mouse hover or ctrl +mouse wheel scroll. Pdf is zooming automatically on mouse movement.

```
[(zoom)]="_zoomSetting" [minZoom]="minZoom" [maxZoom]="maxZoom"  [zoomLevels]="zoomLevels"
```

on button toggle     this._zoomSetting = '125%' to     this._zoomSetting = '93';
```TypeScript
  public minZoom = 0.6;
  public maxZoom = 3;
  public zoomLevels = [ 'auto',  'page-actual',  'page-fit',   'page-width',   0.5,   0.75,   1,   1.25,   1.5,   2,    2.5,    3  ];
  _zoomSetting: number | string | undefined = 'auto';
```

**Comment by stephanrauh** [comment]
I've never run into that problem, so I've tried to write a reproducer. It still doesn't happen on my machine. So I need your help.

Please clone or download https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue502-unexpected-zoom-changes and try to reproduce the bug. If you manage to reproduce it, you can send me your changes as a pull request.

BTW: CTRL+mouse wheel is meant to change the zoom level. That's not a bug. It's an intended behavior. https://pdfviewer.net/keyboard shows how to switch off this feature.

**Comment by stephanrauh** [comment]
@gokultrivandrum Did you manage to solve the problem? I couldn't reproduce it, so I'll close the ticket until I hear from you.
