### ISSUE TITLE
Adding deployUrl before pdfDefaultOptions.assetsFolder

### ISSUE THREAD

**Issue by mkanwar** [stephanrauh/ngx-extended-pdf-viewer#504]
Hi, 
I have multiple environment and every environment have different deployUrl, because of that, I got this error.
![image](https://user-images.githubusercontent.com/20163563/95709878-2de9fd00-0c92-11eb-89cd-15c426344943.png)

My configuration as follow:
![image](https://user-images.githubusercontent.com/20163563/95710100-9933cf00-0c92-11eb-966a-f4c2199bc057.png)

Is there any way I can add deployUrl pdfDefaultOptions.assetsFolder?

Thanks.

**Comment by stephanrauh** [comment]
This attribute is new to me. But I suppose you also have to configure the baseHref:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    ...
    <base href="/path/" />
```

I can only guess (because it's also new to me), but I suppose you can also configure this in the `baseHref` key of your `angular.json`, just below the `deployUrl`.

**Comment by stephanrauh** [comment]
Does this answer the question? I so, give me a short "ping" so I know I can close the issue.

Thanks in advance,
Stephan

**Comment by mkanwar** [comment]
For my case, I can't configure both to same value.. Currently, all my assets will under https://10.1.64.21/fssm/public/assets/*. Later, in production, we will store all our assets at ./fssm/public/prod/assets/*

**Comment by stephanrauh** [comment]
I see. Well, you can also override the default options:

```
pdfDefaultOptions.assetsFolder
```

**Comment by mkanwar** [comment]
Thanks @stephanrauh, it solved.

![image](https://user-images.githubusercontent.com/20163563/95777471-cf0b9e80-0cf8-11eb-97fb-70808378514c.png)

After overriding,

![image](https://user-images.githubusercontent.com/20163563/95777916-a9cb6000-0cf9-11eb-90ce-edad8bb42da2.png)

**Comment by stephanrauh** [comment]
That's great news! Why I wrote my answer, I was in a hurry, so I didn't find the time to mention the feature is even documented: https://pdfviewer.net/troubleshooting (second paragraph).

BTW, it seems you didn't activate the map files. Debugging ngx-extended-pdf-viewer is more fun when you see the real source code.
