### ISSUE TITLE
findMultiple is not working

### ISSUE THREAD

**Issue by lisabeyy** [stephanrauh/ngx-extended-pdf-viewer#506]
I am looking to find several sentences and highlight them in the pdf, although the method findMultiple doesn't seem to work.

**Comment by stephanrauh** [comment]
Would you mind to elaborate? You know, the method seems to work in the showcase (https://pdfviewer.net/find):

![image](https://user-images.githubusercontent.com/3045767/95912656-60374f80-0da3-11eb-9c83-25515394eec2.png)

**Comment by stephanrauh** [comment]
@lisabeyy I didn't hear from you for a while. Did you manage to solve the bug?
