### ISSUE TITLE
Support nameddest

### ISSUE THREAD

**Issue by bretthodel** [stephanrauh/ngx-extended-pdf-viewer#51]
pdf.js supports passing nameddest according to the [viewer option page](https://github.com/mozilla/pdf.js/wiki/Viewer-options).  Would it be possible to add support for this as an input?

**Comment by stephanrauh** [comment]
Sounds good. However, I don't know what a named destination is. It sounds like a bookmark?

**Comment by stephanrauh** [comment]
Here's an explanation of `namedDest`: https://github.com/mozilla/pdf.js/issues/5258#issuecomment-54633345

**Comment by stephanrauh** [comment]
Solved with version 0.9.29. I've added an attribute `[nameddest]`.
