### ISSUE TITLE
Need to have Canvas access outside the viewerContainer

### ISSUE THREAD

**Issue by nbaua** [stephanrauh/ngx-extended-pdf-viewer#517]
Problem Statement:

We are trying to render various texts and shapes on a PDF using a canvas, since the current canvas object is embedded inside a **viewerContainer** we are not able to access this in the Angular via ViewChild reference or any other way.

To overcome this situation we created a overlay canvas (our own copy of canvas) on top of the pdf viewer and succeeded to an extent. However there are couple of issues with this approach.

1. Every time user zooms or rotates, we have to reset our overlay canvas accordingly.
2. For PDFs of uneven page sizes our approach does not work correctly.
3. The performance can be a issue with larger PDF files (which has not been tested yet with our overlay canvas approach).

**Solution we'd like**
A method like getCanvas() and getCanvasContext() would be more fruitful.

**Alternatives we've considered**
adding a #ViewerCanvas on the canvas element which can be accessible by angular via a @ViewChild reference.

**Additional context**
![image](https://user-images.githubusercontent.com/17998763/97008234-31b63300-1560-11eb-986b-a236779036d5.png)

**Comment by stephanrauh** [comment]
You can access the canvas with a complex CSS selector like ".page[data-page-number='4'] > canvas". Would this solve your problem?

**Comment by nbaua** [comment]
@stephanrauh 

Hi,
Thanks for reverting so immediately, 

We tried accessing the canvas using the CSS selectors as well as also tried getElementsByTagName(), however they both seems to have own set of issues in Angular world. Getting the childView reference and the context to the canvas would make it lot easier.

Thanks

N Baua

**Comment by stephanrauh** [comment]
Well... everything inside the viewerContainer is not generated by Angular. So I can't do anything else but using the CSS selector. And that's what you've already tried. Adding insult to injury, the canvas is drawn in a service worker. So you can't easily add you own code to the renderer of pdf.js.

**Comment by nbaua** [comment]
@stephanrauh 

Yes, I can understand where you came from, I also saw the source code earlier and realized that pdf.js canvas is being wrapped inside a container. Still do you see a chance to write some function at the wrapper level which exposes this canvas to the Angular world? I don't want to push it further on you, however I am still being little optimistic. What do you suggest?

Any help on this is a BIG help. Awaiting for your reply, Thanks for showing interest, your time and help so far.

Regards,
 N Baua

**Comment by stephanrauh** [comment]
Maybe I can help you when you tell me which issues you ran into. Currently my best guess it you've run into timing issues. pdf.js is massively asynchronous, so probably you just have to find out which event your have to subscribe. Did you already try to use `(pageRendered)`? That's the event that's raised after rendering a page. So at this point of time, your canvas element is guaranteed to be available.

**Comment by nbaua** [comment]
Hi @stephanrauh 

Yes, we are making use of pageRendered, this works for me for now, Only areas of pain when I have PDF files which have different page sizes and the user is rotating, the canvas does not get **re-drawn** sometimes. Other than that I believe, there are no issues in that context. However when we are  zoomed say 200%, due to overlay canvas, we are facing problem for scroll-pan with hand tool, because the canvas is on top. lots of issues with that  and that is the main reason we wanted to have access to the PDF viewer's (pdf-js) canvas.

Regards,
N Baua

**Comment by nbaua** [comment]
for anyone who wants to have an easy access to the canvas

Please use 
`
onPageRendered(e): void {
    this.__CANVAS = e.source.canvas; // gives you access of canvas when the page is loaded - pages loaded only once 
}
`

Regards,
N Baua
