### ISSUE TITLE
Cannot read property 'on' of null

### ISSUE THREAD

**Issue by ruizenrmar** [stephanrauh/ngx-extended-pdf-viewer#52]
Hi, I have a problem when my application try to load big PDF... if I increment the value of 'delayFirstView' this problem don't occurs, however its not a efficient solution because I don't know the size of PDF file.

This is my code in html and typescript files.

```html
<mat-card-title>
    <h5>{{documentName}}</h5>
</mat-card-title>
<mat-card-content fxLayoutAlign="center" [ngClass]="{'content': !isImage}">
    <img *ngIf="isImage" class="image" src="{{url}}">
    <ngx-extended-pdf-viewer *ngIf="!isImage && url !== null" [src]="url" class="viewer" delayFirstView="2000" useBrowserLocale="true"></ngx-extended-pdf-viewer>
</mat-card-content>
```

```TypeScript
  public documentName: string;
  public url: string;
  public isImage: boolean;

  constructor(private storageService: StorageService, @Inject(MAT_DIALOG_DATA) public data: any) {
  }

  ngOnInit(): void {
    this.url = null;
    this.isImage = this.data.isImage;
    this.documentName = this.data.name;
    if (this.isImage) {
      this.storageService.getImage(this.data, 'big').then(
        (resultImage: string) => {
          this.url = resultImage;
        });
    } else { // pdf viewer
      this.url = this.data.url;
    }
  }
```

Thank you for your time and pay attention!!

**Comment by stephanrauh** [comment]
Ok, that's interesting. It's the first hint why these strange exceptions happen, and why they can be solved by increasing the `delayFirstView` property. Thanks!

In theory, that shouldn't happen because PDF.js doesn't load the entire PDF file. It loads it in chunks of 64 KB, and processes each chunk immediately. So the PDF viewer can display the first page before it has finished loading the PDF file.

However, the server has to support partial loading. Maybe - just maybe - your server doesn't support that. Let's check that first.

Would you mind to have a look at your browser's network tab? Is the PDF file loaded in 64 KB chunks, or is there only a single, huge request? Is there any relation between the time it takes to load the PDF file and the minimum working `delayFirstView` setting?

**Comment by stephanrauh** [comment]
Does your error look like so?

````
core.js:15724 ERROR TypeError: Cannot read property 'on' of null
    at ngx-extended-pdf-viewer.js:374
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:2281)
defaultErrorLogger @ core.js:15724
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
next @ core.js:17771
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
(anonymous) @ core.js:17321
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
onHandleError @ core.js:17321
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:198
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
ZoneTask.invoke @ zone.js:487
timer @ zone.js:2281
setTimeout (async)
scheduleTask @ zone.js:2302
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:301
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
scheduleMacroTaskWithCurrentZone @ zone.js:1245
(anonymous) @ zone.js:2317
proto.(anonymous function) @ zone.js:1569
push../node_modules/ngx-extended-pdf-viewer/fesm5/ngx-extended-pdf-viewer.js.NgxExtendedPdfViewerComponent.ngAfterViewInit @ ngx-extended-pdf-viewer.js:369
callProviderLifecycles @ core.js:22416
callElementProvidersLifecycles @ core.js:22390
callLifecycleHooksChildrenFirst @ core.js:22380
checkAndUpdateView @ core.js:23316
callViewAction @ core.js:23548
execComponentViewsAction @ core.js:23490
checkAndUpdateView @ core.js:23313
callWithDebugContext @ core.js:24177
debugCheckAndUpdateView @ core.js:23879
push../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges @ core.js:21688
(anonymous) @ core.js:18119
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:18119
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent @ core.js:18153
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap @ core.js:18095
(anonymous) @ core.js:17808
push../node_modules/@angular/core/fesm5/core.js.PlatformRef._moduleDoBootstrap @ core.js:17808
(anonymous) @ core.js:17776
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
ZoneAwarePromise.then @ zone.js:1012
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:17803
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:78
0 @ main.ts:12
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 27 more frames
```

**Comment by stephanrauh** [comment]
Please set `[useBrowserLocale]="false"` and add one of the language of `node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files/be.html` (or whichever language you need) to the header of your `index.html`. I guess that'll solve the bug.

BTW: please report back, especially if this solves the bug. Otherwise, I'll never know when to close the ticket. Thanks in advance!

**Comment by ruizenrmar** [comment]
> Does your error look like so?
> 
> ```
> core.js:15724 ERROR TypeError: Cannot read property 'on' of null
>     at ngx-extended-pdf-viewer.js:374
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
>     at Object.onInvokeTask (core.js:17290)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
>     at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
>     at ZoneTask.invoke (zone.js:487)
>     at timer (zone.js:2281)
> defaultErrorLogger @ core.js:15724
> push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
> next @ core.js:17771
> schedulerFn @ core.js:13515
> push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
> push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
> push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
> push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
> push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
> push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
> (anonymous) @ core.js:17321
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
> onHandleError @ core.js:17321
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
> push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:198
> push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
> ZoneTask.invoke @ zone.js:487
> timer @ zone.js:2281
> setTimeout (async)
> scheduleTask @ zone.js:2302
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
> onScheduleTask @ zone.js:301
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
> scheduleMacroTaskWithCurrentZone @ zone.js:1245
> (anonymous) @ zone.js:2317
> proto.(anonymous function) @ zone.js:1569
> push../node_modules/ngx-extended-pdf-viewer/fesm5/ngx-extended-pdf-viewer.js.NgxExtendedPdfViewerComponent.ngAfterViewInit @ ngx-extended-pdf-viewer.js:369
> callProviderLifecycles @ core.js:22416
> callElementProvidersLifecycles @ core.js:22390
> callLifecycleHooksChildrenFirst @ core.js:22380
> checkAndUpdateView @ core.js:23316
> callViewAction @ core.js:23548
> execComponentViewsAction @ core.js:23490
> checkAndUpdateView @ core.js:23313
> callWithDebugContext @ core.js:24177
> debugCheckAndUpdateView @ core.js:23879
> push../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges @ core.js:21688
> (anonymous) @ core.js:18119
> push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:18119
> push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent @ core.js:18153
> push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap @ core.js:18095
> (anonymous) @ core.js:17808
> push../node_modules/@angular/core/fesm5/core.js.PlatformRef._moduleDoBootstrap @ core.js:17808
> (anonymous) @ core.js:17776
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
> onInvoke @ core.js:17299
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
> push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
> (anonymous) @ zone.js:889
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
> onInvokeTask @ core.js:17290
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
> push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
> drainMicroTaskQueue @ zone.js:601
> Promise.then (async)
> scheduleMicroTask @ zone.js:584
> push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
> push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
> scheduleResolveOrReject @ zone.js:879
> ZoneAwarePromise.then @ zone.js:1012
> push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:17803
> ./src/main.ts @ main.ts:11
> __webpack_require__ @ bootstrap:78
> 0 @ main.ts:12
> __webpack_require__ @ bootstrap:78
> checkDeferredModules @ bootstrap:45
> webpackJsonpCallback @ bootstrap:32
> (anonymous) @ main.js:1
> Show 27 more frames
> ```
> ```

yes!

**Comment by ruizenrmar** [comment]
> Please set `[useBrowserLocale]="false"` and add one of the language of `node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files/be.html` (or whichever language you need) to the header of your `index.html`. I guess that'll solve the bug.
> 
> BTW: please report back, especially if this solves the bug. Otherwise, I'll never know when to close the ticket. Thanks in advance!

Thank you for your response. I have a doubt:

How add language in index.html? 

So... If the application supports more than one language, this solution is correct?

**Comment by stephanrauh** [comment]
You can add multiple languages. Let's have a look at one of the files in the `inline-locale-files` folder:

```html
<script type="application/l10n">{"default_locale":"el","locales":{"el":{"previous":{"title":"Προηγούμενη σελίδα"}, ...
</script>
```

Basically, that's a Json file with an arbitrary number of locales. To add German to the list of languages, you add everything following `"locales":{` like so:

```html
<script type="application/l10n">
{
  "default_locale":"el",
   "locales":{
      "el":{"previous":{"title":"Προηγούμενη σελίδα"}, ...},
      "de":{"previous":{"title":"Eine Seite zurück"}, ... }
    }
</script>
```
The only challenge is to deal with the long, long lines and to use the correct number of braces. :)

**Comment by stephanrauh** [comment]
BTW, you can also put the `<script type="application/l10n">` tag into any component (instead of putting it into the `index.html`). The PDF viewer looks for the tag in the entire DOM tree. Just take care the language bundle is part of the DOM when the PDF viewer is loaded and initialized.

**Comment by ruizenrmar** [comment]
Thank you!! its resolved the problem!
