### ISSUE TITLE
ngx-extended-pdf-viewer with flipbook style

### ISSUE THREAD

**Issue by giangsaker1102** [stephanrauh/ngx-extended-pdf-viewer#522]
I want to display the pdf look like flipbook but can't integrate with turnjs.
if possible try it. It is really useful for many projects. Thanks for your contributions.
![macbook-preview-e1597596378306](https://user-images.githubusercontent.com/11018431/97274836-c4f4ae80-1867-11eb-91d1-17f6e32a4121.png)

**Comment by stephanrauh** [comment]
Turn.js is pretty cool, but did you check the license? You must not use it commercially. But that's what many users of ngx-extended-pdf-viewer do. So me need a different implementation.

**Comment by stephanrauh** [comment]
I think the first step to implementing a book-flip effect is to create a library with a friendly license and without dependencies to jQuery or other third-party libraries. I believe it should be simple to re-write turn.js in TypeScript and HTML5. Maybe I'll start such a project one of these days. It's weird that the page-turn effect is so popular, but there's hardly any useful open-source library out there.

**Comment by stephanrauh** [comment]
If you don't mind using an old pdf.js version, you can use this PDF viewer: https://github.com/RaffaeleMorganti/pdf-viewer. Unfortunately, that's a unmaintained library, so use it at your own risk.

Also see https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/161. In the meantime, I've learned a lot about pdf.js, so maybe I could pick up the project again. But still, the first step is to re-write turn.js or find a good alternative to turn.js.
