### ISSUE TITLE
Question: It's possible to show images using the ngx-extended-pdf-viewer?

### ISSUE THREAD

**Issue by felipewmartins** [stephanrauh/ngx-extended-pdf-viewer#524]
Hi,
 I would like to know if possible to show images using this lib.
Thanks a lot :)

**Comment by stephanrauh** [comment]
No. It's a PDF viewer. But you're not the first one to ask this, so I'd like to ask back: what's the advantage of using a PDF viewer over simply displaying an `<img src="whatever.png">`? Which features should my viewer offer?
