### ISSUE TITLE
Not working with system.js.config

### ISSUE THREAD

**Issue by AnandPiyush** [stephanrauh/ngx-extended-pdf-viewer#526]
Hi,
i was trying to add ngx-extended-pdf-viewer to system.comfig.js but as it dont have js files or umd files available i am.not bale to add it inside that,
can anyone help on this how to do.

**Comment by stephanrauh** [comment]
Did you manage to solve the problem? ngx-extended-pdf-viewer has definitely not been design with system.js.config in mind, so I'm curious. Is to possible to get it up and running?

**Comment by AnandPiyush** [comment]
yes, i am able to load using system.config.js but getting multipleDefine error now in below script from pdf-es5.min.js:
function webpackUniversalModuleDefinition(t,r){"object"==typeof exports&&"object"==typeof module?module.exports=r():"function"==typeof define&&define.amd?define("pdfjs-dist/build/pdf",[],r):"object"==typeof exports?exports["pdfjs-dist/build/pdf"]=r():t["pdfjs-dist/build/pdf"]=t.pdfjsLib=r()}

trying to resolve that, is there anything you will be able to help  here
