### ISSUE TITLE
Allow to block external link 

### ISSUE THREAD

**Issue by Foszcz** [stephanrauh/ngx-extended-pdf-viewer#527]
Hi , 
I wonder if it's possible to use the [target] property in order to add a new value in her enum and which allow to block the redirection with external links present in the PDF 

[target]="LinkTarget.BLOCK" (block navigation )

kind regards 

Christopher

**Comment by stephanrauh** [comment]
Probably - but I didn't understand yet what you're trying to achieve. Do you want to disable links? So that the links are visible, and can be recognized as links, but clicking such a link doesn't do anything?

**Comment by Foszcz** [comment]
Yes, exactly ^^ it's a demand of a client , in fact the pdf was generate for the whole platforms and for the mobile app they don't want a redirection.

**Comment by stephanrauh** [comment]
I don't want to add this feature to the library, so I added a demo to the showcase. You know, you can implement the feature yourself. One source of errors less for me, and much more flexibility for you. 

Have a look at the third tab of https://pdfviewer.net/links.

Enjoy!
Stephan
