### ISSUE TITLE
Toolbar goes away for forever, When changing the zoom level below 80%

### ISSUE THREAD

**Issue by nbaua** [stephanrauh/ngx-extended-pdf-viewer#531]
- Does the bug also happen on https://pdfviewer.net/simple? NO
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template - 

**I used this repo as start, now I have to update it based on my project requirement.**

**Describe the bug**
**When changing the zoom level below 80% (or when the view port height does not lead to scrollbar) the toolbar goes away.**

My first impression was it is happening due to the mobile friendly zoom feature (mobileFriendlyZoom), however it is not the case.
The toolbar is gone and never to be returned when the zoom level is increased back to 100% or more.
I tried custom zoom toolbar too, but no help, I am clueless what is causing this issue.

The following is the minimum code I have.

`
<ngx-extended-pdf-viewer
        #blue
        [src]="'assets/files/example.pdf'"
        [height]="'98vh'"
        [useBrowserLocale]="true"
        [showOpenFileButton]="true"
        [textLayer]="true"
        pageViewMode="single"
        [mobileFriendlyZoom]="zoom"
        [zoom]="zoom"
      >
      </ngx-extended-pdf-viewer>
      
      
`

**Version info**
- Version of ngx-extended-pdf-viewer
    "ngx-extended-pdf-viewer": "^5.1.0",

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]
    Chrome - Version 86.0.4240.111 (Official Build) (64-bit) on Windows 10 Desktop with resolution 1920X1080
 
To reproduce the behavior:
1. Run the project
2. Click on zoom minus button (till the moment the vertical scrollbar is gone) like 80% or below
3. The toolbar disappears
4. Now if we increase the zoom level to 100% or more the toolbar still missing
(I created floating toolbar to get zoom when the original toolbar disappear)

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)
File can be found at:
https://psychology.ucsd.edu/_files/undergrad/exampleapastylebspaperempirical.pdf
_used from my projects assets directory, however that should not matter._

**Screenshots**

**Auto**
![image](https://user-images.githubusercontent.com/17998763/97774868-6d18b900-1b81-11eb-82b9-2af5eae94659.png)

**100%**
![image](https://user-images.githubusercontent.com/17998763/97774934-11026480-1b82-11eb-9a02-9777606d30a9.png)

**80% and Toolbar Gone** 
![image](https://user-images.githubusercontent.com/17998763/97774947-2b3c4280-1b82-11eb-8a2d-f5de047394d2.png)

**For Forever**
![image](https://user-images.githubusercontent.com/17998763/97774952-38593180-1b82-11eb-8284-4000ab7dc127.png)

**Additional context**
**Edit:
in Opera it re-appears when zoom level is 200%, with problem in UI, see below**

![image](https://user-images.githubusercontent.com/17998763/97775162-8b33e880-1b84-11eb-9e56-d5fa7d14bda3.png)

**Edit: I have also checked if the toolbar goes behind the Navbar I have in my application, the answer is NO.
It appears wrong in both chrome and opera

![image](https://user-images.githubusercontent.com/17998763/97775234-2200a500-1b85-11eb-81cd-db2feafe300b.png)

![image](https://user-images.githubusercontent.com/17998763/97775239-30e75780-1b85-11eb-8eb5-a64553608861.png)

**As you can see the toolbar has gone behind the browser address bar when the header/navbar is removed** 

If required I can upload the video file on cloud and share the experience as it happens.**

Also noticed the drop down has weird arrow issue, however this is still ok for me if toolbar appears
![image](https://user-images.githubusercontent.com/17998763/97774986-81a98100-1b82-11eb-9f5f-26e894cd5790.png)

I really appreciate how the extended PDF viewer project has grown so far, best wishes.

**Thank you!**
N Baua

**Comment by nbaua** [comment]
I guess looking it further revealed more ...

Why toolbar has to zoom along with the viewer?

**At 50%**

![image](https://user-images.githubusercontent.com/17998763/97778103-db1daa00-1b9a-11eb-94fe-337ec5f058a1.png)

**At 100%**

![image](https://user-images.githubusercontent.com/17998763/97778117-eec91080-1b9a-11eb-895a-ac2fa6c69eea.png)

**At 200%**
 
![image](https://user-images.githubusercontent.com/17998763/97778125-fee0f000-1b9a-11eb-8c57-3e49774ba696.png)

_Please note the browser is not zoomed only the PDF viewer is zooming here._

**Comment by stephanrauh** [comment]
You set both zoom setting to the same value. I suppose that's causing the errors:

```html
[mobileFriendlyZoom]="zoom"
[zoom]="zoom"
```

I intended `mobileFriendlyZoom` to have a fixed value. In increases the size of the toolbar, so you can use it with gloves. The original use-case was in a factory, where the workers have to wear protective gloves. So we had to enlarge the menus and toolbars.

Setting `mobileFriendlyZoom` to values below 100% doesn't sound useful to me. It becomes hard to use the toolbar with such tiny widgets. But it's interesting the toolbar vanishes altogether. You've piqued my curiosity!

**Comment by stephanrauh** [comment]
As for the dropdown: I'm already trying to solve this in #523.

**Comment by stephanrauh** [comment]
@nbaua I can't reproduce the issue, so I need your help. Can you debug the method `calcViewerPositionTop`? Maybe it shifts the PDF viewer over the toolbar, thus hiding the toolbar.

![image](https://user-images.githubusercontent.com/3045767/97780935-224e6f80-1b88-11eb-858c-135fbde393c7.png)

Thanks in advance,
Stephan

**Comment by nbaua** [comment]
> @nbaua I can't reproduce the issue, so I need your help. Can you debug the method `calcViewerPositionTop`? Maybe it shifts the PDF viewer over the toolbar, thus hiding the toolbar.

Hi Stephan,

Okay, I would debug it and let you know, once I am back from my job, I guess today evening I should be able to check this one, unless I am piled up with more workload.

Thanks for your prompt reply.

Regards,
N Baua

**Comment by nbaua** [comment]
> As for the dropdown: I'm already trying to solve this in #523.

Oh Okay,
I guess that's CSS messing with the UI, 

On the other hand,
I came up with my own floating toolbar (custom) and which works pretty well.
Thanks to you for sharing some examples on your web site, that did helped a lot.

Here is what I built,
![image](https://user-images.githubusercontent.com/17998763/97861860-75f8be80-1d2a-11eb-953b-49fa82139a37.png)

It is a translucent toolbar containing the basic tooling for now, but it works nicely say for example at 50% it looks like

![image](https://user-images.githubusercontent.com/17998763/97862038-b48e7900-1d2a-11eb-8062-6b9534a155a2.png)

I can drag it or leave it on the top corner. so yes its kinda solved my problem.
I tried changing zoom values, however the problem happened twice (zoom 100 and mobile fz at 120 or something)
I will still try to check that once again, when I am off work.

**Comment by nbaua** [comment]
I believe, in order to remove the toolbar, we need to set all the buttons to false, which is quiet expensive and I didn't knew until exploring that thing for few hours playing with the configuration parameters, A configuration like **HidePrimaryToolBar** (false|true) could have been a nice enhancement.

**Comment by nbaua** [comment]
> > @nbaua I can't reproduce the issue, so I need your help. Can you debug the method `calcViewerPositionTop`? Maybe it shifts the PDF viewer over the toolbar, thus hiding the toolbar.
> 
> Hi Stephan,
> 
> Okay, I would debug it and let you know, once I am back from my job, I guess today evening I should be able to check this one, unless I am piled up with more workload.
> 
> Thanks for your prompt reply.
> 
> Regards,
> N Baua

This is confirmed, setting mobile zoom levels is causing the issue, also when when supplied custom zoom levels, the zoom level values in the drop-down goes crazy.

![image](https://user-images.githubusercontent.com/17998763/97878413-9df51b80-1d44-11eb-8c48-54787224adfa.png)

**Comment by stephanrauh** [comment]
The zoom levels don't get crazy. It's just that I'm a mathematician. 1.0 is 100% to me, so 100.0 is ten thousand per cent. :)

**Comment by stephanrauh** [comment]
Can we close the ticket? As far as I see, the problem is settled, and the new attribute `showPrimaryToolbar="false"` is a new suggestion, so I'd prefer to open a new ticket.
