### ISSUE TITLE
Users help users - or: please lend your helping hand!

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#532]
This library has become incredibly successful. This also means feature requests and bug report come in faster by the day. So I'd like to find contributors. It's fun to run a one-man show, but it's so much more fun to be part of a team!

There are many ways to contribute:
- Report bugs and feature reports. But that's probably what lead you here. 👍
- Read bug reports of other users and help them if you know the solution. That'd help me a lot!
- Contribute pull requests. Before you do, it's a good idea to tell me, so I know I shouldn't work on the same topic.
- Become a team member. You need to gain some trust to become a team member, but it's easier than you think. So why don't you give it a try?

**Comment by muuvmuuv** [comment]
A good start would be to add donation (through GitHub or anything else) to financially support your work and work done by others (issue bounty).

**Comment by stephanrauh** [comment]
Seems like I really need to dig into German tax lax soon... if more than a handful of people donate, it becomes an income by the definition of the tax law. I doubt this will happen, but you never know.

The issue bounty is an interesting idea. I wasn't aware of that!
