### ISSUE TITLE
Getting more out of pdfLoaded event

### ISSUE THREAD

**Issue by nbaua** [stephanrauh/ngx-extended-pdf-viewer#533]
I wanted to know the PDF file size, which is downloaded from a URL, I don't see anything easily available.

**Describe the solution you'd like**
Would love to see more on the **pdfLoaded** event, currently it is just providing the total page numbers the PDF file contains.
Which is good, however I assume people would like to get more information on the PDF file itself.

I personally have a requirement to show the file size, on the UI and I think the pdfLoaded event is right place to get that information. Other information like Author, Printing Allowed etc can be a good candidate, however I am not sure if the pdfLoaded event is best place to get it.

**Alternatives I've considered**
I am planning to use the node file io for getting the PDF file size for now, however that would require me to trigger another event and some io operations.

Looking forward to have this enhancement.
Love this viewer and your contribution so far.

Thanks a lot

- N Baua

**Comment by stephanrauh** [comment]
Also see #450.

**Comment by nbaua** [comment]
> Also see #450.

Hi Stephan,
Yes, I had viewed this one, Thanks for your prompt reply and considering the request for enhancement. Looking forward for this enhancement to be available. 

Thanks a lot
- N Baua

**Comment by stephanrauh** [comment]
Your feature has landed with version 6.0.0-beta.6. Live demo at: http://localhost:4200/file-info

 There are some interesting metadata that might be worth extracting, too. For example, some of the demo files contain detailed copyright hints, so I'll keep this ticket open for until I've managed to have a close look at these metadata.

**Comment by stephanrauh** [comment]
Note that the file size is stored as "maybeFileSize" because sometimes it's just a wild guess. For example, if you're receiving the file as a Base64 encoded string it's hard to say how big the original file was.

**Comment by stephanrauh** [comment]
I've dropped adding the metadata because no two PDF files seem to use the same metadata. If anybody needs the metadata for some reason, I can add them, but in general they seem to be pretty useless. Let's call the latest beta a final version!

**Comment by nbaua** [comment]
I guess, this is getting better and better, thanks man. I hope, I would have been a contributor to this repo. Kudos man.

**Comment by stephanrauh** [comment]
You've definitely contribute a couple of good idea. If you're interested, you can do even more. Every once in a while, there's an easy bug report, or a user question you can answer. Or you can help me to improve the showcase. Report typos, suggest or implement better demos, add a searchable index... there are countless ways to help!

**Comment by nbaua** [comment]
Okay,

I will try my best, if I make something from demo perspective, will share
it with you.

On the other hand, GitHub is the best way too. Thanks

Regards
N Baua
