### ISSUE TITLE
FR: Need to have Hide/Show primary toolbar flag

### ISSUE THREAD

**Issue by nbaua** [stephanrauh/ngx-extended-pdf-viewer#535]
**Is your feature request related to a problem? Please describe.**
Currently the visibility of primary toolbar depends upon setting various flags to false. When all such button show/hide flag is set to false the primary toolbar goes off.

**Describe the solution you'd like**
We can have the feature other-way round, simply introduce a flag something like **showPrimaryToolbar** (true|false) and that would save lot of efforts/markup in the code.

**Describe alternatives you've considered**
Adding a override CSS class, hijacking the UI, but not the best approach in my opinion.

**Additional context**
#531

**Comment by stephanrauh** [comment]
Good news: your feature has landed with version 6.0.0-beta.2. See the demo at https://pdfviewer.net/hiding-buttons.

**Comment by stephanrauh** [comment]
BTW, I intend to make it a final version during this week-end or early next week. IMHO, the library is production-ready. I just love being able to introduce breaking changes. :)

**Comment by nbaua** [comment]
@stephanrauh ..

_I just love being able to introduce breaking changes. :)_  LOL
If that is so, I can ask more and more features.
BTW, I love the demo, man you're just awesome.

Thanks
N Baua
