### ISSUE TITLE
increase toolbar & button sizes

### ISSUE THREAD

**Issue by leonore14** [stephanrauh/ngx-extended-pdf-viewer#539]
Hello,

Is there a way to increase the height of the toolbar & the size of the buttons ?
I've tried to force the css of ngx-extended-pdf-viewer #toolbarViewer in giving a new height, but it doesnt seem to work for me. 
Any idea on how to fix that ?

Thanks a lot for your help.

**Comment by stephanrauh** [comment]
Bien sûr... that's what the attribute `[mobileFriendlyZoom]` does. Here's the live demo: https://pdfviewer.net/mobile

Enjoy!
Stephan

**Comment by leonore14** [comment]
@stephanrauh  great !! many many thanks !!!!!
