### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by pisipisi** [stephanrauh/ngx-extended-pdf-viewer#54]
![Capture](https://user-images.githubusercontent.com/14434123/56618256-ac0e9b80-65e7-11e9-842d-6b379f14fa31.PNG)

And get this error by copy exact demo to my project 

`<ngx-extended-pdf-viewer
                        *ngIf="visible[0] && !hidden"
                        [src]="''assets/pdfs/pdf-sample.pdf''"
                        backgroundColor="#e8e8ef"
                        [mobileFriendlyZoom]="mobileFriendlyZoom"
                        [showZoomButtons]="true"
                        [showSidebarButton]="showSidebar"
                        [useBrowserLocale]="false"
                        [showSidebarOnLoad]="true"
                        [delayFirstView]="50"
                        [(zoom)]="zoom"
                        [showPresentationModeButton]="true"
                        [height]="height"
                        [handTool]="handTool"
                        [(page)]="page"
                        [filenameForDownload]="filenameForDownload"
                        (pagesLoaded)="onPagesLoaded($event)"
                      >
                      </ngx-extended-pdf-viewer>`

**Comment by stephanrauh** [comment]
I've managed to reproduce your bug after [asking StackOverflow](https://stackoverflow.com/questions/55047063/implementing-pdf-js-viewer-example). The key to understanding the error is the attribute `[useBrowserLocale]="false"`.

You can do so, but in this case, you're responsible for providing the translation files yourself. The easiest way is to copy the content of `node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files/be.html` (or whichever language you need) to the header of your `index.html`.

BTW: please mention the version of the library you're using when you're reporting a bug. I've spent a lot of time trying to reproduce your bug. Funny thing is I've managed to reproduce it - but it looks different in ngx-extended-pdf-viewer 0.9.19+.

**Comment by stephanrauh** [comment]
Oops - your error was the first error I've documented, almost a year ago. Have a look at https://www.npmjs.com/package/ngx-extended-pdf-viewer#troubleshooting.
