### ISSUE TITLE
Missing characters in IE11 using Blob or base64 source

### ISSUE THREAD

**Issue by rezi-elton** [stephanrauh/ngx-extended-pdf-viewer#540]
**Describe the bug**
ngx-extended-pdf-viewer fails to properly render/display all the text/characters when using _certain_ Blob or base64 sources in IE 11.
- The example in https://pdfviewer.net/base64 which uses https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/master/src/app/base64/pdfBase64.ts renders correctly
- On the other hand, https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/src/app/pdfBase64.ts which appears to have a different font format (?) renders a corrupted file with missing characters in IE11.

**Version info**
- 5.3.0, 5.4.0-beta.1

**Desktop (please complete the following information):**
 - Internet Explorer 11
 
**To Reproduce**
Run the pdfviewer in IE 11 using https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/src/app/pdfBase64.ts source 

**Screenshots**
![Base64_IE11](https://user-images.githubusercontent.com/60399157/98171977-33fc8380-1eb6-11eb-9aa6-3bde8e552207.PNG)

**Comment by stephanrauh** [comment]
Oops. I can confirm that. Something's broken between pdf.js 2.6.57 and the current 2.6.4xx version. Weird.

**Comment by maxHus** [comment]
I have the same issue with Edge, did anyone find a workaround  ?

**Comment by stephanrauh** [comment]
Sorry for responding late. I've finally found some time to analyze the bug. It's not a problem of the encoding. If you're using the original file (see attachment), the same error occurs. It also occurs on the showcase of the base library, pdf.js: https://mozilla.github.io/pdf.js/es5/web/viewer.html

[example.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/5568593/example.pdf)

**Comment by stephanrauh** [comment]
@maxHus @rezi-elton Please open the ticket here: https://github.com/mozilla/pdf.js/issues

You can use the example file.
