### ISSUE TITLE
Scrollbarbehaviour in IE11 when pageViewMode = 'single'

### ISSUE THREAD

**Issue by bilgino** [stephanrauh/ngx-extended-pdf-viewer#542]
**Describe the bug**
In IE11 the Scrollbar automatically scrolls to bottom when the pageViewMode is 'single' AND you paginate to the last page using the "jump to last page" button from the paginator.

**Version info**
- Current Version

**Desktop (please complete the following information):**
IE11, Windows 10
 
**To Reproduce**
Please open your DEMO Page in IE11 https://pdfviewer.net/page-view-mode
...and click the paginator (last page)

**Comment by stephanrauh** [comment]
I've solved the bug with version 7.0.0-beta.5. I still need to run a final test and to copy the bugfix to the bleeding-edge branch, so I can't close the ticket yet. But I'm positive you can already run a test yourself.

**Comment by stephanrauh** [comment]
Good news: the bug is gone in Edge.
Bad news: https://pdfviewer.net is completely broken in IE11. At least, in my copy of IE11. The error message doesn't contain any useful information, so I need your help. What does "Uncaught (in promise): Syntaxerror" mean?

**Comment by stephanrauh** [comment]
@bilgino Does the new version of the library work in your project?

**Comment by bilgino** [comment]
I did not update the project to the current version of ngx-extended-pdf-viewer yet! I can't relate to your specified error message "Uncaught (in promise): Syntaxerror". I did not get this type off error! If this fix is breaking the application than you should not upgrade your library.

**Comment by stephanrauh** [comment]
It's not the fix. The error occurs before the PDF file is opened. But that's all I managed to learn after several hours of debugging. Even such a simple project as https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue556-non-numeric-zoom is broken.

Adding insult to injury, the debugger of IE11 crashes all the time. I believe I have to give up IE compatibility. The market share of IE11 has dropped to 1%, so there's no reason to continue supporting it, anyways.

**Comment by bilgino** [comment]
I think this bug is acceptable!
