### ISSUE TITLE
Persisting [zoom] across PDF files

### ISSUE THREAD

**Issue by bilgino** [stephanrauh/ngx-extended-pdf-viewer#543]
**Is your feature request related to a problem? Please describe.**
Currently the zoom settings are not persisted across PDF files. So changing the [src]="blob:URL" attribute will cause a scaling fall back to an inital scale of what ever, but does not keep the zoom setting from the previous PDF file.

**Describe the solution you'd like**
Please make the zoom setting persisted across PDF file changes or at least provide an event hook. 

**Describe alternatives you've considered**
Please add an flag for [ZoomPersist] = "true/false"

**Comment by stephanrauh** [comment]
I believe you can implement this feature yourself easily. `[(zoom)]` is a two-way binding attribute. Store the zoom setting in your application or in the `localStorage`, and you're good to go. How do you like the idea?

**Comment by bilgino** [comment]
Yes, I use the localStorage API to persist the zoom value (read/write) but the problem is, if the zoom value is read from the localStorage and assigned programmatically, the following occurs. The PDFViewer initially sets a zoom value by default e.g. 80%, and only after that the value from the localStorage is read and assigned to [zoom]. This is triggering the (currentZoomFactor) event twice. So if switching [src] attribute resulsts in a flickering/blinking kind of effect. Because it first shows e.g. "page-width" (79%) and then it zooms to the value from localStorage e.g. 20%. The 2-way-binding solution did not solve the problem. Please let me know if you need an stackblitz example.

**Comment by stephanrauh** [comment]
Oh, yes, I'm aware of the problem. You don't need to create a Stackblitz example. Stackblitz doesn't support ngx-extended-pdf-viewer, anyways. :(

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 7.0.0-beta.0. Fixing the behavior of `[(zoom)]` is probably breaking applications relying on the bug, hence the new major version.

**Comment by stephanrauh** [comment]
I've just learned what you tried to tell me halb a year ago. I wasn't aware pdf.js stores the zoom factor on a per-document basis in `localStorage`. So I didn't understand your bug report properly. Sorry about that! I've just prepared a bug fix.

If everything works according to the plan, you can omit `[zoom]` or set it to `undefined` in version 9.0.0. Then the default is still `auto`, unless the user has opened the document before. In that case, their last setting is respected.

I've uploaded a very early preview of the feature to http://pdfviewer.net.

**Comment by stephanrauh** [comment]
The feature has landed with version 9.0.0-alpha.1.
