### ISSUE TITLE
I want to load file PDF from URL (http://example.com/test.pdf)

### ISSUE THREAD

**Issue by giangsaker1102** [stephanrauh/ngx-extended-pdf-viewer#544]
I want to load file PDF from URL (http://example.com/test.pdf) but I received an error below
"ERROR Error: Uncaught (in promise): Error: Invalid parameter object: need either .data, .range or .url
Error: Invalid parameter object: need either .data, .range or .url"

`this.pdf_path: string = 'http://example.com/test.pdf'`

HTML:
```html
<ngx-extended-pdf-viewer
     [src]="pdf_path"
     [height]="'96vh'"
     [useBrowserLocale]="true"
     [textLayer]="true"
     [showHandToolButton]="true">
     [mobileFriendlyZoom]="zoom"
</ngx-extended-pdf-viewer>`

Please give me a help!

**Comment by stephanrauh** [comment]
It's difficult to find the error remotely... at first glance, everything looks OK. My best guess is there's something wrong with the `src` attribute. Is it really a string?

The error is thrown in the API.js. Maybe you can debug the method getDocument() to learn what's going on. It helps to set the attribute `[minifiedJSLibraries]="false"`.

**Comment by giangsaker1102** [comment]
I received error: http://localhost:4200/catalog/'http://example.com/test.pdf'

**Comment by stephanrauh** [comment]
Looks like you've got an extra tick. As a consequence, your URL is treated as a relative path.

**Comment by stephanrauh** [comment]
Any news? Did you manage to solve the bug?
