### ISSUE TITLE
IOS 6.1.1 Blob urls are not working

### ISSUE THREAD

**Issue by ShashankHegde16** [stephanrauh/ngx-extended-pdf-viewer#547]
Hi , The pdfs are not loading in the latest Wkwebview engine. We are using the latest ngx-extended pdf but problem is since IOS has removed the UIwebview in the IOS-engine 6.1.1 the files with blob:// are unable to load.

**Comment by stephanrauh** [comment]
This sounds like a problem specific to Cordova. Does it happen in your native Browser, too? Is it limited to BLOBs?

**Comment by ShashankHegde16** [comment]
With base64 attribute it works but if i pass in blob or array buffer it is not . May i know how are you using blob or array buffer. because if you are converting the blob or array buffer to blob url thats not accepted by cordova IOS engine 6.1.1

**Comment by stephanrauh** [comment]
Here you are:

```typescript
  @Input()
  public set src(url: string | ArrayBuffer | Blob | Uint8Array | { range: any }) {
    if (url instanceof Uint8Array) {
      this._src = url.buffer;
    } else if (url instanceof Blob) {
      this._src = URL.createObjectURL(url); // <<<<< Blobs are converted here
    } else if (typeof url === 'string') {
      this._src = url;
      if (url.length > 980) {
        // minimal length of a base64 encoded PDF
        if (url.length % 4 === 0) {
          if (/^[a-zA-Z\d\/+]+={0,2}$/.test(url)) {
            console.error('The URL looks like a base64 encoded string. If so, please use the attribute base64 instead of src');
          }
        }
      }
    } else {
      this._src = url;
    }
  }
```

**Comment by ShashankHegde16** [comment]
Thanks For the Quick response @stephanrauh . Able to work with array buffer now as we are not converting to blob url.

**Comment by stephanrauh** [comment]
I'm glad you've managed to solve the issue. Just out of curiosity: might this article have helped you, too?

https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html
