### ISSUE TITLE
0.9.19 not displaying document

### ISSUE THREAD

**Issue by rekna1** [stephanrauh/ngx-extended-pdf-viewer#55]
I'm afraid I have to create the issue again (#42). I know I mentioned the bug was fixed in the latest version but probably some javascript files were cached. I tried with a brand new project and added 0.9.8, With this version the pdf is displayed. Then I updated the project to version 0.9.19, no errors but also no document shown.

I've created a repo at https://github.com/rekna1/TestNgxExtendedPdfViewer.
It's just a basic angular application and I followed instructions from your website. It should display a document that is in the assets folder.
When I run it with ng serve no document is displayed. I can see the document is fetched. Also the right number of pages is displayed.
When I downgrade the project to version 0.9.8 then document is displayed.

**Comment by rekna1** [comment]
I inspected and compared the html in both version and the following change is causing the issue :
<div class="zoom" style="height: 100%;"> in version 0.9.19
<div class="zoom" style="height: 80vh;"> in version 0.9.8

height: 100% causes the div to be 0px height, when I change to 80vh then the document shows, probably because my app-component has no height specified.

**Comment by stephanrauh** [comment]
It seems I stumbled about this problem myself some time ago (see #45). Too bad the bug reporter didn't answer, so after a while, I forgot about the problem.

**Comment by stephanrauh** [comment]
I've added a formula that enlarges the PDF viewer if the height setting results in 0 pixels. In this case, it fills all available space to the buttom, or at least 100px.

**Comment by stephanrauh** [comment]
I've published the new feature with version 0.9.20. Please run a test and tell me if it helps!

Thanks in advance,
Stephan
