### ISSUE TITLE
[logLevel]="0" does show regular log messages

### ISSUE THREAD

**Issue by pixxio** [stephanrauh/ngx-extended-pdf-viewer#551]
**Describe the bug**
Log-Level = 0 does still show log-messages that are no errors..
Still visible is:
- "PDF viewer: ngx-extended-pdf-viewer running on pdf.js 2.6.405"
- "PDF 198082420dedf7438672cdd8d5155d60 [1.7 Microsoft® Word für Microsoft 365 / Microsoft® Word für Microsoft 365] (PDF.js: 2.6.405) modified by ngx-extended-pdf-viewer)"
- "isPrimaryHidden" / "isPrimaryVisible"
These log-messages are neither a warning nor an error, just plain "console.log"

**Version info**
- 6.0.0-beta.1

**Desktop (please complete the following information):**
 - any browser
 
**Smartphone (please complete the following information):**
 - any device

**To Reproduce**
- can be reproduced with any project.

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. implement this component in your angular-project
2. check your console after this component was initialized

**Demo PDF file**
- should occur with every PDF file

**Screenshots**
![image](https://user-images.githubusercontent.com/12611695/99243221-a77c8a00-2800-11eb-8c3d-1a3b2249507a.png)

**Comment by stephanrauh** [comment]
The "primaryHidden" messages are already gone in the final release 6.0.0.

I'm not sure I can do something about the other two messages. They are emitted in the pdf.js library. Every time I customize it I risk not being able to merge the latest improvements from the parent project. But I'll have a look at it.

**Comment by stephanrauh** [comment]
I've implemented the feature. Unfortunately, the bleeding edge build is broken, so I'll fix that first before publishing a new version.

**Comment by pixxio** [comment]
Thanks a lot! Looking forward to the new version :)

**Comment by stephanrauh** [comment]
Your feature has landed in version 6.1.0.

Enjoy!
Stephan
