### ISSUE TITLE
Importing a built ngx-extended-pdf-viewer with custom pdf.js into an existing Angular project

### ISSUE THREAD

**Issue by DHalilovic** [stephanrauh/ngx-extended-pdf-viewer#561]
You currently have customized build directions (which work like a charm!) and instructions on importing the standard npm-installed version into an existing project... but how would one import a customized build into an existing project? Thanks in advance!

**Comment by stephanrauh** [comment]
First answer: I'd love to write a schematic to automate the process... but you guys and gals keep me occupied by opening new interesting tickets all the time! :)

Truth to tell, while I'm convinced providing a schematic simplifies using the library a lot, I'm afraid it'll fail all the time when run on existing project. These projects bear a lot of history, so it's next to impossible to predict what's necessary.

But if I get it right, your task is even more challenging. You've already customized pdf.js. Is this correct? If so, it depends an how much you've customized. If it's only a handful of modifications, you can clone my fork of pdf.js, apply your changes to it, and compile ngx-extended-pdf-viewer from source.  Or you can use the standard copy of ngx-extended-pdf-viewer, but make sure your own copy of pdf.js, pdf.worker.js, and viewer.js are copied to the `assets` folder.

If you've modified pdf.js in more than just a few places, I'm at a loss. Technically, the approach I've described above still works, but it'll amount to - well - a lot of work. Maybe it's better to use the approach of CodeHippy (https://www.npmjs.com/package/ng2-pdfjs-viewer).

There's a third option. If you customizations are interesting to a broader audience, send me a pull request, or drop me an e-mail if you aren't sure about it yet.

**Comment by stephanrauh** [comment]
Does any of my suggestions help you? Or did I miss the point? Usually, I keep every ticket open until I know it's been solved, so I'd appreciate your feedback!

Best regards,
Stephan

**Comment by DHalilovic** [comment]
Schematic or not, you're legendary for your work on this, regardless! I'll try to slow down my issues in the near future :)  

To begin, I actually have forked your pdf.js repo, implementing my changes upon yours-- they're rather specific to the overall application in terms of data formatting, but I'll definitely see if something would suit more users, in general!

My modifications work within the ngx-extended angular application (launched via npm start), and I set things up there via the good old `sh updateMozillasPdfViewer.sh` and `npm run win-package` combo. My initial plan of action had simply consisted of copying the packaged `dist/npm-extended-pdf-viewer` over to the other Angular project. I saw you had referenced the dist/npm-extended-pdf-viewer dependency within the project's `package.json` via a local file path (being new to local packages, I didn't realize `npm install` symlinks the `dist/npm-extended-pdf-viewer` to a directory in `node_modules`).

Ah, yes, I had also made changes to your `ngx-extended-pdf-viewer.component.ts` and `ngx-extended-pdf-viewer.service.ts` to suit my pdf.js changes, which would explain my attempts at a copy-paste approach. HOWEVER, your comment has helped me realize that I did not perform the `angular.json` changes for copying the `assets` folder, as specified in the directions for installing the default npm package. I'll make those changes, and return with updates-- currently, the viewer graphics display, but with a few errors, so this is likely the source of my faults.

As always, thanks for your quick responses! I'll append the updates to this thread!

**Comment by stephanrauh** [comment]
Awesome! I'm not sure if `npm install` really symlinks the dist folder. That'd be useful, but I don't think it works out of the box.

How do you deal with the updates of pdf.js itself? I always have a hard time when I merge the latest changes into my fork of pdf.js. I image you're suffering from the same trouble. :)

**Comment by DHalilovic** [comment]
Ah, out of curiosity, how does the local folder reference work within your `package.json`? If you have a resource which I can read, rather than me forcing you to explain, that'd be good too :) (most of the info I found requires an `npm install` to update the node modules based on changes made to the local folder, and only one mentioned symlinking).

Regarding updates to your pdf.js... fortunately, all of my changes took place in `pdf_find_controller.js`, `text_layer_builder.js`, and `app.js`. To play it safe, I simply copied functions rather than overwriting them, so as to easily cross-reference my changes. On a side note, the methods used to highlight different words in unique colors were nearly identical between your code and my changes to the original Pdf.js, which was cool to see!

Regarding my current issue... it seems the `angular.json` changes were key to fixing the viewer! I'm working within an Angular-Electron app, and will be feeding byte arrays retrieved from files via the Electron process into your viewer on the Angular process. Fingers crossed, and thanks for your help!

**Comment by stephanrauh** [comment]
I'm aware there's a clever way using `npm link` (or something like that). The idea is you're developing a local library, publish it to your global npm cache (the cache where everything you install with `npm -g` goes), and use this cache to run `npm install` in another local project on your machine. AFAIK it's not compilcated, but so far I've been to lazy to figure it out.

Instead, I simply copy the dist folder of my library to the `npm_modules` folder of my target Angular project. That's not 100% failsafe, but it works well enough. It's a cumbersome and slow approach, so I really should do something about it. One of these days... :)

**Comment by stephanrauh** [comment]
> On a side note, the methods used to highlight different words in unique colors were nearly identical between your code and my changes to the original Pdf.js, which was cool to see!

Awesome!
