### ISSUE TITLE
Log releases properly

### ISSUE THREAD

**Issue by jpike88** [stephanrauh/ngx-extended-pdf-viewer#565]
Instead of incrementing the version on every little tweak, it's a better idea to group them together and then make a release (use the release feature) to log that release, and summarise the changes made, including breaking changes. I'm trying to figure out what broke/changed since 4.1.2 and it's a rabbit hole because there's no documentation.

Otherwise, great library, this is just a management tip!

Thanks

**Comment by jpike88** [comment]
I didn't see the demo site. never mind lol

**Comment by stephanrauh** [comment]
For convenience, here are the changelogs: https://pdfviewer.net/changelog

Breaking changes are summarized in the README: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/README.md#potentially-breaking-changes

**Comment by jpike88** [comment]
thanks. on an unrelated note, I read about IE11 support being dropped on more recent version and got scared. I know ie11 sucks but libraries like this are more likely to be used by companies that are stuck on old hardware, as it's a document viewer... pls remember ie11!

**Comment by stephanrauh** [comment]
The problem with IE11 is that it displays an error without telling what the error is and where it occurs. So most of the time, I'm just clueless. Plus, I don't own a Windows PC. How to convince the community to help me debugging? :)

**Comment by jpike88** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

You can get a virtual box with IE11 with no problems. I think maybe supporting 'core'/minimal features (like initialising ok, showing the PDF ok) would make it less scary...

FYI, screenshot of latest in action, fired up ok in IE11

<img width="1255" alt="Screenshot 2020-11-24 at 7 41 25 PM" src="https://user-images.githubusercontent.com/9585787/100095491-23c03e80-2e8d-11eb-9a46-be7d49ba6720.png">
