### ISSUE TITLE
Additional PDF Form Field Types

### ISSUE THREAD

**Issue by jmpspm-git** [stephanrauh/ngx-extended-pdf-viewer#567]
First off thanks for your work on this library.  I’ve been looking for something like this.  After trying it out it looks like there are a few form field types that are not working correctly.  These are:

**1. Multi Line Text Fields**

PDF text fields can be defined as being multi line.  Pdfjs supports this and creates a textarea field for editing the values.   The values for multi line text fields cannot be set or returned by the formData currently.

**2. Multi Select Lists**

PDF list fields can be defined as being multi select.  Pdfjs supports this and creates a select field with the multiple attribute for editing the values.   These fields should allow the formData to provide an array of values to select the items and also return an array of selected items to the formData.  Currently only one value can be selected by or returned from the formData.

**3. Check Boxes**

PDF check boxes can be defined with the value that should be set when the checkbox is selected.  Here’s an example of a checkbox field definition in a PDF editor.

![Capture](https://user-images.githubusercontent.com/74985582/100143834-e7c4b380-2e63-11eb-9a4c-392af9334a88.PNG)

When the checkbox is selected the value **_checked_** will be returned from the field, and setting the field to **_checked_** will cause the check box to be selected.  In the current implementation of the code the checkbox value only uses true and false for the field values.  The export value can be found in the annotations for the field. Here’s the annotation for the above field in Chrome’s console.
![Capture](https://user-images.githubusercontent.com/74985582/100143413-4b9aac80-2e63-11eb-8905-64123e15d1bc.PNG)

**4. Radio Button Sets**

PDFs can contain sets of radio buttons.  Selecting any button in the set unselects all the other buttons.  Like checkboxes the creator of the PDF form can specify the value that should be returned for each radio button.  Here’s an example of a radio button definition in a PDF editor.

![Capture](https://user-images.githubusercontent.com/74985582/100143531-75ec6a00-2e63-11eb-98b7-ddf4e2e3574f.PNG)

When this radio button is selected the field should return a value of **_RadioButtonChoice1_**.  These choice values can be found in the annotation for the field.  Here’s the annotation for this field in Chrome’s console.  
![Capture](https://user-images.githubusercontent.com/74985582/100143606-9288a200-2e63-11eb-8066-b1968c8c52c7.PNG)

I have made changes to your code in my environment and I think I have these issues resolved.  
Here’s a screen shot of a PDF using these field types and displaying the formData values below.

![Capture](https://user-images.githubusercontent.com/74985582/100143040-bb5c6780-2e62-11eb-9381-c92fee4bf080.PNG)

If you’re interested, I can send you the code, or put in a pull request.  I’m not at all familiar with Git so I’ll have to learn how to do so.  
Thanks,
Jeff

**Comment by stephanrauh** [comment]
Whow. I'm impressed by your analysis! Yeah, sure, pull requests are always welcome. If that's too difficult, I'll also accept a zip file of your source code. I'm just afraid it'll be difficult to detect the changes. You know, a simple thing like formatting the code automatically makes comparing two versions of the same code difficult.

**Comment by stephanrauh** [comment]
BTW, when you're referring to pdf.js, which version are you talking about? I doubt I've introduced bugs to pdf.js when I integrated it into my library. Or rather, I don't think I added errors to form support, because that's all-new source code so merging the changes was easy. Maybe you're talking about feIatures that have been implemented in pdf.js 2.7?

@Timvandermeij I'd like to include you in the loop because I believe it's interesting to you. Short story: your Acroform support is tremendously popular. However, that means developers detect flaws every once in a while, and I never know if it's my fault or if it's just a feature pdf.js doesn't support yet. :)

**Comment by jmpspm-git** [comment]
I'm using the version of PDFjs that was downloaded as part of you library.  It looks like it's PDF.js: 2.6.408.

![Capture](https://user-images.githubusercontent.com/74985582/100154317-61b06900-2e73-11eb-8bb3-fafedcb8bf9d.PNG)

**Comment by timvandermeij** [comment]
I'm not sure what `formData` here refers to, but I guess that's what the entered data in `ngx-extended-pdf-viewer` is called? The points mentioned in the initial comment above _should_ all work in PDF.js, except for point 2 which, assuming again that `formData` refers to saving/printing entered data, is a known issue; see https://github.com/mozilla/pdf.js/blob/4ba28de2608866dcb10d627d77dc19ff3d017c17/src/display/annotation_layer.js#L804-L810.

**Comment by stephanrauh** [comment]
Thanks! Yes, `[formData]` is my approach to exchange data betweeen Angular and the Acroform.

**Comment by jmpspm-git** [comment]
I submitted the pull request for these changes.  It's the first time I've used Git, so hopefully I did everything correctly.

Thanks,

Jeff

**Comment by stephanrauh** [comment]
Jeff, you've passed the test with flying colors! I've yet to build and test the library, but this was one of the times I simply merged the PR after reading it.

Do you have a test document using the new features I can use in the showcase? I've stumbled in the Acroform business, so I'm ill prepared to create interactive forms myself. Plus, I'd like to use a form that's nice or even puts a smile on the reader's face, but for some reason, my creativity's spending a week on vacation. :)

**Comment by stephanrauh** [comment]
Your PR has landed with version 7.0.0-beta.6. Would you mind to run a test and tell me about it?

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
I've updated the showcase. However, I don't know how to demonstrate the new features.

**Comment by jmpspm-git** [comment]
I can update the showcase with a PDF that has the new field types early next week.  I have family over for the Thanksgiving Holiday that's keeping me away from my computer.

Thanks,
Jeff
