### ISSUE TITLE
Duplicated IDs for #findInput and #password.

### ISSUE THREAD

**Issue by weixinwu** [stephanrauh/ngx-extended-pdf-viewer#572]
I am using multiple pdf viewers on one page, the console is reporting the non-unique Ids warnings from the ngx-extended-pdf-viewer. 

Is it possible to remove the findInput input and password input? cause I don't really need to use them and they are giving  warnings.

**Comment by weixinwu** [comment]
Just found out that it doesn't support multiple viewer on the same page from the troubleshooting page.

**Comment by stephanrauh** [comment]
Yeah. Using global variables is deeply ingrained in the DNA of pdf.js. So the only way to put multiple PDF viewer on a page is using iFrames. Sorry about that!

Best regards,
Stephan
