### ISSUE TITLE
Property filenameForDownload is not documented.

### ISSUE THREAD

**Issue by Stromwerk** [stephanrauh/ngx-extended-pdf-viewer#58]
I was looking for a way to define the name of the PDF when it's downloaded and couldn't find it in the documentation. Upon inspection of the code however I noticed that there is a `filenameForDownload` input, so I used that and it worked great.

This should be added to the documentation. I looked into creating a PR with just the new property, however the table looked generated and decided not to mess with it.

P.S. I noticed some other discrepancies in the documentation. I am open to fixing them and submitting a PR, in which case information on how to best go about doing that would be great.

**Comment by stephanrauh** [comment]
Pull requests are always welcome. Don't be shy about the table - it's hand-crafted.

**Comment by stephanrauh** [comment]
I've merged the PR. I'll close the ticket when I've published a new version of the library.

**Comment by stephanrauh** [comment]
In the meantime, I've published the new version. Let' close the ticket.
