### ISSUE TITLE
minZoom and maxZoom doesn't work on android

### ISSUE THREAD

**Issue by Foszcz** [stephanrauh/ngx-extended-pdf-viewer#583]
**Describe the bug**
When i set value for the input minZoom and maxZoom all works on browsers ( Firefox , Chrome ) but on android inputs are ignored when i pinch in , the zoom dont' stop to the specific value 

**Version info**
tested on 5.0.0 , 6.0.0 , 7.0.0
 
**Smartphone (please complete the following information):**
- Samsung j5 , android 10 

![image](https://user-images.githubusercontent.com/25663208/101647675-4b8cd600-3a39-11eb-9513-53a0f853639a.png)

**Comment by stephanrauh** [comment]
It's the same on iOS. Good finding, thanks!

**Comment by stephanrauh** [comment]
This week I'm very busy, so I can't promise to fix the bug this week.

**Comment by Foszcz** [comment]
> 
> 
> This week I'm very busy, so I can't promise to fix the bug this week.

Thanks to you for your quick response

**Comment by stephanrauh** [comment]
Intermediate result: the source code does check the minimum and maximum zoom level. So why is it ignored?

**Comment by stephanrauh** [comment]
The bugfix has landed with version 7.1.0.

Enjoy!
Stephan
