### ISSUE TITLE
Possibility to remove the leftside bar

### ISSUE THREAD

**Issue by vic1707** [stephanrauh/ngx-extended-pdf-viewer#585]
**Is your feature request related to a problem? Please describe.**
I came from 'ng2-pdf-reader' which is full of bugs but offer exactly what i need.
I'm looking for a module that can display a PDF (I'm not looking for any toolbar even through these can be useful)

I'm looking for an attribute that could completely hide (or remove) the left sidebar.

**Describe the solution you'd like**
A simple boolean attribute like '[showToolbar]' but for that left sidebar

**Describe alternatives you've considered**
I've looked for every attributes and didn't find it, hope i didn't miss it

**Additional context**
that left sidebar : 
![image](https://user-images.githubusercontent.com/28602203/101991374-95c9bd80-3cac-11eb-8207-3cd7f36b7d74.png)

**Comment by stephanrauh** [comment]
Getting rid of the sidebar is easy: `[showSidebarButton]="false"` plus `[sidebarVisible]="false"`. If I understand you correctly, there's even a live demo of what you need. Navigate to https://pdfviewer.net/hiding-buttons and uncheck every checkbox.

**Comment by stephanrauh** [comment]
Bonus question: you've mentioned Vadim's library is full of bugs. I frequently recommend using his library, so I'd like it to be in good shape. I might even be ready to send pull requests to Vadim if need be. That said, would you mind to tell me about the bugs that made you cross? It doesn't have to be on GitHub - you can send me an e-mail: webmaster1 at beyondjava dot de.

**Comment by vic1707** [comment]
Thanks man !! 
Those two lines combined work ! (didn't taught to combine those) and thanks for the link it will help me and my friend to get the perfect look.

We were using ng2-pdf-viewer for it's simple look not really for anything else (and because it was the first result with good reviews).
We left his package for yours today after weeks of troubleshooting (and some ragequit) because we weren't able to make the pages fit the height (div nor browser). 
There is an option for it [zoom-scale] which works great for width but not for height, we found only one stackoverflow page with the same issue about it which tells us to edit everything on the CSS itself.
We also got trouble with the function triggered on error that wasn't giving anything (I opened an issue weeks ago, still no response [by the way thanks for your quick response ! ])

**Comment by stephanrauh** [comment]
All right, so that's something for my medium-to-long-term plans. Currently, https://pdfviewer.net exclusively covers my PDF viewer, and it exclusively covers Angular, but my goals are much more ambitious. It's just that you guys kept me busy with countless bug reports and feature requests. Which is a good thing!

However, I'd also like to cover ng2-pdf-reader and the other alternatives in the Angular world. Plus, I'd also like to cover Vue.js and React.js, maybe be plain vanilla HTML.

You've convince me to put Vadim's library higher on my priority list!

Best regards,
Stephan
