### ISSUE TITLE
Vertical Scrolling bar showing in singlePage mode (and infinitescroll as Stephan told me)

### ISSUE THREAD

**Issue by vic1707** [stephanrauh/ngx-extended-pdf-viewer#589]
**Describe the bug**
Useless vertical scrolling bar showing on simple and infinitescroll mode with zoom set as page-fit

**Version info**
- Lastest so 7.1.0

**Desktop (please complete the following information):**
 - Firefox, Chrome
 
**To Reproduce**
simply put `[pageViewMode]="'single'"` and `[zoom]="'page-fit'"`

**Demo PDF file**
tried with a bunch of pdf, don't know if i can upload it here (it's all the images from https://mangadex.org/chapter/93905 converted into one PDF)

**Screenshots**
on the showcase :
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/28602203/102082728-bad84080-3e12-11eb-86d7-65fa40c1a1ba.png">

**Additional context**
Talked about it with Stephan who says that the same issue occurs with the infinite scroll mode.

**Comment by vic1707** [comment]
got better screenshot now that `'single'` works better than `'simple'` : 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28602203/102137689-8046c600-3e5b-11eb-8569-15d17b1b69cf.png">

**Comment by stephanrauh** [comment]
The bug fix has landed with version 7.1.1.

**Comment by vic1707** [comment]
Hello, 
thanks for the fix ! 
Unfortunately it still happens when `[showBorders]="false"` is used ^^.
I tested and it seems like it's the only argument that causes the bug to return.

with borders : 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28602203/102765648-2e330280-437d-11eb-84b4-6b355a7573e8.png">


without borders : 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28602203/102765624-24110400-437d-11eb-9205-83f0384a6745.png">

**Comment by stephanrauh** [comment]
Right you are! Luckily, it was easy to fix. The fix has landed in version 7.1.2.
