### ISSUE TITLE
Being able to dynamicaly change viewer mode

### ISSUE THREAD

**Issue by vic1707** [stephanrauh/ngx-extended-pdf-viewer#590]
It would be nice to be able to change dynamicaly the value of `[pageViewMode]="ViewerMode"`. 
It should be possible as the 'ng2-pdf-viewer' can do it with it's `[show-all]` attribute

**Comment by stephanrauh** [comment]
This may take a while. It wasn't easy to implement the page view modes. Making them dynamic won't be easy, either. :)

**Comment by stephanrauh** [comment]
@vic1707 Can you give me a hint how important the feature is to you? Is it a "nice to have" or a "must have"?

**Comment by vic1707** [comment]
@stephanrauh It's not what I would consider as a "must have". I just have to tell the users to reload in order to change the reader mode.

**Comment by stephanrauh** [comment]
I see. So I'm considering it a medium priority, after the most pressing bugs. 

BTW, you don't have to tell your users to reload the page. You can automate that, too. I've implemented this in my showcase to switch between the standard version, the bleeding edge version, and ng2-pdf-viewer. Basically, you can force reloading by running

```typescript
location=location
```

or one of the 534 (!) alternatives - see https://beyondjava.net/535-page-reloads :)

**Comment by vic1707** [comment]
Yes thanks, it's working great as à workaround 😉

**Comment by stephanrauh** [comment]
I believe the workaround is good enough. Let's close the issue.

**Comment by michaelmarcuccio** [comment]
This issue is somewhat important for my use case where a document is loaded and then I check to see if the file has > .5MB per page. If that is true then I want to change to single page mode due to massive load times if a user scrolls quickly to the bottom of a pdf with high MB per page. The only workaround I can think of is to load the blob and find the pagecount before rendering in the pdfviewer, which is double the work on the browser.

**Comment by stephanrauh** [comment]
I can have a look at the problem again. The user is able to toggle between view modes (via the menu), so it should be possible to do that programmatically, too. Plus, there's the all-new single-page mode implemented by the Mozilla team. I'm positive their implementation is less capricious than my implementation :)

**Comment by stephanrauh** [comment]
Version 13.0.0-alpha.13 is going to fix this issue.

**Comment by vic1707** [comment]
Congrats 🎉@stephanrauh

**Comment by michaelmarcuccio** [comment]
@stephanrauh This issue was for [pageViewMode] and the fix was instead done for [scrollMode]. As of right now it seems [pageViewMode] will not allow updating dynamically.

**Comment by stephanrauh** [comment]
I'm not sure if it's possible to change `[pageViewMode]` dynamically, but I can have a look. I've opened a new ticket to track the progress (#1415).
