### ISSUE TITLE
Zoom using wheel and ctrl goes to endless loop

### ISSUE THREAD

**Issue by ddankwerth** [stephanrauh/ngx-extended-pdf-viewer#591]
Bug doesn't happen on mozilla viewer

Go to pdfviewer.net
To the zoom page
Zoom works well with toolbar changes
However, a quick wheel and ctrl goes into endless loop of changing zoom level

Desktop win 10 chrome latest

**Comment by stephanrauh** [comment]
Oh, yes. I hope I'm the only one because nobody's complained about this bug.

At the moment, I'm out of clues. How to solve the bug? Each time I run into the bug, my CPU runs at nearly 100%, so I can't debug it. Dear community, has anybody an idea how to proceed?

**Comment by cristianofromagio** [comment]
Don't know how to listen for `Ctrl + Scroll` events for zooming specifically, but assuming it is working now, is there a handling logic somewhere that we could `throttle` its value update?

**Comment by stephanrauh** [comment]
Phew, difficult. If you want to explore it yourself: the wheel events are processed in the file app.js, function webViewerWheel(), of the base library, pdf.js.

Can you elaborate what you mean by throttle? Are you referring to a simple slow-down, or a maximum of x events per seconds, or something else?

I suspect the error mentioned above is a weird race condition, so throttling might be a good solution.

**Comment by dominik1996** [comment]
After shortly reviewing this issue I would suggest looking into the two-way-binding of zoom. Using [(zoom)] I can reproduce this behavior, using [zoom] not.

**Comment by stephanrauh** [comment]
Yes, it's definitely two-way binding. The problem is that each time I try to debug, the error uses all my available CPU. The only solution is to terminate the browser.

Removing the lines you've suggested kills two-way binding. :) Even worse, it kills the entire `(zoomChange)` event.

**Comment by stephanrauh** [comment]
@ddankwerth @cristianofromagio @dominik1996 Please run a test with version 8.0.0-beta.0. I believe I've solved the bug.

**Comment by ddankwerth** [comment]
Ive tried this and seems to work well , well done , many thanks

בתאריך יום א׳, 17 בינו׳ 2021, 23:41, מאת Stephan Rauh ‏<
notifications@github.com>:

**Comment by cristianofromagio** [comment]
Tested it and it solves the looping zoom bug for me. But it throws the `ExpressionChangedAfterItHasBeenCheckedError` when selecting one option from the radio list:
![image](https://user-images.githubusercontent.com/16294559/104923613-0bdfd500-597b-11eb-998b-64e5c6c0be03.png)

[Line 21 on `zoom.component.html`](https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/39779dbc1c5ca1e7e7d56f17af48e9c4a7b3bf38/src/app/extended-pdf-viewer/zoom/zoom.component.html#L21) is the binding to `currentZoomFactor` (which is updated by the `(currentZoomFactor)="updateZoomFactor($event)"` event binding in the component instance):
```html
        <div class="distance-top">Current zoom level: {{ currentZoomFactor | percent }}</div>
```

It is probably the situation where a child component update its parent component state after the change detection cycle has run.

We can test it by making the value update async on the [`updateZoomFactor` event handler](https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/39779dbc1c5ca1e7e7d56f17af48e9c4a7b3bf38/src/app/extended-pdf-viewer/zoom/zoom.component.ts#L63):

```typescript
  public updateZoomFactor(zoom: number): void {
    // this.currentZoomFactor = zoom; // current

    Promise.resolve().then(() => this.currentZoomFactor = zoom); // detect on next microtask
    // OR
    setTimeout(() => this.currentZoomFactor = zoom, 0); // detect on next macrotask
  }
```

**Comment by stephanrauh** [comment]
Ah, so that's why I've added a timeout in the original implementation. I hope re-introducing the timeout won't make the error appear again :) (but I don't think so, I've found and solved a couple of bugs which sent outdated zoom settings, so that was probably the root cause)

**Comment by stephanrauh** [comment]
@cristianofromagio Version 8.0.0-beta.1 fixes the `ExpressionChangedAfterItHasBeenCheckedError` without using a timeout. Can you test it again, please?

**Comment by stephanrauh** [comment]
I suppose I've successfully solved the bug. Don't hesitate to tell me if you still run into it.
