### ISSUE TITLE
[pageViewMode]="'simple'" not working (on lastest angular ?)

### ISSUE THREAD

**Issue by vic1707** [stephanrauh/ngx-extended-pdf-viewer#592]
**Describe the bug**
Can get `[pageViewMode]="'simple'"` to work.

Yesterday it was working perfectly but today i'm completly unable to get it working, i think it might be due to me updating angular or doing a npm i after updating all my packages...

so here is my package.json : 
```json
{
  "name": "new-nas-website",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.4",
    "@angular/common": "~11.0.4",
    "@angular/compiler": "~11.0.4",
    "@angular/core": "~11.0.4",
    "@angular/forms": "~11.0.4",
    "@angular/platform-browser": "~11.0.4",
    "@angular/platform-browser-dynamic": "~11.0.4",
    "@angular/router": "~11.0.4",
    "codelyzer": "^6.0.1",
    "ngx-extended-pdf-viewer": "^7.1.0",
    "ngx-toggle-switch": "^2.0.5",
    "rxjs": "~6.6.3",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.4",
    "@angular/cli": "^11.0.4",
    "@angular/compiler-cli": "~11.0.4",
    "@types/jasmine": "~3.6.2",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.14.13",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "4.0.2"
  }
}
```

**Version info**
- Version of ngx-extended-pdf-viewer : 7.1.0

**Desktop (please complete the following information):**
 -  Firefox Chrome

**To Reproduce**
Update angular ?

**Demo PDF file**
Every PDF file i tested, tried with : 
https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf

**Comment by stephanrauh** [comment]
Just ruling out the obvious: it's `single`,  not `simple` - although that's a good name, too! 👍 

`[pageViewMode]="'single'"`

**Comment by vic1707** [comment]
> Just ruling out the obvious: it's `single`, not `simple` - although that's a good name, too! 👍
> 
> `[pageViewMode]="'single'"`

I'm really wondering how i can feel more stupid XD
Strangly with the right spelling it works better 🤔
