### ISSUE TITLE
Zoom always goes to top of the previous page when 2 pages are on screen and the previous page is still visible

### ISSUE THREAD

**Issue by timothyBrake** [stephanrauh/ngx-extended-pdf-viewer#595]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). **No**
- Does the bug also happen on https://pdfviewer.net/simple? **Yes**
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template **You can clearly see the issue in https://pdfviewer.net/simple**

**Describe the bug**
When zooming in on a page where the previous page is still visible, the top of previous page is shown and zoomed in. I expect the zoom to keep the pages as is and just zoom in.

**Version info**
- 7.1.0

**Desktop (please complete the following information):**
 - Mac OSX Chrome
 
**Smartphone (please complete the following information):**

**To Reproduce**
https://pdfviewer.net/simple

If you really can't provide me a reproducer, please tell me how to reproduce the behaviour:
1. Scroll to second page so that the first page is still slightly visible but for the most part, the second page is visible. 
2. Click on 'Zoom'
3. See error as the to pof the first page is now visible instead of remaining on the second page and zooming in

**Demo PDF file**
https://pdfviewer.net/simple

**Screenshots**
See screencapture to explain the issue. Extract the attached zip file to look at the video explaining the issue
[Screen Recording 2020-12-17 at 12.25.27.mp4.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/5709026/Screen.Recording.2020-12-17.at.12.25.27.mp4.zip)

**Additional context**
See screencapture to explain the issue

Thanks for your excellent component,
Timothy

**Comment by stephanrauh** [comment]
Your bug description sounds exactly like #573. And I couldn't reproduce it at https://pdfviewer.net/simple. It's possible I've missed something, but let's start with the easy stuff. Which version of pdf.js are you using? It should be 2.6.418 (and you can see it in the console window when the PDF viewer is initialized).

My hope is you've simply run into a caching issue!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I haven't heard from you, and I still can't reproduce the bug, so I'd like to close it. If you can reproduce it with version 8.0.0, don't hesitate to tell me, so I can resume investigating the topic.

Best regards,
Stephan
