### ISSUE TITLE
(progess) : On firefox Attributes 'total' & 'percent' respectively 'undefinied' and 'NaN' until last call

### ISSUE THREAD

**Issue by vic1707** [stephanrauh/ngx-extended-pdf-viewer#597]
**Describe the bug**
On Firefox, I can't retreive the total number of bytes to load nor the percentage of completion of the download. Except on the las call of the function.

**Version info**
- last  : 7.2.0

**Desktop (please complete the following information):**
 - Firefox
 - Chrome and Safari work well.
 
**To Reproduce**
- Use the `(progress)` input for the viewer
- console.log the event produced

**Demo PDF file**
All PDFs I tested

**Screenshots**
Firefox : 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/28602203/102987504-b565af00-4512-11eb-9bb3-2d4c98f1cb9e.png">

Chrome  : 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/28602203/102987681-037ab280-4513-11eb-8e62-393d98d7edcc.png">

(which seems to call the function 2 times when the download is complete. Firefox seems to call it 1 time once complete, but maybe the other finished call is marked as `undefined`for the total and `NaN` for the percentage)

**Additional context**
Chrome works well, it's probably a compatibility issue, probably features not supported by Firefox.

**Comment by stephanrauh** [comment]
I've added the `(progress)` event to the demo on the showcase: https://pdfviewer.net/extended-pdf-viewer/pages-loaded

I still don't see a `NaN`. Which operating system are you using?

![image](https://user-images.githubusercontent.com/3045767/103384628-5d710e80-4af7-11eb-8f05-ea05018bdc9a.png)

Best regards + Happy New Year
Stephan

**Comment by vic1707** [comment]
I tried MacOS, Windows and Linux both brand new on firefox...

**Comment by vic1707** [comment]
Can it be the same problem than with ng2-pdf-viewer and my `Onerror` issue ? (can't try it now but will tommorow)

**Comment by vic1707** [comment]
Just tried accessing to the link and it works on my machine too, so the problem seems to be my site....

**Comment by stephanrauh** [comment]
@vic1707 Any news? Did you manage to narrow down the bug?

**Comment by vic1707** [comment]
Hello, unfortunatly no news here, only the fact that I wasn't able To find a single firefox that could work on my website...
Guess you have a line, a declaration or something that makes it work on your site that I missed...

Will look to the code from the showcase ASAP.

**Comment by stephanrauh** [comment]
Bonsoir Luc,

any progress? I've decided to close the bug for the moment. When you've managed to create a reproducer that works (or rather: fails) on my machine, too, I'll happily re-open it.

A la prochaine
Stephan

**Comment by vic1707** [comment]
For now not able to reproduce... And not working for no on my website. Hope i'll find why soon enough

**Comment by vic1707** [comment]
Currently redoing entirely my website.
Brand new project, brand new components, brand new computer and firefox etc...

Still the same error, can't understand why.
Did I missed something on the install process ? 
Installing it : 
![image](https://user-images.githubusercontent.com/28602203/108599327-ca36b580-7390-11eb-8979-f9cecd5c8696.png)

adding : 
```
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }
```
to `angular.json` at the two right places as you can see : 
![image](https://user-images.githubusercontent.com/28602203/108599070-644a2e00-7390-11eb-90c6-783204afd6b8.png)

adding the lib to the `app.module.ts` : 
![image](https://user-images.githubusercontent.com/28602203/108599274-8b086480-7390-11eb-9c53-6216c6cdb33c.png)

and finally use it inside the component : 
![image](https://user-images.githubusercontent.com/28602203/108599420-5648dd00-7391-11eb-8096-63daea704ed3.png)

Can you tell me that i did a mistake that could explain why i can't get the correct output for the onProgress funtion ?

**Comment by stephanrauh** [comment]
Everything looks fine to me. Some time ago, we observed that minification makes a difference. Can you add `[minifiedJSLibraries]="false"` and see what happens?

**Comment by vic1707** [comment]
I have a bad news and a bad news : 
BAD : not working at all with `[minifiedJSLibraries]="false"`

BUT ! 

Good : it works when the file is in the assets folder. 
When i use an src that is an url it's not working (even whent using `https://pdfviewer.net/assets/pdfs/The Public Domain - Enclosing the Commons of the Mind.pdf` and forcing CORS in order to display the file).

So i guess the problem is due to getting the file from elsewhere than  the local `assets` folder ?

**Comment by stephanrauh** [comment]
Oh, yes, that's possible. Maybe the server you're getting the PDF files doesn't offer all the features needed. Such as range requests or sending the size of the PDF file in the response header. Does that sound plausible?

**Comment by vic1707** [comment]
Like you I think the problem can be the server serving the pdf.

But i have to admit i have some doubts because mine, yours (hosting pdfviewer.net) and the one of ng2-pdf-viewer are unable to give the total size of the pdf while probably having different configuration  and even different webservers.

So who's ''''''''guilty'''''''' between the webserver, or the lib is a tought question. 

Mine is a selfhosted NGINX (using SWAG docker container from linuxserver), used as a reverse proxy. The pdf files, for NGINX are locales (it has direct access).
It will certainly be very useful to be able to set whatever settings we want to debug the issue ^^

How do you get the total size from à given pdf in the lib ?


P.S : Hope i don't sound like blaming the lib, which is obviously not the case given the incredible amount of work you put into it !

**Comment by stephanrauh** [comment]
Pas de problem - 1) I don't mind you blaming the lib, and 2) I know you're not blaming the lib! :)

**Comment by stephanrauh** [comment]
My server (or rather - the server I'm renting) is a simple Apache httpd server, with PHP support, but little else. I'm afraid their website is only in German language, but if you're interested, here it is: https://all-inkl.com/webhosting/privatplus/

**Comment by stephanrauh** [comment]
Maybe it's a god idea to locate the line where the event is emitted. Debugging this line should give you an idea where the information (or the missing information) stems from.

**Comment by vic1707** [comment]
I'll try to look at it tomorrow 😉

I think i'll look for the line in the lib and try several ideas to see if i can retrieve the pdf size without downloading it. 
If it's possible to get the total size without having to download every byte of the file we should be able to identify if it's server or lib related and even we should be able to at least find a workaround.

Still have some things to fix in my working environnement of the second version of the Website before looking for it ( things that were working fine for days that suddently stopped working with no reason whatsoever...)
+ i will probably open an issue because i'm having trouble using theelib Inside storybook ( i'll open it once this one is done 😉😅)

**Comment by vic1707** [comment]
Found it, or at list partially.
`curl -sI $URL | grep -i Content-Length` is returning the right file size (tested with one of my files and with yours).
So I think it's safe to says that it's the lib that isn't able to retrieve the file size.

**Comment by vic1707** [comment]
It seems to be a known issue : https://github.com/mozilla/pdf.js/issues/9103#issuecomment-363436612

**Comment by stephanrauh** [comment]
So the method `validateRangeRequestCapabilities()` of pdf.js is a good starting point for debugging. Maybe this function returns without setting the content length.

**Comment by vic1707** [comment]
i visited most of the issues related to this, it appears that it's known and that the header `Content-Length` isn't used due to unaccuracy in some cases... 
But what seems strange to me is that i saw a PR on november that was accepted and uses the header as a fallback.
I wanted to test it by going on `bleeding-edge` but as my issue states i'm unable :cry:

**Comment by vic1707** [comment]
It seems that the only difference between ngx-extended-pdf-viewer and ng2-pdf-viewer regarding the progress event is that ng2-pdf-viewer imports `PDFProgressData form 'pdfjs-dist'` contrary to ngx-extended-pdf-viewer which doesn't. 
I'll take a look at it to know if it's the cause of the problem.

**Comment by stephanrauh** [comment]
As far as I remember, that's an interface defined in a `*.d.ts` file. So I don't think that's the difference. But at least it is a difference! :)

**Comment by vic1707** [comment]
hello, 
don't know what changed but the progress event now works perfectly event with files hosted on a site rather than on local in the assets folder !

**Comment by stephanrauh** [comment]
As much as I hate bugs that simply go away - you never know when they pop up again! - I'm happy you've managed to solve this nasty bug!
