### ISSUE TITLE
Custom message for unverified signature

### ISSUE THREAD

**Issue by jlavric** [stephanrauh/ngx-extended-pdf-viewer#598]
Excelent library!!
I would like to have an option to translate message "This PDF contains digital signature, ...." to my language. I went through lang files but as it looks like this message is hardcoded. It is not a problem but just feature proposal :)

Thank you again for this viewer!!

**Comment by stephanrauh** [comment]
Good point. I'll have a look at it.

**Comment by stephanrauh** [comment]
The message can now be translated to every language supported by pdf.js. I've alread added translations for the few languages I speak (or at least know well enough to can guess if Google translate shows me nonsense or not).

I suppose your language is not in the list. Can you send me the translation? And while you're at it, can you translate the other five missing texts, too? You find the translation files here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/master/projects/ngx-extended-pdf-viewer/src/assets/additional-locale

**Comment by stephanrauh** [comment]
I've just published the new version of ngx-extended-pdf-viewer on npm.js. I'm still listening to this thread, so feel free to send me your translations in this ticket.

Best regards + happy New Year
Stephan

**Comment by jlavric** [comment]
Great, thank you. I have not tested this yet but I am sure that everything is ok. Here are the translations for Slovenina language (sl).
# Additional translations
find_ignore_accents=Ignoriraj znakovne dodatne, strešice in podobno
find_input_line_by_line=Iskalni pojmi, vsaka vrstica je svoj iskalni pojem
find_multiple_texts_label=Poišči vse iskalne pojme hkrati
find_individual_words_label=Poišči samostojne besede
find_fuzzy=Ohlapno iskanje
unverified_signature_warning=Dokument vsebuje digitalni podpis. PDF viewer ne more preveriti veljavnost podpisa. Prosimo prenesite dokument in veljavnost podpisa preverite v programu Acrobat Reader.

Have fun and normality in 2o21!!
Janez
