### ISSUE TITLE
Sidebar visible even when showSidebarButton is set to false

### ISSUE THREAD

**Issue by AlexandrosG** [stephanrauh/ngx-extended-pdf-viewer#6]
I'm using ngx-extended-pdf-viewer with almost all features disabled except zoom, pagination, download and print. 

When setting the `showSidebarButton` param to `false`, the sidebar still loads.

![image](https://user-images.githubusercontent.com/27071926/48623586-5d126980-e9aa-11e8-984d-d18d69eb6608.png)

Looking at the code, `sidebarViewOnLoad` is hardcoded to `1`. Shouldn't this option either be an input parameter or be set according to `showSidebarButton`?

**Comment by stephanrauh** [comment]
You're right. I've added both options: if the sidebar button is shown, you can configure the sidebar to be shown or hidden at load-time.

I've pushed an early sketch of the solution so you can review it. However, it doesn't seem to work yet. Currently, the sidebar is always hidden on my machine, no matter which value  `showSidebarOnLoad` has.

**Comment by AlexandrosG** [comment]
Thanks for looking into it so quickly.

I've done a bit of reading and it seems that there is a bug also on pdfjs' side regarding PDF files that have been configured to show the overview panel by default (through Acrobat I assume). 

I used this pdf files for testing: http://www.pdf995.com/samples/pdf.pdf
Perhaps you can give it a go and see if the overview panel stays open still?

**Comment by stephanrauh** [comment]
I'm afraid it doesn't make any difference which document I use. The problem I'm facing is that no matter which value I assign to `showSidebarOnLoad`, it's simply ignored. It seems that it's always shown by default, until the user clicks the "toggle sidebar" button. For some reason, this choice even survives full page reloads.

This behaviour may even be intended, but at least I'd like to understand how this works. At the moment, it looks a bit weird, verging on "buggy". :)

**Comment by AlexandrosG** [comment]
I had a look at the code and you've added quite a lot of custom code in the viewer.js which makes things quite complicated to debug.

Probably the problems start with the function webViewerLoad. Probably the way the config is handled doesn't allow you access to set or change params.

This needs quite a lot of looking into. The history also acts quite wonky in my use case. It just jumps pages left and right so I'd like to disable it. The option for that is showPreviousViewOnLoad but setting it to false doesn't seem to work
```
(<any>window).PDFViewerApplication.showPreviousViewOnLoad = false;
(<any>window).PDFViewerApplication.disableHistory = true;   
(<any>window).PDFViewerApplication.appConfig.showPreviousViewOnLoad = false;
(<any>window).PDFViewerApplication.appConfig.disableHistory = true;
```

**Comment by stephanrauh** [comment]
I'm afraid you're simply suffering from my code formatter. :( I've compiled a complete walk-through to the customizing. Each time Mozilla releases a new version of pdf.js, I have to go through this list, so I'm sure it's complete: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/how-to-build.md

These are the changes to `viewer.js`:

> 31. open ngx-extended-pdf-viewer/src/assets/viewer.js and replace "require('../build/pdf.js')" by "require('./pdf.js')"
> 32. In the same file: replace "value: 'compressed.tracemonkey-pldi-09.pdf'" by "value: ''"
> 33. In the same file, rougly line 259: replace the lines
>     if (document.readyState === 'interactive' || document.readyState === 'complete') {
>     webViewerLoad();
>     } else {
>     document.addEventListener('DOMContentLoaded', webViewerLoad, true);
>     }
> 
>     by
> 
>     window.webViewerLoad = webViewerLoad;
> 
> 34. In the same file: search for "for (var anyCaseLang in dict.locales) {" (roughly at line 12551). Replace the for loop by this version:
>     for (var anyCaseLang in dict.locales) {
>     const originalCase = anyCaseLang; // added line
>     anyCaseLang = anyCaseLang.toLowerCase();
>     if (anyCaseLang === lang) {
>     gL10nData = dict.locales[lang];
>     break;
>     } else if (anyCaseLang === defaultLocale) {
>     gL10nData = dict.locales[originalCase]; // modified line
>     }
>     }
> 
> 35. open ngx-extended-pdf-viewer/src/assets/pdf.js and remove these three lines (roughly at line 17698):
>     var fs = require('fs');
>     var http = require('http');
>     var https = require('https');
> 
>     (the next line, require('url'), does not cause problems. That's because the 'url' dependencies is available in web projects)
> 
> 36. In the same file: replace the line (roughly at line 16677)
>     var output = require('zlib').deflateSync(input, { level: 9 });
>     by
>     throw Error("zlib not available in the browser");
>

**Comment by stephanrauh** [comment]
![image](https://user-images.githubusercontent.com/3045767/48799870-7ef05100-ed08-11e8-8992-cc98f53ad702.png)

**Comment by stephanrauh** [comment]
![image](https://user-images.githubusercontent.com/3045767/48805598-0abda980-ed18-11e8-81d8-7834adc1eb4b.png)

**Comment by stephanrauh** [comment]
`disableHistory` + `showPreviousViewOnLoad` doesn't work because the viewer is in embeddable mode. At the moment, this doesn't make sense to me, but that's the implementation:

```javascript
if (!AppOptions.get('disableHistory') && !this.isViewerEmbedded) {
        // The browsing history is only enabled when the viewer is standalone,
        // i.e. not when it is embedded in a web page.
        let resetHistory = !AppOptions.get('showPreviousViewOnLoad');
        this.pdfHistory.initialize(pdfDocument.fingerprint, resetHistory);
       ...
}
```

**Comment by stephanrauh** [comment]
I give up. I'm sure there's a clean way to do it, but since I didn't find it after a couple of days, I added some more customization to the `viewer.js`.

As of version 0.9.8, the sidebar is never shown if the "toggle sidebar" button is hidden. If the "toggle sidebar" button is available, you can optionally show or hide the sidebar using the attribute `[showSidebarOnLoad]`. Legal values are `undefined`, `true`, and `false`.
