### ISSUE TITLE
Unable to figure out how to get localization working

### ISSUE THREAD

**Issue by Hime-svm** [stephanrauh/ngx-extended-pdf-viewer#60]
Hi
I'm using your package to visualize a base 64 pdf. First I had the same issue as [https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/52](url) so I added the script to the <head> section of my index.html.
In my page I have a language switcher and I can't figure out how to make the 2 work together. Can you please assist me?

`<ngx-extended-pdf-viewer *ngIf="pedigree" [base64Src]="pedigree" 
            [backgroundColor]="dadada"
            [useBrowserLocale]="false" [showZoomButtons]="true" [handTool]="true"
            [showPrintButton]="false" [showRotateButton]="false" [showPagingButtons]="false"
            [showDownloadButton]="false" [showSidebarButton]="false" [showFindButton]="false"
            [showOpenFileButton]="false" [showBookmarkButton]="false"
            [showSecondaryToolbarButton]="false" [zoom]="'page-fit'"> </ngx-extended-pdf-viewer>`

Index.html :
` <script type="application/l10n">
    {
      "default_locale":"nl",
      "locales":{
        "nl":{"previous":{"title":"Vorige pe...ld in de browser."}},
        "en":{"previous":{"title":"Previous... the browser."}}
      }
    }     
  </script>`

I'm using the TranslateModule, TranslateLoader and TranslateHttpLoader from ngx-translate. Is there a way to set the language to use?

Thanks in advance for any feedback!
Kind regards
Steffie

**Comment by stephanrauh** [comment]
As far as I can see, the challenge to is override the browser language setting.

**Comment by Hime-svm** [comment]
Hi 
sorry for my late reply.
I really don't want to change my visitors browser language when they visit my website. Isn't there another way?
If not then I will have to find another way to visualize my pdf documents.
Kind regards

**Comment by stephanrauh** [comment]
OK, got it.

BTW: Please apologize my slow answers... this is an after-work hobbyist project.

**Comment by stephanrauh** [comment]
I've just shipped version 0.9.31. This version adds an attribute called `language`. You can set it to a fully-qualified language code, such as `es-ES`, `es-AR`, or `de-DE`. 

Note that this option only works when the component is initially drawn. There's no live update without hiding the component for a second.

**Comment by Hime-svm** [comment]
hi Stephan
I wanted to thank you for your work!
Kind regards

**Comment by stephanrauh** [comment]
Hi Steffie,

that's very kind of you! Truth be told, these comments always are a huge boost to my motivation. That's just awesome. It really feels good to know my work helps other people!

Best regards,
Stephan

**Comment by Hime-svm** [comment]
I have one extra question, but It's not an issue with your package, but more a lack in knowledge on my side.
How do I redraw just your component? Because I don't want do do a full page refresh.

Thanks in advance!
Kind regards

**Comment by stephanrauh** [comment]
1. That's unexpected, but someone else has the same problem, so maybe something's wrong. See #84 
2. Use the `[height]` attribute. Percentages in CSS are always tricky, especially when it come to height. By default, ngx-extended-pdf-viewer uses 100% as default height. However, that often results in a height of zero pixels, so I've some extra code to ensure a minimum height of 100 pixels. This extra check only applies if the `[height]` attributes contains a percentage. If you set it manually to `[height]="20px"` or `[height]="5vh"`, the PDF viewer assumes you know what you're doing.
3. No idea. Googling taught me you can call `ngOnInit` or mark it for change detection. However, the idea of Angular is to never redraw a component manually. Angular does it when necessary. Also see https://stackoverflow.com/questions/47813927/how-to-refresh-a-component-in-angular.
