### ISSUE TITLE
Help: Use pdfjs directly in other components

### ISSUE THREAD

**Issue by jos1337** [stephanrauh/ngx-extended-pdf-viewer#606]
This is a request for help, not a bug.

I'm using ngx-extended-pdf-viewer in my app. That works.
Now I need to use pdf.js directly in another component. I access it by importing in from pdfjs-dist: 
import * as pdfjsLib from 'pdfjs-dist/build/pdf' - works as well.

Both Components work when they are opened for the first time but there is a version conflict between to workers - so the app needs to restart to be able to load another worker version.
I'm not able to import pdf.js that comes with the viewer directly. I tried several options, but haven't been able to make it work.

Is there a solution to this? What would be the right approach? 
Thank you very much.

**Comment by jos1337** [comment]
import * as pdfjsLib from "ngx-extended-pdf-viewer/assets/pdf-2.6.423.js";
pdfjsLib.GlobalWorkerOptions.workerSrc = './assets/pdf.worker-2.6.423.js';

leads to an error:
TypeError: Cannot read property 'constructor' of undefined
    at new WorkerTransport (pdf.js:3122)
    at pdf.js:1930

**Comment by stephanrauh** [comment]
You can load the worker using a `<script>` tag. ngx-extended-pdf-viewer loads pdf.js and viewer.js this way. In this case, you don't have to set the `workerSrc`. As far as I remember, the attribute is simply ignored.

A very simple approach is to add `pdf.worker.min.js` to the `scripts` section of your `angular.json`. 

The disadvantage of pre-loading the file is you sacrifice a lot of performance. But unless your files are huge, you won't notice.

An alternative is to copy pdf.worker.min.js from the node_modules/pdfjsdist folder to your assets folder and to set `pdfjsLib.GlobalWorkerOptions.workerSrc = './assets/pdf.worker-2.6.423.js';`. In this case, you don't need the import statement.

In any case, pdf.js runs a compatibility check. AFAIK this only check the major and minor version number. So you can use pdf.js 2.6 with pdf.worker.js 2.7.

**Comment by vlio20** [comment]
@stephanrauh thanks for your suggestion,  we already coping all the `node_modules/ngx-extended-pdf-viewer/assets` to the local assets as you suggest in your documentation and then loading it as follows:
```
import * as pdfjsLib from 'ngx-extended-pdf-viewer/assets/pdf-2.6.423.js';
pdfjsLib.GlobalWorkerOptions.workerSrc = './assets/pdf.worker-2.6.423.js';
```

the error that is thrown is:
```
TypeError: Cannot read property 'constructor' of undefined
```

**Comment by vlio20** [comment]
@stephanrauh I also tried to change manually the version of the pdf-worker.entry.js file to be the same as used in your lib. It resulted the same error as posted in the comment above. Any reason why you are not using the pdfjs-dist lib? it seems like the stable versions are delivered there.

**Comment by stephanrauh** [comment]
I'm not sure it's possible to use the import statement with pdf.js. I tried it with ng2-pdf-viewer these days and failed. I don't understand what's going on, but it seems `require()` works better. pdf.js hasn't been designed with the current TypeScript module system in mind.

**Comment by vlio20** [comment]
I also tried to user require and it didn't work for me, maybe you can show how are you did it?

**Comment by stephanrauh** [comment]
As for not using pdfjs-dist: well, my fork of pdf.js contains several dozen modifications. Mostly added features, but also a couple of bug fixes.

**Comment by stephanrauh** [comment]
ngx-extended-pdf-viewer does not benefit from the `import` statement. Nor does is benefit from the `require()` statement.

However, if you need it for some other reason, here's how to do it: https://github.com/VadimDez/ng2-pdf-viewer/blob/7031a55d57f9f16c5111d72784fbb26b0cd0bb24/src/app/pdf-viewer/pdf-viewer.component.ts#L37

**Comment by vlio20** [comment]
@stephanrauh were you able to load the worker in you library?

**Comment by jos1337** [comment]
@stephanrauh 
Thank you! I will try to explain the problem:
I want to use pdf.js outside of your viewer in my app. Since I'm not able to mix different versions I need to use the one that comes with your library.

I can require it but I'm not able to load the worker with 

`let PDFJS: any;
PDFJS = require('ngx-extended-pdf-viewer/assets/pdf-2.6.423.js');
`
throws
`Error: No "GlobalWorkerOptions.workerSrc" specified.
`
which is expected.

Now I try to load the worker:
`(PDFJS as any).GlobalWorkerOptions.workerSrc = "./assets/pdf.worker-2.6.423.js";`
That throws 
`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'constructor' of undefined
`

With pdfjs-dist this works, the 2nd error does happen with pdf.worker-2.6.423.js that comes with your viewer.

**Comment by stephanrauh** [comment]
I see. I don't know what pdfjs-dist does differently - maybe it adds several `export`  statements. I'm simply using pdf.js without any module system. It pollutes the global window namespace, which is nasty and annoying, but it works well enough.

So try to replace your `import` or `require` with a simple `<script src="/assets/pdf-2.6.423.js">`. After that, you've got the global variable `PDFViewerApplication` (and several others). ngx-extended-pdf-viewer basically uses this global variable to perform its magic.

**Comment by jos1337** [comment]
I tried it with a script tag. Unfortunately that doesn't change anything.

I also tried something else that is kind of interesting:
This time I did remove all additional scripts.
I load an empty app component that has a ngx-extended-pdf-viewer in a *ngIf div. I use the console to check for the global pdfjsLib. It is not defined. After the viewer has been loaded it is defined.
Now I try to use the global pdf.js
`pdfjsLib.getDocument('./assets/sample.PDF')
`

This throws the same constructor Error:
<img width="583" alt="Bildschirmfoto 2021-01-02 um 23 19 07" src="https://user-images.githubusercontent.com/26776579/103467657-812f9100-4d51-11eb-863d-e489cb35d3dc.png">

Could it be that any of your changes is causing an error in getDocument?

**Comment by stephanrauh** [comment]
Can you add the attribute `minifiedJSLibraries="false"`, please? I've tried to look up the line number of the stack trace, but that's next to impossible with minified code.

It seems there's an object missing. If you're importing pdf.js from ngx-extended-pdf-viewer, that's not surprising. I didn't care about the export statements (yet), so I expect Webpack to remove some of the code you need.

BTW, another approach might be to use ng2-pdf-viewer. It doesn't pollute the window name space, so it might be possible to run it along my libary without reloading the page.

In my showcase, I use a radical approach to switch between ng2-pdf-viewer and ngx-extended-pdf-viewer: Instead of using Angular routing, I reload the page. Not a great solution, but it works.

**Comment by jos1337** [comment]
Thank you
<img width="570" alt="Bildschirmfoto 2021-01-03 um 12 44 39" src="https://user-images.githubusercontent.com/26776579/103477687-7d3b5780-4dc1-11eb-8b5a-a5e1b1c60467.png">

**Comment by stephanrauh** [comment]
It seems you've run into one of the improvements by ngx-extended-pdf-viewer:
![image](https://user-images.githubusercontent.com/3045767/103478800-6c8edf80-4dc9-11eb-9081-b187a28d05a1.png)

ngx-extended-pdf-viewer calls `getDocument()` with a JSON parameter. The error message means that the JSON parameter is missing the cmaps field. By default, it's a function, but you can also make it a string - something like `"./assets/cmaps/"`. By default, this object is passed to `getDocument()`:

![image](https://user-images.githubusercontent.com/3045767/103479102-98ab6000-4dcb-11eb-9b7f-acb1dfba3088.png)

**Comment by vlio20** [comment]
@stephanrauh is there anything we can do on our side to prevent this error?

**Comment by stephanrauh** [comment]
Yes, you can call `getDocument({url:'./assets/sample.PDF', cMapUrl: '/assets/cmaps'})` instead of calling `getDocument('./assets/sample.PDF')`.

**Comment by vlio20** [comment]
instead of url can I pass a base64 string? 
and what is a cMapUrl?

**Comment by jos1337** [comment]
looks like those cmaps are included with the package and copied over to the assets folder.
getDocument({url:'./assets/sample.PDF', cMapUrl: '/assets/cmaps'}) is working

**Comment by stephanrauh** [comment]
Yes, that's what I tried to say. :)

The cMaps file are support for several character sets in Asia. It's an annoying bug that you have to define the path. Most of the time you don't need the files. I'm going to fix this bug soon.

**Comment by stephanrauh** [comment]
BTW, it's also possible to pass a base64 string.

**Comment by stephanrauh** [comment]
@jos1337 @vlio20 What's the current state of the art? I'm under the impression you've managed to solve the issue. Is this correct? Can I close the ticket?

**Comment by jos1337** [comment]
Yes, thank you for your support!
