### ISSUE TITLE
Throws Exceptions When using SSR

### ISSUE THREAD

**Issue by elucidsoft** [stephanrauh/ngx-extended-pdf-viewer#609]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

**Describe the bug**
Throws exception on Server if your using SSR.

**Version info**
- 7.3.1

**Desktop (please complete the following information):**
 - Chrome
 
**Smartphone (please complete the following information):**

**To Reproduce**
Setup an angular SSR project, add module...Observe server logs, you will see where its looking for navigator which is undefined. If you stub this out, it will look for window. If you stub that out, it will look for document.  If you stub that out, it will look for Blob, its never ending and not a good solution.

Should defer all loading using isPlatformBrowser as it's not important nor necessary to load when on Server Side.  My suggestion is to simply block all execution unless isPlatformBrowser is true.  It works perfectly fine once the SSR transition to client is completed if you can get it past the error, but can hang things up as it constantly errors SSR preventing the page from rendering.

**Demo PDF file**
Doesn't matter, its Angular related...

**Comment by stephanrauh** [comment]
Would you mind to send me a reproducer? I know creating a SSR project is easy for you, but it's difficult for me. Until now I've never had the privilege to use server side rendering. I'm using a cheap server for my leisure-time projects, so there's no SSR, and it hasn't been a topic at work yet. So I need to learn everything from scratch.

That said, thanks for your analysis. You make it sound easy. I'm positive the `isPlatformBrowser` approach works.

**Comment by stephanrauh** [comment]
Talking of which... I wonder if you can even build a workaround yourself. Wrap `<ngx-extended-pdf-viewer>` in a custom component, something like `<ssr-aware-pdf-viewer>`. Guard the `<ngx-extended-pdf-viewer>` tag with an `*ngIf` switch. Something along these lines:

```html
<ngx-extended-pdf-viewer *ngIf="isPlatformBrowser" src="...">
```

Did you try this already? Does it work?

**Comment by stephanrauh** [comment]
@elucidsoft I've started to dig into the topic. I've got an idea how to solve it, but it doesn't work yet.

I've seen the error messages you're mentioning, but they're compile-time errors. How does checking `isPlatformBrowser` solve such a compile-time error? I feel like I've missing something... :)

**Comment by stephanrauh** [comment]
@elucidsoft I'm not sure you're still watching this issue, but if you do, would you mind to test version 8.0.0-beta.0? It supports server-side rendering. There's also a demo at https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue609. 

At the moment, the bottom line is to replace `NgxExtendedPdfViewerModule` by `NgxExtendedPdfViewerServerModule` on the server side. Maybe we can even get rid of this and always use `NgxExtendedPdfViewerModule`.

**Comment by elucidsoft** [comment]
Thank you, I pulled it out of my project since I'm on tight deadline. But when I get a chance to give it a go I'll let you know!!

**Comment by stephanrauh** [comment]
Let's close the ticket. Server side rendering works in my demo project, so chances are it also works in the wild.

**Comment by YurchenkoAndrew** [comment]
Hello. Came across this page while looking for a solution for the same problem.
My Angular application uses SSR. And I get errors like:
Translation for the key #thumbs is missing.
And so, in a loop for all translation lines.
The error is displayed in the Chrome browser console.
Angular version: 14.2.12
![Снимок экрана 2022-12-02 043842](https://user-images.githubusercontent.com/19759393/205174029-406d0e4b-9ab1-47ba-9019-945c3a8d33c2.png)

**Comment by stephanrauh** [comment]
@YurchenkoAndrew Which version of the library are you using? If you're using version 15.0.12, please update to 15.1.0. That should fix the problem.

**Comment by YurchenkoAndrew** [comment]
Thank you very much for your help.I'll try later and post the results.

**Comment by YurchenkoAndrew** [comment]
> @YurchenkoAndrew Which version of the library are you using? If you're using version 15.0.12, please update to 15.1.0. That should fix the problem.

Good day.
Updated version to "ngx-extended-pdf-viewer": "^15.1.0"
The main line of errors is gone, but a few remain.
I will give them in the attached screenshot file below.
![Снимок экрана 2022-12-03 034713](https://user-images.githubusercontent.com/19759393/205396254-65bcacba-82e3-46d9-9ebb-8c2d4ab42137.png)

**Comment by stephanrauh** [comment]
That's great news. I hope I can fix the remaining messages soon. Basically, they show that I'm behind schedule. I haven't finished updating to pdf.js 3.0 yet, but in the meantime, pdf.js 3.1 has been released. The main feature of the new versions is the editor, which is reflected by the error messages.

**Comment by stephanrauh** [comment]
BTW, you're using the "bleeding edge" branch of the PDF viewer? I appreciate that, because it means I get your bug reports early, but your production code should use the default branch. Unless you know what you're doing, that is. In your case, it doesn't make much of a difference because I want to upgrade to pdf.js 3.0 (default branch) / pdf.js 3.1 (bleeding edge branch) ASAP.

**Comment by exavior75** [comment]
In 15.2.1 you assign window.print which breaks SSR at compile (because no browser exists and so window is not defined). If I get around to it I might send in a pull request. It's a 1-line fix. I'd probably change it to console.log or maybe window ? window.print : console.log
