### ISSUE TITLE
Ability to create snip on page and convert it to base64image

### ISSUE THREAD

**Issue by guptarenu240489** [stephanrauh/ngx-extended-pdf-viewer#613]
Rather than converting the whole page into the image, we should be able to create a snip on the page and convert it to a base64 image.

**Comment by stephanrauh** [comment]
I'm afraid I can't implement that. The library uses pdf.js as a base library, and pdf.js always delivers entire pages as images.

In theory, I could implement the snip functionality after rendering the image. But that's something you can implement just as well. There's no point in adding this functionality to the library.

However, it might be interesting to implement the snip functionality outside the library and publish the algorithm in the showcase.

**Comment by stephanrauh** [comment]
Do you need my help to implement the crop function? And would you like to contribute a demo to the showcase?

Here are a couple of pointers to read. I've tried none of them, but at first glance, they look promising:

- https://foliotek.github.io/Croppie/
- https://fengyuanchen.github.io/cropperjs/
- https://stackoverflow.com/questions/53810434/crop-the-image-using-javascript (the do-it-yourself solution showing which is simple enough to give it a try)

**Comment by guptarenu240489** [comment]
@stephanrauh Thanks a lot for your prompt response & suggestions and apologies for my delayed response.
However, I tried implementing snip via ngx-image-cropper(https://www.npmjs.com/package/ngx-image-cropper).
But the experience is not very smooth as initially the page is loaded in pdf-viewer then to create snip, I send the base64image of that page into ngx-image-cropper. So on UI, I see that page in pdf-viewer and to crop it(1 in image), and an image comes as an overlay(2 in image). Then I crop it and send it across.
 
![image](https://user-images.githubusercontent.com/54392160/104090361-44592200-529c-11eb-927c-30452a3792d3.png)

Any help foe a better solution would be much appreciated. Thanks in advance

**Comment by stephanrauh** [comment]
OK, got it. I didn't think about how to implement a decent UI.

**Comment by guptarenu240489** [comment]
Thanks in advance. Already excited about implementation.

**Comment by stephanrauh** [comment]
I'm drowning in a flood of new tickets, so it doesn't seem likely I'll ever be able to implement this feature. Closing this ticket reluctantly.
