### ISSUE TITLE
Height property doesn't do anything

### ISSUE THREAD

**Issue by Stromwerk** [stephanrauh/ngx-extended-pdf-viewer#62]
I have tried using the `height` property to set a specific height in pixels for the pdf viewer, however it doesn't appear to be working, the viewer is still as high as the viewport allows. You can look at the [repo](https://github.com/Stromwerk/pdf-viewer-reproducer) - I have updated it accordingly.

**Comment by stephanrauh** [comment]
That's a follow-up of #55. Thanks for reporting!

**Comment by stephanrauh** [comment]
Such an evasive error! However, I believe I've successfully solved it by now. I've shipped the bugfix with version 0.9.23.

Like always, I'd appreciate you to test the bug and report back.

Thanks in advance,
Stephan

**Comment by Stromwerk** [comment]
Yes, it's working properly after I updated to 0.9.23
