### ISSUE TITLE
Missing translation keys

### ISSUE THREAD

**Issue by dominik1996** [stephanrauh/ngx-extended-pdf-viewer#620]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? No.
- Does the bug also happen on https://pdfviewer.net/simple? Yes using pdf.js 2.6, language = de.

**Describe the bug**
Some language files are missing translations. It seems like these translations are missing in every language except en-US. Just open any file in the pdf-viewer ([PDF-Viewer Internationalization](https://pdfviewer.net/extended-pdf-viewer/i18n)) and open the browser console. The console will show missing translation keys:

`
Translation for the key #layers is missing.
#layers is undefined.
Translation for the key #layers_label is missing.
#layers_label is undefined.
Translation for the key #toggle_sidebar_notification2 is missing.
`

**Version info**
- Version of ngx-extended-pdf-viewer: 7.3.1 and 7.3.2

**Desktop (please complete the following information):**
 - Browser: Firefox, Opera

**To Reproduce**
Changing the language using [PDF-Viewer Internationalization](https://pdfviewer.net/extended-pdf-viewer/i18n) will reproduce it using 7.3.1 and pdf.js 2.6.

**Additional context**
It looks like pdf.js 2.7 is not missing these translations (sadly my project can't use this version).

**Comment by stephanrauh** [comment]
The bug is easily fixed for the German language, but it affects every language. So I'm going to write a little script to add the missing keys to every language file.

Just out of curiosity: what stops you from using pdf.js 2.7?

**Comment by dominik1996** [comment]
Thanks for looking into it! We are only using stable versions of releases and I am given to understand that 2.7 isn't marked stable yet?!

**Comment by stephanrauh** [comment]
Oh, yes, you're right. I wouldn't recommend using the "bleeding edge" version in production. It's ok to use it for tests, or for less important applications, but if you want to play it safe, better stick with the default version. For two reasons: first, it's a developer version, not an official version released by Mozilla. Second, I maintain my own fork of pdf.js. Recently, pdf.js added many changes that are surprisingly difficult to merge. So it's a good idea to wait a couple of days until I've found all the bugs I've introduced when merging a plethora of changes in a hurry. :(

That said, the pdf.js have a great test coverage and manage to keep up an awesome code quality. Every developer version of pdf.js I've tried worked fine. So every bug you find is mine. :)

**Comment by stephanrauh** [comment]
The bug fix has landed with version 8.0.0-beta.2. I've also copied some English texts to the translation files. That's wrong in that it's not a proper translation, but these texts usually are the default value (so they are shown anyways), and I don't see any point in showing you warnings you can't easily fix.
