### ISSUE TITLE
Download Button on PDFs with a Blob or Base64 string as source does not work on Chrome on iOS

### ISSUE THREAD

**Issue by mathonto** [stephanrauh/ngx-extended-pdf-viewer#629]
**Describe the bug**
When using a Blob or Base64 encoded string as source, the download button on iOS using Chrome does nothing.

**Version info**
- Every version

**Smartphone (please complete the following information):**
 - Device: tested on multiple iOS devices with the latest iOS version (iOS 14.x)

**To Reproduce**
Can be reproduced on https://pdfviewer.net/extended-pdf-viewer/simple within the "Blob" and "Base64" demo projects. Download button does nothing there as well using Chrome on iOS.

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to 'https://pdfviewer.net/extended-pdf-viewer/simple' using an iOS device with Chrome
2. Click on 'Demos -> BLOBs'
3. Click on the "Save" icon 
4. See nothing happens :( 

**Demo PDF file**
Happens with every BLOB or Base64 encoded PDF as source

**Comment by stephanrauh** [comment]
This happens on my iPad, too (or rather, it doesn't happen). But what do you expect to happen? The other browsers open the PDF file in something resembling full-screen mode. Is that the disired behavior?

**Comment by mathonto** [comment]
Thanks for your quick reply, much appreciated! I would expect to either (i) open the built-in PDF displayer which then allows the download via the share button (as in Safari), i.e. "Save to Files App", (ii) directly start a download, or (iii) showing the "Open In" dialog at the bottom that then leads directly to the Files App again.

**Comment by stephanrauh** [comment]
I've started to investigate the topic. It's really weird. First, the feature works on https://mozilla.github.io/pdf.js/web/viewer.html. Second, I don't see any exception yet.

It seems there must be a difference between https://github.com/mozilla/pdf.js/blob/master/web/download_manager.js and https://github.com/stephanrauh/pdf.js/blob/2.7/web/download_manager.js, but I haven't found it yet.

**Comment by mathonto** [comment]
It seems to happen only with Base64/Blob file types, not sure what the filetype of the example in https://mozilla.github.io/pdf.js/web/viewer.html is

**Comment by stephanrauh** [comment]
You're right, it's a bug that happens only with Base64 files and Blobs. It's a side effect of https://github.com/mozilla/pdf.js/pull/8081.

**Comment by stephanrauh** [comment]
After several hours of debugging (thanks for the nice riddle! I always appreciate a good challenge!), I've come up with a solution that's basically an antidote of mozilla/pdf.js#8081. According to the description of the pull request, the solution is be unreliable. Sometimes it works, sometimes it doesn't. But it's an improvement because my bug fix is only used in situations which used to fail 100% of the time. Plus, it works on my iPad. What can go wrong after such an exhaustive series of tests? :)

Jokes aside: would you mind to run your own tests and tell me how it went? The bugfix is going to land with version 9.0.0-alpha.1.

**Comment by stephanrauh** [comment]
The bugfix has just landed with version 9.0.0-alpha.1.
