### ISSUE TITLE
[printing] Blank pages at the top document

### ISSUE THREAD

**Issue by pisipisi** [stephanrauh/ngx-extended-pdf-viewer#63]
When I load new document, hit print, then load another document, hit print, it adds an extra blank page at the top of print windows. If I continue open new document, it will add up blank pages. But if I reload the whole site, problem starts from the begin. Any body facing same problem I had?

**Comment by stephanrauh** [comment]
I couldn't reproduce this behaviour. Maybe I missed something. Dear community, what about you? If anybody's run into the same problem, please tell us!

**Comment by pisipisi** [comment]
I think the reader doesn't clean up properly on ngOnDestroy , I tried not to print and open different pdf, then print, the blank page still add up.

**Comment by stephanrauh** [comment]
Interesting. Maybe you can send me a reproducer? I.e. minimal but complete program showing the error that runs out of the box without configuration?

**Comment by stephanrauh** [comment]
Maybe - just maybe - version 0.9.34 solved the problem. For some reason, empty print containers piled up when navigating to another document. I've just fixed this bug.

**Comment by stephanrauh** [comment]
@pisipisi I haven't heard from you for a while. Are you still using my library, and if so, are you still suffering from this bug?

I'll close the ticket for the moment. It's almost impossible to fix a bug I can't reproduce.

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, brace yourself for breaking changes, especially if you've implemented a workaround. But I expect the update to solve more bugs than it causes.
