### ISSUE TITLE
Pdf file is not loading in Android

### ISSUE THREAD

**Issue by sattasundar** [stephanrauh/ngx-extended-pdf-viewer#631]
Not able to load pdf file in android/iOS device.

**Comment by stephanrauh** [comment]
Well, I'm able to load PDF files:

![image](https://user-images.githubusercontent.com/3045767/106313687-e0a59180-6268-11eb-9b1a-4fc912132fbe.png)

**Comment by stephanrauh** [comment]
I suggest you clone the [showcase](https://github.com/stephanrauh/extended-pdf-viewer-showcase) or the [issue reproducer template](https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template) and find out the difference between these projects and your project.

**Comment by sattasundar** [comment]
It's working in browser, but not working in mobile application.

**Comment by stephanrauh** [comment]
Would you mind to add some detail? I've sent you a photography of the showcase running on my iPad. So, obviously the PDF viewer does work on mobile devices. I don't think it only runs on my mobile devices.

If you need my help, I need a reproducer (i.e. a complete, running application showing the bug, and that doesn't require any installation beyond `npm install` and `ng s -o`) and a description how to reproduce the bug with your reproducer.

Best regards,
Stephan

**Comment by sattasundar** [comment]
Actually I am fetching blob data from API and bind with the ngx-extended-pdf-viewer src. While I am running my app in browser it's working. But while I am generating apk and running in device it's not loading the PDF.

Note: - Implemented in Ionic-Angular project.

**Comment by stephanrauh** [comment]
OK, we're getting closer. :) I'm not sure I can help you: I don't own an Android Device, and for some reason, my MacBook refuses to connect to my iPad.

But I guess you can debug the error message yourself. Do you have a remote debugger for your Android device? If not, you can monkey-patch `console.log`, `console.error`, and so on, and display the messages in your application.

If you send me a stacktrace, please make sure to add the attribute `minifiedJSLibraries="false"`. That make debugging a lot easier. And please tell me which version number of Ionic, of Angular, and of ngx-extended-pdf-viewer you're using.
