### ISSUE TITLE
Any way to set withCredentials without also using Authorization header? 

### ISSUE THREAD

**Issue by marcorinck** [stephanrauh/ngx-extended-pdf-viewer#635]
**Is your feature request related to a problem? Please describe.**
I'm currently trying out ngx-extended-pdf-viewer and want to display PDF files that need to be loaded from a different origin than the angular application (via CORS). Authorization on the PDF server is using cookies, so the "withCredential" attribute needs to be set on the http request. Without it, no cookie will be transmitted by the browser. 
Currently, the only way I can do this, is to hijack the authorization parameter, which is not only setting the "Authorization" http header but also the withCredentials attribute. Unfortunately this backend is treating requests different when the authorization header is set, so currently the requests fail when Authorization is set to some random (static) string, even when the cookie is transmitted.

**Describe the solution you'd like**
I would like to be able to set the withCredential attribute on the http request without setting the "Authorization" http header.

**Describe alternatives you've considered**
I could download the blob manually but I would prefer not to do that to minimize Javascript memory usage. I also tried to use a HttpInterceptor which alters every http request on the angular HttpClientService to always set this attribute. But the requests made by this library (when using the [src] attribute) don't seem to use the HttpClientService as the interceptor is not called for those requests. 

**Additional context**
Thank you @stephanrauh Awesome project! 👍

**Comment by stephanrauh** [comment]
Hi Marco, nice to meet you again!

Your request sounds sensible, but I'm afraid it requires some investigation. Maybe you can have a look at https://github.com/mozilla/pdf.js/blob/e16c99fc020903d705ed7e81cbf3b83cf84e139b/web/app.js#L880. I suppose it's the second parameter you're looking for. So I'd just have to expose it to the API of ngx-extended-pdf-viewer. What's your opinion, does this look promising?

CU
Stephan

**Comment by marcorinck** [comment]
We seem to stumble upon each other quite often. Nice!

Yes, the linked code seems to be the right place. withCredentials isn't in the given examples of the args object, but from context withCredentials should be one its properties.

Thanks for considering it!

**Comment by stephanrauh** [comment]
I just wanted to implement your feature... only to see I've already done that. You know your library is feature-rich when you start forgetting the features you've already implemented! :)

These two attributes are what you're looking for:
- [authorization] This attribute is designed to activate server-side authorization. If this attribute has a value, the attribute withCredentials is set to true. If you're using Keycloak, you can pass the bearer token with this attribute. Note that you have to add the prefix "Bearer: " (with a capital B and a trailing space). To support other authorization servers, you can also set additional headers using the attribute [httpHeaders].
- [httpHeaders] This is the attribute covering all the corner-cases `[authorization]` doesn't cover.

**Comment by stephanrauh** [comment]
Even better, I've also dedicated a page on the showcase to Keycloak: https://pdfviewer.net/extended-pdf-viewer/keycloak

Here's the demo repository demonstrating the feature: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/oauth2-ngx-extended-pdf-viewer-test

Don't hesitate to tell me if anything misses!

A tout a l'heur
Stephan

**Comment by marcorinck** [comment]
Hmm, maybe there is a kind of misunderstanding. 

Yes, I know that there is the authorization attribute. Everything one puts in there gets sent with requests as the Authorization http header. And additionally it sets withCredentials option on the http request to "true". Unfortunately, I can't send any authorization header, as the backend handles those requests differently. I only want to set the "withCredentials" attribute on the http request to true, so that the browser will transmit any cookies together with the request. 

Please note that "withCredential" is NOT a http header. Its an [optional attribute on the http request object ](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) in the browser. So the other option you mentioned (httpHeaders) is not viable for this as I don't want to set any http header manually, but convince the browser that he is allowed to transfer any cookies to the CORS domain. 

Currently I can achieve this only when I make the request myself and then store the resulting blob in a local variable of my component and set the src property of ngx-extended-pdf-viewer to this variable, like so:

````typescript
srcBlob$: Observable<Blob | undefined> = this.httpClient.get(url, {
  withCredentials: true,
  responseType: "blob"
});
````

But I want to get rid of the local copy because of memory consumption. 

So I think, your first suggestion to make the args object available for pdfviewer consumers seems to be a reasonable idea.

**Comment by stephanrauh** [comment]
Oops, sorry. You're right, I can't read. :) Sorry about that!

There's another solution without modifying the library. The type definition of `[src]` isn't complete. You can also pass this JSON object:
```
[src]="{url: 'https://example.com/some.pdf', withCredentials: true"}
```

I've scanned the API of pdf.js for useful options. There are several options, but they aren't useful enough to justify a dedicated attribute. So I'd be happy if simply passing a JSON attribute does the trick.

A la prochaine
Stephan

**Comment by mlakhara** [comment]
@stephanrauh When using this option by settings the src input to an object with url and withCredentials property true, the options are still not passed to PdfJs's getDocument method as in app.js's open method for PdfJs a new parameter object is being created with takes only the url from src (if src is an object), here, withCredentials need to be passed in args object (2nd argument of open method)

**Comment by mlakhara** [comment]
I can add an input [withCredentials] and supporting code to pass it downstream of pdf js. Let me know if a pull request with those changes can be merged. Are there any other things to take care of (like unit tests), before contributing the fix ?

**Comment by stephanrauh** [comment]
Pull requests are always welcome! You don't have to write a test, but if you add an attribute, it would be nice to update the documentation (https://github.com/stephanrauh/extended-pdf-viewer-showcase).

Thanks in advance (and sorry for forgetting to answer you last week)
Stephan

**Comment by stephanrauh** [comment]
@mlakhara If you're preparing your pull request, maybe this code snippets helps you. It's part of `NgxExtendedPdfViewerComponent.openPdf()`:

```typescript
        if (this.authorization) {
          options.withCredentials = true;
          if (options.httpHeaders) {
            if (!options.httpHeaders.Authorization) {
              options.httpHeaders.Authorization = this.authorization;
            }
          } else {
            options.httpHeaders = {
              Authorization: this.authorization,
            };
          }
```

**Comment by mlakhara** [comment]
@stephanrauh I am trying to test the pull request and another issue that I faced in the showcase project. I have executed the steps provided to build the ngx-extended-pdf-viewer and extended-pdf-viewer-showcase projects. Used the local built ngx-extended-pdf-viewer dist in extended-pdf-viewer-showcase. However, the styles from theme (light-theme by default) don't seem to be applied on the ngx-extended-pdf-viewer components. I have checked that they are being added as <style> tag , however, they are not being applied to them. I also tried changing encapsulation for ngx-extended-pdf-viewer component to None, however it has no effect.

**Comment by stephanrauh** [comment]
That's weird. Probably something went wrong with the setup of your projects. But I can't even guess what that might be. I suggest you submit the pull request nonetheless. I don't think your PR modifies the stylesheet, and even if it does, you've warned me, so I know what to look for when running my tests.

**Comment by guppifisch** [comment]
Is there any progress on this issue? I have the same CORS problem.

**Comment by stephanrauh** [comment]
No, I'm afraid there's no progress. At the moment, I've got a hard time catching up. The community has begin to open issues faster than I can solve them!

But that's your opportunity: you can contribute a pull request. I'm sure it's easy to solve the problem, it's just not easy for me because I have to install and configure a lot of infrastructure first. If you're interested, I'm ready to help you!

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I'm drowning in a flood of new tickets. Pull requests are still welcome.
