### ISSUE TITLE
Need to show one page at the time

### ISSUE THREAD

**Issue by Vigneshjana** [stephanrauh/ngx-extended-pdf-viewer#64]
Need to show one page at the time after clicking next button i need to show the another page is it possible?
and also i need to use hotkeys for page next,page down,zoom in,zoom out

**Comment by stephanrauh** [comment]
That's two different topics. Let me copy the "hotkeys" idea to another ticket.

**Comment by stephanrauh** [comment]
What does "one page at a time" mean? Ideas:

- the user must not scroll
- the PDF viewer must ensure that there's an entire page visible, and that no bit of the adjacent pages is shown.

Does this match your intent?

That doesn't sound impossible, but it's not what I had in mind when I wrote the library. Nonetheless, it may make sense for some use-cases.

**Comment by Vigneshjana** [comment]
Thanks for the immediate response, the mentioned two functionalities is exactly what i am looking for and i am expecting that in your library soon.
its very much useful to implement in my project.

**Comment by Vigneshjana** [comment]
@stephanrauh  Is it possible to reorder the page from the Thumbnail view

**Comment by Vigneshjana** [comment]
> What does "one page at a time" mean? Ideas:
> 
> * the user must not scroll
> * the PDF viewer must ensure that there's an entire page visible, and that no bit of the adjacent pages is shown.
> 
> Does this match your intent?
> 
> That doesn't sound impossible, but it's not what I had in mind when I wrote the library. Nonetheless, it may make sense for some use-cases.

@stephanrauh Any update from the above point..

**Comment by stephanrauh** [comment]
@Vigneshjana I've been busy solving several other tickets. At the moment, I still don't know how to prevent scrolling, but I didn't investigate the topic thoroughly yet.

As for your second question: What do you mean by "reordering"?

**Comment by Vigneshjana** [comment]
@stephanrauh Ok fine..
No need check for the Reordering question.. i deleted it

**Comment by Vigneshjana** [comment]
@stephanrauh Ok fine...
No need to check for the Reordering question..i deleted it

**Comment by stephanrauh** [comment]
The extended PDF viewer is not a good tool to display a single page. Most buttons are useless if there's only one page. For example, you don't need the toolbar.

I suggest you have a look at how to implement it with HTML and JavaScript. There's an example at the Mozilla repository, so I assume that'll be easy: https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.html
