### ISSUE TITLE
Annotation Support

### ISSUE THREAD

**Issue by beeing** [stephanrauh/ngx-extended-pdf-viewer#647]
Hi, thanks for putting a PDF viewer with Angular.

I'm interested to use your component as a way for user to review, annotate and sign the PDF document.

Fortunately, there is a library that is built on top of pdf.js - https://github.com/highkite/pdfAnnotate

Will be great if `ngx-extended-pdf-viewer` can be integrated optionally with `pdfAnnotate`

Thanks in advance.

**Comment by stephanrauh** [comment]
Looks like an interesting side-project. Maybe it's not even difficult - the demo https://github.com/highkite/pdfAnnotate/blob/master/examples/pdfjsExample.html doesn't look that complicated.

What's a bit worrysome is that the library doesn't seem to be regularly maintained, and it's not on npm.

**Comment by beeing** [comment]
It is in npm but as a different name - https://www.npmjs.com/package/annotpdf

However, agree that this library is not actively maintained.

Also, there's a little note on how to use it with Angular, in case you missed it - https://github.com/highkite/pdfAnnotate#-using-the-library-in-angular

**Comment by stephanrauh** [comment]
Well, sometimes libraries aren't maintained because they already offer everything that's needed. However, the author seems to answer questions and pull requests slowly.

**Comment by guptarenu240489** [comment]
@beeing @stephanrauh 
I implemented annotations on top of this with help of ng2-canvaswhiteboard(https://www.npmjs.com/package/ng2-canvas-whiteboard)
Steps :
1. Fetch base64 image of any page using this.pdfViewerService.getPageAsImage(this.page, scale)
2. Give this base64 image as input to canvasOptions for ng2-canvas-whiteboard.

**Comment by beeing** [comment]
Thanks for sharing @guptarenu240489, hope you don't mind me asking if it able to zoom in/out for the annotation?
