### ISSUE TITLE
Cannot display file offline on iOS

### ISSUE THREAD

**Issue by sgabb** [stephanrauh/ngx-extended-pdf-viewer#648]
Hi,
I am not sure this is actually a bug caused by this library (which is very cool and well documented, thank you!), however I have been struggling to find a solution to this problem and I hope that somebody could give me some suggestions.

I'm encountering a weird error when trying to load a Blob saved locally (temporary stored in IndexedDB) while **offline (no internet connection)**. The application I am working on uses heavily the Service Worker to load the app offline and serve some features, including a PDF viewer. I have followed all the setup and the library works:

- online in any browser and device;
- offline on desktop browsers (Chrome and Safari) and on mobile Android devices (Chrome).

The lib component is configured like this in the html template:
```
<ngx-extended-pdf-viewer
  [src]="file" useBrowserLocale="true" height="85vh"
  [textLayer]="true" [showPresentationModeButton]="true"
  [enablePinchOnMobile]="true" [enablePrint]="false"
  [showBookmarkButton]="false" [showDownloadButton]="false"
  [showOpenFileButton]="false" [showPrintButton]="false"
></ngx-extended-pdf-viewer>
```
where **file** is a Blob saved in IndexedDB and passed to the component.

The final error showed in the pdf viewer is:
**PDF.js v2.7.667 (build: 162577ae4) Message: The PDF file is empty, i.e. its size is zero bytes**
However, the problem is not that there is no file, but it looks like that there is a network related issue that blocks the operation.
Looking in the Network tab of the developer tools, it looks like the library tries to get something from the same application domain and fails (504) since there is no internet connection. Nonetheless, on desktop and Android it manage to continue its operations, download from cache the PDF.js file and shows the PDF file correctly. The same operation on iOS get blocked and shows the error in the viewer.

**Version info**
- 8.0.0-beta.8

**Smartphone:**
 - iPhone 11 - iOS 14.4 - Safari (14.0.3 Mobile)

**Demo PDF file**
Any PDF as the same issue.

**Additional context**
I have previously tried out the [ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer) library but there I encounter a slightly different issue, which you can find in the related [issue tracker](https://github.com/intbot/ng2-pdfjs-viewer/issues/129). I though that, since that library uses an iframe, it could be some CORS/Security issue.

Finally, I added an issue directly in PDF.js issue tracker but with no luck (the issue was the one from the ng2-pdfjs-viewer library): https://github.com/mozilla/pdf.js/issues/12967#issue-802927639

**_As a side note, on iOS the Presentation Mode Button does not show up...!_**

As I said at the beginning, any help would be much appreciated! Thanks again for your nice work!

**Screenshots**
You can find some screenshot of Android and iOS tests:

**Android**
![ngx-pdf-viewer_android_01](https://user-images.githubusercontent.com/31732038/107886227-d210d880-6efe-11eb-8bda-7aeb0cf19792.png)

![ngx-pdf-viewer_android_01_headers](https://user-images.githubusercontent.com/31732038/107886237-dfc65e00-6efe-11eb-90e8-ea52335ad4f9.png)

![ngx-pdf-viewer_android_01_initiators](https://user-images.githubusercontent.com/31732038/107886241-e5bc3f00-6efe-11eb-9fba-2644795265e6.png)

![ngx-pdf-viewer_android_02](https://user-images.githubusercontent.com/31732038/107886244-e8b72f80-6efe-11eb-8571-d82ce602142a.png)

**iOS**
![ngx-pdf-viewer_iOS_01](https://user-images.githubusercontent.com/31732038/107886247-eb198980-6efe-11eb-8145-c6187e4a73a6.jpg)

![ngx-pdf-viewer_iOS_02](https://user-images.githubusercontent.com/31732038/107886248-ed7be380-6efe-11eb-85e0-f6dbd4754d88.png)

**Comment by stephanrauh** [comment]
First of all, thanks for all the kind words! That's one of the things that help me keep going!

Let's answer your side remark first: the presentation mode button does show on iOS, just not on iPhones. Don't ask me why, I don't get it myself. It seems Apple has deliberately disabled the full-screen mode on small devices. Version 8.0.0 (the final version I've published yesterday) fixes the presentation mode on iPad - see #426.

**Comment by stephanrauh** [comment]
I wonder if it's only the Italian language files that can't be loaded. If so, I've got a solution for you. Set `useBrowserLocale="false"` and include the language files in your `index.html`. You can also add them elsewhere, the bottom line is just the files are there when pdf.js is initializing. I've prepared a JSON version of these files in `node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files`. Just take the HTML snippet and add it to the `<head>` of the `index.html`.

Talking of Italian: it seems the Italian HTML snippet is broken. Almost every text is replaced by the English original. Sounds like a weird bug - the other languages I've checked are not affected.

**Comment by stephanrauh** [comment]
The Italian language pack looks better now. The bug fix has landed with version 8.1.1.

**Comment by sgabb** [comment]
Thanks for your quick answers!

> The Italian language pack looks better now. The bug fix has landed with version 8.1.1.

Nice! I have checked it but it seems that there are still a lot of English translations in the [it.hmtl](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/assets/inline-locale-files/it.html)
Is it a file that you prepared or is it automatically created? Could I give a hand with translations?

> I wonder if it's only the Italian language files that can't be loaded. If so, I've got a solution for you. Set `useBrowserLocale="false"` and include the language files in your `index.html`. You can also add them elsewhere, the bottom line is just the files are there when pdf.js is initializing. I've prepared a JSON version of these files in `node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files`. Just take the HTML snippet and add it to the `<head>` of the `index.html`.

I have updated the lib to version 8.1.1, followed your instructions and re-deployed, unfortunately the issue seems to still be there.
I copied the content of it and en files from node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files directly into the head of index.html of the Angular app, is it correct?
```
<head>
...
<script type="application/l10n">{"default_locale":"it","locales":{"it":  ... </script>
<script type="application/l10n">{"default_locale":"en-US","locales":{"en-US" ... </script>
<script type="application/l10n">{"default_locale":"en-GB","locales":{"en-GB" ... </script>
...
</head>
```
A difference is that in the request shown [here](https://user-images.githubusercontent.com/31732038/107886248-ed7be380-6efe-11eb-85e0-f6dbd4754d88.png) the Headers now only includes _"Accept": "\*/\*"_

The same request when online is something like this (I am passing the Blob directly from local IndexedDB):
![ngx-pdf-viewer_iOS_online](https://user-images.githubusercontent.com/31732038/107893298-aefc1e00-6f2a-11eb-8d98-92020a57a831.png)

I don't understand why and where this xhr call is made...

**Comment by stephanrauh** [comment]
The HTML snippets assume you're using exactly one language. Basically, you've overwritten the Italian language pack with the US English translations, only to overwrite both of them with their Britisch counterpart. But it's also possible that the first one wins.

If you want to allow users to chose between two or more languages using the `<script type="application/l10n">` snippets, you have to create a `<script>` tag that combines all these languages. Sounds difficult? It's not, just a bit tedious. The `<script>` snippets contains a JSON object. It looks like so:

```html
<script type="application/l10n">
{
   "default_locale": "it",  // << this is the language the PDF viewer is going to display unless explicitly configured differently
  "it": {
      "previous":{"title":"Pagina precedente"},
      "previous_label":{"textContent":"Precedente"},
      ... // plus 200 other translations
  }
}
</script>
```

The combined version looks like so:

```html
<script type="application/l10n">
{
   "default_locale": "it",  // << this is the language the PDF viewer is going to display unless explicitly configured differently
  "he": { // Greek starts here
      "previous":{"title":"דף קודם"},
      "previous_label":{"textContent":"קודם"},"next":{"title":"דף הבא"},
     ... // plus 200 other translations
  }
  "it": {  // Italian starts here
      "previous":{"title":"Pagina precedente"},
      "previous_label":{"textContent":"Precedente"},
      ... // plus 200 other translations
  }
}
</script>
```

**Comment by stephanrauh** [comment]
I'm afraid I can't guess which your failing http request is trying to get. You care about private - which is good! - but I guess it would be helpful to see the filename. Is it the PDF file, or is it one of the resource files?

To narrow things down, I guess it's a good idea to simplify things. What happens if you don't display the BLOB, but use the URL in your assets folder instead? I know that's not your use-case, but it'd be good to know if this works or not.

**Comment by stephanrauh** [comment]
As for the HTML file: oops, you're right, it contains many English translations. I didn't expect that. There are at least three possible causes:

- The pdf.js team hasn't translated every text. That's easy to check, and it's plausible because they don't live in Italy. Please check the file https://github.com/mozilla/pdf.js/blob/master/l10n/it/viewer.properties. At the end of the day, it's where I get "my" translations from. Does it contain the missing texts?

- The pdf.js team is constantly updating their PDF viewer. Maybe the missing translations have simply fallen out of use. I don't update the HTML code of ngx-extended-pdf-viewer often, so it's diverging from the HTML code of pdf.js. So it's possible Mozilla removes a translation I'm still using. I guess you can see this in the change log of https://github.com/mozilla/pdf.js/blob/master/l10n/it/viewer.properties.

- I've added half a dozen texts that aren't part of Mozilla's PDF viewer. I'm always looking for volunteers translating the new texts. For some reason, I've forgotten to ask my Italian friend to help me. Maybe I can ask you? I'm talking about this folder: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/assets/additional-locale. If you send me an Italian translation, I'll buy you  a coffee or a whine or a beer when we meet in person. :)

- And of course it's possible my code is buggy. You're right, the HTML snippets are generated automatically. There's no way I can maintain so many languages and dialects manually. I've written a node.js script that takes the translations of pdf.js 2.7 as a basis, adds the translations of pdf.js 2.8, and finally adds the translations of the features I've implemented on top of pdf.js. A second script takes this `viewer.properties` file and converts into the convenience HTML snippet. It goes without saying that this is an error-prone process. You find all the magic at https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/updateMozillasPdfViewer.sh. More specifically, https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/addBaseLanguages/add-additional-translations.js implements the algorithms I've described to generate the language-specific `viewer.properties` files and https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/convertI18nFilesToJson/index.js translates these `viewer.properties` files to the HTML snippets.

**Comment by stephanrauh** [comment]
That's a lot of text - sorry about that. I18n is almost always a difficult topic. :) I hope I've managed to explain everything simple enough. If not, don't hesitate to ask me.

BTW, if I don't answer quickly, bear with me - I've caught a mild cold or something like that (hopefully not COVID!).

**Comment by sgabb** [comment]
I have done some more testing and here follows some considerations and screenshots (where I only covered the domain name)!
I want to specify that the issue is not only on Safari but on Chrome too (always talking about iOS).

This are the Network calls done when online and everything works:
![ngx-pdf-viewer_ios_01](https://user-images.githubusercontent.com/31732038/107995134-6736ce80-6fde-11eb-8213-922f42062fac.png)

Then when offline this happens, the blob url request gives back a 0 content-length:
![ngx-pdf-viewer_ios_01_offline_blob_0size](https://user-images.githubusercontent.com/31732038/107995433-b8df5900-6fde-11eb-816d-5f5efb630fea.png)

And this is the error logged in the console:
![ngx-pdf-viewer_ios_01_offline_error_console](https://user-images.githubusercontent.com/31732038/107995789-2ee3c000-6fdf-11eb-8987-367149a35b2e.png)

It seems like that the initiator of the error is [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/695621b43945b777064f7cac2f8cb7bdef6a10a3/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L218).

**The strange thing is, as seen in the first lines of the console log, that the Blob size that I am passing in the [src] of the ngx-extended-pdf-viewer component is not 0: _Blob indexedDB size 501016_**

Since we are offline, this PDF files are not stored in the assets folder, instead they have been previously downloaded and stored in IndexedDB.
Just to give an idea of what I am doing, it is something like this for the pdf-viewer component (with the logging added to check what is happening):

**.ts**
```
@Input() file: Blob;

ngOnInit() {
    try {
      console.log(`Blob in indexedDB size ${this.file.size}`);
    } catch (error) {
      console.log('no size in file!');
    }
    try {
      console.log(`Blob in indexedDB type ${this.file.type}`);
    } catch (error) {
      this.file = new Blob([this.file], {type: 'application/pdf'});
    }
  this.isLoading = false;
}
```
**.html**
```
<ngx-extended-pdf-viewer *ngIf="!isLoading"
  [src]="file" useBrowserLocale="false" height="85vh"
  [textLayer]="true" [showPresentationModeButton]="true"
  [enablePinchOnMobile]="true" [enablePrint]="false"
  [showBookmarkButton]="false" [showDownloadButton]="false"
  [showOpenFileButton]="false" [showPrintButton]="false"
></ngx-extended-pdf-viewer>
```

And before that, I am saving the file downloaded like this:

```
downloadFileAndSaveInIndexedDB() {
    const req = new HttpRequest('GET', url, {
      responseType: 'blob'
    });
    this.http.request(req)
      .pipe(
        map((res: HttpResponse<Blob>) => {
          if (res.hasOwnProperty('body')) {
            const contentDisposition = res?.headers?.get('content-disposition');
            const fileData = {
              blob: res.body,
              type: res.type,
              url: res.url,
              fileName: contentDisposition?.split(';')[1].split('=')[1].replace(/\"/g, ''),
            };
            return fileData;
          }
        })
      ).subscribe(file => {
        saveFileInIndexedDB(file);
  });
  }
```

**Comment by sgabb** [comment]
> * I've added half a dozen texts that aren't part of Mozilla's PDF viewer. I'm always looking for volunteers translating the new texts. For some reason, I've forgotten to ask my Italian friend to help me. Maybe I can ask you? I'm talking about this folder: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/assets/additional-locale. If you send me an Italian translation, I'll buy you  a coffee or a whine or a beer when we meet in person. :)

I'll check the it translation and for sure will contribute to it!
A beer will be just perfect, but I will probably be the one buying if we manage to solve this mess ^_^

May your cold be gone soon! 💪

**Comment by stephanrauh** [comment]
Beer sound good to me. :) I've grown up in the vinyards (https://www.geschichtsverein-nierstein.de/bilder/niersteiner-geschichte02.jpg), but for some reason, on most days I prefer my beer. :)

**Comment by stephanrauh** [comment]
You've narrowed down the bug considerably, so chances are you manage to go the last mile, too. Alternatively, you could try to load the file as a Base64 string. So you'd load the file first - outside of ngx-extended-pdf-viewer - and just pass a simple string to ngx-extended-pdf-viewer. That makes it easier to know whether the problem is caused by loading the file, or if it's caused by ngx-extended-pdf-viewer itself. Or - since you've already debugged to the domain of pdf.js - if it's caused by my fork of pdf.js.

**Comment by stephanrauh** [comment]
> the issue is not only on Safari but on Chrome too (always talking about iOS).

As far as I know, Chrome on iOS is just a Safari in disguise. Both share the same engine. That's a consequence of the strict guidelines of Apple.

**Comment by sgabb** [comment]
I have done another test because the offline thing seems really strange, so I tried to use the native viewer and see what happens:
**.ts**
```
constructor(
    private sanitizer: DomSanitizer
  ) { }

ngOnInit() {
    const objectURL = URL.createObjectURL(this.file);
    this.safeFile = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL);
}
```

**.html**
```
<object *ngIf="native && safeFile"
      [data]="safeFile"
      type="application/pdf"
      width="100%"
      height="100%">
      <p>Your browser does not support embedded PDFs.</p>
      <a [href]="safeFile" target="_blank">
        Open in another window.
      </a>
    </object>
```
And this is what happens, again a **_blob:null/random-code_**
![native-pdf-viewer_offline_ios_tranlsation](https://user-images.githubusercontent.com/31732038/108000746-f8ac3d80-6fea-11eb-8867-f53843d3eff1.png)

Could it be something related to how Safari and its viewer manage the absence of internet connectivity? Could there be something to do to override it?

I have also tried to "simply" download the PDF file, which results in opening it in another safari-like tab and showing something like the previous screenshot. It seems not possible to choose to open it with a different viewer when offline (even though there is the Adobe viewer app installed).

PS: I will try with the base 64 to see what happens...
However, is there something that could be going wrong in setting of the src done [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/695621b43945b777064f7cac2f8cb7bdef6a10a3/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L204) ?

**Comment by stephanrauh** [comment]
Oh, I just saw you've translated the Italian screenshot to English. That's very kind of you. But I don't think that's necessary. I'm sort of proficient at Spanish, and I've learned Latin at school, so I can usually decipher Italian texts. Of course, I'll miss all the fine points, but as long as we're talking about tech, my approach usually does the trick. Although I have to admit I'd never guessed that "indirizzio web" means "web address". :)

However, actual speech is a completely different story: I always think I understand what's going on, but in reality, I understand nothing...

**Comment by stephanrauh** [comment]
Back to topic. I can't spot an error at `set src()`. Obviously, it doesn't work in your use case, but I don't see why. I also wonder if your native viewer approach should work. What does `URL.createObjectURL(this.file);` do, precisely? Is it supposed to work with `<object>`?

 (I seriously don't know, I've never used this).

**Comment by sgabb** [comment]
I thought that only Italians learn Latin at school!
**Firstly a good news: transforming the Blob into a base64 string and using [base64Src] seems to work!**

For the sake of completeness, this is the function I use to transform the Blob into a base64 string:
```
blobToBase64(blob): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
          const dataUrl = reader.result as string;
          const base64 = dataUrl.split(',')[1];
          resolve(base64);
      };
      reader.readAsDataURL(blob);
    });
  }
```
With regards to the native viewer, I took the idea from [PDFObject](https://pdfobject.com/static/) and, since I don't have a real url because I'm offline and the pdf is a stored Blob, I am creating an [ObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL), which I am not an expert of, but it seems like it creates a virtual link url within the browser that points to the actual File/Blob. It is something that is done both in [PDF.js](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/shared/util.js#L949) and [ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/src/ng2-pdfjs-viewer.component.ts#L185).

It seems the error in this case comes from the fact that it gets a **blob:null/random-url-code**, like Safari can't reach its "internal" URL/Blob if there is no connectivity. 😣

**Comment by stephanrauh** [comment]
> I thought that only Italians learn Latin at school!

Not at all. It's popular in Germany, too, because that's the humanistic tradition and because it's believed to teach logical thinking. Funny thing is I've studied Latin for seven years, but I'd starve in the good old Roman Empire. You know, I've never learned how to ask "I'd like to buy this pane of bread". Adding insult to injury, I only know the words "yes" and "no" because I asked my teacher during our last year at school. Ain't that weird? :)

**Comment by stephanrauh** [comment]
Hey, cool, you've managed to find a workaround! Congratulations! At the moment, I don't see how you're doing the Base64 conversion - I'd expected to see the `btoa()` function or something like this - but if it works, it works!

Your error messages remind me of #534. That's a completely different scenario, but maybe there's a connection.

**Comment by stephanrauh** [comment]
Remains the question what to make of it. I suppose you're not the only one who wants to offer offline capability. Is it enough to add a dedicated page to the showcase, explaining what's going on - well, ignoring the fact we don't understand that yet - and offering your work-around as a solution?

**Comment by sgabb** [comment]
I have taken a look at #534 and it seems strange that in this case there is actually the blob:http request (as seen in the developer tools)...

I still wasn't able to check the logs using the base64, I hope to be able to do it next week.
For sure we could add some documentation details on this, however I would like to prepare a repo or something to test more thoroughly this issue directly on PDF.js. I will try to find some time..!

**Comment by stephanrauh** [comment]
Your help is definitely welcome. The library is growing more popular by the day, beyond my wildest dreams. Nowadays, many of the tickets are advanced use-cases. That's really exciting, but it also means it takes more and more time to wrap my head around it. So I'll happily take every support I can! :)

**Comment by stephanrauh** [comment]
I've just published version 8.1.2 of ngx-extended-pdf-viewer. The Italian translations should look a lot better now. Would you mind to run a test and confirm this?

**Comment by sgabb** [comment]
Updated to 8.1.2 and translations look good and aligned with PDF.js official ones!

**Comment by stephanrauh** [comment]
Hooray! The original issue is still open (at least I think so). This week-end, I've modified ngx-extended-pdf-viewer so it loads the ES5-version on iOS 13 and on every device that doesn't support the Elvis operator. Maybe that solves your original issue, too.

**Comment by stephanrauh** [comment]
I've added a description of the workaround to the showcase.
