### ISSUE TITLE
What about hotkeys for page up/down and zoom in/out?

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#65]
@Vigneshjana suggests to add hotkeys for page next, page down, zoom in, zoom out.

**Comment by stephanrauh** [comment]
Sounds reasonable, and it should be fairly simple to implement.

**Comment by Charles1972** [comment]
I solved this in this way:

///Detect keypress
@HostListener('document:keypress', ['$event']) handleKeyboardEvent(event: KeyboardEvent) {
    this.onKeyPress(event);
  }

//On key press
private onKeyPress(event: KeyboardEvent) {
    console.log('onKeyPress', event.key);
    if (this.isLoaded) {
      switch (event.key) {
        case '+': {
          this.zoomChange(0.1);
          break
        }
        case '-': {
          this.zoomChange(-0.1);
          break
        }
      }
    }
  }

private zoomChange(v: number) {
    let current = this.zoom + v;

    if (current > 0.1 && current < 4.1) {
      this.zoom = current;
    }
  }

Bye!

**Comment by stephanrauh** [comment]
When I implement my own approach, it'll break your solution. Maybe I should make the hotkeys configurable.

**Comment by stephanrauh** [comment]
BTW, thanks for your awesome and simple solution!

**Comment by stephanrauh** [comment]
Folks, it's already there! There's no need to modify the PDF viewer - unless you want to support non-standard keys:

CTRL+"0": back to 100%
CTRL+"+": zoom in
CTRL+"-"": zoom out

Also see https://github.com/mozilla/pdf.js/blob/f652cf8e5ea127393ee83e6cb30c51ecd6ce91c3/web/app.js#L2193
