### ISSUE TITLE
Zoom on mobile devices with double tap

### ISSUE THREAD

**Issue by almalib** [stephanrauh/ngx-extended-pdf-viewer#652]
Hi! You've done a great job that makes life so much easier for other developers, thank you for that. Can you please tell me if it is possible to somehow implement zoom  on mobile devices with double tap. As I understand it, at the moment ngx-extended does not have such a function. This is the only problem at the moment that prevents me from using this library. Thank You!

**Comment by stephanrauh** [comment]
Such kind words. Thank you very much! You've made an open source developer happy! Seriously, this kind of feedback is what motivates me to go on!

**Comment by stephanrauh** [comment]
As for your question: yeah, sure. I'm using the double-top all the time myself, so it's easy to convince me. I believe you can also implement it yourself. Basically, all you need to do is to register a double-tap listener and to adjust the `[zoom]` setting.

If (or when) I'm going to implement this feature, I'll have to deliver a perfect solution (or at least kind of perfect solution) from day one. So let's start with the basics. What does the double-tap gesture do, precisely? Do you have a definition at hand?

**Comment by almalib** [comment]
> As for your question: yeah, sure. I'm using the double-top all the time myself, so it's easy to convince me. I believe you can also implement it yourself. Basically, all you need to do is to register a double-tap listener and to adjust the `[zoom]` setting.
> 
> If (or when) I'm going to implement this feature, I'll have to deliver a perfect solution (or at least kind of perfect solution) from day one. So let's start with the basics. What does the double-tap gesture do, precisely? Do you have a definition at hand?

Thank you for your attention to my question! The double-tap gesture is supposed to toggle zoom (zoom in on the first double-tap and zoom out on the second), as happens on smartphones when we double-tap a photo. Also, the place we touched twice should be in the viewport after zooming in. In turn, zooming in and out should not affect the toolbar, only the pdf should zoom in and out. I hope I have explained clearly.

**Comment by stephanrauh** [comment]
Yeah, thanks for the clarification. Zoom-out might be a challenge. What zoom levels do our users expect? And it's good you've mentioned that zoom-in means that tapped region has to more or less in the center of the enlarged window. That's obvious, but it wasn't on my radar.

**Comment by almalib** [comment]
> Yeah, thanks for the clarification. Zoom-out might be a challenge. What zoom levels do our users expect? And it's good you've mentioned that zoom-in means that tapped region has to more or less in the center of the enlarged window. That's obvious, but it wasn't on my radar.

I believe the increase should be twice the original file size. I saw this in the implementation of the ngx-pinch-zoom component. For example, scale = 1 original size, scale = 2 after zoom.

**Comment by almalib** [comment]
Hello again. I have had some success with double-tap zoom in and out, although this is a rather crude solution, so far it's something for me. Right now I'm trying to show the user exactly the area he double-clicked on. Can you give me any hint in this regard?
`  dobLeTapZoom(event: TouchEvent): boolean {
    const PDFViewerApplication: any = (window as any).PDFViewerApplication;
    if (!this.isTapedTwice) {
      this.isTapedTwice = true;
      setTimeout( () => {
        this.isTapedTwice = false;
        }, 300 );
      return false;
    }
    if (PDFViewerApplication.pdfViewer.currentScale < 1) {
      PDFViewerApplication.pdfViewer.currentScale += PDFViewerApplication.pdfViewer.currentScale;
    } else {
      PDFViewerApplication.pdfViewer.currentScale /= 2;
    }
  }`

**Comment by stephanrauh** [comment]
Doesn't look bad! Thinking about it, i believe the double-tap gesture results in `[zoom]="'page-width'", and the second douple-tap restores the old setting. So you only need to center the viewer on the y-axis, not the x-axis.

I'd measure the height of the PDF viewer, calculate the relative position of the finger (like: 35% below the toolbar), and try to adjust the scrolling after resizing. More likely than not, the page is re-drawn asynchronously, so you need to wrap adjusting the scroll position in a timeout. Plus, there are many corner cases. What happens when the PDF viewer is only partially visible? What about infinite scrolling? Sounds like a hard problem. :)

**Comment by almalib** [comment]
> Doesn't look bad! Thinking about it, i believe the double-tap gesture results in `[zoom]="'page-width'", and the second douple-tap restores the old setting. So you only need to center the viewer on the y-axis, not the x-axis.
> 
> I'd measure the height of the PDF viewer, calculate the relative position of the finger (like: 35% below the toolbar), and try to adjust the scrolling after resizing. More likely than not, the page is re-drawn asynchronously, so you need to wrap adjusting the scroll position in a timeout. Plus, there are many corner cases. What happens when the PDF viewer is only partially visible? What about infinite scrolling? Sounds like a hard problem. :)

Yes, this is not an easy task, at least for me)). However, I need to solve it one way or another))). An example of what I'm aiming for is shown in this demo [.](https://www.pdftron.com/webviewer/demo/) I will try to use your advice, I hope I succeed, but this is rather difficult, given my little experience.

**Comment by stephanrauh** [comment]
I've just published version 8.3.0-preview, containing an implementation of the double-tap. To my surprise, the feature works better than I expected. It already focuses on the tap area. Can you confirm that?

Best regards,
Stephan

**Comment by masartbenji** [comment]
Hello, do you think it will be hard to make the zoom after double-tap as parameter on the library. Actually, I need a 150% zoom in the area of the double-tap :) Thank you.

Best regards,
Nicolas

**Comment by stephanrauh** [comment]
Version 9.0.0-alpha.1 (which has landed a few minutes ago) adds the option as a default attribute: 

``` typescript
import { pdfDefaultOptions } from 'ngx-extended-pdf-viewer';

constructor() {
  pdfDefaultOptions.doubleTapZoomFactor = '150%';
}
```

**Comment by masartbenji** [comment]
Hello,

Thank you for your work :) I have the impression that the zoom only takes into account the height of the document to apply the zoom but I would like it to also take into account the width of the document, so that when I double click on the document, there is a sort focus on the area of ​​my click.

Best regards,

Nicolas Hubert

**Comment by stephanrauh** [comment]
Basically, my algorithm is very simple. It increases the zoom to "page-width" (by default) or to 150% (in your case). That's pretty much the same as choosing the zoom from the dropdown. To my surprise, pdf.js always makes sure that the text under the mouse pointer remains there after scaling the document. Does it behave differently on your machine?
