### ISSUE TITLE
iOS Ionic App: All PDF Files not showing (SintaxError: Unexpected Token '.')

### ISSUE THREAD

**Issue by LuisManuel1983** [stephanrauh/ngx-extended-pdf-viewer#657]
Hi, grettings from Venezuela, I've been using this pdf viewer inside my **Ionic Capacitor** project for a couple of months and I got to say I love it, is really great and thank you so much for creating this... but since yesterday I have a bug in iOS where any PDF file I try to load does not show (blank screen) and I have no idea how to solve it. I recently updated to the last version (8.1.1) to allow viewing of pdf and download buttons and the tests I ran in Android (simulator and device), via web browser (Safari, edge, chrome) with ionic serve all open pdf's files without a problem, but when I open a pdf file inside the iOS simulator or an iOS device I can't see ANY pdf file. I mean not a single one. The error message that I could get (from simulator) is this:

> ---- STARTUP JS ERROR ---- 
SintaxError: Unexpected Token '.'
URL: capacitor://localhost/assets/pdf-2.7.673.min.js
pdf-2.7.673.min.js:22:0

![error](https://user-images.githubusercontent.com/16975334/108433728-cda93000-721c-11eb-97f1-01c589318823.png)

Here is a test in safari (via "ionic serve") with the same source files using the library and the same pdf file without a problem:

![safari](https://user-images.githubusercontent.com/16975334/108434491-1ca39500-721e-11eb-927f-20cdd165cb02.png)

Maybe an issue with capacitor + iOS ? what can I look for to solve this? I read that I can update to pdf.js 2.8 but I'm not sure how to do that. Sorry I'm not experienced with JS or Angular so forgive me if I missed something obvious

**Version info**
- "^8.1.1"

**Smartphone:**
 - iOS Simulator: [iPhone 7 to 12]
 - Device: [iPhone 7]

**Additional context**
I followed the instruccions to use this library with ionic specified here as an example:

https://github.com/tanzl88/ionic-3-extended-pdf-viewer

But my project is Ionic 5 and also with capacitor, not sure if that has any effect. Also, I'm not sure if it's related, but the printing and download functions are not working in Android app (web version works well but that's not really my objective). But that's a minor problem compared to not been able to open any pdf file in iOS

Again, thanks for this library. Any help you can provide me is greatly appreciated

**Comment by LuisManuel1983** [comment]
More detail, I have a single page that acts as the pdf viewer and receives parameters like the pdf name and page number (optional) so every page that wants to open a pdf calls it and send parameters. Here's how I use it in my code:

![code](https://user-images.githubusercontent.com/16975334/108436862-9b023600-7222-11eb-9c7b-a79104cc2eee.png)

**Comment by stephanrauh** [comment]
Hola Luis, I guess there's a missing polyfill. I don't have your source code, nor do I have an iOS simulator, so I need your help. Can you add the attribute `[minifiedJSLibraries]="false"`, please? This slows down the PDF viewer, but gives us a useful stacktrack.

**Comment by stephanrauh** [comment]
Updating to version 2.8. is easy: https://pdfviewer.net/extended-pdf-viewer/pdfjs-versions. But I'm afraid this doesn't help you. I suppose you've run into a new bug, and version 2.8 is even news. But of course, you never so, so give it a try!

**Comment by LuisManuel1983** [comment]
Thanks for the quick response! I tried using the bleeding edge version but it gave me this error:

ngx-extended-pdf-viewer.js:1838 GET http://localhost:8100/bleeding-edge/pdf-2.8.203.js net::ERR_ABORTED 404 (Not Found)

When I review my "www" folder I can't see a folder called bledding edge or js files for 2.8 version. This is how my assets folder looks like:
![list](https://user-images.githubusercontent.com/16975334/108505467-d71eb080-728d-11eb-8083-bf375a0749a6.png)

I'm doing something wrong in the configuration of my project? I have in the package.json the line "ngx-extended-pdf-viewer": "^8.1.1",

Do I need to include something else so ionic creates this bleeding-edge folder?

**Comment by LuisManuel1983** [comment]
Nevermind, I just remembered the scripts section on angular.json to copy to the assets folders... ok so, I'm doing tests with this config on iOS and I'll update after testing all. Thanks

**Comment by LuisManuel1983** [comment]
Allright I managed to execute the test. Here is what is trowing now:
![error](https://user-images.githubusercontent.com/16975334/108516304-6fbc2d00-729c-11eb-87a6-3230fac93b4b.png)

And this is the code that is pointing at:
![pdf-js](https://user-images.githubusercontent.com/16975334/108516984-39cb7880-729d-11eb-964e-08c603ce5fbe.png)

Any idea?

**Comment by stephanrauh** [comment]
Yeah, looks like the Elvis operator is the culprit:

![image](https://user-images.githubusercontent.com/3045767/108553856-8e014780-72f3-11eb-9f98-55ffa7905a8e.png)

**Comment by stephanrauh** [comment]
Shameless self-advertising: https://www.beyondjava.net/elvis-operator-aka-safe-navigation-javascript-typescript

**Comment by stephanrauh** [comment]
Basically, all you need to do is using the ES5 version of the JavaScript libraries. However, I just saw there's no elegant way to enforce this. Plus, I'd like my library to sort these gory details out. As a short-term remedy, I'm raising the minimum version of the iOS version you need. But I don't think that approach is good enough, so I'm not going to publish the library tonight.

As a temporary work-around, you can add `pdf-2.7.673-es5.min.js` or `pdf-2.8.203-es5.min.js` to the `scripts` section of your `angular.json`. That's a bad solution, of course, but it should help you survive the week-end until I've found a way to check whether your JavaScript engine support the `?.` operator. 

(The challenge is when I implement it in TypeScript, it's most likely converted to ES5 code, so my check always says "it's supported").

**Comment by LuisManuel1983** [comment]
"Languages like JavaScript are even worse than the average programming languages" LOOL (I come from over a decade working in Java so yeah, totally agree on JS)

Awesome man, I'm still trying to get my head around modern JS, your article was a great read. I'll be trying your fix as mentioned, thank you so much

**Comment by stephanrauh** [comment]
¡Gracias! I came from a Java background, and I'm still programming Java on a daily basis - but believe me, compared to modern JavaScript it looks like a flintstone tool compared to a modern hammer. It does the trick, it's great and fast, but it's oh so cumbersome... :) The downside is JavaScript has all this history. Adding new ideas like `?.` or `??` always breaks an application or two.

Hasta pronto,
Stephan

**Comment by stephanrauh** [comment]
I've just published version 8.1.2 of ngx-extended-pdf-viewer. I believe it fixes the bug - but since it doesn't happen on any of my machines, I need you. Would you mind to run a test and tell me if the new version fixes the bug or not?

**Comment by LuisManuel1983** [comment]
Hi, on weekends I don't have access to the mac (is from a co-worker and I connect remotely). On monday I will test with a normal version. Thanks!

**Comment by stephanrauh** [comment]
No hay prisa. :)

**Comment by LuisManuel1983** [comment]
Ok so I did a new test using version 8.1.2 and this is the error that I'm getting now:

![error simulator](https://user-images.githubusercontent.com/16975334/108748315-d2b7f900-7514-11eb-859a-33f8b85d6bc5.png)

When I look at the code that the comment is flagging, I see this:
![code](https://user-images.githubusercontent.com/16975334/108748391-ec594080-7514-11eb-9922-c93da36642f9.png)

And finally this:
![code 2](https://user-images.githubusercontent.com/16975334/108748435-f7ac6c00-7514-11eb-9373-b112810b5e00.png)

I did this test with 

> [minifiedJSLibraries]="false"

Anything else you want me to do?

**Comment by LuisManuel1983** [comment]
Oh and BTW, I just did a test on a physical iPhone 7, and it can open PDF files without a problem.... this is weird but at least the actual app is working to view pdf files jajajajajaja

**Comment by stephanrauh** [comment]
Yeah, that sound's like your iOS emulator is a bit too eager. It's true, the ngx-compatibility-checks.js file actively provokes the error you've seen. However, the script catches the error in a try-catch-block, so I wonder why it shows up in your emulator at all. The idea is if the code succeeds, the method returns true, if not, it returns false. So I know whether your iPhone is able to run modern code using the Elvis operator or not.

**Comment by stephanrauh** [comment]
I'm afraid that's the problem indeed: you emulator correctly detects a syntax error, but it doesn't detect I've cared about it. I'm not sure how to solve this. In theory, I could use `eval()`, but the `eval()` function raises flags among security-aware people, so the solution might backfire.

**Comment by LuisManuel1983** [comment]
Hi... so.. this error is now iOS emulator only, it doesn't happen on Android (emulator, device), Ionic serve or an iOS device... is there anything else I can do? I'm just handling this issue by telling others to test iOS on devices only for pdf handling, so this is ok for me

**Comment by stephanrauh** [comment]
Let's close the ticket. I'll keep the emulator problem in mind. I'm going to mention it in the "troubleshooting" section of the showcase, but that's only a first step.

It's been fun to solve the issue with you. You've described the problem so well I was able to help you even though I don't have the emulator. That's not small achievement. Keep on the good work!

Hasta la próxima
Stephan

**Comment by LuisManuel1983** [comment]
Thank you! is been fun to figure out this issue. Hasta la próxima 😎

**Comment by bmadhan90** [comment]
Hi anyone can help,

![image](https://user-images.githubusercontent.com/37164224/144619966-dbe8c85e-0cf9-4e10-9536-523a2fb244a9.png)

getting above error in below code

![image](https://user-images.githubusercontent.com/37164224/144620275-3def9f3d-aeb0-42cc-a33c-0bc6dad26b9d.png)

**Comment by stephanrauh** [comment]
I've run into the same error a few weeks ago with Firefox ESR, but I can't reproduce it. Can you give me a hint why the `||=` operator doesn't work on some browsers? More to the point, how can I detect whether your browser supports it or not?

**Comment by stephanrauh** [comment]
@bmadhan90 Please update to version 11.0.0-alpha.11 and tell me if it fixes the bug. I'm tracking the progress of your bug report here: #1063.

**Comment by elvisgraho** [comment]
> I've run into the same error a few weeks ago with Firefox ESR, but I can't reproduce it. Can you give me a hint why the `||=` operator doesn't work on some browsers? More to the point, how can I detect whether your browser supports it or not?

I got the same Error on Android just now with the latest updates and the issue is not ||=, but the statement inside getPageJSActions which uses Elvis operator 'page?.' That is why the error message explicitly mentions ".".

**Comment by stephanrauh** [comment]
@elvisgraho Did you already check ngx-extended-pdf-viewer 11.1.1? This version checks if the browser supports optional chaining (`?.`), logical assignment, and private class members.

BTW, if the error occurs near `getPageJSActions`, the culprit is probably `||=`. If it happens in that method, I'm at a loss because the method looks innocent:

```js
  getJSActions() {
    return (this._jsActionsPromise ||= this._transport.getPageJSActions(
      this._pageIndex
    ));
  }

 getPageJSActions(pageIndex) {
    return this.messageHandler.sendWithPromise("GetPageJSActions", {
      pageIndex,
    });
  }
```

**Comment by elvisgraho** [comment]
@stephanrauh I am sorry, the actual method is called `getCurrentlyVisiblePageNumbers` and it has the same error `SyntaxError: Unexpected token .`

```ts  
getCurrentlyVisiblePageNumbers() {
    const app = window.PDFViewerApplication;

    const pages = app.pdfViewer._getVisiblePages().views;

    const pageNumbers = pages?.map(page => page.id);
    return pageNumbers;
  }
```

**Comment by elvisgraho** [comment]
@stephanrauh cloud you find the issue in `getCurrentlyVisiblePageNumbers` ?

**Comment by stephanrauh** [comment]
Oh. Sorry. It's always a gamble to add questions to closed issues: I do react, but they're closed, so next day, I've forgotten it. :(

To answer your question: no, I'm clueless. I'm 99% sure the syntax error happens at the `pages?.map()` bit. But that's exactly what my browser support check checks:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/assets/op-chaining-support.js

```javascript
// This file provokes syntax errors if your browser doesn't support
// some new JavaScript standard. This allows ngx-extended-pdf-viewer
// to switch to the slow but reliable legacy builds.
const optionalChaining = {
  support: true,
};

// Does your browser support the logical assignment operators?
let x = false;
x ||= true;


// Does your browser doesn't support private fields?
class ClassWithPrivateField {
  #privateField;
}

window.supportsOptionalChaining = optionalChaining?.support;
```

If there's an error, you're gracefully redirected to the ES5 build. But this doesn't seem to work in your case.

I can't reproduce your bug, so I'd like to ask you for help. Please add a breakpoint to the `op-chaining-support.js` script and check whether there's an error or not. And send me a screenshot of your network traffic. Are the modern ES2020 files used, or does ngx-extended-pdf-viewer load the "legacy" ES5 files?

**Comment by elvisgraho** [comment]
`"ngx-extended-pdf-viewer": "^11.2.0-alpha.1"` As soon as I do any kind of `ngx-extended-pdf-viewer` import in typeScript the app crashes at the start. I cant set any breakpoints.

![Screenshot_1643024754](https://user-images.githubusercontent.com/42517259/150777406-ed22a64d-c770-4620-b657-ddbf93650e88.png)

![error](https://user-images.githubusercontent.com/42517259/150777429-9ca0593c-6ba1-4efb-8166-c97f8a0aa86a.png)

<img width="1439" alt="angularjson" src="https://user-images.githubusercontent.com/42517259/150777652-19f7bfc2-9c4f-4aa0-848d-73e9c1852557.png">

**Comment by stephanrauh** [comment]
@elvisgraho If you don't mind, let's continue the discussion here: #1142. You're using a different device, but it seems to be the same bug.

What I don't understand is why my browser switch doesn't work. I'm tempted to implement an attribute like `[alwaysUseLegacyJavaScript]`. But I'd hate that, because that'd be a performance penalty to the vast majority of users!

**Comment by stephanrauh** [comment]
@elvisgraho I forget my good manners... thank's a lot for digging so deep into the issue and for providing detailed information!

**Comment by elvisgraho** [comment]
@stephanrauh Thank you
