### ISSUE TITLE
Is it possible to use it with Ionic 3?

### ISSUE THREAD

**Issue by silaslira** [stephanrauh/ngx-extended-pdf-viewer#66]
I have tried, but since there is no angular.json file to import external scrips, I am not sure it is possible.

Thank you!

**Comment by stephanrauh** [comment]
I've spent the entire evening figuring out how to get my library up and running with JHipster. Problem is, JHipster uses webpack instead of the standard Angular build tools. Does Ionic 3 do the same?

**Comment by stephanrauh** [comment]
OK, I've digged a little deeper into the challenge. I guess the best option is to update to Ionic 4. As far as I can see, this has been rewritten using the standard Angular CLI.

You second option is to copy the assets folder to your project. Plus, you need to import the three files `pdf.js`, `pdf.worker.js`, and `web/viewer.js` in a file of your project - something like `main.ts`. I've described how to do it in the [README.md](https://www.npmjs.com/package/ngx-extended-pdf-viewer#how-to-use-the-library). 

I hope the Ionic 3 setup is similar, so you get it up and running!

Like always, please report back if my hints helped you or not. If it doesn't, I'll reopen the ticket.

Thanks in advance,
Stephan
