### ISSUE TITLE
Wrong documentation for Zoom option

### ISSUE THREAD

**Issue by stanciupaul** [stephanrauh/ngx-extended-pdf-viewer#662]
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/a7d378773856598b10036152f09f000558a54aa1/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer-server.component.ts#L345

`page-fit` should be mentioned instead of `page_fit`

**Comment by stephanrauh** [comment]
Oops. Yeah, this can be confusing. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
Done. Luckily the typo occurred only in two places, and the documentation in the showcase was (and is) correct.
