### ISSUE TITLE
Reset the Form Action Not Working on PDF Forms

### ISSUE THREAD

**Issue by JerinThomas15** [stephanrauh/ngx-extended-pdf-viewer#666]
Reset the Form Action is not working  on ngx-extended-pdf-viewer. Our PDF forms has a Reset button to clear all the fields. This functionality is working on other PDF viewers. 

![AdobeForm](https://user-images.githubusercontent.com/25506832/108952987-72e65d00-7690-11eb-96b0-0b8bd105f2db.PNG)

![image](https://user-images.githubusercontent.com/25506832/108952971-66fa9b00-7690-11eb-82e9-ed99f9dd0e78.png)

[ResetForm.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/6033621/ResetForm.pdf)

**Comment by stephanrauh** [comment]
I'm afraid it doesn't work on every PDF viewer. I've just started a brand-new firefox and opened your PDF file in the browser. The print button works, but the reset button doesn't do anything.

ngx-extended-pdf-viewer uses the PDF viewer of Firefox, so it's no surprise it doesn't support the reset functionality, either. You can also check this on Mozilla's demo pdf of pdf.js: https://mozilla.github.io/pdf.js/web/viewer.html

But let's include an expert in the loop. @timvandermeij, is pdf.js supposed to support the "reset" functionality"? Or are you and your collaborators developing such a feature in version 2.8?

**Comment by timvandermeij** [comment]
It's not implemented right now due to the fact that AcroForm support is not completely done yet, but the good news is that we have a tracking issue for this on the PDF.js side at https://github.com/mozilla/pdf.js/issues/12721, so this is definitely on our radar. It's not known right now when this will be done though.

**Comment by stephanrauh** [comment]
Hooray!

**Comment by stephanrauh** [comment]
@JerinThomas15 I'd like to close the ticket now. I know it's annoying from your point of view, but implementing this feature is clearly out of scope of this library. I'm not even sure I could implement it if I wanted to.

I hope I've got better news for you next time!

Best regards,
Stephan
