### ISSUE TITLE
Fast zooming crashes the viewer on Android / Chrome

### ISSUE THREAD

**Issue by jpxd** [stephanrauh/ngx-extended-pdf-viewer#669]
**Describe the bug**
Slowly pinch zooming works with `enablePinchOnMobile` in Chrome / Webviews on Android. Fast zooming in and scrolling leads to glitching, flickering and eventually crashes the whole web view (ionic capacitor app / chrome tab). See the video for examples.

**Version info**
- Version of ngx-extended-pdf-viewer: `^8.1.2`

**Smartphone (please complete the following information):**
 - Device: One Plus 5
 - OS: Android 10
 - Browser: Google Chrome 88.0.4324.181

**To Reproduce**
Navigate to https://pdfviewer.net/touch-gestures. Zoom in fast on the PDF and then try to scroll.

**Demo PDF file**
The default PDF on https://pdfviewer.net/touch-gestures works.

**Screenshots**
See this videos. One time in an Ionic App (in a web view) and two times in the Google Chrome App.
First I tested slow zooming & scrolling which works. Fast zooming breaks everything. The chrome tab has to be closed entirely.

https://user-images.githubusercontent.com/10384363/109139329-afcb5600-775b-11eb-995d-9f451924a4a5.mp4

https://user-images.githubusercontent.com/10384363/109139340-b35edd00-775b-11eb-80f6-cf022a99aa06.mp4

https://user-images.githubusercontent.com/10384363/109139351-b5c13700-775b-11eb-870b-b34f250c0e82.mp4

**Comment by jpxd** [comment]
Could be related to #591 ?

**Comment by stephanrauh** [comment]
I'm afraid I don't know how to examine the bug. I don't own an Android device, nor do I own an Android emulator. Maybe you can help me.

Are there any message in the JavaScript console?

**Comment by almalib** [comment]
> Может быть связано с [№ 591](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/591) ?

Hi. Did you manage to solve this problem?

**Comment by almalib** [comment]
If I enlarge the PDF to its maximum size using gestures, it also causes the Android app to freeze.

**Comment by stephanrauh** [comment]
Thank for providing the additional info! Unfortunately, I still don't have an Android device, so I can't reproduce the bug. Is it possible to reproduce the bug in a desktop Chrome or an iOS device?

**Comment by almalib** [comment]
> Thank for providing the additional info! Unfortunately, I still don't have an Android device, so I can't reproduce the bug. Is it possible to reproduce the bug in a desktop Chrome or an iOS device?

no, I was not able to do it. The bug appears only on a smartphone. Checked on different android smartphones.

**Comment by almalib** [comment]
I think it has to do with re-rendering the PDF after enlarging. Is there a way to make the PDF not re-render after scaling?

**Comment by stephanrauh** [comment]
Yes, maybe there's such a feature. Try to set `pdfDefaultOptions.useOnlyCssZoom=true;`. I've never tried this one, but it sounds like it could help you.

You could also try `pdfDefaultOptions.renderer='svg'`or `pdfDefaultOptions.enableWebGL=true`. That's a far shot, but it's worth a try.

**Comment by almalib** [comment]
Thanks for the answer. pdfDefaultOptions.useOnlyCssZoom = true; It works, but where would I best use this? in ngOnInit?

**Comment by stephanrauh** [comment]
Usually, I set the default options in the constructor of the component using `<ngx-extended-pdf-viewer>`. That's because some of the options must be set before pdf.js is loaded. But in this particular case, it doesn't matter. `ngOnInit` should do the trick, too.

BTW, does the CSS zoom reduce the quality of the enlarged image?

**Comment by stephanrauh** [comment]
If you don't mind, I'm going to document the problem and the workaround on the [troubleshooting page](https://pdfviewer.net/extended-pdf-viewer/troubleshooting) and close the ticket. I'd prefer to solve the problem, but as long as I can't even reproduce it, I won't be able to solve it.

**Comment by almalib** [comment]
> Usually, I set the default options in the constructor of the component using `<ngx-extended-pdf-viewer>`. That's because some of the options must be set before pdf.js is loaded. But in this particular case, it doesn't matter. `ngOnInit` should do the trick, too.
> 
> BTW, does the CSS zoom reduce the quality of the enlarged image?

I use maxZoom = 2. I did not notice the change in quality. However, there was a problem that when the page was refreshed on the iphone, some pages remain white if you quickly scroll down. No text is drawn on them. But I'm not sure yet what exactly caused this problem.

**Comment by stephanrauh** [comment]
OK, I can try to reproduce that on iOS. That's always difficult, but I'll keep my eyes open. You don't happen to have a Browserstack account? It allows us to test web applications on real devices without having to buy them. However, unless you can prove you're an open source developer, it's not cheap.

**Comment by almalib** [comment]
> OK, I can try to reproduce that on iOS. That's always difficult, but I'll keep my eyes open. You don't happen to have a Browserstack account? It allows us to test web applications on real devices without having to buy them. However, unless you can prove you're an open source developer, it's not cheap.

Unfortunately I don't have a Browserstack (

**Comment by almalib** [comment]
> > OK, I can try to reproduce that on iOS. That's always difficult, but I'll keep my eyes open. You don't happen to have a Browserstack account? It allows us to test web applications on real devices without having to buy them. However, unless you can prove you're an open source developer, it's not cheap.
> 
> Unfortunately I don't have a Browserstack (



https://user-images.githubusercontent.com/59205866/110631806-fab38780-81b7-11eb-9116-fa0d0f1b480c.mp4

https://github.com/almalib/pdfjs-test - source code repository
https://almalib.github.io/pdfjs-test/ - demo

**Comment by stephanrauh** [comment]
I'm afraid I won't find the time to solve the bug anytime soon. New bug reports and feature requests come in faster than I can solve them. So I guess the best approach is to tell you how to solve the problem yourself. You can debug the code, test it with your real application, and tune it until it fits your need. I can do none of that.

Pinching is implemented in this class: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts

Copy this class to your project, make sure it's loaded, and disable the built-in pinch support (i.e. set `[enablePinchOnMobile]="false"`). The constructor of the class injects Angular's `ngZone` object. I guess it's automatically injected if you convert the class to an Angular service.

Once you've done that, your copy of the class is responsible for pinching, and you can hunt down the bug.

**Comment by jpxd** [comment]
Thanks for the tips @stephanrauh!

I just tested a bit and the problematic code seems to be setting the pdf.js scaling factor `currentScale` in `touchend` with high values. The CSS-transform scaling itself works without any problems. Just the pdf.js-scaling in `touchend` sometimes triggers to the bug. Because the mobile Chrome App completely freezes or crashes I could not debug any further with Chrome Remote Debugging tools.

So in the end the bug is in pdf.js itself and not this library... `useOnlyCssZoom` seems to help though.

**Comment by stephanrauh** [comment]
You can limit the maximum zoom with the attribute `[maxZoom]`. There are also browser-specific limits. Every browser has a specific maximum size of a canvas it can display. I've added checks to make sure to don't exceed them, but maybe that doesn't work yet on Android.
