### ISSUE TITLE
Z-index on class toolbar

### ISSUE THREAD

**Issue by LoganDupont** [stephanrauh/ngx-extended-pdf-viewer#67]
At the moment there is a z-index of 9999 set on the div with class toolbar.

The problem for me was that I had to override the css with !important which I don't prefer to use.

So I was wondering why this was set so high and If it's not possible to let the developer choose the z-index through an input for example.

**Comment by stephanrauh** [comment]
I've inherited the 9999 from Mozilla. A short test showed I can lower it a lot. I've set it to 1 without observing negative effects. Actually, even 0 and -1 work, and that's eerie. Obviously either I have missed something, or the Mozilla team set the `z-index` ridiculously high without thinking twice.

Be that as it may: if I were able to set the `z-index` to 1 - or, say - 10, would you still need the `[zIndex]` property?

**Comment by stephanrauh** [comment]
FWIW, I've run into trouble with the z-index on my (nucleus of a) showcase today. When you're scrolling the page, parts of the toolbar are above the navigation menu, while other parts are hidden behind it.

If you're interested, have a look at https://atapuerca.de.

**Comment by stephanrauh** [comment]
@LoganDupont I suppose you'll like version 0.9.27. I've reduced the z-indices as much as possible. Now every z-index is below 10.
