### ISSUE TITLE
Is there a functional demo (i.e., stackblitz)?

### ISSUE THREAD

**Issue by g3344** [stephanrauh/ngx-extended-pdf-viewer#68]
Hi, this looks like a great repo.

Is there a functional demo of it (i.e., stackblitz)?

It would be great to see a demo before going through the install process.

**Comment by stephanrauh** [comment]
I'm working on it.

Unfortunately, it's not possible to use ngx-extended-pdf-viewer on Stackblitz. That's a great platform, but it doesn't parse the `angular.json` file, and I didn't find another way to import the required JavaScript files.

**Comment by g3344** [comment]
Thanks for the quick answer.  Looking forward to the demo.

**Comment by stephanrauh** [comment]
Here's a very, very early preview:

https://atapuerca.de/simple

Sourcecode at https://github.com/stephanrauh/extended-pdf-viewer-showcase

Please note everything is subject to change - including the URL. I just want to give a an early feedback. Ideas, suggestions, criticism, and pull requests are always welcome!

**Comment by g3344** [comment]
Fantastic.  Thank you. 

FYI, for some odd reason, when I went to https://atapuerca.de/simple directly, it gave me a 404.  But when I typed just https://atapuerca.de/ it then redirected me appropriately.

Thanks again!

**Comment by stephanrauh** [comment]
Thanks for the hint regarding the missing redirection!

**Comment by stephanrauh** [comment]
OK, I've updated the server configuration. Closing the issue again.
