### ISSUE TITLE
Download menu for the viewer

### ISSUE THREAD

**Issue by uk974q** [stephanrauh/ngx-extended-pdf-viewer#680]
I am not sure if this is a bug, a feature request or something which I missed.  
Whenever I am trying to download a file, it downloads as per the name given programmatically. But the issue is that I could not specify the location or a different name for the downloaded file. 
We do have an option to specify the location with Firefox. 

Is it possible to have a menu for the download and wait for user input to save?

![image](https://user-images.githubusercontent.com/8845209/110313156-0ffbab00-802c-11eb-8917-56e90f1897bd.png)

**Comment by stephanrauh** [comment]
I'm afraid there's nothing I can do about it. It's just one of the annoying limitations of JavaScript. 

But then... your GitHub profile says you're an Angular expert, so maybe you've got an idea how to solve this. This is the code implementing the download:

```JavaScript
function download(blobUrl, filename) {
  const a = document.createElement("a");
  if (!a.click) {
    throw new Error('DownloadManager: "a.click()" is not supported.');
  }
  a.href = blobUrl;
  a.target = "_parent";
  // Use a.download if available. This increases the likelihood that
  // the file is downloaded instead of opened by another PDF plugin.
  if ("download" in a) {
    a.download = filename;
  }
  // <a> must be in the document for recent Firefox versions,
  // otherwise .click() is ignored.
  (document.body || document.documentElement).appendChild(a);
  a.click();
  a.remove();
}
````
Any idea how to implement it better?

**Comment by stephanrauh** [comment]
I'm closing the ticket for the moment, because I don't think it can be solved - but I'm still listening to this channel, so don't hesitate to suggest a solution. I'll happily re-open the ticket!

Best regards,
Stephan
