### ISSUE TITLE
Property [(sidebarVisible)] = "sidebarVisible" doesn't work for Angular 11

### ISSUE THREAD

**Issue by VolodymyrHabudaDevPro** [stephanrauh/ngx-extended-pdf-viewer#681]
**Describe the bug**
When adding property [(sidebarVisible)] = "sidebarVisible", (sidebarVisible = true) does not add class = "sidebarOpen" to id = "outerContainer" in html site-bar and the the site-bar is closed. 
Are you planning to support Angular 11 and further versions? 

**Version info**
- Version of ngx-extended-pdf-viewer - "5.2.1", "8.1.2"
- angular/animations": "11.2.3"

**Desktop:**
 - Browser: Chrome
 
**To Reproduce**
when loading the page, the sidebar remains closed

**Thank you!**
thanks in advance for your reply

**Comment by stephanrauh** [comment]
I've added a demo at https://pdfviewer.net/extended-pdf-viewer/custom-sidebar for you. It demonstrates the two-way binding of `[(sidebarVisible)]`. It works pretty well. To double-check, I also tested the demo with an initially closed sidebar. That worked, too.

As for you second question: yes, of course. Currently, the showcase runs on Angular 11. Currently, the library supports every version from 5 to 11. When Angular 12 is release, I've decided to drop support for Angular 7 and below.

**Comment by VolodymyrHabudaDevPro** [comment]
@stephanrauh thanks for your reply. 
Please tell me is it possible that this problem exists when using [customSidebar] and [(sidebarVisible)] at the same time? 
Thanks in advance for your reply.

**Comment by stephanrauh** [comment]
Well, you've formulated that as a question, but the demo of the showcase seem to confirm your suspicion. When I activate the "fancy sidebar" radio button, I have to toggle the sidebar checkbox twice to show the sidebar. So, yes, maybe you're right: custom sidebars are not shown at load time when `[sidebarVisible]="true"`.

**Comment by stephanrauh** [comment]
The problem is the missing `outlineOptionsContainer`.  It's a recent addition to pdf.js and the error message is silently swallowed. You can either update to version 9.0.0-alpha.2 or add an empty `<div id="outlineOptionsContainer"></div>`.

![image](https://user-images.githubusercontent.com/3045767/113480733-2a437000-9496-11eb-98d3-33248c2fe592.png)
