### ISSUE TITLE
Hide console log

### ISSUE THREAD

**Issue by jordankkk** [stephanrauh/ngx-extended-pdf-viewer#683]
Hi

Can we hide the console log when preview the pdf  ?

![image](https://user-images.githubusercontent.com/38534295/110562200-0422fc80-8184-11eb-816a-d2cd8558e022.png)

Thanks

**Comment by stephanrauh** [comment]
Yes, you can. Just add the attribute `[logLevel]="0"`.

Best regards,
Stephan
