### ISSUE TITLE
ngx-extended-pdf-viewer  any way of disabling drag and dropping to canvas? 

### ISSUE THREAD

**Issue by kliarist** [stephanrauh/ngx-extended-pdf-viewer#686]
I need to somehow prevent users from drag and dropping to the canvas of the pdf plugin. I went through the various settings for customising it and while some are very useful for other features, I could not find one for disabling drag-and-drop. Is this supported out of the box or will I have so somehow do it via css?  I have attached a git for you to take a look

![2021-03-10 09 36 28](https://user-images.githubusercontent.com/1371419/110593475-48160180-8184-11eb-860a-f427b17af317.gif)

**Comment by stephanrauh** [comment]
I'd expected a different bug report: it seems draggin and dropping a file to the PDF viewer does not work, can you (Stephan) do something about it? :)

Currently, there's no way to prevent dropping a file. Using CSS sounds like a hot trace. Have you got an idea how to implement this yourself? I could pick up your idea and implement it in the next version of the library.

**Comment by kliarist** [comment]
Sorry somehow I missed the notification. It is still on my to-do list and a matter of time before it gets raised as a bug on our software. (Which uses your plugin). Agreed if we somehow disable it, I will share.

**Comment by stephanrauh** [comment]
This feature is going to be part of the 8.4.0 release.

**Comment by kliarist** [comment]
Great thanks!

**Comment by stephanrauh** [comment]
I've decided to skip the 8.4.0 release. I've just release 9.0.0-alpha.0, which contains your improvement.

**Comment by kliarist** [comment]
Sure no probs. Will check is out in the next couple of days. Thanks again
