### ISSUE TITLE
Couldn't get it running in Angular 4

### ISSUE THREAD

**Issue by crlsmsq** [stephanrauh/ngx-extended-pdf-viewer#696]
I saw and applied your documentation on how to set the library up in angular 4.

Upon running it via `npm start` I got these errors. The version of the lib was from the repo

ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/pdf-notification-service.ts (4,2): Supplied parameters do not match any signature of call target.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/pinch-on-mobile-support.ts (108,81): Argument of type '{ passive: boolean; }' is not assignable to parameter of type 'boolean'.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/unit-to-px.ts (1,39): Cannot find module '../../types/src/shared/util'.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/ngx-extended-pdf-viewer.component.ts (1676,72): ',' expected.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/ngx-extended-pdf-viewer.component.ts (234,7): The left-hand side of an assignment expression must be a
variable or a property access.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/ngx-extended-pdf-viewer.component.ts (1377,9): The left-hand side of an assignment expression must be a variable or a property access.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/ngx-extended-pdf-viewer.component.ts (1676,35): Supplied parameters do not match any signature of call
target.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/ngx-extended-pdf-viewer.component.ts (1676,72): Cannot find name '_000'.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/toolbar/pdf-findbar/pdf-findbar-service.ts (3,2): Supplied parameters do not match any signature of call target.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/toolbar/pdf-paging-area/pdf-first-page/pdf-first-page.component.ts (15,19): Type 'ElementRef' is not generic.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/toolbar/pdf-paging-area/pdf-last-page/pdf-last-page.component.ts (15,19): Type 'ElementRef' is not generic.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/toolbar/pdf-rotate-page/pdf-rotate-page.component.ts (24,20): Type 'ElementRef' is not generic.
ERROR in C:/.../src/app/shared/components/extended-pdf-viewer/toolbar/pdf-rotate-page/pdf-rotate-page.component.ts (27,20): Type 'ElementRef' is not generic.

Do you think that the newest versions of the library doesn't support Angular 4?

**Comment by stephanrauh** [comment]
I'm not sure. It's possible I've carelessly added features of newer Angular versions. But that's not your problem.

Most error messages indicate you're using an old version of TypeScript. I'm aware you're stuck with that old version if you're Angular 4, so there's little you can do about it. I need to change the documentation: nowadays, running ngx-extended-pdf-viewer on Angular 4 requires not "a little effort" but "a lot of effort". I think it's still possible, but even so, I apologize for the trouble!

BTW, I've decided to raise the bar when Angular 12 is released. After that, ngx-extended-pdf-viewer requires Ivy, which amounts to using Angular 8 or above.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I've tagged the issue "won't fix", but if you continue to migrate the library to Angular 4, please keep me in the loop. I'll happily help you if you run into trouble.

If I were you, I'd give up after four hours, or eight hours at most. I believe it's possible to get the library up and running in this little timebox, but I can't promise it's possible.

**Comment by crlsmsq** [comment]
Thank you for your reply! Yeah I think its better for me to update my angular version then. Thank you :)
