### ISSUE TITLE
src input param should also be a byte array

### ISSUE THREAD

**Issue by AlexandrosG** [stephanrauh/ngx-extended-pdf-viewer#7]
Since PDFJs allows for the src to be either a string or a byte array, that should also be reflected in ngx-extended-pdf-viewer.

Related PDFjs lines:
https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L225-L229

**Comment by stephanrauh** [comment]
@AlexandrosG I assume you've found yourself out how to pass a byte array. Even so, is there something I can do to support developers? Should I add something to the documentation?

**Comment by AlexandrosG** [comment]
@stephanrauh Thanks for the reply and for putting this module together. I actually just passed the byte stream through the [src] parameter and there were no complaints and PDFJS recognized the source as a ArrayBuffer and rendered the PDF correctly.

I'm not sure if any changes are required. You can check the lines I linked above regarding what pdfjs accepts as input and maybe add some typings.
