### ISSUE TITLE
To Implement Singlepageviewer

### ISSUE THREAD

**Issue by Vigneshjana** [stephanrauh/ngx-extended-pdf-viewer#70]
I need to implement the singlepageviewer in my project using this library , Can anyone guide me how to implement .
Thanks in advance

**Comment by stephanrauh** [comment]
Related to #64.

**Comment by stephanrauh** [comment]
The extended PDF viewer is not a good tool to display a single page. Most buttons are useless if there's only one page. For example, you don't need the toolbar.

I suggest you have a look at how to implement it with HTML and JavaScript. There's an example at the Mozilla repository, so I assume that'll be easy: https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.html
