### ISSUE TITLE
Using a custom scale when on printing preview only works horizontally

### ISSUE THREAD

**Issue by MastaGumball** [stephanrauh/ngx-extended-pdf-viewer#700]
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? No.
- Does the bug also happen on https://pdfviewer.net/simple? Yes.
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template

**Describe the bug**
When on the print preview you want to use a custom scale to scale down the document for example, it seems like the scaling only happen horizontaly and not on the vertical axis.

**Version info**
- Version of ngx-extended-pdf-viewer: ^7.3.1

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser] : Chrome
 
**Smartphone (please complete the following information):**

**To Reproduce**

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to https://pdfviewer.net/extended-pdf-viewer/simple
2. Click on print icon
3. click on "More settings"
4. Select Custom on the Scale dropdown
5. input "50" for example
6. See the document being distorded

![image](https://user-images.githubusercontent.com/46004399/112146670-22551780-8bdc-11eb-8a27-7f6c0f5695f1.png)

![image](https://user-images.githubusercontent.com/46004399/112146796-47e22100-8bdc-11eb-8d30-1c8d8b006716.png)

**Comment by stephanrauh** [comment]
What a nasty bug! However, I believe there's an important bit of information missing. You say you can reproduce the bug on my showcase? Well, using Brave on MacOS, the preview doesn't look distorted (see screenshot below). But the demo doesn't have a "custom" option with an input field. I can select the pre-defined 50% option, or I can zoom to a couple of other settings. How did you manage to input the "50" setting using the keyboard? Or did I get you wrong?

Best regards,
Stephan

![image](https://user-images.githubusercontent.com/3045767/112213555-7d0f6300-8c1e-11eb-9581-df4b9582761e.png)

**Comment by MastaGumball** [comment]
Hello,

I think to reproduce, you have to select a printer (or a virtual printer). Then you will see the "More settings" button and then the scale option which can be set to custom.

I added a new screen to show you. I tested on Brave and Chrome on a Windows machine.

![image](https://user-images.githubusercontent.com/46004399/112222740-425ef800-8c29-11eb-9f21-f9b7722bcd80.png)

Kind regards,

**Comment by stephanrauh** [comment]
I see. That's a different scenario than I tried. I'm not sure I can reproduce it, but I'm going to try!

À la prochaine
Stephan

**Comment by stephanrauh** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/3045767/112372099-a5ab6180-8cdf-11eb-94ef-b46e224b3886.png)

**Comment by stephanrauh** [comment]
I've got an idea what's wrong and how to solve the bug. But I can't promise anything. Printing PDF files is a pain in the ass because it's hard to debug, and there are so many things that can go wrong.

**Comment by stephanrauh** [comment]
I went over the print CSS in version 9.0.0-alpha.0. It's an alpha version because fixing the print CSS probably breaks many workarounds - but your bug should be gone. Can you verify this, please?

Best regards,
Stephan
