### ISSUE TITLE
Menu View 

### ISSUE THREAD

**Issue by ArinaWik** [stephanrauh/ngx-extended-pdf-viewer#702]
Hey,

first of all thanks for the amazing tool.. 
I have one question regarding left-side menu (showing the content of pdf). 
Is it possible to open it by default when the viewer starts ?

Thanks .. 
<img width="200" alt="PDF Viewer" src="https://user-images.githubusercontent.com/29709450/112468811-0632b100-8d69-11eb-8fd3-9edb44384dbf.png">

**Comment by stephanrauh** [comment]
Yes, it is. Just use the attribute `[sidebarVisible]="true"`.

Best regards,
Stephan
