### ISSUE TITLE
Use URL type as pdf source

### ISSUE THREAD

**Issue by tomb353** [stephanrauh/ngx-extended-pdf-viewer#704]
Hi Stephan, 

first of all: you're doing a really nice job here! Thank you!

context: ngx-extended-pdf-viewer - version 8.x

I would like to use datatype URL for the pdf document to show. 
Currently that type is not supported directly. You can use URL.toString(), but not URL directly. 

Datatype is currently defined as:

_src: string | ArrayBuffer | Blob | Uint8Array | {
        range: any;
 };_

Request 
Support **datatype URL** for source attribute.

**Comment by stephanrauh** [comment]
The feature has landed with version 8.3.0. 

Oh, and thanks for all the kind words!

CU
Stephan
