### ISSUE TITLE
Issue pinching zoom in ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by son-nguyen-bmbsoft** [stephanrauh/ngx-extended-pdf-viewer#708]
Hi there,
I have some issues with pinching zoom on tablet ( Lenovo TB-8505X ) and multiple layer pdf.

https://user-images.githubusercontent.com/72724263/113104141-62df1180-922a-11eb-9464-8cd69aeae1c5.mp4
![image](https://user-images.githubusercontent.com/72724263/113104294-915cec80-922a-11eb-992c-64891136124e.png)

1. the lib cannot limit the range of 2 fingers and zooming too large ( percentage too large), while loosing control the pdf rendering 
2. as the similar reason above, I can limit the range of fingers in online, but I still cannot control it when going to offline (I am using PWA angular).
3. the lib renders url or base64 too slow

Please help me!
Thanks

**Comment by viet-nguyen-bmbsoft** [comment]
I have same issues

**Comment by viet-nguyen-izundo** [comment]
I have same issues and I tried [#669](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/669#issuecomment-790928358) way but it doesn't work

**Comment by doducbinh1995** [comment]
Hi, any one have solution for this?

**Comment by stephanrauh** [comment]
As for performance: are you using the service worker? You're using an attribute I've deprecated a long time ago, so maybe you're still following the old setup instruction. The bottom line is not to include the `pdf.worker.*.js` in the scripts section of the angular.json. Please compare the `angular.json` shown at https://pdfviewer.net/extended-pdf-viewer/getting-started with your version.

If that doesn't help: open your file at https://mozilla.github.io/pdf.js/web/viewer.html. If you're still suffering from performance issues, please report the issue at their bug tracker.

**Comment by stephanrauh** [comment]
As for pinching: I don't have your application, so I guess the best approach is to tell you how to solve the problem yourself. You can debug the code, test it with your real application, and tune it until it fits your need. I can do none of that.

Pinching is implemented in this class: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts

Copy this class to your project, make sure it's loaded, and disable the built-in pinch support (i.e. set `[enablePinchOnMobile]="false"`). The constructor of the class is Angular's `ngZone` object. I guess it's automatically injected if you convert the class to an Angular service.

Once you've done that, your copy of the class is responsible for pinching, and you can hunt down the bug.

**Comment by stephanrauh** [comment]
Side remarks:

- I wonder what the attribute `[id]` does. It's ignored by `ngx-extended-pdf-viewer`. The only effect is it's copied to the parent node of the PDF viewer. But apart from this, Angular ignores this attribute.
- Drop `delayOnFirstView`. It used to solve a couple of bugs, but nowadays, you don't need it.
- If you find the bug, it'd be nice to tell me so I can fix the library. :)

**Comment by son-nguyen-bmbsoft** [comment]
Okie thanks a lot. I'll test and confirm after that.

**Comment by stephanrauh** [comment]
I'll close the ticket because I don't see how I can do anything. However, I'd like to hear from you when you've solved the problem (or even if you didn't manage to solve it).
