### ISSUE TITLE
Pinch zoom event handlers don't get unsubscribed

### ISSUE THREAD

**Issue by jpxd** [stephanrauh/ngx-extended-pdf-viewer#712]
**Problem:**
When using pinch zoom on mobile, the event handlers for `touchstart`, `touchmove` and `touchend` are registered in `initializePinchZoom`. These event handlers should be unsubscribed in `destroyPinchZoom` but this does not work, as we subscribed with anonymous bound functions but try to unsubscribe the known unbound functions:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/bf698289c1307bf49093ce601f317ddb8cbf4cf9/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts#L107-L117

This leads to the execution of the pinch-zoom event handlers even after the PDF-viewer has been destroyed and is not in the DOM anymore. When the `onViewerTouchStart` handler tries to get the (not existing) viewer bounding rectangle it fails:
`null is not an object (evaluating 'document.getElementById("viewerContainer").getBoundingClientRect')`

**Solution:**
We have to keep copies of the bound functions around to unsubscribe them afterwards. See this for reference:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Specifying_this_using_bind

**Comment by jpxd** [comment]
I just opened a PR for this

**Comment by stephanrauh** [comment]
Indeed. It's strange I never saw this bug. Now that you've told me it's obvious!

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 9.0.0-alpha.2.
