### ISSUE TITLE
When scrolling and pinch-zooming simultaneously preventDefault can't be called

### ISSUE THREAD

**Issue by jpxd** [stephanrauh/ngx-extended-pdf-viewer#714]
**Problem when on a mobile device with pinch-zoom enabled:**
- Start to scroll using one finger
- Press second finger on touchscreen and start pinch-zooming
- Everything works from a users perspective, but the console (and the error tracker) is spammed with `Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

When already scrolling the touch events are not cancelable. This can be checked via the `event.cancelable` property (https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable).
Some browsers just seem to ignore calls to `event.preventDefault()` if the event is not cancelable but some throw an error.

**Solution:**
Checking is `event.cancelable` is true before calling `event.preventDefault()` in all three touch event handlers fixes the error message and scrolling and zooming still works.

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 9.0.0-alpha.2.
