### ISSUE TITLE
Flipbook feature

### ISSUE THREAD

**Issue by StephanScholz** [stephanrauh/ngx-extended-pdf-viewer#716]
I read in Issue #161 and #522 that you planned to implement a page turn effect for the pdf-viewer. I have found a great lib written in pure JS. No other dependencies (especially no jQuery). Maybe you could take a look at it:

[StPageFlip](https://github.com/Nodlik/StPageFlip)

Unfortunately I have no idea how to implement this on my own (different background, angular beginner). So I would greatly appreciate this feature to be added to the pdf-viewer.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Yeah, cool. First impression: that's the best library I've seen so far. Plus, I've learned a lot about pdf.js and I've begun to maintain my own fork of it, so it's a good time for a new attempt. Thanks for the hint!

However, it may take a while. At the moment, the bug tracker is a collection of tickets that aren't easily solved.

CU,
Stephan

**Comment by StephanScholz** [comment]
Hey Stephan (a great name btw!),

Don't worry about it too much. I just wanted to point it out for you.
Keep up the great work!

cu, Stephan

**Comment by stephanrauh** [comment]
The feature finally works flawlessly and fast.
