### ISSUE TITLE
Two-way binding of forms is broken with pdf.js 2.8

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#718]
https://pdfviewer.net/extended-pdf-viewer/forms promises two-way binding, but it's not there if you're using pdf.js 2.8.

**Comment by hiteshbhattarai** [comment]
@stephanrauh Been waiting for this long time. Is there any timeline how long will it take to fix.

**Comment by stephanrauh** [comment]
I expect to have more spare time soon, so the answer is "soon". I've already managed to solve part of the problem. `(formChange)` already works well. However, the values injected by `[form]` don't show in printed or downloaded PDF files. No ideas what's going wrong there, but I hope to fix that in the next one or two weeks.

**Comment by stephanrauh** [comment]
@hiteshbhattarai I'm getting closer. Input fields, text areas, and checkboxes work again. Dropdown menus and radio buttons are still broken. Stay tuned!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Multiple-Choice selections are broken, too.

**Comment by stephanrauh** [comment]
Todos left:
[ ] set the radiobutton when loading the PDF file
[ ] dropdowns 
[ ] Multiple-Choice field (only `(formData)` works, `[formData]` is broken)

**Comment by stephanrauh** [comment]
@hiteshbhattarai Please try the bleeding edge branch of version 9.0.0-alpha.9. I believe it repairs form support.

**Comment by stephanrauh** [comment]
Printing multiple choice fields is also broken in pdf.js. More to the point, it's an open ticket. Let's close this issue.

**Comment by stephanrauh** [comment]
The bug fix has shipped with version 9.0.0-alpha.9 in the bleeding-edge branch (which is becoming the default branch soon).

**Comment by hiteshbhattarai** [comment]
@stephanrauh  Thanks. Its working perfectly.

**Comment by stephanrauh** [comment]
Hooray! It was surprisingly difficult to fix this feature, so I'm happy to hear is does work now!
