### ISSUE TITLE
Open password protected pdf programatically

### ISSUE THREAD

**Issue by tanzl88** [stephanrauh/ngx-extended-pdf-viewer#72]
The current implementation requires human input to open a password protected pdf. It will be great if there is an input for password to open password protected pdf programmatically.

**Comment by stephanrauh** [comment]
Can you send me a password protected PDF? If possible, it should be public domain, so I can publish it with the showcase.

I've scanned the source code. Your request seems to be difficult, but not impossible. So I can't promise anything at the moment, but I'm positive to find a solution.

**Comment by tanzl88** [comment]
[Here you go](http://dreamcatcherdevelopment.com/encrypted-sample.pdf) 
Password: 123.

**Comment by stephanrauh** [comment]
Done! Using 0.9.28, you can use the attribute `[password]`.

**Comment by tanzl88** [comment]
Thanks! Will try it soon.
