### ISSUE TITLE
Hyperlinks not working on Presentation Mode (Full Screen)

### ISSUE THREAD

**Issue by kcbg18** [stephanrauh/ngx-extended-pdf-viewer#721]
So we are trying to use this package ngx-extended-pdf-viewer on viewing PDF Files, and the src of the PDF file contains hyperlinks which redirects to another link. The links are working when not in Presentation Mode, but links aren't working when in Presentation Mode (Full Screen). Tried searching how to fix it but not seeing any solutions on the net. Is there any configurations I missed?

**Comment by stephanrauh** [comment]
I'm afraid that's a feature, not a bug: https://github.com/mozilla/pdf.js/issues/7615

**Comment by stephanrauh** [comment]
I've tried to find out where links are disabled. I'm not 100% sure, but it seems that external links are blocked by the browser. It's a security feature. So I can't even offer you a workaround.

Best regards,
Stephan
