### ISSUE TITLE
Suggestion : pagesCount property

### ISSUE THREAD

**Issue by Jch71** [stephanrauh/ngx-extended-pdf-viewer#73]
[x] Suggestion : 

Hi, would it be possible to get the pagesCount property in the available attributes ? 

I'm currently working on a legal document signature, and we need the client to read the whole pdf, so i'm checking the current page and the pageCount.  

I'll be using window.PDFViewerApplication.pagesCount for now, but it would be great to have it natively within the directive

Thanks, And GOOD WORK !

**Comment by stephanrauh** [comment]
Thanks for the kind words!

The property is already there. I just forgot to document it. Actually, it's not a property, but an event that's sent when a document has finished loading. Have a look at the demo here: https://atapuerca.de (and click "pagesLoaded event").

**Comment by stephanrauh** [comment]
I've published a new version of ngx-pdf-viewer to npm. Basically, it only consists of an update to Angular 8.0.0.rc4, and it adds the forgotten documentation.
