### ISSUE TITLE
Prevent download and overwrite CTRL+S behavior

### ISSUE THREAD

**Issue by Marc-Hoch** [stephanrauh/ngx-extended-pdf-viewer#733]
I have a requirement to make a PDF non-downloadable.
When the user presses CTRL+S, I don't want a download to start, but I want to react to the event myself.

I would like an event on CTRL+S to execute a custom code and cancel the default download or not start it at all.

**Comment by stephanrauh** [comment]
Try using `[ignoreKeys]="['CTRL+S']"`. That should do the tricks. Here's the online demo:

https://pdfviewer.net/extended-pdf-viewer/keyboard

**Comment by securelyshare-shiva-kumar** [comment]
Can I override the functionality of download button?

**Comment by stephanrauh** [comment]
You can override the method `PDFViewerApplication.downloadOrSave()`. That's a hack, but I don't think this method is going to change any time soon. 

If you want to play it safe, implement a custom toolbar with your own download button. Overriding the `CTRL+S` key requires `[ignoreKeys]="['CTRL+S']"` and registering your own key listener (something like `@HostListener('window:keyup', ['$event'])`).
