### ISSUE TITLE
Radio button's value is not captured in a specific pdf with fillable form 

### ISSUE THREAD

**Issue by bdhanoa** [stephanrauh/ngx-extended-pdf-viewer#736]
Radio button's value is not being captured in the following pdf file.

[Fillable Form.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/6393462/Fillable.Form.pdf)

I am using [(formData)] two way binding:

  <ngx-extended-pdf-viewer [base64Src]="pdfContents" [height]="'calc(100vh - 252px)'" [useBrowserLocale]="true"
    [(formData)]="formData" [logLevel]="5">
  </ngx-extended-pdf-viewer>

Form as rendered:

![image](https://user-images.githubusercontent.com/50592406/116443291-7aa5b780-a821-11eb-9f7a-3843fe0884c9.png)

radio button selection is missing (showing as 0 : null ) in formData after the form is filled:

![image](https://user-images.githubusercontent.com/50592406/116443262-6feb2280-a821-11eb-952c-443ff75f9e17.png)

Following are the properties of the radio button field:

![image](https://user-images.githubusercontent.com/50592406/116444599-e2103700-a822-11eb-916d-c7dbab85bc9a.png)

Please help.

**Comment by stephanrauh** [comment]
Which version of ngx-extended-pdf-viewer are you using? If I'm not mistaken, forms are broken since I updated to pdf.js 2.7.

**Comment by bdhanoa** [comment]
@stephanrauh, Thank you very much for looking at it. 

I am using ngx-extended-pdf-viewer version 8.3.0. 

Forms are working just fine, except this file and this radio button. Radio buttons do work with other pdf files.

**Comment by stephanrauh** [comment]
That's surprising. I suspected the bug might be related to #677 or #718. But your error description rules this out.

**Comment by bdhanoa** [comment]
yes, this is happening in the current version of Google Chrome on a windows 10 machine.

**Comment by stephanrauh** [comment]
I've fixed the bug with version 9.0.0-alpha.9 in the bleeding-edge branch (which is soon become the stable branch).

**Comment by bsdb** [comment]
Thank you very much.

**Comment by bdhanoa** [comment]
Thank you very much @stephanrauh.

**Comment by stephanrauh** [comment]
You're welcome! Don't hesitate to tell me if something doesn't work. Or even if everything works. :)
