### ISSUE TITLE
Add github release

### ISSUE THREAD

**Issue by Elikill58** [stephanrauh/ngx-extended-pdf-viewer#754]
**Describe the solution you'd like**
I would like that for each next release that you will make, you create a new release to make them appear here:
![image](https://user-images.githubusercontent.com/17381066/117770969-e3cff680-b235-11eb-9d44-d9205fde8fc4.png)

It can be very useful to get all version or see old version changelog.

**Comment by Elikill58** [comment]
> I've never seen this black page before. What is it?

It's github in dark mode, you can get it in your settings then appearance.


I understand that you don't want to lose time with this type of action. Such as github know this, it's very fast to do a release. I suggest you to just copy/paste the NpmJS changelog or directly write link to changelog when you do a version.

I think it can be very usefull for major version.

Also, if you really don't want to create release, I suggest you to just add tag. Each time that you do a release, a new tag is created. The big advantage with tag is you can create it just while commiting with the `-a` option.
Here you can find help for it: https://git-scm.com/book/en/v2/Git-Basics-Tagging

But thanks you for your reply !

**Comment by stephanrauh** [comment]
I guess it's possible to automate tagging. I could add this to the script I'm using to publish a new version. Maybe it's even possible to automate the GitHub release.

**Comment by stephanrauh** [comment]
I think I've found a good compromise. Tags are automatically created with every npm. Converting this to a GitHub release is a matter of a few minutes.
