### ISSUE TITLE
Cannot use multiple instances in an application

### ISSUE THREAD

**Issue by doovewado** [stephanrauh/ngx-extended-pdf-viewer#758]
All the selectors have hard-coded element ids, all changes applied to properties effect the first instance only.

**Comment by stephanrauh** [comment]
That's true. But it's only the beginning. The base library, pdf.js, uses global variables. I consider it more or less impossible to support multiple instances. In theory, I could modify pdf.js, but even if I had enough spare time - after that it's very difficult to merge the latest changes of pdf.js.

So I'm afraid I can't help you.

Best regards,
Stephan

**Comment by doovewado** [comment]
Hi Stephan

Thanks. I didn't realise how deep the problem went.

**Comment by stephanrauh** [comment]
Yeah. It's a pity. You can try this library: https://www.npmjs.com/package/ng2-pdfjs-viewer. It's using iFrames, so it should be no problem to display multiple PDF files on the same file.

As far as I can see, the author is still maintaing the library. At the moment, it's using a slightly older version of pdf.js, but nothing to worry about. Unless you need forms, it should do the trick.
