### ISSUE TITLE
XFDF/FormsData/Annotations are not rendered

### ISSUE THREAD

**Issue by Lindvorn** [stephanrauh/ngx-extended-pdf-viewer#766]
**Describe the bug**
I have a pdf with filled values. The values are not visible when I load pdf. On mozilla it works fine, when I open pdf using this viewer then text boxes are empty.
[document (5).pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/6535174/document.5.pdf)
I'm using bleeding edge (2.8) since in 2.7 two way binding is broken
**Version info**
"ngx-extended-pdf-viewer": "^9.0.0-alpha.7"

**Comment by stephanrauh** [comment]
Just to make sure we're talking about the same document - when I open your document, only the first field is filled, and it contains the number 11. The other fields are empty. Is this correct?

**Comment by Lindvorn** [comment]
Yes. In mozilla it shows '11'. In the demo for the viewer (ver 2.8) the value is not there

**Comment by stephanrauh** [comment]
I haven't committed the bug fix yet, but I've managed to solve the isssue. Thanks for pointing it out!

**Comment by stephanrauh** [comment]
Solved with version 9.0.0-alpha.9.

**Comment by Lindvorn** [comment]
Pdf now renders just fine, thank you.
But now I see another issue with formDataChange event.
When I change any field the event contains only changed data. My meaning is that before the formData was initialized and filled with initial values and all values where passed in the event. Now only changed values are passed.
In the current example/pdf above, when I change page 2 then formDataChange event will contain only info for page 2 but filled value on page 1 is missing in the event.
Is this a bug or is this how event now works?
