### ISSUE TITLE
Printing function doesn't work, sends empty file

### ISSUE THREAD

**Issue by FabySosaD** [stephanrauh/ngx-extended-pdf-viewer#77]
I have a problem when I try to print the PDF, send me a empty document

I get this warning

>>>>>>>>>>>>>>>>>

Warning: Setting up fake worker.
viewer.js:1423 PDF d3f3bc76ae0abb9e32dbb65b128abd9f [1.3 FPDF 1.81 / -] (PDF.js: 2.1.266)

>>>>>>>>>>>>>>>>>

Can you help me?

**Comment by stephanrauh** [comment]
Just ignore the warning. As far as I know, there's a path missing - but that path doesn't seem to be crucial. One day or another, I'd like to get rid of the warning nonetheless.

As for printing: can you send me a reproducer, please?

**Comment by stephanrauh** [comment]
You may also want to check version 0.9.34. It's unlikely, but it may solve the problem.

**Comment by FabySosaD** [comment]
I can´t do a reproducer, sorry, but my problem is that when I send a base64 pdf to show, it's works but when I try to print don't work, I can't see the content of the  pdf in the printing window

Have you had this problem?

**Comment by stephanrauh** [comment]
I wonder if you bug is related to #83 (printing works, but not on iPads and iPhones). Which operating system do you use? If you're using a different OS or a different browser, is it still broken?

**Comment by agiratech-nithin** [comment]
I am also having the same problem. I am using Windows 10. When I am trying to print page, it is coming as empty.

**Comment by nithincn89** [comment]
I am also facing the same issue. I am using windows 10. When I am trying to print a page, Its coming as empty. Please help me to sort it out.

**Comment by stephanrauh** [comment]
@nithincn89 Can you open and print the document on https://pdfviewer.net/simple, please? If the problem shows there, too, please check if it also happens with my demo documents.

**Comment by stephanrauh** [comment]
@nithincn89 Are you using a base64 file or a regular PDF file?

**Comment by nithincn89** [comment]
@stephanrauh Thanks for your response. Here I am getting PDF file from server and I am just passing it to the 'src' attribute. Also, can you please guide me on how to run my PDF file on https://pdfviewer.net/simple ?

**Comment by stephanrauh** [comment]
Open the PDF file in your application, download it using the "download" button, save it as a file to your desktop and open that file on pdfviewer.net. This way we can check if something's wrong with the PDF file. Printing it via https://mozilla.github.io/pdf.js/web/viewer.html is also worth a try - that's the reference implementation, so we learn if the error is in my library or if it's in the base library.

**Comment by nithincn89** [comment]
@stephanrauh I checked the way you explained. Printing is working fine. I think printing the PDF file after downloading is not causing any problem. Direct printing from the library causing the issue. Hope you can sort it out.

**Comment by nithincn89** [comment]
@stephanrauh Any updates on this issue?

**Comment by stephanrauh** [comment]
Not yet. I was busy with another issue. I'm assuming you're using the `[base64Src]` attribute?

As the next step, I'll add a base64 demo to the showcase on pdfviewer.net. I hope you - or even better, I - can reproduce the bug this way. The base64 demo on [the core project](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/src/app/app.component.html) works well, at least on Firefox and my Macbook.

**Comment by stephanrauh** [comment]
@nithincn89 I've added the base64 demo (https://pdfviewer.net/base64). I still don't see any problems with printing. Can you send my a reproducer, please?

**Comment by RojasAB** [comment]
printing have issue in ios and android when using base64, for pdf i didn't test it

**Comment by stephanrauh** [comment]
@RojasAB The iOS bug is already covered in #83. I didn't know it also occurs with Android. Probably the same bug. This ticket (#77) deals with the desktop environment. Several developers report printing is broken on Windows, but it isn't on my copy of Windows 10. So I'm still clueless.

**Comment by skizdigidy** [comment]
I am running Windows 10 in Chrome using version npm version 1.0.0-rc.1 and for me only the last page is printed.  If I try to explicitly tell it to print page 2-3 of a 4 page document, it tells me it's out of range.  Basically no matter how many pages there are in the pdf, the print dialog only thinks it's one page (The last one). 

I've tried using `[base64Src]` and `[src]` and both act the same way.

**Comment by stephanrauh** [comment]
@skizdigidy 

- What happens when you print the same PDF file with https://mozilla.github.io/pdf.js/web/viewer.html? That's basically the same library, but without Angular.
- Can you reprocude the bug on https://pdfviewer.net/simple?
- Does this happen with other PDF files, too?

**Comment by hottabych07** [comment]
@stephanrauh 
I also got this problem. When I click on the print button, I get a blank page, all this I do in my project (Angular 7). And when I create a new project, everything works fine. What can influence this? Please tell me, I’m doing everything according to the instructions, maybe there are any individual settings?

**Comment by stephanrauh** [comment]
@hottabych07 That's both unexpected and exciting. It's the first time I see light at the tunnels end.

Honestly, I don't have any clue what's causing the problem. But your report is the first opportunity to find the reason. Just to be sure: both of your projects are using the same browser, the same version of ngx-extended-pdf-viewerr, the same printer, the same printer driver, and the same version of Angular?

If that's true, let's compare the two projects file by file. There must be a difference. I'd do it myself, but of course I don't have access to your project, so all I can do is to beg for a reproducer. :(

I'm looking forward to your reply! And I'm keeping my fingers crossed - I'd really love to find the root cause of this bug!

**Comment by hottabych07** [comment]
@stephanrauh 
Wow, I solved this problem. It was all that Bootstrap was still connected to me, when I turned it off everything became normal, but there is a nuance, now all pages except the first are visible. Any suggestions on this?

**Comment by stephanrauh** [comment]
Please have a look at #148. Your bug may have been cause by something like `overflow-y: hidden`. That particular bug has been solved with version 1.5.3. However, I guess there are many similar scenarios. The PDF viewer assumes that the entire PDF file is visible in print mode. Optimizing the layout for the desktop or mobile screen often involves clipping the content. As a side effect, printing is broken.

**Comment by b-mi** [comment]
Hello, I've test https://pdfviewer.net/extended-pdf-viewer/blob on current android - preview show empty page and print empty page.

**Comment by stephanrauh** [comment]
@b-mi Do you see any error message in the console window? Does the preview show on the other pages of the showcase?
