### ISSUE TITLE
formDataChange event contains only new values

### ISSUE THREAD

**Issue by Lindvorn** [stephanrauh/ngx-extended-pdf-viewer#771]
Issue with formDataChange event.
Version: 9.0.0-alpha.11, bleeding-edge
When I change any field the event contains only changed data. Old behavior was the formData was initialized and filled with initial values and all values where passed in the event. Now only changed values are passed.
In the current example/pdf, when I change page 2 then formDataChange event will contain only info for page 2 but filled value on page 1 is missing in the event.
Is this a bug or is this how event now works?
[document.5.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/6561730/document.5.pdf)

**Comment by stephanrauh** [comment]
You're right, it's a bug.

**Comment by stephanrauh** [comment]
The bug fix has landed with version 9.0.0-rc.2.
