### ISSUE TITLE
Text selection is broken on some pdfs with bleeding-edge pdf.js

### ISSUE THREAD

**Issue by Lapoinol** [stephanrauh/ngx-extended-pdf-viewer#776]
**Describe the bug**

I've noticed that if you use pdf.js 2.9 on ngx-extended-pdf-viewer 9.0.0-rc.1, text selection on some documents is broken. It's too bad, because version 2.9 fixed some other issues I had with missing spaces on selected text. You can see the problem on the "export text or image" section of the showcase (you have to select 2.9/bleeding edge version) : https://pdfviewer.net/extended-pdf-viewer/export. 

Thanks for all the work you're doing on this library. It's much appreciated! If I had any idea on how to fix this, I would try to contribute, but I'm stumped.

**Version info**
- ngx-extended-pdf-viewer 9.0.0-rc.1 (pdf.js 2.9)

**Desktop (please complete the following information):**
 - Chrome & Firefox on OS/X

**Comment by stephanrauh** [comment]
What a strange bug! Text selection works, but the text layer snippets are rendered at the wrong position.

![image](https://user-images.githubusercontent.com/3045767/120066037-dbb8e900-c074-11eb-9c5c-1a75453f1d19.png)

**Comment by stephanrauh** [comment]
Turns out it's a CSS problem. Before publishing the bug fix, I'll check if the bug fix breaks the default branch of pdf.js.

**Comment by Lapoinol** [comment]
Thank you so very much!

**Comment by stephanrauh** [comment]
Activating and deactivating "mark long words" on the https://pdfviewer.net/textlayer confuses the layout.

![image](https://user-images.githubusercontent.com/3045767/120077021-8dbdd880-c0a8-11eb-890c-1dc4af818ba8.png)

**Comment by stephanrauh** [comment]
The bug fix has landed with version 9.0.0-rc.2.

**Comment by Lapoinol** [comment]
Thanks again!
