### ISSUE TITLE
A questionable page opens

### ISSUE THREAD

**Issue by InfaSysKey** [stephanrauh/ngx-extended-pdf-viewer#784]
Good morning everyone.

Doing some research to include pdf.js in IE, I was brought to this page and found a "broken" link. The link takes you to a betting page.

[https://pdfviewer.net/extended-pdf-viewer/alternatives ](https://pdfviewer.net/extended-pdf-viewer/alternatives)

Photo:
![image](https://user-images.githubusercontent.com/37089170/120351235-ff439400-c2ff-11eb-89b2-bf619d8dbec1.png)

Reeegards!

**Comment by stephanrauh** [comment]
Oh. Thanks for pointing this out. That's definitely not the kind of web site I want to promote!

**Comment by stephanrauh** [comment]
I've published a new version without any offending link. 

¡Gracias de nuevo! Hay sorpresas que no me gustan...

Best regards,
Stephan
