### ISSUE TITLE
Building with custom version of pdf.js not working

### ISSUE THREAD

**Issue by adambeer** [stephanrauh/ngx-extended-pdf-viewer#792]
I have followed the steps listed here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md

But my changes are not taking affect. Specifically I made a change in mypdf.js/web/pdf_find_controller.js and confirmed it worked by running gulp server (step 7 of the bottom task). However after copying the newly compiled ngx-extended-pdf-viewer folder from the dist folder to my node_modules folder in my project, the changes I made wernt working anymore.

Am I missing something here?

**Comment by adambeer** [comment]
As a reference, I posted tan issue on the pdf.js repo about the change I was trying to make:

https://github.com/mozilla/pdf.js/issues/13496

**Comment by stephanrauh** [comment]
Weird. The walk-through seems to be pretty up-to-date. Usually I use `npm run showcase` or `npm run issue`, which copy the library to another project. You could modify one of these scripts to copy the library to your project. Alternatively, you can use `npm link` (and tell me how to do that - for some reason, I've been to lazy to examine that, although I'm sure it'd make my life easier).

Currently, this boils down to three steps:

- `./updateMozillasPdfViewer.sh`
- `npm run showcase`
- `ng s -o` (in the showcase folder)

**Comment by stephanrauh** [comment]
I haven't made up my mind yet, but I guess adding a programmatic API to highlight search results without scrolling is a good idea.

**Comment by stephanrauh** [comment]
I'm afraid ngx-extended-pdf-viewer isn't compatible with the original Mozilla pdf.js library. My fork features roughly 100 bug fixes and improvements. For example, I've added additional fuzzy search.

**Comment by stephanrauh** [comment]
I'm confused you had to rename the files. They are renamed automatically by `add-version-number.js`. Which files did you copy? The correct set of files to copy is in the directory `projects/ngx-extended-pdf-viewer/assets` and `projects/ngx-extended-pdf-viewer/bleeding-edge`.

![image](https://user-images.githubusercontent.com/3045767/120891768-a3805000-c60a-11eb-933a-100e1440ade4.png)
