### ISSUE TITLE
The `height` attribute works only first time

### ISSUE THREAD

**Issue by kemsky** [stephanrauh/ngx-extended-pdf-viewer#796]
**Describe the bug**
Hi! We use viewer in a popup and use `[height]` input parameter to set component height to 100%, but it works only on first open, next time height is changed to pixel value for some reason. Looks like it has something to do with `minHeight`.

```typescript
  public checkHeight(): void {
    if (typeof document !== 'undefined') {
      const container = document.getElementsByClassName('zoom')[0] as HTMLElement;
      if (container) {
        //   --> container.clientHeight === 0 is true 
        if ((this.autoHeight || container.clientHeight === 0) && this._height.includes('%')) {
          this.autoHeight = true;
          const available = window.innerHeight;
          const rect = container.getBoundingClientRect();
          const top = rect.top;
          let maximumHeight = available - top;
          // take the margins and paddings of the parent containers into account
          let padding = this.calculateBorderMarging(container);
          maximumHeight -= padding;
          const factor = Number(this._height.replace('%', ''));
          maximumHeight = (maximumHeight * factor) / 100;
          if (maximumHeight > 100) {
            this.minHeight = maximumHeight + 'px';
          } else {
            this.minHeight = '100px';
          }
        }
      }
    }
  }
```

**Version info**
- "ngx-extended-pdf-viewer": "9.0.1"

**Comment by stephanrauh** [comment]
Sounds like a plausible explanation. I'll have a look.

**Comment by stephanrauh** [comment]
I've implemented a reproducer (https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue-796-modal-height-100-percent).

**Comment by stephanrauh** [comment]
Good new! Updating to version 10.0.0-alpha.7 fixes the problem.

If using an alpha version is a problem to use (as it should!): please run a test with this version nonetheless. The final release of version 10.0 is scheduled for the next two weeks. Currently, I'm collecting new features to justify the new version number.
