### ISSUE TITLE
Find feature generate chunked highlights

### ISSUE THREAD

**Issue by jeremylanglois** [stephanrauh/ngx-extended-pdf-viewer#797]
**Description**

The find and highlight feature seems to suffer from regression with the new pdf.js version (2.9).
Find feature generate an highlight that does not match the text that was searched.
The highlight of the search term looks like discontinued chunks.
I tried to PDF.js demo but could not really reproduce the issue.

**Version info**
Angular 9 (The showcase shows the same symptoms with Angular 12)
PDF.js 2.9 (As far as I can tell, it was working fine on Angular 8 / PDF.js 2.7 and the 8.3.0 of the lib)
Ngx-extended-pdf-viewer 9.0.1

**Desktop (please complete the following information):**
 - Chrome 91.0.4472.77
 - Firefox 89.0
 
**To Reproduce**

1. Open the PDFShowcase
2. Go to the "Find programmatically"
3. Make sure all options are unchecked
4. Search for the sentence: **_approaches to the teaching of beginning Portuguese._**

**Screenshots**

Chrome:

![image](https://user-images.githubusercontent.com/13545067/121084883-2a6e2d80-c7af-11eb-8ed1-f46f69d789b4.png)

Firefox:

![image](https://user-images.githubusercontent.com/13545067/121086442-26dba600-c7b1-11eb-9793-15ba988c878b.png)

PDF.JS Demo viewer with no issue (even if we can clearly see a discontinuation in the highlighting block)

![image](https://user-images.githubusercontent.com/13545067/121087609-afa71180-c7b2-11eb-806c-2a7c3120c5d4.png)

**Additional context**

- It looks like the highlight is divided over several span instead of div (begin , middle,...,middle, end).
- Span with the tag begin and end looks like they are properly positioned.
- Span with middle tag looks always wrongfully placed (left and top value looks coherent)
- Middle Span are not nested in a child Span like Begin and End. Class and embedded Style might be clashing since they are at the same level ??

![image](https://user-images.githubusercontent.com/13545067/121086293-fa278e80-c7b0-11eb-833a-038efd405141.png)

Let me know if there is anything else I can test/communicate and a big thanks for your work on the library !

**Comment by stephanrauh** [comment]
Whow - you've spent a lot of time investigating the topic. Merci beaucoup!

At the moment, I'm at a loss. But I've got an inkling what's going on. pdf.js has improved the text layer with version 2.9. Maybe this also means new bugs. What happens if you run the same search on their showcase? I.e. on https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by jeremylanglois** [comment]
Thanks for getting back quickly !

Sorry it might have been confusing, the 3rd screenshot in my post is using their demo viewer:

![image](https://user-images.githubusercontent.com/13545067/121092185-2c3cee80-c7b9-11eb-8b95-784b2131662d.png)

It does seem to work, even if we can notice that the height of the highlighting block changes from word to word.

We noticed the issue on pdfs (which I can't share ) where we searched for multiline sentences. Basically the begin block is on the first sentence, end block on the last sentence and then we have the middle blocks lost on the page. It is a tiny bit better when we reintroduced the nesting on the "middle" span blocks.

**Comment by stephanrauh** [comment]
Marking text is also affected:

**Comment by stephanrauh** [comment]
The text layer is rendered at weird places. The word marked blue is "teaching":

![image](https://user-images.githubusercontent.com/3045767/121235843-975bf300-c895-11eb-8893-ee318a02411d.png)

**Comment by stephanrauh** [comment]
As it turns out, the culprit was a simple CSS rule.

**Comment by stephanrauh** [comment]
The bugfix has landed with version 9.0.2. Please run a test and tell me about it. I'm only 95% sure I've fixed the bug because I don't understand what causes the bug.

Best regards,
Stephan

**Comment by jeremylanglois** [comment]
Sorry for the delay and thanks for the fix, it indeed solves the problem.

**Comment by stephanrauh** [comment]
Hooray!
