### ISSUE TITLE
Toolbar of the ngx-extended-pdf-viewer is not visible when pdf is landscape (width > height)

### ISSUE THREAD

**Issue by parth23p** [stephanrauh/ngx-extended-pdf-viewer#809]
(no further description)

**Comment by stephanrauh** [comment]
I'm afraid I can't reproduce your bug. When I a landscape PDF in the showcase, the toolbar is there:

![image](https://user-images.githubusercontent.com/3045767/123551085-8d306480-d770-11eb-9747-a2fadd781b9f.png)

Can you send me a reproducer, please?

**Comment by parth23p** [comment]
Dear Stephan Rauh,

Good Day,

As I was debugging the issue, I came to know that in base_viewer.js file
the function _setScale(val, this.pageViewMode === "single") , shifts the UI
of my webapp to leftwards , and I wanted pageviewmode="multiple".And also
shifts UI leftWards when I click on showSidebarButton.

So could you fix that thing , too. And about the code, I can't disclose
code as I am bound to the company's data privacy policy.

I hope that you will understand my issue.Waiting for your reply.

Best regards,
Parth Patel

**Comment by stephanrauh** [comment]
Well, I didn't ask for your confidential source code. They are none of my business, so I don't even want to see them (unless your employer or customer is willing to contribute to the showcase of demo applications I'd like to create).

A reproducer is a small, minimal application that can be installed without further ado. Real-world applications usually contain a lot of irrelevant source code, so they are of little value when hunting a bug.

I'm afraid I still don't know how to reproduce the bug. Does it happen on desktops PCs and laptops, too? Or is it a mobile-only bug?
