### ISSUE TITLE
Need page-rendered event

### ISSUE THREAD

**Issue by Charles1972** [stephanrauh/ngx-extended-pdf-viewer#81]
Hi, 

could you implement the "page-render" event?
Actually there is only the "pages loaded" event, but when this event is fired not all pages are rendered and in my case it's very important to have it.

thanks in advance

**Comment by stephanrauh** [comment]
Version 0.9.32 ships your feature. Enjoy!

**Comment by Charles1972** [comment]
Thanks!

**Comment by Charles1972** [comment]
Thanks! :)
