### ISSUE TITLE
Elvis operator missing

### ISSUE THREAD

**Issue by halufa** [stephanrauh/ngx-extended-pdf-viewer#818]
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/3f5c28930aa3fca9dc52f3285c87ba60fd685ec9/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1490

You forgot to put the Elvis operator here.

It should also be: PDFViewerApplication.pdfDocument?.annotationStorage?.resetModified();

Thanks

**Comment by stephanrauh** [comment]
Right you are! I've published the bugfix as version 9.0.5.

BTW, the question mark behind `document` is almost certainly superfluous - but it doesn't hurt, and there might by situations where there's no document, especially when the component is destroyed, so I've added it, just in case.
