### ISSUE TITLE
thumbnailView: links instead of pictures

### ISSUE THREAD

**Issue by adamabdulaev** [stephanrauh/ngx-extended-pdf-viewer#826]
Hey! I am creating a custom sidebar and I was able to change it significantly to suit my design. However, the only point I cannot fix is ​​displaying text links to pdf Documents pages instead of pictures. Is it possible to do this somehow?
![image](https://user-images.githubusercontent.com/84326043/124626375-47b61a80-de87-11eb-9705-23560de6b859.png)
It looks like this now (first screen):

![Screenshot_1](https://user-images.githubusercontent.com/84326043/124627220-0bcf8500-de88-11eb-9692-1b7273df6c54.png)
I need a result like this (second screen):

P.S. sorry for the crossed-out text, some things I cannot show, as this is a commercial project.

**Comment by stephanrauh** [comment]
Did you already find https://pdfviewer.net/extended-pdf-viewer/custom-thumbnails?

I don't think you can omit the image container of the code snippet below, but I'm pretty sure you can hide it (`<div class="image-container" style="display:none">`). The click listener is added to the surrounding anchor tag, so just adding your text near the image should be everything you need to do.

```html
<ng-template #radiobuttonThumbnail>
  <a class="pdf-viewer-template">
    <div class="thumbnail" data-page-number="PAGE_NUMBER">
        <input id="thumbnail-cbx-$page"
        class="thumbnail-radiobutton"
        type="radiobutton"
        style="top: 80px;right: 25px;position: relative;transform:scale(1.5)"
        onClick="window.PDFViewerApplication.page=PAGE_NUMBER;window.updateThumbnailSelection(PAGE_NUMBER)">
        <div class="thumbnailSelectionRing" style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING; display: contents">
          <div class="thumbnail-text" style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING;margin-bottom: -HEIGHT_OF_RING">
          </div>
          <div class="image-container">
            <!-- image is automatically inserted here -->
        </div>
      </div>
    </div>
  </a>
</ng-template>
```

**Comment by adamabdulaev** [comment]
> Did you already find https://pdfviewer.net/extended-pdf-viewer/custom-thumbnails?
> 
> I don't think you can omit the image container of the code snippet below, but I'm pretty sure you can hide it (`<div class="image-container" style="display:none">`). The click listener is added to the surrounding anchor tag, so just adding your text near the image should be everything you need to do.
> 
> ```
> <ng-template #radiobuttonThumbnail>
>   <a class="pdf-viewer-template">
>     <div class="thumbnail" data-page-number="PAGE_NUMBER">
>         <input id="thumbnail-cbx-$page"
>         class="thumbnail-radiobutton"
>         type="radiobutton"
>         style="top: 80px;right: 25px;position: relative;transform:scale(1.5)"
>         onClick="window.PDFViewerApplication.page=PAGE_NUMBER;window.updateThumbnailSelection(PAGE_NUMBER)">
>         <div class="thumbnailSelectionRing" style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING; display: contents">
>           <div class="thumbnail-text" style="width: WIDTH_OF_RING; height: HEIGHT_OF_RING;margin-bottom: -HEIGHT_OF_RING">
>           </div>
>           <div class="image-container">
>             
>         </div>
>       </div>
>     </div>
>   </a>
> </ng-template>
> ```

This is exactly the answer I was looking for. Thank you!

**Comment by stephanrauh** [comment]
Awesome! Do you think it's a good idea to add a demo to the showcase?
