### ISSUE TITLE
ability to highlight text custom text

### ISSUE THREAD

**Issue by shessafridi** [stephanrauh/ngx-extended-pdf-viewer#828]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my boss asks me to implement highlighting text inside the PDF

**Describe alternatives you've considered**
Searching for the text programmatically but also has the added effect of scrolling to the text

**Comment by shessafridi** [comment]
@stephanrauh

**Comment by stephanrauh** [comment]
I could talk to your boss? :)

Jokes aside, this sounds like a sensible request. But I don't have a clue what a useful API might look like. Any suggestions?

**Comment by stephanrauh** [comment]
BTW, you can implement the feature yourself. You have to activate the text layer and to capture the event `(pageRendered)`. Locate the page that has just been rendered in the DOM. Find the textlayer, and find the `DIV` or `SPAN` you want to highlight. Now you can highlight it using a CSS class or an inline `style`.

**Comment by shessafridi** [comment]
In my app, the user has to select the text they want to highlight, so I have to work with the getSelection API but it's a bit difficult because the selection could start from between the span and I could not highlight the entire span because I only need to highlight the characters selected by the user and I am really struggling with it, and that's just the highlighting I also have to store this state on the server and render the viewer using it.

**Comment by stephanrauh** [comment]
@shessafridi I agree it's a bit annoying that the `<span>` tags are scattered around the text sort of randomly. But there's little I can do about it. That's just how pdf.js works. Plus, I believe the guys who've implemented the text layer have invested a lot of time until they managed to position the `<span>` tags correctly. Feel free to submit a pull request to https://github.com/mozilla/pdf.js if you've got a good idea how to do it better. I'm sure the team will appreciate it. But I'm afraid it's one of the hard problems.

**Comment by stephanrauh** [comment]
If that's still a topic, have a look at the new find demo I've implemented: https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/f23ece50729739f65d1f1e06139eb868ddc4fee1/src/app/extended-pdf-viewer/find/find.component.ts#L178

It deals with the divs, so maybe there's something solving your issue.
