### ISSUE TITLE
Printing is broken on iOS

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#83]
Reported at [StackOverflow](https://stackoverflow.com/questions/55462224/printing-using-ngx-extended-pdf-viewer-on-ios-and-mobile-safari-or-chrome) by Scott Garret.

Steps to reproduce: open the demo on an iPad and click the "print" button. The preview dialog opens, showing nothing but a single blank page.

The discussion on Mozilla's GitHub has several suggestions how to solve the bug: https://github.com/mozilla/pdf.js/issues/7597

**Comment by stephanrauh** [comment]
Nobody has upvoted this ticket for a long time, so I believe nobody uses the PDF viewer to print on an iOS device. Hence I'm closing this ticket now.

**Comment by digaus** [comment]
> Nobody has upvoted this ticket for a long time, so I believe nobody uses the PDF viewer to print on an iOS device. Hence I'm closing this ticket now.

I am using it on Android and iOS, both showing only blank pages :/

**Comment by stephanrauh** [comment]
Oh - not that nasty bug again! I've spent countless evenings trying to figure out what's going on.

On the other hand, I've learned a lot about pdf.js in the meantime, so I'm ready to have a look at it again. I can't promise you to solve the bug. But I can promise to try.

**Comment by kisimediaDE** [comment]
Upvote for print on iOS - I want to integrate this in an Ionic App

**Comment by stuartpaulin** [comment]
Same here, I'm very grateful for this tool, currently viewing using it and it is working on iphone in an ionic app, but download and printer button missing - think it is a cors issue... bit confused.. I'm a junior dev in that respect!

**Comment by mt-webdev** [comment]
> 

For us (Capacitor app) the download butotn is working, you could take another look at your code probably :)

@stephanrauh would you be open to a PR? You mentioned you already dived into pdf.js, not sure if I could help out, but could try.

**Comment by stephanrauh** [comment]
@mt-webdev Of course I'm open to pull requests!

**Comment by stephanrauh** [comment]
I've read the discussion of https://github.com/mozilla/pdf.js/issues/7597 again and added a timeout specifically for iOS. It seems to work. The only problem is I don't have any clue what's going on - and to my experience, that's a bad when fixing bugs.

Be that as it may, please try version 13.5.3 and tell me if it solves the bug on your devices, too.

**Comment by stephanrauh** [comment]
I didn't hear from you for two weeks, so I assume my bugfix works on your machine, too.

**Comment by digaus** [comment]
Was in vacation for two weeks so did not test it yet 🙈

**Comment by stephanrauh** [comment]
Enjoy your vacations - or the week-end if it's already over! Closing tickets is basically a matter of house-keeping. It feels better to have to short list. :) But I'm still listening to this channel, just add your insight as a new comment.

**Comment by mt-webdev** [comment]
I will take a look in the upcoming week (also was on vacation 😅). Looking forward to it!

**Comment by can2000ca** [comment]
@stephanrauh Thanks for your comments.

I used the print button of the PDF viewer's toolbar.

Here is what I did:
open this link from iPad Safari:
https://mozilla.github.io/pdf.js/web/viewer.html
Open any PDF file
Print (use the print button of the PDF viewer's toolbar.)

**Comment by stephanrauh** [comment]
I see. I've managed to reproduce the bug. It's interesting that Safari prints the file correctly on the Laptop, but fails to do so on the tablet.

The pdf.js team have ceased to support Safari. That's why Jonas closed your bug ticket yesterday. They had too much trouble on a topic they consider a byplay. ngx-extended-pdf-viewer inherits most of the code from pdf.js, so I'm very reluctant fixing their bugs. My bugfix tends to get lost or broken with the next update of pdf.js.

If you find out which CSS rules are missing, I can add the vendor-specific prefixes again in my fork of the PDF viewer. Generally speaking, printing on iOS has always been unreliable, but it's new that it doesn't work altogether.
