### ISSUE TITLE
How to perform searching only on the viewed page

### ISSUE THREAD

**Issue by adambeer** [stephanrauh/ngx-extended-pdf-viewer#832]
Do you know of a way to only perform a search ONLY on the page that is being viewed? Strictly to speed up the search of larger documents.

**Comment by stephanrauh** [comment]
Right now, that's not possible. But I can implement that. Basically, all you need to do is to replace this `for` loop:

https://github.com/stephanrauh/pdf.js/blob/d083a05720434de29d59de6e413043c022ee1c1a/web/pdf_find_controller.js#L723

**Comment by adambeer** [comment]
Thank you! This makes complete sense. If you do want to implement this, I would suggest adding a parameter to the search options called singlePage or something and have it false by default.

**Comment by stephanrauh** [comment]
I've just published a prototype with version 11.0.0-alpha.7. It's not perfect yet, but I believe it to be useful. The feature is currently implemented in the "bleeding edge" branch only.

ToDos left:
- [ ] examine why scrolling beyond the last or first search result breaks the UI
- [ ] test the programmatic API
- [ ] add translations for the few languages I know
- [ ] update the documentation

**Comment by stephanrauh** [comment]
The new feature is going to ship with version 11.0.0-alpha.13 today.

**Comment by stephanrauh** [comment]
Note that I've implemented the feature in the "bleeding edge" branch only. Recently, the pdf.js team has started to publish a new version every three or four months, so it's probably just a matter of two months until the feature migrates to the default branch.
