### ISSUE TITLE
allow setting range chunk size

### ISSUE THREAD

**Issue by productivityindustries** [stephanrauh/ngx-extended-pdf-viewer#833]
When pdf.js starts fetching a file in ranges, it uses a default chunk size of 65KB.

PDF.js supports a parameter `rangeChunkSize` that allows custom size to be specified.

Is it possible to have the parameter passed over from pdfDefaultOptions?

**Comment by stephanrauh** [comment]
Sounds like a good idea. May I ask what your use-case is? Why is it better to use a larger or smaller chunk size?

(That's none of my business, so you're not obliged to answer, I'm just curious).

**Comment by productivityindustries** [comment]
I'll gladly answer :-)
I noticed that, in most of the big PDFs I'm dealing with, the first page always starts showing after a few chunks have been fetched. So if i bump the chunk size up a bit, say 256KB, I can show the first page faster, since I'm creating 4x less http connections.

**Comment by stephanrauh** [comment]
The new option is going to ship with version 10.0.0-alpha.7.
