### ISSUE TITLE
Combine pageViewMode: single and spread: even

### ISSUE THREAD

**Issue by barnewsapp** [stephanrauh/ngx-extended-pdf-viewer#859]
Hi 

First of all, thanks for all your work doing this project :+1: 

**Is your feature request related to a problem? Please describe.**
Not a problem, but we have a specific requirement that we have not been able to make happen using the latest version of the pdf-viewer. 

We want the possibility to combine pageViewMode **single** and spread **even**. 
That is, show full pages without a scrollbar, and only change pages using buttons/external events. 
This is possible in Adobe Acrobat and it would be great if it could be done in ngx-extended-pdf-viewer.

When using the two properties the viewer starts as expected showing the first page by it self centered in the view. But when I go to the next page, the viewer only shows page 2 centered, and not both 2 and 3 side by side. 

**Describe the solution you'd like**
I'll attach a gif showing the result we want from Adobe Acrobat: 
![Adobe Acrobat Two Page View](https://user-images.githubusercontent.com/67910734/128170272-2785e0cb-198d-41d6-bd75-5b5affd660ec.gif)

Bonus: If the viewer can also center the last page, the same way as page 1. Adobe does not do this. 

**Describe alternatives you've considered**
We have testet with different values for some of the options but have not made it work.  

**Additional context**

PS: We are planing to contribute some code to the project later on. We want to improve the PinchOnMobileSupport :-)

Thanks and please let me know if you need any more information.

**Comment by stephanrauh** [comment]
Hooray! There's a pull request in the pipeline. I'm looking forward to it. Open source is so much fun!

**Comment by stephanrauh** [comment]
As for your feature request: It makes 100% sense to me, and I believe it's a low-hanging fruit (at least compared to some of the other tickets). I've learned the hard way I shouldn't make promises, but I'd like to add your feature to the 10.0.0 version. In other words, I hope I can find some spare time next week.

**Comment by barnewsapp** [comment]
@stephanrauh That sounds great!  
Yes, Open Source is the best :-) 
Keep up the good work :+1:

**Comment by stephanrauh** [comment]
Your feature has landed with version 10.0.0-alpha.6. There's also a live demo at https://pdfviewer.net/extended-pdf-viewer/page-view-mode.

Enjoy!
Stephan

**Comment by barnewsapp** [comment]
Thank you :+1: 
It works almonst perfectly. I've just found a small bug. 
If you hide the borders the right page in the spread is a off by a few pixels. 
`pageViewMode="single" spread="even"  [showBorders]="false"`

![spread-without-border](https://user-images.githubusercontent.com/67910734/129332329-997c159a-f6c1-4495-ba5a-28face2f37fd.png)

I expect this is easy to fix?

**Comment by stephanrauh** [comment]
I've fixed the offset - sort of. I didn't manage to calculate the offset based on the CSS rules, so I hard-coded the 10-pixel offset. That's probably ok, until you (or someone else) override the CSS class rules.

The bugfix is part of version 10.0.0-alpha.7, scheduled for tomorrow.

**Comment by stephanrauh** [comment]
The feature might be broken by adding the latest addtions of pdf.js 2.12. This needs to be tested.

**Comment by stephanrauh** [comment]
Still looks OK.
