### ISSUE TITLE
Unable to view PDF with Capacitor URI

### ISSUE THREAD

**Issue by muuvmuuv** [stephanrauh/ngx-extended-pdf-viewer#864]
**Describe the bug**

We are using this extension in favor of deprecated native solutions for Capacitor with Ionic. In our app we are download files for offline usage into the filesystem via Capacitor. This results into urls starting with "capacitor://", unfortunately pdf.js or this extension is unable to handle those urls. I cannot really tell which is responsible for this bug.

Here is the full error (results are equal in default and bleeding edge version):

```
⚡️  [error] - [MediaComponent.pdfViewer]: Error: {"message":"Unexpected server response (0) while retrieving PDF \"capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/14C0A73A-92C7-40A2-BE28-EE30AAAF8C72/Documents/config-files/9f74f035077a33133753531d8ec98b3b_Broschuere.pdf\".","name":"UnexpectedResponseException","status":0}
⚡️  To Native ->  Filesystem appendFile 133800070
⚡️  TO JS {}
⚡️  [error] - Unhandled Promise rejection: Unexpected server response (0) while retrieving PDF "capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/14C0A73A-92C7-40A2-BE28-EE30AAAF8C72/Documents/config-files/9f74f035077a33133753531d8ec98b3b_Broschuere.pdf". ; Zone: <root> ; Task: Promise.then ; Value: {"message":"Unexpected server response (0) while retrieving PDF \"capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/14C0A73A-92C7-40A2-BE28-EE30AAAF8C72/Documents/config-files/9f74f035077a33133753531d8ec98b3b_Broschuere.pdf\".","name":"UnexpectedResponseException","status":0} BaseExceptionClosure@http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:1028:38 [<root>]
http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:1031:2 [<root>]
__w_pdfjs_require__@http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:14627:41 [<root>]
http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:56:32 [<root>]
__w_pdfjs_require__@http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:14627:41 [<root>]
http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:14854:41 [<root>]
http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:14901:3 [<root>]
http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:14904:12 [<root>]
webpackUniversalModuleDefinition@http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:31:57 [<root>]
global code@http://192.168.178.101:8100/bleeding-edge/pdf-2.11.154.js:32:3 [<root>]
```

**Version info**
- beta3

**Desktop (please complete the following information):**
 - Edge (here its working because we are using the remote url in the browser starting with https)
 
**Smartphone (please complete the following information):**
 - native WebView

**To Reproduce**

Its hard to create a repl for it since it seems like an issue with the native Capacitor function, but try this:

1. Follow ionic setup guide to create a new ionic app with capacitor: https://ionicframework.com/docs/intro/cli
2. Install ngx-extended-pdf-viewer and Capacitor filesystem plugin
3. Download a file using filesystem plugin and pass the resulting uri to ngx-extended-pdf-viewer
4. Install android studio
5. Run ionic capacitor run android
6. See error

**Demo PDF file**

**Screenshots**

**Additional context**

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by stephanrauh** [comment]
@LuisManuel1983  You've mentioned at https://github.com/ionic-team/capacitor-site/issues/147 you've managed to run ngx-extended-pdf-viewer with capacitor and Ionic. Maybe you can give @muuvmuuv a hint?

**Comment by stephanrauh** [comment]
Oops, sorry, just saw you're already talking with each other.

**Comment by stephanrauh** [comment]
Angel Hurtado offers [a workaround](https://dev.to/angelxehg/implementando-descargas-de-archivos-con-capacitor-cordova-4844): you can download the file first and open it as a blog after finishing the download. Not an ideal solution because it's slow, but at least it's a working solution.

Angel's example use traditional URLs, so you can't use his source code examples. I guess you can simply load the file as a blob using the Capacitor file API (https://capacitorjs.com/docs/apis/filesystem#readfile).

**Comment by stephanrauh** [comment]
@yurydelendik I know it's a long time ago... but do you remember why you've whitelisted the "tel:" URL six years ago in pdf.js?

https://github.com/mozilla/pdf.js/commit/982accf1d79949dfdb866a8aad32396b6847d3fc

It doesn't seem to make much sense because pdf.js rejects this type of URL at two other places (https://github.com/mozilla/pdf.js/blob/745d5cc819d7f3226ef1a3d66983a77bb6afffdb/src/display/display_utils.js#L490 and https://github.com/mozilla/pdf.js/blob/745d5cc819d7f3226ef1a3d66983a77bb6afffdb/src/display/node_stream.js#L62).

**Comment by stephanrauh** [comment]
@muuvmuuv I've just release version 10.0.0-alpha.4. The bleeding edge branch (pdf.sjs 2.11) whitelists both capacitor and ftp URLs. Please run a test and tell me if it fixes the bug, so I can copy the solution to the default branch.

**Comment by muuvmuuv** [comment]
@stephanrauh wow man! You are quick! I did also realized that some protocols where blocked but couldn't find those places, thanks for that. 

And yes I already talked with Luis but hes not using Capacitor (or at least he thinks hes not using it since in his code example he is).

I will try the bleeding edge version now and many thanks for the effort! Is there any way to buy you a coffee for the work in that lib or patreon link?

**Comment by muuvmuuv** [comment]
THIS WORKS! Omg. Thanks! :D I already gave up. So many compiling done till now...

**Comment by stephanrauh** [comment]
Hooray! It was just a long shot, but sometimes you've lucky :)

As for buying a coffee: Thanks a lot! German tax law is very strict, so I never thought about it, but it's a nice offer!

**Comment by muuvmuuv** [comment]
@stephanrauh I am from Germany and use https://www.buymeacoffee.com/ never had problems with it. You could also just link your PayPal in GitHub ;) this wont infer with any laws

**Comment by stephanrauh** [comment]
@LuisManuel1983 Actually, you're explanation was all right... it was just me writing faster than I could read or think :)

**Comment by stephanrauh** [comment]
The capacitor URL can now also be used with pdf.js 2.10 (i.e. the default branch). I couldn't activate ftp:// because the fetch API doesn't support that, so I reverted the corresponding changes of the bleeding-edge branch.
