### ISSUE TITLE
PDF viewer not showing the pdf from base64 data if we viewing it in second time

### ISSUE THREAD

**Issue by vigneshvofox** [stephanrauh/ngx-extended-pdf-viewer#865]
First of all. It is a very useful project and it is very easy to view PDF files either from a source directory or from a base 64 string. I have implemented the same in my project and loaded a pdf document in the ngx-extended-pdf-viewer using base 64 string. The ngx-extended-pdf-viewer is in a modal popup. But it showing the pdf first time only. After closing the popup and if we open the popup again, we cannot able to see the pdf document (Only a gray color instead of pdf). Following is my code on the HTML page.

```
<div class="pdf-container">
            <ngx-extended-pdf-viewer
              [base64Src]="pdfData"
              useBrowserLocale="true"
              height="80vh"
              delayFirstView="2000"
              *ngIf="pdfData.length > 0"
            >
            </ngx-extended-pdf-viewer>
          </div>
```
The 'pdfData' contains the base 64 string data. If we refresh the page and open the popup, then it will be working fine. Any help would be appreciable...!

**Comment by stephanrauh** [comment]
Does the console show any error message?

By the way, you almost certainly can omit the `delayFirstView` attribute. It was necessary in the early days, before I learned how to use pdf.js correctly.

**Comment by vigneshvofox** [comment]
Hi Stephan, sorry for the late reply. Yes console showing an error message. "offsetParent is not set -- cannot scroll"

**Comment by stephanrauh** [comment]
This error message means the PDF viewer is initialized before it becomes visible. An easy workaround is to make the PDF viewer invisible by default and to make it visible after a short timeout. BTW, that's similar to what `delayFirstView` does.

```typescript
public visible = false;

ngOnInit() {
  setTimeout(() => this.visible=true, 200);
}
```

```html
<ngx-extended-pdf-viewer *ngIf="visible" ... >
```

**Comment by vigneshvofox** [comment]
Hi Stephan, I tried this but not working

**Comment by stephanrauh** [comment]
Does this project work on your machine?

https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue-796-modal-height-100-percent

It's a modal dialog. It doesn't use a base64 file, but you can add your base64 file to the demo project easily.

**Comment by vigneshvofox** [comment]
Let me try this. Thank you...!

**Comment by stephanrauh** [comment]
Did you make any progress?
