### ISSUE TITLE
Cannot set property 'setHash' of null

### ISSUE THREAD

**Issue by master0615** [stephanrauh/ngx-extended-pdf-viewer#87]
Hi
I am Pavel Panov.
I have tried to use `<ngx-extended-pdf-viewer>`.
But I have got this error.
![image](https://user-images.githubusercontent.com/14261728/59156659-5d0ebe00-8ae2-11e9-9822-7bc5dd4363f5.png)
My code is like this.
```html
        <ngx-extended-pdf-viewer 
            *ngIf="base64src"
            [base64Src]="base64src"
            height="500px"
            delayFirstView="1000"
            [useBrowserLocale]="false"
            [zoom]="'auto'"
            [language]="currentLang"
            [showSidebarButton]="false"
            [showOpenFileButton]="false"
            [showPrintButton]="false"
            [filenameForDownload]="fileName">
        </ngx-extended-pdf-viewer>
```
When I change 'useBrowserLocale' property to "True", there is no error like this
[useBrowserLocale]="true"
In this case, I can't change the language for pdf viewer.
How to fix this problem?
Thanks.

**Comment by stephanrauh** [comment]
Is there another error message in the console? It looks like you've sent me a screenshot of a follow-up error. It simply means "the PDF viewer hasn't been initialized". That's a bit strange at this point in time (ngAfterViewInit).

Maybe a hack helps you: add the locales you're interested in to the index.html, as I did in the early demos (https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/6345024c1ea13d4ad3e9262708ff3213c0d544ca/src/index.html#L14). I've also described this approach in the [README file](https://www.npmjs.com/package/ngx-extended-pdf-viewer).

If that doesn't work, have a look at the working showcase, compile it, and compare both projects for difference. The sourcecodes are here: https://github.com/stephanrauh/extended-pdf-viewer-showcase

**Comment by szymonlacki** [comment]
I have the same problem, too. 
 `Cannot set property 'setHash' of null`

**Comment by stephanrauh** [comment]
@szymonlacki @master0615 I've managed to reproduce your error by setting `delayFirstView="0"`. Or by debugging. The bug occurs when the PDF viewer takes too long to load the translation files. Can you check if there's an unusual delay in the network tab of the browser's debugger? And can you try increasing `delayFirstView`to, say, 3000? Just to see if the error goes away?

**Comment by stephanrauh** [comment]
OK, got it. The attribute `useBrowserLocale` means you're using the locale files provided by ngx-extended-pdf-viewer. If you set the attribute to `false`, you have to add the locales to the index.html (or any file that's part of the DOM when the PDF viewer is initialized).

In both cases, you can use the attribute `[language]`.

In other words, `useBrowserLocale` is a misnomer. I'm trying to fix that in the next few versions.

I've added error messages to make things less confusing. Hope that helps!

**Comment by stephanrauh** [comment]
I've updated the documentation in the showcase.

**Comment by stephanrauh** [comment]
@vishnu-dev, @szymonlacki, @master0615 Does this solve your issue? Please give me a short "thumbs up" so I can close the issue. Or continue the investigation if it's a "thumbs down".

**Comment by szymonlacki** [comment]
Hello. Sorry for silence. I will tell you is it works tomorrow on my job
where i Will check it

pon., 10 cze 2019, 23:16 użytkownik Stephan Rauh <notifications@github.com>
napisał:

**Comment by szymonlacki** [comment]
Meanwhile, I greet and thank you for contact


pon., 10 cze 2019, 23:27 użytkownik Szymon Łącki <szymonlacki96@gmail.com>
napisał:

**Comment by stephanrauh** [comment]
@szymonlacki Off-topic: You've published your private e-mail address with the latest answer. Assuming that you didn't want to do that, I've removed it from the text in order to protect your privacy. Of course I can restore it again if you prefer that.
