### ISSUE TITLE
Error: The height of the PDF viewer widget is zero pixels.  (IONIC 5)

### ISSUE THREAD

**Issue by polfernandez** [stephanrauh/ngx-extended-pdf-viewer#871]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). NO
- Does the bug also happen on https://pdfviewer.net/simple? NO
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template NO

**Describe the bug**
When loading the pdf widget it shows the following error:
**The height of the PDF viewer widget is zero pixels. Please check the height attribute. Is there a syntax error? Or are you using a percentage with a CSS framework that doesn't support this? The height is adjusted automatedly.**

**Version info**
   "ngx-extended-pdf-viewer": "^10.0.0-alpha.5",

**Desktop (please complete the following information):**
 - Browser Google Chrome, Mozilla Firefox
 
**Smartphone (please complete the following information):**
 NOT TESTED

**To Reproduce**
1. Create blank ionic capacitor project.
2. npm install ngx-extended-pdf-viewer
3. . import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer' in the project's module.
4. VIEW (HTML CODE):  
```
<ngx-extended-pdf-viewer [src]="'/assets/dummy.pdf'"  height="80vh" ></ngx-extended-pdf-viewer>
</div>
```
5. [dummy.pdf](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

**Screenshots**
<img width="1437" alt="Captura de pantalla 2021-08-12 a las 13 50 47" src="https://user-images.githubusercontent.com/32094365/129192032-b83ae6fa-c9e8-4c06-bcd7-45c300a47529.png">

**Thank you!**

**Comment by stephanrauh** [comment]
Weird. What happens if you set `[height]="'500px'"` or if you drop the `[height]` property?

**Comment by polfernandez** [comment]
> Weird. What happens if you set `[height]="'500px'"` or if you drop the `[height]` property?

The same error, I tried height='500px', [height]="'500px'", [height]="customHeight" where customHeight = '500px', and drop it.

**Comment by stephanrauh** [comment]
As it turns out, the warning message is correct. It seems Ionic takes some time to render the page, so when ngx-extended-pdf-viewer is initialized, the height of the parent HTML element is still 0px. So ngx-extended-pdf-viewer enters a panic-mode, setting the height forcibly to 100 pixels.

You can workaround  the bug with a lot of CSS, but the warning message doesn't go away. So I recommend using a timeout like so:

```html
<ngx-extended-pdf-viewer *ngIf="visible" [src]="'/assets/dummy.pdf'" [zoom]="'page-fit'"></ngx-extended-pdf-viewer>
```

```ts
@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page implements AfterViewInit {

  public visible = false;

  public ngAfterViewInit(): void {
    setTimeout(() => {
      this.visible = true;
    });
  }
}
```

I've pushed the reproducer and the bugfix at https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue871.
