### ISSUE TITLE
Spread-pages should be center aligned

### ISSUE THREAD

**Issue by barnewsapp** [stephanrauh/ngx-extended-pdf-viewer#877]
Hi, not sure if this is a feature request or a bug. 

Thanks for making it possible to have even spread in single page mode. 

**Describe the solution you'd like**
When viewing av document using spread=even and pageViewMode=single, the pages should be centered in the same way as with no spread. 

Please look at the attached gif showing the issue: 
![Center-align-spread](https://user-images.githubusercontent.com/67910734/129564498-c7ab2cdd-3fc6-495d-b529-b041fd8a4f16.gif)

In no-spread mode the single page is centered perfectly. 
After changing to even spread, the first page is displayed far to the left. 
When changing til page 2 and 3 the pages i aligned all the way to the left. 

The solution should be to perfectly center both one-page and two-pages in the container. 

Please let me know if you need more information. 

Thanks

**Comment by stephanrauh** [comment]
To my surprise, the bug fix makes the code even simpler. I've published it with version 10.0.0-alpha.8.

**Comment by stephanrauh** [comment]
I just saw that the bug fix isn't part of the bleeding edge branch yet. I'm going to add it to the bleeding edge branch with the next release.

**Comment by barnewsapp** [comment]
Thanks a lot for another quick fix :+1:
