### ISSUE TITLE
Centered (vertically, horizontally) single page view with scrolling capabilities

### ISSUE THREAD

**Issue by gregorymaertens** [stephanrauh/ngx-extended-pdf-viewer#879]
**Is your feature request related to a problem? Please describe.**
In my application we display images, video, iframes and PDFs in present mode using the browser requestFullscreen(). We may enter fullscreen while displaying an image then move to a PDF.
PDFs are shown with zoom=page-fit. For portrait PDFs everything works fine.
When using a PDF in landscape mode, depending on the browser window dimension you may end up seeing the next page at the bottom as shown here:
![Screen Shot 2021-08-17 at 10 05 27](https://user-images.githubusercontent.com/1636112/129688265-8ba83e3e-e30b-4232-b415-a14066f75f5b.png)

**Describe the solution you'd like**
To have an option or a recipe to add vertical padding to center the page within the view port. Something like:
![Screen Shot 2021-08-17 at 10 05 27 copy](https://user-images.githubusercontent.com/1636112/129688645-f6579739-203d-4227-a57f-d1f28365e813.png)

**Describe alternatives you've considered**
I have looked at pageViewMode='single' => not centered vertically. Lose scrolling (as per design).
I have looked at zoom=page-height => page is truncated. For landscape PDF the left/right parts of the page are truncated.
I have looked at pdf.js requestPresentationMode() => page is not centered vertically and won't work if already in fullscreen mode (as per my scenario when starting already in fullscreen with an image then moving to a PDF)

**Additional context**

**Comment by stephanrauh** [comment]
I believe you can add the margin with a simple global CSS rule:

```css
.page {
  margin-bottom: 500px !important;
}
```

I couldn't reproduce the bug because my laptop screen has exactly the right dimensions, so I need your help. Does adding the margin solve the problem?

(If you're reluctant to add a CSS rule to the styles.css, I suppose you can use `::ng-deep` or something like that).

**Comment by stephanrauh** [comment]
Actually, the CSS rules already add `margin-bottom: 100%`. I've increased it to 100vh to avoid corner-cases. However, in theory, it's hard to understand what causes your bug.

**Comment by stephanrauh** [comment]
Shipped with version 10.0.0-alpha.10. I've also added a demo to the showcase (without publishing it yet).
