### ISSUE TITLE
[FEATURE] Disable the textLayer on the pdf

### ISSUE THREAD

**Issue by vishnu-dev** [stephanrauh/ngx-extended-pdf-viewer#88]
I have successfully rendered a PDF on this library and it runs pretty well. How do I disable the text layer to get more performance on PDF which has more than 500 pages?

TextLayer is that container which overlays on the canvas to have selectable text on PDF. Disabling this should, in turn, disable search and other features depending on the text layer.

Also, the scroll is very slow even on small PDFs.

@stephanrauh Please take a look at this.

**Comment by stephanrauh** [comment]
I'm looking for that option myself. I suspect somewhere there's a switch in Mozilla's viewer.js, but I haven't found it yet. Any clues?

**Comment by vishnu-dev** [comment]
[ng2-pdf-viewer](https://github.com/VadimDez/ng2-pdf-viewer) has that feature. Could you inherit from how they have done it?

**Comment by stephanrauh** [comment]
Good idea. Maybe I've found the option. It's called `options.textLayerMode`. However, for some reason unknown I didn't manage to deactivate the text layer yet.

**Comment by vishnu-dev** [comment]
Okay. What happened @stephanrauh ?

**Comment by stephanrauh** [comment]
Well, I've spent a week mostly offline. Now I'm back in town and I'm going to resume working on the project soon.

**Comment by stephanrauh** [comment]
I've just published version 0.9.47, which deactivates the text layer by default. To activate it, set `[showHandModeButton]="true"`. 

CPU load is still a bit high. Can you verify I've successfully deactivated the text layer, please?
