### ISSUE TITLE
How to remove the unverified-signature-warning but still show signature ?

### ISSUE THREAD

**Issue by tungphamhttt1** [stephanrauh/ngx-extended-pdf-viewer#884]
Hi sir,
I'm using ngx-extended-pdf-viewer of you. It's useful.
My problem is about removing the warning - "This PDF file contains a digital signature. The PDF viewer can't verify if the....". 
Because i wanna my layout become clearly. so do you have any ways to remove this warning or could you add the option for me to off that warning ? 
Thank you.

**Comment by stephanrauh** [comment]
Yes, you can remove this warning with a simple CSS rule. Examine the HTML code of the warning and you'll know what to do.

I deliberately choose not to make this obvious. If you're 100% sure that the signature is valid, go ahead. However, I, the library author, can't decide whether the signature is valid or not. For all I know, it might be a fraud signature. So I prefer to play it safe.
