### ISSUE TITLE
Drag and drop a signature image on top of the file

### ISSUE THREAD

**Issue by gentios** [stephanrauh/ngx-extended-pdf-viewer#892]
Hi, thank you for the work and for this great library

I am interested to use the library for drag and drop a signature image on top of the pdf and 
get its (image) coordinates such as: `lx rx, ly, ry` so later on I can send it to the backend for digitally signing it.

I have achieved this result using PDF.js and canvas however I wanted to whether its doable also
with this library and get those extra features that is offering.

Thank you in advance

**Comment by stephanrauh** [comment]
Sounds interesting. How did you implement this with pdf.js?

I'm pretty sure the same approach works with ngx-extended-pdf-viewer, too. Basically, it's simply an add-on to pdf.js.

**Comment by gentios** [comment]
Thank you for your fast reply. 

I have achieved the drag and drop feature with https://interactjs.io/ however I cannot do the same with 
`ngx-extended-pdf-viewer` too

I am attaching a screenshot of trying to do the same.
![image](https://user-images.githubusercontent.com/10573204/131265215-f79c72fc-d779-4431-9927-1cec5e12e476.png)

**Comment by stephanrauh** [comment]
That's strange. But  I'm afraid I don't really understand how interact.js works. I suspect it doesn't recognize you're dragging something into the drop zone. I've tried to debug the library, but that's not that easy.

Maybe interact.js isn't compatible to the build-in drag-and-drop feature of pdf.js (which is active by default in ngx-extended-pdf-viewer).

**Comment by gentios** [comment]
It seems so that it cannot find the `drop zone`.


Here  I created a `stackblitz`, unfortunately `stackblitz` is not able to run for some reason `ngx-extended-pdf-viewer` but it works to show the idea behind it and also for a reference of others.

There I am showing on how I do a `drag-and-drop` on a `pdf.js` custom component I have created, and I try to do the same with `ngx-extended-pdf-viewer`

https://stackblitz.com/edit/angular-ivy-ekxpyh?file=src/app/app.component.html

**Comment by stephanrauh** [comment]
Embedding the entire PDF viewer in the drop zone is a clever solution! That's the difference to what I tried yesterday.

To my surprise, it only takes a few tiny modification to make your demo work. Find the modified StackBlitz demo at https://github.com/stephanrauh/pdfviewer-drag-and-drop.

Enjoy!
Stephan

**Comment by gentios** [comment]
Wow perfect thank you for your support, I appreciate it.

One last thing that I needed to clarify now is how to access the canvas element that is being created if I need to access the context or its width, height.

**Comment by stephanrauh** [comment]
The DOM tree of the PDF viewer looks like so:

![image](https://user-images.githubusercontent.com/3045767/131574088-bba560a4-7e32-4007-a40f-f2a0254c67c9.png)

I assume you know which page you're currently displaying. If so, you can get the canvas using a CSS selector:

```typescript
document.querySelector('[data-page-number]=42  canvas')
```

I didn't test it, so maybe I didn't jot down the CSS selector correctly, but you get the idea.

**Comment by gentios** [comment]
CSS selector did the job, much appreciated from you @stephanrauh

**Comment by ziaKhan1995** [comment]
@gentios Thank you for this Stackblitz example

https://stackblitz.com/edit/angular-ivy-ekxpyh?file=src/app/app.component.html

Can you update a little bit, on how to display all the pages instead of one page?

Thanks in advance

**Comment by stephanrauh** [comment]
Oh, whow, that's a demo I totally forgot. Yes, you're right, it's a minimalist implementation that doesn't consider scrolling. You can fix this by listening to the scroll position using a `MutationObserver`. When the PDF viewer scrolls, the signature canvas should scroll in sync.
