### ISSUE TITLE
Secondary sidebar

### ISSUE THREAD

**Issue by iprnd** [stephanrauh/ngx-extended-pdf-viewer#899]
I just need to be able to add a secondary sidebar on the right, just the thumbnails on left!

**Comment by stephanrauh** [comment]
OK. What do you want to do with the secondary sidebar? Do you want to put your custom content inside, or do you expect ngx-extended-pdf-viewer to do something?

**Comment by iprnd** [comment]
Yes, custom content. Not related to PDF element, like showing list of similar files.

**Comment by stephanrauh** [comment]
Sounds cool! I'm adding this to the ship list of version 11.

**Comment by stephanrauh** [comment]
Implementing a secondary sidebar is more difficult than expected. Plus, the use-case is too limited for my taste. So I decided to do it more radically. I've added the attribute `[customPdfViewer]` allowing you to modify the entire UI except the exception of the CSS imports.

At the moment, I don't know how to document this feature, but I guess a look at the template `customPdfViewer` of https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.html is all you need.

Your feature has landed with version 13.0.0-alpha.17. Please apologize the long wait!

Best regards,
Stephan
