### ISSUE TITLE
[zoom]="undefined" doesn't work as documented

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#90]
Omitting the `zoom` attribute (or setting it to undefined) results in an error message. Plus, the documentation says it's set either to the user's preferences or - if that's not possible - to "auto".

**Comment by leacollaboro** [comment]
I think I'm hitting this issue: no matter what i set, it reverts to default next time i open a pdf. I can see that the zoom value is being saved to localstorage but it's like it never gets read up. I'm not setting the zoom value anywhere in code.

**Comment by stephanrauh** [comment]
Are you referring to a programmatic setting, or are you referring to what the user does? Like, they zoom in, and the new zoom is stored in LocalStorage?

**Comment by leacollaboro** [comment]
When the user changes the setting. So assume we have nothing set for default, the UI shows 'auto' as expected. Then the user selects 'page fit'. Then they navigate away and select another PDF. The component loads the PDF but now the settings are back to 'auto', despite local storage having saved 'page-fit'. It seems to overwrite the stored value once the document is loaded.

**Comment by stephanrauh** [comment]
Funny thing is storing the zoom factor was part of my original use-case. It was one of the reason why I've created the project. I've solved the problem using two-way binding. That's the workaround I suggest now, too.

I wasn't even aware that pdf.js already implements this feature. Nowadays I don't want to break compatibility, so I guess I'll introduce using `LocalStorage` properly as an option.

**Comment by leacollaboro** [comment]
Awesome. Thanks! 

When you say using 2 way binding as a workaround, do you mean bind the value to a variable so next time it loads up it uses the previous value? I'm not sure that'll work if the component is removed and recreated but will check.

**Comment by stephanrauh** [comment]
If everything works according to the plan, you can omit [zoom] or set it to `undefined` in version 9.0.0. Then the default is still `auto`, unless the user has opened the document before. In that case, their last setting is respected.

I've uploaded a very early preview of the feature to http://pdfviewer.net.

**Comment by stephanrauh** [comment]
The feature has landed with version 9.0.0-alpha.1.
