### ISSUE TITLE
Is file query parameter needed for the library?

### ISSUE THREAD

**Issue by chan-dev** [stephanrauh/ngx-extended-pdf-viewer#907]
### Discussed in https://github.com/stephanrauh/ngx-extended-pdf-viewer/discussions/904

<div type='discussions-op-text'>

<sup>Originally posted by **chan-dev** September  6, 2021</sup>
I'm having an issue where adding a `file` query parameter throws an error even if i don't use the value of the query parameter as the pdf source.

![pdf-viewer-error](https://user-images.githubusercontent.com/46891115/132144856-44713fa4-c57f-422b-aa16-23b6c41855b8.png)

For instance, here's a sample URL
`chrome-extension://extensionId/src/pdfviewer/web/viewer.html?file=http://localhost:3000/apis/pdfstorage/someRandomId`

NOTE:
* it is just named `viewer.html` but it's our own custom html file

Here's how i actually use the library:
I just manually add the value in `[src]` `@Input`
```
<ngx-extended-pdf-viewer
  [src]="'assets/ws-checklist.pdf'"
  [handTool]="false"
  [showFindButton]="true"
  [useBrowserLocale]="true"
  zoom="100%"
  height="100vh"
></ngx-extended-pdf-viewer>
```

Upon searching the internet, it seems like they're all pointing to editing the source file. 
One example is from this stackoverflow [answer](https://stackoverflow.com/a/37379368/9732932)

Essentially, i have a couple of questions:
1. Does pdf.js looks at `?file=value` query parameter even if you don't use it in your code?
2. Is the only solution right now is to edit the viewer.js?
</div>

**Comment by stephanrauh** [comment]
The bugfix has shipped with version 10.0.0-beta.2. I've simply removed the `?file=` parameter because I can't imagine anyone will ever put this option to good use in an Angular application.

Enjoy!
Stephan

**Comment by chan-dev** [comment]
awesome. Will try this one out. Currently, since we're still making use of the `?file=` parameter, so we depended on the pdf.js default functionality of using file query parameter, i guess this one will break our existing functionality.

If you don't mind, since we're gonna write our own functionality for fetching local files (e.g `file:///path/to/test.pdf`) instead of using the default behaviour `file?=file:///path/to/test.pdf`, any tips how to go about it?

**Comment by stephanrauh** [comment]
Oh, I wasn't aware you're using the `?file=` parameter. What's the advantage over using `[src]`?

As far as I know, you can't access local files from a browser, with one exception: if the user explicitely grants the file access, you can use the `FileReader` or the brand-new file system access API (https://web.dev/file-system-access/). In both cases, the user either grants permission by selecting a file in a file select box or by drag'n'drop.

If you're allowed to write an application instead of a browser, use Electron. That's a Chrome browser that's not intended to be used as a browser but as a framework for local application. So you get rid of the security restrictions. For example, VS Code is an Electron application.

**Comment by chan-dev** [comment]
Yeah, In our case, the use of `?file=` query parameter is solely because it was being used by the old implementation of an app that we're trying to migrate. Just found out that with the latest beta version, the use of `?file=/path/to/local.PDF` still works w/c is in favor for us because we still have to support that feature. Again, thanks a lot for that update, it helped us in our case.

On the other hand, regarding the file access we don't use file upload or drag and drop for local file access, our input is only the URL that is the value of `?file=` (e.g `?file=/path/to/local.PDF` ), so we have to fetch `/path/to/local.PDF` locally. Btw, thanks to the resources you've specified, i'll be trying those once i have the time.

**Comment by stephanrauh** [comment]
How did you manage to access the local file? Are you using Cordova or something like that? I'm pretty sure that https://www.pdfviewer.net?file=C:/my/favorite/document.pdf does not work.

**Comment by chan-dev** [comment]
Forgot to mention that we're using the library inside a chrome extension. There's a file permission that a user can choose to enable which will give the chrome extension file permissions. The user has to manually activate this permission by visiting `chrome://extensions` and choose "Allow access to file URLs"

**Comment by stephanrauh** [comment]
Ah, that's a huge difference! :)

In that case, my binaries of pdf.js runs a check you won't like. It protects you from opening `file://` URLs. 

Come to think of it - that's a bad check for Electron applications, too. I should allow users to disable this check.
