### ISSUE TITLE
Is there a way to force mobile behavior with gestures on desktop touch screen?

### ISSUE THREAD

**Issue by marchesedesade** [stephanrauh/ngx-extended-pdf-viewer#911]
Hello, 
I found out that zoom pinch gesture is not working on a desktop touch screen because the viewer doesn't recognize it as a mobile device. Is there a way to force this mobile behavior even if browser is in 'desktop' mode?

Thank you

**Comment by stephanrauh** [comment]
Oh. Good point. But it's also weird. I don't see why you desktop is not recognized as a mobile device. Maybe you can help me. This is the mobile check:

```typescript
  private isMobile() {
    return 'ontouchstart' in document.documentElement;
  }
```

Any idea why it returns `false` on your machine?

**Comment by marchesedesade** [comment]
Hi,
I'm using a laptop connected with a desktop touch screen set as main display. I think Chrome does not recognize a mobile configuration because I've two displays and/or I'm not in Win10 'tablet mode' or, even, because resolution is higher then expected. Next week I'm going to run some tests. Besides, forcing mobile mode in Chrome debugger makes pinch zoom works fine on desktop touch screen.
Do you have any other testing suggestions? How can I eventually modify component's logic to force a return 'true' in the mobile check?

Thank you

**Comment by stephanrauh** [comment]
To my surprise, there's no easy way to override the function. But maybe I should rewrite the function. What happens when you execute this line in the console window of your browser?

```javascript
( 'ontouchstart' in window ) || ( navigator.maxTouchPoints > 0 ) || ( navigator.msMaxTouchPoints > 0 )
```

Does it return true?

**Comment by marchesedesade** [comment]
Hi,
this line 

> ( 'ontouchstart' in window ) || ( navigator.maxTouchPoints > 0 ) || ( navigator.msMaxTouchPoints > 0 )

returns `false` in the standard environment (even with laptop's non-touch screen totally disabled), but if I put Win10 in 'tablet mode', it returns `true`.
I could bypass the check this way (my app will be used in kiosk mode), but I'd prefer to have an override in the code to avoid manual configuration of different PCs.

**Comment by stephanrauh** [comment]
Please try version 10.0.0-alpha.11. It should solve the issue.

**Comment by marchesedesade** [comment]
Hi,
I confirm that problem is solved.

Thank you!
