### ISSUE TITLE
How to know whether print successful or cancel

### ISSUE THREAD

**Issue by mingli1015** [stephanrauh/ngx-extended-pdf-viewer#913]
Hello,

I have tried to listen for the afterprint event, but afterprint event is fired when the printing dialog closed no matter I click print button or cancel print button at last on the open window of printing dialog. Is there a solution that return a value to let me know whether it print successful or cancel? 

Thanks

**Comment by stephanrauh** [comment]
I'm afraid that's not possible. It's an annoying limitation of the browser. You can trigger printing from JavaScript, but the browser API doesn't give you any feedback whether the document has been printed or not.

According to https://caniuse.com/?search=onafterprint, every modern browser support the `onafterprint` event handler. Unfortunately, the documentation says this event fires both when the document is printed and when the print dialog is closed without printing. You can give it a try. I don't think this event tells you what the user did, but the HTML specification is a bit hazy (or I read the wrong specification pages), so maybe you're lucky.

BTW, I just saw this is your first issue on GitHub ever. Welcome to GitHub!

Best regards,
Stephan
