### ISSUE TITLE
Single page PDF document, but in the printing dialog, it show me two pages with a blank page. 

### ISSUE THREAD

**Issue by mingli1015** [stephanrauh/ngx-extended-pdf-viewer#915]
Hi, Stephan

Thank you so much for your speedy reply to my last question.
I have another question about the printing. I have a single page PDF document, but in the printing dialog, it show me two pages and the second page is a blank page. Do you know why? and how to solve it. Thank you in advance.

Best regards.
Ming

![Capture](https://user-images.githubusercontent.com/5716210/132641525-b3027a42-9446-4c7a-8195-0ecba559e711.PNG)

**Comment by stephanrauh** [comment]
This bug is almost certainly caused by your CSS framework (and that make it difficult to hunt down). pdf.js draws each page as an image, hides everything else, and sends the HTML page consisting of the images to the printer. If you CSS framework adds a margin or a padding or modifies the font size (or something like that - the list goes on forever), printing is broken.

Which CSS framework are you using?

A la prochaine,
Stephan

**Comment by mingli1015** [comment]
Thank you very much for your reply. In our project, we convert html to pdf with [SelectPdf](https://selectpdf.com/), a REST API. We would like to use ngx-extended-pdf-viewer to view and print the files PDF. Do you have an idea to solve this bug? Thank you in advance.

A la prochaine ;-) 
Ming

**Comment by stephanrauh** [comment]
As far as I remember, this is my approach to solve this bug:

- add a breakpoint here: https://github.com/stephanrauh/pdf.js/blob/d083a05720434de29d59de6e413043c022ee1c1a/web/pdf_print_service.js#L270
- print the document
- The debugger stops after rendering the images but before opening the print dialog.
- Force the browser to use "media type print":
![image](https://user-images.githubusercontent.com/3045767/132947343-742e5622-6d79-4708-9386-a56c6defbfaa.png)

Now you see the document as it's going to be printed in the browser. Use the "elements" tab to find out which CSS rule adds an unwanted padding or margin.

That's always a frustrating and cumbersome debugging session. It's easier if you do the same steps in the Mozilla showcase. Our CSS rules have diverged, but printing is so volatile that the CSS rules still should be identical.

**Comment by stephanrauh** [comment]
Any news? Did you manage to solve the issue?
