### ISSUE TITLE
Set source remotely

### ISSUE THREAD

**Issue by g3344** [stephanrauh/ngx-extended-pdf-viewer#92]
Hi, great extension.

I'm trying to set the source remotely.  Is there a good way to do this?

Below is what is in the .ts file:
```
objUrl = 'assets/test.pdf'
document.querySelector("ngx-extended-pdf-viewer").setAttribute('src', objUrl);
```

Below is in the component.html
```
<ngx-extended-pdf-viewer useBrowserLocale="true" height="90vh" delayFirstView="2000">
</ngx-extended-pdf-viewer>
```

It seems like the source is set...but the url does not load:

What would be the better way to set the source dynamically?

**Comment by stephanrauh** [comment]
I guess you've found the solution yourself: the `[src]` attribute supports Angular's databinding.
