### ISSUE TITLE
The PDF viewer removes the # from the URL

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#923]
https://stackoverflow.com/questions/65969347/ngx-extended-pdf-viewer-removing-hash-from-url-in-angular-8

**Comment by pvymazal** [comment]
Hello, I have the same problem (10.0.0-alpha.11). The fix would be great. Thank you.

**Comment by pvymazal** [comment]
Hi Stephan, when can I expect this bug to be resolved? This bug will cause a routing issue throughout the application, so I can't use the library for now. Sorry to bother you, but resolving this bug would help me a lot. Thank you for your time and work on this project.

**Comment by stephanrauh** [comment]
You can speed up things by helping me. I suppose it's not much work. Please have a look at https://github.com/stephanrauh/pdf.js. More specifically, the bug must be in the `web` subfolder. Can you spot the line modifying the browser URL? More likely than not, the bug is here: https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/pdf_history.js

Once I know what's going on, fixing and publishing the bug is a matter of days, or maybe even hours, depending on how much free leisure time I have.

I know I'm demanding a lot, but I'd really appreciate your help. Thanks in advance!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Oh, I just saw the message "opened their first issue on GitHub in stephanrauh/ngx-extended-pdf-viewer". I feel very honored. Thanks a lot, and welcome to the GitHub community!

**Comment by stephanrauh** [comment]
@pvymazal This evening, I've tried to reproduce the bug, but I've failed. What do I have to do so see the error?

**Comment by pvymazal** [comment]
@stephanrauh Hi Stephan, thank you so much for your efforts. I created an issue-repro. If I leave the import NgxExtendedPdfViewerModule in app.module.ts, then I lose the hash in the url. If I obfuscate the import, the hash is fine.

Unfortunately, I am not savvy enough to find the hash error in the source files. Please let me know if there is anything else I can do to help.

Thank you, have a nice day
[hash-error-repro.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7189840/hash-error-repro.zip)

**Comment by stephanrauh** [comment]
That's the slimmest reproducer I've ever seen! :)

BTW, you zip file is a bit corrupted. It doesn't contain folders but filename with a backslash. But never mind, I was able to install the reproducer quickly.

**Comment by pvymazal** [comment]
Hey, I'm sorry. I tried downloading the zip package from Github and running the project. It seems to be ok - my Windows probably does what it wants :-)

Have a nice day, Petr

**Comment by stephanrauh** [comment]
I've found and fixed the bug. It was hidden at an entirely unexpected line of code.

**Comment by pvymazal** [comment]
Well, that's great :-). So fast... Thank you very much !!!
