### ISSUE TITLE
Add a custom error handler

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#925]
@chan-dev suggests in #920 to implement a custom error handler (something like `<ngx-extended-pdf-viewer (error)="customErrorHandler($event)">`.

I'm not sure if that's possible, but it's worth a look.

**Comment by chan-dev** [comment]
Thanks, this would be really great to suppress some pdfjs errors and handle them yourselves.

**Comment by chan-dev** [comment]
In relation to this one, it seems like `(pdfLoadingFailed)` is not being invoked, even if there's an error loading a pdf file.

**Comment by chan-dev** [comment]
Just update on this one, i keep getting this error when the request fails.
Note: I'm using the `?file=pdfUrlhere` query parameter by convention since the old implementation uses this one.

So I keep getting this error, and i can't handle the error on `(pdfLoadingFailed)` since it is not invoked.
![pdf-error](https://user-images.githubusercontent.com/46891115/133862295-befa9cf3-1019-4756-96af-5539335da1fd.png)

**Comment by chan-dev** [comment]
I wish i have the time to dig into the source of pdf.js but sadly i'm very occupied with work. 
Does pdf.js have a catch all error or exception handler? If there is, we could throw a custom event there.
https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent

With that said, we can listen to that custom error events inside Angular components thru `@HostListener('somePdfsCustomEvent', callback)`? I don't know if this approach makes a lot of sense in terms of flexibility and maintainability.

**Comment by stephanrauh** [comment]
Using an event might be a good idea. pdf.js doesn't have a global error handler. It's using `async/await` a lot, so many errors aren't really exeptions, but rejected promises.

**Comment by chan-dev** [comment]
In the current version, how do you go about it when dealing with catching errors? Say when there's an error in downloading, printing, etc?

**Comment by stephanrauh** [comment]
Well, it's simply an exception that's thrown. But since most of the code is asynchronous, there's no connection to your Angular application. So the exception is simply printed on the console window, and that's it.

**Comment by stephanrauh** [comment]
As it turns out, catching every exception and every rejected `Promise` is difficult for me, but easy for you:

```typescript
window.onerror = function (e) {
    alert("unhandled error: " + e);
};

window.addEventListener('unhandledrejection', function(event) {
    console.error('Unhandled rejection (promise: ', event.promise, ', reason: ', event.reason, ').');
});
```

https://stackoverflow.com/questions/31472439/catch-all-unhandled-javascript-promise-rejections

https://caniuse.com/unhandledrejection
