### ISSUE TITLE
Is there a way to automatically set the title of the pdf?

### ISSUE THREAD

**Issue by chan-dev** [stephanrauh/ngx-extended-pdf-viewer#927]
**Is your feature request related to a problem? Please describe.**
Is there a way to get the title returned by pdf.js or a way for the component to automatically set document.title?

**Describe the solution you'd like**
I believe behind the scenes, pdf.js generates a title, maybe return it as a payload for `(pdfLoaded)`; right now, pdfLoaded only returns `{ pagesCount: value }`

**Describe alternatives you've considered**
Manually set it once `(pdfLoaded)` has been called via `document.title` but i think pdf.js returns a normalized version?

**Comment by stephanrauh** [comment]
Have a look at this demo: https://pdfviewer.net/extended-pdf-viewer/file-info

It shows you how to read the title. After that, you can set `document.title`.

**Comment by chan-dev** [comment]
many thanks, will try this one.

**Comment by chan-dev** [comment]
Just tried this one and it returns undefined on the "title" property.

What worked for me was calling the `pdfjslib`
```
document.title = pdfjsLib.getPdfFilenameFromUrl(url);
```

**Comment by stephanrauh** [comment]
I guess that means the PDF author hasn't defined a title. `pdfjsLib.getPdfFilenameFromUrl()` yields a filename based on some criteria. That's not necessarily what the author of the document had in mind. But I'm not sure. Correct me if I'm wrong. In any case, your approach is a clever one. I just wonder if it amounts to additional network traffic.
