### ISSUE TITLE
Src change error

### ISSUE THREAD

**Issue by pvymazal** [stephanrauh/ngx-extended-pdf-viewer#929]
**Describe the bug**
Hi, I have come across the following problem. If I set [src]="'assets/sample1.pdf'" and then change the value to [src]="'assets/sample2.pdf'", I get an error 

pdfLoadingFailed Error: Invalid PDF url data: either string or URL-object is expected in the url property.
    at getDocument (viewer-2.10.552.min.js:22)
    at Object.open (viewer-2.10.552.min.js:43)
    at NgxExtendedPdfViewerComponent._callee5$ (ngx-extended-pdf-viewer.component.ts:1422)
    at tryCatch (runtime.js:63)

The first time sample1.pdf is loaded, the openPDF() function is called in the ngx-extended-pdf-viewer.component.ts, where options.baseHref = this.baseHref (value "/") is set before calling PDFViewerApplication.open(this._src, options);

The second time sample2.pdf is loaded, the openPDF2() function is called and the options.baseHref setting is missing. If I add it (as in openPDF()), the pdf file will reload fine.

Test on template ngx-extended-pdf-viewer version 6.2.0-alpha.0 worked fine.

**Version info**
- ngx-extended-pdf-viewer: 10.0.0-alpha.11
- Angular 11.2.12

**Desktop**
- browser: Chrome 93.0.4577.63
 
**To Reproduce**
[change-src-error-repro.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7166693/change-src-error-repro.zip)

**Comment by stephanrauh** [comment]
Hey, you've even provided a reproducer project! Thanks a lot for testing (and analysing) the feature so quickly. I was afraid of side-effects. To bad they always lurk in dark, forgotten corners :)

**Comment by pvymazal** [comment]
Hi, I appreciate your work on the project, the library looks very good. Thanks

**Comment by stephanrauh** [comment]
Thanks for the nice words! I've even got good news for you: you bug is top on my list. I hope to be able to publish version 10.0.0 this week-end, including this bug fix and possibly even the other bug fix you've asked for.

**Comment by stephanrauh** [comment]
The bugfix has shipped with version 10.0.0-beta.2.

Enjoy!
Stephan

**Comment by pvymazal** [comment]
Perfect, thank you very much!

Have a nice day, Petr

**Comment by pvymazal** [comment]
Hi Stephan, I have tested fix on version 10.0.0 and it works fine.
Thank you.

Have a nice day, Petr
