### ISSUE TITLE
First and last page is not centered in spread mode 

### ISSUE THREAD

**Issue by barnewsapp** [stephanrauh/ngx-extended-pdf-viewer#930]
**Describe the bug**
Hi. I think this is releated to the previous bug: #881 

**Version info**
Latest master

**Desktop (please complete the following information):**
 - Browser: Google Chrome

**To Reproduce**

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to https://pdfviewer.net/extended-pdf-viewer/page-view-mode
2. Select "even spread"
3. Go to first page in the document
4. The single first page is not center-aligned 

The same happens on the last page in documents with even number of pages. 

**Screenshots**
![2021-09-15_10-32](https://user-images.githubusercontent.com/67910734/133399299-95faea3b-6370-4a32-bfdf-ef3cb0d9c731.png)

**Thank you!**

**Comment by stephanrauh** [comment]
Oh no, not again! At least I've got some practice hunting the bug by now :)

**Comment by stephanrauh** [comment]
The bugfix shipped with version 10.0.0-beta.1.
