### ISSUE TITLE
Pdf is not shown if my console is closed

### ISSUE THREAD

**Issue by mingli1015** [stephanrauh/ngx-extended-pdf-viewer#932]
Hello 

In my project, I need to load the PDF file from server on mode Blob. And set the parameter [src] with the return Blob object. If my console is open, it shows the PDF. But once I close the console, the PDF is not shown until I click on the view PDF. Do you know why? Thanks

```html
 <ngx-extended-pdf-viewer 
                          [src]="pdfSrc"
                         (afterPrint)="onEvent('afterPrint', $event)"
                         pageViewMode="single"
                         [useBrowserLocale]="true">
</ngx-extended-pdf-viewer>
```
 

```typescript
public pdfSrc: Blob = null;  
this.service.getPdfFileOnBlob(this.selectedFiles).subscribe((res) => {
                this.pdfSrc= res;
            });
```
```typescript
public getPdfFileOnBlob(selectedFiles: FileItemViewModel[]): Observable<Blob> {
        return of(selectedFiles.filter(itm => itm && itm.pdfStreamId)).pipe(
            take(1),
            switchMap(itemFiltered => {
                return this._http.post(
                    environment.rootUrlForWebAPI + "Pdf/GetPdfFiles",
                    itemFiltered,
                    {
                        responseType: "blob",
                        withCredentials: true
                    }
                );
            }),
            tap(blob => {
                return blob;
            }
            )
        );
    }
```

**Comment by mingli1015** [comment]
One other question about the repository of the source pdf file. In my project,  [src]="'/assets/pdfs/some.pdf'" work.  Can we set a local repository for src? For example [src]="'C:/pdfs/some.pdf'" or a relative path in project.

**Comment by stephanrauh** [comment]
At first glance, I can't spot the error in your code. Compare it to https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/blob. That's a working example (taken from the showcase). Maybe you can spot the difference.

As for your second question: I'm afraid you can't display local files. Any access to your local hard disk must be initiated by the user. That's a security measure, and the browser can't be cheated. At least I hope so - in the past ( >10 years ago) there were viruses accessing the hard disk using JavaScript in the browser.

**Comment by stephanrauh** [comment]
Some other remarks:
- Did you add the tap() for debugging reasons? If not, get rid of it. It doesn't do anything.
- You don't have to assign `null` to an attribute. The default value is `undefined`, which does the trick just as well. The semantics are: `undefined` means you haven't looked at the attribute yet. `null` means you've deliberately assigned it a value to indicate it doesn't have a value.
- Are you sure you want to use the `of` function? I believe you're better off using the functional programming methods of the array. As a bonus, you get rid of `switchMap`.

**Comment by stephanrauh** [comment]
If your PDF file is rendered after opening the console error, the real cause is probably that opening the console changes the windows size. Try resizing the window. Does your PDF file render now?

**Comment by chan-dev** [comment]
I have somewhat of eccentric issue that is quite similar to this. In my case, i'm loading fetching something from a api server and if i try to display the pdf, it won't load until I do any of the following:
* press right click
* open console dev tools
* press sidebar.

I've noticed that it won't reload some pdf  assets until i do any of the aforementioned actions. Upon further investigation, it seems like the PDF response has multiple requests with HTTP response with 206 status code.

**Comment by stephanrauh** [comment]
Are the 206 responses chunks of 64 kb (or something like that)? If so, they're a feature. pdf.js is able to render the first page of the PDF file while it's still loading the rest of the file. That's the range request feature I've documented briefly at https://pdfviewer.net/extended-pdf-viewer/range-requests.

**Comment by stephanrauh** [comment]
Some time ago, there was a similar issue. The PDF file was loaded correctly, but for some reason, it wouldn't render. So I wonder why your PDF file doesn't render. What about the event `(pageRender)` and `(pageRendered)`? Do they fire?

**Comment by chan-dev** [comment]
> Are the 206 responses chunks of 64 kb (or something like that)? If so, they're a feature. pdf.js is able to render the first page of the PDF file while it's still loading the rest of the file. That's the range request feature I've documented briefly at https://pdfviewer.net/extended-pdf-viewer/range-requests.

About the size, they're not consistent, sometimes it even get's smaller or larger than 64kb. 


Regarding the events, `(pageRender)` and `(pageRendered)` don't fire and doesn't do the requests that result in 206 Http status code until I do the actions on my previous comment

**Comment by stephanrauh** [comment]
I haven't heard from you for a long time. I assume you've either give up or solved the issue?
