### ISSUE TITLE
print produces blank pages after each page

### ISSUE THREAD

**Issue by chan-dev** [stephanrauh/ngx-extended-pdf-viewer#935]
Using the print functionality generates a blank page after each page, and upon checking the console i have this error.

I've already checked the css and no margin or paddings that i've set that will cause the pdf styles to get distorted

```
Warning: AnnotationBorderStyle.setWidth - ignoring width: 4
```

**Comment by stephanrauh** [comment]
Can you send me a reproducer, pleaser? Take this project as a basis, please: https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template

I assume the bug doesn't show with the template project. If so, add your global CSS files until you see the bug.

**Comment by chan-dev** [comment]
I'm unsure how to use the reproducer. Do i just simply clone that repo and create a new folder and make a PR request? or just simply use it as a playground?

Anyways, i've created a local repo and tested the print functionality and i can't reproduce the issue. 
I've tried adding the bootstrap.scss global style and I can't still reproduce it.

One thing, i've noticed on the app with the print pdf issue is that there's a sort of a delay for at least a couple of seconds before the loader starts.

**Comment by chan-dev** [comment]
What fixes my problem was making changes on css in the context of print styles.
Just tried a bunch of solutions from this [stackoverflow](https://stackoverflow.com/questions/7846346/how-to-avoid-extra-blank-page-at-end-while-printing) answer.

Ultimately what fixed my problem was:
```
@media print {
  /**
   * NOTE: this style is very important because
   * it fixes blank pages generated on every page when printing
   */
  html,
  body {
    height: 99%;
  }
  * {
    box-sizing: border-box;
  }
}
```

**Comment by stephanrauh** [comment]
Hooray! Reducing the size of the `<html>` tag is an approach I haven't seen before, but I guess it makes sense.
