### ISSUE TITLE
PDF pages delayed loading only in iPad

### ISSUE THREAD

**Issue by vishnu0067** [stephanrauh/ngx-extended-pdf-viewer#939]
Hi team,

We are having an angular application which uses ngx-extended-pdf-viewer for displaying pdf to user and also allows them to perform commenting on the same. But the issue we are facing now is that only in iPad (various models) even after the application receives pdf from server there is a few seconds (sometimes the time gap is  up to 10-15 seconds) gap before the viewer loads pages to be displayed to user.
Any one facing same issue, if yes please let us know if any solution available.

```html
<ngx-extended-pdf-viewer   [src]="pdfSource" 
                                 [textLayer]="true"
                                 (pagesLoaded)="onPagesLoaded($event)"
                                 (textLayerRendered)="onTextLayerRendered($event)"
                                 [showBookmarkButton]="false"
                                 [showFindButton]="false"
                                 [showSecondaryToolbarButton]="false"
                                 [showOpenFileButton]="false"
                                 [showPrintButton]="false"
                                 [showSidebarButton]="false"
                                 [showPagingButtons]="true"
```

**Comment by stephanrauh** [comment]
@vishnu0067 Sorry for answering late. Recently, I've got a hard time catching up with all the new issues. 

Did you manage to solve the problem? Are you still suffering from the delay?

Version 10 and 11 of the PDF viewer offer performance improvements. Now it's possible to open documents with thousands of pages. If you're still suffering from performance problems, try the new single-page mode of ngx-extended-pdf-viewer 11. At the time of writing, only the bleeding-edge branch benefits from the new single-page mode, but that's going to change soon when I'm going to publish version 11 of ngx-extended-pdf-viewer. Probably that's tomorrow or the day after tomorrow.
