### ISSUE TITLE
Prepends baseHref in hash based routing

### ISSUE THREAD

**Issue by apatsche** [stephanrauh/ngx-extended-pdf-viewer#940]
Hi,

If baseHref is set
ngx-extended-pdf-viewer version 10.0.0

```json      
      ...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "outputs": ["{options.outputPath}"],
          "options": {
            "baseHref": "microapp",
          ...
```
baseHref is prepended to hash route:
http://localhost:5202/microapp#/microapp/messages

wihtout ngx-extended-pdf-viewer:
http://localhost:5202/microapp#/messages

**Comment by stephanrauh** [comment]
I've tried to reproduce your bug, but I wasn't successful. I've converted the showcase to hash-based routing and modified the `baseHref` as instructed. Everything works as intended.

Can you send me a reproducer, please?

**Comment by apatsche** [comment]
https://github.com/apatsche/ngx-extended-pdf-viewer-routing-test

if you change the imports in app.module.ts you can see how routing is changing.

**Comment by stephanrauh** [comment]
Hi Dieter, thanks a lot! I know how much work it is to prepare a reproducer, so I appreciate your prompt response!

I've managed to reproduce your bug. Now I'm confused. As far as I can see, pdf.js is not the culprit. It doesn't even make it to memory. More likely than not, my module definition is faulty. Hey, I love challenging riddles! I'm just sorry people like you experience my riddles as bugs... sorry about that!

Be that as it may, this bug is top on my list. It's blocking my public announcement of the 10.0 version.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Found it! This part of the `@NgModule` is the culprit:

```typescript
  providers: [{
    provide: APP_BASE_HREF,
    useFactory: getBaseHref,
    deps: [PlatformLocation]
  }],
```

**Comment by stephanrauh** [comment]
The bugfix has shipped with version 10.0.2.

Caveat: As of version 10.0.2, the form support is broken in the bleeding-edge branch. I've published the version nonetheless to give you an opportunity to test the hash-based routing.

**Comment by apatsche** [comment]
Hello Stephan,
great! thanks a lot for the fix.

i also found the part of the code causing the issue, but had no time to create a pull request sry.

**Comment by stephanrauh** [comment]
Cool! Can you explain the bug to me? I don't understand why injecting the `BASE_HREF` modifies the URL. Is this a feature or a bug of Angular?

**Comment by apatsche** [comment]
As the angular documentation says APP_BASE_HREF is a predefined DI token to be used with the PathLocationStrategy to preserve the prefix, i guess  you can say it is an angular bug, if it also influences the HashLocationStrategy. 
But i guess you could also say this token was missused because a library should not set this kind of token which influences the routing, as routing should be managed by the consuming application. 

what do you think?
