### ISSUE TITLE
‘showPrintButton‘ and ‘showDownloadButton’ does not work

### ISSUE THREAD

**Issue by legatoplay** [stephanrauh/ngx-extended-pdf-viewer#95]
`<ngx-extended-pdf-viewer
    #pdfViewer
    [src]="'https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf'"
    backgroundColor="#ffffff"
    [delayFirstView]="1000"
    [height]="'90vh'"
    [useBrowserLocale]="true"
    [showPrintButton]="false"
    [showDownloadButton]="false"
    (pageRendered)="onPageRendered($event)"
    (pagesLoaded)="onPagesLoaded($event)"
  >
  </ngx-extended-pdf-viewer>`

 [showPrintButton] and [showDownloadButton]  attributes does not work

**Comment by stephanrauh** [comment]
I've copied your code snippet into my demo. Both the print button and the download button are gone. In other words: I can't reproduce your bug.

**Comment by stephanrauh** [comment]
At second glance, it turned out that responsive design got in the way. I've fixed this with version 0.9.48. There's also a showcase demo at https://pdfviewer.net/hiding-buttons.
