### ISSUE TITLE
open a file which present in my document folder

### ISSUE THREAD

**Issue by krishnamoorthy51** [stephanrauh/ngx-extended-pdf-viewer#953]
i cant able to open the file which present in may local root folders 
is there any ways to open that

**Comment by stephanrauh** [comment]
- The user can open local files, either by using drag'n'drop or by using the "open" button (the one with the arrow pointing upward).
- It's impossible to open local file programmatically. There's an open ticket allowing it for environments like Electron, but as long as you're using a browser, you simply can't open local files. That's a security measure, protecting you from hackers reading all you local files while you're surfing the web.
