### ISSUE TITLE
showToolBar is the property from which we can show and hide the header. But, I want to hide the customFreeFloatingBar as well. I tried it with ngif but the buttons are not working then.

### ISSUE THREAD

**Issue by khanSoliheen** [stephanrauh/ngx-extended-pdf-viewer#956]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I'm always frustrated when [...]"

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stephanrauh** [comment]
Oops. Interesting. Yeah, you're right. Your feature request makes sense. 

I was happy to be able to display the floating bar at all, and next thing I hear is  you want to hide it. :)

Jokes aside, I imagine that `*ngIf` doesn't work well. I'm sure I can offer you a better alternative soon.

**Comment by stephanrauh** [comment]
The feature is going to land with version 11.1.0 soon.

**Comment by stephanrauh** [comment]
The bugfix has landed with version 11.1.0.
