### ISSUE TITLE
pdf with radio button grouping (but looks like checkbox) not getting reflected in the pdfViewer.

### ISSUE THREAD

**Issue by anuroop15** [stephanrauh/ngx-extended-pdf-viewer#958]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). **No**
- Does the bug also happen on https://pdfviewer.net/simple? **Yes**
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template
 Sharing the attachments below
![Screen Shot 2021-10-01 at 1 04 09 PM](https://user-images.githubusercontent.com/21377582/135676155-a4b039a4-7f31-457e-87b3-190cd0e77d62.png)
![Screen Shot 2021-10-01 at 1 04 26 PM](https://user-images.githubusercontent.com/21377582/135676157-960ca96b-8bce-487d-9013-4410ce5dd57a.png)

**Describe the bug**
I'm trying to load a pdf with a group of checkbox items which are preselected. When loaded on mozilla.github.io its working fine but not using ngx-extender-pdf-viewer. The preselected checkboxed are blank. 

**Version info**
- Version of ngx-extended-pdf-viewer **(10.0.0)**

**Desktop (please complete the following information):**
 - Browser - **Chrome**
 
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] **NA**

@stephanrauh

**Comment by stephanrauh** [comment]
I'm afraid I need your help to solve the bug. Can you send me the PDF containing pre-filled checkboxes?

**Comment by stephanrauh** [comment]
If you don't want to expose your file to the public, you can drop me an email at webmaster1 at beyondjava dot net.

**Comment by anuroop15** [comment]
@stephanrauh 
Appreciate your response. Thank you verymuch!

I'm attaching a test form to reproduce the scenario. 

Here is the sample form that has preselected radio button:

[radiogroup test.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7270324/radiogroup.test.pdf)

If I render the same using pdfViewer.net/simple, its blank.
<img width="1276" alt="Screen Shot 2021-10-01 at 5 09 25 PM" src="https://user-images.githubusercontent.com/21377582/135691378-7b729650-a776-4799-bbee-4271ebc4fb4b.png">

<img width="1280" alt="Screen Shot 2021-10-01 at 5 08 47 PM" src="https://user-images.githubusercontent.com/21377582/135691328-be7f371b-aa86-40eb-bd14-b80aa144f1d3.png">

**Comment by stephanrauh** [comment]
Now I'm looking forward to an exciting (or frustrating?) debugging session!

**Comment by anuroop15** [comment]
:)
its weird. When you edit that radio group (select any one from options) using pdfviewer and save it. its saves fine. But if you open the saved file back to pdfviewer, it will select all buttons.

**Comment by stephanrauh** [comment]
I've got a working solution, but before publishing it, I have to think thoroughly about the side-effects. At the moment, I don't want to make any promises. I'm not sure if publishing the bugfix causes more problems than it solves. If in doubt, I'm going to play it safe. Checkboxes that aren't checkboxes are something I didn't expect.

In any case, you've sent me a good riddle! :)

**Comment by stephanrauh** [comment]
The thing you've considered weird is easily explained: checkboxes have a field name and an "export value". If multiple checkboxes share the same field name, they behave like radio buttons. The only way to distinguish between them is the export value.

I didn't know about the export value, so I used the field name as the sole discriminator. That explains that all the checkboxes are checked after reloading the file. Either each of them is checked, or they're all unchecked. 

The thing I need to investigate is if I can use a combination of the field name and the export value without breaking simple checkboxes. Plus, `[(formValue)]` must be backward compatible because AcroForm support is tremendously popular. If I modify the key of a checkbox from "myFavoriteCheckbox" to "myFavoriteCheckbox/checked" (or something like that), I'm going to make many developers unhappy. So I'm looking for a better option.

**Comment by stephanrauh** [comment]
I believe to have solved the issue. The bugfix has landed with version 10.1.0.

**Comment by stephanrauh** [comment]
I'm not sure if the bugfix has made it to the pdf.js 2.10 branch. Please check the "bleeding-edge" branch. During the next week, I'm going to update pdf.js, so pdf.js 2.11 is going to be the default branch. In other words, I won't spend any time fixing bugs of the 2.10 branch of pdf.js.

**Comment by anuroop15** [comment]
Thanks for the fix. yea we have modified to use pdf 2.11 using bleeding-edge. 👍

**Comment by stephanrauh** [comment]
Hooray! So I can start work on version 11.0.0. I just have to announce version 10 first. :)
