### ISSUE TITLE
 document is not defined error - Angular Universal project

### ISSUE THREAD

**Issue by ReneRautenbach** [stephanrauh/ngx-extended-pdf-viewer#959]
**Error**
"UnitToPx.con = document.createElement('div');
               ^
ReferenceError: document is not defined"

when running command npm run dev:ssr on Angular Universal project
 
**Version info**
-  "ngx-extended-pdf-viewer": "^8.3.0"
-  "ngx-extended-pdf-viewer": "^9.0.5"
-  "ngx-extended-pdf-viewer": "^10.0.2"
- "@nguniversal/express-engine": "~12.1.0"

**To Reproduce**
1. Download Demo Angular Universal app from https://angular.io/guide/universal
2. Run : npm install ngx-extended-pdf-viewer
3. Add NgxExtendedPdfViewerServerModule to app.server.module.ts
3. Add NgxExtendedPdfViewerModule to app.module.ts
4. Run : npm run dev:ssr 
    
Thank you!

**Comment by ReneRautenbach** [comment]
I place the following code after "import 'zone.js/node';" in the server.ts file and the error was resolved.

const domino = require("domino");
const fs = require("fs");
const path = require("path");
const templateA = fs
  .readFileSync(path.join("dist/browser", "index.html"))
  .toString();
const win = domino.createWindow(templateA);
win.Object = Object;
win.Math = Math;

global["window"] = win;
global["document"] = win.document;

**Comment by stephanrauh** [comment]
I'm happy you've found a solution, but I think it's too early to close the issue. :) I can't require everybody to install domino. That's a third-party library, isn't it?

So I think I ought to find out why SSR loads the UnixToPX class at all, and if I can't avoid that, I ought to check if there's a `document` because using it.

Does this sound like a plan?

**Comment by ReneRautenbach** [comment]
Yes - it would be great to solve without having to use domino. I also found that when I use my app that I created using Angular CLI the problem persist, even after using the domino code. I am debugging now to find out why. 
This is the part of the main.js file generated where the error occurs. I made the error line bold.

`
class UnitToPx {
    static initElements() {
        // this.con = document.createElement('div');
        this.con.style.position = 'absolute';
        this.con.style.width = '0';
        this.con.style.height = '0';
        this.con.style.visibility = 'hidden';
        this.con.style.overflow = 'hidden';
        // this.el = document.createElement('div');
        this.con.appendChild(this.el);
    }
    static pxPerUnit(unit) {
        if (!this.pxPerUnitCache[unit]) {
            if (!this.con) {
                this.initElements();
            }
            this.el.style.width = this.sample + unit;
            document.body.appendChild(this.con);
            var dimension = this.el.getBoundingClientRect();
            this.con.parentNode.removeChild(this.con);
            this.pxPerUnitCache[unit] = dimension.width / this.sample;
        }
        return this.pxPerUnitCache[unit];
    }
    static toPx(length) {
        var unitRe = /^\s*([+-]?[\d\.]*)\s*(.*)\s*$/i;
        var match = unitRe.exec(length);
        if (match != null && match.length > 2) {
            const bare = match[1] === '';
            const val = bare ? 1 : Number(match[1]);
            const unit = match[2];
            const valid = !isNaN(val) && unit;
            if (valid) {
                return unit == 'px' ? val : this.pxPerUnit(unit) * val;
            }
        }
        throw new TypeError('Error parsing length');
    }
}
// cache this.con, el for reused
**UnitToPx.con = document.createElement('div');**
UnitToPx.el = document.createElement('div');
// high sample will more accurate?
UnitToPx.sample = 100;
UnitToPx.pxPerUnitCache = {};

class NgxExtendedPdfViewerComponent {
    constructor(ngZone, platformId, notificationService, location, elementRef, platformLocation) {
        this.ngZone = ngZone;
        this.platformId = platformId;
        this.notificationService = notificationService;
        this.location = location;
        this.elementRef = elementRef;
         `

**Comment by stephanrauh** [comment]
I've found and fixed the bug. However, the toolbar looks different with SSR. The zoom dropdown is zero pixels wide (i.e. invisible), and several buttons are missing.

**Comment by stephanrauh** [comment]
The bugfix has landed with version 10.1.0.

**Comment by ReneRautenbach** [comment]
Thank you Stephan
