### ISSUE TITLE
No name for the downloaded pdf

### ISSUE THREAD

**Issue by RojasAB** [stephanrauh/ngx-extended-pdf-viewer#96]
If we set the filenameForDownload variable or not the downloaded pdf will been downloaded with the name undefined.

**Comment by BarGol00683** [comment]
Check older version. Change version in Json to 0.9.46
```json
"ngx-extended-pdf-viewer": "0.9.46"
```

**Comment by RojasAB** [comment]
i know that version 0.9.46 download with correct filename but the download function itself doesn't work correctly in all devices for that version. I will try to fix the issue now

**Comment by stephanrauh** [comment]
@RojasAB @BarGol00683 You're right, when I finally found out how (and when) to configure pdf.js correctly, I accidently destroyed the `filenameForDownload` feature. It never showed in my tests because if still works when changed later, using `ngOnChanges()`.

**Comment by stephanrauh** [comment]
@RojasAB You say that the download functionality itself is broken? It seems to work on pdfviewer.net. Do you still see this problem? Soon I'll publish 0.9.52, maybe you can run a test with the new version.

**Comment by stephanrauh** [comment]
I've just pushed version 0.9.52.
