### ISSUE TITLE
Theming for Acroforms

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#961]
I don't like the standard design of the forms. It should be easy to customize the CSS rule, so let's do it!

**Comment by namblard-sword** [comment]
Hi @stephanrauh,

I'm interested in that topic. Is there any breakthroug made about it ? 

Thank you for your time,

Best regards

**Comment by stephanrauh** [comment]
People kept me busy by finding and reporting bugs, so I didn't even begin yet. :)

But I really think it's easy. All the rules are collected in [this file](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/theme/common/annotation-layer-builder.scss), and maybe also [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/theme/common/xfa_layer_builder.scss), so all it takes is extracting these files and allowing users to replace them with other files. Plus, I think I should replace the hard-coded color values by SCSS variable to make customizing even simpler.

**Comment by stephanrauh** [comment]
@namblard-sword I've implemented `[formTheme]="'light'` and `[formTheme]="'dark'"`. The third option is `[formTheme]="'custom'", which requires you to add a copy of [the theme component](https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/lib/theme/pdf-light-theme) yourself.

At the moment, there's some rudimentary documentation at https://pdfviewer.net/extended-pdf-viewer/theming.

The demo isn't as reliable as it should be yet. Plus, many properties of the form are defined by the author of the PDF file. This includes the font color, the border colors, and the background colors of the input fields. In other words, almost everything that counts. So successful form theming depends on the co-operation of the author of the PDF file.

May I invite you to run a test? I've published the feature with version 13.0.0-alpha.12.

Happy Easter!
Stephan

**Comment by stephanrauh** [comment]
@namblard-sword Another Easter weekend... and this time I feel overwhelmed by a flood of tickets. In other words, I'm looking for ways to simplify the library. I'd like to remove the Acroform theme feature again, because it broke soon after implementing it. I doubt anybody has managed to use it successfully. What about you? Are you using Acroform themes?

**Comment by stephanrauh** [comment]
I've decided to remove `[formTheme]`. It's been broken for quite some time now, and I need to prune the library to keep up with the rapid progress of the pdf.js team.
