### ISSUE TITLE
Values of the form input fields are invisible when zoomed in

### ISSUE THREAD

**Issue by dahar92** [stephanrauh/ngx-extended-pdf-viewer#962]
**Version info**
- 10.1.0

**Smartphone**
 - Device: iPhoneX, iOS 15

**To Reproduce**
On my iPhone X, I opened a pdf with filled form fields and zoomed in. The values of the fields are invisible

![image](https://user-images.githubusercontent.com/38558821/135817004-e1979f59-5ea8-4c15-8eba-3a5b6fb8cfbd.png)

![image](https://user-images.githubusercontent.com/38558821/135817043-24e7ce47-8ef7-44e8-b9eb-80cb0c9b1984.png)

**Comment by stephanrauh** [comment]
@dahar92 Is this a bug that didn't happen in earlier versions? Would you mind to test the feature with the "bleeding edge" version of pdf.js?

Maybe it's related to https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/958. I solved the pre-fillled fields issue yesterday, but for some reason, the bugfix only made it to the bleeding-edge version.

**Comment by stephanrauh** [comment]
Wait, what? Are you telling me that the fields are emptied or become visible by zooming? That's entirely unexpected, so please confirm if this is the bug you're reporting.

**Comment by stephanrauh** [comment]
I've tried to reproduce the bug, but I couldn't. As long as you're using the bleeding edge branch, everything seems to be OK.

**Comment by dahar92** [comment]
I've tested the feature with the bleeding-edge version, but the bug still exists. When I zoom in, the form field values becoming invisible. When I zoom out to the default zoom, the values are visible again

**Comment by dahar92** [comment]
when I change the renderer the svg, then it is working

**Comment by dahar92** [comment]
You can reproduce the bug if you open that review page with the iPhone and click the zoom button in the pdf viewer. https://pdfviewer.net/extended-pdf-viewer/forms

**Comment by stephanrauh** [comment]
You're right, it also happens on an iPhone 12 mini running the most current iOS 15. I can see the context of the fields for a fraction of a section before it vanishes. When I tap the "+" button three times, the text appears again.

I'm afraid I don't have any clue how to debug this issue. For some reason unknown, I can't link my iPhone to my MacBook.

Does this bug also happen without two-way binding?

**Comment by dahar92** [comment]
Yes, this bug happens also without two-way binding of the form. I do not use that. 
This is the Code:

<ngx-extended-pdf-viewer
    [base64Src]="base64Content"
    [useBrowserLocale]="true"
    [enablePinchOnMobile]="isMobile"
    [mobileFriendlyZoom]="'150%'"
    [showToolbar]="false"
    [height]="cssHeightOfPdfContainer"
    [zoom]="'auto'"
    [maxZoom]="2"
    (pagesLoaded)="pagesLoaded($event)"
></ngx-extended-pdf-viewer>

**Comment by stephanrauh** [comment]
Workaround: add this CSS rule:
```CSS
::ng-deep ngx-extended-pdf-viewer div#viewerContainer {
  -webkit-overflow-scrolling: auto;
}
```

**Comment by stephanrauh** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

**Comment by stephanrauh** [comment]
After testing the workaround thoroughly, I've added it to version 11.1.1.
