### ISSUE TITLE
Scrolling issue in album screen orientation on mobile device (Ionic 5)

### ISSUE THREAD

**Issue by EugeneDP89** [stephanrauh/ngx-extended-pdf-viewer#965]
**Describe the bug**

**Version info**
- ngx-extended-pdf-viewer@10.0.0
 
**Smartphone (please complete the following information):**
 - Device: iPad 8 (ios 15.0)

**To Reproduce**
- Issue happens only with album screen orientation (2nd attached video).  I disabled ionic page scroll <ion-content [scrollY]="false">, as it also caused an issue (1st attached video). So if I open sidebar with pages previews - scrolling start working, after closing it stops working. The same thing happens both when I open document in portrait and album orientation - portrait works, album not.

Video of scrolling issue when not disabled page scroll:

https://user-images.githubusercontent.com/8157247/136180371-1d92af2a-a45c-4ade-ac93-68fc5464f041.mp4

Video of scrolling issue when changing orientation:

https://user-images.githubusercontent.com/8157247/136180121-48fb77af-30be-4209-829e-f49316fb77d6.mp4

 
```
<ion-content [scrollY]="false">
  <ngx-extended-pdf-viewer
    *ngIf="visible"
    [src]="document.document_file.url"
    [showToolbar]="true"
    [showSidebarButton]="true"
    [showZoomButtons]="true"
    [showFindButton]="false"
    [showPagingButtons]="false"
    [showPresentationModeButton]="false"
    [showOpenFileButton]="false"
    [showPrintButton]="false"
    [showDownloadButton]="false"
    [showBookmarkButton]="false"
    [showSecondaryToolbarButton]="false"
    [showRotateButton]="false"
    [showHandToolButton]="false"
    [showScrollingButton]="false"
    [showSpreadButton]="false"
    [showPropertiesButton]="false"
  ></ngx-extended-pdf-viewer>
</ion-content>
```

**Comment by muuvmuuv** [comment]
I have the same issue, but it happens all the time. Replacing ion-content with a div does not make any difference. Scrolling is only working on web.

Edit: Okay, seems this is because the PDF (500mb) is still loading (or caching/creating previews?). After two app crashes it has cached everything and it works :D

**Comment by stephanrauh** [comment]
@muuvmuuv Oh, that's awesome! Did you notice any broken feature? I believe using `OnPush` must have a disadvantage or two. For instance, I'd expect `(page)` to be broken. What's your experience?

**Comment by muuvmuuv** [comment]
@stephanrauh unfortunately we aren't using any of the event features :/ but couldn't find any disadvantages yet.

**Comment by stephanrauh** [comment]
@EugeneDP89  @muuvmuuv @elvisgraho Is this issue still an issue? Or did the comments help you to solve the problem?

If so, can you give me a hint what to add to the documentation? I hardly ever use Ionic, so solving Ionic bugs is always a challenge to me. In other words: I'm looking forward to your insight!

**Comment by muuvmuuv** [comment]
@stephanrauh the `changeDetection: ChangeDetectionStrategy.OnPush` fixed it for me, so no, it is no longer an issue.

**Comment by stephanrauh** [comment]
That's good news! I'm going to close the ticket now. I suppose I'll document the Change Detection strategy sooner or later, but at the moment, I still need to research the consequences.
