### ISSUE TITLE
prevent Double click 

### ISSUE THREAD

**Issue by mahmooudali7** [stephanrauh/ngx-extended-pdf-viewer#970]
Hi @stephanrauh 

is there any way to prevent the pdf from streching when double click on it 

Thanks in advance

**Comment by stephanrauh** [comment]
Hey, that's a feature I've added because it seem to be popular! :) But I can add a feature toggle. Maybe you're also happy with a simple work-around:

```ts
import { pdfDefaultOptions } from 'ngx-extended-pdf-viewer';

constructor() {
  pdfDefaultOptions.doubleTapZoomFactor = '100%';
}
```
