### ISSUE TITLE
Drag drop and get coordinate

### ISSUE THREAD

**Issue by tanmac2905** [stephanrauh/ngx-extended-pdf-viewer#972]
Hi im need drag drog box and get coordinate follow the PDF inside can you help me
![Untitled](https://user-images.githubusercontent.com/87795981/137090958-c2c2f839-723d-429a-870a-536112c2a0c4.png)

**Comment by stephanrauh** [comment]
Todo left:

- [ ] document the new property of `fileInputChange`
