### ISSUE TITLE
Rotate working with R key even when rotate buttons are hidden

### ISSUE THREAD

**Issue by adityakmehta** [stephanrauh/ngx-extended-pdf-viewer#985]
**Description**
I want to stop using hotkey "R" to rotate the PDF inside viewer. There is no method available in the utility to stop this behavior. Even if I hide the rotate buttons, still R is triggering rotate.

**Version info**
- All Versions

**Desktop (please complete the following information):**
 - All Browsers
 
**To Reproduce**
Click anywhere inside PDF Viewer. 
Hit "R" on the keyboard. 
Image will rotate. 
Click anywhere outside the PDF viewer window and hit "R". The PDF will Rotate.
Set [showRotateButton] to false. Still "R" will rotate the PDF.

**Comment by stephanrauh** [comment]
I agree this smells suspiciously like an error. But it isn't. I want to give you developers as much flexibility as possible, so I've decided to allow you to disable the button and the key separately.

https://pdfviewer.net/extended-pdf-viewer/keyboard describes how to disable individual keys. In a nutshell: just add the attribute `[ignoreKeys]="['R', 'Shift+R']"`.

What's a bit weird is that you still can rotate the PDF file with the "R" key if the focus is outside the PDF viewer. But still, I suppose that's what most users expect. I'd only get nervous if the PDF file is rotated when you're trying to type an "R" in an input field.

I'm going to close the issue now, but feel free to add remarks or follow-up questions. I'm still listening to this channel.

Best regards,
Stephan
