### ISSUE TITLE
Download filename is undefined

### ISSUE THREAD

**Issue by teland94** [stephanrauh/ngx-extended-pdf-viewer#99]
When I click Download button I am getting 'undefined' filename. I'm tried to use [src] from Uint8Array and [base64Src]
![Undefined](https://i.ibb.co/f2gSks7/Capture.png)

**Comment by stephanrauh** [comment]
I suppose you've found the answer yourself: if the filename is "undefined", just define it. That's what the attribute `[filenameForDownload]` is for.

BTW, do you have a suggestion for a better default name?
