### ISSUE TITLE
slow performance with pdf having 13234 pages

### ISSUE THREAD

**Issue by aysha-statvalu** [stephanrauh/ngx-extended-pdf-viewer#995]
I tried to open a pdf having 13234 pages and its size is 30MB. When I tried to open with ng2-extended-pdf-viewer issue is
It performed slow when I tried to scroll down its lagging and not smooth. Link for pdf file to download is 

https://1drv.ms/b/s!AnQBGhZ6jZZmgY9WwSoErTmxU7SeVQ?e=jIMAG2

on one drive working like a charm.

https://user-images.githubusercontent.com/82865585/138648642-d3fd723a-4016-4783-85c0-46ef1b8067b6.mp4

**Comment by aysha-statvalu** [comment]
please help how to deal with this issue?

**Comment by stephanrauh** [comment]
@aysha-statvalu I'm sure you know the golden rule of open source: the best way to speed up things is offering your help.  

Here's how you can help me. I'd like to know what makes my PDF viewer slow. Would you mind to help me with the investigation?

- The most plausible culprit is Angular's change detection. Please add the Angular Devtools to your Chrome browser, run a performance measurement, and tell me how much time your application spends with change detection. Plus, examine if your application is the performance bottleneck. Change detection is very performance-sensitive, so even small changes to your application might make a difference. Also have a look at https://www.beyondjava.net/zonejs#How%20much%20time%20does%20your%20application%20spend%20with%20change%20detection?
- You can also try to use a different change detection strategy in your application. Sometimes `ChangeDetectionStrategy.OnPush` makes a big difference.
- It's also possible that another part of your application triggers change detection frequently, leaving only a small time-slot of the PDF viewer.
- Finally, 13234 pages is a huge document. It's way beyond what I had in mind when creating the PDF viewer. Truth be told, I'm impressed my pet project is able to open such a huge document at all!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
@elvisgraho Can you tell me something about the size of your PDF documents? 

I'll try a long shot: a common mistake is disabling the service worker. That's my fault: a long time ago I recommended adding the `pdf.worker.js` file to the `scripts` section of the `angular.json`. Removing this files from the `angular.json` gives your application a major performance boost.

**Comment by muuvmuuv** [comment]
Well, just commenting here too because I had a similar issue (described here #965). We wrapped this lib into a component which hasn't set `changeDetection: ChangeDetectionStrategy.OnPush`, so this was the problem because Angular just ran into an infinite loop of CDR. I suggest you to try the same and look if you have range-requests disabled: https://pdfviewer.net/extended-pdf-viewer/range-requests

**Comment by aysha-statvalu** [comment]
changeDetection: ChangeDetectionStrategy.OnPush not working please help me one thing if a pdf have more than 5000 pages please show single page at a time not 5000 pages at a time please add this feature please help.

**Comment by muuvmuuv** [comment]
@aysha-statvalu this feature is already implemented and called "range-requests". Is is also **enabled by default**. Read my comment again. Do you have disabled it? Check your website's network tab in chrome's dev-tools. If you see just one pdf requested then you have disabled it or an old version of *ngx-extended-pdf-viewer*.

**Comment by aysha-statvalu** [comment]
please add input property like [showAll]= false like ng2-pdf-viewer has it will enhance performance. Range request not working at all. Rendering 33000 pages are the issue, it's creating a performance issue.

**Comment by stephanrauh** [comment]
> Rendering 33000 pages are the issue,

No, it's not. The PDF viewer renders only a few pages in advance. Unless you implement a custom pre-rendering strategy, that's two pages in advance at most.

**Comment by stephanrauh** [comment]
Did you already discover the single-page mode? https://pdfviewer.net/extended-pdf-viewer/page-view-mode 

That's pretty much the same as `[showAll]="false"`. However, what I will not do is writing a new renderer. ngx-extended-pdf-viewer is the PDF viewer of Firefox, plus a few improvements, re-packaged so it supports Angular. I won't re-implement the Firefox PDF viewer from scratch. I agree it has some limitations, and I'm sure it was never meant to display more than a few thousand pages.

I suggest you double-check if you're using range requests, examine your application for performance leaks, and use the single-page mode.

**Comment by aysha-statvalu** [comment]
pageViewMode="single", This input property saved my life Thank u from my bottom of my heart.

**Comment by stephanrauh** [comment]
Oh, is it really that simple? You're welcome! BTW, kudos to @muuvmuuv who made me realize you might have missed the single-page mode. Ayesha, if you've got an idea how I can document it better or how to empower developers to find the feature faster, just tell me.

As for the lagging zoom: to be honest, I'm clueless. But I'm ready to investigate the topic. But not now: unless I find a sponsor who pays me for working on ngx-extended-pdf-viewer during business hours, it's a leisure-time project, and every once in a while my family life requires me to be there for them.

**Comment by elvisgraho** [comment]
> @elvisgraho Can you tell me something about the size of your PDF documents?
> 
> I'll try a long shot: a common mistake is disabling the service worker. That's my fault: a long time ago I recommended adding the `pdf.worker.js` file to the `scripts` section of the `angular.json`. Removing this files from the `angular.json` gives your application a major performance boost.

I just used random adobe pdf from the web with 978 pages to test. It is 9 mb 
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf

**Comment by elvisgraho** [comment]
pageViewMode="single" fixed issue performance issue for me too. Now I have a weird problem where the page sticks to the left side of the screen no matter how I zoom, instead of it beeing in the middle.

**Comment by elvisgraho** [comment]
![viewer](https://user-images.githubusercontent.com/42517259/140485433-ff00cc58-120a-4381-96de-74e421f3ba0d.png)

**Comment by aysha-statvalu** [comment]
> pageViewMode="single" fixed issue performance issue for me too. Now I have a weird problem where the page sticks to the left side of the screen no matter how I zoom, instead of it beeing in the middle.

Do one thing paste this code in your global style.css 
#viewerContainer {
    text-align: center;
}

and try open chrome devtools and pick classes from there and add your own style simple and easy.

**Comment by aysha-statvalu** [comment]
@elvisgraho there is an another package called https://www.npmjs.com/package/ng2-pdf-viewer it has no performance issue try it.

**Comment by stephanrauh** [comment]
I've got a couple of ideas how to improve the performance. You can implement one of them already now in your project.

Open the file `polyfills.ts` and scroll down to `import 'zone.js'`. Add this line:

```typescript
(window as any).__Zone_disable_requestAnimationFrame = true; // << NEW NEW NEW :)
 import 'zone.js';  // Included with Angular CLI.
```

That's only a small performance boost, but I'm positive you'll notice it.

Chances are I'm able to release some more brakes soon. Stay tuned!

**Comment by aysha-statvalu** [comment]
thank you thank you thank you now scroll bar issue is fixed, now scroll scrollbar not lagging working fine. But ****One Issue still remaining while Clicking on zoom in, zoom out button its lagging performing slow.****

**Comment by stephanrauh** [comment]
Interesting. I still see hundreds of useless change detections, so I didn't expect the tiny improvement to have such an impact. I'm glad to able to help!

**Comment by stephanrauh** [comment]
After analyzing the performance today, I'm developing a different theory what's causing the problem. pdf.js generates an empty `<div>` for each thumbnail and each page. That's 26468 empty divs, and probably quite a challenge for both the V8 engine and the rendering engine.

I'm not sure I want to fix this, but I've decided to investigate the topic. If there's an easy way without risking to break future compatibility to pdf.js, I'll do it.

BTW, you may be interested in using the new scrollmode of pdf.js. It's pretty much the same as my `[pageViewMode]="'single'"`, but developed independently by the pdf.js team.

**Comment by aysha-statvalu** [comment]
in single view performance is great for rendering pdfs the only issue is on click zoom in, out button it's lagging that thing should only have to fix. On pdftron website if you see they are also doing the same thing single page mode for large documents and thank god we have that feature.

**Comment by stephanrauh** [comment]
@aysha-statvalu Did you already try the new `[scrollMode]="3"`? It's been developed by the pdf.js team, so chance are they deliver superior performance. The new feature is currently only available in the "bleeding edge" branch of the 11.0.0-alpha versions.

**Comment by muuvmuuv** [comment]
> After analyzing the performance today, I'm developing a different theory what's causing the problem. pdf.js generates an empty <div> for each thumbnail and each page. That's 26468 empty divs, and probably quite a challenge for both the V8 engine and the rendering engine.

Now I know why the change detection strategy "on push" fixed it for me xD this is insane haha

Thanks for the zone trick. We already disabled a few must see if this one breaks any other feature.

**Comment by aysha-statvalu** [comment]
> @aysha-statvalu Did you already try the new `[scrollMode]="3"`? It's been developed by the pdf.js team, so chance are they deliver superior performance. The new feature is currently only available in the "bleeding edge" branch of the 11.0.0-alpha versions.

i am using angular v12 can i use this "bleeding edge" branch.

**Comment by stephanrauh** [comment]
Yes, of course. The difference between the "assets" branch (which is the default) and the "bleeding edge" branch is it's using a different version of pdf.js. That's nothing to do with the Angular version.

As you've already reported in another ticket, the current version of ngx-extended-pdf-viewer requires RxJS 7, which isn't the default setting of Angular 12 projects. I believe you can update to RxJS 7. Alternatively, wait until I've published the next alpha version. I intend to lower the requirements to RxJS 6.

**Comment by stephanrauh** [comment]
Starting with version 11.0.0-alpha.3, my custom single-page-mode has been replaced by `[scrollMode]="3"`, provided you're running pdf.js 2.12 or higher. That should solve the issue.
